### ISSUE TITLE
Remove Federation Hosting Select Box

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#100]
Federation Hosting feature should be removed.  This is old and will not be supported in its current form. The select and any backend components should be removed.

**Comment by nynymike** [comment]
![federation_hosting](https://cloud.githubusercontent.com/assets/3717101/9334140/e7d82ccc-4592-11e5-9c2c-c08915001b82.png)

**Comment by yurem** [comment]
We also need to clean up LDAP schema and code.

**Comment by rahatjaan** [comment]
removed from UI
