### ISSUE TITLE
Managing a user record: nav highlighted should be "Manage People"

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1003]
When managing a user record, the left column nav should show "Manage People" highlighted. 

Currently when editing an existing user record, the nav shows you in "Add People" (see screenshot). This is a little confusing, as you are not adding a new user, you are managing an existing record. 

![image](https://user-images.githubusercontent.com/5271048/40989674-2e689c8e-68b4-11e8-80d4-53bbd9759645.png)

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/41170140-bb5e8caa-6b68-11e8-92c3-b1a73e590c72.png)
