### ISSUE TITLE
The notification bubble that appears after updating the manage authentication seems a little off

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1012]
# Description
On clicking update it says **Person Authentication configuration successfully updated**  which is misleading as the current item is **Manage authentication**.

# Steps to reproduce:

1. Login into Gluu Admin Ui
1. Navigate to **Configuration** > **Manage authentication**
1. Select any tab and apply some changes
1. Click on **Update** button

**Comment by syntrydy** [comment]
I guess  a message lik this ** system authentication settings successfully updated ** is correct

**Comment by syntrydy** [comment]
@willow9886 May be you have best test description for this situation.

**Comment by willow9886** [comment]
@syntrydy yes, agreed with your updated message:

> System authentication settings successfully updated.
