### ISSUE TITLE
Ability to Disable Gathering Of Metrics

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#1014]
Gathering metrics for Gluu Server into LDAP to display in oxTrust is sometimes unnecessary and unwieldy, requiring writes to LDAP for no discernible reason. There should be an option to disable metric gather.

**Comment by yurem** [comment]
Implemented. In current oxAuth/oxTrust there is new parameter "metricReporterEnabled" in JSON configu to enable/disable metric persistence.

Admin can change this value without server restart.

**Comment by natt-tester** [comment]
@yurem, when I disabled the "metricReporterEnabled" and tested blocked login, it generated a lot of data displayed later in the metrics: the login values rose from 90/62 (successful/failed login) to 102/87 and counting. 

**I did not restart the server, as you said it wasn't necessary.**

This was the setup on c7:
 
<img width="789" alt="metrics" src="https://user-images.githubusercontent.com/38302725/45855636-68735b00-bd94-11e8-8b4b-d376ec25a669.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45953312-8ee9fe00-c001-11e8-8233-38e60563becc.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45953372-be990600-c001-11e8-9894-08a12e5900bc.png)
