### ISSUE TITLE
New redis configuration ssl parameters support

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1018]
Now on oxcore we have two more properties for SSL support:
* useSsl
* useTrustStoreFilePath.

See class here https://github.com/GluuFederation/oxCore/blob/5437b4200076eef81f43fa19e63989f1b8acbd43/oxService/src/main/java/org/xdi/service/cache/RedisConfiguration.java#L11

We need to support them on UI.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxCore/issues/50

**Comment by afroDC** [comment]
Once implemented and 3.1.4 packages go out for testing, I'll check functionality.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/41820258-83b666b6-77ec-11e8-8985-07f68b583b9e.png)

**Comment by shekhar16** [comment]
@yuriyz  Please check it and let me know if you need anything more in this issue?

**Comment by afroDC** [comment]
@shekhar16 I think we should change `useSsl` to `useSSL`.

**Comment by shekhar16** [comment]
@yuriyz  we had implemented it with jsoneditor.js which doesn't provide hide/show on change functionality.

**Comment by yuriyz** [comment]
got it, it's not critical anyway.

**Comment by sahiliamsso** [comment]
what is the purpose of highlighted labels as name is same as field name
![image](https://user-images.githubusercontent.com/21104811/44125385-f07e125e-a04f-11e8-99d2-11ece19fa9f8.png)

**Comment by natt-tester** [comment]
> @shekhar16 I think we should change `useSsl` to `useSSL`.

The string is unchanged in RC4, please follow @afroDC's idea

 
<img width="1107" alt="ssl" src="https://user-images.githubusercontent.com/38302725/45422220-ea97bb80-b6d2-11e8-9ed3-fc6b80192516.png">

**Comment by afroDC** [comment]
@sahiliamsso is right and that field, `sslTrustStoreFilePath`, should have the caption read `Directory Path to Trust Store`

Also the caption under `useSSL` should read `Enable SSL communication between Gluu Server and Redis cache`

**Comment by shekhar16** [comment]
@yuriyz  if I m going to change the label useSsl to useSSL than we need to change in oxauth code aswel.
because label should be same as Json attribute in oxtrust json editor.

@sahiliamsso @afroDC  @natt-tester Once @yuriyz confirms the changes than only we can change the label otherwise it will break the functionality.

I updated the caption. here is screenshot.

![image](https://user-images.githubusercontent.com/15937500/45593799-a7c43500-b9ab-11e8-8186-f2dde66b30e3.png)

**Comment by yuriyz** [comment]
@shekhar16 changed in oxCore 3.1.4 and 4.0.0 (thus in oxauth too).

**Comment by yuriyz** [comment]
change `name` in oxTrust too. It should be available for validation in RC7 (3.1.4)
