### ISSUE TITLE
Add clientID and clientSecret rows by  default in passport

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1020]
In form at  Configuration > Manage Authentication > Passport Authentication method

when the "add  strategy" button is pressed we need to show two rows. One for *clientID* and another for *clientSecret* with empty values on the right hand side (or maybe a text indicating that they need to be filled).

This helps us making clearer how to add a new strategy (since clientID/secret are required for any social strategy to work).

**Comment by syntrydy** [comment]
I think the left side shouldn't be editable, Also both field shouldn't be removable like other custom field.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/41927944-92347176-796b-11e8-986c-cce05fbf61ad.png)

**Comment by jgomer2001** [comment]
@syntrydy I merged your PR #1023, can you copy your work to master as well?

**Comment by syntrydy** [comment]
@yurem  will merge 3.1.4 in master after the final release, so  i don't think it is necessary to copy every work to master right now.
