### ISSUE TITLE
Lists at "Manage Sector Identifiers" pages are skewed

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1027]
Environment:
Ubuntu 14.04, Gluu CE 3.1.3

Lists at "OpenID Connect -> Manage Sector Identifiers -> Add Sector Identifier" have the same issue as described in [this report](https://github.com/GluuFederation/oxTrust/issues/858):
![sector_id_page_list_bug](https://user-images.githubusercontent.com/11802046/42184474-59fc0e3a-7e4e-11e8-8efb-97d6578cb785.png)

**Comment by natt-tester** [comment]
Agreed, it's done.

**Comment by natt-tester** [comment]
@shekhar16, I see now that it's better to make the rows a bit longer -- preferably as long as the ones in the first column -- to avoid situations like this one:

<img width="802" alt="ubuntu14_rc2_longer-table" src="https://user-images.githubusercontent.com/38302725/45158371-1b857580-b227-11e8-925f-02eeede4a157.png">

Tested with RC2 in Ubuntu 14/Firefox.

**Comment by syntrydy** [comment]
Before
![image](https://user-images.githubusercontent.com/7513418/45160287-fd952200-b1e0-11e8-96b3-4852d4eab153.png)

After

![image](https://user-images.githubusercontent.com/7513418/45160477-772d1000-b1e1-11e8-8f2f-acfb1d54f89e.png)
