### ISSUE TITLE
Unable to download shibboleth2 files from 'Generate' TR method

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#103]
IDP is throwing error `Failed to prepare Shibboleth2 configuration files for download` whenever going to download 'Shibboleth2.zip' from Trust Relationship created with 'Generate' method. 

* How to reproduce the issue: 
- Go to SAML -> Trust Relationship
- 'Add new Trust Relationship'
- 'Metadata Type: Generate' 
- URL: anything is fine. i.e. https://test.test.com
- Keep other feature as it is now. 
- Add this trust relationship. 
- After creating this Trust, try to download it's files which were generated by IDP ( Screenshot attached ). 
- Error. 

Screenshot: 

![screen shot 2015-08-25 at 6 19 19 am](https://cloud.githubusercontent.com/assets/7156097/9465503/ca363776-4af2-11e5-9709-5a1043fd2a44.png)

Main problem from log:

    INFO   | jvm 1    | 2015/08/25 11:18:46 | 2015-08-25 11:18:46,598 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to add WEB-INF/resources/doc/README_SP.pdf to zip

Full stack trace: 

    INFO   | jvm 1    | 2015/08/25 11:18:46 | 2015-08-25 11:18:46,596 ERROR [org.xdi.util.io.ResponseHelper] Failed to add resource README_SP.pdf to zip archive
    INFO   | jvm 1    | 2015/08/25 11:18:46 | java.lang.NullPointerException
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744) 
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.xdi.util.io.ResponseHelper.addInputStream(ResponseHelper.java:164)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.xdi.util.io.ResponseHelper.addResourceToZip(ResponseHelper.java:149)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.downloadConfiguration(UpdateTrustRelationshipAction.java:889)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at java.lang.reflect.Method.invoke(Method.java:606)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.security.SecurityInterceptor.aroundInvoke(SecurityInterceptor.java:163)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.gluu.oxtrust.action.UpdateTrustRelationshipAction_$$_javassist_seam_58.downloadConfiguration(UpdateTrustRelationshipAction_$$_javassist_seam_58.java)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at java.lang.reflect.Method.invoke(Method.java:606)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335)
  INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:348)
  INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.el.parser.AstPropertySuffix.invoke(AstPropertySuffix.java:58)
  INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.el.parser.AstValue.invoke(AstValue.java:96)
  INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)
  INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.core.Expressions$2.invoke(Expressions.java:222)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.navigation.Page.preRender(Page.java:311)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.navigation.Pages.preRender(Pages.java:351)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.jsf.SeamPhaseListener.preRenderPage(SeamPhaseListener.java:565)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.jsf.SeamPhaseListener.beforeRenderResponse(SeamPhaseListener.java:476)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.jsf.SeamPhaseListener.beforeServletPhase(SeamPhaseListener.java:147)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.jsf.SeamPhaseListener.beforePhase(SeamPhaseListener.java:117)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:228)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:99)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 	at java.lang.Thread.run(Thread.java:745)
   INFO   | jvm 1    | 2015/08/25 11:18:46 | 2015-08-25 11:18:46,598 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to add WEB-INF/resources/doc/README_SP.pdf to zip

**Comment by nynymike** [comment]
Rahat, this bug is really problematic. Its a really important feature. Can you take a quick look at this?

**Comment by alinawazbscs** [comment]
do we need to fix it in New GUI?

**Comment by yurem** [comment]
I added missign resource/
Zico, Can you add TR to http://ce-release.gluu.org in order to retest this issue.

**Comment by nynymike** [comment]
No its still not working on ce-release...

**Comment by dmogn** [comment]
It now works with fresh build from Git.

**Comment by yurem** [comment]
For me it also works fine in CE 2.3.4 on our testing data with sample TR. But I can't load another TR which I added manually. Probably the bug in another place. But on CE 2.4.0 I can't open TR for editing. I'm going to reopen it to double check on ce-release.gluu.org

**Comment by nynymike** [comment]
This is still broken for me....

![image](https://cloud.githubusercontent.com/assets/3717101/9964647/3169c3ce-5df7-11e5-9381-d563b971f7cc.png)

When I try to generate a TR using generate, it asks me for a valid SP URL when I hit submit. But the whole point of Generate is the SP doesn't exist yet.

**Comment by yurem** [comment]
Why URL  should be not mandatory? SP metadata contains specified URL. How to generate this file if this property is empty?

**Comment by mzico** [comment]
@nynymike @yurem : I think we need SP URL to generate configuration files and SAML certificate.

**Comment by yurem** [comment]
Closing it...
