### ISSUE TITLE
Bug: can't edit added scopes on ce-dev6

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1031]
Please refer to the GIF: the majority of the added scopes can't be edited. When you create an entirely new scope, it can be edited.

![2018-07-05_19h16_31](https://user-images.githubusercontent.com/38302725/42315407-b6014144-808a-11e8-91c7-2fbfc79b1325.gif)

**Comment by syntrydy** [comment]
@natt-tester i tested that on other servers and there is no issue. May be ce-dev6  has been mess up.

**Comment by syntrydy** [comment]
@natt-tester, please test this on 3.1.4
