### ISSUE TITLE
Error message on logout from client side

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1033]
Based on [this](https://support.gluu.org/single-sign-on/5559/error-message-on-logout/) ticket, User gets below error message on logout.

Error Message:
{“error”:”invalid_grant”,”error_description”:”The provided access token is invalid, or was issued to another client.”}

This is reproducible in gluu idp 2.4.4 as well, and seems to happen anytime there is a cookie in the browser i.e. on incognito browser, User can login/logout fine for the first time. Any subsequent logout attempt throws this error

Flow -
1. Client calls OP and gets “code” back -> successful login
2. Client logs out and call end_session with id_token_hint
3. At this point logout is successful and user login to get the “code” back -> successful login
4. User clicks logout and call end_session with the same id_token_hint from previous session which is already expired.

Expected behavior - Client has to fetch NEW id_token and then present that new id_token as id_token_hint to /end_session.

**Comment by mzico** [comment]
@qbert2k : Any thought on this?

**Comment by qbert2k** [comment]
Please check whether it is the same as issue oxAuth-371:
https://github.com/GluuFederation/oxAuth/issues/371

**Comment by mzico** [comment]
@sahiliamsso : It is. I think it's expected behavior... check out @qbert2k 's last comment there in https://github.com/GluuFederation/oxAuth/issues/371.

**Comment by shekhar16** [comment]
@mzico can we close this issue?

**Comment by mzico** [comment]
We can close it.
