### ISSUE TITLE
'Authentication Requests' graph should only include oxAuth authentication

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1034]
Seems like in clustered setup ( when there are multiple LDAP servers included and all of them are replicated ), 'Authentication Requests' graph is including some other 'authentication attempts' ( i.e. one ldap server is logging into another ldap server to mirror changed data ) along with user authentications. 

![handful_of_authentications](https://user-images.githubusercontent.com/7156097/42440378-35b429fe-832b-11e8-9930-b6f74c1f22df.png)

This graph should log only user authentication ( human ) attempts.

**Comment by yurem** [comment]
@mzico do you have testing data to reproduce this? Or how to reproduce it?

**Comment by yurem** [comment]
@mzico Did you see same issue in 3.1.4?
In 3.1.4 we fixed issue which might led to this issue. In CE < 3.1.4 oxTrust and oxAuth both save statistic in oxAuth branch. In 3.1.4 we fixed this.

**Comment by yurem** [comment]
@mzico Is it still work not well? we applied few fixes related to metrics in 3.1.4/3.1.5 Can you check it in 3.1.5 recent beta?
