### ISSUE TITLE
Remove requiredness for streetAddress in scim

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1037]
Subattribute `addresses.streetAddress` is flagged required. This is too strict in practice, since users of service may like having addresses consisting of (type, country, postalcode) or very simple bits of data (`streetAddress` being the most specific)

**Comment by natt-tester** [comment]
I've successfully created a user through SCIM with no streetAddress: 
![2018-08-09_19h55_08](https://user-images.githubusercontent.com/38302725/43892244-c3e11268-9c0e-11e8-85c3-859536c23dba.png)
I agree it's done.
