### ISSUE TITLE
New custom script type to pull data from RDBMS and other sources

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#104]
Currently CR allows to sync users with LDAP server only. I think we can add new custom script type with 1 method:
List<GluuSimplePerson> loadSourceServerEntries(return_attributs, conf, etc)

In this method customer can implement logic to get data from RDBMS, MySQL, etc..
CR doesn't require major changes. For CR perspective instead of loading data from LDAP custom script method will return data need to finish iteration.

After that customers can add simple authentication script which will do authentication against RDBMS instead of AD LDAP.

**Comment by aliaksander-samuseu** [comment]
@yurem, do we really need a separate tab for that? Mb it's possible to add another function user can redefine to the current CR's class(es), which, if implemented by user, will took over/override the part of CR's functionality responsible for getting data from LDAP, while not touching the other its parts? It just would appear more intuitive, imo, so easier to document and explain to users :) If it doesn't over-complicate things from app architecture's point of view, of course.

**Comment by yurem** [comment]
@aliaksander-samuseu where did you find something about UI in issue description?
I offered to add method to CR script:

    loadSourceServerEntries(return_attributs, conf, etc)

It's will be enough to implement any other source data loading mechanism.

**Comment by nynymike** [comment]
Re-open if customer demand increases.
