### ISSUE TITLE
Pretty Print OpenID Client Config

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#1040]
The client form is so long, it's impossible to get a screenshot. It would be nice if we had a "Config Summary" button at the top, which prints a condensed summary of the configuration for the client, omitting any empty values. This would help the support team to ask customers to share their client config.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/43369458-53b2674c-938c-11e8-81f5-97ec7caab6b6.png)

**Comment by natt-tester** [comment]
@shekhar16, I see that there's a button included in the client summary -- I think it's obsolete, could you remove it? 

I think the only button we could need here would be a "Copy All" button as ctrl+a copies everything, also beyond the pop-up. To make the copying convenient, we either need to set boundaries for the pop-up only, or add a button to do that. Can it be done?

Also, the header font looks a bit blurry to me. Could you make it sharper?

![2018-08-10_17h58_03](https://user-images.githubusercontent.com/38302725/43946137-c4d37f4e-9cc7-11e8-81e3-802a343cccf2.png)

**Comment by shekhar16** [comment]
@natt-tester  I removed the button from summary popup.
For header and boundaries, we have a defined UI theme,  all dialogues/popup's designs are similar .We have header in bold font for all popups.

**Comment by shekhar16** [comment]
here is latest screen shot of my fix.
![image](https://user-images.githubusercontent.com/15937500/44004379-817e4f62-9e7f-11e8-943f-55cbdbbb260a.png)

**Comment by syntrydy** [comment]
@shekhar16, i think you work break some feature on that page:

Before you change, the scopes was added to the form one after another as the user pick then from the DialogBox, currently all added are visible only when the user hit the **update button**.

**Comment by shekhar16** [comment]
@yurem  I think primfaces and richfaces libs are conflicting on this page.

**Comment by shekhar16** [comment]
@yurem please merge the PR https://github.com/GluuFederation/oxTrust/pull/1161

**Comment by natt-tester** [comment]
@nynymike said if would be nice to have the Client Config Summary at the top, but now it's at the bottom. @shekhar16, could you move it to the top? The UX would be better if the user didn't have to scroll all the way down to click the button. 
<img width="1231" alt="bottom_button" src="https://user-images.githubusercontent.com/38302725/45156741-5f29b080-b222-11e8-86df-29f0aa35be5a.png">

Apart from that, it's done and the details are printed correctly:
![client_config](https://user-images.githubusercontent.com/38302725/45156719-533dee80-b222-11e8-8b0c-db3e40fbc8bb.png)

**Comment by syntrydy** [comment]
@natt-tester Already fixed.

![image](https://user-images.githubusercontent.com/7513418/45159733-81e6a580-b1df-11e8-964d-c0e3819b239c.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45513172-dff42980-b799-11e8-9492-acbb55c74b9d.png)

**Comment by syntrydy** [comment]
May be your browser need QA ahhahaha.

**Comment by natt-tester** [comment]
> May be your browser need QA ahhahaha.

I'm checking c7.gluu.org and it looks the same as I reported. Must be the 15" Mac screen, then!

**Comment by willow9886** [comment]
> Must be the 15" Mac screen, then!

The UI should be responsive.. 15" is a fairly large screen size. It should look OK... can you confirm @syntrydy  ? Do we need to make any additional fixes for the next RC?
