### ISSUE TITLE
oxTrust Auditing

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#1041]
oxTrust could benefit by having some auditing feature where it logs any LDAP changes it makes. For example, if you add or delete a user in oxTrust, there is no log of that activity or what specifically was deleted. The add and delete action can be viewed in LDAP but it doesn't give any identifying information of what that entry was. 

I'm going to assume this is true of almost all interactions between oxTrust and LDAP. An audit log of these actions would surely benefit on a small scale for general administration.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44095395-98b4e61c-9fd0-11e8-896e-14a8380b6a38.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44264235-b804bb00-a219-11e8-9ce9-0e82894fb80c.png)
