### ISSUE TITLE
Manage LDAP Authentication duplicated name

### ISSUE THREAD

**Issue by earezki** [GluuFederation/oxTrust#1043]
When creating a new source ldap server, the names of the other servers is the same as the first one.

Steps to reproduce:
1. Open oxTrust backoffice.
2. Go to Configuration => Manage Authentication => Manage LDAP Authentication.
3. Click "Add source LDAP server" at the bottom.
4. Fill in the form then Update.
5. Observe the new ldap server.

![image](https://user-images.githubusercontent.com/11857979/42867448-8df04452-8a67-11e8-99bd-aff3ebdde070.png)

**Comment by natt-tester** [comment]
I can't reproduce  it and agree it's fixed.
