### ISSUE TITLE
Manage LDAP Authentication cannot remove ldap servers

### ISSUE THREAD

**Issue by earezki** [GluuFederation/oxTrust#1044]
When creating a new source ldap server, there is no way to remove it from the UI.

Steps to reproduce:

1. Open oxTrust backoffice.
2. Go to Configuration => Manage Authentication => Manage LDAP Authentication.
3. Click "Add source LDAP server" at the bottom.
4. Fill in the form then Update.
5. Try to remove the newly added server.

**Comment by syntrydy** [comment]
The remove button is still not visible. Noted the gap at the left side of the screenshot.
![image](https://user-images.githubusercontent.com/7513418/43147674-7b49782a-8f5b-11e8-9fa3-0a7072681cee.png)

**Comment by earezki** [comment]
Please make sure your branch is Master.
The delete button is at the top right.
As for the gap it has always been there, what is the issue with it ?
![image](https://user-images.githubusercontent.com/11857979/43150616-407fa208-8f62-11e8-93d9-80709a5db688.png)

**Comment by syntrydy** [comment]
I know what is the problem. I will fix it when i have some time.
