### ISSUE TITLE
The button to remove Source Ldap Server under LDAP Manage Authentication don't shows up on every screen.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1048]
# Description
The button to remove Source Ldap Server under LDAP Manage Authentication don't shows up every screen.

On large screen the button is visible but not on small screen(Lenovo X1 Carbon for example).

Even when the button is visible, it is not at the best position on the screen.
![image](https://user-images.githubusercontent.com/11857979/43150616-407fa208-8f62-11e8-93d9-80709a5db688.png)

I guess a button like the one on the below screenshot should be good:
![image](https://user-images.githubusercontent.com/7513418/43184661-40dc9150-8fe1-11e8-989e-932b76a97986.png)

**Comment by syntrydy** [comment]
The end result looks like this
![image](https://user-images.githubusercontent.com/7513418/43189191-eb383c92-8fed-11e8-8fc4-2fd97131d90e.png)

**Comment by syntrydy** [comment]
Sorry, the first commit is not present here because i forgot to add the issue number in commit message.

**Comment by earezki** [comment]
This PR seem to be only merged in 3.1.4.
Would you please check and merge in Master as well ?
Thanks

**Comment by syntrydy** [comment]
The 3.1.4 will be merged in master just before the release.

**Comment by natt-tester** [comment]
I've tested the behavior of the button and it's a bit off. Please fix it:
![2018-08-07_20h10_35](https://user-images.githubusercontent.com/38302725/43769988-6ce2a85a-9a7e-11e8-864d-e784708eb644.gif)

**Comment by natt-tester** [comment]
@syntrydy, the buttons still show the same behavior -- tested in Ubuntu16, RC2. Maybe the change hasn't been merged?

![bad button](https://user-images.githubusercontent.com/38302725/45151092-c2aae280-b210-11e8-9fa8-c49ff99409c7.gif)
![bad_button2](https://user-images.githubusercontent.com/38302725/45151202-01d93380-b211-11e8-8b87-a90320e4a528.gif)
