### ISSUE TITLE
Validate contact values entered in openID clients form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1051]
According to [spec](http://openid.net/specs/openid-connect-registration-1_0.html):

>contacts: Array of e-mail addresses of people responsible for this Client.

When pressing the "add contact" button at the bottom, one can enter any string, we should validate it is an e-mail actually:
![not_an_email](https://user-images.githubusercontent.com/5444180/43223567-1e6bbd34-9019-11e8-94fd-001774fbc1b9.png)

**Comment by syntrydy** [comment]
I added a contact validator that ignore pick up just the valid email but that occurs when the save button is pressed. It is correct for you @jgomer2001 ?

**Comment by natt-tester** [comment]
It works as @syntrydy described: any string can be saved as an e-mail address, but upon clicking Add/Update it's removed and an error message is displayed:

<img width="852" alt="mail1" src="https://user-images.githubusercontent.com/38302725/45149701-8de95c00-b20d-11e8-94f8-f545be394254.png">
<img width="1407" alt="mail2" src="https://user-images.githubusercontent.com/38302725/45149744-a48fb300-b20d-11e8-9578-d12e87e716d3.png">
