### ISSUE TITLE
Remove Level feature from Cache Refresh config

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1056]
![image](https://user-images.githubusercontent.com/5271048/43541147-453c845e-958f-11e8-92ad-b25b1b092541.png)

Can you remove the `Level` field? Feature can simply be hidden. We don't need it any longer.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/43545668-6e633a64-95ce-11e8-9d76-3a54518f5b24.png)
