### ISSUE TITLE
Add GUI to show rate metrics and all counter metrics

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#106]
oxAuth currently gather next metrics: user_authentication_success, user_authentication_failure, user_authentication_rate, dynamic_client_registration_rate.
First 2 metrics contains just numeric value:
{"count":1}
Rate metrics looks like:
{"count":2,"meanRate":6.488439892715768E-4,"oneMinuteRate":1.2095845996399209E-23,"fiveMinuteRate":7.192343502873298E-6,"fifteenMinuteRate":0.006601105395911883,"rateUnit":"second",
"min":39.364784,"max":42.685147,"mean":41.17397971371821,"stdDev":1.653480383026116,"median":42.685147,
"value75thPercentile":42.685147,"value95thPercentile":42.685147,"value98thPercentile":42.685147,"value99thPercentile":42.685147,"value999thPercentile":42.685147,"durationUnit":"milliseconds"}

Rate metrics are good for analysis. For example value99thPercentile allows to see more accurate authentication statistic without extreme cases.

We need add GUI to show rate metrics and all counter metrics. Admin should able to: select period, select appliance, select rate metric, specify which values to show.

**Comment by nynymike** [comment]
Not a huge priority. Let's wait for more customer demand.
