### ISSUE TITLE
add search to oxtrust attribute page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1061]
People should be able to search through their available attributes in oxTrust. Please add.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/43638426-b092204c-9710-11e8-89e6-e1bf0c560c20.png)

![image](https://user-images.githubusercontent.com/7513418/43638450-d262bbc8-9710-11e8-968e-ad6ee11d68ae.png)

**Comment by shekhar16** [comment]
@syntrydy I also done this issue please let me know if u r doing the  issue.It will make conflict in repo for same issue.

**Comment by shekhar16** [comment]
@syntrydy I also done this issue please let me know if u r doing the  issue.It will make conflict in repo for same issue.
