### ISSUE TITLE
Password Reset page Improvement 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#1066]
After successful password reset, Gluu server redirects to    <Gluu Server>identity/resetPasswordSuccess
Which shows below 

> Please Check your Email for Password Reset Link
> Thank you for usingGLUU.

It will be good if we can make below changes.

1- Thank you for **usingGLUU** cane be Thank you for **using GLUU**
2- Add one link which will allow user to navigate to login page

Gluu server 3.1.3

**Comment by nynymike** [comment]
Casa would be the preferred way to implement password reset, not oxTrust.
