### ISSUE TITLE
Reset password form should has captcha

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1071]
We need to apply few changes to user reset functionality:

1. We need to add captcha validation to password reset form.
  - oxTrust should display current form without captcha if admin decided to not enable it (current flow)
  - Show captcha if admin activated captcha config
2. Remove section of [code](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/PasswordReminderAction.java#L210) which send mail to not register e-mails. We also need to remove related messages from message resource files.
3. Update message which we show after password reset `If this email is associated with a user account in our system, you will receive an email with instructions to reset your password.`

**Comment by yurem** [comment]
This issue depends on https://github.com/GluuFederation/oxTrust/issues/1072

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/44158049-85e84180-a0d1-11e8-9f7e-ab5a90d0316c.png)

**Comment by shekhar16** [comment]
@yurem  we already have captcha functionality in resetpassword and passwordreminder page.

**Comment by shekhar16** [comment]
@yurem can we close https://github.com/GluuFederation/oxTrust/issues/356 issue same as this one.

**Comment by willow9886** [comment]
@shekhar16 there's no reason to take someone to a dedicated page with this text.. it should simply be a note on the password reset page.

**Comment by shekhar16** [comment]
@willow9886 sorry it was misunderstand by me, #356 is for email content and this one is for portal success page, so there is no relation in 356 and this one.
Please ignore my above comment.

**Comment by shekhar16** [comment]
@willow9886  i agree  ,I think 356 is related to mail content different from this one.

**Comment by willow9886** [comment]
@shekhar16 yes, #356 is the content supplied in the email to the user.

**Comment by natt-tester** [comment]
@yurem, @shekhar16 

 1. Done
**2. Not working correctly: after enabling captcha and sending an email I disabled it as an admin. After waiting a while + clearing cache + restarting oxauth, it's still in the form.:**:

3. I think it's done -- tested with an unregistered email and got no email
4. Not updated in RC4 -- there are too many capital letters and no space marked in the picture. Also, I think a button taking the user back to the login page would be a nice enhancement. What do you think, @willow9886?

**Comment by willow9886** [comment]
> Also, I think a button taking the user back to the login page would be a nice enhancement. What do you think, @willow9886?

The question is can we tell what page they were trying to access, and make sure we send them back to the login page with the right redirect baked in? 

Instead of sending them to a new page that says.. "Please check your email.." wouldn't it be easier to just show a pop up message on the existing page? 

Ideally its a good flow for the user, so something like this:

user --> app --> login (which, after success, would redirect *back* to the app) --> reset password --> click validation email --> set new password --> redirect back to login page with the original redirect URI set

**Comment by natt-tester** [comment]
@shekhar16, there's no need for a new resetPasswordSucces page, just put the message in a pop-up still in passwordReminder.
