### ISSUE TITLE
Move captcha setting to "Manage Authentication" into new tab

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1072]
We need to move fields `Recaptcha Site Key' and `Recaptcha Secret Key` to "Manage Authentication" into new tab Also we need to add checkbox to enable/disable it.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/44002283-eae9caf2-9e5d-11e8-9431-c7b5cd86053b.png)

**Comment by shekhar16** [comment]
we already had these fields on manage registration. So do we need to remove from these text fields from manage registration page.
![image](https://user-images.githubusercontent.com/15937500/44002316-4914bdbc-9e5e-11e8-981d-c2088b3401cd.png)

**Comment by natt-tester** [comment]
@shekhar16, if I understand it correctly, recaptcha should be moved to "Manage Authentication". Now it is there as Captcha Site Key and Captcha Secret Key, so please change the names.

Also, Recaptcha fields are still present in the Manage Registration Page, so please remove them:

<img width="1363" alt="recaptcha" src="https://user-images.githubusercontent.com/38302725/45282681-f478bd80-b51e-11e8-8753-c6d89035ddf0.png">
<img width="1364" alt="captcha" src="https://user-images.githubusercontent.com/38302725/45282696-fe022580-b51e-11e8-973a-6b7c6277ebbc.png">

**Comment by willow9886** [comment]
@natt-tester since and organization might want to use Captcha's on many pages, e.g. registration, login, etc. do you think we should put the Captcha configuration fields in a more top level page, like `Organization Configuration` and then offer a checkbox on configuration pages, like `Authentication` and `Registration` to enable / disable captcha for that specific page?

**Comment by natt-tester** [comment]
> @natt-tester since an organization might want to use Captcha's on many pages, e.g. registration, login, etc. do you think we should put the Captcha configuration fields in a more top level page, like `Organization Configuration` and then offer a checkbox on configuration pages, like `Authentication` and `Registration` to enable / disable captcha for that specific page?

@willow9886 Yes, I think it's a good idea, it will be clearer for the user. @shekhar16, could you implement it?

**Comment by shekhar16** [comment]
@natt-tester  @willow9886  the captcha keys would be same.So we can add enable / disable check boxes for different functionality pages like registration, login, etc.

**Comment by shekhar16** [comment]
Captcha site and key text-boxes are removed from manage registration and authentication configuration page.
only on json configuration page captcha site and key text boxes are visible.here is snapshots
Manage Authentication page:
![image](https://user-images.githubusercontent.com/15937500/45595526-195fab80-b9cb-11e8-94f4-627effd0cf47.png)


Manage registration page .
![image](https://user-images.githubusercontent.com/15937500/45595531-372d1080-b9cb-11e8-9d32-2b28f2e8111e.png)

json configuration : 

![image](https://user-images.githubusercontent.com/15937500/45595546-6c396300-b9cb-11e8-96ed-2439a0c9acfc.png)

**Comment by willow9886** [comment]
@shekhar16 why in manage authentication is the field `Enable Captcha...` and in manage registration the field is `Diasble Captcha...` ? What is the purpose of framing the same question differently in two places?

**Comment by shekhar16** [comment]
@willow9886 checkbox on authentication tab will enable the captcha on passwordreset functionality and  manage registration checkbox will enable it on registration page.

**Comment by shekhar16** [comment]
I changed the label of checkbox to make label consistent in manage authentication and registration
here is screenshot.
![image](https://user-images.githubusercontent.com/15937500/45840137-c91e7b80-bd33-11e8-968d-bcd7d0efef98.png)

**Comment by syntrydy** [comment]
it is okay. Cool @shekhar16
