### ISSUE TITLE
View log tab should show the name of the current log file

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1074]
# Description

In the oxtrust "tail log" view it would be nice if the log file name that you clicked on were also displayed on the tail screen. Once there are several days/mos worth of logs on the "available logs" list it becomes difficult to know which log file you clicked on when bouncing back and forth between screens/tabs/apps

# Steps

1. Login into Gluu Admin  UI
1. Navigate to **Organization configuration** and **View Log**
1. Select **Oxtrust settings**
1. Click one file
1. The **tail tab** is show but there is no way to know which log content is it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/43955709-49b8fe2a-9c99-11e8-8a5e-e2285017920c.png)

![image](https://user-images.githubusercontent.com/7513418/43955722-5934408a-9c99-11e8-9793-9bfbec75ede4.png)

**Comment by natt-tester** [comment]
The enhancement is there, please only correct the typo here: 
<img width="973" alt="no_content" src="https://user-images.githubusercontent.com/38302725/45132128-13034f80-b1d3-11e8-97d3-e327516f81c6.png"> :)

**Comment by natt-tester** [comment]
@syntrydy Now when there' s no content, there's no message:

<img width="744" alt="no_content" src="https://user-images.githubusercontent.com/38302725/45667191-8013cf00-bb5b-11e8-885f-80ff94c9a219.png">
