### ISSUE TITLE
Offer means to create UMA resource and edit associated client

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1077]
In "UMA" > "Resources" > "Resource update"  we are offering a button for deleting. But we don't have means to create a new resource. 

Also in the update page, it would be nice to be able to edit the oxAssociatedClient. Currently this is just a link sending to client details.

**Comment by jgomer2001** [comment]
screenshot
![uma_resources](https://user-images.githubusercontent.com/5444180/44003126-87fd1e5c-9e13-11e8-8f11-9ee7af6778fe.png)

**Comment by shekhar16** [comment]
@jgomer2001 we have functionality to add resource.see below screen shot 
![image](https://user-images.githubusercontent.com/15937500/44145404-045f9adc-a0a9-11e8-95f1-92d6917a6028.png)
also we had functionality to add/remove client.see below screen shot.
![image](https://user-images.githubusercontent.com/15937500/44145435-32646ce6-a0a9-11e8-8589-c9e90260bc5b.png)

**Comment by jgomer2001** [comment]
I see, so was this added for 3.1.4? In 3.1.3 (centos or ubuntu) these buttons are shown.

**Comment by syntrydy** [comment]
Closing this as it is done.
