### ISSUE TITLE
Signal to gluu-flask that Shibboleth XML needs to be pushed to shib nodes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#108]

**Comment by shouro** [comment]
I am looking on a was to share metadata using salt pillar and docker volumes.
one thing is, we can not signal or call gluu-flask api from container.

**Comment by iromli** [comment]
i'm agree with @shouro to take a look at salt pillar first

**Comment by yurem** [comment]
Currently oxTrust put config files to SVN to track configuration files changes. But we can update oxTrust to store config file using other methods.

**Comment by iromli** [comment]
> i'm agree with @shouro to take a look at salt pillar first

Shouro and I have take a look on salt pillar, and apparently it's out of options.

I'm proposing approach to use docker volume to store config files, and script in gluu-flask to monitor them.
We may not need to change oxTrust code or add signal.

**Comment by yurem** [comment]
oxTrust can create file in specific place and name with current data/time. What do you think about this solution? Is this will be enough to signal gluu-flask?

**Comment by iromli** [comment]
gluu-flask v0.4 has a scheduler that monitors events (file addition, modification, etc in all Shib-related files e.g. metadata) in `/opt/idp` directory. Whenever those events occur, gluu-flask will push the files to all Shib nodes.

> oxTrust can create file in specific place and name with current data/time.

What file will be generated by oxTrust?

**Comment by willow9886** [comment]
@iromli can you confirm if this is still an issue?

**Comment by iromli** [comment]
@willow9886 All's good. No need to modify oxTrust code to handle this one at the moment. Gluu Enterprise Edition backend handles the signal.
