### ISSUE TITLE
Email validation in System Configuration

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1090]
It's not a required field, but now any string can be entered and saved as the email address. Please add validation to the field.

<img width="876" alt="email_validation" src="https://user-images.githubusercontent.com/38302725/44068947-ee4d368a-9fbf-11e8-808b-a32a9a9e6356.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44101977-8ee664b6-9fe0-11e8-99a8-e0a244a51f87.png)

**Comment by willow9886** [comment]
I would update the text to:

> Please provide a valid email address.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44198512-89afae80-a139-11e8-92f3-c51191a0688f.png)
