### ISSUE TITLE
Placeholder instead of Build Number

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1091]
In Configuration -> Organization Configuration -> OxTrust Settings there's a placeholder instead of the correct value:

<img width="774" alt="placeholder" src="https://user-images.githubusercontent.com/38302725/44069375-c63906ea-9fc1-11e8-9dbd-cf39b6c5c177.png">

Tested in Ubuntu 14.04, firefox.

**Comment by earezki** [comment]
This env var exists only for Jenkins builds:
![image](https://user-images.githubusercontent.com/11857979/44110345-54778104-9ff7-11e8-9c61-fc31387fc2e5.png)

However, the build date and the build number seem to be only useful for devs and have no use to the end user. Hence, I think we should remove them from the UI.

**Comment by natt-tester** [comment]
@earezki, that's a good way to solve this issue. I'll check it in the new package :)
