### ISSUE TITLE
Improve layout and element design

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1093]
Please refer to the screenshot -- I think we should soon come up with **new button design for drastically better UX**. Now we have both rectangular and rounded buttons, which is inconsistent. I'd suggest changing all to rounded for a fresher look.

We also have **links** to other views which could be easily **overlooked/misclicked**. If we change them to buttons, the layout will look more appealing.

Finally, the **color of buttons** can make more sense. **Red** to indicate **cancel/removal/back** options, and **blue** for **ok/update/addition**.

<img width="1062" alt="button" src="https://user-images.githubusercontent.com/38302725/44081870-29ab1ef8-9ff3-11e8-898b-2db758e3b4ed.png">

Similarly, we should decide what kind of fields we want and stay consistent with the choice. Now we have e.g. **rounded dropdowns** and **rectangular fields**, both in one view:

<img width="862" alt="fields" src="https://user-images.githubusercontent.com/38302725/44082347-47421f74-9ff4-11e8-9db7-f084816a1ec3.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44478695-53d96100-a636-11e8-871a-0e1eba544351.png)

![image](https://user-images.githubusercontent.com/7513418/44478756-808d7880-a636-11e8-9d50-e072bb5a43f6.png)
