### ISSUE TITLE
Gender field should be a dropdown on Profile page, User add/Update Page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1099]
Fix the Label "Gender, male or female:", and input should be a dropdown.
Currently custom text is allowed and saved.

![image](https://user-images.githubusercontent.com/21104811/44122673-973b2c2a-a042-11e8-9993-a12ee384ca96.png)

**Comment by willow9886** [comment]
Agreed. The field should be `Gender:` and the input should be a drop down with options: `male` , `female`

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44209223-bcb66a00-a15a-11e8-8e9b-e13d68650094.png)

**Comment by syntrydy** [comment]
Closing it now

**Comment by sahiliamsso** [comment]
Please fix registration page too
![image](https://user-images.githubusercontent.com/21104811/44612694-fdcc0f80-a827-11e8-967a-3493027e2ff2.png)

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/44612727-4f749a00-a828-11e8-9069-2de36bf98307.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44664588-9969a580-aa0b-11e8-8f01-bdb54bdbca12.png)

**Comment by syntrydy** [comment]
The title read **Gender field on profile page** when  the screenshot is for **User add page**.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45021246-f7f4dc00-b028-11e8-9185-0cdbbf4efc50.png)

The profile page is currently correct.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45051277-9ca00980-b07b-11e8-8190-1f7c0f223841.png)
