### ISSUE TITLE
Hide Client secret on OpenID Connect page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1103]
By default, Client secret for oidc is visible, Please mask it.

![image](https://user-images.githubusercontent.com/21104811/44181374-1bf68900-a11f-11e8-8b87-5f57c9bbadd5.png)

**Comment by earezki** [comment]
Hello,
I'm wondering why would we want to present the secret visible or not.
Can we make the field empty while viewing ?
Thanks,
El Mehdi

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/44231492-f9667d80-a1bb-11e8-9122-1863a5cb3633.png)

**Comment by willow9886** [comment]
@earezki the server admin needs to be able to view and provide the client secret to the developer. Not sure how else it would work? Looks good to me @shekhar16

**Comment by syntrydy** [comment]
@shekhar16  as @willow9886 said, no need to hide the secret field. Can you amend your PR?
