### ISSUE TITLE
[Bug]Custom attribute for which certain access scopes were set becomes inaccessible via web UI for default admin user right after its creation.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#111]
Environment:
Ubuntu 64bit 14.04.3 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.3-1

Preconditions:
1) Fresh installation of CE 2.3.3-1

Steps to reproduce:
1) Log in to oxTrust web UI as default admin user
2) Move to the "Configuration->Attributes" page, click the "Add Attribute" link
3) Use settings as specified below, then click "Add" button:
"Name" : "testtest"
"SAML1 URI" : leave empty
"SAML2 URI" : leave empty
"Display Name" : "testtest"
"Type" : "Text"
"Edit Type" : "user"
"View Type" "user"
"Usage Type" : "Not defined"
"Multivalued" : "True"
"oxAuth claim name"  : "aaaa"
"SCIM Atribute" : "False"
"Description" : "aaaa"
"Enable custom validation for this attribute" : unchecked
"Enable tooltip for this attribute" : unchecked
"Status" : "Active"
4) Return to the "Configuration->Attributes" page again, click "Show All Attributes" link there, and try to find new attribute in the list.

Result:
Attribute cannot be seen in the list of attributes if only "user" value was selected in the "Edit Type" and "View Type" controls. Thus admin user does not have ability to edit or remove it using GUI. The only way to do that is to either remove the attibute object by directly accessing the LDAP db, or to change value of its "gluuAttributeEditType" attribute to "admin" there.
It seems that something not right with this list, as sometimes it's enough to only set one of this controls to "user" to make the attribute disappear right away, and sometimes it won't disappear for a while even when 2 of them set to "user". Please take this into account when attempting to reproduce and try several different combos. In my case, setting both of them to "user" via direct modification of LDAP db worked most of the time instantly, and setting one of them to "admin" again resulted in its appearance in the list right away (see attached picture)

Expected result:
At least the default admin user should have full access to all objects available through web UI, regardless of visibility scopes set for them.

![attrib-dissap](https://cloud.githubusercontent.com/assets/11802046/9750124/7804f5c2-569c-11e5-8dc4-2958a84579e2.png)

**Comment by aliaksander-samuseu** [comment]
Updated Result and Steps sections as issue seems somewhat trickier that it appeared first.

**Comment by aliaksander-samuseu** [comment]
It almost seems like sometimes direct modification of attribute's object in LDAP db being reflected in web UI instantly, and sometimes it doesn't at all for a while, or until some trigger fires (don't know what it is, moving to other page, re-login, restarting service). I also remembering it was acting like this a couple of times when I tried to modify custom attribute's settings via web UI.

**Comment by yurem** [comment]
Fixed. Now user with admin permissions can edit/view attributes all the time
