### ISSUE TITLE
Cache data need to draw graph on home page

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#112]
Mike:
>> It may be better to only load 3 hours worth of data, and let the admin request more when really needed.
We really want oxTrust to be fast...

We can use org.xdi.service.CacheService + define new ehcache type in configuration file.

Lifetime of data in cache can be 2-5 minutes. oxAuth stores metric by default every 5 minutes. Hence there is no sense to read data on every home page show.

**Comment by rahatjaan** [comment]
Cache is enabled for metrics
