### ISSUE TITLE
"Enter your client id here" and "Enter your client secret here" must be placeholders Passport strategies

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1122]
While adding passport strategies  textboxes contains  `Enter your client id here` and `Enter your client secret here` texts, they must be placeholders.
![screenshot_2018-08-21_00-11-05](https://user-images.githubusercontent.com/6398752/44366861-bddaf480-a4d6-11e8-9b10-45b725f1a0b3.png)

**Comment by earezki** [comment]
![image](https://user-images.githubusercontent.com/11857979/44400246-6e321280-a542-11e8-80ae-f141fbac8aca.png)
