### ISSUE TITLE
Register attribute page fields are misaligned

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1137]
Attributes >   Register Attributes 

![image](https://user-images.githubusercontent.com/21104811/44610817-a32cb680-a81b-11e8-82cc-2928ec63bcbb.png)

**Comment by jgomer2001** [comment]
I also want to add that new styles for checkboxes IMO are not very noticeable... it may depend on your screen

For instance, in the cust scripts page, it took me a while to notitce there was a checkbox on the right of  "enabled".
![weird_checkbox](https://user-images.githubusercontent.com/5444180/44619243-efdab680-a848-11e8-8878-62a8b6b26200.png)


Formerly the checkbox was below that,

**Comment by syntrydy** [comment]
Already Fixed
