### ISSUE TITLE
Email validation on Edit profile page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1138]
Please add validation for email already exists (or give standard error in case we don't want to expose existing emails in the ldap) on edit profile page.
It allows to save duplicate emails in LDAP. It causes problem when user authentication is set to email

![image](https://user-images.githubusercontent.com/21104811/44612774-d32e8680-a828-11e8-926c-1f2a27535eb8.png)

**Comment by syntrydy** [comment]
The description is not clear enough
