### ISSUE TITLE
Admin password can be seen when adding person

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1139]
Steps to reproduce in CE 3.1.4

1. Edit admin profile (any field) and press update
1. Try addding a new user (email and password are somehow prefilled)
1. click on the password's eye. It shows the actual admin password

![password_shown](https://user-images.githubusercontent.com/5444180/44619273-4942e580-a849-11e8-97ad-52823d5b1c91.png)

**Comment by syntrydy** [comment]
Not reproducible

**Comment by natt-tester** [comment]
I've just reproduced it in the latest build for Ubuntu16. I was able to see the creds when I wanted to add a new first user. I think this is when it's shown because I was unable to reproduce it with at least one user + admin.

**Comment by syntrydy** [comment]
this happen when you allow the browser to save admin username and password on the login page
