### ISSUE TITLE
custom scripts levels  all in zero

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1143]
In 3.1.4 beta, The form for custom scripts management is loading zeroes for the "level" field across all scripts

Underlying LDAP data is correct (different levels).

It seems updating level is not taking effect either.

**Comment by syntrydy** [comment]
This is due conflicting library.
For instance RichFaces and PrimeFaces.

When i disable Primefaces every thing is correct.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44721582-4b63a900-aac2-11e8-891a-f9711053de03.png)
