### ISSUE TITLE
Dead link in Super Gluu login page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1144]
Please refer to the screenshot -- the marked link doesn't take the user to the Android app:

![image](https://user-images.githubusercontent.com/5271048/44677070-a3cf7380-a9fa-11e8-818d-674b10424513.png)

Please point link to: 

https://play.google.com/store/apps/details?id=gluu.org.super.gluu&hl=en_US

**Comment by shekhar16** [comment]
@sahiliamsso  please check the custom property 'supergluu_android_download_url' on manage Custom Script page -> person Authentication tab -> Super Gluu

Here is screenshot

![image](https://user-images.githubusercontent.com/15937500/45109534-7ce11200-b15d-11e8-99e8-75052e6ae4fb.png)

**Comment by willow9886** [comment]
@shekhar16 we should have the correct link out of the box.. can confirm?

**Comment by shekhar16** [comment]
@willow9886  yes i had corrected this link in ldif file i.e. pre-loaded data in ldap in commit i.e. https://github.com/GluuFederation/community-edition-setup/pull/476/commits/b2993b3bddb9d43cb78ae0982c131ca233a35264

I m just wanted to confirm, is it present in Sahil's setup  or he had just updated the identity war file.

**Comment by syntrydy** [comment]
I confirm, the change is in 3.1.4 branch and will be surely available in RC4

**Comment by natt-tester** [comment]
@willow9886, @shekhar16, checked in RC4 -- it's done.
