### ISSUE TITLE
Unable to create TR from "Federation" Entity Type

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1148]
1, Create a TR of type "Federation" using inCommon Metadata
![image](https://user-images.githubusercontent.com/21104811/44692011-98259080-aa7e-11e8-98c7-97fab364d4a5.png)

2. Create another TR  , 

Entity Type:* = Single SP
Metadata Location = Federation
Federation Name = Choose Name created in Step1

No option to select "Entity ID" is displayed. 
Click on Configure Relying Party, You will see error
![image](https://user-images.githubusercontent.com/21104811/44692082-f6527380-aa7e-11e8-8d81-d7df961181cf.png)

**Comment by syntrydy** [comment]
You can't upload file with size more that 30MB.

**Comment by sahiliamsso** [comment]
@syntrydy - It's a separate issue than size limit. This happens for a shorter length data as well
