### ISSUE TITLE
"uma grant" option not available in oxtrust OIDC client 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1149]
oxauth-rp shows following options
![image](https://user-images.githubusercontent.com/21104811/44694433-0b350400-aa8b-11e8-8599-176c3083d042.png)

Where as OpenID Connect > Add Client > Add Grant Type 
![image](https://user-images.githubusercontent.com/21104811/44694424-03755f80-aa8b-11e8-9278-0a87351d37df.png)

**Comment by syntrydy** [comment]
@sahiliamsso  when creating issue please make sure you provide all information or where to find them

**Comment by syntrydy** [comment]
@sahiliamsso  where do the first screenshot coming from?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47360081-59026d00-d6c6-11e8-87ab-803fd006f6d1.png)
