### ISSUE TITLE
[Bug]Attribute mappings cannot be removed on the Cache Refresh's configuration page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#115]
Environment:
Ubuntu 64bit 14.04.3 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.3-1

Preconditions:
1) Attribute mapping is created on Cache Refresh's configuration page (you'll need to assign values for all other required settings on the "Configuration->Cache Refresh" page for configuration to be accepted)

Steps to reproduce:
1) While being logged in to oxTrust web UI as default admin user, move to the "Configuration->Cache Refresh" page
2) Try to remove attribute mapping there by clicking on the small "cross"-button to the right of it.

Result:
User agent is redirected to the IdP's home page and error message ("System error") is displayed (see attached picture)
Related fragment of the oxtrust.log: [link](https://drive.google.com/file/d/0B6Mqu38YJ8RcclVfcjNpaGxwams/view?usp=sharing)

![attr-rm-err](https://cloud.githubusercontent.com/assets/11802046/9836607/9f71aeea-5a28-11e5-892e-05adb3e6c615.png)

**Comment by yurem** [comment]
It should works fine in current version
