### ISSUE TITLE
Unable to add/update same Login Redirect URL or Post Logout URL in Gluu server

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#1150]
Tested on Gluu 3.1.3

1- Create a new client in Gluu server  oxTrust
2- Assign a valid  Login Redirect URL / Post Logout URL
3- Add other required details and  Create/Update client
4- Now remove the Login Redirect URL  / Post Logout URL and try to add same  Login Redirect URL  / Post Logout URL  to the client
5- Click on update

Now oxTrust will give validation error

**"The URL is not valid or black listed"**

**Comment by syntrydy** [comment]
@centroxy  no such behavior in 3.1.4.

Closing this thicket for now.

**Comment by centroxy** [comment]
@syntrydy  How about gluu-server-3.1.3sp1 ?

**Comment by syntrydy** [comment]
unable to reproduce this issue, i test it on 3.1.3 and in 3.1.4.
Note that in 3.1.4 multiple login redirects is not allow until you add a sector identifier.

Close this ticket now.
