### ISSUE TITLE
Enhance password reset email

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1151]
It would be great to have proper email formatting instead of a block of text in the password reset message:

<img width="1042" alt="ubuntu16_gserver3 1 4_password_reset_email1" src="https://user-images.githubusercontent.com/38302725/44658868-ae632a80-aa45-11e8-8cd7-8524eab27d7c.png">
<img width="725" alt="ubuntu16_gserver3 1 4_password_reset_message2" src="https://user-images.githubusercontent.com/38302725/44658891-bd49dd00-aa45-11e8-8879-bfbcb6d5348a.png">

**Example (really minimalist):**

<img width="386" alt="reset_password" src="https://user-images.githubusercontent.com/38302725/44698259-91207180-aac2-11e8-9c5b-5a7e2a697274.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44910881-b7d9e480-ad1c-11e8-9668-8efd003b1b50.png)

**Comment by natt-tester** [comment]
@syntrydy, could you unify the font and add spaces:

- after Hello user
- between the text and the button?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45293520-53730e00-b4f0-11e8-9c69-4e65d248c440.png)
