### ISSUE TITLE
Persistent placeholders, no ^ v symbols

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1153]
Please refer to the screenshot from Manage Custom Scripts and fix the problems throughout the whole menu:

- the placeholders are not cleared when you click on the field
- there are no **^ v** symbols to add/subtract values
- the X and eye icons should be next to each other with a reasonable distance between them: 
<<>> .............. X

![twilio_layout](https://user-images.githubusercontent.com/38302725/44701315-6b4e9900-aad1-11e8-8e3e-c18523ddbc6c.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44721463-e3ad5e00-aac1-11e8-9e84-e404e7d725d6.png)

**Comment by syntrydy** [comment]
Fixed here https://github.com/GluuFederation/oxTrust/issues/1143
