### ISSUE TITLE
Attribute mapping entries on Cache Refresh becomes empty

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1157]
1. Go to Configuration > Cache Refresh
2. Enter Add source attribute to destination attribute mapping:
![image](https://user-images.githubusercontent.com/21104811/44760975-f164f100-ab5e-11e8-99a3-46d64d273356.png)

3. Now click on "Add source attribute to destination attribute mapping" button

It deletes the existing values entered in step 2.

![image](https://user-images.githubusercontent.com/21104811/44760997-12c5dd00-ab5f-11e8-877e-cac21f67e20c.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44775848-88857500-ab6e-11e8-9e91-f86f8c3b1a37.png)


Fixed
