### ISSUE TITLE
align "remove source server" in CR Source Backend server tab

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1158]
Go to Configuration > Cache Refresh >  Source Backend Servers

![image](https://user-images.githubusercontent.com/21104811/44761104-7fd97280-ab5f-11e8-8074-3763a1c89320.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44776901-1b271380-ab71-11e8-8747-7e317000aad2.png)
