### ISSUE TITLE
Render StorageService for memcached

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#116]
Currently oxTrust render in-memory StorageService template as seen [here](https://github.com/GluuFederation/oxTrust/blob/f774cb211fd5a9b1374ce405108d605458128439/configuration/template/shibboleth2/sp/shibboleth2.xml.vm#L23).

In cluster edition, we need to use memcached as StorageService. Here's an example of memcached StorageService configuration:

``` xml
<StorageService type="MEMCACHE" id="mc" prefix="SERVICE_PREFIX:">
    <Hosts>
        127.0.0.1:22122
    </Hosts>
</StorageService>

<StorageService type="MEMCACHE" id="mc-ctx" prefix="SERVICE_PREFIX:" buildMap="1">
    <Hosts>
        127.0.0.1:22122
    </Hosts>
</StorageService>

<SessionCache type="StorageService" cacheTimeout="28000" StorageService="mc-ctx" StorageServiceLite="mc" />
<ReplayCache StorageService="mc"/>
<ArtifactMap StorageService="mc" artifactTTL="180"/>
```

It would be nice if oxTrust can determine whether to use in-memory or memcached StorageService.

**Comment by nynymike** [comment]
This part of the shibboleth config does not get rendered by oxTrust. In any case, it needs to be reconsidered in light of Shib 3. Closing for now... let's revisit.
