### ISSUE TITLE
Messed up checkboxes in Register Attribute

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1164]
Please fix them:
<img width="591" alt="attribute_messed_up" src="https://user-images.githubusercontent.com/38302725/44856706-69433080-acb1-11e8-99de-2d7c1152eea2.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/44868404-a217e100-ac82-11e8-9a87-6859f8ccb45d.png)
