### ISSUE TITLE
oxTrust logout improvements

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#1168]
Currently oxTrust relies on `JSESSIONID` for session management. This `JSESSIONID` only expires when the session ends. Therefore `session_id` configuration in oxAuth will not affect oxTrust sessions.

**Comment by syntrydy** [comment]
@afroDC i think all session stuff are handle in oAuth project

**Comment by yurem** [comment]
Right, oxTrust uses JSESSIONID cookie. It's state-full application.
session_id is oxAuth cookie. We are using it for SSO.

We can define JSESSIONID  expiration in web.xml: https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp-jetty/WEB-INF/web.xml#L87

**Comment by yuriyz** [comment]
In addition  oxTrust must  react on /end_session action performed by another RP (not oxTrust itself). Means oxTrust client should register `frontchannel_logout_uri` and perform logout action if `frontchannel_logout_uri` is hit. It seems to be not the case right now, as shown by @natt-tester here https://github.com/GluuFederation/oxAuth/issues/849#issuecomment-450367959

**Comment by yurem** [comment]
@afroDC can you add step-by-step flow or work flow to understand it. I think oxTrust session (JSESSIONID ) is enough for this app

**Comment by yurem** [comment]
It's not needed now
