### ISSUE TITLE
Empty page in update OIDC client

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1173]
1. Create valid OIDC client
2. Update the client

![image](https://user-images.githubusercontent.com/21104811/45007680-99c1fc00-b01c-11e8-9abb-6ea6ebb0ed9e.png)

**Comment by syntrydy** [comment]
@sahiliamsso do you think the screenshot provide is enough the identified that issue?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45035829-d7da1280-b052-11e8-96b8-238cb31b1518.png)
