### ISSUE TITLE
Export Client Config

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1176]
We have a Client Config Summary option now in oxTrust. People need to be able to export that config. 

Perhaps we can make an option for "view in markdown" so the person can see the config and copy/paste it into a text editor (like our support portal!).

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47635915-df9bcc00-db56-11e8-8e1e-b77bf7177d10.png)

**Comment by shmorri** [comment]
Documented here:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/openid-connect.md#client-summary
