### ISSUE TITLE
Validation of Import People causes error 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1178]
Please refer to the GIF and confirm this behavior in RC2. Tested in Ubuntu16, Firefox:

![upload_people](https://user-images.githubusercontent.com/38302725/45087410-118d4500-b149-11e8-8892-da5a44059dfe.gif)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45093551-a1fb6380-b110-11e8-8409-f58d6a5b2689.png)
