### ISSUE TITLE
Validation for client expiration needed

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1179]
In OpenID --> Clients --> Add/Update Client, I think we need a warning message when the user sets the datepicker in the past to delete a client, or even creates a new client and chooses a past date by mistake. Due to the new design, it's relatively easy to misclick it now; the warning would improve the UX.

**Comment by willow9886** [comment]
> when the user sets the datepicker in the past to delete a client

Is there a good reason someone would use this strategy to delete a client? 

Is there ever a good reason to set a client expiration in the past? Would it be better if we didn't allow setting past dates for client expiration? 

@natt-tester @yurem @syntrydy

**Comment by syntrydy** [comment]
Fixed
