### ISSUE TITLE
UMA resource fields moved to the right

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1180]
After adding a test UMA resource, its fields are moved to the right and beyond the form:

<img width="1301" alt="ubuntu16_add_uma_resources" src="https://user-images.githubusercontent.com/38302725/45091534-1a384800-b156-11e8-886f-e5a340d69be2.png">
Please fix it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45150933-e2b4b480-b1c4-11e8-8b86-acdc71e10971.png)

**Comment by syntrydy** [comment]
Fixed, 40% left and 60 right?
