### ISSUE TITLE
Disappearing icons in Passport Authentication method

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1190]
Steps:

1. Go to Configuration > Manage Authentication > Passport Authentication method
2. Add a Strategy if not added
3. Add a new property

Expected: The preview icons are visible for clientId and clientSecret.
Actual: The icons disappear. Also, if you want to delete an added but empty property, it generates an error message which should be removed. 

Please refer to the GIF downloadable at:
https://ufile.io/krp03

**Comment by willow9886** [comment]
@natt-tester this is RC2 I assume?

**Comment by natt-tester** [comment]
@willow9886 yes, still tested in RC2.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45229781-c5641100-b2be-11e8-81e5-cbbc3e8aca74.png)
