### ISSUE TITLE
Add new method getBindCredentials method to CR script to allow dynamically change AD password

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1197]

**Comment by yurem** [comment]
Implemented

**Comment by yurem** [comment]
In order to resolve this I added next flow:
-  Call CR script method getBindCredentials if api > 1
-  This method can return null or BindCredentials(“bindDn”, “bindPwd”)
-  If getBindCredentials returns null than use bindDn/bindPassowrd from Source LDAP configuration
-  If getBindCredentials returns not null than use credentials returned from method

Test flow:
1. Deploy latest 3.1.4 oxTrust.war
2. Add new method and update getApiVersion method. Example:
    def getApiVersion(self):
        return 2

    def getBindCredentials(self, configId):
        print "Cache refresh. GetBindCredentials method"

        return BindCredentials("bindDn", "bindPwd")
3. We need to return right credentials instead of "bindDn", "bindPwd" in real method
4. Specify wrong password in Source LDAP server config
5. Run CR
6. Check if it works well
7. Update return BindCredentials("bindDn", "bindPwd") to return wrong crenetials
8. Check if CR not works well
9. Update return BindCredentials(“bindDn”, “bindPwd”) to return None
10. Check if CR not works well

**Comment by willow9886** [comment]
@natt-tester can you do a test of this?

**Comment by natt-tester** [comment]
@yurem, @willow9886, I changed the script, but keep getting the error you can check in the log. What can I do to make it work?
[CR_files.tar.gz](https://github.com/GluuFederation/oxTrust/files/2379095/CR_files.tar.gz)

**Comment by yurem** [comment]
It's python code style issue:
```
Caused by: IndentationError: ('unindent does not match any outer indentation level', ('cache_refresh.py', 56, 4, '    def getBindCredentials(self, configId):\n'))
```
In python line indent is used to group methods in blocks. It's simular to `{` and `}` in java. So, all idents should be in right positions.

**Comment by natt-tester** [comment]
@yurem, could you please try to set up your ldap server with the data that I sent you? When I update and validate the script, it's a success, but during a CR I can't get any users from the external database. I'd really like to close the issue, but I'm stuck.

**Comment by natt-tester** [comment]
@yurem, I think it still needs improvement. When I updated the script on c7 and validated it, it gave me an error: getBindCredentials() takes exactly 2 arguments (3 given). The full stacktrace is in the log:
[script_error_cr.txt](https://github.com/GluuFederation/oxTrust/files/2410343/script_error_cr.txt)

**Comment by yurem** [comment]
Can you apply this update to you script and try again?
https://github.com/GluuFederation/oxExternal/commit/aab7b715ff761689c665577826c583955782972a

**Comment by yurem** [comment]
I tested it myself too.
1. After activating CR with wrong password of source LDAP server:
```
2018-09-25 17:16:54,712 DEBUG [Thread-1144] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:181) - Allowing to run new process exclusively
2018-09-25 17:17:54,889 ERROR [Thread-1157] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:1080) - Failed to connect to LDAP server using configuration source
2018-09-25 17:17:54,905 ERROR [Thread-1157] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:283) - Skipping cache refresh due to invalid server configuration
```

2. After enabling script with `getBindCredentials` which return not None:
```
ely
2018-09-25 17:31:04,309 ERROR [Thread-129] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:1072) - Using updated password which got fr  om getBindCredentials method
2018-09-25 17:31:06,674 INFO  [Thread-129] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:318) - Attempting to load entries from sour  ce server
```

According to point 2 it works well.

**Comment by yurem** [comment]
Also I updated sample CR script in CE to help with testing it: https://github.com/GluuFederation/community-edition-setup/commit/0e7ed38f99ad705c678d57e1ab8d74d1ee20231c

**Comment by natt-tester** [comment]
Tested, it works in gluu-server-3.1.4_1-2.
