### ISSUE TITLE
Center string in registration page

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1205]
Please center the string marked in red:

<img width="874" alt="center" src="https://user-images.githubusercontent.com/38302725/45408169-eb1e5b00-b6ae-11e8-9b93-4863b2ab1b48.png">

**Also, what's the logic behind "Already have an account"? Shouldn't it be linked to the login page? Now it's just a string.**

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45411512-45e29300-b66c-11e8-847a-8b27ee9b1864.png)

**Comment by syntrydy** [comment]
Done
