### ISSUE TITLE
Placeholders not cleared & keys editable 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1207]
Please refer to the GIF and fix the incorrect behavior we've fixed already for some fields: 

- if I remember correctly, the keys should be uneditable (please confirm @syntrydy)
- the placeholders for values should be cleared on focus
- the preview icon doesn't change anything at first click

![fields_not_cleared](https://user-images.githubusercontent.com/38302725/45418705-7eb05580-b6c8-11e8-8726-2ca1de78c2ca.gif)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45446276-62aab500-b6c4-11e8-82dc-2653f271001b.png)
