### ISSUE TITLE
Backend name in CR should conatins alphanumerc value

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#121]

**Comment by yurem** [comment]
I suspect that we fixed this in 2.4.0 already...

**Comment by yurem** [comment]
@aliaksander-samuseu what do you think about my comment?

**Comment by willow9886** [comment]
@aliaksander-samuseu can you confirm if this has been fixed?

**Comment by aliaksander-samuseu** [comment]
@yurem @willow9886 I'm not sure I'm following. Was it me who reported it initially? I'll try to check it out anyway.

**Comment by yurem** [comment]
We can close this issue. The name with space was the problem for properties based CR setting.
Now we store them in JSON in LDAP. Hence the name can contains any characters and spaces.
