### ISSUE TITLE
Export Attribute | Add Export button at top

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1210]
Go to Import/Export Attributes, Click on Export Attribute LDIF

You have to scroll all the way down to find the export button.  Please move this button to the top (better to include both buttons at the top as well as bottom)
![image](https://user-images.githubusercontent.com/21104811/45462648-62430600-b726-11e8-8ed1-b42b5028bf9e.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45480501-0b96f580-b741-11e8-994b-8e2085750f09.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45480531-1f425c00-b741-11e8-8fca-58615db14b75.png)
