### ISSUE TITLE
Disappearing error button

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1213]
Lo and behold, the button disappears when you click it several times and then scroll:

![magic](https://user-images.githubusercontent.com/38302725/45493358-df678d00-b7b1-11e8-8041-ba41e34212de.gif)

**Comment by syntrydy** [comment]
That is not an issue.  All custom scripts are build using the same code. The **show error** button shows up only when the error is available.

**Comment by natt-tester** [comment]
@syntrydy, but the header stays red and I know the error is still there... Shouldn't the button disappear along with the header turning back to normal/green if enabled?

**Comment by syntrydy** [comment]
Error is show only when is throw from script.

If you create a new custom script and provide **hello word** as script content it clear that the script will fail and the error field will not be displayed.
