### ISSUE TITLE
Improvement : oxTrust automatically switch to another tab on update action.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1219]
Steps
1. Go to "Configuration" -> "JSON Configuration"
2. Select "oxAuth Configuraiton" tab.
3. Change any value and click Update button.
Result: page is refreshed and "oxTrust Configuration" tab is selected. If user wish to double check whether value is really saved then he/she needs to select "oxAuth Configuraiton" tab again and navigate to changed value. 
Expected result: as minimum I would expect no automatic switch of the tabs. Ideally page should stay on same position as it was during Update click. So user just see message "oxAuth configuration is updated successfully."

**Comment by syntrydy** [comment]
@yuriyz, enhancement added

**Comment by natt-tester** [comment]
> Expected result: as minimum I would expect no automatic switch of the tabs.

The requirement is met. DONE.
