### ISSUE TITLE
Don't asks user fill inum LDAP server setting in CR form in some cases

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#122]
We need to add checkbox to CR form to specify if we are planning to use CE LDAP server as inum DB.
Once admin select this checkbox we should hide inum section and use oxTrustLdap.properties to connect inum server.

**Comment by mzico** [comment]
+1

**Comment by shekhar16** [comment]
Added check box for default inum server and conditionalyy hide/show for inum server tab.

**Comment by shekhar16** [comment]
Please let me know how CR functionality load inum server configuration.

**Comment by yurem** [comment]
It did that there
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/cache/service/CacheRefreshTimer.java#L249

You can create there LdapServerConnection with ldapEntryManager inside.

**Comment by shekhar16** [comment]
Fixed.removed the c:if tag and load the default inum server configuration.
