### ISSUE TITLE
Improvement : introduce toolbar for `page-wide` buttons.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1220]
Lets say user needs to change any value on `oxAuth Configuration` page which is on top of the page. User needs:
1. change value
2. scroll down to the buttom of the page (which is huge), find and click on "Update" button.

We have to improve UI/UX for it and introduce toolbar for buttons. Depending on page different buttons should be displayed. Toolbar should be always on top, similar to how Google Drive UI works.
Example:
1. "oxAuth Configuration" page is selected -> Toolbar should show "Update" button.
2. "Client" details page is selected -> Toolbar should show "Update" and "Delete" buttons.
We can still have inline buttons on the page but goal of toolbar is to keep page wide buttons on toolbar, so user don't need to hunt them.

**Comment by shmorri** [comment]
This is a great idea for the new Admin UI
