### ISSUE TITLE
Remove old /users API

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#123]
There is API which allows to modify person:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/api/rest/UserRestService.java
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/api/rest/UserRestServiceImpl.java

It looks like it's old API. According to SVN Oleksiy imported this code long time ago at 12/10/12. Comment of this commit is "Added merged oxTrust code"

There is no doc about this on wiki.

I propose to remove it an clean up related classes.

**Comment by yurem** [comment]
Mike, do you remember this API?

**Comment by nynymike** [comment]
Definitely remove. I don't even remember this. The only API should be SCIM.

**Comment by yurem** [comment]
Removed
