### ISSUE TITLE
Password reset UI enhancements

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1234]
Please have a look, @syntrydy: 

The password reset flow from RC5 still needs to be improved:

- **the email** should show the expiration time in minutes (otherwise it will say the link will expire in 0 hours) and say "**expire**", not "expired"
<img width="489" alt="expire" src="https://user-images.githubusercontent.com/38302725/45608009-80489780-ba93-11e8-99d5-aae01771acc6.png">

- **the expired link message** should be centered, with each sentence in a new line. It should say "**no longer valid**", not "no more valid"
<img width="477" alt="re-enter" src="https://user-images.githubusercontent.com/38302725/45608042-bb4acb00-ba93-11e8-948d-e7bc56c535cd.png">

- the pop-up after a successful password reset should have a black string with an info icon, not an error look
![reset_success](https://user-images.githubusercontent.com/38302725/45608104-21cfe900-ba94-11e8-9c24-137c0b380f42.png)

**Comment by syntrydy** [comment]
Done
