### ISSUE TITLE
Fix Manage authetication captcha

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1250]
![image](https://user-images.githubusercontent.com/7513418/45929150-9e0b7600-bf45-11e8-8fe9-4134aa3129a8.png)

**Comment by natt-tester** [comment]
Done:
<img width="521" alt="captcha" src="https://user-images.githubusercontent.com/38302725/46207140-a4e12100-c369-11e8-806a-2d9d0e57e8a5.png">
