### ISSUE TITLE
Captcha on Forgot password

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1252]
1. Enable Recaptcha on User Registration
2. Enable forgot password, and go to https:///{host}/identity/person/passwordReminder
3. Enter Email and click submit email

Don't see any option to verify captcha yet getting the error "Please check your input and CAPTCHA answer.Instructions letter was not sent. "

![image](https://user-images.githubusercontent.com/21104811/45930886-4a1f8200-bf83-11e8-9d8f-e47da49265c3.png)

**Comment by syntrydy** [comment]
Have you enter **Site key** and **Secret  key** before?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45931643-a5904680-bf68-11e8-8d0a-0e1f5c2b76fe.png)

**Comment by natt-tester** [comment]
Works fine.
