### ISSUE TITLE
oxtrust allows user to delete email and username

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1259]
Go to Users > Manage Users
Search for existing user
Click on "x" against username and email and click update
![image](https://user-images.githubusercontent.com/21104811/46012443-e746fb80-c0e6-11e8-81d3-192e193c75a1.png)

Result: It allows to save user
![image](https://user-images.githubusercontent.com/21104811/46012482-080f5100-c0e7-11e8-8488-a412f15ec76d.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46036390-49aaf680-c0fd-11e8-8e15-c4b2c7a0eda2.png)

**Comment by natt-tester** [comment]
Checked, it's impossible to delete these fields in the UI.
