### ISSUE TITLE
Suggestion for further re-work of "Add/Update OIDC client" page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1262]
The look of the page is sure much better now, but, IMO, controls which are rarely used still take too much space for themselves, while pushing the most often changed settings to the bottom and cluttering the page. On the attached picture I tried to suggest an even more compact an easy-to-grasp way of placing them on the page, when the least used settings are either pushed down the page, or moved to a hidden (folded) lists or to pop-up windows, triggered by user clicking a button.
![oidc_client_new_layout](https://user-images.githubusercontent.com/11802046/46048963-a249b600-c134-11e8-8bf5-89df7fbabc46.png)

**Comment by aliaksander-samuseu** [comment]
One more small suggestion in addition to what picture shows. It seems now when you create a client registration manually, its expiration is set to 24 hours. Usually when we add a client in such way, we don't want it to expire at all. In previous versions it was default behaviour for manual addition, and I think it should stay such, as it will require user to do extra job of setting it to never expire each time they create a client in web UI.

**Comment by aliaksander-samuseu** [comment]
We also should try to come up with a more smart placement of the "Add"/"Update"/"Cancel" button. Currently, if user arrives at this page to tweak a single setting at the top of it, he needs to scroll all the way down to apply the change. Perhaps the script on the page could detect that a change did take place, and draw a panel with "Update"/"Cancel" button right at the bottom of the current working screen, which would stay there while user scrolls up/down?

This is already more a "quality of life"-type of enhancement, still worth considering.

**Comment by willow9886** [comment]
Maybe we should have a button for "Advanced Settings" , which exposes infrequently used configuration options

**Comment by aliaksander-samuseu** [comment]
@willow9886 
The fields I moved to "General info" on the picture probably won't fit such category very well. They are not that advanced, but still not frequently used (I would also move the "Contacts" button there as well, while retuning "Client description" text box back to the main page, as it's where it belongs, user must be able to see it first-first when they open this page, as it usually will give them general description of the client's role). Having 2 different categories would reduce cluttering, I think.

Also instead of pop-ups triggered by buttons we could split the page into several tabs, like "Standard settings" / "General info" / "Advanced settings" or "Encryption/Signing algorithms".

**Comment by aliaksander-samuseu** [comment]
I would probably go with 3 tabs:
1. "Standard settings" or "Basic configuration" - the most important/mandatory properties you need for most of clients. "General info" button is placed on this page as well and behaves as described above.

2. "Advanced settings" - Some less often used, and mostly not critical, but still useful settings, either defined in OIDC specs, or controlling our custom features

3. "Encryption/Signing algorithms" - worth of dedicating a separate tab for them, as though they are not frequently used, yet still there are a lot of them and they may be very important in specific cases or for some setups.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46606144-bc4fa500-caf3-11e8-9102-abe69de9e894.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46606187-d8534680-caf3-11e8-8ddd-ba026f346a3c.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46606213-f28d2480-caf3-11e8-9167-582695295392.png)

![image](https://user-images.githubusercontent.com/7513418/46606235-0e90c600-caf4-11e8-9e37-26720a40b107.png)

**Comment by syntrydy** [comment]
@willow9886 @aliaksander-samuseu  please check if it is correct.

**Comment by willow9886** [comment]
this looks excellent @syntrydy !

**Comment by aliaksander-samuseu** [comment]
@syntrydy @willow9886 

Here are some suggestions per each tab:

**Sign/Enc properties:**

(See picture attached below)

1. We need to maintain grouping of controls related to a specific item, as it was done on the old page, to enhance usability. It will usually be 3 controls per item, in next fixed order: "JWS alg Algorithm for signing...", "JWE alg Algorithm for encrypting..." and finally "JWE enc Algorithm for encrypting..." On the attached picture only 1 out of 3 groups was preserved (marked with green), groups marked with yellow and orange got separated. Also, order of elements inside each group doesn't match the order mentioned above.

2. Not sure why "Default Max auth age" is placed here, as I don't see obvious relation to enc/signing here. It should be moved to "Advanced settings", I believe
@syntrydy @willow9886 

Here are some suggestions per each tab:

**Sign/Enc properties:**

(See picture attached below)

1. We need to maintain grouping of controls related to a specific item, as it was done on the old page, to enhance usability. It will usually be 3 controls per item, in next fixed order: "JWS alg Algorithm for signing...", "JWE alg Algorithm for encrypting..." and finally "JWE enc Algorithm for encrypting..." On the attached picture only 1 out of 3 groups was preserved (marked with green), groups marked with yellow and orange got separated. Also, order of elements inside each group doesn't match the order mentioned above.

2. Not sure why "Default Max auth age" is placed here, as I don't see obvious relation to enc/signing here. It should be moved to "Advanced settings", I believe
![new_enc-sign_props_page](https://user-images.githubusercontent.com/11802046/46688543-4b4ce200-cc06-11e8-91fd-fe412a835f0d.png)

**Comment by aliaksander-samuseu** [comment]
**Advanced settings**

1. Fields like "Logo URI", "Policy URI" etc don't look like they belong here, being neither important, nor advanced, yet they consume space right in the center of the page. Most of the time those fields will be left empty anyway. At the very least, we should move them to the bottom of the page, but better still try to find a better place for them (the previous suggestion for them moved to a pop-up window called with a button on the first tab still holds)

2. The picture seems to be truncated, so I can't see elements further down the page

**Standard settings**

1. "Disabled" button should really be moved somewhere up. The idea is here is that user should be able to assess the general state of this entiry with one quick glance when they open its page, and whether client's entry is disabled or not is pretty important info.

**Comment by aliaksander-samuseu** [comment]
Does this "Disabled" control have to be that big, at all? Can we "shrink" it to a small checkbox placed right after client's name or inum fields? May be it does't even need a caption of its own, just a checkbox, perhaps with a hint explaining its purpose when mouse cursor is hovered over it, or with some visual effect (green halo around it like around a light bulb etc) when it's set?

**Comment by willow9886** [comment]
> "Logo URI", "Policy URI"

I think these could be used quite frequntly... they are presented to the user in an OAUth consent transaction. They should probably be in the general settings

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46853162-3edaac00-cdf5-11e8-9efa-6ab8fdeb03a2.png)

![image](https://user-images.githubusercontent.com/7513418/46853194-5023b880-cdf5-11e8-9532-dc80a1405743.png)

![image](https://user-images.githubusercontent.com/7513418/46853297-8a8d5580-cdf5-11e8-8f81-679282566926.png)

![image](https://user-images.githubusercontent.com/7513418/46853336-a133ac80-cdf5-11e8-8e6b-667f2aa73839.png)

![image](https://user-images.githubusercontent.com/7513418/46853360-b4467c80-cdf5-11e8-9042-521a59554a1b.png)

**Comment by natt-tester** [comment]
@syntrydy, @aliaksander-samuseu, these are the final layouts as displayed by my 15" Mac (Firefox):
<img width="1280" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50055587-32563500-0151-11e9-8b85-60249e24d201.png">

<img width="1272" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50055597-41d57e00-0151-11e9-9551-0249122cbc38.png">

<img width="1280" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50055603-53b72100-0151-11e9-8721-a63182d97a8f.png">
  
**Please make sure the Advanced tab displays all the wanted changes.**

**Comment by syntrydy** [comment]
@natt-tester **Advanced tab displays all the wanted changes**.

If you see a missing fields open an issue for it.

**Also, I think that we should have tabs to navigate between the fields here**

We have a task to fix such issue in 4.0, the whole UI will be replace by more appropriate conponents.

**Comment by natt-tester** [comment]
The tabs are added, it's DONE.
Checked in 3.1.5_5.
