### ISSUE TITLE
Improve some public facing pages to match Gluu design

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1264]

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50091615-2a0f0000-020c-11e9-9665-b2364f85c7a9.png)


![image](https://user-images.githubusercontent.com/7513418/50091678-53c82700-020c-11e9-8536-c02e113081a8.png)

**Comment by syntrydy** [comment]
@natt-tester track the OTP stuff here https://github.com/GluuFederation/oxAuth/issues/966

**Comment by natt-tester** [comment]
The font is unified, waiting for RC5 to check https://github.com/GluuFederation/oxAuth/issues/966 :)
