### ISSUE TITLE
Change button location in Cache Refresh

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1265]
Please follow the suggestions:

![cache_rfr](https://user-images.githubusercontent.com/38302725/46078126-9ca4ac80-c1d6-11e8-871a-b53797e9a512.png)
![rm_sserver](https://user-images.githubusercontent.com/38302725/46078146-ac23f580-c1d6-11e8-94f0-d3e68ffcbb92.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46093272-ce098200-c1ae-11e8-81ba-a9832567131b.png)


![image](https://user-images.githubusercontent.com/7513418/46093336-00b37a80-c1af-11e8-99b3-e683626dc8b5.png)
