### ISSUE TITLE
Problems with public-facing pages

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1268]
Please refer to the GIF: there's no logo, I think the footer is missing, and the captcha should be aligned with the fields (in the same column). 

**Tested with 3.1.4-1, centos6 and Firefox.**

![no_logo_no_footer](https://user-images.githubusercontent.com/38302725/46123378-78da7880-c261-11e8-8618-ac5cea653821.gif)
<img width="207" alt="footer" src="https://user-images.githubusercontent.com/38302725/46123748-80028600-c263-11e8-8002-cb0280707d68.png">

Also finishLogout is missing the logo&footer. Please make sure that all the recently changed pages have the same design.
<img width="1006" alt="finishlogout" src="https://user-images.githubusercontent.com/38302725/46123975-a83eb480-c264-11e8-89ce-57fa517afb62.png">

<img width="874" alt="reset_password" src="https://user-images.githubusercontent.com/38302725/46124792-5cdad500-c269-11e8-9a04-a79f8c3327e9.png">

<img width="870" alt="reset_pwd" src="https://user-images.githubusercontent.com/38302725/46124946-189c0480-c26a-11e8-8a66-a44266859b6a.png">

**Comment by syntrydy** [comment]
I don't see any bug on these pages

**Comment by natt-tester** [comment]
The suggested white font has changed to blue. Everything's aligned now, there are logos and footers too.
