### ISSUE TITLE
Register page pop-up displayed for another user (the same browser)

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1269]
Steps:

1. Go to the user registration page
2. Complete the form with new credentials and click Register

Expected: On the same page there is a pop-up saying you've registered successfully, but you're inactive.
Actual: There's no pop-up, the admin sees it when they log in. The same behavior occurs for password reset.

**Comment by syntrydy** [comment]
After user registration, a message is added to facesMessages for displayed, there is also to redirection to login page. The message is coming from oxTrust(registration page) and the redirection goes to oxauth(login) page, hence the messages can't cross component. It is then display when you login and when back to **oxtrust(home page)**

**Comment by natt-tester** [comment]
I think it's solved: now the user is redirected to see their inactive profile. The pop-up is there:

<img width="1426" alt="register" src="https://user-images.githubusercontent.com/38302725/46200300-9fc5a700-c354-11e8-8331-01ee944ea5b9.png">
However, when the user clicks on the dropdown Profile/Language/Logo, they are redirected to the login page. @willow9886, is that acceptable behavior?

**Comment by willow9886** [comment]
@natt-tester 

> However, when the user clicks on the dropdown Profile/Language/Logo, they are redirected to the login page.

Its not ideal behavior. It puts them in a loop with no clear objective. I think we should simply display a message saying: 

> Your account has been disabled. If you believe this is an error, contact your system administrator for assistance.

**Comment by natt-tester** [comment]
> > However, when the user clicks on the dropdown Profile/Language/Logo, they are redirected to the login page.
> 
> Its not ideal behavior. It puts them in a loop with no clear objective. I think we should simply display a message saying:
> 
> > Your account has been disabled. If you believe this is an error, contact your system administrator for assistance.

The behavior is still the same as I reported, there's no error message about the account being disabled for inactive users right after registration. Please fix it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50155863-79693500-02cd-11e9-9a7d-7398e420a23b.png)

**Comment by willow9886** [comment]
@syntrydy i dont understand the message of the first screenshot.. "you successfully registered, but your account is disabled"... can you clarify?

**Comment by natt-tester** [comment]
@syntrydy, @willow9886, I think it'd be better if we just changed the first string to "You successfully registered. Please contact site administration to enable your account".

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50399697-854b7000-0781-11e9-8843-18d746e820fe.png)
