### ISSUE TITLE
Logo inconsistency

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1270]
After uploading a custom logo to **/opt/gluu/jetty/oxauth/custom/static/img**, it appears on the left on the login page, but is centered in the majority of other public-facing pages. 

**Shouldn't we choose one convention and stick to it?** 

<img width="896" alt="login_logo" src="https://user-images.githubusercontent.com/38302725/46124348-e937c880-c266-11e8-8afe-e62ca976f94d.png">
<img width="921" alt="error_logo" src="https://user-images.githubusercontent.com/38302725/46124369-0ff5ff00-c267-11e8-8e67-2874db8288c8.png">
<img width="773" alt="passportpostlogin" src="https://user-images.githubusercontent.com/38302725/46131051-1479e200-c27e-11e8-8a79-d7800a9f9afe.png">

**Comment by syntrydy** [comment]
What is the problem?

**Comment by natt-tester** [comment]
@syntrydy, now that we've changed the design of the other public-facing pages, I've noticed that the not-centered logo really stands out. Should we keep it this way?

**Comment by syntrydy** [comment]
That was by design, the logo for logo page is left-align and others logo are centered

**Comment by natt-tester** [comment]
This is why I've added also @willow9886 to this question, maybe we should consider redesign in the future? Especially the passportpostlogin page looks a bit random now...

**Comment by syntrydy** [comment]
Agreed, we shouldn't be doing UX, normally design is provide by UX team and we just implement as it is. 
I guess we don't have UX team. Without UX design we are going to say all time **this is good, this isn't, etc**.
Meanwhile we have to do with what we have at hand.

**Comment by syntrydy** [comment]
@natt-tester there is a task to enhance logo customization, that task has been schedule for 3.1.5.
https://github.com/GluuFederation/oxAuth/issues/912

I suggest to let all logo as they are now. In 3.1.5 we can improve them as we want.
