### ISSUE TITLE
Too many popups for already used reset pwd email

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1274]
This is what the user sees now after they click an already used password reset button:

<img width="1226" alt="pwd_reset_popups" src="https://user-images.githubusercontent.com/38302725/46202906-6cd2e180-c35b-11e8-90f5-1f1fcbf196f3.png">

The re-enter email field is also missing.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46205835-0b3e5300-c31a-11e8-8ff0-26bd4b9ab80c.png)
