### ISSUE TITLE
Enhance error messages

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1275]
We should redesign our error messages to provide better UX, but I think it'll be a bigger issue. Can we schedule it for 3.1.5, @willow9886? 

![error_msg](https://user-images.githubusercontent.com/38302725/46203598-a86eab00-c35d-11e8-9ffd-164d209b465c.gif)
<img width="242" alt="valid_error" src="https://user-images.githubusercontent.com/38302725/46203685-dfdd5780-c35d-11e8-8a42-be810f585068.png">

**Comment by natt-tester** [comment]
@syntrydy, the problem still occurs for other tabs in this menu and needs a fix:
<img width="789" alt="errors_remove" src="https://user-images.githubusercontent.com/38302725/50050305-3f463a80-00f7-11e9-9fbb-a72678c6de74.png">

Also, can we do something with the marked part? It's not very informative now. I know that these can be errors from any of the tabs, displayed upon hitting Udate, but maybe we can make them more descriptive?

**Comment by natt-tester** [comment]
@syntrydy, can we do something with the marked parts? The error messages are still quite enigmatic in RC4:

<img width="629" alt="cache" src="https://user-images.githubusercontent.com/38302725/50356950-70d66000-0554-11e9-96cc-1d85bd0ed5de.png">

**Comment by syntrydy** [comment]
@natt-tester we are going to  fix this in 4.0
