### ISSUE TITLE
Enhance icons for multivalued Attributes

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1276]
Please provide enough space between the icons in Manage People (admin), and maybe change the + color to Gluu green?

**Also, I think some of the icons are skewed. Could you make sure they're all aligned?**
<img width="450" alt="icons" src="https://user-images.githubusercontent.com/38302725/46205262-54ff5b80-c363-11e8-94c0-6553fcd49e91.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/46208360-5f4d3580-c322-11e8-86bc-274bd6a4a794.png)
