### ISSUE TITLE
Improve error messages when cust scripts have errors

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1282]
Very often, the "show error" functionality found in the custom scripts UI page does not help to diagnose what's wrong with the failing script. The error tends to be very generic and force you to check oxauth_script.log and do debugging.

It would be nice if we can improve this somehow.

Users send us screenshots like this:

![protected-ticket-6062-screen_shot_2018-09-27_at_2 58 28_pm](https://user-images.githubusercontent.com/5444180/46222144-0e831000-c315-11e8-80b2-9285ae2b6e69.png)

**Comment by syntrydy** [comment]
@jgomer2001, a fix is provide here https://github.com/GluuFederation/oxCore/issues/91

**Comment by natt-tester** [comment]
I believe it's DONE:
<img width="661" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50131592-279bbd00-0283-11e9-86f9-f3a20dba0efe.png">
