### ISSUE TITLE
authenticationRecaptchaEnabled property in oxTrust configuration has invalid drop down menu action

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1283]
![image](https://user-images.githubusercontent.com/36208047/46224608-6ec98000-c31c-11e8-8b53-9123843dcce7.png)

At the bottom of the JSON OxTrust configuration page in 3.1.4, the `authenticationRecaptchaEnabled` property has a dropdown that allows you to pick the input type, but should only support Boolean.

**Comment by natt-tester** [comment]
Checked in 3.1.5_3: DONE.

<img width="708" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50050056-40746900-00f1-11e9-81d7-45529ee4db7b.png">
