### ISSUE TITLE
Cache Refresh metrics don't work as expected

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1286]
I've come across this in previous versions, but in 3.1.4 when Cache Refresh is set up, it tends to not actually populate the metrics as expected. For instance, after syncing with our test LDAP, I can search for our test users and see that they're populated, but when looking at the actual Cache Refresh tab, there are no metrics:

![image](https://user-images.githubusercontent.com/36208047/46427235-816dfb80-c706-11e8-9237-f2a8a3159903.png)

Additionally, when I `Validate Script`, I get an error every time, despite the feature working.

![image](https://user-images.githubusercontent.com/36208047/46427277-a4001480-c706-11e8-9e8a-c28ffc94bae1.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47773187-87e19a00-dce9-11e8-960b-5e115d848b3e.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47777916-0b08ed00-dcf6-11e8-890e-299413a1e159.png)
