### ISSUE TITLE
Application should disable controls on processing Ajax requests

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#129]

**Comment by willow9886** [comment]
@yurem should we leave this in the 2.4.2 milestone?

**Comment by yurem** [comment]
We can move it to 2.4.3

**Comment by nynymike** [comment]
This is a very old issue. I'm not sure what "disable controls" means, and if it's still relevant.

**Comment by yurem** [comment]
In some pages we partially re-render part of the page without submitting whole page. In older version it was the problem because user can trigger more than one ajax update simultaneously. As result he get error page. I think it's not an problem with JSF 2.2 now. In 3.1.0 I never get concurrent call exception. I think we only can add label to upper corner of the page to show user when browser executing ajax request.

**Comment by yurem** [comment]
Implemented
