### ISSUE TITLE
Improve OpenID Scope selection UX

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#1292]
It takes too long to select OpenID Scopes, you have to search, select, and hit ok. It would be better if there was an oxTrust JSON property called "defaultOpenIDClientScopes" with default values "openid, profile, email" which would automatically show when you hit the add scopes button in the client form. It would also give customers the ability to add add'l scopes if they commonly use them.

**Comment by willow9886** [comment]
Also give users ability to add multiple scopes at the same time, e.g. click `scope 1`, `scope 2`, `scope 3`, etc., then click: `add`

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47356804-007aa200-d6bd-11e8-8b98-e7eafb01468c.png)

**Comment by syntrydy** [comment]
@nynymike i think the solution provide above is better in that:
- We don't have to create new entry in LDAP just to store **defaultOpenIDClientScopes**
- Our upgrade script stay unchanged as there is no new LDAP entry/updated entry
- In real scenario we don't have enough scopes and even if we have enough, the scroll bar help to pick them with ease.

**Comment by natt-tester** [comment]
@syntrydy, I think the scroll is gone from the scopes list -- my newly created scope cannot be found on the list when you want to add it to an OIDC client. Also all 10 < scopes are missing:
 
<img width="727" alt="obraz" src="https://user-images.githubusercontent.com/38302725/49775334-f2a3dd80-fd4b-11e8-9843-6039abac1acf.png">

<img width="1094" alt="scopes" src="https://user-images.githubusercontent.com/38302725/49775457-61813680-fd4c-11e8-8143-d1d41697e850.png">

Please look into it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/49787929-38e74580-fd28-11e8-8708-c92963da7300.png)
