### ISSUE TITLE
Add a dedicated logger for Velocity's logs

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1294]
Creating per @yurem 's request.

1. Remove deprecated property "VelocityLog" from oxTrust's configuration
2. Add a new logger to oxTrust's log4j2.xml which will redirect Velocity (apache.velocity package) logs to a separate file like “oxtrust-template.log”

**Comment by shmorri** [comment]
Documented in https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/operation/logs.md#core-logs
