### ISSUE TITLE
Add oxPush to default installation

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#130]
add latest oxPush code to out-of-the-box server integrations

**Comment by yurem** [comment]
According to @nynymike we need to finish oxPush upgrade before adding it to CE

**Comment by yurem** [comment]
We need to include oxPush2 into CE 2.4.2

**Comment by yurem** [comment]
I've added current oxPush2 script to CE 2.4.2: https://github.com/GluuFederation/community-edition-setup/commit/f1b14404a1414f752bfa81825aabb48557b77f08
