### ISSUE TITLE
Display available ACR options in client UI

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1304]
Admin should see their available ACRs in this screen in order to choose available ACRs. 

![image](https://user-images.githubusercontent.com/5271048/47115980-ead12c80-d225-11e8-9359-b5f5d2f7e28c.png)

Should function similar to "Add Response Type" popup in client UI:

![image](https://user-images.githubusercontent.com/5271048/47116061-1ce28e80-d226-11e8-8a66-6fd16024b777.png)

**Comment by syntrydy** [comment]
@willow9886 the default popup will show all person authentication scripts?
I mean **super gluu, u2f, OTP,passport_*,duo**.

**Comment by willow9886** [comment]
hi @syntrydy yes, that's the idea.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/47292313-7f5cd580-d5fe-11e8-8792-77bf36ee1b70.png)

**Comment by shmorri** [comment]
Documented here:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/openid-connect.md#setting-the-default-acr
