### ISSUE TITLE
Remove internal / external select box from UMA scopes form

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#131]
While creating UMA Scope it may be not very clear to end-user which type of option to select internal or external. It's good idea to add better explanation on UI:

if we create it then it's always internal because external must be provided by Resource Server

**Comment by nynymike** [comment]
Is there a link to this in the UMA spec? I don't remember reading it in UMA Core.

**Comment by yuriyz** [comment]
Here is sample from spec:
https://docs.kantarainitiative.org/uma/draft-oauth-resource-reg.html#rfc.section.2.1
```
{
  "name" : "Photo Album",
  "icon_uri" : "http://www.example.com/icons/flower.png",
  "scopes" : [
    "http://photoz.example.com/dev/scopes/view",
    "http://photoz.example.com/dev/scopes/all"
  ],
  "type" : "http://www.example.com/rsets/photoalbum"
}
```
http://photoz.example.com/dev/scopes/view is RS scope. During development we agreed that it would be nice to host scopes also by AS (add/remove/edit via oxtrust).
This leads to two types of scopes:
- RS hosted scope - external - http://photoz.example.com/dev/scopes/view
- AS hosted scope - internal - http://as.example.com/scopes/view

External/internal is our interpretation of scope. UMA specs samples stick to external scopes only (RS hosted). This term external/internal is our "invention", we can call it in other way.

**Comment by yurem** [comment]
We need to review this. @nynymike told that external scopes are scopes created via UMA API

**Comment by yuriyz** [comment]
@yurem external scopes are scopes hosted by RS (or any other server different from AS). internal or external it's just our terminology which was actually introduced by me :).

**Comment by nynymike** [comment]
I think this internal | external select should be removed, because it's not used for anything.

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20810286/34e6e796-b82f-11e6-99ca-f976f53ab30d.png)

**Comment by yurem** [comment]
Commits looks fine, closing it
