### ISSUE TITLE
Changing "oxTrust acr" to "default" in "Default Authentication Method" Deletes oxTrustAuthenticationMode Entry

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#1311]
In 3.1.4 if you change the oxTrust acr to default, it will delete the entry entirely. This will prevent you from accessing oxTrust without adding the entry back manually in LDAP.

**Comment by syntrydy** [comment]
@afroDC **Default** isn't a valid value for **oxTrustAuthenticationMode**, so when you pick **Default** and hit **save**, the value save is **null** and when an entry's value is null, the entry can be useless hence. 

Let me fix that now.
