### ISSUE TITLE
It's possible to create OIDC scopes with duplicated names in oxTrust

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1323]
_Assigning both Gasmyr and Yuriy as I'm not sure whether it's web UI's or oxAuth's issue (or both)_

Environment:
CentOS 7.4, gluu-server-3.1.4-1-2.centos7

Steps to reproduce:

1. Log in to web UI

2. Move to "OpenID Connect ->  Scopes"

3. Create a new scope with the same name as an already existing scope.

Result:
The scope is created without successfully and has the same name (though a different `inum`)

Expected result:
Scopes' names should be unique as otherwise oxAuth won't be able to select the proper one when serving requests from RPs (perhaps if scopes would have an enable/disable trigger, it would make some sense, allowing to have several versions of the scope, still only one active at a time?)

**Comment by syntrydy** [comment]
@aliaksander-samuseu This issue is duplicated with this https://github.com/GluuFederation/oxTrust/issues/1322
