### ISSUE TITLE
Configuration > Certificates enhancements

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1328]
- We don't need 'Shibboleth IDP SAML Certification' information. 
   - We need information of `idp-signing.crt` 
   - We need information of `idp-encryption.crt`

 - 'If possible'; add a feature which will allow user to 'download' cert from there. Say... if anyone 'click' on 'HTTPD SSL' cert; it will download 'httpd.crt'. Same for others. 

note: Please create separate issue if required for 2nd feature request. 

![certlocation](https://user-images.githubusercontent.com/7156097/48021040-26f8fe00-e0fd-11e8-895c-95694c3ef271.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50173574-34a6c380-02f8-11e9-94bb-0a8373384a9c.png)

![image](https://user-images.githubusercontent.com/7513418/50173631-51db9200-02f8-11e9-86ce-3ab5186caf89.png)

**Comment by syntrydy** [comment]
@mzico  https://github.com/GluuFederation/oxTrust/issues/1421

**Comment by shmorri** [comment]
Documented here:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/certificate.md#certificates-in-oxtrust
