### ISSUE TITLE
should localhost be allowed in redirect uri for clients?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1332]
According to OIDC core spec 1.0:

> 3.2.2.1.  Authentication Request
> ...
> redirect_uri
>    REQUIRED. Redirection URI to which the response will be sent. This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of [RFC3986] (Simple String Comparison). When using this flow, the Redirection URI MUST NOT use the http scheme unless the Client is a native application, in which case it MAY use the http: scheme with localhost as the hostname. 

Currently oxTrust does not let you to provide localhost in redirect_uri, should we account for the special case above?

**Comment by yurem** [comment]
Can you share real use case. Server can't sen AuthZ response to localhost.

**Comment by jgomer2001** [comment]
right, It's only conceptual (to align more closely to spec). Like a special case of native apps. where it says:

>  is a native application, in which case it MAY use the http: scheme with localhost as the hostname.

Also, I recently found this interesting draft spec https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12 where in theory we could use http://127.0.0.1/... (see section 7.3) for redirect_uri

**Comment by nynymike** [comment]
Yes, it should. In a javascript client in the browser, localhost would be used. I thought this requirement had already been relaxed.

**Comment by yurem** [comment]
I believe we need to allow this for native application only. Am I right?

**Comment by yurem** [comment]
I added successfully in recent code `http://localhost`
