### ISSUE TITLE
Add `password` field for Redis cache configuration

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1340]
We need to add `password` field for Redis cache configuration

https://github.com/GluuFederation/oxAuth/issues/785
https://github.com/GluuFederation/oxCore/blob/b2528361e295e84a2cf881ad187d62c735318d05/oxService/src/main/java/org/xdi/service/cache/RedisConfiguration.java#L21

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/49239210-6c5dd200-f402-11e8-98b4-a1683e0d574c.png)
