### ISSUE TITLE
Unify user email templates

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1344]
Right now we have one improved email template for **password reset** that uses the user name and good formatting:

<img width="647" alt="pwd_reset_mail" src="https://user-images.githubusercontent.com/38302725/48447268-61186e80-e793-11e8-8743-8ba7a85c8d33.png">

Can we do the same with the rest of the confirmation emails we send to users, e.g. registration **confirmation email**:

<img width="948" alt="reg_confirm_mail" src="https://user-images.githubusercontent.com/38302725/48447376-a50b7380-e793-11e8-8efc-586640f1ef92.png">
It could be something like "Hi [name],
A user has been registered for [email]. Click the following link to confirm it: [link]"

or make **smtp config email**:

<img width="584" alt="smtp_config_email" src="https://user-images.githubusercontent.com/38302725/48447396-b18fcc00-e793-11e8-8d49-8525836c97cb.png">

something like this: "Hi [name],
your SMTP server configuration has been successfully verified.

**Also, it would be great to have all of the email strings in one file so that it would be easier to compare/edit them if necessary.**

**Comment by syntrydy** [comment]
Here is the template i propose for user registration mail.

![image](https://user-images.githubusercontent.com/7513418/48659713-a8358680-ea55-11e8-9a8e-ca29677acf51.png)

**Comment by syntrydy** [comment]
We don't have to customize this one, only admin see this, No useful even if it is write in Hexadecimal.
The goal is just to test **The mail server settings is correct and messages can be send out**.
![image](https://user-images.githubusercontent.com/7513418/48660621-103f9900-ea65-11e8-9bbe-70850fbf3f7f.png)
