### ISSUE TITLE
CE 3.1.4: recaptcha doesn't disappear from resetPassword form

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1345]
In Manage Authentication -> Manage Captcha we have a radio button to **Disable Captcha for Password Reminder form**. However, it doesn't seem to be working on the resetPassword form:

<img width="873" alt="resetpassword" src="https://user-images.githubusercontent.com/38302725/48452780-84014d80-e7a8-11e8-8e13-184e7ad0a17c.png">

@syntrydy, is this by design?

**Comment by syntrydy** [comment]
@natt-tester may be you can rephrase, i don't get what you mean.

**Comment by natt-tester** [comment]
@syntrydy Sure, my point is: when you **Disable Captcha for Password Reminder form**, it disappears from passwordReminder. When you follow the flow and get to the resetPassword form, however, you can see that the recaptcha is there.

**The question is:** should the recaptcha also disappear from the resetPassword form when you tick **Disable Captcha for Password Reminder form**, or should it stay there as long as it's configured in the JSON?
