### ISSUE TITLE
The password reset message should be neutral

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1347]
If the user enters a known email address the page reloads with the "Please Check your Email for Password Reset Link" message, but if the user enters an unknown email address the page reloads without showing any message at all. 

The message should be neutral in both cases:
Like this: **Please Check your Email for Password Reset Link**.
We don't want user to play the guessing game, they should know their **email**.

One more thing we can do to make sure user enter a correct email is this:
- First field: **Enter your email**
- Second field: **Confirm your email**

**Comment by willow9886** [comment]
@yurem i thought we already fixed this flow? Can you comment here?
