### ISSUE TITLE
Store user pictures in FS

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#135]
Currently we stores picture in LDAP as user attribute. We need to store them in  FS.

We added API org.gluu.oxtrust.ldap.service.ImageRepository long time ago to work with images repository. We need to use it to store images in FS instead of storing it in LDAP.

Here is full plan:
1) Review ImageRepository API. We added it 5 years ago. Maybe we need to improve something in it.
2) Store in user entry path in the repo to image.
3) Find all places in oxTrust (including SCIM too) where we remove users to remove image from repo too.

The parent issue is: https://github.com/GluuFederation/oxTrust/issues/94

**Comment by willow9886** [comment]
@yurem who should we assign this to?

**Comment by yurem** [comment]
I think we should do next:
1) Review org.gluu.oxtrust.ldap.service.ImageRepository to allow use it in oxAuth/oxTrust For example we can remove @Create annotation from this class and inhereti it in oxAuth and oxTrust to allow initialize properly. Also we need to review it. Maybe we need to improve something in it.
2) Update oxTrust to use this API to store images Some information in attribute + relative path of the image in repository.
3) Review oxAuth to use these new picture attributes
4) Review SCIM to work on similar to oxTrust way.

**Comment by yurem** [comment]
Points 1-3 is one task. But point 4 we should do after finishing previous steps. It's independents step.
For 1-3 I offer to assign @qbert2k because he knows both oxAuth/oxTrust and knows how oxAuth should return picture claims.
For point 4 I offer to assign @shekhar16

**Comment by nynymike** [comment]
This feature is just not that critical. It can wait until 3.1

**Comment by nynymike** [comment]
Another caveat... oxTrust may not be user facing. Photos would have to be published somewhere public...

**Comment by yurem** [comment]
It's old issue. We need to review it from cluster perspective. Also it's not critical part because there is no requests to fix it. I offer to close it.

**Comment by nynymike** [comment]
If we decide to support this feature, we should design a new solution from the top down.
