### ISSUE TITLE
CE3.1.4: Missing Authentication Methods

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1359]
@syntrydy, turns out the list of enrolled devices for Authentication Methods is missing from oxTrust's user profile inspected by admin. It should look like this (view from 3.1.3.1):

<img width="697" alt="auth_list" src="https://user-images.githubusercontent.com/38302725/48694944-d96aae00-ec31-11e8-898c-ff7aeb7ce857.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/48703248-67737400-ebf3-11e8-9a1c-6d7966a2cb4b.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/48710069-8f6cd280-ec07-11e8-81d1-6b56a3bcce60.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/48710561-0fe00300-ec09-11e8-95c6-5876288cc9f1.png)
