### ISSUE TITLE
Update form to edit a Client, there are missing attributes

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#136]
This form must be updated to allow edit the complete set of Client attributes.

**Comment by qbert2k** [comment]
Trying to change Authentication Method in admin tool doesn't work. When I click Update Pre-Authorization value of "Trusted Client" drop down for some reason is displayed in red with message "value is required".

**Comment by willow9886** [comment]
Is this also related to issue #99 ?

**Comment by nynymike** [comment]
Well, client registration managment in general is not ideal. But this is just a bug.

**Comment by yurem** [comment]
yes #99 is the same

**Comment by nynymike** [comment]
#99 is a complete re-write of the page. I think to fix this bug, we just need to edit the xhtml page and remove one item from the dropdown list.
