### ISSUE TITLE
Refactor Authentication Methods list in person form

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1366]
We need to review code which we use to display `Authentication Methods`. In current code there are hardcoded parts which expects that script name should exactly match. Also we can remove  from person entry:
    
    @LdapJsonObject
    @LdapAttribute(name = "oxOTPDevices")
    private OTPDevice  oxOTPDevices;
    
    @LdapAttribute(name = "oxMobileDevices")
    private String oxMobileDevices;

I think so, because custom script form and auth method enrollments never update these attributes.

**Comment by shmorri** [comment]
oxTrust is being fully refactored as the new Admin UI
