### ISSUE TITLE
Cache Refresh Logs not descriptive

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#137]
1) In cache refresh logs, it says "LDAP connection Error", but there can be many ldap servers--backend + inumdb, so its hard to figure out which one is the problem. It would be better if the hostname + port is given in the log for a given connection error.

2) Validation errors do not show up in the logs at all. This is a problem, because with the accoridian style logs, you may not expand the tab that has the problem to see the error. If there is any way to send form validation errors to the cache-refresh logs, that would be helpful.

**Comment by yurem** [comment]
Every backed in our configuration has name. We can use it.

**Comment by zamilskhan** [comment]
is it fixed?

**Comment by aliaksander-samuseu** [comment]
Shouldn't this one be closed? It's old, and hese is what currently in my CR logs:

Failed to connect to LDAP server using configuration 'source'

So it's probably fixed
