### ISSUE TITLE
Add a way to list/delete users pairIdentifiers

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1382]
Admin should be able to list/delete users pairIdentifiers.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/49602522-f7057a80-f988-11e8-9767-3632b9d5d6df.png)

**Comment by shmorri** [comment]
Documented here: https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/user-management/local-user-management.md#manage-people-in-oxtrust
