### ISSUE TITLE
Oops when uploading ldif

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1387]
@syntrydy, could you check the following behavior:

**Steps:**
1. Log in to oxtrust
2. Go to Import/Export Attributes
3.  Click on one of the buttons several times.

Expected: There's no error.
Actual: There is an Oops page thrown:
[oxtrust(1).log](https://github.com/GluuFederation/oxTrust/files/2661099/oxtrust.1.log)

gluu-server-3.1.5_3, reproduced in Ubuntu16 and Centos6

**Comment by syntrydy** [comment]
@natt-tester i wasn't able to replicate this issue.

**Comment by natt-tester** [comment]
Closing the issue, not reproducible in other 3.1.5_2 installations.

**Comment by natt-tester** [comment]
Reopening because of #1029

**Comment by natt-tester** [comment]
Checked in 3.1.5_4 and cannot reproduce it anymore. It's DONE.
