### ISSUE TITLE
Consolidate oxAuth / oxTrust login pages

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#139]
- Lets use the default oxtrust login page design for oxauth.
- The logo added in config > org config should be displaed on the default login screen
- Lets include the favicon image (as set in config > org config) in the new login page template.

**Comment by willow9886** [comment]
@yurem should we keep this open? if so, will it make it into 3.0 or should we move it to a later release?

**Comment by nynymike** [comment]
This was done.
