### ISSUE TITLE
Clicking through tabs on "Manage Custom Scripts" page throwing JS Error

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#140]
Screenshots and supporting text can be found here: https://trello.com/c/xD6b9qC9/125-bug-manage-custom-scripts-throwing-js-error

1. The issue is triggered by simply clicking through tabs in the custom scripts interface, it has nothing to do with any specific tab, it seems that selecting any tab presents a chance to trigger the bug.
2. I haven't been able to find a solid way to reproduce it, but it seems to me that you have a higher chance to achieve it by changing tabs rapidly. When it's triggered the error message appears similar to the one on the screenshot @Mike provided. See [a fragment of wrapper log](https://github.com/GluuFederation/oxTrust/files/67892/custom_scripts_exept1.1.txt) with java exception supposedly related to the error
3. When a user selects any tab at all some strange exception is being logged to wrapper.log (see 
[a fragment](https://github.com/GluuFederation/oxTrust/files/67894/custom_scripts_exept2.1.txt)).
4. Switching from tab to tab takes a lot of time, and in case you start to do it quickly enough this time rapidly grows to the point when you can't even change a tab anymore. Sometimes it even results in such prolonged UI's locks that it's easier to simply reload the page.' This issue actually predates new UI by a great margin. It was first discovered months ago, and errors from the second log fragment were also there back then. Though the 2nd error (the one Mike reported initially) is a new one.
![upload_10_15_2015_at_2_44_49_pm 1](https://cloud.githubusercontent.com/assets/11802046/11919152/e4241fc6-a75a-11e5-9711-2fd6901a4b6b.png)
![upload_11_17_2015_at_9_18_13_am 1](https://cloud.githubusercontent.com/assets/11802046/11919155/ead3f8aa-a75a-11e5-87bf-d7629f8c7cf0.png)

**Comment by shekhar16** [comment]
Could not able to reproduce this issue.

**Comment by willow9886** [comment]
OK, thanks @shekhar16. @mzico can you keep an eye out for this error and if you see it again re-open this ticket. Thanks!

**Comment by mzico** [comment]
@willow9886 : Sure

**Comment by willow9886** [comment]
I was able to replicate today... See screenshot below:

![image](https://cloud.githubusercontent.com/assets/5271048/14357790/b8e1c5c0-fcaf-11e5-9447-a7179e20c8e3.png)


This is in the ce-release.gluu.org server. 

All I did to see these error messages was:
1) Navigate to custom scripts 
2) Click update user tab
3) then click user registration tab relatively quickly.

**Comment by zamilskhan** [comment]
#237 I got the same error

**Comment by aliaksander-samuseu** [comment]
Just checked it in 2.4.3-1-3 - still throws errors if tabs are changed quickly, switching between tabs is still slow and UI tends to freeze after some time of switching between them.

**Comment by shekhar16** [comment]
Fixed.
@willow9886 @mzico @zamilskhan @aliaksander-samuseu  Please try it again.

**Comment by yurem** [comment]
@shekhar16 , please add link to your issue fixes. It will be easier to understand which build should we retest. Also this allows to review changes.

**Comment by shekhar16** [comment]
@yurem https://github.com/GluuFederation/oxCore/commit/83cd80b27091e242ed5e6fc0cc001f3249ace74c

**Comment by willow9886** [comment]
@yurem can you confirm Shekhar's fixes? Thanks!

**Comment by yurem** [comment]
According to the code it should fix NPE. I saw this issue many times before. Use case:
1) Open scitps page
2) Click on the tabs quickly

Now there is no this error.
