### ISSUE TITLE
Reorder oxTrust log level

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1400]
Under **Oxtrust Json configuration** from the Gluu Admin ui,
The **loggingLevel** field looks like this:
![test](https://user-images.githubusercontent.com/7513418/49789256-d7c17100-fd2b-11e8-8c74-5a90ceda36bf.png)

We have to reorder that list:
```
TRACE –  log all messages.
DEBUG – log all debug level messages and above.
INFO – log all informational level messages and above.
WARN – log all warning level messages and above.
ERROR – log all error level messages and above.
FATAL – log only fatal error messages.
OFF – disable logging.
```

**Comment by syntrydy** [comment]
One part done here https://github.com/GluuFederation/community-edition-setup/issues/503

**Comment by shmorri** [comment]
Documented here:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/operation/logs.md#log-levels
