### ISSUE TITLE
Add more space between elements in Certificates view 

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1417]
Please add more space between the elements below:

<img width="651" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50132761-faeaa400-0288-11e9-9371-9cde46ff8594.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50163228-42504f00-02e0-11e9-963d-025aab1a4730.png)
