### ISSUE TITLE
remove "inum" attribute from personal > profile

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#142]
![](https://trello-attachments.s3.amazonaws.com/563d15e22c6f5358d25bbde7/1730x890/900b2c5369c12b59c1108cb10f362910/upload_11_6_2015_at_3_04_38_PM.png)

The inum field showed in the above screenshot does not need to be visible to the user.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14937009/2c982926-0f18-11e6-8b9e-2d9d3edac25c.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by mzico** [comment]
Just perfect. Thanks @shekhar16!
