### ISSUE TITLE
Add ability to download a certificate from the list of cert

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1421]
# Description

Admin want the ability to download a cert from the list of certs.

# Steps

- Login to oxTrust Admin Ui
- Navigate to **Configuration > Certificates**
- You can see a list a cert

We need a way to download a given certs from the list.

**Comment by syntrydy** [comment]
@mzico you can track that feature here.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50439295-d2e6ea80-08f1-11e9-8e51-c49737b4f1b8.png)

**Comment by shmorri** [comment]
Documented here:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/certificate.md#certificates-in-oxtrust
