### ISSUE TITLE
Nav bar doesn't stick to tab in Custom Scripts

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1423]
Steps:

1. Log in to Gluu Server
2. Go to Manage Custom Scripts
3. Click on one tab on the far right

Expected: The navigation bar's position corresponds with the location of the chosen tab.
Actual: The navigation bar goes back to the far left.

**Comment by syntrydy** [comment]
@natt-tester  there is no solution for that issue at the moment, i will try again later.
