### ISSUE TITLE
Password requirement feature

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1429]
It will be great if we can add couple of rules for password creation with oxTrust. Something like: 

 - Password should be between 8 chars to 60 chars. 
 - Passwords must contain a combination of lower case letters, upper case letters, numbers, and at least one symbol. ( Not exactly about symbol, don't know how it might behave with other component of Gluu Server ) 
 - Password cannot match UID or email_Address. 

i am not labeling this feature because I don't know how hard it might be from code level; so please feel free to assign label whichever is sufficient.

**Comment by mzico** [comment]
For review: @nynymike @yurem @willow9886 @aliaksander-samuseu @afroDC

**Comment by nynymike** [comment]
Adding users is not something to encourage through oxTrust.
