### ISSUE TITLE
Remove references to login.htm 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#143]
See reference to login.html at the following locations: 

https://github.com/GluuFederation/oxTrust/blob/edf471fec2e5d350be721f732b1475661f4bb0c2/server/src/main/webapp/index.html

https://github.com/GluuFederation/oxTrust/blob/edf471fec2e5d350be721f732b1475661f4bb0c2/server/src/test/java/org/gluu/oxtrust/action/test/AbstractAuthorizationTest.java

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxTrust/commit/11dfb133c14f92f91f477cd29f7357714fe74ccd
