### ISSUE TITLE
Regex validation of attribute leads to Error Page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1434]
Based on [this ](https://support.gluu.org/identity-management/6445/regex-validation-of-attribute-leads-to-error-page/#at42884) ticket, 

Whenever the following Regex is passed in for attribute validation , upon an erroneous string being passed, Identity crashes and we're sent to an error page:
```
(((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+))|((?=.*[0-9]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+)(?=.*[a-zA-Z]+)|((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[0-9]+))))[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/a-zA-Z0-9]{8,}
```

Steps to reproduce -

Go to Oxtrust > attributes, and add the above regular expression to nickname field. Create a user and provide invalid value to nickname, and hit save.

![image](https://user-images.githubusercontent.com/21104811/50368493-46fe5700-05af-11e9-8203-39ea3d50a0a8.png)

oxtrust logs
2018-12-22 00:13:00,186 INFO  [qtp985655350-17] [org.gluu.oxtrust.ldap.service.OrganizationService] (OrganizationService.java:233) - Starting App version 3.1.2.Final
2018-12-22 00:28:42,737 ERROR [qtp985655350-13] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - java.util.regex.PatternSyntaxException: Unclosed character class near index 252
(((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+))|((?=.*[0-9]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+)(?=.*[a-zA-Z]+)|((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[0-9]+))))[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/a-zA-Z0-9]{8,}

                                                                                                                 ^
javax.faces.FacesException: java.util.regex.PatternSyntaxException: Unclosed character class near index 252
(((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+))|((?=.*[0-9]+)(?=.*[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/]+)(?=.*[a-zA-Z]+)|((?=.*[a-z]+)(?=.*[A-Z]+)(?=.*[0-9]+))))[`~!@#$%^&*()\-+={}[\x22\x5D\x5F\\|:;',.?/a-zA-Z0-9]{8,}

                                                                                                                 ^
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:84) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]

**Comment by syntrydy** [comment]
@sahiliamsso that regular expression isn't correct

**Comment by sahiliamsso** [comment]
In that case, a valid error must be thrown instead of generic error page.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50546564-e95eb000-0c29-11e9-9bcf-36fcce3f67ff.png)
