### ISSUE TITLE
Error when saving customized set of registration form's attributes

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#144]
![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b99aa372b44c07c33b6eb/x/7729bc8831b0db110bab8a1af11b2cb1/manreg-update-error.png)

see screenshot.

**Comment by willow9886** [comment]
@aliaksander-samuseu can you also comment on whether this is still a bug?

**Comment by aliaksander-samuseu** [comment]
@willow9886 It is at least for deb package gluu-server-2.4.1 All described issues are still there.
