### ISSUE TITLE
User Registration Email link with random number always displays REGISTRATION COMPLETED

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1446]
<Gluu Server>/identity/confirm/registration?code={randomcode}, will always generate the following page
![image](https://user-images.githubusercontent.com/21104811/50593363-1a571300-0ebe-11e9-9db0-1a357772d24a.png)

Expected Outcome should be => This registration code is not valid or expired. Please contact site administrator

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50632103-18856200-0f47-11e9-9820-ba49a225913c.png)
