### ISSUE TITLE
List of attributes for "Registration form attributes" feature is being reset when another filter string is chosen

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#145]
![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b99bab9406499b4a11bf9/x/66a2ba90d2454c19fdaf4609eb3f6a87/manreg-update-error.png)

see screenshot.

**Comment by willow9886** [comment]
@aliaksander-samuseu is this still a bug? We couldn't reproduce...

**Comment by aliaksander-samuseu** [comment]
@willow9886 yes it is. I can reproduce it for deb package gluu-server-2.4.1 Here is a video capture: [link](https://drive.google.com/file/d/0B6Mqu38YJ8RcRjdRR3hPV3lFLUk/view?usp=sharing)

**Comment by willow9886** [comment]
ok, assigning to @yurem and adding it to our milestone for 2.4.2

**Comment by aliaksander-samuseu** [comment]
@willow9886 @yurem Just wanted to note that I reproduced it on ce-release. I suppose the most recent build is deployed there, is it correct?

**Comment by willow9886** [comment]
We also need to update the look and feel of the attributes tables.

**Comment by shekhar16** [comment]
Fixed : update button is now working properly and the selected items are not resetting
