### ISSUE TITLE
Force required permissions in jsf pages

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1456]
Right now html pages has action like this:
<f:viewAction action="#{permissionService.hasPermission(target, action)}"/>

But this method returns true/false only. We need to add new method `requestPermission` to permissionService which should throw SecurityEvaluationException when EL expression return false.

Also after that we need to do global replace in all xhtml: permissionService.hasPermission -> permissionService.requestPermission

**Comment by syntrydy** [comment]
@yurem when i check few xhtml pages there is call for **<f:viewAction action="#{permissionService.hasPermission(target, action)}"/>** in them. However that method is call from the leftmenu.xhtml page here https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/WEB-INF/incl/layout/leftmenu.xhtml#L46.
When you  say **....should throw SecurityEvaluationException when EL expression return false.**, Which    EL expression.

**Comment by yurem** [comment]
This line we should not change because here we prepare value for rendered attribute
