### ISSUE TITLE
JSON Config field to disable/enable FIDO2 Endpoints is not clear

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1457]
Currently, the field to disable/enable FIDO2 endpoints in oxTrust is confusingly labeled. Right now it simply looks like this:

![image](https://user-images.githubusercontent.com/36208047/50711411-c2421d00-1033-11e9-9ae6-24ccdbc35b7d.png)

I think that calling the field `disableFido2` or something similar would be a little less confusing, rather than just the single ambiguous word.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/50721981-d3893900-10c8-11e9-8d24-e2f21623ae0e.png)
