### ISSUE TITLE
Clean up JSON schema configuration files

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#146]
https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json

These are 2 JSON schema files which we uses in oxTrust to display configuration.

We need to add title, description, min, max, validations… More information about JSON schemas you can find here: http://json-schema.org

**Comment by qbert2k** [comment]
Hello William the task is complete and merged into the master branch.
Also I have added description for all the properties in the oxAuth config schema.
