### ISSUE TITLE
couchebase with multiple buckets

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1461]
I could not run 4.0 with multiple couchebase buckets. With single bucked, it works well with single bucket.

**Comment by yurem** [comment]
Is it setup or application issue? Is setup able to create multiple buckets?

**Comment by mbaser** [comment]
Yes, setup.py can create multiple buckets, I commented them, most probably a config issue:
https://github.com/GluuFederation/community-edition-setup/blob/952b973a7ddff39fbab6e66a75bfc9f4cc526ea5/setup.py#L3875

**Comment by yurem** [comment]
Fixed
