### ISSUE TITLE
UMA Interface overlapping 'x' 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#147]
![](https://trello-attachments.s3.amazonaws.com/564b70c64c10e88baf2261d4/1920x1152/0af986d2448f542a9e3110135b85a153/upload_11_17_2015_at_12_24_25_PM.png)

see overlapping 'x' in the UMA user interface.

**Comment by shekhar16** [comment]
HI William,
I checked the issue,but i couldn't able to reproduce it.
It is working fine for Firefox,IE,Chrome.
![image](https://cloud.githubusercontent.com/assets/15937500/12702708/e7f92300-c855-11e5-94db-95d7b96da730.png)

**Comment by nynymike** [comment]
Did you try to increase the font size?

**Comment by shekhar16** [comment]
yeah i tried it with zoom as well here is snap shot.

![image](https://cloud.githubusercontent.com/assets/15937500/12720842/c698461e-c922-11e5-9053-38a4507e88d4.png)

**Comment by willow9886** [comment]
thanks @shekhar16 closing this issue then.
