### ISSUE TITLE
Issues after two successive logoffs take place

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1474]
I faced a couple of issues when testing an application, and using oxTrust at the same time 

Not sure if this is a general CE issue (arbitrary applications) or if this is exclusively when oxTrust is present. In that case, this might be related to #1473 

Suppose app A (using a client requisting an acr with level = 1).  Particularly for log out, this app uses "RP-Initiated Logout" as described in section 5 of [spec](http://openid.net/specs/openid-connect-session-1_0.html). 

Suppose oxTrust as it comes by default in CE (default acr level = -1)

Here I list some flows with the corresponding outcomes after the 2nd logout (**4th** step takes place):

---
*Flow 1*

1. Login to app A
1. Login to oxTrust
1. Logout from app A 
1. Logout from oxTrust

In this case, no thank-you-page is shown. Browser is taken directly to the SSO login form

---
*Flow 2*

1. Login to app A
1. Login to oxTrust
1. Logout from oxTrust
1. Logout from app A 

The browser shows

```
{"error":"post_logout_uri_not_associated_with_client","error_description":"The provided post logout uri is
 not associated with client.","reason":"Session was removed successfully but redirect to post_logout_redirect_uri fails since AS failed to validate it against clients associated with session (which
 was just removed)."}
```

---
*Flow 3*

1. Login to oxTrust
1. Login to app A
1. Logout from oxTrust
1. Logout from app A 

Again this appears:

```
{"error":"post_logout_uri_not_associated_with_client","error_description":"The provided post logout uri is
 not associated with client.","reason":"Session was removed successfully but redirect to 
post_logout_redirect_uri fails since AS failed to validate it against clients associated with session (which
 was just removed)."}
```

---
*Flow 4*

1. Login to oxTrust
1. Login to app A
1. Logout from app A 
1. Logout from oxTrust

```
{"error":"invalid_grant_and_session","error_description":"The provided access token and session state are
 invalid or were issued to another client.","reason":"Failed to identify session by session_id query 
parameter or by session_id cookie."}
```

**Comment by yurem** [comment]
@jgomer2001 Here is ticket with same or similar issue description

**Comment by jgomer2001** [comment]
@yurem After your latest oxauth/oxtrust update, the situation changed in the following way:

Flow 1: it works fine. Oxtrust shows the thank-you page

Flow 2, 3, and4: they all show the following error:
```
{"error":"invalid_grant_and_session","error_description":"
The provided access token and session state are invalid or were issued to another client.",
"reason":"Failed to identify session by session_id query parameter or by session_id cookie."}
```

**Comment by yurem** [comment]
I think the main issue flow 1 was resolved. Now oxAuth end_sesison works according to coded rule.

I open oxAuth issue https://github.com/GluuFederation/oxAuth/issues/992 to discuss how we can add second logout support.

**Comment by jgomer2001** [comment]
With latest oxauth/oxtrust wars (3.1.6), the problems in flow 4 persists
