### ISSUE TITLE
Oops page when deleting user

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1478]
Every time I try to delete a user, I'm bounced to the oops. Environment: Gluu CE 3.1.5 on xenial

Log attached

Also, there are so many identical log statements like "Checking permissions for target 'configuration' an 'action'. Identity: access". Can we enhance this?

[oxtrust.log](https://github.com/GluuFederation/oxTrust/files/2783734/oxtrust.log)

**Comment by syntrydy** [comment]
@jgomer2001 please provide the ldif of that user entry from LDAP

**Comment by willow9886** [comment]
@jgomer2001 this issue might be fixed with @syntrydy 's latest update to the war. We tested in `dc` and deleting works now.
