### ISSUE TITLE
Bug in OpenID Connect Add Scopes pop-up window

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#148]
![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b99da570cf723d08e841d/x/83b7c56ca418fb50398e714226eaa672/scope-popup.png)

"Add scopes" pop-up doesn't scale well to the current dimensions of browser's window. The pop-up appears after the button "Add scope" is clicked on the new client creation page. The issue arises when user simply clicks the "Search" button to display the full list of available scopes (without providing filter string).

In addition, the iNums of the scopes being displayed are truncated. Please see attached picture for details.

**Comment by shekhar16** [comment]
Can you please tell, how you reach to this popup.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/12531285/68413d58-c21c-11e5-914e-1f2b8d065640.png)

I fixed the issue, please take a look on the attached snapshot.

**Comment by willow9886** [comment]
Great, thanks Shekhar.
