### ISSUE TITLE
Enhance how 2uf devices are displayed in user's profile

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1484]
Currently we are showing something like 

![u2f](https://user-images.githubusercontent.com/5444180/51610026-a373cf80-1ee9-11e9-9f71-eff6ae86ed6e.png)

Can we fill some (or all) of the missing fields? Under fido branch at every user, there is all data needed. We can use `oxId` for "Id" column, `displayName` for "nickname", and `creationDate` for "date added". See `oxDeviceRegistration` ldap object class for more info. 

If you want to go further you can use for modality "Super Gluu Device" or "Security key" if `oxDeviceData` is present or absent in the entry respectively.

**Comment by syntrydy** [comment]
Fixed

**Comment by jgomer2001** [comment]
Much better. Upon clicking on the Id of device, a modal window like this appear:
![device detail](https://user-images.githubusercontent.com/5444180/51680970-417e9d00-1fb1-11e9-9825-48d966ce6a8f.png)


I'm not sure if we need to display pulic key and attestation cert, what do you think @yurem and @willow9886 

The modal occupies a lot of space but it's not making effective use of it, maybe we can improve somehow.

**Comment by willow9886** [comment]
I can't think of any reason an admin would need to see the public key here.. not sure about attestation cert. @jgomer2001 @yurem
