### ISSUE TITLE
Add feature to refresh logs in oxtrust viewer 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#149]
There's currently no obvious way to either update a log the user is viewing, or set some update interval for it can be found; by refreshing the page the log selection page is loaded, so additional efforts are required to open the needed log again.

Refreshing the page should load the same log you were viewing. Ability to set refresh interval would be useful too. 

@aliaksander-samuseu can you provide some further details on this? Perhaps a screenshot or something?

**Comment by aliaksander-samuseu** [comment]
I'm not sure if it needs one. What I meant is when you open any log in oxTrust it's just a page where a fragment of it is shown. The displayed part of it never updates by itself, and there are no controls there, like buttons, to refresh it. When you just press F5 key in attempt to update the page it takes you back to the log selection screen in the end (at least it's the case for my firefox). So you need to open the same log again to view it. So the whole sequence to update it takes a lot of unnecessary actions. Instead the log viewer page should just be refreshed automatically with some interval that should be configurable.

**Comment by nynymike** [comment]
Customers should ssh and use all the tools there to manage the logs. Log viewer should be a last resort. Let's wait for more customers to complain, and re-open if necessary.
