### ISSUE TITLE
Improvements in sector identifier and redirect uri assignment in oxTrust UI

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#1490]
**Describe the issue**
The assignment of Sector identifier and Redirect URI behavior has some inconsistencies that can be improved to enhance the user experience.

**Steps To Reproduce**

1.) When creating a client, add two or three redirects and save. Then go to create a new sector identifier. If you add the URLs before adding the client, and then click the client button to link the sector identifier to the client, it will re-load the URls from the client into the sector identifier. This would be useful but it also causes duplicate entires in it's current form.

2.) Similar scenario but in reverse: If I'm creating a client where I've already created the sector identifier first, it would be nice to be able click on a button to associate the sector identifier from gluu to the client without having to manually copy/paste in the redirect URLs into the client again. (import in a manner that also prevents dups)

3.) In oxtrust when clicking on "OpenID Connect" -> "Sector Identifier", you're presented with a list of Guids which don't really have any meaning. Can you add a name and/or desc field to sector identifiers to show in this list and in the individual sector identifier?

**Expected behavior**
1. When a sector identifier is linked with a client, it should load the client redirect uris into the sector identifier without add duplicates.

2. When a client is linked with a sector identifier, it should load the client redirect uris into the client metadata without add duplicates.

3. Add a description field for the sector identifiers and also show it in the sector identifier list UI.

**Additional context**
See ticket: https://support.gluu.org/identity-management/6601/minor-annoyances-in-oxsector-functionality/

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/52636562-3f7f6e00-2ecd-11e9-90b3-11e16a1922db.png)

![image](https://user-images.githubusercontent.com/7513418/52636611-6dfd4900-2ecd-11e9-8330-5a42fff6a0f9.png)

![image](https://user-images.githubusercontent.com/7513418/52636640-853c3680-2ecd-11e9-81fd-dbc88e0c923c.png)

![image](https://user-images.githubusercontent.com/7513418/52636693-9edd7e00-2ecd-11e9-9fdf-52d1a03e1479.png)
