### ISSUE TITLE
Wrong free memory status in Ubuntu 18

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1491]
![screenshot 3](https://user-images.githubusercontent.com/6104200/51968138-44caca80-2482-11e9-99a2-eb97e7ca27b3.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/52198914-ba5cdf00-2864-11e9-96d7-0af1ec81f68c.png)
