### ISSUE TITLE
Protected Gluu end points

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1494]
Following Gluu endpoints should be made protected. Also, we need to check all other end points and ensure that sensitive end points are not public

../passport/saml_config
../passport/passportstrategies

Issue is reproducible on following versions
3.1.2, 3.1.3, 3.1.4, 3.1.5

Note: **No** sensitive data is exposed via these endpoints.

**Comment by jgomer2001** [comment]
2 Passport endpoints do not need protection. They were removed and code adjusted, as per https://github.com/GluuFederation/oxAuth/issues/993

@yurem can you do an overall CE revision about any other data exposed anonymously
