### ISSUE TITLE
Add 'persistent' type NameID in oxTrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1495]
There are two types of nameID available in 'Configure Custom NameID' page. We need to add 'persistent' type as well.

NameFormat: `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` 

![untitled](https://user-images.githubusercontent.com/7156097/52181380-c2f6dc00-27b6-11e9-88af-52d5158dc2c8.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/52210314-ff920880-2886-11e9-9daa-92101f603e2a.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/52211407-16862a00-288a-11e9-9a65-d76bd33f8bea.png)
