### ISSUE TITLE
Fields crashing when adding new user with 'outside' attributes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1496]
This is happening when i am going to create users with more attributes other than default eight given in oxTrust. Email_address and Password fields go blank. 
![oxtrustusercustomattribute](https://user-images.githubusercontent.com/7156097/52181918-110ede00-27bd-11e9-8a77-cfa5374c4843.gif)

**Comment by syntrydy** [comment]
@mzico clearing both password field is normal for security reason.

I fixed the email field.
