### ISSUE TITLE
TR tabs user interface touch up

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#150]
![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b9a06aa00ca2781e5ceee/x/6eae8550477c2a3f5d1f2c26342f327a/tr-tabs-indent.png)

see screenshot.

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14434909/f1b6f60a-0032-11e6-93f4-4f1eec0e4f21.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14434922/016594d0-0033-11e6-8b21-5b6f04d20d51.png)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 , for which version it was fixed? I still see it in 2.4.3-1-3 deb package

**Comment by willow9886** [comment]
@shekhar16 re-assigning this ticket to you to confirm the fix with @aliaksander-samuseu

**Comment by shekhar16** [comment]
@aliaksander-samuseu  can u please give me your testing environment link.

**Comment by mzico** [comment]
@shekhar16 : Looks good. 

Working version: 

Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.3-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 9c43b
Archiver-Version: Plexus Archiver
