### ISSUE TITLE
Add SAML TR Logout profile

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1501]
It's last part of issue https://github.com/GluuFederation/oxShibboleth/issues/50
Previous issue we resolved in 3.1.5. But for better user experience we also need to update oxTrust GUI to allow configure SAML2 relaying party Logout profile.

**Comment by yurem** [comment]
Implemented

**Comment by willow9886** [comment]
@yurem this looks like the type of issue that should be tagged with at least `Needs documentation` and most likely also `Needs screenshots` .. can you confirm, and please make use of these tags regularly?

**Comment by yurem** [comment]
![screenshot 4](https://user-images.githubusercontent.com/6104200/52274478-e14b0c00-295d-11e9-8269-00c38a17eeac.png)

**Comment by yurem** [comment]
This section is needed for IDP->SP logout flow. With enabled Logout profile user can trigger IDP/SP/OP logout using URL like this `https://<idp>/idp/Authn/oxAuth/logout`.

Here is default logout IDP page after logout from  IDP/SP/OP:
![screenshot 5](https://user-images.githubusercontent.com/6104200/52274804-d2188e00-295e-11e9-8fd1-3eee4f7b0ad7.png)
