### ISSUE TITLE
Input fields protrude beyond the page's edge on the "Source backend ldap servers" tab

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#151]
![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b9a23779382d78189ec77/x/1ceb76b139e69c18446de55733c28c84/source-bn-gui-bug.png)

see screenshot.

**Comment by shekhar16** [comment]
Fixed,Input fields are adjusted similar to manage registration page fields.

**Comment by willow9886** [comment]
@shekhar16 If you've fixed this, should we go ahead and close the issue?
