### ISSUE TITLE
Client : add ability to specify client attributes as JSON

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1512]
**Describe the issue**
Now `oxAuthClient` OC has new attribute called `oxAttributes` [see](https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/java/org/xdi/oxauth/model/registration/Client.java#L213).

This attribute contains JSON, not single attribute. Idea is to avoid adding new LDAP attribute for each single client property. Now we will keep it as JSON. Therefore we need ability to render this JSON and specify client attributes as JSON on oxTrust side. Similar as we do it for oxauth JSON configuration.

https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/model/registration/ClientAttributes.java#L14

**Steps To Reproduce**
It's new feature, no steps to reproduce. JSON attributes are implemented for oxauth, we need support for oxtrust now.

**Expected behavior**
It must be possible to specify client attributes as JSON object which MUST reflect oxauth `org/xdi/oxauth/model/registration/ClientAttributes.java` class (see link above).

**Screenshots**
new feature, no screenshot

It must be included in 4.0 version.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/52789087-32948300-3063-11e9-8ce9-df815420f921.png)
