### ISSUE TITLE
'Import people' feature can't import multiple values of single attribute

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1513]
If we have some attribute with multiple value in xls file, oxTrust can't import multiple values. 
Screenshot below showing what it looks like when we are trying to import a xls file which has custom attribute named 'orvtroles' containing multiple attributes: 'Program Manager' and 'License Admin'. 

oxTrust loaded one attribute. 

![importuser](https://user-images.githubusercontent.com/7156097/52412746-4b21fd80-2aa5-11e9-8d9f-bfff64512007.PNG)

**Comment by sahiliamsso** [comment]
still see single value being populated on gluu-server-3.1.6_1-2~xenial+Ub16.04_amd64.deb
![image](https://user-images.githubusercontent.com/21104811/53494721-6496e380-3a6c-11e9-8096-535ed29b6a0f.png)
![image](https://user-images.githubusercontent.com/21104811/53494737-6bbdf180-3a6c-11e9-9215-9d100747f9d3.png)

**Comment by mzico** [comment]
@syntrydy : Create a quick doc on how to prepare xls sheet. After confirmation from @sahiliamsso , we can add that doc in our public repo. 

@sahiliamsso : wait for doc from Thomas on how to prepare xls sheet.

**Comment by syntrydy** [comment]
@shmorri please can you share the doc for this feature?

**Comment by willow9886** [comment]
@syntrydy this one: https://gluu.org/docs/ce/user-management/local-user-management/#file-structure 

?

**Comment by syntrydy** [comment]
No, i gave details about that feature to @shmorri last time. I don't know if the doc is ready.

**Comment by syntrydy** [comment]
@sahiliamsso in your excel sheet, you can't have two column with same name. Instead use only one column for **UserPermission** and if it's multi-value attribute just separate the values with **semi-coma** (;).

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/53548482-d9802100-3b31-11e9-9e8c-d9710cc4e573.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/53549164-ccfcc800-3b33-11e9-93e1-298fbc424c68.png)

**Comment by sahiliamsso** [comment]
worked now, Thanks

**Comment by shmorri** [comment]
Added on [this page](https://github.com/GluuFederation/docs-ce-prod/blob/3.1.6/docs/source/user-management/local-user-management.md#import-people-in-oxtrust) with clarifying screenshot
