### ISSUE TITLE
Improve UI when adding SAML TRs

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1521]
I think we can make a better use of space in the form for adding SAML trust relationships. This may avoid too many scrolls appearing. See screenshot above:

![scrolls2](https://user-images.githubusercontent.com/5444180/52795718-5b575100-3040-11e9-9c4a-ec5ff2cff292.png)

**Comment by shmorri** [comment]
No longer necessary since oxTrust is being replaced
