### ISSUE TITLE
Error during password reset

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1523]
## Describe the issue
Error during password reset feature.

## Steps To Reproduce
1. Login to admin UI
2. Setup SMTP configuration
3. Enable selfPassword reset
4. Create a user for testing 
5. Try to reset his password

## Expected behavior
The user password should be reset

## Actual behavior
**OOps error message is receive on the reset form**

## Screenshots
![image](https://user-images.githubusercontent.com/7513418/52905333-14807b80-3239-11e9-80e5-542ca0685fa1.png)

## Desktop (please complete the following information):
 - OS:Centos
 - Gluu version: 3.1.6

**Comment by sahiliamsso** [comment]
@syntrydy - After changing password, I am immediately redirected to login screen.  I am not getting any message if password change is successful or not
