### ISSUE TITLE
Make profile update safer

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1525]
There are cases where profile update in oxTrust can override changes performed by other apps. 

Casa, apps using SCIM API, or other customer applications that edit user entries can be affected by how oxTrust applies LDAP modifications.

As an example suppose this flow:

1. Login to casa, visit the OTP tokens page, choose soft token, then press "ready"
1. Scan the QR code with the OTP app
1. Enter the code in the text field and press "validate"
1. In a separate browsing session, login to oxTrust as admin and go to the profile edition page for the user of step 1
1. Back to Casa, enter a nickname for the OTP device and press "add" (this will make the user LDAP entry to be updated)
1. In oxTrust form, edit a field, say "gender", and press update (this will overwrite the user LDAP entry losing the changes applied by previous step)
1. Reload the OTP tokens page in Casa. The enrollment is not there...

While this may happen unfrequently, it is a good spot for enhancement due to potential data loss.

**Comment by shmorri** [comment]
This is no longer necessary due to UI redesign
