### ISSUE TITLE
Changing OpenID Client secret don't work

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1527]
## Describe the issue
Changing OpenID Client secret don't work

## Steps To Reproduce
1. Log into Gluu server Admin UI
2. Add a new OpenID client with **secret** as client secret
3. Save the changes
4. Change the client secret to **changeit** and save the changes
5. Load that client details

## Expected behavior
The client secret is **changeit**

## Actual behavior
The client secret is still **secret**
## Screenshots
![image](https://user-images.githubusercontent.com/7513418/53015841-5d5c4e00-344c-11e9-9b04-024c4df56226.png)

## Gluu details
- Gluu server 3.1.6

**Comment by sahiliamsso** [comment]
Can we make "Client Secret" not an editable field. Currently I it is allowing me to update the password without using "Change Client Secret".
Step:
Edit the client, Type the password in Client Secret
![image](https://user-images.githubusercontent.com/21104811/53492276-77a6b500-3a66-11e9-967f-35ba8052dda2.png)
Click update button

**Comment by willow9886** [comment]
@sahiliamsso @syntrydy  agreed, see my issue https://github.com/GluuFederation/oxTrust/issues/1535 we need to lock these fields once set so they cant be changed inadvertently.
