### ISSUE TITLE
Create passport forms as needed

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1531]
According to our plan for passport revamp, we have to offer means so that passport parameterization takes place in oxtrust

Currently we have a "Passport Authentication Method" tab in  `Configuration` > `Manage Authentication` to supply oauth identity providers parameters, but now we have to handle 2 extra things:

- General configuration
- IDP-initiated flows configuration

as well as including support for SAML providers (aka IDPs), and OP providers when using oxd as mediator

I already proposed: 

> ... to add an Inbound identity section to oxTrust menu when passport is enabled.

It is up to you how to better layout the scenarios needed.

I split this task in the following issues:
#1532 
#1533 
#1534 

**Important**

As mentioned in the roadmap, we will store all data in a single json in LDAP. For this we will use attribute `gluuPassportConfiguration` under `ou=oxpassport,ou=configuration,inum=...,ou=appliances,o=gluu`

Structure of json is:

```
{
	"conf": {...},
	"idp_initiated": {...},
	"providers": [...]
}
```

The issues describe to more detail every section. The above is already modeled in [this class](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/passport/PassportConfiguration.java)

In a fresh CE install, `gluuPassportConfiguration` will look like [this](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/passport-central-config.json) (with the proper replacement of variables in it)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55356760-674d8400-54c3-11e9-8230-1c0a8de7a0e4.png)

![image](https://user-images.githubusercontent.com/7513418/55356796-76cccd00-54c3-11e9-951e-8962b7cea58e.png)

![image](https://user-images.githubusercontent.com/7513418/55356919-bdbac280-54c3-11e9-8071-ee0e1821b4b1.png)

![image](https://user-images.githubusercontent.com/7513418/55357066-0ffbe380-54c4-11e9-84d1-da09b2e04f1c.png)
