### ISSUE TITLE
Add form for passport configuration management

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1532]
Related #1531 

The `conf` section of `gluuPassportConfiguration` json looks like:
```
{
	"serverURI": "...",
	"serverWebPort": 8090,
	"postProfileEndpoint": "...",
	"spTLSCert": "...",
	"spTLSKey": "...",
	"logging": {
		"level": "...",
		"consoleLogOnly" : true/false,
		"activeMQConf": {
			"enabled": true/false,
			"host": "...",
			"username": "...",
			"password": "...",
			"port": "..."
		}
}
```
We have to create a form to manage this data. There is already a POJO created for [this here](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/passport/config/Configuration.java)

All fields are required except the `activeMQConf` section.

The possible values that `level` can take are the npm logging levels: error, warn, info, verbose, and debug

Hopefully, upon form submission we should validate `serverURI` and `postProfileEndpoint` are URLs (not arbitrary strings)

**Comment by yurem** [comment]
@jgomer2001 can we assign these new Passport GUI issues to you? @syntrydy is very busy in 4.0. He needs to finish oxTrust API.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/54741613-4a5daa80-4bbf-11e9-9a49-920082fe56e5.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55136499-da0ad800-512e-11e9-9f30-36bda60c4ff1.png)

**Comment by shmorri** [comment]
Documented here: https://gluu.org/docs/ce/4.0/authn-guide/passport/#passport-configuration
