### ISSUE TITLE
Revamp form for providers management configuration

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1533]
Related #1531 

The `providers` section of `gluuPassportConfiguration` is an array of [ProviderDetails](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/passport/Provider.java) objects

I think we can split the info of every provider in 3 tabs:

- Basic details (will contain the mandatory properties)
- Extra (will contain the optional properties)
- Passport strategy options (see member `options` of [POJO](https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/passport/Provider.java#L25)). 

The following are the mandatory properties: id, displayName, type, mapping, passportStrategyId, enabled
The following are optional ones: logo_img, requestForEmail, emailLinkingSafe, passportAuthnParams

options tab can visually resemble what we already have (3.1.x) to enter clientID/clientSecret, etc.. in other words, both the name and value of the field can be edited, and there can be an arbitrary number of these fields

Particularly, *type* should be presented as a list from which admins can select one of: saml/openidconnect-oxd/openidconnect/oauth

----
If type == openidconnect-oxd (ie if it is selected from the list in the UI):
passportStrategyId should get populated with the string `passport-oxd` automatically
mapping should get populated with the string `oxd-default` automatically

the following fields should appear for options:

|Field Name|Default Value|
|-|-|
|clientID||
|clientSecret||
|oxdID||
|issuer|https://server.example.com|
|oxdServer|https://oxd-server.acme.com:8443|

----
If type == openidconnect:
passportStrategyId should get populated with the string `passport-openidconnect`
mapping should get populated with the string `openidconnect-default`

the following fields should appear for options:

|Field Name|Default Value|
|-|-|
|clientID||
|clientSecret||
|issuer|https://server.example.com|
|authorizationURL|https://server.example.com/authorize|
|tokenURL|https://server.example.com/token|
|userInfoURL|https://server.example.com/userinfo|
|scope|openid|

----

If type == saml:
	passportStrategyId should get populated with the string `passport-saml`
	mapping should get populated with the string `saml_ldap_profile`

the following fields should appear for options:

|Field Name|Default Value|
|-|-|
|entryPoint|https://idp.example.com/idp/profile/SAML2/POST/SSO|
|issuer||
|identifierFormat|urn:oasis:names:tc:SAML:2.0:nameid-format:transient|
|authnRequestBinding|HTTP-POST|
|cert||

----

If type == oauth:

the following fields should appear for options:

|Field Name|Default Value|
|-|-|
|clientID||
|clientSecret||

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/54621788-a06c0a00-4a68-11e9-929c-ef7c89dd2131.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/54623031-00fc4680-4a6b-11e9-96c7-51598353549d.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/54691037-e5547700-4b22-11e9-907f-682d6abb10a2.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55136282-505b0a80-512e-11e9-9c21-fcfe8d6e03f5.png)
