### ISSUE TITLE
Once set, lock client ID, client name, client secret fields

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1535]
In order to avoid unintended edits to client ID , secret, or name, once those fields are set, in order to edit those field values we should require the user to click an edit button. 

This will help avoid unintended changes, for example unintended form autofills.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/53577245-9a73bf00-3b75-11e9-9544-3f22f756b9b6.png)
