### ISSUE TITLE
InActive attributes available to add in User profile page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1539]
All attributes including Inactive are available to add in the user profile page when creating a new user. But when we try to add then error is thrown. We should not display attributes which are not active.
 
## Steps To Reproduce
1. Verify that "Manager" attribute is set to Inactive
2. Go to Add Person, fill required fields and add Manager attribute  to the profile.
3. Enter any value and hit submit.
You will see error on the profile.

## Expected behavior
We should not display attributes which are not active.

## Screenshots
![image](https://user-images.githubusercontent.com/21104811/53493980-b5a5d800-3a6a-11e9-8b4e-4490f827d4df.png)

![image](https://user-images.githubusercontent.com/21104811/53494039-cfdfb600-3a6a-11e9-8506-5c63ee96818d.png)

![image](https://user-images.githubusercontent.com/21104811/53494087-e980fd80-3a6a-11e9-9060-9328faf5ba2c.png)

 - OS: Ubuntu16.04LTS
 - Gluu version 3.1.6

**Comment by syntrydy** [comment]
@sahiliamsso i don't know why you think this is an issue. The entry entry don't have an attribute named **Manager** and your are trying to add set a value to an it.  For example **city** is also **inactive**, try to add it and it will work. Or you can also active **Manager** attribute and try to it add, it will fail.
