### ISSUE TITLE
Adjust order and behavior of client auth settings 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1543]
1. We should swap the order of the two authorization fields on the client page. `Pre-Authorization` should be first, and `Persist Client Authorization` should follow. 

2. In addition, the current behavior is incorrect. Currently when Pre-Auth == True, Persis Auth is set to False, and it cannot be adjusted. 

The correct behavior should be the following: 

- When Pre-Auth == True, Persist Auth should also == true, and the field should be **disabled**. 

- When Pre-Auth == False, Persist Auth should be configurable True **or** False. 

![image](https://user-images.githubusercontent.com/5271048/53778827-bbb11400-3ec3-11e9-99c6-c20e30f7b028.png)

**Comment by mbaser** [comment]
I 
![screenshot_2019-03-06_22-41-08](https://user-images.githubusercontent.com/6398752/53908878-6a3e8b80-4061-11e9-84d6-8e0e1340249f.png)
checked the issue if fixed
