### ISSUE TITLE
[CR] Mapping table's entry is ignored if it contains upper-case letters in source attribute's name

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#156]
Please see attached picture below:
![cr-case 1](https://cloud.githubusercontent.com/assets/11802046/11959486/9d2cf36a-a8de-11e5-9263-8f592cb19e00.png)

**Comment by mzico** [comment]
This is interesting. This is not about case sensitiveness. 
The error means: 'otherhomephone' attribute is not created in Gluu Server's LDAP. 

But the question is: why would it ask for this attribute? It's in customer's backend and we are mapping this with 'mobile' attribute. Question for @yurem

**Comment by aliaksander-samuseu** [comment]
I used this attribute just for example, as I found the bug when trying some thing in my local instance. It was lately confirmed by a community user, and after changing all letters to lowcase he was able to circumvent it. It's really about that, you can try to experiment:
1) Add some attribute you have in backend, but never have pulled before to Gluu; you can use any case you want

**Comment by aliaksander-samuseu** [comment]
One moment to note, regarding attribute you'll choose for testing: Gluu schema must not allow such attribute for user entries. What actually happens, I suppose:
1) oxTrust get attribute "otherHomePhone" from the list of pulled attributes, and convert it to lowercase (what is logical, LDAP uses case insensitive names)
2) It starts to look for mapping for it in the table. It's supposed to convert all names there to lower-case, but it does not. So when he compares now lowercased "otherhomephone" to "otherHomePhone" (as it's specified in table), they don't match.
3) When CR has some attribute for which mapping isn't specified, it tries to do implicit mapping to the attribute with the same name (a known behavior), so it tries to actually save "otherhomephone" directly to Gluu's LDAP

**Comment by yurem** [comment]
We need to resolve it in 2.3.2

**Comment by yurem** [comment]
Foxed: https://github.com/GluuFederation/oxTrust/commit/6acffe087d39c816608d5ab61383310023c08c5c
