### ISSUE TITLE
[CR] Additional key attributes don't seem to make any difference.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#157]
Please see attached picture for details. Either its implementation should be completed, or the ability to add more keys should be removed to not confuse a user.
![addnl_keys 1](https://cloud.githubusercontent.com/assets/11802046/11959435/5618e65a-a8de-11e5-87d5-a548afc7e2c6.png)

**Comment by mzico** [comment]
I agree. I haven't seen anyone with multiple primary_key. If any organization want multiple attribute to use for authentication ( i.e. username && email_address ), they can use custom script which is available and tested.

**Comment by yurem** [comment]
It's possible to add max 3 key attributes. We can uses them to create our unique key if their primary key is not unique.
Regarding filter. I think we can use 'and' logic operation for all primary attributes. We need to use 'or' to make sure that at least one primary attribute is exists:
|(primary1=*)(primary2=*)(primary3=*)

We can move postpone this issue resolution for next versions 2.3.3/2.3.4. It's small priority issue.
