### ISSUE TITLE
Email validation error message on "Add person" screen

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1578]
## Describe the issue
Once you provide invalid email address on Add User screen and click submit button, then successive attempts throw same error message even after providing the valid format 

1)   Login as admin in gluu server.     
2) Navigate to the Users Menu > Add Person     
3) Filled all the user information fields but enter invalid email.    
4) Clicked on ‘Add’ button     
5) Seen an error message “Please provide valid email address. Message is   shown.”     
6) Now enter valid Email address it shows again same message “Please   provide valid email address. Message is shown.”     
--

## Expected behavior
User should be added successfully.

## Actual behavior
Getting invalid email address validation error message
## Screenshots
![image](https://user-images.githubusercontent.com/21104811/54971189-adeb2d80-4f5b-11e9-95d1-fa8251344d91.png)

## Desktop (please complete the following information):
 - OS: Ubuntu18 and CentOS6
 - Gluu version: Gluu-server-3.1.6:amd64/bionic-devel 1-10~bionic+Ub18.04
 - Browser ALL

**Comment by syntrydy** [comment]
@sahiliamsso  fixed.
