### ISSUE TITLE
Password/Confirm Password Validation shown for all mandatory fields

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1579]
## Describe the issue
On Add User screen, providing different password and confirm password results in "Password/Confirm Password Validation Error" shown for all mandatory fields

## Steps To Reproduce
1) Login as admin in gluu server. 
2) Navigate to the Users Menu > Add Person
3) Filled all the user information fields, with different Password and Confirm password.
4) Click on Add button. Password and confirm password validation is shown for all mandatory fields. 
5) And also see the attached screenshot of the error page.

## Expected behavior
User should get error message for password/confirm password fields only
## Actual behavior
Same error message is displayed on all other fields

## Screenshots
![image](https://user-images.githubusercontent.com/21104811/54971419-bd1eab00-4f5c-11e9-8d6f-c2bd69be83e5.png)

## Desktop (please complete the following information):
OS: Ubuntu18 and CentOS6
Gluu version: Gluu-server-3.1.6:amd64/bionic-devel 1-10~bionic+Ub18.04
Browser ALL

**Comment by syntrydy** [comment]
@sahiliamsso  This is not reproducible. Please ask if someone can replicate it.

![image](https://user-images.githubusercontent.com/7513418/55219483-4bb55580-5205-11e9-9625-26ade182b368.png)
