### ISSUE TITLE
Error is thrown when federation TR is added in web UI, and when you try to open its page while it's still in "validation" state.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1581]
## Steps To Reproduce
1. Try to create a TR of "Federation" type. This [metadata](https://github.com/GluuFederation/oxTrust/files/3007787/testshib-providers-full.xml.zip) can be used for it
2. While it's still in "Validation Scheduled" or "Validation" state soon after creation, try to open its page

## Result
On step 1 an error is thrown when you click "Add" button. The TR is still created regardless.
On step 2, a similar error is thrown. When TR reaches "Active" state, error stops to appear.
![Selection_021](https://user-images.githubusercontent.com/11802046/54992652-dd884d00-4fd0-11e9-9ef0-9df8bc3b6728.jpg)

**Comment by yurem** [comment]
I can't reproduce it. Maybe it's caused on slow machines with by big metadata size. We opened issue to improve this: https://github.com/GluuFederation/oxTrust/issues/1575
