### ISSUE TITLE
Email Validation Wrong Message Displayed

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1582]
## Describe the issue
Consider user fill the form fields except email, password and confirm password and click on add button we get the invalid email validation message with some wrong exception message.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Login as admin in gluu server
2. Navigate to the Users Menu > Add Person
3. fill the form fields except email, password and confirm password
4. click on add button we get the invalid email validation message with some wrong exception message
5. See the error.

## Expected behavior
Email Validation message should be in correct format.

## Actual behavior
It shows the invalid email validation message with some wrong exception message

## Screenshots
![image](https://user-images.githubusercontent.com/34593983/54994781-2220e200-4feb-11e9-94dd-92b0b86a685a.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu16.04LTS
 - Gluu version(3.1.6)
 - Browser [chrome, Firefox]

**Comment by willow9886** [comment]
Duplicate? https://github.com/GluuFederation/oxTrust/issues/1578

Sahil opened and Gasmyr fixed and closed. Please confirm and close or keep open if different

**Comment by MohitMaliFtechiz** [comment]
hi @willow9886 , this is related to the wrong encrypted error message , see screenshot over top right corner.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55217928-f70fdb80-5200-11e9-8135-51b3015ae47b.png)
