### ISSUE TITLE
Invalid Birthdate Format

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1583]
## Describe the issue
User is able to enter alphabets in date field.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Login as admin in gluu server.
2. Navigate to the Users Menu > Add Person
3. Fill all fields of the add person form, select Birth date attribute and enter alphabets.

## Expected behavior
Date picker should be there.

## Actual behaviour
User is able to add alphabets in text field.

## Screenshots
![image](https://user-images.githubusercontent.com/34593983/54996938-990ca980-4ff0-11e9-88b0-1dd9ff977f80.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu16.04LTS
 - Gluu version(3.1.6)
 - Browser [ chrome, Firefox]

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83014174-26dd8d80-a016-11ea-872d-7a2902cef835.png)
