### ISSUE TITLE
[CR] "Remove Anonymous Bind" button

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#159]
1. It demands to provide Bind DN.
2. Even after some real DN is provided, it still fails (wireshark doesn't show any connection attempts and there is an error trace in wrapper.log ([see a fragment of it](https://github.com/GluuFederation/oxTrust/files/67875/ann-bind-err-trc.1.txt)))
3. It seems that the "Bind DN" input field should become hidden the moment this checkbox is set, and visible again the moment it's unset, but this change of its visibility only happens after the "Update" button is clicked atm.
   ![ann-bind1 1](https://cloud.githubusercontent.com/assets/11802046/11919024/d5640594-a757-11e5-922c-d2ef62b32d77.png)

**Comment by aliaksander-samuseu** [comment]
Btw, I've seen at least one of our commercial clients who uses it (before I said I don't remember anyone using it)

**Comment by mzico** [comment]
We had to implement this for this specific client. Personally, I really don't like this feature. :-)

**Comment by mzico** [comment]
@yurem @nynymike: Can we keep this feature out of oxTrust and keep it somewhere inside ldap? If anyone need this, user can enable this from LDAP.

**Comment by yurem** [comment]
@zico for me it will be better to fix this bug than implement some logic just of one client.

**Comment by mzico** [comment]
@yurem: Sure, if you find it easy to fix.

**Comment by willow9886** [comment]
@yurem can you update this issue?

**Comment by nynymike** [comment]
Let's just remove the checkbox for Anonymous bind. I don't see why anyone should be allowed to use anonymous bind for cache refresh.

**Comment by sahiliamsso** [comment]
"Anonymous Bind" button still available on CR screen.
