### ISSUE TITLE
Introduce tree view for interception scripts (with common scripts support)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1590]
## Describe the issue
We should introduce tree view for interception scripts:

![image](https://user-images.githubusercontent.com/2013070/55319260-26328100-547d-11e9-9d9a-73a9847a8da3.png)

oxCore ticket: https://github.com/GluuFederation/oxCore/issues/124

## Steps To Reproduce
New Feature

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/62825991-33d6e080-bbac-11e9-8ca2-71d67f9d0a04.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/62825999-64b71580-bbac-11e9-908f-d6c9fe011637.png)

**Comment by syntrydy** [comment]
@yuriyz i think we can put it in 4.0. The part about common folder can be done in 4.1

**Comment by willow9886** [comment]
Looks pretty good. Couple ux things.. 

- add a space between `custom` and `script` in the add new custom script button

- instead of green with blue highlight for the menu, let's try white with green highlight

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/62875215-87ffd300-bd1a-11e9-8e32-f8a111320a21.png)

**Comment by syntrydy** [comment]
I'm merging this to 4.0 because it is working very well and it is fast compared to the previous version.

**Comment by yuriyz** [comment]
> @yuriyz i think we can put it in 4.0. The part about common folder can be done in 4.1

Yes, agreed. We can add common support once it's ready on back-end.

**Comment by willow9886** [comment]
nice, looks good @syntrydy
