### ISSUE TITLE
Display SCIM attribute name (if applicable) in attributes form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1595]
Citing @nynymike 

> In SCIM, each attribute has a name…
> But where is that name mapped in the Gluu Server ?
> I don’t see it in the attributes form.
> I think we should have it reflected.
> And I think displaying in the attributes form of oxTrust would make it more clear, even if it’s a non-editable field

The above means we should show a non-editable field in the "edit attribute" form for certain ldap attributes that we employ to store scim core attributes.

I will create a list with ldap attr vs. scim attr name.

A more elegant solution so we don't hardcode this table nor add an attribute to `gluuAttribute` objectClass is by introspecting the code (subclasses of `org.gluu.oxtrust.model.scim2.BaseScimResource` annotated with `org.gluu.oxtrust.model.scim2.annotations.StoreReference`).

I will check if this algorithm can be written.

**Comment by jgomer2001** [comment]
This algorithm creates `ldapScim` (a mapping of ldap attribute name vs. scim attribute info):
```
Map<String, String> ldapScim = new HashMap<>();
Map<Class<? extends BaseScimResource>, Map<String, String>> refs = new HashMap<>(IntrospectUtil.storeRefs);
List<Class<? extends BaseScimResource>> resourceTypes = Arrays.asList(UserResource.class, FidoDeviceResource.class, GroupResource.class);
Predicate<Class<? extends BaseScimResource>> p = resourceTypes::contains;
refs.keySet().removeIf(p.negate());

for (Class<? extends BaseScimResource> resourceType : refs.keySet()) {
	Map<String, String> scimLdap = refs.get(resourceType);
	String resourceName = ScimResourceUtil.getType(resourceType);

	for (String scimAttr : scimLdap.keySet()) {
	    String ldapAttr = scimLdap.get(scimAttr);
	    String val = ldapScim.getOrDefault(ldapAttr, String.format("%s (", scimAttr));
	    val+= String.format("%s/", resourceName);
	    ldapScim.put(ldapAttr, val);
	}
}
ldapScim.keySet().forEach(ldapAttr -> ldapScim.compute(
	    ldapAttr, (k, v) -> v.substring(0, v.length() - 1).concat(")"))
);
```

The generated map is:

```
{
preferredLanguage=preferredLanguage (User),
mail=emails.value (User),
oxApplication=application (FidoDevice),
oxTrustUserType=userType (User),
displayName=displayName (User/FidoDevice/Group),
timezone=timezone (User),
description=description (FidoDevice),
oxTrustx509Certificate=x509Certificates (User),
oxTrustNameFormatted=name.formatted (User),
locale=locale (User),
inum=id (User/Group),
oxTrustAddresses=addresses (User),
oxTrustExternalId=externalId (User),
oxTrustTitle=title (User),
oxId=id (FidoDevice),
uid=userName (User),
oxDeviceKeyHandle=deviceKeyHandle (FidoDevice),
oxTrustMetaVersion=meta.version (User/FidoDevice/Group),
oxLastAccessTime=lastAccessTime (FidoDevice),
oxTrustRole=roles (User),
oxTrustPhotos=photos (User),
oxTrustEntitlements=entitlements (User),
member=members (Group),
oxCounter=counter (FidoDevice),
memberOf=groups.value (User),
sn=name.familyName (User),
oxTrustPhoneValue=phoneNumbers (User),
updatedAt=meta.lastModified (User),
oxDeviceRegistrationConf=deviceRegistrationConf (FidoDevice),
nickName=nickName (User),
oxTrustProfileURL=profileUrl (User),
givenName=name.givenName (User),
oxDeviceHashCode=deviceHashCode (FidoDevice),
oxTrustImsValue=ims (User),
creationDate=meta.created (FidoDevice/FidoDevice),
oxTrustMetaLocation=meta.location (User/FidoDevice/Group),
oxPPID=pairwiseIdentitifers (User),
oxTrusthonorificPrefix=name.honorificPrefix (User),
oxTrustEmail=emails (User),
oxNickName=nickname (FidoDevice),
middleName=name.middleName (User),
oxCreationTimestamp=meta.created (User),
oxStatus=status (FidoDevice),
oxTrusthonorificSuffix=name.honorificSuffix (User),
oxTrustActive=active (User),
oxDeviceData=deviceData (FidoDevice)
}
```

**Comment by jgomer2001** [comment]
In the UI (attribute form) let's do:
-  where it reads "SCIM Attribute", change that label with "SCIM extended attribute". This the real meaning of this true/false field
- Add a row after "oxauth claim name" with label "SCIM Attribute", where the scim attribute name will be displayed

Since `ldapScim` has to do with core SCIM attributes only, the "SCIM extended attribute" should not appear if the current gluu attribute is part of `ldapScim`. If it is not part of the mapping, the "SCIM Attribute" row should not be shown, but the "SCIM extended attribute" should be

**Comment by syntrydy** [comment]
@jgomer2001 is it okay like this:

![image](https://user-images.githubusercontent.com/7513418/57460712-8cc17080-726d-11e9-8cd7-c99cf45f8eec.png)


In this case, the attribute is **mail** and his SCIM equivalent is **email**.
