### ISSUE TITLE
Error showing certificates list

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1600]
## Describe the issue

Oops,Error showing certificates list

## Screenshots

![image](https://user-images.githubusercontent.com/7513418/55490948-874c8700-562c-11e9-9ed3-932045d2b788.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55493384-c11f8c80-5630-11e9-8bde-518f56b59c11.png)

**Comment by sahiliamsso** [comment]
Is it possible to format the certificate display same as we're displaying other entries like users. TRs and clients?
