### ISSUE TITLE
Remove the finishlogout page

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1602]
## Describe the issue
Currently the page name **finishlogout.xhtml** is kind of useless.
It is an extra click for user and an extra page to maintain.

We have to remove it and may the logout process go straight to login page.

## Steps To Reproduce
1. Login Into Gluu Admin UI
2. Click the logout button

## Expected behavior
You should see the login page.
## Actual behavior
The finish logout page is shown instead.
## Screenshots
![image](https://user-images.githubusercontent.com/7513418/55540751-83b41100-56bb-11e9-961f-d2e202ccc7c6.png)

**Comment by yurem** [comment]
We need to review back to this after resolving https://github.com/GluuFederation/oxAuth/issues/1024

**Comment by yurem** [comment]
I'm starting to understand root case of this issue. @willow9886 @syntrydy Correct me if I'm wrong. Is it related to IDP? Starting from 3.1.4 IDP uses own oxAuth client. As result IDP/oxAuth/etc don't redirect to oxTrust after logout. As result we can keep this page.

**Comment by willow9886** [comment]
hi @yurem , yes, your understanding is correct. Closing this out.
