### ISSUE TITLE
oxTrust RS code (passport, scim, oxtrust-api) must set scopes for protection

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1605]
## Describe the issue
All three projects (passport, scim, oxtrust-api) must set scopes for UMA protection.

In `BaseUmaProtectionService.java#L141` class there is code
```
if (scopes.isEmpty()) {
            rptTokenValidationResult = umaPermissionService.validateRptToken(patToken, authorization, getUmaResourceId(), scopes);
        } else {
            rptTokenValidationResult = umaPermissionService.validateRptToken(patToken, authorization, getUmaResourceId(), getUmaScope());
        }
```

Scopes to check are taken from `@ProtectedApi` annotation. But in oxTrust code scopes are not set, it means nothing to check, any even dummy RPT is considered as valid. 

## Steps To Reproduce
Get RPT without scopes and call any API from passport, scim or oxtrust-api. It will run successfully.

## Expected behavior
It must be rejected. RS should check specific scope that must be present in RPT.

**Comment by jgomer2001** [comment]
> maybe we need to add one more uma configuration option to allow override ProtectedApi scopes . It should be false (or not exist) by default.
> This can help us in case when we need to extend something via script but limited with hardcoded scopes

**Comment by jgomer2001** [comment]
The conditional was wrong, should be `if (!scopes.isEmpty()) {`

Thus, if `protectedApi` has no scopes, it will grab those from the concrete class, which in the end picks then from oxtrust appconfiguration
