### ISSUE TITLE
Attribute dissapers from the list if administrator is forbidden to edit it

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1608]
Environment: Gluu Server CE 3.1.6

Steps to reproduce:

1. Log in to web UI as admin
2. Move to "Configuration > Attributes"
3. Edit an attribute's properties by changing "Edit Type" to have only "user" selected
4. Click "Update"

Result:
The attribute has disappeared from the list on "Configuration > Attributes" page

Expected result:
Attribute's properties still must be configurable at "Configuration > Attributes" page; this setting must only control whether or not user / admin can change **value** of this attribute when editing their profile.

**Comment by sahiliamsso** [comment]
getting OOPS error on clicking update button  after changing "Edit Type" to have only "user" . Nothing is logged in oxtrust log files
