### ISSUE TITLE
Place SCIM and oxTrust API properties into collapsible sections

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1609]
Oxtrust json configuration is kind of big form. We can improve organization and length by grouping the following into collapsible sections (like currently clientBlackList is):
![group](https://user-images.githubusercontent.com/5444180/56500027-c99c1200-64ce-11e9-8301-d519435d876c.png)

- SCIM properties (scimClientUmaId, clientKeyId, resourceId, etc..., test mode, max_count). Here I think we can use the already existing `org.gluu.config.oxtrust.ScimProperties` class
- API properties (apiUmaClientId, etc..., test mode)

We could do the same with passport properties, however, I think that as there exist 3 pages for passport configuration already, we can add a 4th one called "UMA RS configuration".

This will also help partitioning the long class `org.gluu.config.oxtrust.AppConfiguration`.

**Comment by jgomer2001** [comment]
Since SCIM API is now a separate component, all configurations should be in a separte tab in Json Configurations menu

**Comment by shmorri** [comment]
No longer necessary due to GUI redesign
