### ISSUE TITLE
Import users feature doesn't work

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#161]
Unfortunately, there are still multiple problems with this feature. Please see attached picture for more details.
![user_import 1](https://cloud.githubusercontent.com/assets/11802046/11919174/98b0ba80-a75b-11e5-8dbc-84fd6cb06ff3.png)
Here is [the xls file](https://github.com/GluuFederation/oxTrust/files/67898/libreofic-mfo2003f.zip) I used to import users when testing.
1. Imported users have one less object class definition then those which were created manually using web UI. I suppose as only their creation methods differ, not their purpose, they should be represented by exactly the same objects.
2. Imported users don't have value "active" assigned to the "gluuStatus" attribute, so it won't be possible to use them right away. I'm not sure whether it's by design, or not.
3. Even after setting "gluuStatus" to "active" manually, you won't be able to log in to this account, as there is some ambiguity or issue with providing passwords using an import file. If passwords Gluu expects to find there should be in pre-encoded (hashed) form, then it shouldn't accept a simple alpha-numeric string at all, as according to RFC 2307 draft 02, item 5.2.2.1 (https://tools.ietf.org/html/draft-howard-rfc2307bis-02) hashed password value must has schema prefix, so it would be more logical to expect that hashes there - most likely exported from some directory - will have it too. If it's supposed to be a cleartext string, then it computes the hash incorrectly, because in my case I was able to log in to imported account only after resetting password via jxplorer using the same cleartext string. At least it should explicitly inform user about a password field's format somehow (hints, docs' article, etc)

**Comment by aliaksander-samuseu** [comment]
**Yuriy M. wrote:**
I offer to move it to 2.4.1 because it's very old code (4 years old) and in depends on file: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/gluuImportPerson.properties
I think we can write more smarter import dialog in 2.4.1 which not depends on gluuImportPerson.properties

**Comment by nynymike** [comment]
What is the status?

**Comment by aliaksander-samuseu** [comment]
@nynymike , me and Zamil were checking it today. The issue with "duplicate uid" still was blocking the ability to test it properly. But judging by William's last comment in corresponding report - https://github.com/GluuFederation/oxTrust/issues/102 -  it has just been fixed, so we'll be able to check its status in one of the upcoming releases.

**Comment by willow9886** [comment]
@aliaksander-samuseu Yura seems to have pushed a fix in December, so it is not that recent...

**Comment by aliaksander-samuseu** [comment]
@willow9886 , I have 2.4.1-1 ubuntu package installed which I set up a weak or two ago, and this bug is here. Don't know what package Zamil used when checking it out, but probably also one of the recent ones

**Comment by willow9886** [comment]
@aliaksander-samuseu #102 or this issue? are they the same?

**Comment by aliaksander-samuseu** [comment]
@willow9886  , this one: https://github.com/GluuFederation/oxTrust/issues/102 , reported by Zico
We couldn't check what is the status of issue #161 as we can't even import users at all at the moment, issue #102 is a blocker.

**Comment by willow9886** [comment]
@aliaksander-samuseu  I just added a note on #102 there asking yura to double check.

**Comment by shekhar16** [comment]
@willow9886 this issue is fixed and i checked in the code in repository.Please check it .
