### ISSUE TITLE
Couchbase & LDAP: Can't access passport pages

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1610]
I can't access passport pages with both couchbase and ldap backends
![passport1](https://user-images.githubusercontent.com/6398752/56723477-b2b92200-6751-11e9-999f-80e13633cf29.gif)
![passport2](https://user-images.githubusercontent.com/6398752/56723479-b2b92200-6751-11e9-9015-6ca1ddc5d8a4.gif)
![passport3](https://user-images.githubusercontent.com/6398752/56723480-b351b880-6751-11e9-97f7-88960eeff860.gif)

**Comment by yurem** [comment]
It happens when we not install passport. As result without passport data in LDAP this not work. We need to hide passport menu when passport is not installed.

**Comment by syntrydy** [comment]
Fixed.
