### ISSUE TITLE
Calendar popup for Date type attributes

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1612]
It would be nice if we have calendar popup for **Date** type attributes:
![Screenshot_2019-04-25_12-13-25](https://user-images.githubusercontent.com/6398752/56724469-bf3e7a00-6753-11e9-9263-160fc1eeee27.png)

For example, for user:
![Screenshot_2019-04-25_12-10-56](https://user-images.githubusercontent.com/6398752/56724607-0167bb80-6754-11e9-8e55-edd0785c83f9.png)

As we do for example clients
![Screenshot_2019-04-25_12-10-38](https://user-images.githubusercontent.com/6398752/56724635-0f1d4100-6754-11e9-96f4-8b4906531770.png)

**Comment by sahiliamsso** [comment]
Please remove time picker selection, and make the field uneditable (allow only to select from date picker to avoid date format errors)

![image](https://user-images.githubusercontent.com/21104811/56937227-99093900-6ac9-11e9-8620-e157ba9109a7.png)

**Comment by syntrydy** [comment]
**and make the field uneditable** why do you need the field to be uneditable?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/56973781-6c0a6400-6b65-11e9-8199-1e66ca90bb31.png)

**Comment by MohitMaliFtechiz** [comment]
1) Not able to add user first time. It don't give any error message, after refreshing page it Blanks password and confirm password field.
2) Not able to add DOB from calendar.  Select Birth date attribute after first time when we click on ad button, not able to select date from Calendar.
3)  Then enter Password and confirm password and click on add button it gives oops error message.
