### ISSUE TITLE
Change name field title for LDAP auth

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1617]
In Configuration > Manage Authentication > Manage LDAP authentication, we should change the `Name` field title to `acr`. 

Because actually, the `auth_ldap_server` is published by the server as an acr. 

![image](https://user-images.githubusercontent.com/5271048/56895552-7f9cc880-6a9a-11e9-8358-f46116e1044f.png)

**Comment by syntrydy** [comment]
@willow9886 still want me to change this?

BTW, I already fix another issue about multiple LDAP source servers.

**Comment by willow9886** [comment]
maybe we should just add clarification in the docs... @syntrydy what do you think ?

**Comment by syntrydy** [comment]
@willow9886 done.

Here is the issue https://github.com/GluuFederation/support-docs/issues/8.
