### ISSUE TITLE
[CR] "Load entries with a limited search" feature uses incomplete character set.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#162]
The feature tries to reduce amount of entries returned in responses by splitting the request of type `(key=*)` into a sequence of requests like `(key=aa*),(key=ab*)...(key=a0*),(key=ba*)...(key=a.*)...(key=..*)`. But it omits next characters that can be encountered in attributes most often used as keys (uid, sAMAccountName): `' $ & _ # ^ ~` - (and possibly some other) It only includes alphanumeric and the dot `.` character. 

So uids/samaccounts like `"D'Alamber"` won't make it to the internal db. Moreover, despite samaccountname and uids seems to not allow to use anything aside from mentioned above, as CR allows to use literally any backend attribute as a key, including custom attributes, possibility that many other non-alphanumeric characters may be encountered in the first 2 positions should be taken into account. 

Yuriy's idea to allow user to specify a character set to use in these 2 first character positions should resolve the issue. It could provide a default set including letters, digits, dot and a single quot, and allow to expand it with additional characters, or compose a totally custom set if user wishes so.

**Comment by yurem** [comment]
We need to move this card coded string with list of characters to CR configuration to allow change it without code update
