### ISSUE TITLE
Add SAML acr field to person authentication script form

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1620]
To support our [new SAML feature](https://github.com/GluuFederation/oxShibboleth/issues/15), our person authentication scripts need a new field for admins to provide a value for `SAML acr`. 

![image](https://user-images.githubusercontent.com/5271048/56984310-c53ebb80-6b96-11e9-9a3b-df35a7662a9a.png)

A few details about the new field:

- editbox, single valued (from list values)
- name: `SAML acr`
- constraints - unique; i.e. no duplicate values allowed in other scripts, e.g. two different scripts can't have the same value for the `SAML acr` field.

Sample values:  

```
urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
urn:oasis:names:tc:SAML:2.0:ac:classes:Password
```

Constraint example:

if `urn:oasis:names:tc:SAML:2.0:ac:classes:Password` is the `SAML acr` of one script, it cant be used as for another.

**Comment by yurem** [comment]
@willow9886 Instead of `SAML acr` I offer to use non SAML name like `Alias ACR` or `Additonal Name`. I think because this functionality we can reuse even without SAML. Also we should allow to specify more than one such `Alias ACR`

But to help to select SAML authentication flows we can follow Harjinder's recommendations. We can read them from `conf/authn/general-authn.xml` and add link near to this field like `Select SAML flow`. Once user click this link we can show dialog to select names from list.

**Comment by malotian** [comment]
## AuthnContextClassRef

The Gluu Server supports AuthnContextClassRef out-of-the-box. Including `<saml:AuthnContextClassRef> tag` in the initial SAML request from the SP signals to the IDP that the user must reauthenticate with specified authentication scheme/method.
sample request:
```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_809707f0030a5d00620c9d9df97f627afe9dcc24" Version="2.0" ProviderName="SP test" IssueInstant="2014-07-16T23:52:45Z" Destination="http://idp.example.com/SSOService.php" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="http://sp.example.com/demo1/index.php?acs">
  <saml:Issuer>http://sp.example.com/demo1/metadata.php</saml:Issuer>
  <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" AllowCreate="true"/>
  <samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
Note: Allowed values must be defined under conf/authn/general-authn.xml under authn/oxAuth bean
```
<bean id="authn/oxAuth" parent="shibboleth.AuthenticationFlow"
		p:forcedAuthenticationSupported="true"
		p:nonBrowserSupported="false" >
	<property name="supportedPrincipals">
		<list>
			<bean parent="shibboleth.SAML2AuthnContextClassRef"
				c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:Password" />
			<bean parent="shibboleth.SAML2AuthnContextClassRef"
				c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
			<bean parent="shibboleth.SAML2AuthnContextClassRef"
				c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol" />
		</list>
	</property>
</bean>
```
### AuthnContextClassRef Extension
User can define custom AuthnContextClassRef attribute values as well, recommeded format for values is either urn or uri.
#### example formats
- urn:oasis:names:tc:SAML:2.0:ac:classes:X509
- urn:oasis:names:tc:SAML:2.0:ac:classes:TLSClient
- urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
- urn:oasis:names:tc:SAML:2.0:ac:classes:Password
- urn:oasis:names:tc:SAML:2.0:ac:classes:Kerberos
- urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
- https://refeds.org/profile/mfa
- https://refeds.org/profile/sfa

### Enable AuthnContextClassRef in oxTrust
Gluu Authentication Schemes (basic, fido, mfa, ldap etc.) needs to be associated with AuthnContextClassRef values (one-to-one), This can be achieved by updating ACR attribute under Person Authentication.

**Comment by malotian** [comment]
> We can read them from `conf/authn/general-authn.xml` and add link near to this field like `Select SAML flow`. Once user click this link we can show dialog to select names from list.

Once user click this link we can show dialog to select **_UNUSED_** names from list.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/57538076-826fa700-733f-11e9-886d-a2382fdc71ff.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/57541455-fb263180-7346-11e9-8ab9-cd118dad8e9f.png)
![image](https://user-images.githubusercontent.com/7513418/57541479-0b3e1100-7347-11e9-9da6-d1ea38f2c0d0.png)
