### ISSUE TITLE
Hide unnecessary passport-related elements

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1627]
Let's hide the main Passport menu item (the one containing basic config, providers, etc.) when passport support is not enabled (ie when `Configuration  ` > `Organization configuration` > `Passport Support` shows "disabled")

Let's remove the tab "Passport authentication method" from `Configuration` >  `Manage Authentication`. It's redundant

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/57159099-07593e80-6ddd-11e9-837a-4f83f549427c.png)

![image](https://user-images.githubusercontent.com/7513418/57159143-15a75a80-6ddd-11e9-9540-cc7dd9971446.png)

![image](https://user-images.githubusercontent.com/7513418/57159188-28219400-6ddd-11e9-8684-1ba62ac386c9.png)
