### ISSUE TITLE
[CR] "Test LDAP connection" buttons need to be added for each LDAP connection UI pane on the "Configuration -> CR" page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#163]
Was proposed by @nynymike . Like the one on the "Manage authentication" page (see picture), for both backend and inum db tabs, a separate button for each defined LDAP connection.
![test-ldap 1](https://cloud.githubusercontent.com/assets/11802046/11919233/ee035784-a75d-11e5-9818-78c0c66c9d28.png)

**Comment by mzico** [comment]
+1
