### ISSUE TITLE
Group configuration properties to make it more user-friendly

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1630]
There are many lifetime configuration option. I offer to group them in one bean to make configuration list more user friendly.
https://github.com/GluuFederation/oxAuth/issues/824

TODO: define groups:
- lifetime group
- ?

**Comment by yuriyz** [comment]
We should think about it from user perspective. If we want to make it more user-friendly then we should group it on UI (not on AS side). And on UI we can define lets say logical groups, e.g. `UMA Configurations`, `Client Configurations`. Than map that UI bean into oxauth  `AppConfiguration`. On AS side it's just map of key-value/key-object while on UI we can represent it in whatever form. Not just rendering current oxauth json. 

So first we need to define logical groups and then how we want to represent them on GUI. I propose following logical groups:

- Client configurations
- UMA configurations
- Session configurations
- Persistence configurations
- what else?

**Comment by shmorri** [comment]
This is being addressed in Gluu Admin UI for Gluu 5
