### ISSUE TITLE
Impossible to add new OIDC client when datasource is Couchbase

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1631]
## Describe the issue
It is not possible to add new OIDC when the data source is Couchbase.

## Steps To Reproduce
1. Install Gluu server 4.0 latest
2. Log into Gluu admin UI
3. Try to add a new client and save

## Expected behavior
The client should be added

## Actual behavior
Oops, an error page is shown.

**Comment by syntrydy** [comment]
[error.txt](https://github.com/GluuFederation/oxTrust/files/3146808/error.txt)

**Comment by yurem** [comment]
Fixed
