### ISSUE TITLE
Performance degrade for /person/view, person/viewProfile.htm (potentially other pages)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1636]
## Describe the issue

We loaded oxtrust with 50 concurrent users. oxTrust login process works. We can see that viewProfile.htm page starts to degrade. Time of response increased from milliseconds to 16 seconds. 

It seems major cause is rewrite filter (similar as we had it for oxauth).

![image](https://user-images.githubusercontent.com/2013070/57330661-5f66ac80-711f-11e9-874d-b7b1b4ec4ce0.png)

Yourkit snapshot (can be opened with Yourkit GUI)
[start-2019-05-07.zip](https://github.com/GluuFederation/oxTrust/files/3154431/start-2019-05-07.zip)

![image](https://user-images.githubusercontent.com/2013070/57331127-8d98bc00-7120-11e9-83e0-3ba805aea17c.png)

![image](https://user-images.githubusercontent.com/2013070/57331142-94bfca00-7120-11e9-93a8-e997bb3c4270.png)

**Comment by yuriyz** [comment]
This should be partly covered by redirect library removing.

**Comment by yurem** [comment]
yep, we need to recheck it now

**Comment by nynymike** [comment]
oxTrust performance is not a big issue... closing.
