### ISSUE TITLE
No-passport in setup but 'passport' config showing in oxTrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1644]
May be we shouldn't show 'passport' configuration in oxTrust if we don't choose passport in setup. 
In below screenshot, I don't have any passport server but oxTrust is showing Passport config. 
![Capture](https://user-images.githubusercontent.com/7156097/57474499-cc7d5d80-7257-11e9-9d0d-1fffaf415bfb.PNG)

**Comment by syntrydy** [comment]
@mzico closing this as it is fixed in the latest build.
