### ISSUE TITLE
Cache Refresh triggers activation on all nodes when  no custom cache refresh script is enabled

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/oxTrust#1647]
In `/src/main/java/org/gluu/oxtrust/service/external/ExternalCacheRefreshService.java`
`executeExternalIsStartProcessMethods` will always return true if there is no custom cache
refresh script setup and enabled, there by making the check on "Server
IP Address” (primary oxTrust node) useless.

**Comment by yurem** [comment]
Fixed
