### ISSUE TITLE
Gluu Server SAML NameID enhacement

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1651]
We need to allow users to create their SAML nameID from oxTrust [feature](https://gluu.org/docs/ce/3.1.6/admin-guide/saml/#configure-nameid) without juggling shibb velocity templates ( /opt/gluu/jetty/identity/conf/shibboleth/idp ) much.

**Comment by malotian** [comment]
Implemented and tested sucessfully
