### ISSUE TITLE
Display FIDO2 credentials in users profile form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1654]
Currently oxtrust shows fido u2f devices properly in the user form. The same should happen for fido 2 devices , which  apparently is not implemented yet. FIDO 2 support was added to Gluu server by version 3.1.5

**Comment by syntrydy** [comment]
I don't have fido2 devices to test this feature. If you have LDAP entry for fido2, i can add that to my LDAP and use for testing

**Comment by jgomer2001** [comment]
neither do I. Ask @yurem some sample data

**Comment by yurem** [comment]
[fido2.zip](https://github.com/GluuFederation/oxTrust/files/3197304/fido2.zip)

**Comment by yurem** [comment]
[fido2_2.zip](https://github.com/GluuFederation/oxTrust/files/3197346/fido2_2.zip)

**Comment by jgomer2001** [comment]
In latest package, when clicking on the details of the fido device, it bounces to oops page. Log shows:

```
ERROR [qtp985655350-14] [org.gluu.oxtrust.ldap.service.FidoDeviceService] (FidoDeviceService.java:73) - Failed to find device by id 9b795c2f-bb8a-4e9c-8d12-40686422da64
org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: oxId=9b795c2f-bb8a-4e9c-8d12-40686422da64,ou=fido,inum=A8F2-DE1E.D7FB,ou=people,o=gluu
	at org.gluu.persist.ldap.impl.LdapEntryManager.find(LdapEntryManager.java:365) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
```

it's looking up the wrong branch.

Also when clicking on the remove icon, the entry is immediately deleted from ldap but is the table (UI) is not refresh
