### ISSUE TITLE
SAML metadata is behind left navigation panel

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1659]
Steps to reproduce
1. Add new trust relationship
2. Choose "File" for "Metadata Location"
3. Select and upload a metadata
4. Try to view uploaded metadata

See the screenshot
![Screenshot_2019-05-21_22-47-34](https://user-images.githubusercontent.com/6398752/58126176-fe5ccf80-7c1a-11e9-8e69-1875114d7a74.png)

**Comment by mbaser** [comment]
In the latest build, I can't see metadata file.

**Comment by syntrydy** [comment]
I'm checking
