### ISSUE TITLE
[CR] Add ability to browse backend/inumdb LDAP directories for Base DNs to the "Configuration -> CR" page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#166]
**This is from the selection of enhancements that @nynymike and @yurem  came up with when discussing current CR's drawbacks**. (I'm not sure I correctly understood this one, please feel free to correct the description)
Add ability to "browse" the backend server for base DN's. An input field "Root DN" and a button "Browse" next to it should be added to each LDAP connection defined on the page. On clicking the button a pop-up window should appear listening contents of the backend/inumdb LDAP directories as if you just have bound to it at the DN supplied in "Root DN" field. From now on a user can browse the directories and select the entry to use as a Base DN by clicking it and then clicking "Apply" button.
Not sure how it should be implemented in details - should it only display entries like "ou", "o" and others containing leaf objects, without showing their contents? If it also should show leaf objects, like users, computers, sessions etc, it will need to use limited LDAP searches to only show a subset of them (as there can be thousands), to enhance usability of this feature (long response times, higher chance of crash or hang of the browser if a lot of entries will be loaded and need to be processed by client-side script engines).
Also, perhaps the same functionality should be also added to the "Manage authentication" page.

**Comment by aliaksander-samuseu** [comment]
**Zico wrote:**
Question: Is this a new feature with which we will be able to browse backend AD/LDAP?

**Comment by aliaksander-samuseu** [comment]
If I got it right, it's just a way to select Base DN in a more intuitive way, instead of copy-pasting it from some other application. You provide some root DN for backend, click the Browse button, bind to the Root DN and start browsing the backend's tree, select some branch down the tree you want to become your Base DN for that LDAP connection and click "Apply". But it was @Mike 's idea, I could get it wrong.

**Comment by nynymike** [comment]
No! Customer can use a standard LDAP browser tool.
