### ISSUE TITLE
Allow special char "underscore" in attribute name

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1663]
We can't create attribute like 'some_attribute' from oxTrust. Some customers might need it. 
We can directly add such special char attribute in LDAP, so there is no issue from LDAP side. 

Let's allow oxTrust to accept attribute like `some_attribute`.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83020318-37930100-a020-11ea-80b1-edeed3f86da5.png)
