### ISSUE TITLE
404 error message

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1674]
## Describe the issue
Not able to see profile.

## Steps To Reproduce
1. Go to Profile image present at top right corner and click on it.
2. Two options are there Profile and logout. Click on Profile
3. See the error.

## Expected behavior
It should open profile page.

## Actual behavior
It gives an 404 error message.

## Desktop (please complete the following information):
 - OS: ubuntu 18
 - Gluu version 4.0.
 - Browser Mozilla Firefox

**Comment by syntrydy** [comment]
@MohitMaliFtechiz I fixed this already, please check again when the new package will be available.
