### ISSUE TITLE
[CR] If 2 different LDAP backends are provided, and one of them is down, CR won't pull the 2nd one at all, and just will skip this iteration completely

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#168]
@nynymike asked to create a report for this issue, but after speaking with @yurem  it seems now this may be a limitation hidden deep in CR's code, so I decided to make it a discussion instead. Here is what he told me (please correct me if I misinterpret something):

"If some part of a distributed users database can't be pulled in at this iteration, CR can't process the rest of it too as unification of all involved user sets has to be done to proceed. We would need to rewrite a significant part of current CR's implementation to change this behavior, and it won't be an easy task, a lot of time has been spent to polish the current one. It's better to request that users employ fail-over servers for each distinct source of user data. Though, we should clearly notify a user about something like that is happening in logs"

AFAICR, at the moment in that case some ambiguous message appears in CR log, which can confuse a user.

**Comment by YuriyM** [comment]
Hey

My user name is YuriyM and I have received 2 notifications from this project because I was mentioned.

I am not a contributor to this project. Seems it was misspelling and in fact mentioned user name was yurem.

**Comment by willow9886** [comment]
Thanks, @YuriyM. Sorry for the confusion.

**Comment by aliaksander-samuseu** [comment]
Sorry, I created this one and probably miss-clicked somewhere in a hurry.

**Comment by YuriyM** [comment]
No problem

**Comment by mzico** [comment]
+1

**Comment by aliaksander-samuseu** [comment]
@yurem 

Here is what currently in log when this situation occurs:
```
2016-05-08 21:17:01,344 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-6) Failed to connect to LDAP server using configuration source_another
2016-05-08 21:17:01,402 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-6) Skipping cache refresh due to invalid server configuration
```
I think it should be something more clearly describing the cause of the issue, which is the fact that one of the holders of distributed user database is unreachable, so they could start resolving it immediately.

**Comment by YuriyM** [comment]
Hey

Seems my GitHub account @YuriyM was mentioned by mistake and I was not
supposed to receive this email.



On Mon, May 9, 2016 at 12:23 AM, aliaksander-samuseu <
notifications@github.com> wrote:

> @yurem <https://github.com/yurem>
>
> Here is what currently in log when this situation occurs:
>
> 2016-05-08 21:17:01,344 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-6) Failed to connect to LDAP server using configuration source_another
> 2016-05-08 21:17:01,402 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-6) Skipping cache refresh due to invalid server configuration
>
> I think it should be something more clearly describing the cause of the
> issue, which is the fact that one of the holders of distributed user
> database is unreachable, so they could start resolving it immediately.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GluuFederation/oxTrust/issues/168#issuecomment-217746996>
>



-- 
Regards,
Yuriy Mykytyuk

**Comment by YuriyM** [comment]
Hey, duplicate reply here.

Seems my GitHub account @YuriyM was mentioned by mistake and I was not
supposed to receive this email.

On Sun, Dec 20, 2015 at 8:32 PM, aliaksander-samuseu <
notifications@github.com> wrote:

> @Mike <https://github.com/Mike> asked to create a card for this issue,
> but after speaking with @YuriyM <https://github.com/YuriyM> it seems now
> this may be a limitation hidden deep in CR's code, so I decided to make it
> a discussion instead. Here is what he told me (please correct me if I
> misinterpret something):
>
> "If some part of a distributed users database can't be pulled in at this
> iteration, CR can't process the rest of it too as unification of all
> involved user sets has to be done to proceed. We would need to rewrite a
> significant part of current CR's implementation to change this behavior,
> and it won't be an easy task, a lot of time has been spent to polish the
> current one. It's better to request that clients employ fail-over servers
> for each distinct source of user data. Though, we should clearly notify a
> user about something like that is happening in logs"
>
> AFAICR, at the moment in that case some ambiguous message appears in CR
> log, which can confuse a user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GluuFederation/oxTrust/issues/168>.
>



-- 
Regards,
Yuriy Mykytyuk

**Comment by nynymike** [comment]
Let's re-test this in new release.
