### ISSUE TITLE
Improve Error Reporting In oxTrust API

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxTrust#1682]
Currently, the oxTrust API relies on HTTP Status codes (documented with swagger annotations) almost exclusively for error reporting. 
As useful as this may be to report errors,  it isn't quite enough to tell API consumers what actually
went wrong in details. The lack of such error reporting may push the API consumers to almost always have to check out the oxTrust logs to know what actually went wrong. 
We may introduce a class called `OxTrustApiError` to wrap and return more meaningful errors to the user.

**Comment by nynymike** [comment]
Should be in the https://github.com/GluuFederation/oxtrust-api project...
