### ISSUE TITLE
Redirect to requested uri after successfull login

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1683]
# Background
  Gluu Server installed and running.

# Description

When an identity resource like **https://hostname/identity/scope/scopeInventory** is requested from a new incognito browser, the user is redirected to the login page and after successful login, the user is not **redirected back to the originally requested url**. 
That decrease de user experience and increase the development time as two many rounds are required each time the server is reloaded.

**Comment by shmorri** [comment]
No longer necessary due to UI redesign
