### ISSUE TITLE
OpenID Connect  clients :- Added scope info is not shown in Client config Summary

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1684]
## Describe the issue
OpenID Connect  clients :- Added scope info is not shown in Client config Summary
## Steps To Reproduce
1. Go to OpenID Connect 
2. Click on Clients.
3.Add New client with scopes and other info and save it.
4. Click on Client config Summary.

## Expected behavior
It should shows added scope information.

## Actual behavior
No scope info is there

## Desktop (please complete the following information):
  OS: ubuntu 18
 - Gluu version 4.0
 - Browser  chrome
![Screenshot (7)](https://user-images.githubusercontent.com/34593983/59518578-83b66580-8ee3-11e9-8559-47e0b631a47f.png)
![Screenshot (8)](https://user-images.githubusercontent.com/34593983/59518582-85802900-8ee3-11e9-87b2-efb58c2f5e61.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59528512-63cc7500-8ed6-11e9-93f0-827bc8b7843d.png)
