### ISSUE TITLE
Prompt for confirmation before deleting auth method from user profile

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1687]
## Describe the issue
Currently in oxTrust, if you delete an enrolled authentication method from a user's profile, there is no prompt to confirm the action. Since the authentication method is quite important, we should make sure the admin confirms they in fact want to delete the mechanism from the user's account. 
 
## Steps To Reproduce
1. Navigate to Users
1. Find an existing user with enrolled authentication mechanisms
1. Delete one of the authentication mechanisms

## Expected behavior
oxTrust should prompt the admin to confirm they in fact want to delete that authentication mechanism. The prompt should include the Nickname of the authentication mechanisms that is being deleted. 

## Actual behavior
No confirmation prompt currently, the entry is simply deleted when the x is clicked. 

## Screenshots
![image](https://user-images.githubusercontent.com/5271048/59666807-3f1a1b00-91be-11e9-93db-57f092c6fc6f.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59773012-cd68cc80-92a4-11e9-960b-141a51777f5b.png)

**Comment by willow9886** [comment]
Hi @syntrydy 

Let's adjust the message to:

```
Warning: Removing this authentication mechanism could cause lockout or authentication errors for the end-user. 

```

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59845817-2fcdd580-9356-11e9-9779-bd70206ff56c.png)

**Comment by willow9886** [comment]
perfect, thanks! @syntrydy
