### ISSUE TITLE
Scopes list not properly loaded in idp-initiated flows config form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1690]
In the panel to specify the authorization request params, when clicking on "add scope", the list is looking this way:

![scopes_problem](https://user-images.githubusercontent.com/5444180/59713416-10f40580-91d5-11e9-9774-b1f7e4c377f8.png)

 In a previous Gluu 4 build, the list was populated correctly.

Environment: Latest Gluu 4.0 on Centos 7, Firefox browser.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59746361-ad1e1b00-926e-11e9-9bad-a8a4eaabe637.png)
