### ISSUE TITLE
Gluu 4.0 QA - Couchbase :- Not able to see admin profile

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1695]
## Describe the issue
When try to see admin profile it gives an oops error message.

## Steps To Reproduce
1. Go to Manage people.
2. Search admin.
3. Try to see admin profile.
4. It gives oops error message.

## Expected behavior
Admin profile should be open.

## Actual behavior
It gives an 404 error message.

**Comment by mbaser** [comment]
I got 502 proxy error.
![Screenshot_2019-06-21_09-30-27](https://user-images.githubusercontent.com/6398752/59902570-48e28f00-9407-11e9-9c6a-93e942822c37.png)
