### ISSUE TITLE
uma_protection is absent in scope list

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1697]
Steps to reproduce:
1) Go to OpenID Connect > Clients
2) Click Clients
3) Click "Add Client" button
4) Click "Add Scope" button

You won't be able to see `uma_protection` in the **Scopes** popup

![Screenshot_2019-06-22_14-36-56](https://user-images.githubusercontent.com/6398752/59964122-0b642b80-9505-11e9-9cde-e314a33ebc25.png)

**Comment by mbaser** [comment]
I tested with this build: https://repo.gluu.org/centos/7-testing/gluu-server-4.0-1-51.centos7.x86_64.rpm
Backend: LDAP

**Comment by syntrydy** [comment]
The elements is present  in the list of Uma Scopes, not OpenID connects Scopes

**Comment by willow9886** [comment]
Hi @syntrydy but I see uma_scopes in the list of OpenID Connect scopes as well.. see below:

![image](https://user-images.githubusercontent.com/5271048/60010547-4a66be00-9678-11e9-83bd-6feabca3557b.png)

**Comment by syntrydy** [comment]
@willow9886 which server is it? If **uma_protection** shows up now in OpenIdConnect scopes, it means that someone updated the entry in database.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/60205897-4b4f4980-984a-11e9-87ae-66d3422ba883.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/60206044-9e290100-984a-11e9-80b1-6dff38f77050.png)

**Comment by mbaser** [comment]
Checked. It is fixed
