### ISSUE TITLE
OpenID Scopes Display Name is empty

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1698]
Steps to reproduce (LDAP):
1) Go to OpenID Connect > Scopes
2) Click on scoped ID to edit.
3. Display Name will be empty

![Screenshot_2019-06-23_16-54-26](https://user-images.githubusercontent.com/6398752/59977269-e68cb880-95d7-11e9-92c8-bf75f77df65f.png)

**Comment by mbaser** [comment]
tested build https://repo.gluu.org/centos/7-testing/gluu-server-4.0-1-51.centos7.x86_64.rpm

**Comment by syntrydy** [comment]
@mbaser Fixed
