### ISSUE TITLE
oxTrust logout from old session web page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#17]
If you login / logout it works. But if you login... wait a long time... and then hit Logout, the session is not Logged out of the browser. Perhaps the seam session is not valid, so the admin is getting redirected before the Logout is called? Is there some way to fix this? Perhaps auto-close of the oxTrust web UI so that the person no longer sees the Logout link?

**Comment by mzico** [comment]
Need to test if this issue still there in oxTrust or fixed already.

**Comment by nynymike** [comment]
Its not fixed. But its not the highest priority either. Because the oxTrust session is expired, the logout link is invalid... but the openid connect session is still valid, so it lets you in. I think we can perhaps figure out a better solution for this... but I'm not sure what it is right now.

**Comment by zamilskhan** [comment]
I waited and hit logout. This is what I get.
![screenshot-ubuntu gluu info 2015-08-14 03-33-18](https://cloud.githubusercontent.com/assets/7703245/9262270/6613616c-4235-11e5-8efb-22cc47a4ba6d.png)

**Comment by mzico** [comment]
@nynymike : got it, thanks. 

@zamilskhan : Thanks. Yes, this logout is happening but openID connect session is active even after logout. Not a high priority issue right now.

**Comment by mzico** [comment]
@nynymike @zamilskhan @yurem: Feel free to test this with 2.4.1. Logout improved in this version.

**Comment by yurem** [comment]
We also has plan to deprecate basic oxTrust authentication method: https://github.com/GluuFederation/oxTrust/issues/188

**Comment by yurem** [comment]
We removed this deprecated functionality
