### ISSUE TITLE
Add warning when deleting active SAML TR

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1700]
I can't delete active SAML TR, in order to delete, it should be deactivated first. If this is expected behavior we need to add such warning "Deactivate to delete TR".
Steps to reproduce:
1) Go to "SAML > Add Trust Relationships"
2) Add a TR
3) Wait it to be validated
4) Try deleting, it won't delete
5) To delete hit "Deactivate" button.
6) Now you can delete by hitting "Delete" button.

**Comment by syntrydy** [comment]
Fixed!

**Comment by mbaser** [comment]
Tested. It is fixed.
![Screenshot_2019-06-27_15-40-23](https://user-images.githubusercontent.com/6398752/60267080-0979de00-98f2-11e9-9489-d1a4c004838b.png)
