### ISSUE TITLE
Bug: Failed to add policy script in UMA scope

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#1702]
## Describe the issue
Failed to add policy script in UMA scope. 

## Steps To Reproduce
1. Go to `UMA > Scopes > `
1. Click on any one scope 
1. Click on `Add Authorization Policy` button
1. Select any other script and click ok
1. After clicking on `ok`, nothing is happening

## Expected behavior
It should show the selected policy after clicking ok and add on update operation

## Actual behavior
After clicking on Ok button in the popup, nothing is happening.

## Screenshots
Please chek the video in zip
[bug.mp4.zip](https://github.com/GluuFederation/oxTrust/files/3335021/bug.mp4.zip)

## Desktop (please complete the following information):
 - OS: Ubuntu16.04LTS
 - Gluu version 4.0
 - Browser: chrome
 - Browser Version: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by syntrydy** [comment]
@ldeveloperl1985 I'm using the latest package with the latest war and I can 't reproduce it. Are you using the latest war as well?

**Comment by ldeveloperl1985** [comment]
I've download today this version `gluu-server-4.0_1-59~xenial+Ub16.04_amd64.deb`. Anyway please provide me a link of the latest war. I'll test again

**Comment by syntrydy** [comment]
@ldeveloperl1985 think the issue description is not correct. The issue is that we can't add more than one policy script to a Uma scope. If you add one policy it works, more than one it fails.

**Comment by ldeveloperl1985** [comment]
Yes, but it also fails when I tried to add a single policy in a **newly created scope** case. Please follow the below step to reproduce
1. Add one new scope
2. then try to add policy in new uma scope, it is failing

Please check the video in zip file https://github.com/GluuFederation/oxTrust/files/3335021/bug.mp4.zip
