### ISSUE TITLE
Remove Name field from nameid screen

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1707]
Remove Name field from nameid screen (redundant, not required) refer discussions

![image](https://user-images.githubusercontent.com/8274294/60758111-5db34b00-9fe1-11e9-9960-7999743ba5df.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/60767841-5f4e4300-a0b5-11e9-8bd9-08470a386ffb.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/60768358-2add8580-a0bb-11e9-8223-11d70276a8fa.png)
