### ISSUE TITLE
Add "active" column to import spreadsheet

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#171]
At the moment imported users don't have value "active" assigned to the "gluuStatus" attribute, so it won't be possible to use them right away. A user will then need to activate all these accounts manually through web UI, one by one, or by using command line tools. Perhaps adding a new column "Status" to import files' template could make this whole process more convenient and straightforward.

**Comment by aliaksander-samuseu** [comment]
Another viable solution for the first problem could be ability to change at least some most simple settings of multiple user accounts, plus implemented extended search filters for the "Manage People" page. So an admin user could first search for accounts with "Active" flag not set, set some "Select all" checkbox, click the button "Bulk edit", select corresponding property from the list of supported by this mode, and set it to Active in one go for all these accounts. (Something like that is implemented in Jira and allows to change certain properties for a selection of bug reports at once)

**Comment by aliaksander-samuseu** [comment]
Another viable solution for the first problem could be ability to change at least some most simple settings of multiple user accounts, plus implemented extended search filters for the "Manage People" page. So an admin user could first search for accounts with "Active" flag not set, set some "Select all" checkbox, click the button "Bulk edit", select corresponding property from the list of supported by this mode, and set it to Active in one go for all these accounts. (Something like that is implemented in Jira and allows to change certain properties for a selection of bug reports at once)

**Comment by aliaksander-samuseu** [comment]
Another viable solution for the first problem could be ability to change at least some most simple settings of multiple user accounts, plus implemented extended search filters for the "Manage People" page. So an admin user could first search for accounts with "Active" flag not set, set some "Select all" checkbox, click the button "Bulk edit", select corresponding property from the list of supported by this mode, and set it to Active in one go for all these accounts. (Something like that is implemented in Jira and allows to change certain properties for a selection of bug reports at once)

**Comment by nynymike** [comment]
Pre-encoded passwords can be supported with respective prefix as specified in https://tools.ietf.org/html/draft-howard-rfc2307bis-02
