### ISSUE TITLE
Enhance usability in passport's idp-initiated flow form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1713]
Currently users need to click `Add`, choose IDP, fill remaining data (or accept defaults), then click on `Save`.

That takes them to the summary table. At that point nothing has been saved to ldap, and it is not too evident they need to press  `Update` to finalize the process. 

In the internal discussion we mentioned 2 options:

- Avoid `Update` by persisting when saving, or 
- Display a warning if the user tries to leave this page before hitting `Update` (eg “do you want to save or discard your changes”?)

**Comment by willow9886** [comment]
> Avoid Update by persisting when saving, or

Yes, shouldn't need to update and save.. should be one or the ther.
