### ISSUE TITLE
Add ID and callback URL field to passport providers form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1714]
In our discussion we agreed the ID should not be generated for identity providers but entered manually, so we need to add such new field to the form.

Upon form validation we should check:
- The ID only contains chars: a-z A-Z hyphen dash or digits
- There is not other provider already registered with the same ID

When a provider is created:
- the ID form field should be read-only
- A new read-only field "Callback URL" should appear. Its value will be:

`https://<host-name>/passport/auth/saml/<PROVIDER-ID>/callback`  if the provider is of type saml, or
`https://<host-name>/passport/auth/<PROVIDER-ID>/callback` otherwise

I think we can place it under the checkboxes because it can be lengthy.

**Comment by jgomer2001** [comment]
Ideally we can move ID column as the first one in the summary table of providers added so far.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61052640-bf115a80-a3e3-11e9-8013-1dc396f973b9.png)

![image](https://user-images.githubusercontent.com/7513418/61065051-d3148680-a3fa-11e9-8319-d9aa216ccb22.png)

![image](https://user-images.githubusercontent.com/7513418/61065203-1ff85d00-a3fb-11e9-934a-41e8449c28de.png)

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/61292657-d5caff00-a79f-11e9-8e59-e273b971fd78.png)

Please fix to disallow use of duplicate provider IDs
