### ISSUE TITLE
Make port in passport basic configuration read only

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1715]
We should not allow this parameter to be changed. It is unlikely someone needs it.

It is too involved to offer a completely functional port change as well: requires updating ldap, httpd.conf, and passport service updates.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61036921-f838d300-a3c1-11e9-9773-43f39a6292a2.png)
