### ISSUE TITLE
Support for Default ACR (AuthnContextClassRef) Setting in TR Config

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1722]
## Describe the issue
In TR Configuration Screen - option shall be provided so that user can associate a default ACR/AuthnContextClassRef for TR.

**Comment by malotian** [comment]
@syntrydy we need to provide a options, user can select from.
options shall be populated from xml (same way - as done on person script page)

**Comment by malotian** [comment]
![image](https://user-images.githubusercontent.com/8274294/61192178-7924f280-a680-11e9-98e0-c3bea96cd185.png)
@syntrydy we need following sort of ui update

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61329664-d30af100-a815-11e9-8ca1-7256a1b4a8c7.png)

**Comment by syntrydy** [comment]
@malotian **/opt/shibboleth-idp/conf/authn/general-authn.xml** don't contain the list of expected values.

**Comment by malotian** [comment]
Preliminary testing showed working fine. more detailed testing to be conducted
