### ISSUE TITLE
Support for Default NameID Setting in TR Config

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1723]
##  Describe the issue
In TR Configuration Screen - option shall be provided so that user can associate a default NameID for TR.

**Comment by malotian** [comment]
![image](https://user-images.githubusercontent.com/8274294/61376537-63295480-a86f-11e9-891a-68b38c9836ef.png)

**Comment by malotian** [comment]
values should be as done for nameIDType in Configure Custom NameID screen (e.g)

![image](https://user-images.githubusercontent.com/8274294/61376703-aaafe080-a86f-11e9-8f87-ce87ab50948f.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61394224-92b17e80-a8ba-11e9-8c36-da23cbb61cf8.png)

**Comment by malotian** [comment]
Preliminary testing showed working fine. more detailed testing to be conducted
