### ISSUE TITLE
Add Support to Edit Supported ACRs via GUI (for TR)

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1726]
1) GUI to edit general-authn.xml <bean parent="shibboleth.SAML2AuthnContextClassRef" c:classRef="xyz" />.
2) Render general-authn.xml. Do we need to restart IDP after that? We can extract this <list> into separate xml file and add include into general-authn.xml
3) Add to TR GUI new option to specify auth method

There is more info in saml channel

**Comment by yurem** [comment]
It's for point 3: https://github.com/GluuFederation/oxTrust/issues/1722

**Comment by malotian** [comment]
tried yuriy's suggestion to split the config files, but couldn't get through.
Also however it will be better to keep single file only that is - general-authn.xml, via introducing general-authn.xml.vm velocity templates.

**Comment by syntrydy** [comment]
@malotian so what to do then? please provide all details and when done I can start working on this ticket.

**Comment by malotian** [comment]
@syntrydy I will plan to work in this in couple of days, But you can keep front end ready which can create/edit/render c:classRef values

<property name="oxauthSupportedPrincipals">
<list>
        <bean parent="shibboleth.SAML2AuthnContextClassRef"
               c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol" />
        <bean parent="shibboleth.SAML2AuthnContextClassRef"
               c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
        <bean parent="shibboleth.SAML2AuthnContextClassRef"
               c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:Password" />
</list>
</property>

**Comment by malotian** [comment]
User should be able to Add, Edit, Delete new values.

**Comment by syntrydy** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<bean id="authn/oxAuth" parent="shibboleth.AuthenticationFlow"
                p:forcedAuthenticationSupported="true"
                p:nonBrowserSupported="false" >
            <property name="supportedPrincipals">
                <list>
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:Password" />
                </list>
            </property>
</bean>
```

**Comment by yurem** [comment]
@syntrydy we need to add also `beans` section:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
                           http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd"
...<your_bean_part>
</brans>
```

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/62149160-027c2c00-b2f3-11e9-86e9-6c8371b8edbb.png)

**Comment by malotian** [comment]
looks good, will add backend support

**Comment by malotian** [comment]
oxTrust\server\src\main\java\org\gluu\oxtrust\action\SamlAcrAction.java:[17,29] error: cannot find symbol

@syntrydy 
seems like you haven't committed model - org.gluu.oxtrust.model.SamlAcr

**Comment by malotian** [comment]
Its working from GUI Perspective, but still writing to file is pending

**Comment by malotian** [comment]
@syntrydy serialize to ACR settings to LDAP as being done for TRs and other

**Comment by malotian** [comment]
Menu Item can be named as 'Manage SAML ACR', and move under Configuration

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/62330906-0b672c00-b4b2-11e9-9a2d-0e870d811e62.png)

**Comment by malotian** [comment]
2019-08-02 16:11:55,659 ERROR [qtp413601558-18] [org.gluu.oxtrust.action.SamlAcrAction] (SamlAcrAction.java:62) - Error loading saml acrs
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=samlAcrs,o=gluu, filter: (&(objectClass=samlAcr))
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:404) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.findEntries(BaseEntryManager.java:131) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]

**Comment by malotian** [comment]
@syntrydy ldap persistence is not working

**Comment by malotian** [comment]
@syntrydy it require schema changes, and placeholder ou creation
