### ISSUE TITLE
Support for nameIDFormatPrecedence Setting in TR Config (extension of #1723)

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1731]
## Describe the issue
In TR Configuration Screen - option shall be provided so that user can associate a order of preference to NameID Formats for TR (via SSO profile)

**Comment by malotian** [comment]
![image](https://user-images.githubusercontent.com/8274294/61489473-c521b100-a978-11e9-804a-2e1458c7dfba.png)

**Comment by malotian** [comment]
basically Options will be available in list box, User can choose which he wants and move to left box, and user can change order in left list box,

eventually user can have multiple values for nameIDFormatPrecedence, and control order/sequence as preference

**Comment by malotian** [comment]
basically this is extension of #1723

**Comment by malotian** [comment]
![image](https://user-images.githubusercontent.com/8274294/61644435-a66e3380-ac72-11e9-90b8-18c6c83eb179.png)

**Comment by malotian** [comment]
only when check-box is selected, unspecified ll be available
if unchecked, it shall be removed from both.
and on selection it shall be added to Available only.

**Comment by malotian** [comment]
we need not to persist this checkbox. only selected values will required to be persisted

**Comment by malotian** [comment]
while reading the persisted settings, if list included urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified, show checkbox as checked.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61710547-c7ee1e80-ad49-11e9-9525-7b8a0c963b97.png)

![image](https://user-images.githubusercontent.com/7513418/61710602-df2d0c00-ad49-11e9-8f70-16d58e50871a.png)
