### ISSUE TITLE
During user import if user status is not set, the default should be set to Inactive

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1732]
## Describe the issue
Set user status to **Inactive** during the import if the value is not provided.

**Comment by willow9886** [comment]
Docs added to specify as much: 

https://gluu.org/docs/ce/4.0/user-management/local-user-management/#file-structure

> Note: If User Status is not included, the default is set to Inactive

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61552258-39c71f00-aa4f-11e9-9579-4b7ac2787482.png)

**Comment by syntrydy** [comment]
@sahiliamsso  to test user import, you can use this exel file here. https://docs.google.com/spreadsheets/d/19lL_eThtFcC84nzpxn5wcDdtAzuVuudnuruLRAA89Pc/edit?usp=sharing

**Comment by sahiliamsso** [comment]
This file doesn't have the password, so failing at the validation step

**Comment by syntrydy** [comment]
> This file doesn't have the password, so failing at the validation step

really? I tested users import with that file, the password field is not mandatory during user import.
