### ISSUE TITLE
Use better property names in basic passport config

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1734]
As discussed in ticket [7200](https://support.gluu.org/7200) the labels SP TLS cert & key are not appropriate, let's replace the following way:

spTLSKey -> Passport SP Decryption Private Key
spTLSCert -> Passport SP Decryption Cert

Since new names are long, I propose to move those under "POST profile data" and make them occupy the full row (not a single column). Probably we could do the same for "POST profile data to" as well.

![sptls](https://user-images.githubusercontent.com/5444180/61578770-45ebc480-aac1-11e9-9a0b-3eea8a07ffab.png)

Related https://github.com/GluuFederation/docs-ce-prod/issues/201

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61626636-ade30c00-ac75-11e9-9b68-3dd6bd8441ff.png)
