### ISSUE TITLE
Support for urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified 

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1735]
## Describe the issue
Support required Name ID Format - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

**Comment by malotian** [comment]
latest shibb doesn't support - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified, format by default (deprecated)

since customers may need this as - mentioned by @mzico, so need to see alternatives to support same.

**Comment by malotian** [comment]
@syntrydy we will need gui enhancements in SSO profile, to support this.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61616390-2c34b380-ac60-11e9-9c1c-c4459ccffaf8.png)

![image](https://user-images.githubusercontent.com/7513418/61616564-b715ae00-ac60-11e9-82e6-79890054e291.png)
