### ISSUE TITLE
Typo in SCIM configuration endpoint

### ISSUE THREAD

**Issue by stakoz** [GluuFederation/oxTrust#174]
Path annotation value at [Line 41](https://github.com/GluuFederation/oxTrust/tree/master/server/src/main/java/org/gluu/oxtrust/ws/rs#L41) probably had to be:
```
@Path("/oxtrust/scim-configuration")
```

Related to [#109](https://github.com/GluuFederation/oxTrust/issues/109).

**Comment by willow9886** [comment]
Thanks @stakoz . I've updated line 41 to fix the typo.
