### ISSUE TITLE
Unable to view Gluu user details at oxTrust UI, created using interceptor script

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#1740]
## steps to Reproduce

Create user using interceptor script 

 ```
     newUser = User()
            
		newUser.setAttribute("cn", my_cn)
            
		newUser.setAttribute("sn", my_sn)
            
		newUser.setAttribute("uid", my_uid)
            
		newUser.setAttribute("mobile", my_mobile)
            
		newUser.setAttribute("mail", my_email)
            
		newUser.setAttribute("givenName", my_firstname)
            
		newUser.setAttribute("displayName", my_displayname)
            
		newUser.setAttribute("oxExternalUid", my_uid)
            
		newUser.setAttribute("userPassword", my_password)
            
		newUser.setAttribute("iname", my_email)
            
		newUser.setAttribute("gluuStatus", gluu_status)
            
foundUser = userService.addUser(newUser, True)
```

User is now created in Gluu ldap
At oxTrust UI if you do people search. You can see the user in search result. But when you click on the user to view the details or edit, that page does not appear.
It does a 302 redirect to identity/person/personInventory.htm

https://gluu_idp/identity/person/update/@!E1FA.6A90.941D.1222!0001!E95E.9628!0000!66C0.B8B7.A501.319C

## Expected behavior
	oxTrust should display the user details which is created by interceptor script

## Actual behavior
	oxTrust does not display the user details which is created by interceptor script

## Screenshot

![image](https://user-images.githubusercontent.com/20181082/61786900-46bb8800-ae2c-11e9-9540-9d33bff3b193.png)

## Additional Details
Gluu 3.1.6

Ubuntu 16

**Comment by willow9886** [comment]
> Create user using interceptor script

What type of interception script? Can you provide the script so we can better understand?

**Comment by nynymike** [comment]
Not sure this is a bug in the code. What search is it doing? Is a required attribute missing?
