### ISSUE TITLE
Render saml-nameid.properties.vm with uniq salt

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1746]
Right now salt in saml-nameid.properties.vm is hardcoded:
idp.persistentId.salt = saltatgluudotorg

We need to fix this. Salt should be persistent but uniq per server

**Comment by syntrydy** [comment]
I guess the affected part is this

![image](https://user-images.githubusercontent.com/7513418/62204451-0f496000-b385-11e9-88ad-88c0435c9d85.png)

**Comment by syntrydy** [comment]
@malotian can you check the implemented solution and merge if it worked very well.
