### ISSUE TITLE
Show notification about released upgrades

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1749]
Before enabling this user must accept that server will send version, hostname, contact details to gluu server.

We need to show in oxTrust on home page notification that new version or patch is available.

To implement this we can put into repo.gluu.org public available static file with information about versions. We can use JSON to describe versions.

oxTrust can periodically download this file and check if there are upgrades/patches.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83200863-28a17100-a13c-11ea-8940-39321d6a0d03.png)
