### ISSUE TITLE
Detect OS security updates and allow to run upgrade

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1750]
We need to prepare few OS commands. First one is need to check for new upgrades. And second one should run upgrade. This can be one script which supports parameters.

oxTrust should display information about allowed upgrades. We can display list of packages for admin. And after running upgrade it should show console output about upgrade process.

**Comment by nynymike** [comment]
I don't think we should do this in oxTrust... especially considering that oxTrust could be running in a chroot or container.
