### ISSUE TITLE
Unable to Edit Sector Identifier.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1754]
## Describe the issue
If  Sector identifier is added without Login Uri and Add client, During edit it gives error message “Failed to find Sector Identifier

## Steps To Reproduce
1. Login as Admin. Go to OpenID connect
2. Click on Sestor Identifier.
3. Add Sector Identifier without Login URI and Add client.
4. Try to Edit it.
5. See error

## Expected behavior
User should be able to edit Identifier.
## Actual behavior
It Gives an error Message "Failed to Find Identifier".

**Comment by MohitMaliFtechiz** [comment]
![Screenshot from 2019-08-07 16-09-51](https://user-images.githubusercontent.com/34593983/62616759-f7964c80-b92d-11e9-9f7e-83620df39fc6.png)

**Comment by syntrydy** [comment]
@MohitMaliFtechiz please always put the milestone on issue creation, especially for bugs.
