### ISSUE TITLE
Unscrollable dialog boxes 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#176]
* From the menu on the left, choose "OpenID Connect", then "Clients",
  open a client, and then "Add scope".
* This opens a dialog box to search for scopes. Leave the search box
  empty, click "Search".
* The new dialog box is taller than my screen, can't be scrolled, and
  can't be moved so that the bottom of the dialog box becomes visible.

Attached is a screenshot.

This prevents users from easily being able to add scopes to clients. We
have a large number of scopes, and having to type them individually is
a bit of a chore.

This may be an issue in other screens as well. 

![gluu-big-dialog](https://cloud.githubusercontent.com/assets/5271048/11961916/788071dc-a8a1-11e5-9191-63952c0aa44e.png)

**Comment by yurem** [comment]
![fixes](https://cloud.githubusercontent.com/assets/6104200/11963790/e67e27e2-a8f1-11e5-91b4-376aed5ccb17.png)
Fixed: https://github.com/GluuFederation/oxTrust/commit/e0d9adf8dbcfae875122f96ff22591ddd85841e1
