### ISSUE TITLE
Better error handling than "Ooops, Something went wrong" 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1762]
Generally when such "Oops" message come; it's the reason of some issue with identity ( correct me if I am wrong ). However, "Oops" doesn't provide much info or any indication to user where or how should he/she/they can troubleshoot. 

Under the hood, oxtrust.log can reveal the reason of such "Oops". Do you think if there is any better way to guide user when they see "Oops" message? i.e. "Contact your administrator?" ( End user might get it ). OR "Check identity logs?" ( For server administrators ) ?

**Comment by yurem** [comment]
We need to add JSON property to enable detailed error page. With this property application should show stack trace and request details.

**Comment by shmorri** [comment]
No longer necessary due to UI redesign
