### ISSUE TITLE
`getAllActivesAttributes` and `getAllInActivesAttributes` oxTrust API names should be adjusted for natural English

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1763]
The current API names for `getAllActivesAttributes` and `getAllInActivesAttributes` are not currently 
 natural English, which could lead to mistakes in implementation.

I suggest we change them to `getAllActiveAttributes` and `getAllInactiveAttributes`, respectively.

**Comment by syntrydy** [comment]
@shmorri this one fixed. You can regenerate the api doc and the modifications will be visible.
