### ISSUE TITLE
Default ACR Values in LDAP/LDIF

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1770]
Default Installation shall have following ACR Values in LDAP/LDIF (refer #1722)

urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
urn:oasis:names:tc:SAML:2.0:ac:classes:Password

**Comment by malotian** [comment]
@mbaser connect with @syntrydy or @malotian for any further inputs you may need

**Comment by mbaser** [comment]
Added to `oxidp.ldif` by commit https://github.com/GluuFederation/community-edition-setup/commit/4c60fdb72fd8fa583452cc5b79b9b22e4723f94d

@syntrydy please close this issue after you finish your part.
