### ISSUE TITLE
Gluu 4.0 QA | Unable to add custom script with key/value properties

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1779]
## Describe the issue
Unable to add custom script with key/value properties

## Steps To Reproduce
1. Go to Configuration > Manage Custom scripts
Issue: Option to add New Custom script is missing until click on "Person Authentication"
2. Click on "Person Authentication"
3. Enter Name, Description and Click on Add new property

## Expected behavior
Key Value input textbox should appear
## Actual behavior
Nothing happens

4. Enter value in the script box and click Save

Error: OOPS error page

## Screenshots

 - OS:  CentOS 7.6
 - Gluu version: gluu-server-4.0-73.beta3.centos7.x86_64

![CRIssue](https://user-images.githubusercontent.com/21104811/63308158-527d5b80-c2bf-11e9-9377-56f6fda75df2.gif)

**Comment by syntrydy** [comment]
@sahiliamsso i fixed this yesterday. Please use the latest war.

**Comment by syntrydy** [comment]
Already fixed
