### ISSUE TITLE
Email confirmation for registration

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#178]
In order to confirm a user who registers against an IDP actually owns the email address he/she registers with, we need to add an account confirmation prompt before the account is activated. The easiest way to do this would be via email confirmation to demonstrate that the user who registered actually controls the email address account they registered with.

**Comment by yurem** [comment]
I think we can resolve this issue without hardcoding it into oxTrust.
We have next registration script API now:
`
class UserRegistration(UserRegistrationType):
    def init(self, configurationAttributes):
    def destroy(self, configurationAttributes):
    def initRegistration(self, user, requestParameters, configurationAttributes):
    def preRegistration(self, user, requestParameters, configurationAttributes):
    def postRegistration(self, user, requestParameters, configurationAttributes):
    def getApiVersion(self):
        return 1
`

We can add new method to this API
`
    def verifyRegistration(self, user, requestParameters, configurationAttributes):
    def getApiVersion(self):
        return 2
`

**Comment by yurem** [comment]
Next we will do something like this:
`
    def preRegistration(self, user, requestParameters, configurationAttributes):

        // Generate UUID and store it in user entry

        // Store UUID expiration time in user attribute
`

Now we need to send e-mail:
    def postRegistration(self, user, requestParameters, configurationAttributes):
        // Send e-mail here with link to specific oxTrust page with UUID in URL

After that in new method:
`
    def verifyRegistration(self, user, requestParameters, configurationAttributes):
        // Try to find user with UUID from requestParameters
        // Set user attribute gluuStatus = True, remove UUID speciff attributes

**Comment by yurem** [comment]
Last method will be simple:

    def cleanUpRegistrations(sel, configurationAttributes):
        // Remove expired registration with user entries

**Comment by yurem** [comment]
In this approach we only need to add one page to oxTrust which should call action class to call registrationscript.confirmRegistration

It's lightweight solution without deep integration into oxTrust

**Comment by willow9886** [comment]
Beautiful

**Comment by willow9886** [comment]
I think we should assign this to @shekhar16 . @yurem what do you think?

**Comment by willow9886** [comment]
We've decided to handle registration locally inside our apps. i.e. our support app will have its own registration form and it will pass back necessary ifnormation to gluu server via SCIM. This means that we will also be able to handle the email verification without making changes to the idp. 

So, I'm not sure if this is still something we want to address. 

Any comments or feedback welcome.
