### ISSUE TITLE
Unable to Update Uma Resource

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1780]
## Describe the issue
Unable to update Resource when try to update Resource it gives an Error Message.

## Steps To Reproduce
1. Go to Uma. 
2. Click on Resources.
3. Enter all Fields and create a resource.
4. Edit it and try to update it.
5. See Error.

## Expected behavior
Able to Update Resource.

## Actual behavior
It gives an error message.

## Desktop (please complete the following information):
 - OS: Centos 7
 - Gluu version :- gluu-server-4.0-73.beta3.centos7.x86_64.rpm
 - Updated Date :- 2019-08-16
 - Browser  chrome
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34593983/63336726-4051fa80-c35d-11e9-837f-1078b1114e7f.gif)

**Comment by syntrydy** [comment]
Fixed
