### ISSUE TITLE
OpenID Client Delete

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1781]
## Describe the issue
Issue while delete an openID client.

## Steps To Reproduce
1. Go to OpenID Connect
2. Click on Clients.
3. Create a Client.
4. Go to Client list.
5. Search Client which is created.
6. Select it and try to delete it.
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/34593983/63339131-dee05a80-c361-11e9-89be-7c4b33322cfd.gif)

5. See error. Pop Up still remain there.

## Expected behavior
Pop UP should not be there. It opens an Clients list.

## Actual behavior
Delete Pop UP is remains there.

## Desktop (please complete the following information):
 - OS: Centos7
 - Gluu version :- gluu-server-4.0-73.beta3.centos7.x86_64.rpm
 - Updated Date :- 2019-08-16
 - Browser :- Chrome

**Comment by syntrydy** [comment]
Not reproducible
