### ISSUE TITLE
Forgot  Password :- Validation and Design Error.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1788]
## Describe the issue
Forgot Password :- Check the design and validation message Of Reset Password Page.

Steps To Reproduce:-
1) Go To forgot password.
2) Enter email and click on Forgot Password Button. See Validation Message.
3) Now Click on link receive on Mail. Reset Password Page is open. See Error.

## Expected behavior
1) Design Of Reset Password Form, the fields should not overlap the container.
2) There is no duplicate message in the top right corner.
3)  When user Enter email address and click on Send Email Button Validation Message should be " Check your email for a link to reset your password ". And the form fields should  not be there only message should be there.

## Actual behavior
1) Fields are overlapping in the container.
2) There is a duplicate message in the top right corner.
3) Field is there and Validation message content needs to be change.

## Desktop (please complete the following information):
 - OS: Centos7
 - Gluu version :- gluu-server-4.0-73.beta3.centos7.x86_64.rpm
 - Updated Date :- 2019-08-16
 - Browser :- Chrome, Firefox.
 
![Screenshot from 2019-08-23 21-12-56](https://user-images.githubusercontent.com/34593983/63696226-dbecda80-c837-11e9-9cd7-7d40b5b1aa24.png)

**Comment by syntrydy** [comment]
@MohitMaliFtechiz this is already fixed in the latest war.
