### ISSUE TITLE
Cache Refresh / Set 'Max Connections' to 2 or any non-zero number

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1789]
Change value of 'Max Connections' to 2. Without any non-zero number, Cache Refresh doesn't work. So let's make it non-zero out of the box. 
![Capture](https://user-images.githubusercontent.com/7156097/63860659-1e650300-c96f-11e9-96a1-37c91c42aed5.PNG)

**Comment by syntrydy** [comment]
Fixed in OxService, default set to 2 as requested
