### ISSUE TITLE
attribute-resolver.conf produced from the latest Velocity template leads to Shibboleth's (idp.war) crash at service startup

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#179]
Preconditions:
1. When reproducing, please keep in mind [accompanying issue](https://github.com/GluuFederation/community-edition-setup/issues/73) which can interfere with your judgement.
2. Check [this issue](https://github.com/GluuFederation/community-edition-setup/issues/72) to understand why we need to acquire configuration templates like that
3. Freshly installed 2.4.0-1 instance is recommended for reproduction (isn't tested for newer packages)

Steps to reproduce:
1. Start the gluu-server24 service (if needed) and move into the container
2. Stop tomcat service (`/etc/init.d/tomcat stop`)
3. Remove /opt/idp/conf/attribute-resolver.xml and  /opt/idp/conf/attribute-filter.xml files
4. Download updated versions of templates for these 2 files (attribute-resolver.xml.vm and attribute-filter.xml.vm) from [this branch](https://github.com/GluuFederation/oxTrust/tree/master/configuration/template/shibboleth2/idp) and put them into /opt/tomcat/conf/shibboleth2/idp/ (it seems other templates haven't been changed); make sure that "tomcat" user is still owner of these 2 files
5. Start tomcat service (`/etc/init.d/tomcat start`)
6. The shibboleth module (idp.war) will most likely fail to start this time as it won't be able to find these 2 files removed from  /opt/idp/conf/ on step 3) - it seems tomcat regenerates them too late; you need to wait until it will do this anyway; you may opt to monitoring the contents of the directory with something like `watch 'ls /opt/idp/conf/'`; when these files again appeared in /opt/idp/conf/ - stop tomcat again
7. Remove/Rename /opt/idp/logs/idp-process.log to make analyzing it easier
8. Start tomcat again.

Result:

Shibboleth module failed to initialize and SAML SSO does not function ([here is](https://github.com/GluuFederation/oxTrust/files/71131/storedid.txt) complete contents of idp-process.log). The cause of it seems to be the "DataConnector" element labeled "StoredID" which is present in the latest (downloaded on step 4)) attribute-resolver.xml.vm template and isn't commented out by default. Commenting out this element, and several other elements referencing it, seems to resolve the issue. These elements seems to be the only addition to the template's code, comparing to the previous (issue-less) version. Also, this data connector element seems to depend on mysql, and AFAIK we don't use it anymore. I'm providing its definition below for convenience:

```
<resolver:DataConnector xsi:type="StoredId" xmlns="urn:mace:shibboleth:2.0:resolver:dc"
                        id="StoredId"
                        sourceAttributeID="uid"
                        salt="ufujAWGSuzbCtRRcMYpnCujW0r8+55jE8Ez64AO7NV1">
     <resolver:Dependency ref="siteLDAP" />
    <ApplicationManagedConnection jdbcDriver="com.mysql.jdbc.Driver"
                               jdbcURL="$mysqlUrl"
                               jdbcUserName="$mysqlUser"
                               jdbcPassword="$mysqlPass" />

</resolver:DataConnector>
```

**Comment by mzico** [comment]
Assigning this to me; I need to test. 

First of all, I won't push latest IDP templates without latest oxIDP.war. 
Secondly, we need to know 'why' we need to push latest templates in existing Gluu Server.

**Comment by aliaksander-samuseu** [comment]
@mzico 
You should discuss the situation with @yurem , I was just relaying his evaluation. if I got it right, these updated templates should be in release long ago, but due to this #72 issue they were "hidden" all that time.

**Comment by willow9886** [comment]
@aliaksander-samuseu are you basically saying that SAML doesn't work?

**Comment by aliaksander-samuseu** [comment]
@willow9886 Not really. That's sort of hard to explain. It's still probable there is some sort of confusion.
When we were doing manual upgrade work at Colby, we ended up with SAML broken at some point. The cause of it happen to be that particular template. When I asked @yurem about it he said that this template that surfaced up during this upgrade project and led to SAML issue (it isn't being applied when you install the CE package the usual way) is, in fact, the most recent and correct one, and it should be applied instead of the one that is being applied at the moment. That template duality happens because of other issue -  https://github.com/GluuFederation/community-edition-setup/issues/72

**Comment by willow9886** [comment]
ok, seems we need @yurem 's input on this..

**Comment by nynymike** [comment]
I'm closing this issue. If it's still an issue after shib idp3 update, let's create a new issue.
