### ISSUE TITLE
UMA Resource :- Unable to Open Resources Page.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1790]
## Describe the issue
Unable to open UMA resources.

## Steps To Reproduce
1. Go to Uma
2. Click on Scopes. Add one scope.
3. Then go to resources. Click on Add resource.
4. Fill all fields and also select scope which is added. Now click on Add button.
5. Now go to (UMA)Scopes and delete the scope which is added.
6. Now try to open Resources(UMA).
7. See Error. It gives an Oops error message.

## Expected behavior
Able to open resources.

## Actual behavior
Opens an Oops error page.

## Desktop (please complete the following information):
 - OS:  Ubuntu16.04LTS
 - Gluu version :- gluu-server_4.0-73-beta3~xenial+Ub16.04_amd64.deb
 - Updated Date :- 2019-08-19
 - Browser :-  chrome, FireFox.
 - Backend DB :- Couchbase

![Screenshot from 2019-08-28 17-55-33](https://user-images.githubusercontent.com/34593983/63864779-0b355000-c9ce-11e9-825c-088877f27927.png)

**Comment by syntrydy** [comment]
Fixed, please check with latest war(i'm gonna to build that in few minutes)
