### ISSUE TITLE
Remove validation for any info from identity registration page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1794]
![Capture](https://user-images.githubusercontent.com/7156097/63955686-c00d5280-ca4a-11e9-94df-7f640742fda7.PNG)

This is how it looks like if user is already here in Gluu Server 3.1.6. 
We should remove any kind of validation message. It might give server's info to outsiders. 

A better approach would be to simply fail the user registration after the user tries to submit the form, with a more general error message, such as: 

`Registration failed. Please try again, or contact the system administrator.`

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/64017963-d981cd80-cb22-11e9-9480-468e4dfaf42f.png)
