### ISSUE TITLE
Manage SAML ACRs - menu not working (beta4)

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1798]
Oops
Something wrong happened.

![image](https://user-images.githubusercontent.com/8274294/64080875-d6bfdd80-ccc6-11e9-9c06-8ca0fdc3382a.png)

**Comment by syntrydy** [comment]
@malotian, How to replicate this? Please follow issue creation template

**Comment by syntrydy** [comment]
@malotian can you test this on the latest package(beta5)
