### ISSUE TITLE
Validation Status - Empty/Nothing(beta4)

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1799]
![image](https://user-images.githubusercontent.com/8274294/64081028-5c448d00-ccc9-11e9-91f8-fbc920a2524d.png)

Since TR is Invalid, so unable to test TR, receiving error
This page isn’t working test.gluu.org is currently unable to handle this request.
HTTP ERROR 503

**Comment by malotian** [comment]
working after restart

**Comment by syntrydy** [comment]
Okay, Normally you just have to wait for validation to finish. Closing now.
