### ISSUE TITLE
Fix Cluster configuratiuon

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#18]
It looks like GUI is broken. What about moving these options to new page from organization page?

**Comment by mzico** [comment]
We don't need this feature now; we have different cluster solution. It would be better to remove/hide this button. What do you think, @yurem?

**Comment by yurem** [comment]
yes, we need to remove this from organizationForm.xhtml and clean up related beans and action classes

**Comment by yurem** [comment]
Fixed: 14af4b79e68a04b1c6ac83b782e93db18768d3ad, 20ee32a93d86617b13d9083633acf85dcb7a4811
