### ISSUE TITLE
Gluu 4 QA: Keep same design for expanded / contrasted passport idp-initiated "widget"  

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1802]
When the widget is not expanded, it looks like this: 

![image](https://user-images.githubusercontent.com/5271048/64128782-9e98c780-cdb8-11e9-8ee7-8998aba53c26.png)

After clicking `Add`, the widget takes on the following modified design: 

![image](https://user-images.githubusercontent.com/5271048/64128790-ace6e380-cdb8-11e9-804f-7908160da780.png)

To reduce confusion, the same design for this "widget" should be present after clicking the `Add` button.

**Comment by willow9886** [comment]
Also note how the page buttons change once you "expand" this widget.. 

Initially, we have: `Update` and `Cancel` buttons. But then, once the widget is expanded.. we have `Save` and `Cancel`. Not sure what the difference is.. but these types of differences are not good for UX.

**Comment by syntrydy** [comment]
@willow9886 there are different, you can see from their title.
I think is quite common to see such behavior in web app. 
It works like this: 
- Click on **Add** button
-  The list part is hidden automatically and the form shows up
- User can fill the form and save to add to the list and the form disappears when the list becomes available again.

**Comment by syntrydy** [comment]
Here is how I fixed it @willow9886 
![image](https://user-images.githubusercontent.com/7513418/64610643-a0b9e200-d3c7-11e9-811e-7de4df232fd7.png)
When the **Add** button is clicked we have this:
![image](https://user-images.githubusercontent.com/7513418/64611190-c98ea700-d3c8-11e9-8704-df6e765a928e.png)

NB: We reuse the same page for efficiency.
