### ISSUE TITLE
Gluu 4 QA: Standardize "please wait" look and feel

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1804]
Seems we have at least two slightly different designs for the "please wait" loading bar.. We should have only one design for this. 

Also, instead of "Please wait" , lets use the content: `Loading..` 

Style 1:

![image](https://user-images.githubusercontent.com/5271048/64133636-ec70f800-cdd7-11e9-98a7-f4b6067d5c30.png)

Style 2: 

![image](https://user-images.githubusercontent.com/5271048/64133639-f1ce4280-cdd7-11e9-9a63-01c59894fac0.png)

**Comment by syntrydy** [comment]
@willow9886 Fixed.
