### ISSUE TITLE
“show error” button does nothing if cust script has error

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1809]
When a script has an error, the "show error" button appears but clicking on it does not display the usual pop up

Environment: latest ce 4.0 beta on stretch
browser: recent chrome

![no_error](https://user-images.githubusercontent.com/5444180/64261697-875df500-cef2-11e9-95dd-f37a4c6d8d85.png)

**Comment by syntrydy** [comment]
@jgomer2001, I tested and it is working. Make sure in your case there is an error in the log because the same error in log is shown on the UI.

**Comment by jgomer2001** [comment]
the problem is gone in the latest package
