### ISSUE TITLE
[Attributes] Attempt to add attribute with underscore in the "Name" field fails

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#181]
Steps to reproduce

1) Log in to web UI as admin
2) Move to "Attributes" page, click the "Add Attribute" button
3) Provide some valid values for all mandatory fields there, but use underscore character in the "Name" input field
4) Click the "Add" button

Result:

Attribute isn't added and [this error message](https://github.com/GluuFederation/oxTrust/files/71924/attribute-name-undersc.txt) appears in oxtrust.log. It seems that despite oxTrust notifies use that only letters and underscores are allowed, opendj's current configuration doesn't allow such names in its schema.

**Comment by mzico** [comment]
This is not bug, please request an 'enhancement' for 2.4.3 release in trello.
