### ISSUE TITLE
Unable to Add OpenID connect Clients

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1813]
## Describe the issue
When Try to add new client (OpenID connect), it gives Opens an Oops Something Wrong happened Page.

## Steps To Reproduce
1. Go to OpenID connect.
2. Click on Client. Client List page is open. Click on Add Client button.
3. Enter Client name, Client description, Add Scopes, Add Response Type and Sector Identifier.
4. Now click on Add button. See Error.

## Expected behavior
Client should be added successfully.

## Actual behavior
It opens an Oops error message page.

## Desktop (please complete the following information):
 - OS:  Ubuntu16.04LTS
 - Gluu version :- gluu-server_4.0-78-beta4~xenial+Ub16.04_amd64.deb
 - Updated Date :- 2019-09-03 (Opendj db)
 - Browser :- chrome, Firefox
![ezgif com-gif-maker(5)](https://user-images.githubusercontent.com/34593983/64338369-338d0200-cfff-11e9-9019-71a526312abb.gif)

**Comment by syntrydy** [comment]
Fixed
