### ISSUE TITLE
Gluu 4 QA: SAML SSO Profile screen needs Rededign/Reformat

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1815]
![image](https://user-images.githubusercontent.com/8274294/64455158-e53d3900-d0ba-11e9-9fe9-5a5a0068a6fc.png)

Need a realignment/reformatting here, Not looking impressive/soothing…

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/64535453-3d6c7900-d30f-11e9-9c76-abe7969f1de1.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/64535632-8cb2a980-d30f-11e9-89aa-dba45881d5b3.png)
