### ISSUE TITLE
Disable debug output in production profile by default

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#182]
We need to disable debug output in production builds.
Also we need to review log messages where we may log invalid password user to log. We should not log them because user can made typo.

**Comment by yurem** [comment]
Also it will be nice to add few additional loggers to allow enable debug logging for specific componnet only.

**Comment by shekhar16** [comment]
Fixed .
Added new variable in config-build.properties file for log level.
and used this property in log4j.xml file to set loge level for "org.oxtrust" logs.
