### ISSUE TITLE
Change Ldap to DB for cust script location type

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1821]
For *presentation purposes*, we need to change "Ldap" with "DB" in  location type field of cust script form.

![location](https://user-images.githubusercontent.com/5444180/64561853-45c5b380-d311-11e9-8b9b-fea46f704c16.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/64570190-b98aaf00-d357-11e9-8391-6b3f7190372b.png)
