### ISSUE TITLE
Can't add UMA Scope

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1822]
OS: CentOS7
gluu package: gluu-server-4.0-80.beta4.centos7.x86_64.rpm

Steps to reproduce:
1. Install gluu server with couchbase backend
1. Go "UMA --> Scopes"
1. Click "Add Scope"
1. Fill fields
1. Click "Add Scope"

It will timeout and get the following screen:

![Screenshot_2019-09-10_14-33-53](https://user-images.githubusercontent.com/6398752/64610545-234a9d80-d3d8-11e9-8616-c03fa49965b7.png)

ADDITIONALLY: oxtrust goes to infinite loop for this query (oxtrust_persistence.log):

```
SELECT oxId, oxScopeType, oxIconUrl, oxUmaPolicyScriptDn, oxScriptDn, displayName, oxAuthClaim, description, inum, defaultScope, oxAuthGroupClaims, dn FROM `gluu` AS gluu_doc WHERE objectClass = "oxAuthCustomScope"
```

**Comment by syntrydy** [comment]
@mbaser  Which Database?
