### ISSUE TITLE
Boolean and numeric values inserted as string in user profile

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1828]
Hi @yurem I'm assigning this to you firstable so you can determine if the observed behavior in couchbase is correct or not:

Steps to reproduce:
- In oxtrust `Configuration` > `Attributes`  > `Register attribute`
- Fill the form choosing Type= boolean
- Insert or modify a user and assign a value for this attribute (eg True)
- Check the document stored in cb. It will look like: 

```
 ...
  "attribute": "true"
}
```

is `"attribute": true` expected instead ?

That's on one hand, on the other, register a numeric attributes ends up saved in oxtrust like 

```
 ...
  "attribute": "100"
}
```

are we expecting `"attribute": 100` here ?

**Comment by yurem** [comment]
Implemented
