### ISSUE TITLE
Only first value of multi-valued attributes are stored in couchbase

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1829]
Steps to reproduce:
- In oxtrust Configuration > Attributes > Register attribute
- Fill the form selecting multivalued = true
- Insert or modify a user and assign several values for this attribute
- Saved document only contains the first one value this way:

``` 
 ...
  "attribute": "value1"
}
```

correct would be (assuming values are strings):

``` 
 ...
  "attribute": ["value1", "value2" ... ]
}
```

**Comment by yurem** [comment]
Is i about custom attributes? Fixed.
