### ISSUE TITLE
Gluu 4.0 QA | Advanced settings radio button changes to textbox after updating client

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1831]
Advanced settings radio button changes to textbox after updating client

## Steps To Reproduce
1. Go to OpenID Connect > Clients 
2. Click on edit client
3. Click on Advanced settings tab
4. Check "Access Token as JWT:" radio button and click update
5. Check Advanced settings again,

## Expected behavior
Access Token as JWT radio button should be selected
## Actual behavior
All radio buttons are shown as text box. On screen refresh , it changes back to radio button

## Screenshots
![openIdradio](https://user-images.githubusercontent.com/21104811/65005182-fa8d4100-d8cc-11e9-990e-5a738a870b0c.gif)

 - OS: CentOS Gluu 4.0 Rc1 with couchbase

**Comment by syntrydy** [comment]
@sahiliamsso this is fixed.
