### ISSUE TITLE
Adding Custom Scripts button should be easier to find

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1832]
## Describe the issue
Currently, the `Add New Script` button shows up when you select the category you want to add a new script at the top of the page. 

## Steps To Reproduce
1. Go to 'Configuration' > 'Manage Custom Scripts' 
2. Minimize the 'Person Authentication' tab
3. Expand the 'Person Authentication' tab

## Expected behavior
The `Add New Script` button should be shown under the Person Authentication tab when the window opens, instead of having to close it and open it again. Additionally, the button should be displayed aligned left or right above the script panel, rather than above navigation.

## Actual behavior
The button only appears if clicking away from the category and back on it, and is displayed above navigation.

## Screenshots

Current display when opening the page:

![image](https://user-images.githubusercontent.com/36208047/65154262-cf9c0d80-d9f0-11e9-9ac5-5e5deefa998f.png)

After clicking away and back:

![image](https://user-images.githubusercontent.com/36208047/65154311-e5113780-d9f0-11e9-9419-d7616a1e928d.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/65178228-31d82b00-da50-11e9-86e1-f425520b4dac.png)

![image](https://user-images.githubusercontent.com/7513418/65178281-53391700-da50-11e9-9328-76da5cbc3c25.png)
