### ISSUE TITLE
Claims associated with custom attributes won't appear in list when adding a claim to a scope.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1835]
Quoting customer who originally reported it:

>  I've manually registered ~14 of our custom attributes. All of the custom attributes have a usage type of openid with an oxAuthClaim name set

>Afterwards I go to: OpenID Connect -> Scopes -> Add Scope, enter a display name and desc, set the scope type to dynamic, then click on Add Claim, none of the claims I've manually entered show up in this list. I have to instead search for them. This is inconvenient as only one claim can be entered at a time. Can you change this please?

I was able to confirm this behaviour. IMO, any custom attribute defined with "oxAuth claim name" property set and/or "Usage Type" set to "OpenID" should appear in this list along with pre-packaged standard attributes/claims, and search function should only be used to narrow down this long list, if needed.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/65281672-0ece7980-db2b-11e9-9a60-7ffd4fa48f99.png)
