### ISSUE TITLE
CustomScript Screen -  CustomScript, and ACR association can't be removed.

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1836]
ACRs list shall have Empty/None as List Item, So that Custom script can be disassociated from ACRs.

Note: None or Empty Item shall not be persisted to Ldap

**Comment by syntrydy** [comment]
@malotian  where is the screenshot.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/65283448-109a3c00-db2f-11e9-8724-0a3f9586ce16.png)


@aliaksander-samuseu on this SAML ACRS you can select and unselect as you want. So I don't see any issue with it.

**Comment by aliaksander-samuseu** [comment]
@syntrydy 

After playing with it for a bit more, I see you're right, it's possible. But the only way I can do it is by holding the Ctrl key why clicking at the script. If I just click it, it won't get unselected.

At least, we need to describe this behaviour in our docs, as it's not immediately obvious. But tbh would be more straightforward if an user would be able to unselect with just a left click as well. Is it doable?

**Comment by willow9886** [comment]
@aliaksander-samuseu @syntrydy perhaps checkbox selectors would simplify the UX?

**Comment by malotian** [comment]
I suggest to have button, name RESET

**Comment by syntrydy** [comment]
Okay, button Added. Personally I still don't know why such button is needed.
That widget is so simple and intuitive.
