### ISSUE TITLE
No status is displayed for new SAML TR until it's validated

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1838]
Package: gluu-server-4.0-82.rc1.centos7 (Backend: OpendDJ)

## Steps to reproduce the behavior:

1. Move to "SAML -> Trust Relationships" in web UI 
2. Click "Add Relationship", and submit a basic data required to create a stub "Single SP" TR
3. Click "Add" button, then move to "Trust Relationships" right away

## Expected behavior
"Validation Status" shows proper current status of the new TR, starting from "Validation is scheduled", then to "Validation", then to validation's result - as it was doing in 3.x and earlier packages.

## Actual behavior
"Validation Status" field is empty for a new TR until it will pass validation. This may confuse an user, and it wasn't like this previously:
![Selection_032](https://user-images.githubusercontent.com/11802046/65288242-c45ef400-db4e-11e9-87a7-944dd8e19ba9.jpg)

**Comment by syntrydy** [comment]
@aliaksander-samuseu this is fixed
