### ISSUE TITLE
Imported User From Excel unable to login to server. 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1842]
Imported User from excel unable to login to gluu server , several field were missing on user profile like city ,country , kudioroles (custom attribute) and password.

## Steps To Reproduce
1. Go to  Oxtrust
2. Click on  Users
3. Scroll down to Imported Users
4.  Upload the Excel 
5. Try to login with user credential also check user profile. 

## Expected behavior
Imported users must be able to login to gluu server , all the attribute must be shown on user profile

## Actual behavior
Imported users unable able to login to gluu server , all the attribute is  shown on user profile

## Excel file

[Gluu_Users_Add.xlsx](https://github.com/GluuFederation/oxTrust/files/3642422/Gluu_Users_Add.xlsx)

## Screenshots
![excel](https://user-images.githubusercontent.com/34593983/65431541-48f39000-de37-11e9-9761-f560db90074f.png)
![excel2](https://user-images.githubusercontent.com/34593983/65431542-48f39000-de37-11e9-9bf8-34dbdcec0722.png)
![authenticate](https://user-images.githubusercontent.com/34593983/65431543-498c2680-de37-11e9-8366-777662c9bcf9.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu 18
 - Gluu version 4.0

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/65609936-7ca1f780-dfa8-11e9-9d42-db8adce489b5.png)

**Comment by syntrydy** [comment]
You also have to configure Json user import  config section
![image](https://user-images.githubusercontent.com/7513418/65610139-cee31880-dfa8-11e9-8e37-94f74df2917e.png)
