### ISSUE TITLE
Gluu 4.0 QA: adding attributes to a new TR

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1844]
Gluu 4.0 RC 2. 

I'm adding attributes to a new TR, but they are not being displayed anywhere. Where should the attributes be displayed? I click the attribute, and the attribute seems to be selected, it is no longer available in the right column, but they are simply vanishing. 

![image](https://user-images.githubusercontent.com/5271048/65457105-acfa6200-ddff-11e9-9cc5-e488fea07d98.png)

**Comment by willow9886** [comment]
Once you select entity type = single SP are the selected attributes shown. This is not a good user experience. Are attributes not relevant to TR's with entity type = federation? If so, that needs to be more clear to the user.

**Comment by willow9886** [comment]
Suggested fix: 

Attributes should be displayed as they are selected, regardless of whether entity type has been chosen yet.

**Comment by mzico** [comment]
Agreed with @willow9886. Let's display released attributes regardless of Entity Type.
