### ISSUE TITLE
Registration: Redirected to old page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#185]
When I completed registration, I was re-directed to a page with the old look and feel. 

![image](https://cloud.githubusercontent.com/assets/3717101/12042476/120084e2-ae41-11e5-9711-65f6835db8e2.png)

**Comment by shekhar16** [comment]
HI William,
I couldn't find the registration link so that i can finish the registration and view successful registration page.So please share me registration link details.

**Comment by shekhar16** [comment]
HI All,
Somehow i found the url pattern for registration page.Here is the updated page with new template.

![image](https://cloud.githubusercontent.com/assets/15937500/12702898/07b8c6e6-c85b-11e5-875e-50ad49b5040f.png)
