### ISSUE TITLE
Some of extra attributes are not imported when importing users via oxTrust

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1858]
Environment: gluu-server-4.0-90.rc2.centos7

[Our docs on importing users](https://gluu.org/docs/ce/4.0/user-management/local-user-management/#import-people-in-oxtrust) read:
>Additional fields cn be defined for import by navigaing to Organization Configuration > JSON Configuration and selecting the tab for oxTrust Import Configuration

Yet this doesn't seem to work and some additional attributes are ignored, even if they are specified on "Configuration -> JSON Configuration -> oxTrust Import Configuration" page.

## Steps To Reproduce

1. Move to "Configuration -> JSON Configuration -> oxTrust Import Configuration" page and add 2 attributes to the list:
  - LDAP names: "o" and "gender";
  - display names: "Organization" and "Gender"
  - set both as not mandatory
2. Prepare an Excel file with a couple of test users which will contain columns for those 2 attributes as well; you can use the file attached [here](https://github.com/GluuFederation/oxTrust/files/3683715/Import_User_template_test.zip)
3. Move to "Users -> Import people" and import users from the file
4. Search for LDAP entries of the users, and confirm that all attributes were imported

## Expected behavior
All attributes are imported, including the extra ones added on step 1)

## Actual behavior
If the file attached used for import, "Organization" gets its value, but "Gender" doesn't, for some reason. I don't see any errors in `oxtrust.log`

**Comment by aliaksander-samuseu** [comment]
@syntrydy 

I'm also not sure what role field called "Display name" plays on "Configuration -> JSON Configuration -> oxTrust Import Configuration" page. It seems to me it's supposed to be name of the corresponding column in the Excel file, is it correct? In such case, name like "Display name" may be confusing, can we use something else may be, like "Excel file name" etc?

**Comment by davidgvh** [comment]
Was this fixed? I don't see any commits in the issue or in the repository.
