### ISSUE TITLE
Do we still need web UI representation of nameids?

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1862]
I see we still have option of adding "trainsientid" and "persistentid" attributes to "Released" list of SAML TRs in web UI. As we now fully handling nameid definition via a separate web UI control coupled with elements in `saml-nameid.xml` file, I wonder whether we still need those old representations? What purpose do they serve now? If they are just legacy elements, it's better to remove them, so they won't confuse an user.

**Comment by malotian** [comment]
Interesting, but I guess it's fine since those are part of available attributes, and what if somebody wanted those to be released as part of assertion as well.

This might be a hypothetical case but just wanted to share and list.
