### ISSUE TITLE
Copy client config summary as markdown outputs wrong default ACR

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1863]
Default ACR outputs `[Ljava.lang.String ... ` . Probably is calling java array toString

For example the client below:
![casa_client](https://user-images.githubusercontent.com/5444180/66930694-990ae000-effa-11e9-9ce7-7a6ef9f19342.png)

Outputs:
![client](https://user-images.githubusercontent.com/5444180/66930774-b8097200-effa-11e9-894f-757a3659552e.png)

**Comment by jgomer2001** [comment]
Environment:
Gluu 4 rc5 on debian 9 with couchbase backend

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/66935287-b27c4e00-f033-11e9-9e2c-30afad56c822.png)


Fixed
