### ISSUE TITLE
After updating username admin user should log out automatically

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1866]
Issue: https://support.gluu.org/identity-management/7628/after-changing-default-admin-uid-oxtrust-fails-if-user-does-not-log-out/#at53388

**Comment by willow9886** [comment]
This should apply to any user, not just `admin`, right?

**Comment by shekhar16** [comment]
Fixed : If user is going to update his own username or password then user will get logout automatically.
Here is the PR details. 
https://github.com/GluuFederation/oxTrust/pull/2146

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  issue is fixed, closing this ticket. Lease let us know if you found anything wrong.
