### ISSUE TITLE
Passing null value in SCIM payloads is clearing attributes

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1869]
Original and correct behavior is to leave attribute untouched.

This problem was introduced as a side effect of 4.0 refactoring.

More context of he problem [here](https://support.gluu.org/7640/#at53576)

**Comment by mzico** [comment]
Got report that it's still happening in 4.3.1. Reopening for QA...

**Comment by jgomer2001** [comment]
Need some evidence... let's be more specific too.

**Comment by jgomer2001** [comment]
Haven't witnessed a behavior like this
