### ISSUE TITLE
Deactivate "default acr" field in oxTrust OIDC client

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#1873]
In the OIDC client for oxTrust, we should deactivate the field that allows an admin to choose the "default acr". Screenshot below: 

![image](https://user-images.githubusercontent.com/5271048/68408228-d6661780-0139-11ea-9936-ae0cef1a63d9.png)

We should consider deactivating this field for the oxTrust client.. 

Already, this field is ignored for the oxTrust client, since the default acr for oxTrust is defined separately in the manage authentication feature, which is authoritative. 

![image](https://user-images.githubusercontent.com/5271048/68408422-2a70fc00-013a-11ea-87fc-16ead7d8100b.png)

**Comment by nynymike** [comment]
agreed
