### ISSUE TITLE
Wrong time in client form

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1877]
The time specified in oxTrust client form and stored in DB is different. The difference caused by timezone.

oxTrust should show same time in GUI which conforms to DB.

Steps to reproduce:
1. Enable client expiration in oxAuth JSON config (`dynamicRegistrationExpirationTime`).
2. Register new client with oxAuth-RP. Sample time is `20191127103914.154Z`
3. Try to open same client in oxTrust GUI.
4. Save client without changing expiration time. Result is `21191127000000.000Z`

**Comment by syntrydy** [comment]
The client expiration date by default in oxtrust is current time + one century

**Comment by yurem** [comment]
The question is not about default time. The issued caused by nxt time transformation `20191127111459.724Z` --> `21191127000000.000Z` after client open/save in oxTrust GUI
