### ISSUE TITLE
Remove old authentication methods

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#188]
During oxTrust development we changed authentication methods few times:
Basic->Shib->oxAuth...

Now in the code there are parts of Shib authentication method which expect attributes in header.
Also oxTrust still supports basic authentication method which introduce duplicity because oxAuth provides same functionlaity
And oxTrust supports oxAuth authentication method. But don't use discovery endpoint.

I think we need to remove last parts of Shib and baic authentication methods from oxTrust. And update oxAuth authentication to use oxAuth discovery endpoint. We already uses discovery endpoint in oxIdp and oxCAS.

**Comment by nynymike** [comment]
agreed

**Comment by yurem** [comment]
Fixed

**Comment by yurem** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/33a3e5af10e832b407a078208eeaaf6ac6267a7f
