### ISSUE TITLE
Enable/Disable OpenDJ mail uniqueness

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1880]
Opendj mail uniqueness can be enabled/disabled via ldap query. So, we can execute ldap query depending on what admin chooses for `enforceEmailUniqueness`

This is how we can do with Python:

```
import ldap
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW)


conn = ldap.initialize('ldaps://localhost:4444')
conn.simple_bind_s("cn=Directory Manager", "TopSecret")

#Disable mail uniqueness
conn.modify_s("cn=Unique mail address,cn=Plugins,cn=config", [( ldap.MOD_REPLACE, 'ds-cfg-enabled',  'false')])

#Enable mail uniqueness
conn.modify_s("cn=Unique mail address,cn=Plugins,cn=config", [( ldap.MOD_REPLACE, 'ds-cfg-enabled',  'true')])
```

**Comment by mbaser** [comment]
After implementing this we can remove this section from documentation:
https://gluu.org/docs/ce/user-management/user-registration/#opendj

**Comment by yurem** [comment]
We add this into organization configuration page

**Comment by syntrydy** [comment]
@mbaser do we have such feature for couchbase?

**Comment by mbaser** [comment]
No we don't have. uniqueness should be implemented in application level.

**Comment by yurem** [comment]
I've added update to oxCore to support this configuration update: https://github.com/GluuFederation/oxCore/issues/175
