### ISSUE TITLE
Make sure all changes are recorded in oxTrust audit log: Web / API

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#1881]
All changes to config changes from the Web UI or API's should be logged in the oxTrust audit log.  It would also be good if before saving any config changes, the admin was forced to put a comment. The authenticated user and client_id should also be recorded in the logs.

**Comment by shmorri** [comment]
Moved to the new UI project: https://github.com/GluuFederation/gluu-admin-ui/issues/123
