### ISSUE TITLE
Inaccurate description of scim field in attribute form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1882]
In attributes form the "Scim extended attribute" field has an associated description which is wrong.

If the field name is not self explanatory we can use as description "Whether this attribute is part of the SCIM user extension or not"

![scim_inaccurate_attrib_form](https://user-images.githubusercontent.com/5444180/69977946-abcd6b80-14f9-11ea-813e-99d726f65d89.png)

**Comment by willow9886** [comment]
What's this field actually do? It makes the attribute available via SCIM? The field title should be more self-explanatory.. 

If this feature does what I assumed above.. then let's change the field title to:

`Available via SCIM:`

**Comment by jgomer2001** [comment]
> What does this field actually do?

Signals whether this attribute is part of the SCIM user extension or not

**Comment by willow9886** [comment]
Ok, let's adjust the title to:

`Include in SCIM extension:`
