### ISSUE TITLE
Make inum field readonly while editing person

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1884]
## Describe the issue
Currently inum field is editable when you edit a person, this field should be readonly

## Steps To Reproduce
1. Go to "Users"
1. Click "Manage People"
1. Search a person
1. Click on "UID" to edit
1. Click "inum" field. This is editable.

## Expected behavior
inum field should be read only

## Actual behavior
inum field is editable

## Screenshots
![inum_edit](https://user-images.githubusercontent.com/6398752/70734103-abfd1080-1d1c-11ea-8f18-d71fa46f9cd9.gif)

## Desktop (please complete the following information):
 - OS: Debian 9
 - Gluu 4.0.1 (Beta)
 - Browser Chrome
 - Version 74.0.3729.108

**Comment by nynymike** [comment]
This is actually a bug in Community Edition--the default value for Edit Type for this attribute should be none.
