### ISSUE TITLE
Make username field readonly while editing person

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1885]
## Describe the issue
Currently username field is editable when you edit a person, this field should be readonly

## Steps To Reproduce
1. Go to "Users"
1. Click "Manage People"
1. Search a person
1. Click on "UID" to edit
1. Click "username" field. This is editable.

## Expected behavior
**username** field should be read only

## Actual behavior
**username** field is editable

## Screenshots
![username_edit](https://user-images.githubusercontent.com/6398752/70734534-74db2f00-1d1d-11ea-8489-02962ccfe562.gif)

## Desktop (please complete the following information):
 - OS: Debian 9
 - Gluu 4.0.1 (Beta)
 - Browser Chrome
 - Version 74.0.3729.108

**Comment by syntrydy** [comment]
@mbaser i think we can close this.  right?

**Comment by nynymike** [comment]
I disagree. Why is username not editable? An admin should absolutely be able to change the person's username.

**Comment by mbaser** [comment]
I username is editable now
