### ISSUE TITLE
Add `oxAttributes` JSON value support to Scopes (UI and API)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1889]
## Describe the issue
In 4.2 (master) there is JSON attribute added to scope object `oxAttributes to oxAuthCustomScope`. We must support it on UI. (Similar to already working `oxAttributes in oxAuthClient`). It should be supported also by API.

Sample LDIF
```
dn: inum=0a96137f-1a16-4bbe-82ed-3e54ee40beba,ou=scopes,o=gluu
objectClass: oxAuthCustomScope
objectClass: top
defaultScope: false
del: true
description: Spontaneous scope: transaction:245
displayName: transaction:245
exp: 20191218115405.718Z
inum: 0a96137f-1a16-4bbe-82ed-3e54ee40beba
oxAttributes: {"spontaneousClientId":"c8592b26-8984-484d-8aba-9f475be73af0",
 "spontaneousClientScopes":["^transaction:.+$"]}
oxId: transaction:245
oxScopeType: spontaneous
```

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83657781-38e0a280-a5b9-11ea-8bba-3ae0efbd54c6.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83658237-dcca4e00-a5b9-11ea-9d6d-121435d4f6fc.png)
