### ISSUE TITLE
Remove dependency to eduPerson

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#189]
Out of the box, we ship with eduperson, an objectclass used by universities. However, non-univeristy customers don't need this. We should probably not ship with eduperson, or include instructions on how to remove it.  Right now, when you remove eduPerson schema from OpenDJ, you cannot login to oxTrust.

**Comment by yurem** [comment]
It's not the 2.3.6/2.4.0 problem. We resolve it long time ago at 09/30/2014. Now oxAuth requires only:
@LdapObjectClass(values = { "top", "gluuPerson" })
