### ISSUE TITLE
Add spontaneous scope script to UI 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1890]
#  Describe the issue

We have to support new `SpontaneousScopeType` script type (see https://github.com/GluuFederation/oxCore/blob/b2f113a9867ab57f805d08e8064eee6ad2365c49/oxService/src/main/java/org/gluu/model/custom/script/type/spontaneous/SpontaneousScopeType.java#L5). It was added as part of "Spontaneous Scope" ticket https://github.com/GluuFederation/oxAuth/issues/839

Newly added script DNs should be saved here:
https://github.com/GluuFederation/oxAuth/blob/ffd8e659be921f8b9ba8eebf7b595ee514006fd2/persistence-model/src/main/java/org/oxauth/persistence/model/ClientAttributes.java#L37

In `oxAuthClient` attribute `oxAttribute` with `spontaneousScopeScriptDns` key in json.

Sample LDIF

```
dn: inum=c8592b26-8984-484d-8aba-9f475be73af0,ou=clients,o=gluu
objectClass: oxAuthClient
objectClass: oxAuthClientCustomAttributes
objectClass: top
del: true
displayName: Spontaneous scope test
inum: c8592b26-8984-484d-8aba-9f475be73af0
oxAttributes: {"tlsClientAuthSubjectDn":"","runIntrospectionScriptBeforeAcce
 ssTokenAsJwtCreationAndIncludeClaims":false,"keepClientAuthorizationAfterEx
 piration":false,"allowSpontaneousScopes":true,"spontaneousScopes":["^transa
 ction:.+$"],"spontaneousScopeScriptDns":["inum=031C-4A65,ou=scripts,o=gluu"]}
oxAuthAppType: web
...
```

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83049827-869e5d80-a043-11ea-8978-b6aaa646d0bc.png)

**Comment by yuriyz** [comment]
We can't expect that user will know script DNs. Lets add scripts via dialog as it's already done for "Post Authn" and "Consent Gathering" scripts. It's also DNs references in `oxAttributes`.

![image](https://user-images.githubusercontent.com/2013070/83050384-2f08ed80-a055-11ea-9c9e-c2b32ca24a0f.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83158708-05a39c80-a0fd-11ea-9b94-200e0358d59b.png)

**Comment by yuriyz** [comment]
@syntrydy nice

**Comment by syntrydy** [comment]
@yuriyz i saw this commit https://github.com/GluuFederation/oxTrust/commit/7e5fcb250c3851415b30feaf29d70f820b15319f.

I think that removing them properties.json is not a good option.
Because they will still show up under oxAttributes tab, maybe is better to keep them in properties.json but deactivated.

**Comment by yuriyz** [comment]
I put it back with https://github.com/GluuFederation/oxTrust/commit/326be93fb563bd838b0ba2a719f14148f48758e4

I found this ticket on their github https://github.com/jdorn/json-editor/issues/523

But somehow `"options": { "hidden": true }` doesn't hide field. I guess we should leave as is until we find solution how to hide field completely.

**Comment by syntrydy** [comment]
okay
