### ISSUE TITLE
Re-visit differences between single-SP and federation types of SAML TR

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1891]
We may need to re-visit differences between single-SP and federation types of SAML TRs. As Zico discovered, you can create a single-SP TR using federation metadata - which still will behave as federation TR anyway, allowing you to create child TRs based on it. That poses a question why do we need federation TR type, in the first place. What problem does it solve?

**Comment by nynymike** [comment]
I think it makes clear to the end user that we support federation metadata.
