### ISSUE TITLE
Name change: "Custom Attributes" to something else

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1893]
Better to call it .. ."Available Attributes" ? or something like that? 
Attributes which are here not always "custom" attributes. 
It's in Person Add Form. 
![Users_attribute](https://user-images.githubusercontent.com/7156097/71094499-b120ec00-2170-11ea-9460-b1bb20cab9ba.PNG)

**Comment by sahiliamsso** [comment]
Please change the same in profile page as well
![image](https://user-images.githubusercontent.com/21104811/71736513-4386e800-2e1f-11ea-954f-c5de3ca65715.png)

**Comment by nynymike** [comment]
Available "User Claims"
