### ISSUE TITLE
Multi value attribute's second value not showing in 'Profile' page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1894]
Multi value attribute ( i.e. in test case .. "Organization" attribute ) has two values created with oxTrust for one specific user. 

These values should be available in 'Personal' > 'Profile' page as well. But we see only first value of this multivalue attribute there 'Profile' page. 

Testing screencast is here: https://youtu.be/w78Bm8RkQvQ

**Comment by mzico** [comment]
@syntrydy : tested in autoqa server; most probably it's not working yet ( not sure about specific version of autoqa though ). 

Here is what I tried: 

 - Created a new user
- Made attribute 'organization' multi-valued
- Tried to insert two attributes for this attribute
- Logged into  autoqa as this new user in different browser, went to profile; "Organization" is showing single value ( first value ). 

Here is the screencast: https://youtu.be/9f5EBKASyXg

**Comment by mzico** [comment]
@syntrydy : I just tried to latest oxtrust war from repo. Here is what I am getting now: https://youtu.be/_NJe_A4fiXw

**Comment by syntrydy** [comment]
@mzico please war for the latest war to be built.

**Comment by yurem** [comment]
@mzico @syntrydy I've rebuilt new war

**Comment by mzico** [comment]
@yurem @syntrydy : It's working with oxtrust latest version: 

```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Build-Branch: origin/version_4.1.0
Implementation-Version: 4.1.0.Final
Archiver-Version: Plexus Archiver
Built-By: jetty
Implementation-Build: 52b946b55c43161f9baaeea36712af2e1074d756
Implementation-Vendor-Id: org.gluu
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_222
```
