### ISSUE TITLE
Use empty value for date instead of 'null' if blank in OpenID client form

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1901]
Till now, if we don't select any expiration date ( or, if we want to keep it null ), oxTrust tag one expiration date ( though very much usable long term date ). 

In this feature, request is: if user put 'null'.. just keep it null in expiration date; don't push / tag any date there from Gluu Server side.

**Comment by syntrydy** [comment]
@mzico it is not acceptable to have an entry in LDAP without expiration date. If the user doesn't want an expiration date for the client, he can let the field empty in that case the client will be removed after 24 hours. The expiration date isn't mandatory in the UI, but in LDAP each entry added by a user new expiration date.

**Comment by mzico** [comment]
@syntrydy : I tested latest oxTrust verion (**); seems like something is off: 

 - I had a client which didn't have any expiration date. Great! No entry in CB. 
 - I inserted some expiration date there. Great! Entry inserted in CB. 
 - I removed that entry from oxTrust but "oxAuthExpiration is still there in CB"; it's not removing. 

Screencast attached: https://youtu.be/ze8qeJuXMyg

**Comment by syntrydy** [comment]
@mzico it is now fixed.
