### ISSUE TITLE
Couchbase: store oxTrustEmail and oxTrustAddresses as JSON

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxTrust#1903]
In CB, attributes oxTrustEmail and oxTrustAddresses are json, so use the correct datatype to make them searchable.

**Comment by yuriyz** [comment]
Moved to oxTrust project.

**Comment by mbaser** [comment]
In Couchbase, we store json data as json, gluu stores **oxTrustEmail** as string. See sample user:
![Screenshot_2020-01-17_12-41-23](https://user-images.githubusercontent.com/6398752/72601649-e2830800-3926-11ea-89e8-87e56363d2f6.png)

Here **oxTrustEmail** can be stored as json, we need to store as follows:
![Screenshot_2020-01-17_12-45-21](https://user-images.githubusercontent.com/6398752/72601849-40afeb00-3927-11ea-93e1-4ec4f985ab83.png)

**Comment by nynymike** [comment]
oops, I thought this was oxAuth :-)

**Comment by yurem** [comment]
We discussed this issue during work on Couchbase persistence layer. The idea was to store attribute value as json sub-document to allow do search in SCIM. I think we can close this issue now and reopen if needed. I think so, because there are no questions about search in SCIM now.

Here is old digest when we discussed this issue first time:

>>> One question: While I was working on loading test data to couchbase, I noticed that oxTrustEmail and oxTrustAddresses are json type. But we are not treating them as json. Should I treat them as json?

>> It will be nice to store them as JSON But SCIM code expects it as string
```
        person.setAttribute("oxTrustPhoneValue", getComplexMultivaluedAsArray(res.getPhoneNumbers()));
        person.setAttribute("oxTrustImsValue", getComplexMultivaluedAsArray(res.getIms()));
        person.setAttribute("oxTrustPhotos", getComplexMultivaluedAsArray(res.getPhotos()));
        person.setAttribute("oxTrustAddresses", getComplexMultivaluedAsArray(res.getAddresses()));
...
```
This code converts String to JSON manually.
