### ISSUE TITLE
Ehanced management for redirect_uri lists

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1907]
As was pointed in in ticket 7874 by a customer, it may be a bit confusing for an user to manage redirect_uris separately on client's properties page and on sector identifier page.

From usability standpoint alone, if a Gluu-hosted sector identifier uri is created for some client, it should be linked to its data entry, and any redirect_uri added to the client should automatically be pushed to the sector identifier JSON object. On removal, the object should be checked and that `redirect_uri` removed from it.

**Comment by nynymike** [comment]
I don't understand this ticket.

**Comment by aliaksander-samuseu** [comment]
@nynymike 

It's about how sector identifier JSON objects hosted at oxAuth (internally) are handled from web UI. When you need to add a new uri, you have to add it 2 times: first to the corresponding sector identifier object, then to the client's list of redirect_uris. There may be a better way to handle it, from usability standpoint.
