### ISSUE TITLE
Add a notification to UI when new version is available

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#1909]
We should add a notification to oxTrust when a new CE version is available. Yuriy proposed the following approach (latest version).

This flow will check if there is new CE package. oxTrust should do next:
1. Run 2 times per day script `/opt/gluu/bin/check_new_version.py`.
2. Compare version specified in `/etc/gluu_version` with version in point 1.
3. Show notification on home page if new version is available.

This flow will check if admin should run upgrade script. oxTrust should do next:
1. Run 2 times per day commands: `/opt/gluu/bin/show_version.py -target=/opt/dist/gluu/ --json` and `/opt/gluu/bin/show_version.py`
2. Compare versions in both json.
3. Show notification on home page if admin should apply updates.

On organization configuration page admin should be able to disable this timer job

**Comment by adrian-gluu** [comment]
just add as @yurem suggested https://repo.gluu.org/oxtrust/printVersion.py

**Comment by yurem** [comment]
@adrian-gluu we need to store `printVersion.py` output in `https://repo.gluu.org/latest_version.json`

Also second part of this issue is for oxTrust. Hence we can close it once both parts wil be ready

**Comment by adrian-gluu** [comment]
https://repo.gluu.org/infoupdate/latest_version.json this output was extracted from the latest build from Ub18.04

**Comment by yurem** [comment]
@syntrydy New file is ready. It's persistence location. We can hardcode this url `https://repo.gluu.org/infoupdate/latest_version.json`

**Comment by mbaser** [comment]
This script checks repository for new version:
https://raw.githubusercontent.com/GluuFederation/community-edition-package/version_4.1.0/check_version/check_new_version.py

Do we need https://repo.gluu.org/infoupdate/latest_version.json ?

**Comment by syntrydy** [comment]
@yurem @mbaser @shmorri  @adrian-gluu The information you added on this ticket is conflicting and I can really proceed with unclear description.
