### ISSUE TITLE
Gluu 4.1 QA - No validation error message for Attribute creation with hybrid backend

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1916]
No validation error message for Attribute creation with hybrid back end, and **attribute creation is failing**

## Steps To Reproduce
1. Go to Configuration > Attributes > Register Attribute
2. Provide Attribute Name, and keep all other mandatory fields empty
3. Click on register

## Expected behavior
Error message should appear for mandatory fields

## Actual behavior
No error messages are seen

4. Now provide all mandatory fields and hit Register

## Expected behavior
Attribute should be registered

## Actual behavior
Error : The attribute type ‘Test’ not defined in LDAP schema

## Screenshots
![Attribute](https://user-images.githubusercontent.com/21104811/74750731-2f197600-523a-11ea-96dd-4dcadbcc4cae.gif)

 - OS: [e.g. Ubuntu16.04LTS] Centos 7.5
 - Gluu version(If applicable) 4.1 rc9 with hybrid db

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/74767096-80e7ed80-5286-11ea-88e2-d2d79176a52b.png)
