### ISSUE TITLE
User Confirmation URL broken on 3.1.7 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1919]
## Describe the issue
User confirmation email URL is broken , its prompt not found on 3.1.7

## Steps To Reproduce
1. Go to Register page
2. Register a user.
3.  You will receive the registration email.
4.  Click on confirm button , it will taken to broken url 

## Expected behaviour
A URL must taken to user confirmation page

## Actual behaviour
Error URL not found.

## Screenshots

![Screenshot from 2020-02-13 18-21-36](https://user-images.githubusercontent.com/34593983/74811602-d6200f80-5317-11ea-9e78-faed97c0c439.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 16.04LTS
 - Gluu version 3.1.7

**Comment by syntrydy** [comment]
@MohitMaliFtechiz I think i already show you how to fix this issue. Just update the corresponding script as mentioned.
