### ISSUE TITLE
Gluu 4.1 QA - Software Statement field under OIDC client is disabled by default

### ISSUE THREAD

**Issue by sahilIT2020** [GluuFederation/oxTrust#1921]
On creating OIDC client, software Statement field under Advanced Settings is disabled by default.

## Steps To Reproduce
1. Go to '.OpenID Connect  > Clients > Add Client
2. Click on 'Advanced Settings' Tab
3. Scroll down to bottom
4. Type something in 'Software Statement:' textbox

## Expected behavior
It should allow user to enter text
## Actual behavior
Textbox is disabled

## Screenshots
![image](https://user-images.githubusercontent.com/21104811/75047364-a0546580-5494-11ea-90d6-ea13115cefd7.png)

## Desktop (please complete the following information):
Gluu 4.1 rc10 package on Centos 7.4 with hybrid db

**Comment by syntrydy** [comment]
@sahiliamsso this is a ready only field if I can remember.

**Comment by yurem** [comment]
@sahiliamsso Can we close it?
