### ISSUE TITLE
SAML TR / "Attributes Published" column buggy

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1927]
In below screenshot and gif, there are two Trust relationships. 'SAMLID.Test' showing proper released attributes but 'samlapp' is not showing proper attribute ( only Username is released there ); instead it's just trying to mirror 'SamlID.Test' for some reason. 

![Capture](https://user-images.githubusercontent.com/7156097/76170655-ffcb9a00-6151-11ea-9dab-c30450f613e2.PNG)
![41oxTrustSAMLTR_page](https://user-images.githubusercontent.com/7156097/76170661-0823d500-6152-11ea-80bb-780e3ead1ca7.gif)

**Comment by mzico** [comment]
@syntrydy : I still see this issue in 4.1.1 ( latest oxturst, 17th April published ).

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/85397680-e0fbe280-b54b-11ea-8497-30cd32a5d0ce.png)

@mzico This is fixed
