### ISSUE TITLE
SAML metadata validation issue in all 4.x instances

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1928]
## Environment:

gluu-server-4.1.0-centos7 (confirmed both for WrenDS  and Couchbase, also confirmed for 4.0, and supposedly for 3.1.6 (according to Zico)).

## Description:

Any new SAML TR doesn't pass validation, and previously existing TR get broken if their metadata is updated. Somehow that doesn't prevent IDP from functioning (i.e. SAML flows for all affected TRs seem to work), but this potentially may have further implications on existing setups.

## Steps to reproduce:

1. Create a SAML TR for any SP (`samltest.id` will do)

2. Wait till validation will fail and open its properties page to see the detailed cause

## Result:

TR doesn't pass validation and error text like this is seen on its page:
```
src-resolve: Cannot resolve the name 'resolver:BasePrincipalConnectorType' to a(n) 'type definition' component.
Error of schema creating
Warning: cannot validate metadata. Check internet connetion ans www.w3.org availability.
Warning: Error of schema creating
Warning: src-resolve: Cannot resolve the name 'resolver:BasePrincipalConnectorType' to a(n) 'type definition' component.
```
Next Java error trace appears in `oxtrust.log`: [link](https://github.com/GluuFederation/oxTrust/files/4327325/oxtrust-md-issue-trace.txt)

**Comment by aliaksander-samuseu** [comment]
Please note we have [SAML metadata validation issue](https://github.com/GluuFederation/oxShibboleth/issues/68) atm which may affect you reproduction attempts

**Comment by yurem** [comment]
We need to try to load schema from `idp-schema-3.4.6.jar`. This is part of shib idp dist `shibboleth-identity-provider-3.4.6.zip:\shibboleth-identity-provider-3.4.6\webapp\WEB-INF\lib\idp-schema-3.4.6.jar`

**Comment by yurem** [comment]
It should work well in 4.1.1

**Comment by srin105** [comment]
> It should work well in 4.1.1
When will this version be available in the gluu repo? 
https://repo.gluu.org/

**Comment by yurem** [comment]
https://ox.gluu.org/maven/org/gluu/oxtrust-server/4.1.1.Final/oxtrust-server-4.1.1.Final.war

**Comment by tterrag1098** [comment]
How would I deploy this fix to gluu-server? It doesn't seem that 4.1.1 is in the apt repo, and I am not sure where to place the oxtrust-server WAR to install it manually, or if that is even possible.

**Comment by philzyk** [comment]
to tterrag109:
rename your identity.war in /opt/gluu-server/opt/gluu/jetty/identity/webapps to identity.war.bak
download https://ox.gluu.org/maven/org/gluu/oxtrust-server/4.1.1.Final/oxtrust-server-4.1.1.Final.war and rename it identity.war, then do service identity restart
error for schema will gone and Validation status should change to green Success

**Comment by stroemmma** [comment]
Hello
I put the identity.war , now the trust relationship is success
But my /idp/shibboleth metadata is gone , the service idp wont start with error :
2020-03-25 13:27:16.994:WARN:oejs.SecurityHandler:main: ServletContext@o.e.j.w.WebAppContext@1b68ddbd{Shibboleth Identity Provider,/idp,file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-7796412318786163483.dir/webapp/,STARTING}{/opt/gluu/jetty/idp/webapps/idp.war} has uncovered http methods for path: /*
2020-03-25 13:27:17.035:INFO:oejshC.idp:main: Initializing Spring root WebApplicationContext

It is because of identity.war ? I reboot the gluu server , same error
Thanks

**Comment by ryanmac8** [comment]
I can confirm, the metadata validation is broken. Replacing the war file breaks oxauth and now you can't even login.

**Comment by stroemmma** [comment]
No problem , i have old identity.war ... 
But with this , i walk into circles , no validation on trust relationships ...... so no shibboleth ...
Is a resolve for that ? or i must wait v 4.2 ?

**Comment by ryanmac8** [comment]
@stroemmma I was able to get it to work. Once you replace the war file, don't restart the Gluu container. Just run "service identity restart". Then try to validate your metadata. It should return successful. Once that happens, put the old war file back in place and restart the identity service again.

**Comment by stroemmma** [comment]
i give a try tomorow , thanks for assist me and quick response.

**Comment by stroemmma** [comment]
I can confirm that : after replacing with old identity.war , trust relationship ramain succesfull 
But after a server reboot , idp service is inactive/dead , need manual restart
And samltest.id now show 
Bad Request
Your browser sent a request that this server could not understand.
I think samethings is broken forever ....

**Comment by mzico** [comment]
Please open ticket in https://support.gluu.org. We used github to track issue only. 
I know it's fixed in 4.1. Here is quick glimpse: 

- Install 4.1 from official repo. It's published. 
- After installation completed, do next: 
  - Get the lastest identity war from here: https://ox.gluu.org/maven/org/gluu/oxtrust-server/4.1.1.Final/
  - Stop "identity" service by "service identity stop" 
  - Remove any "identity" related directory/ies if there is/are any in `/opt/jetty-9.4/temp/` location. 
  - Rename your downloaded artifacts as `identity.war`
  - Put that inside `/opt/gluu/jetty/identity/webapps/` 
  - Start identity service
- Go and create Trust relationship. 

For further assistance, open ticket in support portal please.

**Comment by stroemmma** [comment]
Thanks for your response, i open allready a ticket on support
I think is a issue , because on official repo with 4..1 is not included , and this is a workaround find on this github ( and broke somethings else .. )
But nevermind , you can close this ticket

**Comment by justinfiore** [comment]
@yurem is there a backport for this for `3.1.6` or `3.1.7`? as this is affecting this for us on these versions.

I doubt that dropping the `4.1.1` identity war into place on a `3.1.7` server is a good idea given all of the changes between Gluu 3x and 4.x

**Comment by shmorri** [comment]
We are preparing a 3.1.8 release, which is intended to be our final 3.x version. I see that this issue is included in its list of fixes.

**Comment by justinfiore** [comment]
That is great news @shmorri any idea when we can expect it to be released? (I know you are probably hard at work building, QAing, etc.

**Comment by shmorri** [comment]
If all the testing goes well, @justinfiore,  I would guess early next week. It's a pretty small release, so I'm optimistic!

**Comment by justinfiore** [comment]
Great. Thanks!

**Comment by stroemmma** [comment]
@shmorri  And for 4.1 ? we wait 4.2 ?

**Comment by shmorri** [comment]
@stroemmma  4.1.1 is scheduled for release next, after 3.1.8.

**Comment by stroemmma** [comment]
Thanks a lot !

**Comment by mzico** [comment]
For further assistance, open ticket / continue conversation in support.gluu.org ticket.
