### ISSUE TITLE
Ignore case sensitive search 'objectGUID' binary attribute in CR

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#193]
The binary attribute 'objectGUID' is case sensitive now for searching 'binaryAttributes=objectGUID'. If possible make it to lower case all string which we are going to compare in CR

**Comment by willow9886** [comment]
@mzico can you give an example in ldif?

**Comment by mzico** [comment]
@willow9886 : This is an enhancement of https://github.com/GluuFederation/oxAuth/issues/32
We can import binary attribute from backend with Cache Refresh. Using binary attribute among SAML is not very popular but it's a requirement for Microsoft based services like Office365, they ask IDP to release 'ObjectGUID' in exact binary form which is there in backend AD. 
We have a placeholder named 'objectGUID' inside LDAP which can pull and store this binary attribute from backend. In current setup, the name of this placeholder must be "objectGUID", if user tries to change it 'ObjectGUID' or 'objectGUid', it will not work. We can remove this restriction. 

Here is the existing code: 
      `public boolean isBinaryAttribute(String attributeName) {
                  return binaryAttributes.contains(attributeName);
          }`

**Comment by yurem** [comment]
FIxed
