### ISSUE TITLE
Cache Configuration title in oxtrust is called Memcached Configuration in 4.1

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxTrust#1931]
## Describe the issue

oxTrust tab title for `Configuration > JSON Configuration > Cache Provider Configuration` is `Configuration > JSON Configuration > Memcached Configuration` which is not right.

## Steps To Reproduce

1. Install Gluu 4.1

## Expected behavior

`Configuration > JSON Configuration > Cache Provider Configuration` 

## Actual behavior

`Configuration > JSON Configuration > Memcached Configuration` 

## Screenshots

![Untitled](https://user-images.githubusercontent.com/47318409/76878103-badaee00-684a-11ea-8d9f-54d6ee81f065.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/77075947-64f57a00-69f3-11ea-8bf3-dade37d2fd3d.png)
