### ISSUE TITLE
Replace SAMLS ACR aliases list with modal dialog in custom script form

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1932]
Current approach to specify SAML ACR aliases for Authentication methods cause many user issues. Here are typical issues:

1. It's not clear that admin should select them to enable aliases.
2.  Admin might don't know how to select 1 and 3 without 2.
3. Sometime admin select them accidentally.

We need to replace this list with `Select SAML ACRS` button and render list after user selection. This approach will be similar to all other dialogs in GUI, for example client form.

**Comment by syntrydy** [comment]
Fixed
