### ISSUE TITLE
Missing TR .xml file (on re-deploy/scale up)

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#1936]
## Describe the issue

On re-deploying or scaling up oxTrust pod/container, the generated TR file is missing, but the record is still in persistence.

## Steps To Reproduce

1. Deploy single oxTrust container/pod.
2. SAML TR is added via oxTrust UI.
3. New .xml metadata file created at `/opt/shibboleth-idp/metadata/abc-efg.xml`.
4. Destroy oxTrust container/pod.
5. Re-deploy (or scale up) oxTrust container/pod.
6. On newly created oxTrust container/pod, there's no `/opt/shibboleth-idp/metadata/abc-efg.xml`, but TR is persisted in persistence and shown in oxTrust UI (being inactive).
7. Need to re-upload SAML file to re-generate metadata

## Expected behavior

SAML metadata file is re-generated upon startup if TR is in persistence but not in filesystem.

## Actual behavior

SAML metadata file is missing in filesystem but the record is saved in persistence, marked as being inactive.

## Additional context

docker and k8s deployment.

**Comment by yurem** [comment]
The main problem that we need to store File SP somewhere. LDAP is not good for this. Because even InCommon metadata in arhive has size 14Mb

**Comment by iromli** [comment]
Moving to JCA as DocumentStore fixed the issue.
