### ISSUE TITLE
oxTrust : we need ability to set "logout_uri" and "logout_session_required" for client

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#194]
Right now it is not possible to set "logout_uri" and "logout_session_required" for client.

Both these options comes from Http-based logout specification:
http://openid.net/specs/openid-connect-logout-1_0.html

**Comment by willow9886** [comment]
@yuriyz who should we assign this to?

**Comment by yuriyz** [comment]
Reopened, since we get request to add multiple logout_uri's per one client. oxauth issue is created https://github.com/GluuFederation/oxAuth/issues/153

Scheduled this for next release.

**Comment by yuriyz** [comment]
@qbert2k I've added support on oxauth. So you can add it on oxTrust.

**Comment by shekhar16** [comment]
Fixed on add client page and update client page as well.

**Comment by zamilskhan** [comment]
Closing issue as it is implemented
