### ISSUE TITLE
Gluu 3.1.8 QA - Redirect uri's are throwing error that "A Sector Identified must be added first"

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1942]
Redirect uri's are throwing error that "A Sector Identified must be added first"

## Steps To Reproduce
Create a new client and try to add 'http://oidc-js.site:5000/user-manager-sample-silent.html' as redirect URI

## Expected behavior
It should allow to add URI

## Actual behavior
Throws error - "A Sector Identified must be added first"

**PS: This is happening for URLs with more than two . (dots) in it.**

![image](https://user-images.githubusercontent.com/21104811/79016203-5d317d00-7b3c-11ea-9c60-78fe7684d1c2.png)

Gluu 3.1.8 on centos 7.5

**Comment by syntrydy** [comment]
@sahiliamsso this is not an issue, the problem here is the scheme you are using.

HTTP is insecure, for redirect Uri, always use **https**.

Closing it for now.

**Comment by aliaksander-samuseu** [comment]
Yes, apparently there was a confusion when we first discovered it. I'll open a new ticket, with corrected description.
