### ISSUE TITLE
externalize Shibboleth IDP templates

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#1944]
Shibboleth XML velocity templates should be stored outside the war. Currenlty, you have to do this:

```
- Get identity.war
- Extract it
- Go to WEB-INF/lib/ location
- You will get another jar named oxtrust-configuration-4.0.Final.jar
- Extract this jar and you will get those VM files.
- if you modify these velocity templates and put them inside /opt/gluu/jetty/identity/conf/shibboleth3/idp/ ( as ‘vm’ file )
```
Ideally, these templates should be stored in the database.

**Comment by malotian** [comment]
@nynymike 
Earlier it was like external only, 
This was done, so that users don't touch this accidently
Only advance users shall be performing updates, and if they need to, they shall be doing this explict step.
Please reconsider.

**Comment by malotian** [comment]
Or I will suggest something like 
`java -cp identity.war com.gluu.ExtractTemplates -extractTo /opt/gluu/jetty/identity/conf/shibboleth3/idp/`

basically suggesting creating a Utility class - com.gluu.ExtractTemplates, and document it how to Use.

**Comment by nynymike** [comment]
Closing as we are in the middle of a shib refactoring anyway.
