### ISSUE TITLE
Gluu 4.1.1 QA - Username and password labels are not showing up on Login screen

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1952]
Username and password labels are not showing up on Login screen

## Steps To Reproduce
1. Install Gluu and open login page

![image](https://user-images.githubusercontent.com/21104811/80515533-1cb16c00-8950-11ea-94ca-60c9738c43f9.png)

Also, {url}/oxauth/stylesheet/bootstrap.min.css.map is returning 404
![image](https://user-images.githubusercontent.com/21104811/80515498-115e4080-8950-11ea-9f01-feaf7c6461f9.png)

Gluu 4.1.1 on CentOS7x

**Comment by syntrydy** [comment]
@sahiliamsso Fixed
