### ISSUE TITLE
CIBA configuration UI

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#1958]
1. Update oxAuth Configuration UI for CIBA fields. **DONE**

2. Update Client UI. Add UI fields to edit the following _oxAuthClient_ attributes:

```oxAuthBackchannelTokenDeliveryMode``` (poll, ping, push)
```oxAuthBackchannelClientNotificationEndpoint``` (string)
```oxAuthBackchannelAuthenticationRequestSigningAlg``` (RS256, RS384, RS512, ES256, ES384, ES512, PS256, PS384, PS512)
```oxAuthBackchannelUserCodeParameter``` (true, false)

3. Update Person UI. Add UI fields to edit the following _gluuPerson_ attributes:

```oxAuthBackchannelDeviceRegistrationToken``` (string)
```oxAuthBackchannelUserCode``` (string)

See https://github.com/GluuFederation/oxAuth/issues/750

**Comment by miltonbo** [comment]
I added those attributes to the client entity in oxTrust. About person entity, the UI is generated automatically, therefore I only added those new attributes in `community-edition-setup` repository.

**Comment by miltonbo** [comment]
There is also a PR related to this issue in the `community-edition-setup`: https://github.com/GluuFederation/community-edition-setup/pull/670
