### ISSUE TITLE
Login Page blank value error message is not user friendly.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#1966]
## Describe the issue
Currently if you try to login with blank username and password its showed you "loginForm:j_idt15: Validation Error: Value is required" which customers are complaining is not user friendly.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to login page
2. blank username or password
3. try to login

## Expected behavior
We can give provide more user friendly message "username or password is missing".

## Actual behavior
"loginForm:j_idt15: Validation Error: Value is required" this message is shown.

## Screenshots
![Screenshot from 2020-05-22 21-09-34](https://user-images.githubusercontent.com/34593983/82684661-9b0fde00-9c70-11ea-9165-22b2515ef851.png)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu16.04LTS]
 - Gluu version 4.1

**Comment by syntrydy** [comment]
@MohitMaliFtechiz this is not oxtrust issue

**Comment by MohitMaliFtechiz** [comment]
I created the same as oxAuth issue.
