### ISSUE TITLE
Use JSON Property to allow extra attributes for person status

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#1967]
Currently, there are only two hard coded values for status:

![image](https://user-images.githubusercontent.com/3717101/83188083-c709e400-a0f4-11ea-9e8e-8a126b500173.png)

[UpdatePersonAction](https://github.com/GluuFederation/oxTrust/blob/0c76d9504eb19a95e1a042bf20fec09e2ee74caf/server/src/main/java/org/gluu/oxtrust/action/UpdatePersonAction.java#L863)

```
public GluuStatus[] getActiveInactiveStatuses() {
		return new GluuStatus[] { GluuStatus.ACTIVE, GluuStatus.INACTIVE };
	}
```
Customers may have their own status values. It would be helpful if we define a JSON property that enables the customer to add extra values for status.

**Comment by syntrydy** [comment]
@nynymike what is the advantage of having in oxtrust JSON properties?
 I personally think that using the json here is not a good option. 
Currently, the user Status is a subpart of a java enum named GluuStatus.

**Comment by nynymike** [comment]
We have a customer who needs to add status "pending". Hard coding the values is inflexible.

**Comment by nynymike** [comment]
One question is what is the active value if the customer uses different languages? What about making "active" the first value in the list. For example for `["bird", "tree", "fish"]` ... `bird` would signify active.

**Comment by yurem** [comment]
I offer to add new property to specify extended status instead of adding more values to `gluuStatus`

We use `gluuStatus` not only in user entry. We also use it in Groups, TR, etc.. As result adding more values and make it customizable can led to breakdown in other parts.

**Comment by yurem** [comment]
Alternative idea is to replace `gluuStatus` with `oxEnabled` in all places where our code expects to get only predefined values.
After that customers can use `gluuStatus`with any values.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83697653-795f1100-a5f7-11ea-858c-9fc00f7b6adf.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/83697866-f1c5d200-a5f7-11ea-88c0-de877dd83fc9.png)
