### ISSUE TITLE
oxTrust should detect ainstalled modules at runtime

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#197]
There are modules oxIdp and oxAsimba which admin can skip during install.

At startup oxTrust should detect if there are war files which belong to this modules (or any other conditions) and disable actions/menu.form which belong to not enabled modules.

It's easy to use JBoss Drolls to implement this. We uses it in this project already. On user login we can assign right roles and add methods to check if user has specific role or permission. Example:

@Restrict("#{s:hasPermission('idp', 'access')}") in java
<restrict>#{s:hasPermission('idp', 'access')}</restrict> in page.xml

And definition in security.drl
rule AccessIdp
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(target == "attribute", action == "access", granted == false)
  Role((name == "idp"))
then
  check.grant();
end

**Comment by yurem** [comment]
@willow9886

**Comment by iromli** [comment]
For consideration, in Enterprise Edition, oxIdp/oxAsimba are not installed in same environment (container) with oxTrust, hence I'm afraid actions/forms for oxIdp/oxAsimba will always be disabled if we choose to detect by module existence.

**Comment by yurem** [comment]
We can detect installed modules on single machine in CE.
But in cluster this solution will not work.
I think we need to add custom attribute like oxComponents: {'idp' : {"status' : false}, .... } to appliance entry.

oxTrust can read it and build menu according to requirements.

**Comment by dmogn** [comment]
I added some functionality, which related to the issue:
https://github.com/GluuFederation/oxTrust/issues/216

**Comment by yurem** [comment]
I think #216 is enough at this point
