### ISSUE TITLE
Smtp mail configuration not working after migration to Java 11

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1972]
## Describe the issue
Smtp configuration not working since the migration to Java 11.
Hence all features from which we send mails are broken.

## Steps to replicate
Setup the smtp properties and click the test button

![image](https://user-images.githubusercontent.com/7513418/84385112-ede11380-abe6-11ea-802e-c71c190afa77.png)

**Comment by yurem** [comment]
Fixed in oxAuth/oxTrust
