### ISSUE TITLE
Javascript errors prevent enabling custom scripts

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1977]
In latest available 4.2 beta build it is not possible to click on any of the tabs (except for the first) in "Other custom scripts" page

Additionally in "Person authn scripts" after hitting update there is no confirmation message (the page remains static) despite the changes do take effect.

![custscripts](https://user-images.githubusercontent.com/5444180/84815227-590c5a80-afd8-11ea-84f3-3b3e99eeed8d.png)

**Comment by uprightech** [comment]
Issue fixed.
