### ISSUE TITLE
Missing popup when clicking SP Metadata File link 

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#1985]
## Describe the issue

Popup doesn't appear when clicking SP Metadata File link.

## Steps To Reproduce

1. Add new TrustRelationship (TR) using metadata file (`.xml`) and submit
1. Wait until validation finished
1. View the newly created TR at `/identity/trustmanager/updateTrustRelationship.htm`
1. Click the SP Metadata File link

## Expected behavior

Popup appears (similar to v4.1); see screenshot below:

![Screenshot from 2020-06-25 02-14-09](https://user-images.githubusercontent.com/231601/85620453-0264e780-b68e-11ea-8dd7-09620310a688.png)

## Actual behavior

Popup doesn't appear; see screenshot below:

![Screenshot from 2020-06-25 02-39-27](https://user-images.githubusercontent.com/231601/85620519-19a3d500-b68e-11ea-8518-3856c8254d65.png)

## Desktop (please complete the following information):

1. oxTrust v4.2.0-SNAPSHOT

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/85720280-30771580-b6e8-11ea-9993-16a6da8ea0f2.png)

**Comment by syntrydy** [comment]
@iromli Are you using latest oxtrust war?

**Comment by iromli** [comment]
@syntrydy tested on oxTrust v4.2.0-SNAPSHOT build at 2020-06-25 12:15.

Surprisingly, if DocumentStore is set to `LOCAL`, the popup appears. If set to `JCA`, the issue persists.

**Comment by syntrydy** [comment]
@iromli Where do you change the value of **DocumentStore** on the UI?

**Comment by iromli** [comment]
@syntrydy It's in Configuration > JSON Configuration > Store Provider Configuration

**Comment by nynymike** [comment]
@MohitMaliFtechiz can you verify if this is repeatable in the VM distribution.

**Comment by MohitMaliFtechiz** [comment]
Hi @nynymike @syntrydy ,

On default installation without changing any configuration value the popup work fine. Now i am testing it by changing config to JCA as described by @iromli .

Thanks and Regards
Mohit Mali

**Comment by MohitMaliFtechiz** [comment]
i have test it againist JCA also its worked fine.
