### ISSUE TITLE
Gluu 4.1.1 and 4.2: getting same Pairwise ID ( first generated one ) for rest of the users 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1987]
In Gluu Server 4.1 and 4.2 whose data source is CB: creating users with oxTrust feature is working fine for first users. After that, whichever user we are creating it's getting first Pairwise Id ( which was generated for first user ) for all users. 

How to reproduce video is available here: https://www.youtube.com/watch?v=GJNoQ8grPfE&feature=youtu.be

**Comment by yurem** [comment]
Fixed
