### ISSUE TITLE
Gluu 4.2 QA | No option to delete Redirect URI, Grant Type and Redirect Logout URIs

### ISSUE THREAD

**Issue by sahilarora2020** [GluuFederation/oxTrust#1989]
## Describe the issue
Gluu 4.2 QA | No option to delete Redirect URI, Grant Type and Redirect Logout URIs

## Steps To Reproduce
1. Go to OpenID Connect > CLients 
2. View any existing client or create a new
3. Try to remove existing Redirect URI/Grant Type

## Expected behavior
Should see 'x' for these entries

## Actual behavior
No option available
 
![image](https://user-images.githubusercontent.com/21104811/86058219-891f1900-ba2e-11ea-8b26-5438d0e05b90.png)

version
Title: oxAuth Server
Version: 4.2.0-SNAPSHOT
Builddate: Fri Jun 26 19:52:35 UTC 2020
Build: d60f5a301e5b25e998533e4ba95a75165b472902

Title: Fido2 API Server
Version: 4.2.0-SNAPSHOT
Builddate: Fri Jun 26 19:53:48 UTC 2020
Build: 198f50f85103b2e93218e74a36cf659aa1a9ba90

Title: oxTrust Server
Version: 4.2.0-SNAPSHOT
Builddate: Fri Jun 26 19:55:09 UTC 2020
Build: 0a58a312707247ab83b2eae1b577502d26c17c2f

Title: SCIM API Server
Version: 4.2.0-SNAPSHOT
Builddate: Fri Jun 26 19:58:18 UTC 2020
Build: 30415dce9768d5ea5559c08996c4e7e3c433a52b

Title: Gluu Shibboleth IDP
Version: 4.2.0-SNAPSHOT
Builddate:
Build: d48e6fe04d6cace9900c84310168c2eaf5b91432

Title: oxAuth RP
Version: 4.2.0-SNAPSHOT
Builddate: Mon Jun 29 12:49:39 UTC 2020
Build:

Title: casa
Version: 4.2.0-SNAPSHOT
Builddate: Fri Jun 26 20:00:14 UTC 2020
Build: e3b83a2c57a35e0375768eabdef181346d34aca9

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/86132341-a90e1580-bade-11ea-8a39-cb7afa78658a.png)
