### ISSUE TITLE
GLuu 4.2 QA | Random text in Sector Identifier Description field

### ISSUE THREAD

**Issue by sahilarora2020** [GluuFederation/oxTrust#1990]
GLuu 4.2 QA | Random text in Sector Identifier Description field

## Steps To Reproduce
1. Go to 'OpenID Connect > Sector Identifier > Add Sector Identifier'

## Expected behavior
Description should be 'Default description'

## Actual behavior

Default description xxxxxx

![image](https://user-images.githubusercontent.com/21104811/86058461-f0d56400-ba2e-11ea-9553-e193508fe3a5.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/86118679-1616b080-bac9-11ea-9399-b0f68a5c0591.png)
