### ISSUE TITLE
identity crashing frequently

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1999]
![42error](https://user-images.githubusercontent.com/7156097/87230212-0a05db00-c374-11ea-90c0-4b609c7b7756.gif)

oxTrust version: 

```
[root@localhost certs]# cat /opt/jetty-9.4/temp/jetty-localhost-8082-identity_war-_identity-any-2138693855297178574.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Build-Branch: origin/master
Implementation-Version: 4.2.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: jetty
Implementation-Build: 8b7b5fdb15dd374fd5cc2425cb1043e4da0cef5c
Implementation-Vendor-Id: org.gluu
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_222
```

**Comment by syntrydy** [comment]
@mzico this is a misterious bug, we are still traking that bug.

**Comment by mzico** [comment]
@syntrydy : I guess it's mostly happening for memory issue. TRACE level log spitting some when we get this error. 
Screenshot attached. 
![identity_issue](https://user-images.githubusercontent.com/7156097/87413732-4f9eef80-c590-11ea-81e7-1f67d5dfbe74.PNG)

**Comment by syntrydy** [comment]
@mzico can you do this. Edit **/etc/default/identity** and change **MaxMetaspaceSize=128m** to **MaxMetaspaceSize=3200m**

**Comment by syntrydy** [comment]
@mzico i'm closing this issue, increasing the mespace fix it.
