### ISSUE TITLE
 Not able to import User from excel file.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2000]
## Describe the issue
Not able to import User from excel file.

## Steps To Reproduce
1. login to gluu server.
2. go to Users.
3. go to Import People.
4. try to import user Excel file 

## Expected behavior
User must be imported

## Actual behavior
not able to import User  and identity throws error. 

``` ERROR [qtp956420404-14] [org.gluu.util.properties.FileConfiguration] (FileConfiguration.java:81) - Failed to load ‘/etc/gluu/conf//gluuImportPerson.properties’ configuration file from resources ```
 

## Desktop (please complete the following information):
 Gluu-version (4.2)

OS Ubutnu 18.04, Centos 7

**Comment by syntrydy** [comment]
@MohitMaliFtechiz closing this.

To fix it  you can just do this:
- Edit /etc/default/identity
- Change Mespace from 128 to 320m
- Restart identity
