### ISSUE TITLE
 Password reset functionality failed to reset password when Secret question and Secret Answer are active. 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2001]
## Describe the issue
 Password reset functionality failed to reset password when Secret question and Secret Answer are active. 

## Steps To Reproduce
1. Register a new user with Secret Question and Secret Answer Attribute enable.
2. After successfull registration,  Go to login page and try to change user password by forgot password.
3. Provide all details. 
4. Try to reset password on password reset link.
5. After Enter new/confirm password with secret answer on reset page , new reset password page appears while submit this page  Oops error Occured. 

## Expected behavior
there must be one reset page with secret question and then password should be reseted. 

## Actual behavior
Goes to another password reset page and later failed to reset password (Oops error).

## Screenshots
![reset1](https://user-images.githubusercontent.com/34593983/87755396-8db44180-c824-11ea-9ec1-630162689012.png)
![reset2](https://user-images.githubusercontent.com/34593983/87755401-90169b80-c824-11ea-804f-e1f0b3a823ff.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 18
 - Gluu version 4.2

**Comment by syntrydy** [comment]
@MohitMaliFtechiz please always provide logs

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/87875570-0c96af00-c9ca-11ea-94b0-da9bf3db6027.png)

**Comment by thuythuy9171** [comment]
lenhung9171@gmail.com 

>
