### ISSUE TITLE
Not able to delete `Claims redirect uri` for any client

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxTrust#2002]
## Describe the issue
On oxtrust UI I am not able to delete the added on `Claims redirect uri` for any client.

## Steps To Reproduce
1. Login to oxtrust
2. Click on OpenID Connect from left menu. Then click on Clients.
3. Open any client listed on the screen.
4.  Go to `Advance Settings tab`
5. Add `Claims redirect uri` 

## Expected behavior
Users should be able to remove the added `Claims redirect uri`.

## Actual behavior
1. There is no way to delete the added `Claims redirect uri` from the list.
2. This field allows adding only https:// in the list (which is not correct Uri)

## Screenshots

![image](https://user-images.githubusercontent.com/32794267/87900491-212e8200-ca72-11ea-8069-6e643a8afc1e.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/87937506-c6eeea80-ca8c-11ea-911c-0fdf5ce8be09.png)
Fixed
