### ISSUE TITLE
Two 'save' buttons in json configuration ?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#2003]
Using a general Save button in addition to a specific Save button for every tab  is kind of redundant

![Screenshot from 2020-07-22 14-39-09](https://user-images.githubusercontent.com/5444180/88221544-41a13c80-cc2a-11ea-8302-61bd1f055d0a.png)

Users may think they have to press (the right one) to save the specific tab values, and then use the other (left) to apply changes.  I think this brings a usability problem

Also it doesn't look good, they are misaligned and have no space in-between

I vote for removing one or the other

**Comment by syntrydy** [comment]
@jgomer2001 both buttons are usefull. One of the button is coming from json editor and is usefull.
I just align both buttons

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/88429900-64308280-cdef-11ea-8568-0ae888dc3f06.png)
