### ISSUE TITLE
Bump jython version

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#2009]
Oxtrust 4.2 and 4.2.1-snapshot wars have the file `WEB-INF/lib/jython-standalone-2.7.1.jar`. 

It is known to contain security vulnerabilities, see https://bugs.jython.org/issue2762

Please update the dependency to a more recent version, eg. 2.7.2

**Comment by syntrydy** [comment]
Fix both in 4.2.1 and master. 
Reference 37eeef83d2b147ce0afa3f7200b4e77b04536b9c
