### ISSUE TITLE
Remove minimum character requirement from sector uri client search form

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#201]
On the https://<host>/identity/sectoridentifier/manage/add

Hitting search is ok, but should be limited to 20 results. 

![image](https://cloud.githubusercontent.com/assets/3717101/13091106/2c1ce024-d4bf-11e5-92c4-f97d013a5dbe.png)

**Comment by shekhar16** [comment]
Fixed : Removed no of character validations and set limit of display search client result.

**Comment by yurem** [comment]
I think according to issue description we should keep input validation: 2-30 characters. But limit result set to 20 results.
>> Hitting search is ok, but should be limited to 20 results. 

Also I think you can remove lines 264-266:
https://github.com/GluuFederation/oxTrust/commit/6218bc888fd3fba884faba170386e6164ff118a0#diff-63759ce348cbb0a769fa7c3fcc2152abR264

Method uses searchClients(String pattern, int sizeLimit) second param wich tell LDAP to return max number of results.

**Comment by shekhar16** [comment]
Yes Yuriy ,I already tried do this issue with this approach but the display list is not restricted to expected limit, After that i fixed issue with different approach.(which is currently committed in repo.).
I reviewed that searchclient method and it was returning expected limited result but after that in do-while it will increase the result size and exceed the limit.And finally on display the list exceed the size limit.

**Comment by shekhar16** [comment]
As per issue heading "Remove minimum character requirement from sector uri client search form"
I removed the character validation.

**Comment by yurem** [comment]
If LDAP API not working fine we need to open issue to find out core of the issue.
LdapEntryManager.findEntries(String baseDN, Class<T> entryClass, Filter filter, int sizeLimit)
Should return maximum specified number of entries if sizeLimit > 0

**Comment by yurem** [comment]
Regarding subject of this issue. I think we need to remove only minimum characters validation. Maxim validation should works as before.

@nynymike Can you clarify requirements

**Comment by yurem** [comment]
@shekhar16 I understand what you wrote about LdapEntryManager.findEntries with sizeLimit

In oxLdap name of the parameter not conform to actual action..

I updated oxLdap. I renamed:
sizeLimit -> searchLimit

And added:
sizeLimit parameter to allow specify how many entries LDAP should return. Now when we do search we do next:
<code>
searchRequest.setSizeLimit(sizeLimit);
</code>

These are new changes:
https://github.com/GluuFederation/oxCore/commit/e8ebc63f9461efc86d14994e26b39e2ad7a7e5f6#diff-794d10d8e9dc72141ca737ff12142343R213

**Comment by yurem** [comment]
@shekhar16  can you try to use new method:
findEntries(String baseDN, Class<T> entryClass, Filter filter, int searchLimit, int sizeLimit)

searchLimit = 0 to not use pagination during search

**Comment by yurem** [comment]
I offer to close it.

I updated validation: https://github.com/GluuFederation/oxTrust/commit/a1ef4362740cc21a662eb11c97fdbf4d0ca6334f

And now we uses LDAP to limit search limit
