### ISSUE TITLE
Using Components with Known Vulnerabilities: Outdated jQuery Library Version

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2010]
One of our customer has done vulnerability assessment and penetration testing and they have flagged out the following finding

a) WAPT-4) Using Components with Known Vulnerabilities: Outdated jQuery Library Version.

## Describe the issue
Outdated jQuery Library Version is outdated in OxTrust , is it possible for us to load up the latest jQuery library into Gluu Server ?

roblem.

## Desktop (please complete the following information):
 - OS: rhel 7.7
 - Gluu version 4.0

**Comment by MohitMaliFtechiz** [comment]
To add-on to WAPT-4, there are additional libraries flagged out

Bootstrap 3.3.2, 4.0.0
Vue 2.5.16

**Comment by MohitMaliFtechiz** [comment]
Please check the pdf finding for more detail
[protected_answer_8595_WAPT-4-AdditionalLibraries.pdf](https://github.com/GluuFederation/oxTrust/files/5033252/protected_answer_8595_WAPT-4-AdditionalLibraries.pdf)

**Comment by yurem** [comment]
We can't update JS jQuery due to RichFaces dependecy
