### ISSUE TITLE
Sector Identifier description

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2011]
Possible to add a description field on the sector identifier objects that are registered directly in gluu? This would be a field filled out by the gluu admin during SID creation. It would be useful for us to be able to write our own descriptions so we can easily identify the who/what/whys of any particular sector identifier object.

Ref. ticket: https://support.gluu.org/feature-request/8657/description-details-field-on-sector-identifiers/

**Comment by syntrydy** [comment]
@mzico we have that field already
![image](https://user-images.githubusercontent.com/7513418/90516502-ffe9b000-e15b-11ea-86bb-72c0216a4300.png)

**Comment by syntrydy** [comment]
@mzico that field is already there, also in previous version. Feel free to close this issue.

**Comment by mzico** [comment]
Thanks
