### ISSUE TITLE
Injection: Cross-Site Scripting

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2012]
## Describe
One of our customer has done vulnerability assessment and penetration testing and they have flagged out the following finding

a) WAPT-1) Injection: Cross-Site Scripting

-->  Based on the VAPT findings, this is found in the Manage People section

Detailed VPAT finding is attached please have a look.
[protected_answer_8595_WAPT-1-Functions (1).pdf](https://github.com/GluuFederation/oxTrust/files/5033230/protected_answer_8595_WAPT-1-Functions.1.pdf)

## Desktop (please complete the following information):
 - OS: rhel 7.7
 - Gluu version 4.0

**Comment by syntrydy** [comment]
@MohitMaliFtechiz it is not possible to inject data input field unless the user is admin.
Also  JSF already  escape input data by default to prevent against XSS.

Can you ask that customer to provide the steps to replicate?

**Comment by yurem** [comment]
Fixed
