### ISSUE TITLE
Change label / values for Scope visibility 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2015]
On the OpenID scopes management page...

![image](https://user-images.githubusercontent.com/3717101/89923541-5e47e900-dbc6-11ea-9394-94810325e348.png)

This is very confusing... it should say "Show in configuration endpoint", with the booleans reversed from the current.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/90508246-44228380-e14f-11ea-98ca-ac67929e6fc3.png)

**Comment by syntrydy** [comment]
oxauth is also update accordingly
