### ISSUE TITLE
oxTrust should not rely on configuration endpoint for scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2016]
Customer reports:

```
After going into OIDC > Scopes and updating all to be hidden from Discovery except openid, I can't 
login in Admin UI anymore. I get error "Login failed, oxTrust wasn't allowed to access user data"
```

This should not be the case. oxTrust knows the scopes it needs, and whether or not they are included in the OpenID configuration response, it should be fine.

**Comment by yurem** [comment]
Default oxTrust config has:
```
"oxAuthClientScope":"openid+profile+email+user_name",
```

We can change it to:
```
"oxAuthClientScope":"openid+user_name",
```

@nynymike Can explain this:
```
This should not be the case. oxTrust knows the scopes it needs, and whether or not they are included in the OpenID configuration response, it should be fine.
```

oxTrust uses user_name` clains during login.

**Comment by syntrydy** [comment]
These(**openid+profile+email+user_name**) are the scopes oxtrust send to oxauth during the initial code flow.
OxTrust don't rely on configuration endpoint to handle the scopes. Changing the discoverability of oxtrust scopes(**openid+profile+email+user_name**) doesn't affect the login/authn process.

**Comment by syntrydy** [comment]
@nynymike oxtrust does not use the configuration endpoint to verify the presence of the scopes it used.

**Comment by yurem** [comment]
I think we can close this issue. I've specified "Show in configuration endpoint" = false for all scopes requires for oxTrust. Login works well after that.
![image](https://user-images.githubusercontent.com/6104200/91583402-da2d8980-e959-11ea-9225-57600ff697ee.png)
