### ISSUE TITLE
Visual issues on OIDC client advanced settings page

### ISSUE THREAD

**Issue by theshaun** [GluuFederation/oxTrust#2018]
Hi Team, 

Just noticed that the remove button for the "Default requested Authentication Context Class Reference (ACR) values" section is hidden

![image](https://user-images.githubusercontent.com/712995/90593501-6ab5ec80-e22b-11ea-9d94-670c4bb4451d.png)

![image](https://user-images.githubusercontent.com/712995/90593533-87eabb00-e22b-11ea-8a66-c93cb77f2abd.png)

Cheers, 
Shaun

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/90628290-48b16f80-e215-11ea-87ac-061ea5f603e2.png)

**Comment by syntrydy** [comment]
@mzico @theshaun  Fixed
