### ISSUE TITLE
Password reset functionality is not working when security Question and security answer is entered.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2019]
## Describe the issue
 Password reset functionality is not working when security Question and security answer is entered.

## Steps To Reproduce
 1. Register a user with security question and security answer active .
 2. Go to gluu oxtrust login ui and try to change the password.
 3. enter security question and answer along password and repeat password.
 4. Try to change the password.

## Expected behavior
 Password should  changed.

## Actual behavior
It will taken to new forgot password page but again after entered field values its taken to same page.

## Screenshots
![Screenshot from 2020-08-24 17-05-29](https://user-images.githubusercontent.com/34593983/91040571-1d22f080-e62c-11ea-9ed5-d021657df3b6.png)
![Screenshot from 2020-08-24 17-05-39](https://user-images.githubusercontent.com/34593983/91040620-2e6bfd00-e62c-11ea-8d6d-c7e441c121fc.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu 18
 - Gluu version 4.2.1

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/91051894-a4feff80-e618-11ea-9295-a5bc766f2f93.png)

**Comment by syntrydy** [comment]
This issue is strange

**Comment by MohitMaliFtechiz** [comment]
hi @syntrydy  are you able to replicate it ?
