### ISSUE TITLE
Saml Configured relay party : assertionlifetime value box is so small its value cannot be read . 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2026]
## Describe the issue
Saml Configured relay party : assertionlifetime value box is so small its value cannot be read . 

## Steps To Reproduce
1. Go to 'saml'
2. Create Trust Relationship , configured relay party 
3. Select SAML 2 logout profile 
4. try to enter assertionlifetime

## Expected behavior
assertionlifetime value box must be readable

## Actual behavior
assertionlifetime value box is unreadable

## Screenshots
![Screenshot from 2020-09-15 18-01-13](https://user-images.githubusercontent.com/34593983/93210570-768ac500-f77d-11ea-960a-5257a3f585b4.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu 18 
 - Gluu version 4.2.1 with couchbase

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/93240830-86ee7000-f77c-11ea-9c4b-ed2b60df4900.png)
