### ISSUE TITLE
Add Local Authentication for oxTrust 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2028]
A partner currently has a blocker to use Gluu because they can't strip the Admin UI capability, as oxTrust itself is a client of oxAuth.  Perhaps we can add a feature to store a local password for admin in the oxTrust configuration (needs to be hashed), bypassing the OpenID authentication.

**Comment by syntrydy** [comment]
It is not clear for me what should be done here.

**Comment by yurem** [comment]
We need additional login form to allow admin log in without using oxAuth. To hash/check admin password we can use:
`PasswordEncryptionHelper.createStoragePassword(passwords[i], PasswordEncryptionMethod.HASH_METHOD_SSHA256);`
`PasswordEncryptionHelper.compareCredentials(password, userPassword);` methods

**Comment by syntrydy** [comment]
okay, how are we going to know which one should be used? a config property in oxtrust or in oxauth?

**Comment by nynymike** [comment]
I think we should back-burner this issue. In Gluu 5, the admin UI enables you to configure any OP as the source for admin identity.
