### ISSUE TITLE
Add ability to specify oxauth address instead of calling FQDN

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxTrust#2032]
When calling the authorization endpoint(the code flow), oxTrust attempts to hit the full FQDN to get the endpoint. In cloud native edition it is possible to specify an internal address that oxTrust can use instead of using the full FQDN. In other words, it shouldn't require a call externally.

**Proposed enhancement**

Add  the ability to inject the oxauth address via env and if that fails  use the FQDN. That will save us network hops in the cloud native edition along with increasing performance and security. 

Example: 
ENV OXAUTH_ADDRESS = oxauth:8080

Full FQDN is assumed to be `test.gluu.org`

The changes would equate to :

If ENV OXAUTH_ADDRESS  --> `https://oxauth:8080/open-id`
else --> `https://test.gluu.org/open-id`

**Comment by yurem** [comment]
@syntrydy Please don't reformat code. It's very difficult to review commits when 100% lines were changed.
