### ISSUE TITLE
need to restart `idp` service to get saml attribute 

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/oxTrust#2034]
## Describe the issue
In SAML response, I am not able to get the SAML attribute which I've already added on my external gluu IDP TR. oxTrust showing the TR status `active` but still failing. I am getting this problem just after the fresh installation of Gluu. I have to restart the IDP service manually `service idp restart` then it started releasing SAML attribute.

## Steps To Reproduce
1. Install Fresh Gluu CE
2. Add TR 
3. Use SP and request SAML - you can our Inbound SAML passport as an SP. you need one more Gluu CE for SP
4. Request for SAML and In SAML response, you will not get the attributes
5. Getting this logs in `oxauth_script.log` of SP Gluu CE which means external IDP is not releasing the attributes.
```
[org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Passport. checkRequiredAttributes. Attribute 'uid' is missing in profile
```

but after I restart the `idp` service. I am started getting attributes.

## Expected behavior
IDP should release SAML attribute after active TR.

## Actual behavior
Currently, I added TR, status is `active` but still facing problem. not able to get SAML attribute in 

## Desktop (please complete the following information):
 - OS: Ubuntu 18.04
 - Gluu version 4.2.1.Final 
 - Browser - chrome

## Additional context
I have two gluu servers
1. external IDP - where I have added TR
2. local IDP - this is my passport SP. where I've passport and it SAML request to external IDP

[oxauth_script.log](https://github.com/GluuFederation/oxTrust/files/5276984/oxauth_script.log) of my local idp where you can see `Attribute 'uid' is missing in profile` in log.

[oxauth.log](https://github.com/GluuFederation/oxTrust/files/5277004/oxauth.log) log file of external idp
[oxtrust.log](https://github.com/GluuFederation/oxTrust/files/5277010/oxtrust.log) log file of external idp

**Comment by nynymike** [comment]
This is not a bug. You actually don't have to restart--you have to wait for the Shib IDP refresh period, which is five minutes by default.
