### ISSUE TITLE
Add option to use internal addresses on all external oxTrust calls.

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxTrust#2035]
In cloud native edition it is possible to specify an internal address that oxTrust can use instead of using the full FQDN. In other words, it shouldn't require a call externally.

Proposed enhancement

Add the option to inject the internal addresses with the protocol to use  via env and if that fails use FQDN. That will save us network hops in the cloud native edition along with increasing performance and security.

Some external call examples:

```
https://FQDN/.well-known/openid-configuration --> protocol://internal-address/.well-known/openid-configuration 
https://FQDN/.well-known/uma2-configuration --> protocol://internal-address/.well-known/uma2-configuration
```

**Comment by nynymike** [comment]
First of all, this is really an oxAuth feature. Second these config pages are internet facing (not just used internally). Third, I don't know if it's worth the complexity to avoid some network traffic.
