### ISSUE TITLE
Validation not working in Register.xhtml

### ISSUE THREAD

**Issue by abhijain-cloud** [GluuFederation/oxTrust#2039]
Validation not working in Register.xhtml

## Describe the issue
Attribute should be validated for Validation RegExp or Regex Pattern.

Register.htm page has attribute Name: UID /Display Name : userName

Provide validation value for : RegExp or Regex Pattern

Register.xhtml page has validator for attribute.

## Steps To Reproduce
1. Go to Attribute . Select attribute uid/user name
2. Provide value for RegExp or Regex Pattern. Save it.
3. Go to URL : {gluuserver,url}/identity/register.htm
4. Pass any invalid value 
5. Attribute accept all value , No validation error,
6. Validation not working application accept all value.

## Expected behavior
Validation should work 

## Actual behavior
Validation not woking, user can enter any data and save it.

## Desktop (please complete the following information):
 - Browser chrome, safari

## Additional context
Register.xhtml page has validator for attribute.
<f:validator validatorId="extendedRegexValidator"> <f:attribute name="pattern" value="#{((empty _custAttr) or (empty _custAttr.metadata) or (empty _custAttr.metadata.attributeValidation) or (empty _custAttr.metadata.attributeValidation.regexp)) ? '.*' : _custAttr.metadata.attributeValidation.regexp}" /> </f:validator>

Class not exits for class extendedRegexValidator in git code base version 4.2. Since 3.1.0 It was removed from code but it is exit in Register.xhtml

Register.xhtml page has validator for attribute.

I tried with <f:validateRegex pattern in custome page , same behaviour validation not working.

**Comment by nynymike** [comment]
Won't fix. People should not be using this feature.
