### ISSUE TITLE
Improvements in interfaces for Asimba

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#204]
Edit properties forms should be converted to some wizards. For example: an user creates a new IDP. Enter URL -> select IDP type (Shib, ADFS, other Asimba) -> the form finds Metadata URL, download Metadata, fills flags and attributes with default set for this type of IDP.

Mike Schwartz: we have an xml mapping file now.
Mike Schwartz: we wrote a custom discovery class to support this use case.
Mike Schwartz: but net-net, I'm very confused by this interface.
Mike Schwartz: Its asking me for a bunch of ID's... and I'm not sure where to find them
Mike Schwartz: PreAuthorizationProfileID, PostAuthorizationProfileID, AttributeReleasePolicyID, AuthenticationProfileIDs
Mike Schwartz: what is this stuff????
Mike Schwartz: how am I supposed to know it?
Mike Schwartz: Even under Selector:
Mike Schwartz: Organization ID\* ?
Mike Schwartz: what is it ?
Mike Schwartz: DO I make it uP?

Mike Schwartz: I have no idea what's going on, or what to configure.
Mike Schwartz: It needs to be more intuitive....
Mike Schwartz: The point of the GUI is to make it easy for the admin

**Comment by aliaksander-samuseu** [comment]
@dmogn @nynymike 
It seems Asimba's pages have been re-worked, they look much more consistent now. Can we close this issue?
