### ISSUE TITLE
Remove 'Generate SP metadata' feature

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2043]
We don't need Gluu Server to generate metadata for SP. SPs are sufficient enough to generate their own metadata which can be used in Gluu Server to create Trust relationship. 
![Capture](https://user-images.githubusercontent.com/7156097/99356137-4213b200-286f-11eb-81e5-f809089a2093.PNG)

**Comment by nynymike** [comment]
agreed. The feature is more trouble then it's worth.
