### ISSUE TITLE
Remove `sector_identifier_uri` menu with dialogs and provide ability to enter it as text with automatic population of `redirect_uris`

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#2044]
## Describe the issue

Calculation of sub must be performed based on host of the `sector_identifier_uri`. Thus we need:

1. Remove `sector_identifier_uri` menu with dialogs
2. Provide ability to set `sector_identifier_uri` as text for the client.
3. When set `sector_identifier_uri` for the client, oxTrust must : 
   a) validate `sector_identifier_uri` is valid
   b) retrieve JSON from `sector_identifier_uri`. If no JSON, show error message
   c) If it's valid JSON, add content to client's `redirect_uri`.

Support: 9141

**Comment by syntrydy** [comment]
Fixed
