### ISSUE TITLE
Custom Branding (change in logo and favicon) is not working in Gluu CE 4.2.2

### ISSUE THREAD

**Issue by HemantKMehta** [GluuFederation/oxTrust#2050]
Hi I am trying to change the logo and favicon in Gluu CE 4.2.2 and to do this I have copied the custom logo to custom/static/logo/logo.png and favicon to custom/static/favicon/favicon.ico. After this I restarted services (oxauth, identity).

Still I see the default logo and favicon. It seems that the internal servlets (/servlet/logo and /servlet/favicon) are not working as expected.

However,It works when I copy them in /opt/gluu/jetty/oxauth/custom/static/img/ or (/opt/gluu/jetty/oxauth/custom/static/logo/ and /opt/gluu/jetty/oxauth/custom/static/favicon/)
and in login-template.xhtml referring them through
ext/resources/img/logo.png or ext/resources/logo/logo.png
ext/resources/img/favicon.ico or ext/resources/favicon/favicon.ico
instead of
#{request.contextPath}/servlet/logo
#{request.contextPath}/servlet/favicon.

**Comment by syntrydy** [comment]
In 4.2.x there is an option under organization configuration to upload the logo and favicon.

Please refer to the documentation https://gluu.org/docs/gluu-server/4.2/admin-guide/oxtrust-ui/#organization-settings
