### ISSUE TITLE
Upgrade Bouncy Castle library for FIPS Compliance

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/oxTrust#2058]
In order to use FIPS compliant cryptography, we need to upgrade our Bouncy Castle crypto library to a FIPS Certified version. Information and packages can be found [here](https://www.bouncycastle.org/fips-java/).

**Comment by nynymike** [comment]
This should not be done in the code. There should be a procedure in the docs about how to replace BounceCastle with a FIPS verified version.

**Comment by shmorri** [comment]
Adding to docs to-do list
