### ISSUE TITLE
oxTrust is crashed when a search with a broad criteria is executed using User search feature against a big enough user database

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2061]
## Description

As was reported in ticket 9511 for Gluu Server 3.1.7 first, in case of substantial userbases (hundreds of thouthands, even millions of users) a search for an user with a broad criteria that may return thousands or hundreds of thousands of results (substrings like "an", or one containing part of org inum) results in oxTrust crashing with Java OOM error thrown.

## Preconditions:

1. Gluu Server installed with LDAP server as backend (haven't been tested for CB), with 300000 to 1.5mil test users entries in it; for ease of testing, it would help to ensure all user entries contain same substring in some of their attributes (like, they all could have the same `givenName`)

## Steps To Reproduce

1. Log in to oxTrust
2. Move to `Users` > `Manage People`
3. Use a wide enough search criteria there that will return your tens or hundreds of thousands users 

## Expected behavior
Search either provides requested results, or at least rejects the criteria, deeming it too broad and potentially dangerous. Utilizing LDAP pagination feature should help with providing at least some results without putting a lot of strain on the server (but not sure how to handle case when CB is backend, if it's affected as well)

## Actual behavior
oxTrust crashes with Java OOM error thrown

**Comment by nynymike** [comment]
These are ad hoc searches. We can increase the number of characters required--for example to three. We could also disallow searches on inum, or create a regular expression that would prevent search against the base inum.

**Comment by MohitMaliFtechiz** [comment]
hi Gasmyr ,

I also did same test with around 4 lakh user ,  when i try to search user with "org" keyword oxTrust crashes so we have to prevent certain keyword too.

**Comment by syntrydy** [comment]
@MohitMaliFtechiz your server(user.gluu.org) is updated with the latest war. Try on it now, if possible add more users as well.
Customers have a million users
