### ISSUE TITLE
Group and People count on Server Status Page Incorrect

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/oxTrust#207]
Upon fresh installation of Gluu Server 2.4.2 on CentOS 6.7, the server status page showed empty space next to Groups and People count. Upon import of 9 contacts from a test xls file, it showed a count of 1 for Group and Person. It should have been `10 = 1 admin + 9 imports`. Upon creating a new person using the <kbd>Add  Person</kbd> from the oxTrust UI, the count still remained at 1.

**Comment by zamilskhan** [comment]
I tried rebooting VM and then restarting Gluu Server. The count does not go up immediately and it takes some time.

**Comment by yurem** [comment]
yes, we gather this statistic every one minute to avoid extra CPU/LDAP usage on every home page show
We can decrease this interval to 30 seconds if needed. But it's not bug...

**Comment by aliaksander-samuseu** [comment]
@yurem @zamilskhan 
Changed it to enhancement, is it okay?

**Comment by yurem** [comment]
ok
