### ISSUE TITLE
Fill correct provider options as per type in Passport Provider Configuration

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/oxTrust#2074]
## Describe the issue
Once you select type `oauth`, it populate/shows two fields `client_id` and `client_secret` which are wrong key for type `oauth`. Those are **case sensitive**. Those should be `clientID` and `clientSecret`

## Steps To Reproduce
1. Go to `Passport > Providers > Add New Provider > Select type: oauth`
2. Now you can see two Provider Options, `client_id` and `client_secret` which are wrong

## Expected behavior
The key should be `clientID` and `clientSecret`

## Actual behavior
Currently its populating `client_id` and `client_secret`

## Screenshots
![Gluu 2021-06-11 22-31-36](https://user-images.githubusercontent.com/39133739/121724113-0b500280-cb05-11eb-9afc-65ee47efa3f9.png)

## Desktop (please complete the following information):
 - OS: Ubuntu20.04LTS
 - Gluu version 4.3.0 latest
 - Browser: chrome

## Additional context
Please take care while updating code. For type `oauth`, keys should be `clientID` and `clientSecret`
and
For type `openid-client`, keys should be `client_id` and `client_secret`.

**Comment by syntrydy** [comment]
@kdhttps do we need a patch for 4.2.3?

**Comment by kdhttps** [comment]
@syntrydy  
no, I just checked this is working good in 4.2.3, this may occurs because of openid-client changes in 4.3.0 beta. Fix it for 4.3.0.

**Comment by kdhttps** [comment]
I tested new changes, there is one problem. Once you switch from `oauth` to `openid-client` and wise-wersa 2 times then it populate wrong fields in `oauth` case.

How to reproduce:
1. select `oauth`, it will populate `clientID` and `clientSecret`, which is correct
2. select `openid-client`, it will populate  `client_id` and `client_secret`, which is correct
3. select `oauth` again, it will populate `client_id` and `client_secret`, which is wrong

@syntrydy  could you please perform this test and checks/fix?

**Comment by syntrydy** [comment]
@christian-hawk , fixed
