### ISSUE TITLE
oxtrust: Validation Error: Value not according to pattern

### ISSUE THREAD

**Issue by marchharesoftware** [GluuFederation/oxTrust#2076]
oxtrust: Validation Error: Value not according to pattern

To reproduce this problem:

1. use oxtrust to add a new user
2. enter a valid email address

```
a&amp;bapps_management@mhsww.us
adam.d'amway@mhsww.us
```

3. receive an error message saying it's not a valid email address

[see picture](http://march-hare.com/images/email-address-validation-error.png).

This error also occurs when the same user is loaded via SCIM and reported here (closed without resolution):
[support ticket 9731](https://support.gluu.org/identity-management/9731/scim-unexpected-value-for-attribute-emailsvalue/)

I do not know if the validation is duplicated in both oxtrust and scim or if there is a central place where this incorrect validation is coded

Reported here:
[support ticket 9766](https://support.gluu.org/identity-management/9766/oxtrust-validation-error-value-not-according-to-pattern/)

Originally reported here (and closed without resolution):
[support ticket 9732](https://support.gluu.org/identity-management/9732/oxtrust-validation-error-value-not-according-to-pattern/)

Before the above tickets were closed, someone on the gluu team mischaracterised this bug report as being about unicode email addresses.  

I want to make clear that these are NOT unicode email addresses, and any LDAP server should have no problem storing these email addresses.  

these are plain ascii email addresses.

These email addresses are similar to real customer email addresses from whom I have hundreds of emails.

see wikipedia description of a valid address: https://en.wikipedia.org/wiki/Email_address#Local-part

I have not personally tested that opendj accepts these addresses - but since they are plan ASCII text email addresses I think that is a reasonable expectation.

Please advise how to change these validation rules for both oxtrust and scim.

**Comment by huebnd** [comment]
I'd like to support the request of @marchharesoftware . Having the email validation for SCIM hard coded (https://github.com/GluuFederation/scim/blob/08291a8ba28674e20c946b965c296eaaa73cb318/scim-model/src/main/java/org/gluu/oxtrust/model/scim2/Validations.java#L21) seems suboptimal and renders some valid email addresses in existing IDM systems virtually useless when using Gluu. 

We've run into the same issue with email addresses like `user+01@example.org` which are valid email addresses and should not cause any issues with storing in the LDAP backend.

I think these filters should either be configurable (I can see the issue with incompatible values in LDAP though) or at least less strict.

Kind regards
David

**Comment by shekhar16** [comment]
Fixed. allows more special character as per above comments like & 'etc Here is the screenshot.

![image](https://user-images.githubusercontent.com/15937500/163004223-dff0a692-1b1f-4de7-b582-067487bca470.png)


![image](https://user-images.githubusercontent.com/15937500/163004524-597cd659-7dce-4cc4-b0da-1ff6fa4731fd.png)

**Comment by marchharesoftware** [comment]
is this fixed in SCIM as well, or only in oxTrust?

What release is this targeted for?

**Comment by shekhar16** [comment]
@marchharesoftware   this fixed in oxtrust.
