### ISSUE TITLE
Adding Extra Libraries created wrong classpath in oxauth.xml

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2077]
## Describe the issue
Adding Extra Libraries created wrong classpath in oxauth.xml

## Steps To Reproduce

1. go to gluu admin console
2. go to cofiguration
3. go to organization configuration-> Exrta Libraries
4. add jar to "Add lib to Oxauth"
5. click update 
6. on terminal login to gluu-server open opt/gluu/jetty/oxauth/webapps/oxauth.xml.
7 check the newly created path.

## Expected behavior
newly created path needs to be "opt/gluu/jetty/oxauth/custom/libs/xyz.jar"

## Actual behavior
new path is "opt/gluu/jetty/oxauth/webapps/oxauth.xmlxyz.jar which cause oxauth failure and http 404 error

## Desktop (please complete the following information):
 - OS: Ubuntu 20
 - Gluu version: 4.2.3

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/124948185-60017300-e008-11eb-8460-eb70a5987e67.png)
