### ISSUE TITLE
Updating client id in passport IDP-initiated flow config throws   Oops error.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2084]
## Describe the issue
Updating client id in passport IDP-initiated flow config throws Oops error.

## Steps To Reproduce
1. Go to admin console.
2. Go to passport.
3. Go to IDP-initiated Flow config 
3. try to change the value in clinet ID 

## Expected behaviour
Client id must be changed to selected client on update

## Actual behaviour
on clicking update gets identity error.

## Desktop (please complete the following information):
Gluu-version 4.3.0
OS:- Ubuntu 20.04

**Comment by syntrydy** [comment]
Can you share the log?

**Comment by syntrydy** [comment]
Fixed!
