### ISSUE TITLE
Enhance usability of scopes picker in client edition form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#2085]
In the client form, the popup used to select scopes should allow dragging the divider between name and displayname columns

When a scope  name is longer than a few characters it is not possible to read the whole name. This makes it difficult to select scopes when several of them share the same prefix. I'm attaching an image for clarity

Ideally the list should appear sorted by name upon first load...

![Screenshot from 2021-08-13 08-55-46](https://user-images.githubusercontent.com/5444180/129373533-4e90c058-88fe-4c7a-9c4e-1d745a10c1e0.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/129392719-5984afe5-db18-4452-9639-61ae995ee4bf.png)

For sorting, a click on a column name sort the data.

**Comment by jgomer2001** [comment]
yes, I generally know how to use a computer
