### ISSUE TITLE
Passwords not pulled from file in the import file method

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#209]
The Passwords stored in the test file under the coloumn `Password` is not pulled and does not show up in the imported user details. The password needs to be manually added for the user to log in.

**Comment by zamilskhan** [comment]
Update: while accessing the user pulled from file, the following lines are in the `wrapper.log`

INFO   | jvm 1    | 2016/03/09 10:17:38 | 2016-03-09 10:17:38,072 ERROR [org.gluu.oxtrust.ldap.service.AttributeService] Failed to find attribute 'iname' metadata
INFO   | jvm 1    | 2016/03/09 10:17:38 | 2016-03-09 10:17:38,072 ERROR [org.gluu.oxtrust.ldap.service.AttributeService] Failed to find attribute 'oxLastLogonTime' metadata

**Comment by shekhar16** [comment]
Fixed : Now Password are set from the file .

**Comment by zamilskhan** [comment]
Closing Issue
