### ISSUE TITLE
User Registration Page 

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#210]
It seems that any user is able to register and have his basic info such as First Name, Last Name, Username and Email put into the server even when the script is disabled. If it is possible, the page `hostname/identity/register/` could be kept dormant until the script is enabled.

**Comment by nynymike** [comment]
1. The page should not be visible.
2. Before the form is processed by the action, it should make sure registration is enabled.

**Comment by shekhar16** [comment]
Fixed. Added check whether user_registration script is enable or not.

**Comment by zamilskhan** [comment]
Closing issue.
