### ISSUE TITLE
Please re-evaluate fix to Support Ticket #2310

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#211]
Setting the `@JsonIgnore` annotation in `Resources` property of `ListResponse.java` caused the disappearance of the `Resources` field in the JSON body, as reported in the following ticket:

https://support.gluu.org/integrations/unexpected-200-behavior-for-scim-user-group-endpoints-2540

However, I could not reproduce the issue in the original ticket (#2310) as the attached image has already been deleted/expired. Could you please re-evaluate fix?

Thanks.

**Comment by shekhar16** [comment]
Fixed. Added @JsonAutoDetect to avoid unexpected behavior..

**Comment by yurem** [comment]
Can we close it?

**Comment by uboznikov** [comment]
Tested ok.
