### ISSUE TITLE
Not able to  create custom nameid(4.3.1+MYSQL).

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2116]
### Describe the issue 

Not able to  create custom nameid(4.3.1+MYSQL).

### How to reproduce

1. Go to admin ui
2. Go to SAML
3. Go to Config_nameID
4. Try to enable a new nameid

### Expected Behaviour

Name-id must be created

###  Actual Behaviour

oops error occured on update

### Config

Gluu 4.3.1 +mysql

OS Ubuntu 20.04

**Comment by MohitMaliFtechiz** [comment]
[nameid_error.log](https://github.com/GluuFederation/oxTrust/files/7806353/nameid_error.log)

**Comment by syntrydy** [comment]
Fix by @yurem
