### ISSUE TITLE
Remove api-server module

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#2119]
I think this module is deprecated. In GluuFederation there is standalone server oxtrust-api project: https://github.com/GluuFederation/oxtrust-api

**Comment by uprightech** [comment]
Just adding this for the record. 

We all had a back and forth conversation and it was the standalone version we had to deprecate instead
Reason being , It was pointed out (rightly so) , customers have been complaining about having to run too many pods
A standalone oxTrust instance would have meant an additional pod/component to manage , so it was decided it wasn't 
necessary to remove the api-server module from oxTrust

**Comment by shekhar16** [comment]
@nynymike  @uprightech  @yurem  if we are continuing this module then what we need to do with new project i.e. https://github.com/GluuFederation/oxtrust-api
We implemented new functionality i.e. trust-IDP apis in this project and I think it has been delivered to one of the client also.

**Comment by uprightech** [comment]
@shekhar16  , we'll have to migrate the code written there to here. Can you open a ticket for that ?

**Comment by syntrydy** [comment]
I think we don’t have to re-migrate
we can keep it separated, but make sure the artifact is a jar not .war
if a client wants to deploy that API, they can edit identity.xml and associate that API jar as a custom library
Separating that is very good as it means that the API doesn’t depend on oxTurst release flow.

I think doing it that way is the best option, it doesn’t imply more pod, but it helps separate the development of that API from the development of Oxtrust.
If for example, a customer need a new endpoint ASAP, we just add that endpoint, build that jar and they deployed under identity as a custom library.

**Comment by nynymike** [comment]
In Gluu 4, I think oxtrust API should stay a part of oxtrust...

**Comment by yurem** [comment]
@syntrydy if we run oxtrust-api under oxTrust as custom library we can maintain only one copy in https://github.com/GluuFederation/oxtrust-api In this case to allow use it as custom library we can add module which contain all required classes

For me sync 2 projects all the time will led to issues. It's better to have one project which produces jar and war artifacs

**Comment by shekhar16** [comment]
I agree with @yurem, It will be difficult to sync both repos and also for maintaining the swagger docs for oxtrust apis therefore we need to decide whether we need to continue the module or new independent project for oxtrust apis.

**Comment by nynymike** [comment]
I still do not understand which approach is used in shipping 4.4.1?

**Comment by shekhar16** [comment]
> In Gluu 4, I think oxtrust API should stay a part of oxtrust...
ok then we are going to continue with oxtrust's module for oxtrust apis.
I m creating the ticket to add missing apis in module.
