### ISSUE TITLE
Updating log-level in passport basic configuration is not reflection on passport.log file.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2133]
### Describe the issue
Updating log-level in passport basic configuration is not reflection on passport.log file.
 
### Steps To Reproduce
Steps to reproduce the behaviour:

Go to admin UI.
Go to passport.
Go to basic configuration.
Try to change the log level.

Check log file ```/opt/gluu/node/passport/logs ``` .

### Expected behaviour
log levels in passport logs must be changed accordingly 

### Actual behaviour

log-level is not changed.

### Config

Gluu-server 4.3.1+mysql

Ubuntu20.04

### screenshots
![Screenshot from 2022-03-21 15-10-27](https://user-images.githubusercontent.com/34593983/159224249-807e265f-cdb5-4f10-b461-f2640da68418.png)
![Screenshot from 2022-03-21 15-11-13](https://user-images.githubusercontent.com/34593983/159224266-344d0096-51ab-40cb-9b16-e4a3cf250698.png)

**Comment by MohitMaliFtechiz** [comment]
> `passport-config.json` shouldn't be affected by oxTrust UI as the settings in this file (generated during gluu server setup) are used to fetch configuration from oxauth (`configurationEndpoint`) using `UMA` protocol.

agreed! changes in cert files can lead to passport failure, those values should not be editable in basic configuration.  but for logging-level it should work, as i am not able to change logging level here.

> The issue is wrongly written.
> After changing log level in the UI, the expected **behavior** is to see other log levels in passport logs.

i'll update the issue here. thank you for correction.

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  the log level changes are properly reflecting in Database.
![image](https://user-images.githubusercontent.com/15937500/163564565-aa856c62-774d-4018-9760-3a8ecbeb3528.png)

**Comment by MohitMaliFtechiz** [comment]
closing this issue after disscussion with @shekhar16
