### ISSUE TITLE
Login page not showing the correct localized characters

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/oxTrust#2134]
## Behaviour 
On the login page, there are some characters that couldn't able to displayed properly. 

## Expected:

```
Falha na autenticação.
```

## Result:

```
Falha na autentica&ccedil;&atilde;o.
```

![](https://images2.imgbox.com/ec/fd/YB02tsxV_o.png)

## How to reflect?

I have customized [this](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/oxauth_en.properties) resource file and put into `/opt/gluu/jetty/oxauth/custom/i18n`.

![](https://images2.imgbox.com/44/fd/KPOXOEyr_o.png)

Ref. Tickets: https://support.gluu.org/10241,  https://support.gluu.org/10107

## Gluu Server Info:

- OS: Ubuntu 18
- Version: Gluu 4.3.0
-

**Comment by imShakil** [comment]
I have faced this issue on the login page. But @yurem confirmed me to create here. @syntrydy let me know please if need to create on the oxauth.

**Comment by nynymike** [comment]
yes, please re-create on oxauth

**Comment by nynymike** [comment]
Now here https://github.com/GluuFederation/oxAuth/issues/1660
