### ISSUE TITLE
Mysql: Unable to add oxtrust and oxauth logo/favicon.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2139]
### Describe the issue

Not able to add oxtrust and oxauth logo/favicon.

### How to reproduce

1. Go to admin ui
2. Go to configuration.
3. Go to organization configuraion.
4. Go to organization setting. 
5. try to update oxauth and oxtrust logos
6. update the setting.

### Expected behaviour 

oxtrust and oxauth logo/Favicon should be uploaded

### Actual behaviour 

identity throws oops error 

### config

Gluu-server 4.4.0 + mysql.

OS Ubuntu 20.04

### Gif

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/34593983/160080971-55cb225d-df72-4211-8cba-b85a1c86a140.gif)

**Comment by shekhar16** [comment]
Hi @MohitMaliFtechiz  its working fine for me. Here is the screenshot.
![image](https://user-images.githubusercontent.com/15937500/160869961-2f0abba2-bf06-479c-85b0-5a8de8986cda.png)



Can you please check again.

**Comment by MohitMaliFtechiz** [comment]
closing this issue as uploading favicon is working now. this issue has been fixed.
