### ISSUE TITLE
Hide SAML menu items (Shib, Asimba) while Asimba or Shib IDP hasn't been installed

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#216]
Check that the product has been installed while show SAML submenu:

William Lowe: can we make it so that if Asimba is not installed during installation, the new interfaces are hidden?
William Lowe: we need to do the same thing for Shibboleth

**Comment by dmogn** [comment]
Update:

Maybe the best solution is use the stored properties list 
https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L1579
check configuration flag 
https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L60
and make this checking as general feature in oxTrust's util package for future using.

**Comment by dmogn** [comment]
Hm... The installer do not stores instalXXX flags https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L60
to 
/install/community-edition-setup/setup.properties.last

**Comment by dmogn** [comment]
This task is directly related to #197
( And to closed #223. Three issues for one feature ).

**Comment by dmogn** [comment]
Dmitry Ogn: It's more architecture question.
William Lowe: Right.. And we can't do it just for CE?
Dmitry Ogn: I can add some flag, check it and hide the submenu for CE only.
William Lowe: That might be a good fix

**Comment by dmogn** [comment]
Down for CE:

![menuhidesaml](https://cloud.githubusercontent.com/assets/14166017/15995877/e20c1a3c-30f7-11e6-912f-32569e9244b4.jpg)

Hide full SAML menu when CE and both Shib IDP + Asmiba uninstalled.
Hide SAML submenu when CE and Shib IDP uninstalled.
Hide Asmiba submenu when CE and Asmiba uninstalled.

All checks in dynamic (every time oxTrust starts).

**Comment by dmogn** [comment]
We need adjust this logic for "Docker" version.

**Comment by iromli** [comment]
It would be nice if oxTrust could check the environment variables to hide/show the menu and submenus.

**Comment by yurem** [comment]
Is it need for "docker" version we can add environment variables checks.
But maybe we can add LDAP attribute to specify list of installed components in JSOM format? Is there any tree in LDAP which we not sync during replications?

**Comment by iromli** [comment]
@yurem Currently, only `o=gluu` that is replicated.

**Comment by shouro** [comment]
I vote for environment variable check.

**Comment by yurem** [comment]
Here are variables names which oxTrust ProductInstallationChecker should check:
```
gluu.component.ce=true
gluu.component.oxauth=true
gluu.component.oxtrust=true
gluu.component.idp3=true
```

**Comment by yurem** [comment]
If `gluu.component.docker=true` oxTrust should assume that there is no installed components unless if it's enabled via env variable.

**Comment by yurem** [comment]
@iromli Is this issue still actual? I think we resolved it already

**Comment by iromli** [comment]
> Here are variables names which oxTrust ProductInstallationChecker should check:
>
> gluu.component.ce=true
> gluu.component.docker=true
> 
> gluu.component.oxauth=true
> gluu.component.oxtrust=true
> gluu.component.idp3=true
> gluu.component.asimba=true

@yurem I can double check. How to pass the environment variable to oxTrust server?
