### ISSUE TITLE
fix: ui not showing multivalued properties correctly

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxTrust#2175]
## Describe the issue
When adding multivalued attributes they appear in raw form

![image](https://user-images.githubusercontent.com/47318409/168284309-a0fae22e-27f0-491e-8c3f-277156637ae9.png)

**Comment by MohitMaliFtechiz** [comment]
i am able to replicate the issue in gluu-server-4.4.1+mysql

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  I had a discussion with @yurem so for MYSQL we can't alter the table after installation of Gluu server. So, we are disabling the attribute's multivalued check box for MySql DB.

**Comment by yurem** [comment]
Now oxTrust gets information if attribute is multivalued from SQL schema.
