### ISSUE TITLE
Client secret key is replacing with Gluu admin account password if autofill is activated.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2177]
## Describe the issue

Client secret key is replacing with Gluu admin account password if autofill is activated.

## Steps To Reproduce
1. Go to admin login page and try to login with auto fill is activated.
2. Login to admin via admin credentials.
3. Go to OpenidConnect and add a new client.
4. check the Client secret value.

## Expected behavior
Client secret should have been different form admin login password.

## Actual behavior

client secret autofill as admin password on client creation.

## Gif
![clientsecret-2022-05-20_12 06 45 (online-video-cutter com)](https://user-images.githubusercontent.com/34593983/169476451-cf49319e-280f-484d-bbf0-f9f7d2edeee3.gif)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu20.04
 - Gluu version 4.2.3- 4.4.0

 ## Reference ticket 
https://support.gluu.org/single-sign-on/10504/client-secret-key-is-replacing-with-gluu-admin-account-password/

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  there is no connection between login form and add client form.
It looks like you enabled the  browser's save form functionality for add client page thus the older add client form value got populated, its not login page values.

**Comment by shekhar16** [comment]
Also auto-form filling will only work on same host url, in our case the login page is of oauth and add client page is of identity.

**Comment by MohitMaliFtechiz** [comment]
as per discussion with @shekhar16 this issue is not replicated in Google Chrome browser. currently closing this issue
