### ISSUE TITLE
Remove sessionIdEnabled feature from oxTrust 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2179]
`sessionIdEnabled` feature is by default "true" inside code now and it shouldn't be modifiable by user ( https://github.com/GluuFederation/oxAuth/issues/900 ). Remove this dropdown from oxTrust. 

![Selection_025](https://user-images.githubusercontent.com/7156097/170507516-bf969471-45fc-451f-b78a-c7131eb9200f.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/12270959cc3b55a30f63e9a21404d27059579ca0
https://github.com/GluuFederation/oxTrust/commit/c48fc5c2ea23046919be8d5e8549c35e814fbf6f

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/170880923-797e1d53-e464-435a-8169-b45df64da54a.png)
