### ISSUE TITLE
Add test to clean up person/groups

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#218]
We need to cover case when there are problems in code and test is able to create person/groups but not able to remove them.

We have similar test in oxAuth-Server: https://github.com/GluuFederation/oxAuth/blob/master/Server/src/test/java/org/xdi/oxauth/comp/CleanUpClientTest.java

This test should remove all person/group except specified in properties.

Also it should clean up next test groups:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/oxauth/data/oxauth-test-data.ldif#L137
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/oxauth/data/oxauth-test-data.ldif#L145

There is only one member of this groups by default. It's inum=%(inumOrg)s!0000!B1F3.AEAE.B798,ou=people,o=%(inumOrg)s,o=gluu

**Comment by shekhar16** [comment]
Fixed.

**Comment by willow9886** [comment]
@yurem can you confirm Shekhar's fixes?

**Comment by yurem** [comment]
@shekhar16 please, add links with all commits related to this issue. I will review them.

**Comment by yurem** [comment]
We added this test but we need to find out proper conditions to activate it. It should clean up only test data.
For instance it can remove all entries with 'test user' in displayName

**Comment by nynymike** [comment]
This issue is quite old. Is it still outstanding?

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/1de6850a1b87561a37d934a3462c89bf31b5b5d9
https://github.com/GluuFederation/oxTrust/commit/e7489592db3a4f5e950b22d93acc8d02e2fd8801
https://github.com/GluuFederation/oxTrust/commit/9f4206aa2e220a19927da3fbe8392ebcd779e5df

**Comment by shekhar16** [comment]
yes it is fixed. above are commit links.:)
