### ISSUE TITLE
OxTrust `trusted-idp` persistence (config) api allowing empty required params

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/oxTrust#2184]
## Describe the issue
As noticed in inbound-saml issue https://github.com/GluuFederation/inbound-saml/issues/132 , the api allowing required param `host` to be empty. This value is also an unique identifier. 

## Steps To Reproduce
1. Install and setup api `4.4.0-SNAPSHOT` in a gluu 4.4.0 server install2. 
2. send `POST` request to trusted-idp endpoint

## Expected behavior
According to [Swagger specs 1.0.1](https://app.swaggerhub.com/apis/chris-hawk/inbound-saml/1.0.1), response status code should be 404 and a json with error message in it's body.

## Actual behavior
It's returning `201`, created. And is creating an object without `host` param or value in LDAP.

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu16.04LTS]
 - 4.4.0

**Comment by shekhar16** [comment]
Hey @christian-hawk
as per docs https://app.swaggerhub.com/apis/chris-hawk/inbound-saml/1.0.1 API have to return 403 if host already present and the same implemented Here is the doc screenshot.
![image](https://user-images.githubusercontent.com/15937500/175344160-ab2fc68b-91c4-464a-96ad-fa3d7344fa1d.png)


Here the implementation.
![image](https://user-images.githubusercontent.com/15937500/175344231-ae0987b6-1625-48b9-840f-26e8d6a0fef7.png)

**Comment by shekhar16** [comment]
@christian-hawk   Please close this ticket.

**Comment by shekhar16** [comment]
it is fixed closing it.
