### ISSUE TITLE
Remove custom attributes after test execution

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#219]
We need to add one missing step to [UserExtensionsTest](https://github.com/GluuFederation/oxTrust/blob/master/server/src/test/java/org/gluu/oxtrust/service/test/UserExtensionsTest.java)

It should remove custom attributes from custom object class and remove custom attributes at final step.

Also it will be nice to not hardcode CREATEJSON.  We can read it from properties file:
testData.getString("scim2.user.extension.create_json");

**Comment by uboznikov** [comment]
Please see commit: [889d1ad17d0269370419fe5da349292928477954](https://github.com/GluuFederation/oxTrust/commit/889d1ad17d0269370419fe5da349292928477954)

There is no need to remove custom attributes as this is just the same with [UserExtensionsJsonTest](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/UserExtensionsJsonTest.java) and [UserExtensionsPersonTest](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/UserExtensionsPersonTest.java) in SCIM-Client.

**Comment by yurem** [comment]
In this test we uses dynamic attributes with names 'customFirst', 'customSecond' and 'customThird'. But in SCIM-Client we uses pre-added attributes with names 'scimCustomFirst', 'scimCustomSecond' and 'scimCustomThird'

Hence attributes 'customFirst', 'customSecond' and 'customThird' removal will be good test if our API works fine and allow to add/remove attribute.

**Comment by uboznikov** [comment]
Sorry, I forgot that the custom attributes in the SCIM-Client unit tests have been renamed, but originally they were the same. So what we really want is another set of tests, i.e., for creating and deleting custom attributes?

**Comment by yurem** [comment]
ok, we can keep this test without attribute removal. We can add another non SCIM test to cover attributes add/remove just to check SchemaService.

**Comment by uboznikov** [comment]
Ok, I have committed: [- Fixed names of custom attributes](https://github.com/GluuFederation/oxTrust/commit/dee67c4c2372c7c59db53369f7457b7e70db283d)
