### ISSUE TITLE
Password reset confirmation page / color mismatch 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2194]
I think we should match color and design. Here is what it looks like now...
![Selection_072](https://user-images.githubusercontent.com/7156097/176825983-2312a21d-7e03-4df5-964c-fcff569599e9.png)
.

**Comment by shekhar16** [comment]
this is fixed. @mzico  or @MohitMaliFtechiz please test it.

**Comment by shekhar16** [comment]
I m closing this ticket.
@MohitMaliFtechiz  if found any issue please let me know.
