### ISSUE TITLE
No popup value available after selecting any metadata location from Drop-down.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2195]
### Describe the issue
No popup value available after selecting any metadata location from Drop-down.

### How to reproduce

1. Go to admin ui.
2. Go to SAML.
3. try to add a Trust Relationship
4. fill up the fields accordingly 
5. go to metadata location and click the drop-down to choose metadata location

### Expected behavior 

after selection of any location for metadata a popup must show up to provide metadata file. 

### Actual behavior 

No popup value available after selecting any metadata location from Drop-down.

### config

Gluu-server 4.4.1 

OS Ubuntu 20.04

### screenshots
![Screenshot from 2022-07-04 12-50-24](https://user-images.githubusercontent.com/34593983/177102513-2f7fd1f1-e2da-41f5-8261-ab624dad1a31.png)
![Screenshot from 2022-07-04 12-50-29](https://user-images.githubusercontent.com/34593983/177102543-426405aa-b009-4d27-9489-5e6c8d557153.png)

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  it is fixed. please test it.
https://github.com/GluuFederation/oxTrust/pull/2193

**Comment by MohitMaliFtechiz** [comment]
@shekhar16 ok i'll check.

**Comment by MohitMaliFtechiz** [comment]
this issue has beed fixed closing the issue.
