### ISSUE TITLE
oxTrust popup window is not stable

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#220]
Check out below screenshot. Popup window 'Relying Party Configuration' is sliding under left management menu... 

![popup_problemo](https://cloud.githubusercontent.com/assets/7156097/14048931/a283298e-f27f-11e5-80de-9865c821f369.png)

**Comment by willow9886** [comment]
we should also update the style of this pop up to match our new skinning.

**Comment by shekhar16** [comment]
Fixed.Popup window 'Relying Party Configuration' is now always on top.
Style is updated to match our new skinning.

**Comment by willow9886** [comment]
nice work @shekhar16 !
