### ISSUE TITLE
Cache refresh should remove persons sub entries on removal

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#2209]
If ORM not supports cascade removal CR  should remove `ou=pairwiseIdentifiers,inum=person_inum,ou=people,o=gluu` and `ou=fido,inum=person_inum,ou=people,o=gluu` related entries

In order to check if ORM supports this server can use `persistenceEntryManager.hasBranchesSupport(inum=person_inum,ou=people,o=gluu)`

To remove entries server can use `persistenceEntryManager.remove(String primaryKey, Class<T> entryClass, Filter filter, int count);`

**Comment by shekhar16** [comment]
code has been merged.
closing this ticket.
@MohitMaliFtechiz  Can you please test it.
