### ISSUE TITLE
Logout URI in OpenID Connect Add Client

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#221]
There is a filed in the form in the Add Client page named `Logout URI` and there is a button `Add Logout URI`. Are these the same or is there a duplicate?

**Comment by aliaksander-samuseu** [comment]
@zamilskhan 
Afaicr, "Add Logout URI" add "post_logout_redirect_uris" client's parameters which are used by [session management spec](http://openid.net/specs/openid-connect-session-1_0.html)
The only spec I've found mentioning "Logout URI" is [OpenID Connect Front-Channel Logout 1.0 - draft 00](http://openid.net/specs/openid-connect-frontchannel-1_0.html):

`
Client Metadata Name: logout_uri
Client Metadata Description: RP URL that will cause the RP to log itself out when rendered in an iframe by the OP `

Gluu does seem to support this:

![logoutmeta](https://cloud.githubusercontent.com/assets/11802046/14758696/68db9a4c-0911-11e6-9844-4707f2060d67.jpg)

..though it seems names of these metadata parameters are bit differ from those in spec:

![logoutmeta2](https://cloud.githubusercontent.com/assets/11802046/14758711/cdce6164-0911-11e6-8e88-c2f86ce9a865.jpg)

**Comment by aliaksander-samuseu** [comment]
@yuriyz , @willow9886 , could you have a look?

**Comment by yuriyz** [comment]
@aliaksander-samuseu during implementation front channel spec says:
```
"logout_supported" : true
"logout_session_supported" : true
```
Now spec is updated and appends "frontchannel_" prefix to avoid conflict with backchannel logout.
Of course both oxauth and oxtrust must be updated accordingly.

**Comment by yuriyz** [comment]
Created issue for oxauth here: https://github.com/GluuFederation/oxAuth/issues/204

**Comment by zamilskhan** [comment]
closing this issue then
