### ISSUE TITLE
Cache refresh should be independent service

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#2210]
Create new project based on Cache Refresh code from oxTrust. It also should not depend on oxTrust setting. Example of project organization is in https://github.com/GluuFederation/fido2 project

Build process should produce jar and war artifacts to allow run it as standalone and as part of Trust server

**Comment by nynymike** [comment]
I think we should start a folder in Janssen Project to do this... but leave Cache Refresh as part of oxTrust.
