### ISSUE TITLE
SMTP Keystore password must not be visible

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2214]
![image](https://user-images.githubusercontent.com/3717101/180670360-0811b471-78d6-40c3-acdf-1f29ccce6516.png)

This password should not be visible. Admins should be able to set it, but not view it.

**Comment by yurem** [comment]
Can we include fix for this in next version 4.4.2?

**Comment by smansoft** [comment]
Implemented/fixed in the version 4.4.1.
