### ISSUE TITLE
Remove Attrributes from UMA Scope Form

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2215]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/3717101/180833981-80c7e07f-a755-4e97-ba10-4079e419fd74.png">

This does not belong on the UMA Scope form...

Also, can we change the "Add Scope" text to "Save" -- it's confusing here, because you may think there is a scope withing a scope...

**Comment by shekhar16** [comment]
Issue is fixed as a part of #2213 . closing it.
@MohitMaliFtechiz  Please test it.
