### ISSUE TITLE
Remove "Add Resource Set" button from UMA / Resources

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2216]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/3717101/180838878-5078e06e-5d80-47b4-9804-6510e13d866b.png">

* As resource sets are registered by clients dynamically, an admin would never actually add a resource set.

* An admin would never manually register a client, so we could also remove the "Add Client" button, and the remove client link... associated client should be read only.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/3717101/180839254-15a4489e-3183-4a34-9879-f2c2ebb13b9d.png">

**Comment by shekhar16** [comment]
@nynymike   this issue will get  automatically resolved as a part of issue https://github.com/GluuFederation/oxTrust/issues/2222
 we removed the UMA -> resource navigation. User can navigate resources through client's form  (fixed as part of https://github.com/GluuFederation/oxTrust/issues/2211 )

**Comment by shekhar16** [comment]
closing this ticket.
