### ISSUE TITLE
Substring text search for Scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2219]
Both the `displayName` and `id` of the scope should be substring searched. For example, `offline` search returns nothing, even though there is a default scope called `offline_access`

**Comment by shekhar16** [comment]
fixed.

![image](https://user-images.githubusercontent.com/15937500/184505378-b93280d7-a7c7-4862-b9ca-99fc5bdf7bc4.png)

**Comment by shekhar16** [comment]
Issue is fixed. closing it.
@MohitMaliFtechiz  Please test it.
