### ISSUE TITLE
Hostname should show FQDN in Configuration/Server Status

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#222]
![hostnamevalue](https://cloud.githubusercontent.com/assets/7156097/14148207/35955728-f664-11e5-80d9-0a14cf81387e.png)

**Comment by zamilskhan** [comment]
@mzico is this  high priority?

**Comment by mzico** [comment]
No

**Comment by shekhar16** [comment]
@mzico the hostname is coming from ldap not from url ,so we need to update it in ldap.

**Comment by mzico** [comment]
@shekhar16 any idea which attribute? We might take a look...

**Comment by shekhar16** [comment]
@mzico  gluuhostname is the mapping attribute for hostname.

**Comment by mzico** [comment]
@shekhar16 : perfect!! thanks. 
@yurem : any suggestion on this issue? Seems like 'gluuHostname' is not getting the full hostname of IDP; instead it is getting the first part of the hostname

**Comment by nynymike** [comment]
Hostname needs to return the FQDN. What OS is this?

**Comment by mzico** [comment]
@nynymike : It's same for all OS ( Ubuntu, CentOS and RHEL ). 'gluuHostname' attribute is getting 'idp' value if the FQDN is 'idp.gluu.org'.

**Comment by nynymike** [comment]
The hostname should come from the LDAP config, not the server.

**Comment by nynymike** [comment]
This is a bug, but I'm not sure who looks at this page. I'm closing it because I don't care.
