### ISSUE TITLE
Remove files in /var/gluu/identity/removed

### ISSUE THREAD

**Issue by devrimyatar** [GluuFederation/oxTrust#2225]
It is reported that there are  LOTS (few millions) files under /var/gluu/identity/removed/ Files named like uuid={some_uuid},ou=cache,o=gluu{timestamp} Each file content is LDIF.
We need to check this directory regularly and remove non-used files.

Additionally we need to add property to specify how long we should keep history.

**Comment by shekhar16** [comment]
implementation is done and code has been merged in master branch.
Closing this ticket.
