### ISSUE TITLE
Feat: make languages configurable in properties

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2226]
This dropdown needs to be configurable:
![image](https://user-images.githubusercontent.com/3717101/183957751-a4daec9a-96e7-42c4-b96e-622469105123.png)

Currently, it is hard-coded:
![image](https://user-images.githubusercontent.com/3717101/183957807-0f9732a4-1445-465f-8def-5ee1241b6948.png)

**Comment by shekhar16** [comment]
The code has been merged.
Closing this ticket.
@MohitMaliFtechiz  testing is required.
