### ISSUE TITLE
Enhancement: 'no SAML' Gluu Server - no SAML feature in oxTrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#223]
If possible...

Organization might not install SAML in their Gluu Server. In that case can we remove the SAML features ( Shibboleth / Asimba ) from oxTrust? 
![suggestion](https://cloud.githubusercontent.com/assets/7156097/14148332/ad41f29a-f664-11e5-9c6a-30c91b046772.png)

**Comment by willow9886** [comment]
@dmogn do we already have an open issue for this?

**Comment by dmogn** [comment]
@willow9886 
Yes, we have: https://github.com/GluuFederation/oxTrust/issues/216

**Comment by willow9886** [comment]
OK, closing this and point to issue [216](https://github.com/GluuFederation/oxTrust/issues/216)

**Comment by dmogn** [comment]
Fixed.
