### ISSUE TITLE
'Update Password' button in many pages...

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#224]
There is an 'Change Password' that has no purpose! 
- Configuration --> Organization Configuration

**Comment by nynymike** [comment]
![image](https://cloud.githubusercontent.com/assets/3717101/24824430/a359ce1e-1bd0-11e7-99f0-7ae43b892656.png)

**Comment by sahiliamsso** [comment]
Still same this button available on screen for 3.0.2

**Comment by rajnikantsh** [comment]
Whatever changes has been done for this issue is not their in branch 3.0.2
