### ISSUE TITLE
'Login' button not required in password reset link

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#225]
I think we don't need 'Login' button in password reset link ( .../identity/person/passwordReminder.htm )
![passwordreset](https://cloud.githubusercontent.com/assets/7156097/14183320/54fc2b92-f735-11e5-9463-fa62b1c8b66f.png)

**Comment by willow9886** [comment]
can we also make the captcha look a little more professional? Take a look [here](https://www.google.com/search?q=captcha+design&espv=2&biw=1920&bih=932&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjB-8qGr-vLAhUrsYMKHeuTB5oQ_AUIBigB) for some inspiration. Let me know if you need a psd design or any other materials to help..

**Comment by mzico** [comment]
@shekhar16 @willow9886 : Instead of Captcha, I think we can implement 'reCAPTCHA' ( https://www.google.com/recaptcha/intro/index.html )?

**Comment by yurem** [comment]
We uses new reCapthaca in cert script:
![screenshot_2](https://cloud.githubusercontent.com/assets/6104200/14185407/58a64aaa-f782-11e5-8d52-101883a0020c.png)


You can use it as reference

**Comment by shekhar16** [comment]
Fixed : New reCAPTCHA is implemented and code is committed.

**Comment by willow9886** [comment]
@shekhar16 can you upload a screenshot?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14289563/f8a35c24-fb78-11e5-86c3-da62c22e0b2b.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14289600/192c2142-fb79-11e5-847f-e29f7ad37999.png)

**Comment by willow9886** [comment]
ok, looks good. @yurem can we get this into the 2.4.3 release?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14289618/32f848d0-fb79-11e5-8f48-cb687c775738.png)

**Comment by nynymike** [comment]
@shekhar16 Original ticket was to remove login button, but it's still there.

**Comment by yurem** [comment]
There is no Login button in latest code
