### ISSUE TITLE
More user-friendly look of the OIDC client configuration page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#226]
In CE 2.4.2 the "OpenID Connect -> Clients -> Update/Add Client" page may look somewhat frightening to a new user. There are a whole lot of new properties you can edit using web UI now (which is a good thing), but a user who has just installed Gluu and tries to configure his first OIDC client may easily be lost in this long list of settings with sometimes not very obvious purposes. At the same time, in past times when web UI was offering just a limited subset of settings, configuring OIDC client manually was a joy.

May be it's possible to employ both approaches simultaneously, in a "easy to learn - difficult to master" fashion? Like, present only a limited subset of settings first (the same subset we used in past), and add some "Advanced settings" checkbox which will show a full list of them? Some grouping/categorizing of the settings in "Advanced" mode could help too.

**Comment by willow9886** [comment]
Reference: [https://support.gluu.org/integrations/prepareforstep-not-called-on-step-2-2596#at9448](https://support.gluu.org/integrations/prepareforstep-not-called-on-step-2-2596#at9448)
