### ISSUE TITLE
feat: oxTrust config API: add OAuth Client Security 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2260]
Currently there are two modes to protect the oxTrust API, "Test Mode" and "UMA Mode". We need to add another mode: "OAuth Mode". In OAuth Mode, the client would authentication with the Client Credential Grant and obtain an access token with the correct scope. Each endpoint/method would have a specific OAuth scope, like `https://gluu.org/oauth/oxtrust/admin.read`, which would enable the client to call the endpoint/method.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/pull/2268

**Comment by shekhar16** [comment]
All the changes are done including swagger documentation annotations.
Closing this Ticket.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/2277
