### ISSUE TITLE
Landing page after 'passwordReminder.htm' 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#227]
'/identity/person/passwordReminder.htm' is the first step of password reset feature. 
![passresetlink](https://cloud.githubusercontent.com/assets/7156097/14187336/1d9f2632-f748-11e5-9ee7-d73038410611.png)

After submitting email_address here in above page, the flow is taking user to oxAuth login page. Can we add one page ( something like below ) which will come after above page? A quick javascript pop up isn't bad as well...

![logoutafterpasswordreset](https://cloud.githubusercontent.com/assets/7156097/14187388/64c2444a-f748-11e5-9c2b-340ae734f9ba.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14935680/dda2a5b4-0ef7-11e6-987b-cb9bc1fb9432.png)

**Comment by shekhar16** [comment]
Fixed.
Commit link : https://github.com/GluuFederation/oxTrust/commit/a59e4d05b361a9453d23caac03640571a61f6fac

**Comment by mzico** [comment]
Beautiful @shekhar16 !! Thank you so much, it's working properly.
