### ISSUE TITLE
Not possible to add a deep link as redirect_uri

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2282]
## Description

Reported by a partner in ticket 11012
When adding a deep link kind of uri (example: `myapp://com.callback`) as redirect_uri for an OIDC client, oxTrust will respond with "The url is malformed" error pop up and will refuse to add it. The code checking for it seems to be embedded in the page itself.

## Steps To Reproduce

1. Log in as admin user
2. Move to `OpenID Connect` > `Clients`
3. Create a client entry, or use an existing one; open it for editing and try to add a uri above as `redirect_uri` (the partner used uri like this `com.okta.dev-55232784:/callback`)

## Expected behavior
oxTrust must allow addition of deep linking redirect_uri-s at least for the "Native" type of client. Though it may be needed to support it for "Web" as well (need to be assessed by somebody with sufficient expertise in mobile app development)

## Actual behavior
The uri is rejected with "The url is malformed" error pop up

**Comment by nynymike** [comment]
Any valid URI should be allowed.  See https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2

**Comment by shekhar16** [comment]
Code merged.
Closing this ticket.
