### ISSUE TITLE
fix: misleading description in cache refresh page

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/oxTrust#2286]
## Describe the issue
The description of the mapping table in the cache refresh menu is misleading. It says “Add source attribute to destination attribute mapping”, which is false. Cache refresh only maps attributes in this table from source to destination **if they have different names**. For example, the following table:
| Source | Destination |
|:-----|:------|
| lastName| lastName |

This is redundant because Cache Refresh already maps attributes with matching names if they exist. The description should be **“Change attribute name from source to destination”**

## Steps To Reproduce
1. Install Gluu server
2. Visit oxTrust, then go to `Configuration` > `Cache Refresh`

## Expected behavior
The description of the mapping table should be  “Change attribute name from source to destination:”

## Actual behavior
The description of the mapping table is “Add source attribute to destination attribute mapping:”

## Screenshots
![image](https://user-images.githubusercontent.com/6601566/208486386-faec953b-67e8-4ca0-a94b-4ca1f6077fda.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 20.04 VM

**Comment by shekhar16** [comment]
the code has been merged. closing this ticket.
