### ISSUE TITLE
Object is missing the required property 'mode' in JSON Configuration

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#229]
The following line is shown in the JSON Configuration in red.]
     Object is missing the required property 'mode'
![error-oxtrust](https://cloud.githubusercontent.com/assets/7703245/14397867/e25c4ee0-fe01-11e5-97d4-406f300d4eb4.png)

**Comment by yurem** [comment]
Also there are few missing oxtrust json schema definitions
![screenshot_1](https://cloud.githubusercontent.com/assets/6104200/14427468/9d5782b2-fffd-11e5-8ff9-8761065d3b14.png)

**Comment by yurem** [comment]
Fixed
