### ISSUE TITLE
It's hard to browse list of OIDC scopes when configuring client's properties, it's cluttered too much and not organized enough

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2295]
## Issue description
When choosing which scope to allow to be used by a certain OIDC client, all interactions will happen through a pop-up dialogue window. In its current state it's a huge list of pre-packaged scopes (dozens of items) with little organization and tools to speed up the selection. Please see the example screenshot below.

Most of these scopes are rarely used, and clutter the screen while making it harder to quickly find and select a few most usable ones (like profile, email, username etc). This is an usability issue.

![scope_selection_for_client](https://user-images.githubusercontent.com/11802046/212198635-165041cb-4c49-4be4-a8d9-60287a67bdc4.png)

## Expected behavior

A few suggestions how to alleviate this issue:

1. Add a search control to this pop-up, similar to the one we already have in pop up that allows you to add claims to a scope at "OpenID Connect" > "Add Scope" page
2. Add a few pre-defined filter buttons to pop-up which would show/hide scopes of certain type (at least one button that would, when clicked, leave only the standard, most usable scopes in the list; then may be a button for custom scopes created by user, for dynamic scopes etc)
3. Implement a more reasonable ordering strategy to this list, moving more "popular" scopes higher in the list, with "openid", "email", "username" etc core scopes at the top of it.

Any of 3 can be combined, but I would prioritize the number 1 over the other two. Perhaps items 1 and 2 combined would be enough to deal with the issue.

**Comment by shekhar16** [comment]
Added search box to filter the scopes on add and update client's page.
here is the screenshot.
![image](https://user-images.githubusercontent.com/15937500/216891454-0b2d2f33-15de-4aed-9bda-2ecaeb13c031.png)
