### ISSUE TITLE
OpenID Connect Client auto selected

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#230]
![error-menu](https://cloud.githubusercontent.com/assets/7703245/14400346/876940b2-fe18-11e5-9009-6b6357a5e97a.png)

**Comment by willow9886** [comment]
@zamilskhan can you provide some more context on this issue? What is happening VS. what is happening?

**Comment by zamilskhan** [comment]
@willow9886 the menu shows two items selected, and even in home page the `Clients` stays selected as you can see in the screenshot above. When I took that screenshot, I was in the `manage custom script` page and only that was supposed to be highlighted.

**Comment by yurem** [comment]
Fixed
