### ISSUE TITLE
Cache Refresh configuration page can't be accessed

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#231]
Environment:
gluu-server-2.4.3-2-beta2 deb CE package

Steps to reproduce:
1. Log in to web UI as admin user
2. Click the "Configuration->Cache refresh" link in accordion menu

Result:
User is redirected to the home page and "System error.." message is displayed and
` "javax.el.ELException: //localhost/identity/WEB-INF/incl/organization/cacheRefreshForm.xhtml @58,122 rendered="#{!_configureCacheRefreshAction.appliance.useDefaultCacheRefreshInumServer}": Error reading 'useDefaultCacheRefreshInumServer' on type org.gluu.oxtrust.model.GluuAppliance"`
entry appears in the wrapper.log. Here is a full java error trace from there: [link](https://github.com/GluuFederation/oxTrust/files/217663/cr-trace.txt)

**Comment by yurem** [comment]
Fixed
