### ISSUE TITLE
User self-registration page doesn't seem to enforce custom validation rules for attributes

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2311]
## Description
When user self-registration is enabled, and "Regex Pattern" is set for "Password" attribute, upon user's self-enrolment it doesn't seem like oxTrust actually enforces the regex rules.
Setting high priority for this one as it's related to another issue reported by a customer which they insist disrupting their workflows.

## Steps To Reproduce
1. Login to oxTrust
2. Make sure self-registration is enabled, as described [here](https://gluu.org/docs/gluu-server/4.4/user-management/user-registration/) (email confirmation isn't needed for this test)
3. Move to "Attributes" page
4. Edit attribute "Password" by adding next regex as "Regex pattern" property: `^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;'.,?/*~$^+=<>]).{8,32}$`
5. In a separate incognito window go to `/identity/register.htm` path at this Gluu Server
6. Fill all the fields, while providing `1q2w3e4r` for "Password" field and its confirmation
7. Finish registration

## Expected behavior
As the `1q2w3e4r` string doesn't conform to the rule enforced by the regex above, the user creation should fail (at least), but better the page should notify them which field they filled wrong, and allow them to correct themselves. This must work as such for all attributes for which custom validation rules are enabled

## Actual behavior
User creation is successful, user is persisted to the database - though it's not clear what is used as password, but at least you can't login using this password with this user

**Comment by shekhar16** [comment]
Fixed, below is the screenshot.

![image](https://user-images.githubusercontent.com/15937500/236320352-98d07b1a-232f-4142-9c4f-b92f6f95f0e8.png)
