### ISSUE TITLE
Feat: New configuration parameters

### ISSUE THREAD

**Issue by Milton-Ch** [GluuFederation/oxTrust#2313]
Two new configuration parameters must be added.

The parameters are as follows:
1. `return200OnClientRegistration`: boolean type.
2. `dateFormatterPatterns`: Object that has internally, dynamic fields, to configure the date patterns:
Example:
```
"dateFormatterPatterns": {
    "birthdate": "yyyy-MM-dd"
},
```

**Comment by shekhar16** [comment]
@Milton-Ch where do you want to add these configuration. in oxtrustConfApplication ?

**Comment by shekhar16** [comment]
Code has been merged, below is the screenshot of newly added field.
![image](https://github.com/user-attachments/assets/6fb2155e-6bfe-488d-a19e-ad5d31d55607)


Closing this ticket, let me know if anything needed.
