### ISSUE TITLE
Formatting for Configure Relying Party

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#232]
This modal window is too small in the SAML Trust Relationship form (all the options for the SAML2 SSO Profile):

![image](https://cloud.githubusercontent.com/assets/3717101/14508018/2bd42f66-018b-11e6-8533-94ba37915650.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by willow9886** [comment]
@shekhar16 can you upload screenshots to show your fixes?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14611187/9bd87804-05ae-11e6-90e7-010176a76aff.png)
