### ISSUE TITLE
oxTrust won't allow to set several postlogout redirect uris for OIDC client

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2321]
![image](https://user-images.githubusercontent.com/3717101/228893604-cf6bf98e-29f5-46c9-a0ca-23fec1ce6ef0.png)

Both `Front Channel Logut URI` and `Back Channel Logout URI` need to be multi-value. This was a mistake in the orignal spec... 

![image](https://user-images.githubusercontent.com/3717101/228894217-413e9719-b1d1-4f77-a3bf-67d7cc098359.png)

**Comment by nynymike** [comment]
https://github.com/GluuFederation/oxTrust/commit/2fd87c2aa3759cf7005b2af85ef9f4b5d5e8f7c8

**Comment by shekhar16** [comment]
closing this ticket as the code has been merged. Please let me if any issue found.

**Comment by kristmartin** [comment]
Hi, original issue stated in this ticket's title: "oxTrust won't allow to set several postlogout redirect uris for OIDC client " is still not fixed. And there is no explanation or reasoning why it is not fixed also at that ticket.
Instead under this ticket are fixes (?) to different issues front and back logout URIs and ticket is closed.
Please fix original issue or at least give some reasoning why it is decided not to fix it. 
OpenID Connect spec - https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata , has not changed an states that there can be multiple post logout redirect URIs defined for a client.

**Comment by nynymike** [comment]
It should be fixed in 4.5.1
