### ISSUE TITLE
"Custom scripts" tab of OIDC client properties now displays fewer scripts type, and won't allow multiple similar scripts assigned to a client

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2322]
## Description
Some custom scripts must be assigned to specific client to be executed in the flow that involves it, what is done on "Custom scripts" tab of such client. It makes sense that for a certain client more than one such script may be called (they still have "Level" property which should define in which order the scripts are called by design) - that is how it worked previously. Currently oxTrust won't allow you to assign more than one script of any type to certain client. Moreover, the number of available script types is reduced, compared to the previous versions (see screenshots below).

## Steps To Reproduce
1. Login to oxTrust
2. Make sure you have several scripts of the same category of any type that has to be assigned to specific client to be executed activated on "Configuration" > "Other Custom scripts" page (introspection scripts is a good example)
3. Open any OIDC client's properties on "OpenID Connect" > "Clients" page and move to "Custom scripts" tab there
4. Try to add several scripts to "Introspection Scripts" section

## Expected behavior
It makes sense that for some flows user may need several scripts of the same type to be executed - and it was allowed before. Unless it's a planned change, it may be a bug

## Actual behavior
Scripts are selected from drop-down list now which allows only one choice. I've also noted that even this choice still fails to persist in LDAP db properly 

## Screenshots
![Workspace 1_016](https://user-images.githubusercontent.com/11802046/228385870-257d890d-eff1-4114-8aa3-baa3920cf308.png)
![Selection_014](https://user-images.githubusercontent.com/11802046/228385891-5df3831e-e465-451b-bdf4-756869d0e099.png)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 , unless it's a change already coordinated with @yuriyz , could you please reach to him and make sure both the "one script of a kind for a certain OIDC client" rule and removed sections for RPT Claims Scripts and Consent Gathering Scripts is according to the current design?

**Comment by yuriyz** [comment]
This is bug, we must have RPT Claims and Consent Gathering scripts. And yes, it must be multi-valued.

**Comment by nynymike** [comment]
Unless we have a customer who needs multiple scripts, I think we should leave it one script for clarity.
