### ISSUE TITLE
oxTrust incorrectly references default auth method from OIDC client's properties

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2323]
## Description
When a default authentication script is set for some OIDC client in oxTrust, it's the script's inum what is now written to "oxAuthDefaultAcrValues" attribute of the script's DB entry - but while serving OIDC flows oxAuth still seem to try to look up the script as if it was its acr_value (display name)

## Steps To Reproduce
1. Enable "basic" authentication script
2. Set it as a default acr for some OIDC client
3. Make sure no other auth method may take precedence for this client
4. Start the flow for the client without specifying which acr to use explicitly
5. Check the client's DB entry's "oxAuthDefaultAcrValues" attribute

## Expected behavior
Unless any override happens oxAuth engages the script set as default acr for the client

## Actual behavior
Flow fails with an error page. In oxauth.log next lines appear:
```
2023-03-28 17:13:31,909 ERROR [qtp902478634-15] [gluu.oxauth.authorize.ws.rs.AuthorizeAction] (AuthorizeAction.java:285) - Failed to get CustomScriptConfiguration. auth_step: 1, acr_values: A51E-76DA
2023-03-28 17:13:31,909 TRACE [qtp902478634-15] [org.gluu.oxauth.service.AuthorizeService] (AuthorizeService.java:184) - permissionDenied
```
When client's DB entry is displayed, you can notice that "oxAuthDefaultAcrValues" attribute contains `inum` of the script set as default, the same that appears in the logged error above.

According to @yuriyz this is 100% oxTrust issue and the script must be referenced by its name, not by its inum or DN.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 , please treat it as a high priority issue, we have an outstanding customer complaint about this

**Comment by shekhar16** [comment]
closing this ticket as the code has been merged. Please let me if any issue found.
