### ISSUE TITLE
Unable to create custom attribute in 2.4.3 beta4

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#233]
Creating custom attribute with oxTrust is not happening. I went to create a custom attribute named 'myattribute' and it's throwing error: http://pastebin.com/JVPZNGKR

**Comment by yurem** [comment]
It's related to OpenDJ 3.

I added fix. Now ShemaService do next:
1) Remove custom OC from cn=schema
2) Add custom OC to cn=schema

@nynymike Is it right approach to change custom OC ?

With OpenDJ 2.6.0 workflow was the next:
1) Add OC to cn=schema

We always used add ldap method. And OpenDJ do replace of custom OC.

**Comment by nynymike** [comment]
I think it's fine, but you may want to backup the ldif of the old schema (write it to the logs) just in case you need to restore it.

**Comment by mzico** [comment]
@yurem : I can see this error again in 2.4.3 final version

**Comment by aliaksander-samuseu** [comment]
@mzico @yurem 
Can't confirm it for 2.4.1-1-3 deb package. Has it been fixed?

**Comment by mzico** [comment]
@aliaksander-samuseu : I couldn't reproduce the problem either. What I can see... I have 2.4.3 snapshot identity war here. I'll test with 2.4.3 final again. Closing the issue.

**Comment by yurem** [comment]
I've fixed add/remove custom attributes in 2.4.3 Fix is part of final build
