### ISSUE TITLE
'Test LDAP Connection' of 'Manage Authentication' is not working properly

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#234]
'Test LDAP Connection' is unable to validate the correct setting. Though the backend information is correct and after saving this LDAP connection is working properly for authentication but still 'Test LDAP Connection' is throwing 'failed to connect' message. Stack trace: http://pastebin.com/z20bV724

How to reproduce the issue: 

- Complete CR 
- Make sure you are able to connect backend server with ldapsearch,telnet
- Provide backend info in 'Manage Authentication' section. 
- Hit 'Test LDAP Connection'
- You will see below message in oxTrust and upper stack trace in oxtrust.log

![failed_to_connect_ldap_server](https://cloud.githubusercontent.com/assets/7156097/14631628/f398601a-05d9-11e6-867e-0d3394c56eb4.png)

**Comment by aveekbu** [comment]
attached the log with the ticket; if pastebin erase the log after certain period of time. 
[oxtrust_log.txt](https://github.com/GluuFederation/oxTrust/files/227614/oxtrust_log.txt)

**Comment by aliaksander-samuseu** [comment]
Quick note: Wireshark showed that no LDAP traffic appears on the wire when the button is clicked, it seems it fails before any connection to backend is attempted.

**Comment by shekhar16** [comment]
Fixed .

**Comment by mzico** [comment]
Thanks @shekhar16 . It's working properly.
