### ISSUE TITLE
bug: Password reset page showing success even when passwords mismatching

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2343]
oxTrust password reset page: `https://<hostname>/identity/resetPassword.htm?guid=d7sr9o5w0082zjql` [ Generate and sent to email ] is landing to "Password change successfully" ( `https://<hostname>/identity/passwordResetResult.htm` ) page even when passwords are not matching. 

Target is: if passwords doesn't match, user should be stayed on same page rather than landing to false "Successful" page. 

Here is the whole recorded GIF, here you can see "Password" and "Confirm Password" are clearly different but still it's showing false "Success" page. 

![Wrong_password_panel](https://github.com/GluuFederation/oxTrust/assets/7156097/badc8c00-9af1-4a47-a675-40dbed4d8d41)

**Comment by imShakil** [comment]
I tried to look into it. It seems this [redirect](https://github.com/GluuFederation/oxTrust/blob/0bb9a5a2911d62a4c63319c563da4257d54ef2aa/server/src/main/java/org/gluu/oxtrust/action/PasswordResetAction.java#L182) should be happened inside if clause.
