### ISSUE TITLE
feat: Add MAU Report to oxTrust

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2346]
![image](https://github.com/GluuFederation/oxTrust/assets/3717101/560e9a08-8e7e-4e63-99b8-b4623481ff9a)

We use MAU for billing, so it would be great if there was a report that showed monthly MAU back the preceding 12 months.
This information is provided in the `/internal/stat` endpoint of oxAuth. 

For billing, we need to see a report like this:

For example:

```
Jan 5500
Feb 2345
Mar 8963
Apr 3453
May 16344
Jun 2435
Jul 6634
Aug 2211
Sep 5346
Oct 9087
Nov 7869
Dec 11292

Avg 6432
Max 16344
```

**Comment by nynymike** [comment]
There is a MAU exporter script 
https://github.com/GluuFederation/docs-gluu-server-prod/blob/2c2df5e1f3a7a839c0636bdda064c49d48ec0d33/docs/source/operation/stat-exporter.md#L16-L15

**Comment by shekhar16** [comment]
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/fe80b5cd-7b93-482d-bae8-ed80e2270fbc)

**Comment by shekhar16** [comment]
added functionality and code is merged.
Closing this ticket, if needed please let me know :).
