### ISSUE TITLE
Add GUI to properly render NameID

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#235]
We need a GUI element to manage NameID. It shouldn't be necessary to do this in the velocity template.
https://ox.gluu.org/doku.php?id=ce:custom_nameid 

Normally nameid format is chosen based on the order listed in SP metadata. It would also be convenient to allow the admin to specify a nameid in the relying party congifuration, which can be done with the attribute [nameIDFormatPrecedence](https://wiki.shibboleth.net/confluence/display/SHIB2/IdPRelyingParty)

This should be done as part of the Shib 3 update.

**Comment by zeroluck** [comment]
Thank you! This documentation looks like something I can actually figure out! The differences between oxShibboleth and Shibboleth with the velocity templates and other ways of dealing with custom attributes have made it very difficult for me to get past the NameID part of our SSO integration. Adding this functionality to the GUI would be even better.

**Comment by aliaksander-samuseu** [comment]
@nynymike @dmogn 
We also have this old [report](https://github.com/GluuFederation/oxTrust/issues/113) on the same issue.

**Comment by dmogn** [comment]
@aliaksander-samuseu
Ok, thanks!

**Comment by nynymike** [comment]
duplicate #274
