### ISSUE TITLE
fix(oxTrust): regex pattern not working for `addUser` form in `oxTrust` admin UI (gluu-4.2.3)

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxTrust#2357]
## Describe the issue
Target [ticket](https://support.gluu.org/customization/11378/email-validation-failed-when-symbol-is-included-in-the-mail-test1test2usernamecevalogisticscom/#at84660).

In mail attribute, regex pattern should work for `addUser` form in `oxTrust` admin UI.

## Steps To Reproduce
1. add a regex pattern like `^[a-zA-Z0-9+&*-]+(?:.[a-zA-Z0-9+&-]+)@(?:[a-zA-Z0-9-]+.)+[a-zA-Z]{2,7}$` for mail validation.
2. create user with mail like `test1.test2+username@xyz.com`
4. See mail validation error in oxTrust admin ui 

## Expected behavior
This validation should work for gluu-4.2.3

## Actual behavior
Showing validation error.

## Screenshots
<img width="366" alt="validation-error" src="https://github.com/GluuFederation/oxTrust/assets/43112579/031504dd-be8e-49b6-bdec-10d9e9ef3889">

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu20.04LTS]
 - Gluu version(4.2.3)

**Comment by mmrraju** [comment]
@shekhar16 could you please see it?

**Comment by shekhar16** [comment]
its working as expected confirmed by @mmrraju .
closing this ticket.
