### ISSUE TITLE
Organization favicon image couldn't be uploaded

### ISSUE THREAD

**Issue by aveekbu** [GluuFederation/oxTrust#236]
While trying to update Organization favicon image through admin UI -> organization configuration -> oxTrust Settings; I've found the following error from /opt/tomcat/log/wrapper.log

system info:
CentOS release 6.7 (Final)
gluu-server-2.4.3-1-1.centos6.x86_64

`INFO   | jvm 1    | 2016/04/20 08:38:11 | 2016-04-20 08:38:11,882 ERROR [org.gluu.oxtrust.servlet.FaviconImageServlet] Organization favicon image doesn't exist
INFO   | jvm 1    | 2016/04/20 08:38:11 | java.io.FileNotFoundException: File '/var/ox/photos/source/null' does not exist
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.gluu.oxtrust.servlet.FaviconImageServlet.doGet(FaviconImageServlet.java:80)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.ContextFilter$1.process(ContextFilter.java:42)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.web.ContextFilter.doFilter(ContextFilter.java:37)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
INFO   | jvm 1    | 2016/04/20 08:38:11 |   at java.lang.Thread.run(Thread.java:745)
`

**Comment by shekhar16** [comment]
Fixed.

**Comment by willow9886** [comment]
@aveekbu can you please test and confirm? If it's good, close this issue.
