### ISSUE TITLE
Change welcome message from "you successfully register, enjoy" to "you've successfully created your account, please go to you email to successfully register your account.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2363]
![Screenshot from 2023-08-15 11-38-29](https://github.com/GluuFederation/oxTrust/assets/34593983/9fb6f47a-8fa5-4798-b7ff-569d5703a545)
Currently  on registering a user va register.htm, we get welcome message like you are successfully registerd, enjoy,  however the user is not verified in this state hence user is inactive till user confirm his email to active account. so can we change the message to you've successfully created your account, please go to you email to successfully register your account.

**Comment by shekhar16** [comment]
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/33fbab1a-be10-45b9-9585-57ba2a0ba4f8)
