### ISSUE TITLE
Create button to enable default scope in add scope UI.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2364]
As of now there is no option available to set default scope in add scope UI  in gluu-server 4.5.x (can be done via backend).

**Comment by shekhar16** [comment]
HI @MohitMaliFtechiz 

we have default scope checkbox on ui with the name of "Allow for dynamic registration:"


![image](https://github.com/GluuFederation/oxTrust/assets/15937500/1c5c2123-e92b-4b16-a9aa-22ecb504b429)
