### ISSUE TITLE
feat: Add Search Field for Scopes Selection in OpenID Client

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2371]
![image](https://github.com/GluuFederation/oxTrust/assets/3717101/dd058bad-a5e4-40a7-8215-a7903e2ef2fb)

There can be a lot of scopes... there should a field to filter them.

**Comment by shekhar16** [comment]
This was fixed in ticket https://github.com/GluuFederation/oxTrust/issues/2295
But looks like code was removed in other commits.
Fixed it again in 4.5.2 , its already present in 4.6.0
.

**Comment by shekhar16** [comment]
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/82389ee2-60ba-40aa-b47b-c568a20e7465)

**Comment by shekhar16** [comment]
cloing this ticket as its fixed in both branch
