### ISSUE TITLE
Remove Trusted IDP form in SAML  on admin UI   

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2372]
## Describe the issue
Remove Trusted IDP form in SAML  on admin UI 

![Screenshot from 2023-09-20 23-11-33](https://github.com/GluuFederation/oxTrust/assets/34593983/df7fef72-dfda-4a1e-a705-f53f627cf9ad)

as discussed with mike, Trusted Idp form needs to be removed.  

Gluu-version 4.5.2

**Comment by shekhar16** [comment]
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/e3e8d1e4-ee03-4cea-a185-7be58f9a4fba)

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  the issue is fixed. please let me know if anything needed on this.
