### ISSUE TITLE
fix(Cache refresh): Cache Refresh tries to add New Entry Instead of Updating

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxTrust#2377]
## Describe the issue
Target [ticket-11510](https://support.gluu.org/cache-refresh/11510/cache-refresh-adding-new-entry-instead-of-updating/)

We are encountering an issue with Cache Refresh where instead of updating existing entries in the Gluu LDAP, it is attempting to create a new entry.

## Steps To Reproduce
At my gluu server ldap I've an user 'abc', in remote source there have also user `abc`. So when I activate Cache Refresh  it's sync but problem is, its' try to add new entries instead of updating [code snipet](https://github.com/GluuFederation/oxTrust/blob/4f6ab8465829f64f8b810ef57d4689ad871ca461/server/src/main/java/org/gluu/oxtrust/ldap/cache/service/CacheRefreshTimer.java#L753C77-L753C87). And getting error, screenshot attached.

## Screenshots
![Screenshot from 2023-10-14 00-19-51](https://github.com/GluuFederation/oxTrust/assets/43112579/d9d712bb-d7bc-4967-bba0-3c586adbce93)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu20.04LTS]
 - Gluu version(4.4.2.final, 4.5.1.final)

**Comment by nynymike** [comment]
This is a corner case: the entry should not exist already if we're specifying an external LDAP server as the source. If we address this, it needs to be a feature flag controlled, for example `cache_refresh_update_user_if_present` .

**Comment by yurem** [comment]
Can you try to specify in CacheRefresh configuration: `"keepExternalPerson":false,` By [default](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxtrust/oxtrust-cache-refresh.json#L33) it's `true`?

**Comment by mmrraju** [comment]
@yurem `"keepExternalPerson":false` its' remove our existing user on first cycle. Following [this docs](https://gluu.org/docs/gluu-server/4.4/user-management/ldap-sync/#things-to-remember).

**Comment by yurem** [comment]
yes, this will remove existing user and copy new one from server.

The main questions with user `abc` are:
1. We don't know how to map external user from AD to local one. The explanation is below.
2. How often we will use this in future?
3. Why we can't do sync and add required changes to user entry after that?

On CR sync it stores in o=site information about primaryKey/secondaryKey/tertiaryKey (from AD) and primaryKeyAttrName.
As result how to map automatically without o=site entry? We need to restore from local user `abc` entry AD primaryKey[/secondaryKey/tertiaryKey].

From my point of view we need to remove conflicted entries from local DB before inserting new user `abc`. This makes flow more clear.

@mzico Do you remember if there are environments where we pre add to local LDAP generic users (not admin) before sync?

**Comment by nynymike** [comment]
I don't think this is a bug--it's working as advertised. If `keepExternalPerson` is false, it removes the user. If `keepExternalPerson` is true, it is undefined. We should just update the docs here. Cache Refresh is a "lightweight" sync process, not intended to be a two-way sync process. You are supposed to define one authoratitive source. If you do have external users, it's your responsibility to make sure there is no collission with a primary key in your target ldap server.

**Comment by Humangoku** [comment]
.
