### ISSUE TITLE
feat: sync gluuStatus with oxTrustActive attribute

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#2378]
In the user's form, whenever the gluuStatus attribute is updated, the oxTrustActive attribute should reflect the same value:

If gluuStatus was set to `active`, set oxTrustActive to `true`
otherwise set  oxTrustActive to `false`

some context in ticket 11518

**Comment by shekhar16** [comment]
what we can do if user wants to set gluuStatus = inactive and oxTrustActive =  true
Check below screenshot.

![image](https://github.com/GluuFederation/oxTrust/assets/15937500/eedda42f-72c2-4f85-a6a5-73f661657810)

**Comment by shekhar16** [comment]
closing this ticket.
