### ISSUE TITLE
Wrong button caption for adding Redirect Logout URI

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2389]
In OIDC client's properties, on "Logout" tab, we have property called "Redirect Logout URIs". But its related button reads "Add Post Logout redirect URI". One of these captions isn't correct, apparently, but not sure which one. May be @yuriyz will be able to suggest.

![07 11](https://github.com/GluuFederation/oxTrust/assets/11802046/2e08c8d1-6b8c-46a5-a4bd-6947cc622b58)

**Comment by yuriyz** [comment]
Caption should be "Post Logout Redirect URIs".

**Comment by shekhar16** [comment]
in 4.5.3 and 4.5.4 its already "Post Logout Redirect URIs"
 
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/9e21b62d-b6bb-4bc6-b16b-dbd94c7398a7)

**Comment by shekhar16** [comment]
closing this ticket. Please verify and let me know if found anything wrong.
