### ISSUE TITLE
SCIM Test Mode

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#239]
We need to add a feature called something like "test-mode" that uses a static oauth2 token to enable access to the SCIM API's instead of requiring UMA. This feature should be a configuration property. The purpose of this feature is to facilitate the SCIM interop testing process.

**Comment by yurem** [comment]
We can configure oxTrust in next way -Dgluu.test.scim.uma.rpt=dummy_rpt

oxTrust we can update to check if this param exists. If it exists it should use specified dummy_rpt to check if client has access or not.

**Comment by uboznikov** [comment]
The current implementation is I have put the configuration in oxTrust; basically if scimTestMode = true it will generate a long-lived access token (1-year expiry) which can then be distributed to clients. Likewise oxTrust will only authorize using OAuth2 if scimTestMode = true; if false, it will fallback to UMA.

![testmode](https://cloud.githubusercontent.com/assets/16329085/14893184/e9204444-0da0-11e6-8073-ec02f359f075.png)

**Comment by uboznikov** [comment]
Enhancement committed to Git.

**Comment by gengstah** [comment]
Sir Val?
