### ISSUE TITLE
feat(passport): update passport-saml to @node-saml/passport-saml 

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/oxTrust#2392]
## Describe the issue
Update value in strategy dropdown `passport-saml` to `@node-saml/passport-saml`

## Screenshots
![Clipboard - November 23, 2023 10_10 PM](https://github.com/GluuFederation/oxTrust/assets/39133739/bb0bfc72-0ed1-4667-b5f2-630ca7b84901)

**Comment by shekhar16** [comment]
Ji @kdhttps 
I have Fixed it and raised PR for 4.5.3 and master too
Below is the screenshot

![image](https://github.com/GluuFederation/oxTrust/assets/15937500/32411a79-9146-49da-8dd0-9bf9089760f5)

**Comment by shekhar16** [comment]
closing this issue.
