### ISSUE TITLE
On client registration page it is not possible to set/change client_secret_expires_at property

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#241]
It would be nice to get ability to change  client_secret_expires_at property via GUI and avoid oxauth client clean up for dynamically registered clients if their default expiration time is small..

https://gluu.org/docs/integrate/openid-connect/#client-registration

    @LdapAttribute(name = "oxAuthClientSecretExpiresAt")
    private Date clientSecretExpiresAt;

**Comment by yuriyz** [comment]
marked it as high priority since oxd libs devs often asks about it. (@ldeveloperl1985, @dollar007 , @tecoholic)

**Comment by shekhar16** [comment]
Fixed.

**Comment by yuriyz** [comment]
@dollar007 would u please validate it? You've requested it many times.
