### ISSUE TITLE
Post logout URI is not case sensitive.

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxTrust#2412]
## Describe the issue
Target [Ticket-11590](https://support.gluu.org/single-sign-on/11590/logout-uris-which-differ-only-by-letter-case-cannot-be-stored-in-gluu-admin-gui/)

We’re not able to register multiple URLs in oxTrust (Gluu Admin GUI), which only differ with some characters being lower or upper case.

## Steps To Reproduce
1. Go to Admin UI
2. Create an oidc client 
3. Add `Post Logout Redirect URI` 1. `https://localhost:8443/test_logout` 2. `https://localhost:8443/Test_logout`
4. Now save and update.
5. Reload the browser then you will see only `https://localhost:8443/test_logout`

## Expected behavior
It's should be case sensitive. And we should see both of `Post Logout Redirect URI`.

## Actual behavior
It's not case sensitive.

## Desktop (please complete the following information):
 - OS: `[ Ubuntu20.04LTS]`
 - Gluu Version `4.5.3.final`

**Comment by yuriyz** [comment]
default definition is 
```
 {
            "desc": "oxAuth Post Logout Redirect URI",
            "equality": "caseIgnoreMatch",
            "names": [
                "oxAuthPostLogoutRedirectURI"
            ],
            "multivalued": true,
            "oid": "oxAttribute",
            "substr": "caseIgnoreSubstringsMatch",
            "syntax": "1.3.6.1.4.1.1466.115.121.1.15",
            "x_origin": "Gluu created attribute"
        },
```
you need to change `caseIgnoreMatch` to `caseExactMatch`

**Comment by mmrraju** [comment]
![Screenshot from 2023-12-29 05-17-24](https://github.com/GluuFederation/oxTrust/assets/43112579/d2217ce9-33f9-4e25-bb80-ebadef285dcc)


I've changed it but not resolved.

**Comment by yuriyz** [comment]
Then it seems to be UI issue. Assigning it to @shekhar16 .

**Comment by shekhar16** [comment]
Thanks @yuriyz for above comments.
@mmrraju i changed the the definition and its working for me.
here is the screenshot.
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/07348105-2e92-4038-b30a-5bade3760728)



Please restart the ldap so that it will reload the definition.

**Comment by shekhar16** [comment]
@yuriyz  do we need to make this changes in setup also or it client specific change.

**Comment by mmrraju** [comment]
@shekhar16  thanks it's working.

**Comment by yuriyz** [comment]
I guess we don't need to change anything else. It's customer specific request.

**Comment by shekhar16** [comment]
Thanks @yuriyz .
Closing this ticket.
