### ISSUE TITLE
"Multivalue" option is not operational

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2413]
I am unable to use "Multivalued" option in Attribute section. It's not working. 
![Screenshot from 2024-02-01 11-03-07](https://github.com/GluuFederation/oxTrust/assets/7156097/51ebbd33-aee0-46a5-aff7-fbd1b44ffb5b)

**Comment by shekhar16** [comment]
@mzico  not able to reproduced it with version 4.5.1.
Please check below screenshot.
![image](https://github.com/GluuFederation/oxTrust/assets/15937500/6d7e9875-b96a-43a6-8dbd-2ca82a41018b)

**Comment by shekhar16** [comment]
Closing this ticket. please let me know if anything you found.
