### ISSUE TITLE
oxtrust shows old passport strategy name by default

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/oxTrust#2425]
# Error looks like this

<img width="1240" alt="Screenshot 2024-06-14 at 11 21 16" src="https://github.com/GluuFederation/oxTrust/assets/20867846/244b8128-4cd5-41a2-8db8-aa08287ad97d">

## Configuration

- Gluu Server 4.5.3
- OS: Ubunto 20

**Comment by shekhar16** [comment]
@imShakil  I think this issue is fixed as part of ticket : https://github.com/GluuFederation/gluu4/issues/4
here are more details 
https://github.com/GluuFederation/gluu4/pull/7

Please check and let me know if anything needed.

**Comment by imShakil** [comment]
Hi @shekhar16 

Yes, I have tested on 4.5.6. It's fixed now. I am closing the issue.
