### ISSUE TITLE
feat(oxTrust): add missing option to fido2 schema file

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#2426]
[fido2-config.json](https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/fido2-config.json) is out of date. We need to add missing options to it from [AppConfiguration.java](https://github.com/GluuFederation/fido2/blob/master/model/src/main/java/org/gluu/fido2/model/conf/AppConfiguration.java). Sample [configuration](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/fido2/dynamic-conf.json) there is in setup.

**Comment by shekhar16** [comment]
Code has merged, closing the ticket.
please let me know if any issue found.
