### ISSUE TITLE
Blank page after log in if client is trusted client

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#243]
We get this on ltest code on ce-dev2:

![invliad_redirect](https://cloud.githubusercontent.com/assets/6104200/15014296/e7121030-120d-11e6-9685-0338e685948e.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15090228/e8108304-143d-11e6-8be4-390c355f160d.png)

**Comment by shekhar16** [comment]
@yurem i m successfully logged in .
as user is trusted client we have to logged in directly without opening consent page .

**Comment by aliaksander-samuseu** [comment]
@yurem @shekhar16 
I'm also unable to reproduce this. When trusted client flag is true I'm able to access web UI without being asked for consent at all.
Could you recheck your steps, mb something you are doing but not mentioning triggers this bug?

**Comment by shekhar16** [comment]
@aliaksander-samuseu as per your comment in chart mentioned  in issue
https://github.com/GluuFederation/oxTrust/issues/206
"it should not ask for consent at all when "pre-authorization" is set to true".
this right.

**Comment by yurem** [comment]
I fixed it already. The problematic code were:
https://github.com/GluuFederation/oxAuth/commit/0c145b1d875f1cbd7f6461f0871b066d6b06add7

As result it showed blank page... without redirect user to right place. In this and in few next commits I fixed logic.
Closing this issue.
