### ISSUE TITLE
bug(oxtrust): failed to remove memberof attribute from user entry if DB is PostgreSQL

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#2439]
When user remove `memberOf` attribute from user entry oxTrust add custom attribute `memberof` with empty array value. PostgreSQL is sensitive to case in attribute name. As result Db throws exception.

Version: Gluu CE 4.5.5 + PGSQL

Here is data from debugger:
![изображение](https://github.com/user-attachments/assets/c5d925b4-5ba9-4b3c-997b-6bc6ba4a0940)
[exception.txt](https://github.com/user-attachments/files/17318233/exception.txt)

**Comment by shekhar16** [comment]
changes are done and its working as expected, Let me know if anybody found any new issues.
Closing this ticket.
