### ISSUE TITLE
Use specific LDAP certificate or cacert to connect remote LDAP server

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#244]
In our LDAP connection code there is line:
https://github.com/GluuFederation/oxCore/blob/master/oxLdap/src/main/java/org/gluu/site/ldap/LDAPConnectionProvider.java#L106

It's not big security issue if all parts inside one VM or in corporation's network. But for AD server it's problem.

What is better:
1. Use java cacerts ? In order to access AD server admin should import SSL cert into cacerts. Right now it's our main approach.
2. Use specific certificate to connect AD server. In other words LDAP connection code should loads it from string parameter or from FS.

**Comment by yurem** [comment]
@nynymike Which approach is better now?

**Comment by mzico** [comment]
@yurem : Here is my two cents.... I think #2 is better because, it will serve the purpose and if remote AD upgrade their cert, it won't be much difficult to make it okay inside Gluu Server as well.

**Comment by yurem** [comment]
I vote for solution #2 too. It's easier replace file than update cert in cacert

**Comment by yurem** [comment]
I added new properties to [ox-ldap.properties](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/ox-ldap.properties#L6).
```
ssl.trustStoreFile: %(certFolder)s/openldap.pkcs12
ssl.trustStorePin: %(encoded_openldapJksPass)s
ssl.trustStoreFormat: pkcs12
```

Setup fill these properties during install.

Also for compatibility purposes if `ssl.trustStoreFile` or `ssl.trustStorePin` are empty oxLdap uses trust all trust manager as before. we will remove this in 3.2.0 completely: https://github.com/GluuFederation/oxTrust/issues/641

**Comment by yurem** [comment]
@jschristie can you add note to 3.1.0 docs about these 3 new ox-ldap.properties?
