### ISSUE TITLE
Encrypt password attributes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#245]
it's issue related to:
https://github.com/GluuFederation/community-edition-setup/issues/127

On user profile we should display input field with imapPassword. It's not problem, we don't need to show password from LDAP but in LDAP we should store it in encrypt format.
Which salt to use in this case?

The problem is bigger because oxAuth should return imapPassword as claim to php application which uses oxd. How it should encrypt this password?

What do you think about adding encription_key parameter to site registration oxd call? As result oxd will store it in some place.

**Comment by yurem** [comment]
Another problem is that oxTrust should know which attributes are password fileds. We can add fla to attribute entry to specify this.

And third problem how to specify that oxTrust shuld use specific encription_key to encrupt password filed?

**Comment by yurem** [comment]
@nynymike , @yuriyz , @dollar007

**Comment by nynymike** [comment]
The IMAP password may be different from the LDAP password. I think we should define a user claim called gluuImapCreds which contains a JSON:

```
{
 "imapusername": "foobar@acme.com",
 "imaphost": "mail.acme.com",
 "imapport": "993",
 "useSSL": "true",
 "imapPassword": {encryptedString: "XBik468/7YKd4jN84scIH+x5hw==", 
                              "cipher": "blowfish",
                              "mode": "CTR"
}

```

There is a good online [tool](http://codebeautify.org/encrypt-decrypt) I found which has a number of two-way encryption algorithms.  We need to find an algorithm where we have compatible libraries for both Java and php. 

How a user would get these encrypted values into the Gluu Server is currently out of scope for this assignment. When Roundcube is done, we can create an issue on oxTrust to add this enhancement. Or the customer could use SCIM or LDIF to populate the LDAP user attribute.

**Comment by nynymike** [comment]
How a user would get these encrypted values into the Gluu Server is currently out of scope for this assignment. When Roundcube is done, we can pershaps re-open this enhancement. Or the customer could use SCIM or LDIF to populate the LDAP user attribute.
