### ISSUE TITLE
[Users->Manage people] Search form lacks pagination controls

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#246]
Environment: Ubuntu 64bit 14.04.4 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.4.3-1-3

Preconditions:
1. Gluu's internal directory is populated with enough number of user entries crafted in such way that a search string that will be used in a test could possibly return more then 20 entries in response under normal conditions. You may use [attached ldif file](https://github.com/GluuFederation/oxTrust/files/250877/export.zip) with ~4k users. When creating your own keep in mind that feature's search filter checks only uid, mail, iname and displayname attributes, and looks like that: `(&(&(objectclass=top)(objectclass=person))(|(|(|(uid=*search_string*)(mail=*search_string*))(displayname=*search_string*))(iname=*search_string*)))`

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to the "Users->Manage people" page
3. Search for any string that is [theoretically] should return more then 20 user entries (subject to composition of your user pool)
4. Issue command like that from the container to gauge the amount of entries this feature should return: `/opt/opendj/bin/ldapsearch -h 127.0.0.1 -p 1636 -s sub -T -Z -X -D 'cn=directory manager' -w 'SOME_PASS' -b 'o=gluu' '(&(&(objectclass=top)(objectclass=person))(|(|(|(uid=*search_string*)(mail=*search_string*))(displayname=*search_string*))(iname=*search_string*)))' 1.1 | grep -v '^$' | wc -l`

Result:
The search form displays no more than 20 user entries regardless of what search string is used. The same search with ldapsearch tool is capable of returning times more entries. Monitoring tool shows that LDAP search requests generated by web UI include pagedResultControl set to 20 (entries), that explains the upper limit. But the page lacks any means to see entries past the first 20 entries (see picture below)
![pic](https://cloud.githubusercontent.com/assets/11802046/15052533/e35fcfa0-1306-11e6-9c30-b3726a362865.jpg)

Expected result:
Some pagination controls must be present on the page, which supposedly should make use of LDAP search cookie feature to request remaining entries.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15090196/6c75ec2c-143b-11e6-9a12-5e2760493da2.png)

**Comment by shekhar16** [comment]
Fixed.
