### ISSUE TITLE
SCIM RPT validation needs to check permission / expiration

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#250]
oxTrust fetched RPT permissions and if any is present it consider it as success.
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/UmaAuthenticationService.java#L78

However it should check whether RPT has permission for given resourceId and whether it has scope (which present in the method), if not then ticket has to be registered and returned to RP for RPT authorization.

UMA spec: https://docs.kantarainitiative.org/uma/rec-uma-core.html
Docs : https://gluu.org/docs/integrate/uma/

**Comment by yurem** [comment]
We also need to check RPT returned from server to make usre that we get right response.

**Comment by yuriyz** [comment]
During RPT introspection AS returns permissions. RPT must be active and must contain permissions required by RS endpoint.

**Comment by nynymike** [comment]
@uboznikov Can you check that the the RPT is active and the permissions for the SCIM endpoint is there?

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxTrust/blob/2d5e5101d5a897813eaa51e1db6f3378473d0e30/server/src/main/java/org/gluu/oxtrust/service/uma/UmaPermissionService.java#L124
