### ISSUE TITLE
Sync "oxTrustEmail" and "mail" LDAP attributes via SCIM or update from oxTrust GUI

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#251]

**Comment by uboznikov** [comment]
Related: [https://support.gluu.org/identity-management/user-added-but-email-is-empty-and-gluustatus-is-true-instead-of-active-2740](https://support.gluu.org/identity-management/user-added-but-email-is-empty-and-gluustatus-is-true-instead-of-active-2740)

**Comment by nynymike** [comment]
Why do we even have two attributes for email? We should always use standard inetOrgPerson attributes when possible.

**Comment by uboznikov** [comment]
@nynymike As I understand we store the email value in 'mail' as per inetOrgPerson while in 'oxTrustEmail' we should store same email value plus the SCIM metadata.
