### ISSUE TITLE
SCIM v1.x endpoints use SCIM v2.x scheme in response

### ISSUE THREAD

**Issue by stakoz** [GluuFederation/oxTrust#252]
[User](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L104), [Group](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/GroupWebService.java#L77) and [Bulk](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/BulkWebService.java#L330) endpoints for SCIM v1.x are sending schema identifier _urn:scim2:schemas:core:1.0_ in response instead of _urn:scim:schemas:core:1.0_ as per [specification](http://www.simplecloud.info/specs/draft-scim-core-schema-01.html#user-resource).

**Comment by nynymike** [comment]
Val, can you check this?

**Comment by uboznikov** [comment]
Thanks @stakoz, [fix](https://github.com/GluuFederation/oxTrust/commit/5afa8d5662f07ec10903ff239f855c629b79c724) committed.
