### ISSUE TITLE
Support imap attribute type

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#253]
In order to resolve [this ](https://github.com/GluuFederation/community-edition-setup/issues/127) we need to support new attribute type 'imap'. IMAP connection attribute are details in JSON format.

[06.05.2016 13:18:37] Yuriy Movchan: We can define for this attribute type imap
[06.05.2016 13:18:55] Yuriy Movchan: And improve profile page to support this new type
[06.05.2016 13:19:21] Yuriy Movchan: We can display them in one group instead of few attributes in the list now

**Comment by yurem** [comment]
Here is example how we handle photo attributes:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/profile/person/viewProfile.xhtml#L132

In our case we are going to add 'imap' data type. In shows group of fields to allow user enter connection details.

**Comment by nynymike** [comment]
```
gluuIMAPData: {
 "imapusername": "foobar@acme.com",
 "imaphost": "mail.acme.com",
 "imapport": "993",
 "useSSL": "true",
 "imapPassword": {encryptedString: "XBik468/7YKd4jN84scIH+x5hw==", 
                              "cipher": "blowfish",
                              "mode": "CTR"
}
```

**Comment by yurem** [comment]
@shekhar16 I've reviewed this. It expects that there is predefined attribute "gluuIMAPData". Can you update schema in setup to add it? Also we need to add attribute metadata for this attribute:
https://github.com/GluuFederation/community-edition-setup/blob/master/static/opendj/101-ox.ldif
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif

**Comment by shekhar16** [comment]
@yurem files are committed.

**Comment by yurem** [comment]
Can you add links to commits to setup

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/74096d1d54615d07969a6f62a1dc98e7eae053d4
