### ISSUE TITLE
Default Authentication Method is missing Level

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#255]
![default_authn](https://cloud.githubusercontent.com/assets/3717101/15479950/76a203fc-20e8-11e6-8373-1a3ca3db1823.png)

The default authentication method does not allow you to define a "level" like in the custom authn scripts.

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15628694/140cc0c4-2525-11e6-95f1-1e1bc2bf750d.png)

**Comment by mzico** [comment]
@shekhar16 : looks good. Thanks!
