### ISSUE TITLE
Review CopyUtils test

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#256]
Community helped us to cover CopyUtils by tests:
https://github.com/GluuFederation/oxTrust/tree/master/server/src/test/java/org/gluu/oxtrust/util/test

Now we added them to test suite. But it looks like they out of date:
https://ox.gluu.org/jenkins/job/oxTrust/326/

We need to review and enable them:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/test/resources/testng.xml#L33

We also can update them to cover CopyUtils2 instead of CopyUtils.

**Comment by nynymike** [comment]
Is this still relevant?

**Comment by yurem** [comment]
Done: https://github.com/GluuFederation/oxTrust/commit/aa457c8047c8a6a100f623581d023724ee7d176f
