### ISSUE TITLE
Create Interception Script Mechanism for SCIM Update

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#264]
We should add an interception script for SCIM and create different methods for add, delete, modify and password change.

**Comment by uboznikov** [comment]
[https://support.gluu.org/integrations/user-update-script-2791](https://support.gluu.org/integrations/user-update-script-2791)

**Comment by yurem** [comment]
@nynymike, I explained @uboznikov how to do that but we need and example to make sure that I understand main idea correctly

**Comment by willow9886** [comment]
@uboznikov @yurem any chance we can get this into a release by July? Customer needs it for a deadline in early August.. Thanks, guys!

**Comment by uboznikov** [comment]
@willow9886 I'm working on it to be included in 2.4.4.

**Comment by willow9886** [comment]
Fantastic. Thanks, Val.

**Comment by yurem** [comment]
@uboznikov , Can we close it?

**Comment by uboznikov** [comment]
@yurem Yes, closing this issue...
