### ISSUE TITLE
'Manage Custom Scripts' page broken

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#265]
oxTrust: 
```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.3-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 8b412
Archiver-Version: Plexus Archiver
```

Screenshot: 

![custom_auth_page_broken](https://cloud.githubusercontent.com/assets/7156097/15615667/42fa3a18-2405-11e6-9d30-c843a6f4b2fe.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15868676/8d53a612-2d06-11e6-8739-7378a247852b.png)

**Comment by mzico** [comment]
Thanks @shekhar16 ; I'll check the status and inform you ASAP.

**Comment by mzico** [comment]
@shekhar16 : It' working now but may be need little modification which will align with other tabs? 

Here is what other tabs looks like: 

![other_tab](https://cloud.githubusercontent.com/assets/7156097/16013403/e6b69912-3152-11e6-8fea-e8ef3408850a.png)


And, here is how 'Manage Custom Script' tab looks like: 

![customscript](https://cloud.githubusercontent.com/assets/7156097/16013429/f9140a04-3152-11e6-8600-692e2beaa18f.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/16047867/684e8e7c-326f-11e6-8429-a6dca2cfd3f5.png)

**Comment by shekhar16** [comment]
Let me know should i reduce more height of tabs.

**Comment by willow9886** [comment]
@shekhar16 @mzico  perhaps we should add a horizontal scroll bar so that people can scroll right to see hidden menu items?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/16050332/e6f9915a-3278-11e6-88e5-fb3413b11dda.png)

**Comment by shekhar16** [comment]
@willow9886 @mzico  please take a look above pic with scroll.

**Comment by willow9886** [comment]
@shekhar16 yes, i think that's perfect.

**Comment by willow9886** [comment]
@shekhar16 does this scroll bar need to be applied to any other interfaces in oxtrust?

**Comment by mzico** [comment]
@willow9886 : I'll check and get back to you two with my suggestion...

**Comment by mzico** [comment]
@willow9886 @shekhar16 : It looks good. Scroll bar seems not required in any other interface.
