### ISSUE TITLE
[Update User] It isn't possible to change "User Status" ("gluuStatus" in LDAP) attribute through web UI

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#266]
Environment: Gluu CE 2.4.3-1-4 deb package

Preconditions:
1. One of user entries existing in internal LDAP directory has "gluuStatus" attribute set to "active"

Steps to reproduce:
1. Login to web UI as admin
2. Move to the "Manage People" page and open user mentioned in "Preconditions" there
3. Change value of  "User Status" to "inactive" and click the "Update" button

Result:
1. Update attempt seems to happen, but after page is refreshed the attribute disappears from the list.
2. If you move to some other page, then return back to "Manage People" and open this user again, its "User Status" attribute will still have "active" value; it will have the same value if viewed in LDAP browser too.
3. No errors in logs

This issue may be tied to this one: #267 (actually it may be the real cause why it's again at "active" after clicking "Update"; in that case this issue is only about the fact it disappears from the list after page refreshes)

**Comment by shekhar16** [comment]
@yurem Can we add 'gluustatus' as predefine attribute like 'gluuIMAPData',

**Comment by yurem** [comment]
@shekhar16 Did you added 'gluustatus' and 'gluuIMAPData',to setup? Do you need help?
