### ISSUE TITLE
[Update User] "User Status" ("gluuStatus" in LDAP) attribute changes to "active" if "Update" button is clicked

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#267]
Environment: Gluu CE 2.4.3-1-4 deb package

Preconditions:
1. One of user entries existing in internal LDAP directory has "gluuStatus" attribute set to "inactive"

Steps to reproduce:

1. Login to web UI as admin
2. Move to the "Manage People" page and open user mentioned in "Preconditions" there
3. Click the "Update" button

Result:
If you check that user in internal LDAP directory now, its "gluuStatus" attribute is set to "active". This was discovered before, actually, but becomes a real problem now, as we are about to add Account Lock-Out script/feature to the list. Administrator willing just to edit some attribute of locked-out user may unknowingly unlock it this way.

**Comment by shekhar16** [comment]
Fixed.

**Comment by yurem** [comment]
Fixed
