### ISSUE TITLE
Add Person to Group -- Person not visible

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#268]
When you add a person to a group, the list is not updated until you refresh the group.

1. View Group 
2. Search for person
3. Check person and Add
4. **Person not reflected in Group view**
5. Hit Update on Group
6. Re-view Group--person will be present.

**Comment by shekhar16** [comment]
Hi Mike,

I checked the issue but couldn't  able to reproduce it please see below snap 
1) I opened manage group in that 
2) i clicked on 'add member' button ,a pop up is there.
3) 'search' for member and checked it 
4) clicked 'ok' button.
5) the new member is added in members area.

Please let me know if i m doing anything wrong.

Thanx.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15828019/4aa66538-2c2b-11e6-8589-00749e029752.png)

**Comment by nynymike** [comment]
Ok, I'll try again and give the version and browswer that I'm using.

**Comment by mzico** [comment]
@shekhar16 : Looks okay to me. Using: 

- Chrome 51.0.2704.103
- oxTrust version: 
```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 2acb4
Archiver-Version: Plexus Archiver
```
