### ISSUE TITLE
[SCIM Interop Testing] Convert LDAP attributes stored as JSON arrays to multivalued attributes

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#269]
Currently object lists like emails and addresses are stored as JSON arrays in a single LDAP attribute, thus:

`[{"value":"c@d.com","type":"other","primary":"true"},{"value":"e@f.com","type":"work","primary":"false"}]`

This format presents difficulty to search via SCIM filters, e.g., `emails[value sw "c@" and type eq "work"]`, since there is no way to stop matching `"type":"work"` from the other email entry.

If converted as a multivalued attribute, e,g,

```
oxTrustEmail = {"value":"c@d.com","type":"other","primary":"true"}
oxTrustEmail = {"value":"e@f.com","type":"work","primary":"false"}
```

`emails[value sw "c@" and type eq "work"]` will be potentially converted to the LDAP filter:

`(&(|(oxTrustEmail=*"value":"c@*"type":"work"*)(oxTrustEmail=*"type":"work"*"value":"c@*)))`

which will correctly not return any result.

This entails that customers upgrading to 2.4.4 will need to have their data migrated also to the new structure.

**Comment by nynymike** [comment]
Perhaps you should also populate the "mail" attribute with just the email, and search that.

**Comment by uboznikov** [comment]
@nynymike There is syncing between 'mail' and 'oxTrustEmail' (https://github.com/GluuFederation/oxTrust/issues/251) so searching on 'oxTrustEmail' would suffice.

**Comment by nynymike** [comment]
But I would hope that the synch does not include the metadata. So I would just search for the email first, and if found, then iterate the metadata. It won't be fast... but its SCIM.

**Comment by uboznikov** [comment]
Yes the syncing does not include the metadata, and searching on one field will also be efficient (no other trips to LDAP) and uniform/simple for the filter combinations.
[some-filter-combinations.txt](https://github.com/GluuFederation/oxTrust/files/296970/some-filter-combinations.txt)

**Comment by uboznikov** [comment]
Initial commit for mail:

[https://github.com/GluuFederation/oxTrust/commit/05eaa4fd9bfba5d44732bb95206075b454d654bb](https://github.com/GluuFederation/oxTrust/commit/05eaa4fd9bfba5d44732bb95206075b454d654bb)

**Comment by uboznikov** [comment]
Here's the commit for the other SCIM list attributes:

[https://github.com/GluuFederation/oxTrust/commit/24f63f9ee6879c204e47f9c5c0ea797769a13569](https://github.com/GluuFederation/oxTrust/commit/24f63f9ee6879c204e47f9c5c0ea797769a13569)

@tecoholic 

For the SCIM list attributes in LDAP that need to be migrated to the new structure, please see the lists in this class:

[User.java](https://github.com/GluuFederation/oxTrust/blob/master/scim/src/main/java/org/gluu/oxtrust/model/scim2/User.java) (or [ScimPerson.java](https://github.com/GluuFederation/oxTrust/blob/master/scim/src/main/java/org/gluu/oxtrust/model/scim/ScimPerson.java))

**Comment by tecoholic** [comment]
@uboznikov Sure. Thank you for the pointer.

**Comment by uboznikov** [comment]
It is now working.
