### ISSUE TITLE
"Update/Add client" page allows to set id_token's signing algorithm to none, resulting in unsigned id_token

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#271]
Steps to reproduce:

1) Log in to web ui as admin
2) Create some basic OIDC client entry with minimal set of required features intended for "authz code" flow, while setting "JWS alg Algorithm for signing the ID Token" property to "none"
3) Try to follow  "authz code" flow using this client

Result:

id_token is returned from token endpoint as unsigned jwt structure what violates OIDC core spec:

> ID Tokens MUST be signed using JWS [JWS] and optionally both signed and then encrypted using JWS [JWS] and JWE [JWE] respectively, thereby providing authentication, integrity, non-repudiation, and optionally, confidentiality

![oidc-unsigned-idtoken2](https://cloud.githubusercontent.com/assets/11802046/15801327/252ffa40-2a9a-11e6-93fb-7f8238c0e7ed.jpg)

It also seems that this ability has been present in Gluu for some time already, as you can achieve the same in 2.3.x instance by modifying corresponding attribute in client's LDAP entry directly, by explicitly assigning "none" value to attribute of client's entry named "oxAuthIdTokenSignedResponseAlg".

Do we really need this allowed? Mb it shouldn't be at least that easy to enable (i.e. no need to put it to web UI)?

**Comment by yuriyz** [comment]
@qbert2k Javier, is it required by our oxauth acceptance test? because it seems to be a bug.
