### ISSUE TITLE
Confirm delete of Custom Script

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#272]
In oxTrust under Configuration -> Manage Custom Scripts, it is possible to delete the scripts by clicking on the green 'X' on the far upper right side near at the beginning of that script.

Currently there is no confirmation dialog verifying the intention to delete. As a result it is possible to inadvertently delete a script.

Can we wrap this delete functionality with a confirmation dialog bog?

**Comment by nynymike** [comment]
Don't you have to delete it and then hit Submit?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24834952/43efd5b2-1d11-11e7-8f1c-ca9b09b03b1e.png)

**Comment by shekhar16** [comment]
Fixed.
