### ISSUE TITLE
OxTrust Does Not Trim Whitespaces from Login and Logout Redirect URIs

### ISSUE THREAD

**Issue by teemuk** [GluuFederation/oxTrust#273]
When adding Login or Logout Redirect URIs, oxTrust application does not trim the whitespaces from the URI values. This means that if e.g. the login redirect URI is set to "https://localhost/redirect " in oxTrust UI, when calling oxAuth authorization endpoint with redirect_uri value "https://localhost/redirect", following error is shown:

```
{"error":"invalid_request_redirect_uri","error_description":"The redirect_uri in the Authorization Request does not match any of the Client's pre-registered redirect_uris."}
```

Similarly for logout redirect URIs the error is:

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter or parameter value, repeats a parameter, or is otherwise malformed."}
```

**Comment by nynymike** [comment]
Shekhar, please prioritize this if possible for 2.4.4

**Comment by shekhar16** [comment]
Fixed.
Trim all uris present in oxtrust configuration and add/update client page.

**Comment by yurem** [comment]
Code looks fine. I only reffactored it., Assigning to @zamilskhan to check in new beta build
