### ISSUE TITLE
Create custom nameID

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#274]
Now we need to modify velocity templates to create custom nameID in Gluu Server. [As for example](https://gluu.org/docs/ce/admin-guide/saml/#custom-nameid). 

It would be great if we could develop a feature which will allow Gluu Server administrator to create custom nameID from oxTrust. 

It might be something like this: 
- Administrator is interested to create a custom nameID named 'customuidname' which will be based on 'uid' attribute. 
  - Create custom attribute from oxTrust 
  - There might be some checkbox which will ask 'Create NameID' and an input box which will ask 'source attribute' 
    - If administrator 'enable' that checkbox and put 'uid' in 'source attribute' input box, oxTrust will: 
      -  add `$attribute.name.equals('customuidname')` in attribute definitions of 'attribute-resolver.xml.vm 
      - add `<resover:AttributeDefinitiion...... </resolver:AttributeDefinition>`

**Comment by nynymike** [comment]
@uboznikov Was this requirement addressed in Shib IDPv3?

**Comment by uboznikov** [comment]
@nynymike In IdP v3 the definition has been moved to `saml-nameid.xml` and adding it is a manual exercise.

[NameIDGenerationConfiguration](https://wiki.shibboleth.net/confluence/display/IDP30/NameIDGenerationConfiguration)
[CustomNameIDGenerationConfiguration](https://wiki.shibboleth.net/confluence/display/IDP30/CustomNameIDGenerationConfiguration)

I have asked @mzico to test it:
[Add 'emailAddress' as default nameID format](https://github.com/GluuFederation/oxIdp/issues/5)

**Comment by yurem** [comment]
@mzico can you test it?

**Comment by mzico** [comment]
I will test

**Comment by mzico** [comment]
@uboznikov : There is no GUI way to add custom NameID in 3.0.0? 
We need to add necessary snippets in 'saml-nameid.xml' manually to configure nameID?

**Comment by willow9886** [comment]
@yurem @mzico status of this issue?

**Comment by mzico** [comment]
@willow9886 : No GUI yet. Configuring through cmd.

**Comment by willow9886** [comment]
should we reassign to shekhar?

**Comment by mzico** [comment]
Yes, that will be good.
