### ISSUE TITLE
Text/Font of 'Certificate Management' is ..... 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#275]
Screenshot attached: 

![certificate_management](https://cloud.githubusercontent.com/assets/7156097/16057547/3af4a42c-3240-11e6-8404-e553108fc813.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/17769042/76d66254-6554-11e6-96c9-c855a19476b1.png)

**Comment by shekhar16** [comment]
Fixed : Change the fonts size of headings.
