### ISSUE TITLE
Old 'green shade' in 'Manage Registration' page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#276]
Screenshot attached: 
![registration_green](https://cloud.githubusercontent.com/assets/7156097/16057744/09a4b30c-3241-11e6-90db-53c78834f2dd.png)

**Comment by willow9886** [comment]
we should also update the style of the buttons to something in line with the rest of the buttons on our app.

**Comment by shekhar16** [comment]
Fixed

**Comment by mzico** [comment]
@shekhar16 : looks good. Thanks.
