### ISSUE TITLE
Searching feature for SAML Trust relationship

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#277]
In 'OpenID Connect' Client section we have search feature ( the searching box ) which can search for clients. 
![openidclientsearch](https://cloud.githubusercontent.com/assets/7156097/16085235/fd21e910-32e0-11e6-8594-454391632431.png)

Is it possible to implement such search box for SAML Trust relationship page, where Gluu Server administrator will be able to search any trust relationship? To make things simple... we can only implement searching based on 'Community' column. 

![trsearching](https://cloud.githubusercontent.com/assets/7156097/16085286/323b72d8-32e1-11e6-9791-0782ce9e502a.png)

**Comment by willow9886** [comment]
instead of a "type and click the search button" style of search (like we have for OpenID Connect clients), a "refining search" might be preferable here... i.e. as you type, the complete list is refined to match your search.

**Comment by shekhar16** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/15937500/16565269/d77a5d20-4229-11e6-9350-f51b02b72037.png)

**Comment by mzico** [comment]
@shekhar16 : Working. Thanks.
