### ISSUE TITLE
Valid email format in registration

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#281]
We should make sure that anything entered into the email field in the default registration form has the valid "name@xyz.something" format.

Currently you can register with any string of characters.

**Comment by mzico** [comment]
@shekhar16 : Basic functionality is working but need little modification. Messages are coming twice.... Screenshot attached. 
![double](https://cloud.githubusercontent.com/assets/7156097/16714649/817bf14e-468f-11e6-99ca-b2f294c77fc1.png)

**Comment by mzico** [comment]
@shekhar16 : Working. 

Tested in: 

```
GLUU.root@test:/opt/tomcat/webapps/identity/META-INF# cat MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 0f132
Archiver-Version: Plexus Archiver
```
