### ISSUE TITLE
Long grant value causes interface to 'break'

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#282]
From support ticket:
https://support.gluu.org/customization/long-grant-value-causes-interface-to-break-2883

We have a string attribute that we put into a token and if we put(privileges in the screenshot): "api/policyengine/functions/measurementFunction|api/policyengine/functions/policyFunction|api/policyengine/functions/Function1|api/policyengine/functions/Function1|api/policyengine/functions/Function3|api/policyengine/functions/Function4|api/policyengine/functions/Function5|api/policyengine/functions/Function6|api/policyengine/functions/Function7|api/policyengine/functions/Function8|api/policyengine/functions/Function9|api/policyengine/functions/Function10"

Into it, the interface attached screenshots show the setup, before, and after.

One additional question - is there a maximum length for a string in this case?

**Comment by qbert2k** [comment]
The bug is in the user interface, css layout and affects all the text field when entering long texts.

The layout looks better in Firefox, in Chrome the layout goes totally useless when entering long text

A work around is to use Firefox mean while the bug is being solved

**Comment by shekhar16** [comment]
'rich:inplaceInput'  tag doesn't support maxlength attribute.And I tried few more things with it but doesn't work.
To fix this issue we need to replace 'rich:inplaceInput' tag to 'h:inputtext'.Or we need to update richfaces  version which support maxlength attribute in 'rich:inplaceInput'  tag.
.

**Comment by yurem** [comment]
Seam can work without richafes. Hence it's independent part. But this can trigger JSF libs update, etc..
I offer to do richfaces upgrade in next version. I think so because new richfaces version can break other functionality or it can deprecate older componenents.

What do you think about next idea?
1) Add new attribute type: text (or other name)
2) If attribute has specified type we can render textarea or any other component to allow enter long text.

This will allow to customize attributes to conform user requirrements.

**Comment by aliaksander-samuseu** [comment]
There is still an issue with this page. Please see attached picture. When I open default admin for editing and try to add some attribute to it, I'm instantly presented with error message that one string is more than 60 chars long (seems to be memberOf attribute). When I click some attribute in the list to the left to "attach" it to user and edit, it disappears from it, but doesn't appear on the pane to the right. So all functionality is broken here, unless you trim this memberOf attribute, with unknown consequences. Also please consider that some other attribute, perhaps imported from some backend, may also happen to be longer that 60 characters.
![long_string](https://cloud.githubusercontent.com/assets/11802046/16847599/81b76bac-49fa-11e6-9c4c-8ffac5b8cb62.jpg)

**Comment by aliaksander-samuseu** [comment]
There are too problems with it:

1. Right now it's not possible to edit default admin in web UI right out of the box, that doesn't seem right.
2. Unless CR also will be enforcing this limit, you may end up with a lot other users like this. There are also auth scripts, like gplus or saml scripts, which are capable to enroll new users on the fly, and they user attributes values received from 3rd parties, so if the limit not enforced there too, you'll again may end up with a bunch of users that can't be edited in web UI

**Comment by shekhar16** [comment]
@yurem As per old code we already had max-length attribute on this page but it was not working So i just made correction and added this validation.
So please suggest for which input fields we should add this maxlength validation or can i remove it?

**Comment by yurem** [comment]
Why we don't use attribute type field to render proper component type?
There are next attribute types now: Text, Numeric, Long, Date. We can add Long Text, e-mail, etc..
This will allow us to render proper component, allow to implement validation, text limitation, etc..

@shekhar16 BTW, why there is no imap attribute type in this list?
