### ISSUE TITLE
Change: Shibboleth:Outbound, Asimba: Inbound

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#284]
![image](https://cloud.githubusercontent.com/assets/3717101/16320903/de9e1f06-395f-11e6-9bd8-d90cf013e5d9.png)

We need to change "Shibboleth" to "Outbound" and "Asimba" to "Inbound"

This is because we may be supporting an inbound IDP use cases where Asimba is not used, but we still want to use the IDP form.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/16360838/aa718b28-3b94-11e6-888d-62740027b982.png)

**Comment by mzico** [comment]
@shekhar16 : Which version has enhancement? I tried with '2.4.4-SNAPSHOT' and '2.4.4.Final' oxTrust but I don't see anything. Am I missing anything? 

![testing244](https://cloud.githubusercontent.com/assets/7156097/16470353/4a526486-3e1b-11e6-91da-15e6a39b1fde.png)

**Comment by shekhar16** [comment]
May be the Latest code is not deployed?

**Comment by nynymike** [comment]
It seems a waste that certificates is duplicated (i.e. one heading for one sub child).

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/16713845/0fc761ae-46d1-11e6-9363-516b02ef3b48.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by mzico** [comment]
@shekhar16 : Looks good. Thanks.
