### ISSUE TITLE
Failed to set custom gluuPerson attribute

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#286]
In current CE 2.4.4 beta2 SCIM works fine out of the box. I updated SCIM UMA documentation page.

There is question only about oxEnrollmentCode attribute: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif#L1060

It’s gluuPerson attribute. I’m trying to set it using:

        // User Extensions
	String enrollmentCode = UUID.randomUUID().toString();
        Extension.Builder extensionBuilder = new Extension.Builder(Constants.USER_EXT_SCHEMA_ID);
        extensionBuilder.setField("oxEnrollmentCode", enrollmentCode);

But on server side I get:

INFO   | jvm 1    | 2016/06/25 04:37:30 | java.lang.IllegalArgumentException: NOT A CUSTOM ATTRIBUTE: oxEnrollmentCode
INFO   | jvm 1    | 2016/06/25 04:37:30 | 	at org.gluu.oxtrust.service.scim2.jackson.custom.ExtensionDeserializer.deserialize(ExtensionDeserializer.java:74)
INFO   | jvm 1    | 2016/06/25 04:37:30 | 	at org.gluu.oxtrust.service.scim2.jackson.custom.ExtensionDeserializer.deserialize(ExtensionDeserializer.java:34)

**Comment by uboznikov** [comment]
Missing "oxSCIMCustomAttribute: true" attribute

Reference:
[scim-test-data.ldif](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/scim-client/data/scim-test-data.ldif#L43)

**Comment by yurem** [comment]
Thank you for quick response. I merged your changes into v2.4.4: https://github.com/GluuFederation/community-edition-setup/pull/145
