### ISSUE TITLE
CE v2.4.4-beta2-2: In CentOS 6.8, repeated calls to RptStatusService.requestRptStatus() results in "Failed to determine RPT status" error

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#288]
The issue described below was encountered on CentOS 6.8 only thus far during CE v2.4.4 QA testing (CE v2.4.4-beta2-2). It was never encountered on Ubuntu 14.04.

On executing multiple SCIM unit tests like in [UserFiltersMainTests.java](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/UserFiltersMainTests.java#L49-L72), the line [RptStatusService.requestRptStatus()](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/UmaProtectionService.java#L149) of the UMA authorization breaks after several calls. This "several calls" is random so it is kinda hard to say on which test item it will happen.

The test has been re-run several times, even after re-installation, and it only occurs on CentOS 6.8 and never on Ubuntu 14.04. There were also no errors in `oxauth.log`.

There seems to be a "race condition" happening because if you add a delay after each unit test, say `Thread.sleep(1000);`, the issue goes away.

`oxtrust.log` and `oxauth.log` files are attached.

[oxtrust-oxauth-logs.zip](https://github.com/GluuFederation/oxTrust/files/339441/oxtrust-oxauth-logs.zip)

**Comment by yurem** [comment]
I suspect that the issue comes from Apache Anti-DOS modules. They "think" that you are trying to hack the server.

Can you comment few lines in out: /opt/gluu-server-2.4.4/etc/httpd/conf/httpd.conf
LoadModule status_module modules/mod_status.so
LoadModule negotiation_module modules/mod_negotiation.so
LoadModule antiloris_module modules/mod_antiloris.so
LoadModule evasive20_module modules/mod_evasive20.so
LoadModule limitipconn_module modules/mod_limitipconn.so


Try to restart the apache service and comment out another lines after disable these modules.

**Comment by uboznikov** [comment]
This is not encountered in RC1 CentOS 7.2.

**Comment by yurem** [comment]
It's definitely Apache Anti-DOS configuration issue.

**Comment by uboznikov** [comment]
> Can you comment few lines in out: /opt/gluu-server-2.4.4/etc/httpd/conf/httpd.conf

After commenting out the said lines, `check_ssl` issue was encountered.

**Comment by uboznikov** [comment]
In CentOS 6.8, `check_ssl` issue was encountered right after restart, no modifications.

**Comment by uboznikov** [comment]
In CentOS 6.7, the error went away after commenting out the following lines:

` LoadModule evasive20_module modules/mod_evasive20.so`

and

`# Anti-DOS stuff`
```
ExtendedStatus
IPReadLimit
DOSHashTableSize
DOSPageCount
DOSSiteCount
DOSPageInterval
DOSSiteInterval
DOSBlockingPeriod
```

**Comment by ganesh-at-wiw** [comment]
Hi Uboznikov,

Can you please contact me on skype? 
My id is: worldiswelcome

**Comment by ganesh-at-wiw** [comment]
I do not see the Anti-DOS stuff in Ubuntu.
But in CentOS, yes we do and I've added the IfModule conditions at the end of httpd.conf file to make it easier to comment out LoadModule during testing.
I'm checking out further possibilities.

**Comment by ganesh-at-wiw** [comment]
For CentOS based, I've configured mod_evasive to have more relaxed values for DOSPageCount and 
DOSSiteCount to 20 and 100 resp. In my testing I see that with these new values, I get Forbidden response very late. So, it's kind of safer for working. If need be we can tweak it to more relaxed or tightened values.
