### ISSUE TITLE
Add an explicit notification that changes to SAML TR may take some time to be applied

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#290]
Issue was raised in [this ticket](https://support.gluu.org/maintenance/o365-stopped-working-2931#at12136)

It seems that there is a significant delay between the moment some changes are introduced to SAML TR in web UI and when those changes are actually applied by Shibboleth module, up to several minutes. This may lead to a confusion of an user sometimes (though I vaguely remember I've seen a warning about that in our docs somewhere), as he may think that changes he did are the cause that TR still doesn't work as it should, he may start to tweak it again, actually do some mistake this time, creating another issue and so on.

It would probably be a more beneficial to all parties if oxTrust would display a clear notification about this each time TR is saved, similar to the picture below:

![saml_tr_notif](https://cloud.githubusercontent.com/assets/11802046/16628853/19e117ce-43bc-11e6-9437-a3d8b839e35e.jpg)

**Comment by aliaksander-samuseu** [comment]
Or may be this text is better: "Please note it may take several minutes before new settings are actually loaded and applied by Shibboleth module!". I like it more because it also touch the actual cause of this delay, saving an user some time asking/uncovering it for himself.

**Comment by happymcplaksin** [comment]
There could even be a link to a page in the GUI that says when the last reload happened :)

**Comment by shekhar16** [comment]
Fixed.

**Comment by aliaksander-samuseu** [comment]
Fix verified
