### ISSUE TITLE
oxTrust's notifications showing results of different user's action could have their "fade out" time increased

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#292]
Below is an example of what these notifications are:

![19e117ce-43bc-11e6-9437-a3d8b839e35e 1](https://cloud.githubusercontent.com/assets/11802046/16717007/333c150a-4715-11e6-85ad-4ebecb840123.jpg)

By @shekhar16 , atm their "fade out" time is at 3 seconds, and it's a global setting. That's way too low, user will be  barely able to read the text even after several repeats of the action. This time should be at 7-10 seconds, I believe. But as it's a global setting, I thought we should discuss it first, with some senior developers providing their opinion

**Comment by yurem** [comment]
Currently we show message for 2 seconds only.
		<rich:notifyMessages stayTime="2000" nonblocking="true" />

We can add sticky="true" param to add close button to message. But it's not convenient for info messages. We can try to write JS to auto-hide them after some time.

**Comment by aliaksander-samuseu** [comment]
Hi, @yurem.

Just've talked with @shekhar16 about the fix he prepared. It seems you decided to create a workaround by integrating this particular message into the page itself (not like other pop-up status messages ). It's fine, but what concerns me is that we still may have some important status messages showed at other places which fade out too soon. Like, 2 secs is too low anyway. Mb we shoudl still rise this global setting a bit? At least to 5 secs.
