### ISSUE TITLE
Inbound SAML (Asimba): Enable support for multi-party federation 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#295]
When adding an IDP, it would be nice if the admin could specify the source of the metadata as a multi-party SAML federation.  This is dependent on [enhancement in gluu-Asimba](https://github.com/GluuFederation/gluu-Asimba/issues/15)

The experience should be similar to in Outbound SAML/Add Trust Relationship, where the user can browse or search for a specific IDP.

Note, the list should filter on IDPs... no need to show SP's in this list.

**Comment by willow9886** [comment]
No longer necessary.
