### ISSUE TITLE
oxTrust Passport API / GUI

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#299]
We are in the process of integrating Passport-js into the Gluu Server. There are two parts to this assignment:

1) We need an UMA protected API that the passport server can call to retreive its configuration, which should be stored in LDAP:

```
dn: ou=oxpassport,inum=appliance-inum,ou=appliances,o=gluu
objectclass: top
objectclass: organizationalUnit
objectclass: gluuPassportConfigEntry
ou: oxpassport
gluuPassportConfiguration: {"provider": "passport", 
  "serverURI: "gluu.local.org",
  "serverWebPort": "8000",
  "applicationEndpoint": "https://gluu.local.org/oxauth/auth/generic/genericpostlogin.htm",
  "applicationStartpoint": "https://gluu.local.org/oxauth/auth/generic/genericlogin.htm",
  "applicationSecretKey": "GluuNodeServerSocialLogin1234567890"}
gluuPassportConfiguration: {"provider": "twitter", "clientID": "", "clientSecret": "",...}
gluuPassportConfiguration: {"provider": "facebook", "clientID": "", "clientSecret": "",...}
gluuPassportConfiguration: {"provider": "linkedin", "clientID": "", "clientSecret": "",...}
status: active
```

2) We need a UI that will enable the oxTrust admin to enable|disable passport, and to manage this information, including configuring new "strategies" i.e. gluuPassportConfiguration JSON objects.  
This should go in the Configuration section. 

Here is an example of the [original config file](https://github.com/GluuFederation/gluu-passport/blob/master/server/_config.js). Note: we don't need the host and port beacause Apache will be the web server.

**Comment by shekhar16** [comment]
@nynymike Please check below passport flag enable|disable on oxtrust UI configuration.
![image](https://cloud.githubusercontent.com/assets/15937500/16901274/35fddfca-4c5c-11e6-86bd-d32d23f0d1fc.png)

**Comment by nynymike** [comment]
I think it would be better to maintain consistency with the other optional features, and do an "Enabled|Disabled" drop down.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/16901546/b41c4556-4c64-11e6-83a0-afdadc1dcdb0.png)

**Comment by shekhar16** [comment]
dn: TBD
objectclass=top
objectclass=oxPassportConfiguration
ou=oxpassport
gluuPassportId: {"clientID": "", "clientSecret": "",...}
gluuPassportId: {"clientID": "", "clientSecret": "",...}
gluuPassportId: {"clientID": "", "clientSecret": "",...}
gluuPassportId: {"clientID": "", "clientSecret": "",...}
applicationEndpoint: https://server
applicationSecret: dsljflkdsjflksdj
status: active

**Comment by shekhar16** [comment]
GUI and Ldap changes are done.Please verify it.

**Comment by shekhar16** [comment]
Passport Api is created. 
Url  :  http://{server domain}/identity/seam/resource/restv1/passportconfig
method : post

**Comment by yurem** [comment]
I've checked it on ce-dev. There is no button in UI to remove configuration.
Endpoint /identity/seam/resource/restv1/passportconfig should be protected by UMA according to requirements.

**Comment by yurem** [comment]
In SCIM we also protect endpoints using UMA: https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/UserWebService.java#L82

@nynymike there is only one question. I think we have to duplicate [these](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxtrust-config.json#L124) UMA properties to protect this endpoint.
We need to change UMA properties format:
```
"umaConfiguration":
[{
    "id":"scim",
    "issuer":"https://%(hostname)s",
    "clientId":"%(scim_rs_client_id)s",
    "clientKeyId":"",
    "resourceId":"1447184268430",
    "scope":"https://%(hostname)s/oxauth/seam/resource/restv1/uma/scopes/scim_access",
    "clientKeyStoreFile":"%(scim_rs_client_jks_fn)s",
    "clientKeyStorePassword":"%(scim_rs_client_jks_pass_encoded)s"
},
{
    "id":"passport",
    "issuer":"https://%(hostname)s",
    "clientId":"%(scim_rs_client_id)s",
    "clientKeyId":"",
    "resourceId":"1447184268430",
    "scope":"https://%(hostname)s/oxauth/seam/resource/restv1/uma/scopes/scim_access",
    "clientKeyStoreFile":"%(scim_rs_client_jks_fn)s",
    "clientKeyStorePassword":"%(scim_rs_client_jks_pass_encoded)s"
}
]
```

**Comment by nynymike** [comment]
Yes, there is no question these endpoints have to be protected! GAT token protection would also be acceptable.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/6397a641cd84f2c3b9c38c8d619f783c95524785

**Comment by shekhar16** [comment]
Added code to protect the api with GAT token.

**Comment by arvindsinghtomar** [comment]
Thanks @shekhar16 . I'll contact you if I need anything.

**Comment by arvindsinghtomar** [comment]
@shekhar16 I can still access API directly. Please check.

**Comment by shekhar16** [comment]
@arvindsinghtomar Actually at that time the code was not deployed.The Latest code is deployed successfully deployed on friday and working fine. please test it.I created your client/secret on skype.

**Comment by shekhar16** [comment]
@arvindsinghtomar As per your requirement I updated the response parameters for passport api.
here is new response sample
{
  "applicationEndpoint": "https://gluu.local.org/oxauth/auth/generic/genericpostlogin.htm",
  "applicationStartpoint": "https://gluu.local.org/oxauth/auth/generic/genericlogin.htm",
  "authenticationUrl": "gluu.local.org",
  "passportStrategies": {
    "testPassport": {
      "clientID": "testPassport",
      "clientSecret": "testPassport"
    },
   "twitter": {
      "clientID": "7719rof6v75s4g",
      "clientSecret": "fM4ACEGDCVaYdNfg"
    },
    "linkedin": {
      "clientID": "7719rof6v75s4g",
      "clientSecret": "fM4ACEGDCVaYdNfg"
    },
    "facebook": {
      "clientID": "7719rof6v75s4g",
      "clientSecret": "fM4ACEGDCVaYdNfg"
    }
  }
}

**Comment by yurem** [comment]
There are 2 comments about protection part:
1) We issue PAT token on each API call. @arvindsinghtomar how often we can call this endpoint?
2) We uses SCIM client to protect this API. I think it's not part of SCIM and should be protected by own client.

**Comment by yurem** [comment]
Roughly speaking we can't use same user/password to protect different API.
SCIM is very powerful. If someone will hack passport he will able to access SCIM. We definitely need own client_id, JKS with keys to protect passport API.

**Comment by yurem** [comment]
I've fixed passport configuration endpoint. But GUI still requires your artention:
```
Caused by: java.lang.NullPointerException
	at org.gluu.oxtrust.action.ManagePersonAuthenticationAction.addStrategy(ManagePersonAuthenticationAction.java:397)
```

**Comment by yurem** [comment]
Fixed
