### ISSUE TITLE
Certificates Page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#304]
![image](https://cloud.githubusercontent.com/assets/3717101/17038155/f55baea6-4f59-11e6-8fe3-5a26c00c39c3.png)

This page is showing up even when I didn't install Asimba.

Also, I don't understand what the search field at the top is searching...

Is this information specific to Asimba, or to the Gluu Server in general? Maybe it should be in the Configuration section?

**Comment by dmogn** [comment]
It is not bag, It is feature.

Aswimba's keystore is only one of multiple target.
This page shows all Gluu's certificates, so admin can check httpd/OpenDJ certs too.

**Comment by willow9886** [comment]
perhaps we can not show Asimba if Asimba has not been installed?

**Comment by dmogn** [comment]
Ok. I'll move the page to 'Configuration' and make empty sections hidden.

**Comment by dmogn** [comment]
Done. Maybe we can add it in 2.4.4. 

![certificate monitoring3](https://cloud.githubusercontent.com/assets/14166017/17046910/c756b28a-4fae-11e6-8bd0-50f915da2fbd.jpg)

**Comment by dmogn** [comment]
Can I close the issue?

**Comment by yurem** [comment]
It's build with this fix: http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.4/oxtrust-server-2.4.4.war
