### ISSUE TITLE
Customizations made using SAML TR's "Configure RelyingParty" feature doesn't make it into Shibboleht's module's conf file

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#305]
**Update:**
**Please read comments below it seems that oxTrust interprets Shibtest's metadata as federation, what explains this strange behavior; still, questions remain**

Environment:
CentOS6.7, Gluu CE 2.4.4-1.rc2

Preconditions:
1. Instance is installed with Shib IdP v2

Steps to reproduce:

1. Log in to web UI as admin
2. Create some test SAML TR using [metadata of www.testshib.org](http://https://www.testshib.org/metadata/testshib-providers.xml) with "URL" method of providing metadata; don't use "Configure RelyingParty" feature while doing it yet; release `transientid` as attribute
3. Check `/opt/idp/conf/relying-party.xml`, the part just beneath the `</rp:DefaultRelyingParty>` (there shouldn't be anything beside Gluu's system SP's definition)
4. Edit TR created on step 2) and use "Configure RelyingParty" feature this time; set encryption of assertions to "never" for SAML2SSO profile
5.  Check `/opt/idp/conf/relying-party.xml`, the part just beneath the `</rp:DefaultRelyingParty>` again.

Result:

Nothing appears in the mentioned section of `/opt/idp/conf/relying-party.xml` (despite configuration entry for this TR in LDAP seems to be assigned correct values to relevant attributes); under normal circumstances an additional `<rp:RelyingParty` xml element describing custom properties for this SP must appear in the conf file (please see attached picture)

![2 4 4rc2_saml_tr_custom](https://cloud.githubusercontent.com/assets/11802046/17041497/12946238-4faf-11e6-969b-18a6f58ee134.png)

**Comment by aliaksander-samuseu** [comment]
Can't see any relevant exceptions in log files

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

This may be important: in my tests I used url to [testshib's metadata](https://www.testshib.org/metadata/testshib-providers.xml) which combines both their IdP and SP metadatas, when creating TR. Mb this confused Velocity script, or something.

In `velocity.log` I can see just a single error entry:
```
2016-07-21 19:59:10,924 - Left side ($trustParams.trustEntityIds.get($trustRelationship.inum).size()) of '>' operation has null value at attribute-filter.xml.vm[line 11, column 93]
```
...which doesn't seem relevant neither by time stamp, nor by its content.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

This time it's really important: it seems because of the fact metadata mentions 2 entities, oxTrust interprets it as a federation:

![2 4 4rc2-false-fed](https://cloud.githubusercontent.com/assets/11802046/17042220/8ae60b88-4fb4-11e6-9c25-13d49ec529d0.jpg)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

In the end it seems that "Configure RelyingParty" feature works for SPs. So it comes down to 2 questions:

1. Should metadata file like that (with 2 entities in it, but without any explicit declarations that this is federation's metadata) be treated like fed's metadata by oxTrust? Should it at all be accepted?
2. Why do we have "Configure RelyingParty" feature UI controls when editing/creating federation TR? I'm trying to use it, I see that these settings indeed being persisted into LDAP, but I can't see them be reflected in the `relying-party.conf` file. Is it broken? Or mb this feature has no sense when used with federation, so we could just remove it from there?

**Comment by aliaksander-samuseu** [comment]
Seems like there is no particular marker for federation metadata, beside enclosing everything in `<EntitiesDescriptor>` xml element. So only question 2) still holds: what purpose "Configure RelyingParty" has in case of federation? Should it do something useful? Otherwise we should remove it from web UI for federations (I remember in old web UI "Configure RelyingParty" wasn't displayed when you was creating TR, and only was displayed after you clicked "Update" button, actually creating it; also AFAICR it wasn't displayed for federations at all)

**Comment by nynymike** [comment]
The ability to make TR's using federation metadata is a critical feature in the Gluu Server. 

["A metadata aggregate is a signed SAML metadata document containing an EntitiesDescriptor element."]
(https://spaces.internet2.edu/display/dsaml/A+profile+for+distributed+SAML+metadata+management)

I'm not sure I understand  why an SP appears on the drop down for federations.

**Comment by yurem** [comment]
Is it for 2.4.4 or 2.4.5?

**Comment by aliaksander-samuseu** [comment]
@nynymike 

My initial mistake was that I didn't check what is in the testshib.org's metadata (it was a link you supposed to use to add their test SP). And after I created TR with it, there wasn't any signs on the surface that could help me to understand I've just created a federation TR, it looked like usual SP TR. So then I tried to use  "Configure RelyingParty" feature, and my custom configurations didn't change its behavior, so I thought that's a bug. Lately I spotted that it's actually a federation I created, but still the question is: if we have  "Configure RelyingParty" control being displayed for federation TRs, why doesn't it do something? Is it a bug? Or is it an unneeded control added here by mistake?

**Comment by aliaksander-samuseu** [comment]
Actually, there is one sign: "Federated websites" tab appears upon this TR is activated. I probably overlooked it.

**Comment by aliaksander-samuseu** [comment]
@yurem 

I assigned 2.4.5 as milestone as there wasn't a "2.4.4" option.

**Comment by nynymike** [comment]
Closing issue as made obsolete by [oxTrust issue 310](https://github.com/GluuFederation/oxTrust/issues/310)
