### ISSUE TITLE
Entityid selection pop-up for TRs created based on federation TR overlaps with other UI elements

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#306]
Environment:
Gluu CE 2.4.4-1.rc2, Firefox 46.0 in full window, screen resolution at 1360x768

Steps to reproduce:
1. Log in to web UI as admin.
2. Create Incommon TR using [this metadata](http://md.incommon.org/InCommon/InCommon-metadata.xml)
3. Create TR based on incommon fed's TR

Result:

On step when you must to select specific entity id by clicking "Click to select entity Id" link, pop up that appears goes under other UI elements (please see picture below)

![fed-select-entity-ids](https://cloud.githubusercontent.com/assets/11802046/17042994/4f06463a-4fbb-11e6-9f90-3f203de34d3d.jpg)

**Comment by shekhar16** [comment]
Fixed.
