### ISSUE TITLE
Rewrite Shibboleth2ConfService for Shib IDP V3

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#307]
Shibboleth2ConfService modifies Shib. XML files with UI actions.

TODO: modify IDP3 conf files in same manner, later move conf files to LDAP.

**Comment by nynymike** [comment]
@dmogn Is this work done? Is config really being stored in LDAP?

**Comment by dmogn** [comment]
@nynymike  I should chat with @uboznikov first.

**Comment by uboznikov** [comment]
@dmogn 

There are [Shibboleth3ConfService](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/service/Shibboleth3ConfService.java) config properties stored in [oxtrust-config.json](https://github.com/GluuFederation/oxTrust/blob/master/configuration/oxtrust-config.json).

For the IdP [config files](https://wiki.shibboleth.net/confluence/display/IDP30/ConfigurationFileSummary) like `idp.properties` and `ldap.properties` I don't think you can move them to LDAP.

**Comment by nynymike** [comment]
The idp.properties and ldap.properties files are relatively static. The main files I'm concerned about moving to LDAP are the ones that get modified for new relying parties and attribute release policies--i.e. stuff impacted by updates to SAML Outbound Trust Reletionship management in oxTrust.  If this is not ready for testing right now, we should change this issue to 3.1.

**Comment by uboznikov** [comment]
@nynymike Could you please elaborate. Thanks.

**Comment by uboznikov** [comment]
@dmogn What needs to be done?

**Comment by dmogn** [comment]
It is wide issue: 
oxTrust SAML TR UI -> Shibboleth3ConfService -> IDP V3 XML configs.
You already made most parts of it.
