### ISSUE TITLE
Add Trust Relationship: Federation websites are blocked in View

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#311]
![image](https://cloud.githubusercontent.com/assets/3717101/17145592/5a02258c-5320-11e6-9f8f-3d7ee807c04c.png)

It doesn't matter how big or small I magnify this view, the box is always partially hidden.

Steps to re-create issue:

 1) Add InCommon metadata aggregate as TR
```
http://md.incommon.org/InCommon/InCommon-metadata.xml  
```
 2)  Add new SAML TR, select "Federation" as "Metadata type"

**Comment by aliaksander-samuseu** [comment]
@nynymike 

That was just fixed by Shekhar: #306

**Comment by nynymike** [comment]
already fixed

**Comment by zamilskhan** [comment]
![federation-entity-if](https://cloud.githubusercontent.com/assets/7703245/17264283/bfe9d874-5607-11e6-9613-9fb6b200827c.png)

As tested in the latest build going into production.
