### ISSUE TITLE
[CR] UI control to remove additional source LDAP server is not visible

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#313]
Environment:
Gluu CE 2.4.4-1.rc3-1, CentOS6.7, Firefox 46.0 in full window, screen resolution at 1360x768

Steps to reproduce:
1. Log in to web UI as admin.
2. Move to "Cache Refresh" page and add additional source server there
3. Try to remove server you added

Result:

There is no controls visible on the CR page to remove this additional source LDAP server, at least at this screen resolution. Also please note that this UI pane is misalligned against supposed width of the UI's working space. It's quite possible that this control is present, but is "being pushed" out of visible space (check the attached picture)

![2 4 4rc3_cr_remove_server](https://cloud.githubusercontent.com/assets/11802046/17195071/71c50cda-5464-11e6-8978-59a02824615d.png)

**Comment by nynymike** [comment]
agreed, admin should be able to remove it

**Comment by shekhar16** [comment]
Added horizontal scroll.
Fixed.
