### ISSUE TITLE
[CR] CR doesn't map attributes like "sn" or "mail" implicitly (when there is no mapping for them in the table) anymore

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#314]
Environment:
Gluu CE 2.4.4-1.rc3-1, CentOS6.7

Preconditions:
1. Some LDAP server you can use as a source backend for CR
2. All user entries in this backend must have "sn" and "cn" attributes set to some values

Steps to reproduce:
1. Log in to web UI as admin.
2. Move to "Cache Refresh" page, configure a basic setup for some backend of your choice, add both "cn" and "sn" attributes to the list of attributes to pull, but don't add mapping for "sn" attribute to the mapping table. The "sn" attribute is chosen because it's a mandatory attribute for user entries in Gluu's schema, and it's easier to spot in logs when this attributes is missing (there is a java exception)
3. Enable CR and start monitoring its log

Result:

On next pulling attempt you'll see exception(s) stating that CR can't persist some entry(s) because they are missing a mandatory "sn" attribute. To this moment, if for some attribute pulled from backend there hasn't been specified an explicit mapping, it implicitly has been mapped to the attribute with the same name. That would not create an issue if there is an attribute of such name in Gluu's schema too. Thus, in case of "sn", or "cn", or "mail" and similar attributes with ubiquitous names, it worked fine even if they weren't mapped explicitly. I believe we even have this behavior mentioned in our docs on CR.

Was this change intentional? Otherwise it's a serious issue.

**Comment by willow9886** [comment]
@yurem any thoughts on this?

**Comment by willow9886** [comment]
@shekhar16 @aliaksander-samuseu is this bug still affecting us? Is it high priority? What's the status?

**Comment by nynymike** [comment]
I disagree with this assessment. `cn` and `sn` are only required by inetOrgPerson, which we are not using.
