### ISSUE TITLE
SP logout url box is throwing error message

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#315]
Situation : whatever the value is, this message is coming. No stack trace found in oxtrust or wrapper log. 
Error screenshot attached: 
![logouterror](https://cloud.githubusercontent.com/assets/7156097/17224884/6f87d20e-54c8-11e6-88a6-8fd575f14ac4.png)

How to reproduce: 
1. SAML --> Trust Relationship
2. Create new trust or use any existing one. 
3. Insert any valid/not valid value in 'SP Logout URL (optional)' field.

**Comment by willow9886** [comment]
@mzico is this something we can wait til 2.4.5 to fix? That will be at least 3 more months. Seems like it's pretty important functionality that needs to be addressed immediately.

**Comment by mzico** [comment]
@willow9886 : Actually we need check how it should work; 99% of our customers are not using it for their SP logout at all. So... need to check the 'target' first.

**Comment by devlinse** [comment]
As the original identifier of the issue which mzico kindly logged on my behalf, I'd say let it wait until 2.4.5.  We worked around it by manually adding the appropriate clause to the resultant IDP metadata file used by the SP.

```
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" 
  Location="https:/idp-name/idp/logout.jsp" /> 
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" 
   Location="https://idp-name/idp/logout.jsp" />

```
Realise that the preference is not to edit the resulting files, but it its not been raised previously there's no reason to believe that it's super urgent.

**Comment by shekhar16** [comment]
Fixed.
https://github.com/GluuFederation/oxTrust/commit/f687aa1f8735b98e65981e47aa3e3515337ff47e
