### ISSUE TITLE
Updates for new OpenID Connect Front Channel Logout Spec

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#316]
`frontchannel_logout_session_supported`  --> true | false ... default = true 

This param should be managed as a JSON property for oxAuth. Check community edition setup to make sure it gets provisioned correctly.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21577326/17db1ffe-cf7d-11e6-94be-01f1e7bd06a9.png)

**Comment by shekhar16** [comment]
Added new attribute in   http://localhost:8080/oxauth/.well-known/openid-configuration


"frontchannel_logout_session_supported": false

**Comment by shekhar16** [comment]
Fixed.
