### ISSUE TITLE
Rename "Change Password" -> "Change client secret" on Connect Client page

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#318]
I get question what is client password and client secret because on UI we have "Client secret" field to specify secret by "Change Password" button to change that secret which makes user to think that there is password besides secret. Please rename label to avoid user confusion.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20240182/186d2680-a938-11e6-8140-499f7fc051f4.png)

**Comment by shekhar16** [comment]
Fixed.
