### ISSUE TITLE
Cache Refresh saves password in the clear in the oxtrust_persistence.log

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#319]
Failed to create connection pool with properties: {binaryAttributes=objectguid, maxconnections=5, bindDN=CN=XXXXXXXXXXXXXXX\, XXXXXXXXXXXXXXX,OU=XXXXXXXXXXXXXXXXXX,OU=XXXXXXXXXXXXXXXX,DC=XXXXXXXXXXXXXXX,DC=XXXXXXXXXXXXXXXX,DC=net, useSSL=true, bindPassword=REDACTED

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/14b2a0fbd73c8bad2a0d867dc7b7e9c5384a2386

**Comment by shekhar16** [comment]
Fixed.

**Comment by nynymike** [comment]
Should this be closed?

**Comment by yurem** [comment]
I think instead of just changing password property value in properties we need to clone them. It will be more expected behavior than change value on catch exception.

```
((Properties)props.clone()).setProperty("bindPassword" , "hiddent_value");
```

**Comment by nynymike** [comment]
@shekhar16 Do you understand what needs to be done?
