### ISSUE TITLE
Authentication Level mapping to ACR

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#32]
In the custom authentication levels, we have a dropdown-box for "Level" with integers in it. 

I think we need to add a new global field in Configure authentication for "Authentication Level ACR Prefix" (ALAP)

For example, if ALAP is "https://example.com/acr/level" , then an authentication level with 10 the the proper acr would be "https://example.com/acr/level/10"  This should be available also in OpenID Connect discovery.

**Comment by yurem** [comment]
Can we close this issue?
