### ISSUE TITLE
Make SCIM 2.0 search MAX_COUNT configurable

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#320]
Currently it is hard-coded to 200.

**Comment by uboznikov** [comment]
If more than 200 search results are needed, paging can always be used.

[testSearchUsersPaging](https://github.com/GluuFederation/SCIM-Client/blob/master/src/test/java/gluu/scim2/client/UserFiltersMainTests.java#L132)

**Comment by willow9886** [comment]
The max count should be set in a property.

**Comment by shekhar16** [comment]
Should we save it in LDAP oxtrust config or it should be properties file.
I think ldap would be correct as we had all properties in ldap.
Please suggest.

**Comment by yurem** [comment]
This is not LDAP property. It's SCIM property. I think it's better to add this new property to oxTrust configuration. There are few scim properties in oxtrust [config](https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json#L365) already:

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/460b2e4b4c351538a4b622ec91305f65c127b23a

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/96d1eb4990f67d7d7aad152ba2c76c31664f79e0

**Comment by shekhar16** [comment]
Added new object ScimProperties  in oxtrust [config.](https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxtrust.properties.json#L365)
