### ISSUE TITLE
Removing logout URI from OpenID Connect Client throws error

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#321]
See this [issue](https://support.gluu.org/identity-management/oxtrust-unable-to-remove-client-logouturi-3077)

In the oxtrust UI I accidentally added a logout URI under using "Add LogoutURI" instead of with "Add Logout Redirect URI". When I click the green 'X' next to the logout URI which I don't want onthe client, I get redirected to the oxtrust home page with an error message in the right upper corner that says a system error occured, contact the gluu administrator. This is 2.4.4.b4

**Comment by willow9886** [comment]
@tecoholic can you add this to the automated user interface testing so it would be caught in future QA testing?

**Comment by tecoholic** [comment]
@willow9886 Sure. I will do it.

**Comment by mzico** [comment]
@tecoholic : Do you think we can ask customer to test? If yes, which version ( oxauth / oxtrust ) has this fix?

**Comment by tecoholic** [comment]
@mzico: I have added the UI test code that would be useful for us to catch this bug in future releases. I haven't created any fix. Maybe @aliaksander-samuseu can comment about it.

**Comment by nynymike** [comment]
Duplicate of #366
