### ISSUE TITLE
Limit search in SCIM v1

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#322]
We have 3 methods in User SCIM v1 where it's possible to get all users:

- [List<GluuCustomPerson> personList = personService.findAllPersons(null);](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L81)

- [GluuCustomPerson gluuPerson = personService.getPersonByAttribute(searchPattern.getAttribute(), searchPattern.getValue());](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L437)

- [List<GluuCustomPerson> personList = personService.getPersonsByAttribute(searchPattern.getAttribute(), searchPattern.getValue());](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim/UserWebService.java#L477)

**Comment by uboznikov** [comment]
Duplicate of #317
