### ISSUE TITLE
responsive design login

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#327]

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/17767232/bb43c010-654c-11e6-8278-d35d73c7b542.png)

**Comment by willow9886** [comment]
@shekhar16 let's change the message to "Incorrect email or password."


Otherwise looks good!

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/17838009/90e495ac-67df-11e6-9d56-be0a3a68f0de.png)

**Comment by willow9886** [comment]
@shekhar16 can we make the error message dynamic based on what UID the login form is asking for? 

For instance, if it is asking for email, the error message should read: Incorrect email or password. 

If the login form is asking for Username, it should read: Incorrect username or password. 

If the login form is asking for something else, like mobile number, it should read: Incorrect mobile number of password. 

So essentially I'm asking can we make the fir attribute in the error message a variable that is determined by whats on the form? 

e.g. something like 

`response=Incorrect_{UID_value)_or_{cred_value)`

**Comment by willow9886** [comment]
@shekhar16 any update on this?
