### ISSUE TITLE
Asimba: Metadata button should be Upload  (not Add)

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#328]
I was confused by this button, because metadata was already present. So "Add" made me think I needed to add another (which doesn't make sense, becuase you can only have one).

![image](https://cloud.githubusercontent.com/assets/3717101/17780679/ded855ce-6531-11e6-81bd-046f28de8331.png)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 asked me for some details regarding this part of UI, and I remember another minor issue I met here. When you just have provided Trust Certificate file there, its name is displayed in the list beside the "Add" button. But after you have created this SP requestor, the list is empty, and it's hard to say whether there is certificate attached to it, or not. Also I'm a bit confused why do we need to provide both metadata and certificate here, isn't we already have this certificate in the metadata?

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

...and I believe at IDPs page of Asimba configuration part of web UI, the Trust Certificate upload control also behaves like that. All Asimba pages with similar controls for uploading metadata/certificates should be checked, they all may need to be renamed like that, and some way of showing that metadata/certificate has already been uploaded is needed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/17836598/9ecbfae0-67b5-11e6-9705-847da429f203.png)

**Comment by shekhar16** [comment]
Updated both sp and idp page.
Fixed.
