### ISSUE TITLE
Fix attributerelease and gather elements of template

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#329]
![image](https://cloud.githubusercontent.com/assets/3717101/17782340/a1d3e3da-6538-11e6-8d17-2f61fe953c93.png)

As shown in the screenshot above...

In the attributerelease section, we should remove everything but `<attribute name="*" />`

We also need to add the 

```
<gather>
   <attribute name="whitelist-attribute-name" />
</gather>
```

**Comment by nynymike** [comment]
@uboznikov - Can you see if this is fixed in 3.0?

**Comment by dmogn** [comment]
@uboznikov  aimba.xml template now is here:
https://github.com/GluuFederation/community-edition-setup/blob/master/static/asimba/asimba.xml#L603

**Comment by dmogn** [comment]
Done.
