### ISSUE TITLE
Set ACR / Level for LDAP Password Authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#33]
There is no where to set the ACR or level associated with the default LDAP password workflow.

**Comment by yurem** [comment]
There is basic authentication method which is qual to LDAP passowrd authentication method:
https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/basic

It's possible to enable it and specify auth level/name if we need acr in oxAuth.

**Comment by yurem** [comment]
Fixed some time ago
