### ISSUE TITLE
Asimba IDP/SP metadata store should be persistent

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#333]
Asimba stores IDP/SP metadata in /opt/tomcat/webapps/asimba/WEB-INF/sample-data/{idp:sp}
It's exploded asimba.war folder. Hence we can easily lost  this metadata. Why we can't store this in LDAP IDP/requestor entries?

**Comment by nynymike** [comment]
We need to externalize this. We also need to make sure Arun knows to export this (and all Asimba) data for upgrade scripts.

**Comment by yurem** [comment]
@tecoholic

**Comment by dmogn** [comment]
Testing...

**Comment by dmogn** [comment]
Done.

**Comment by tecoholic** [comment]
@dmogn I would like to know the effect of this in version migration. Can you clarify the about the persistence? If the entire LDAP data is migrated, does it mean the Asimba Metadata and other config will be migrated too? We need not bother about the Asimba.war or any other folder in the filesystem to get this metadata.
