### ISSUE TITLE
Password reminder action uses wrong condition to enable/disable this functionality

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#334]
Right now this service activation status depends on:

```
    public boolean enabled(){
        GluuAppliance appliance = ApplianceService.instance().getAppliance();
        return  appliance.getSmtpHost() != null 
                    && appliance.getSmtpPort() != null 
                    &&((! appliance.isRequiresAuthentication()) 
                            || (appliance.getSmtpUserName() != null 
                                && appliance.getSmtpPasswordStr() != null))
                    && appliance.getPasswordResetAllowed()!=null 
                    && appliance.getPasswordResetAllowed().isBooleanValue();


    }
```

We need indendent option on organization page to allow enable/disable it.

This functionality depends on SMTP setting. We need to keep this condtions but show message to user instead of showing blank green page.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20240205/96da4cbe-a938-11e6-9ba3-d03b556049f8.png)

**Comment by shekhar16** [comment]
The flag is already present i.e passwordResetAllowed.

**Comment by nynymike** [comment]
This should be tested during regression testing.
