### ISSUE TITLE
Error editing users in web UI

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#337]
From one issue.
The Gluu 2.4.4 installation is OK and server is running fine although I am not able to edit or add new users due to a validation error "value must be shorter or equal to 60 characters."
Eg. If I edit the admin user. Click update without making any changes, I get the above error appear on the memberOf attribute.

We need to enforce text filed length. We can do next:
1) Set max lenght for all fields to 4000
2) Add new attribute to attribute entry to specify max text length. Default value will be 4000.

@nynymike what do you think?

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/335

**Comment by shekhar16** [comment]
Please let me know the length validation for Add new user fields.

**Comment by shekhar16** [comment]
As per Mike's discussion, we should make validation configurable.
So can we add validation attributes in these custom attributes?
so that we can told customers that they can alter the length and required validation.

**Comment by yurem** [comment]
We can store validation information in one metadata attribute in JSON format.
Example:
oxValidationRule:
{ type: "string"/"integer"/"etc",
minLenght: -1 ... MAX_VALUE,
maxLenght: -1 ...MAX_VALUE,
....
}

**Comment by yurem** [comment]
This allows to store all required infromation need for proper validation in one attribute. Our LdapEntryManager supprot JSON attribute type.

@shekhar16 implementation will be simular to imap user attribute data

**Comment by shekhar16** [comment]
Fixed.
Currently we handled minlength, maxlength and regex pattern with configuration (oxvalidation attribute type).

**Comment by yurem** [comment]
We also need to add these options to attribute metadata form to allow start using this functionality. We can't offer to add this attribute manually to LDAP

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/2064a9b00fd29c9cc7ec740cc1ba427aad5b55f9

**Comment by shekhar16** [comment]
Fixed.
View added to set validation properties.

**Comment by yurem** [comment]
When I try to add new attributes to attribute metadata I get:
WARNING: /WEB-INF/incl/attribute/attributeForm.xhtml @190,191 value="#{_attribute.attributeValidation.regexp}": Target Unreachable, 'attributeValidation' returned null on 'org.xdi.model.GluuAttribute'
javax.el.PropertyNotFoundException: /WEB-INF/incl/attribute/attributeForm.xhtml @190,191 value="#{_attribute.attributeValidation.regexp}": Target Unreachable, 'attributeValidation' returned null on 'org.xdi.model.GluuAttribute'
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:100)

**Comment by yurem** [comment]
There is duplicity in code
    @LdapAttribute(name = "gluuRegExp")
    private String regExp;

And there is similar property in AttributeValidation.regexp

**Comment by shekhar16** [comment]
so we should remove 'gluuRegExp' or oxValidation ?

**Comment by nynymike** [comment]
yes, use your best judgement. If it's not needed, remove it.

**Comment by yurem** [comment]
For me it's more attractive to keep AttributeValidation.regexp because this object hold values in JSON.

Can you also remove 'gluuRegExp' from LDAP schema to keep it smaller?

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/977451127ac3c69b6f78c025267867e3894ab100

**Comment by yurem** [comment]
Fixed
