### ISSUE TITLE
Long loading times after upgrading using the import script

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/oxTrust#338]
While testing the import script, it was noticed that the loading time is very long after the import when compared to the loading time before the import.

Here are the logs:
- [wrapper.log.txt](https://github.com/GluuFederation/oxTrust/files/443122/wrapper.log.txt) = initial loading when the server was installed and setup 
- [wrapper2.log.txt](https://github.com/GluuFederation/oxTrust/files/443123/wrapper2.log.txt) = tomcat restarted by the import script
- [wrapper3.log.txt](https://github.com/GluuFederation/oxTrust/files/443124/wrapper3.log.txt) = after the gluu-server was restarted with `service gluu-server-2.4.4 restart`

```
wrapper.log:INFO   | jvm 1    | 2016/08/29 16:07:19 | INFO: Server startup in 158517 ms
wrapper2.log:INFO   | jvm 1    | 2016/08/29 16:16:30 | INFO: Server startup in 145276 ms
wrapper3.log:INFO   | jvm 1    | 2016/08/29 16:34:30 | INFO: Server startup in 576697 ms
```

The main reason seems to be the creation of SecureRandom for session ID.

```
wrapper.log:INFO   | jvm 1    | 2016/08/29 16:07:09 | INFO: Creation of SecureRandom instance for
 session ID generation using [SHA1PRNG] took [123,313] milliseconds.
wrapper2.log:INFO   | jvm 1    | 2016/08/29 16:16:19 | INFO: Creation of SecureRandom instance for
 session ID generation using [SHA1PRNG] took [112,449] milliseconds.
wrapper3.log:INFO   | jvm 1    | 2016/08/29 16:34:19 | INFO: Creation of SecureRandom instance for
 session ID generation using [SHA1PRNG] took [543,660] milliseconds.
```

Notice  that the time taken in wrapper3 is **5 times** the original load times. The lines which indicate the reason are in `wrapper3.log`:

```
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [543,660] milliseconds.
Aug 29, 2016 4:34:19 PM org.apache.catalina.session.StandardManager doLoad
16:34:19 | SEVERE: IOException while loading persisted sessions: java.io.StreamCorruptedException: unexpected EOF in middle of data block
16:34:19 | java.io.StreamCorruptedException: unexpected EOF in middle of data block
```
1. What is causing this delay?
2. It seems to point to some shortcoming in the upgrade scripts. Is the delay due to the upgrades?
3. What can be done to fix this?

**Comment by willow9886** [comment]
@tecoholic can you comment on / add a milestone to this issue ?

**Comment by tecoholic** [comment]
@yurem Is this situation still worth investigating? If not, kindly close this.

**Comment by yurem** [comment]
We can close it. Now we uses jetty instead of Tomcat and Orcale JRE instead of OpenJDK. I never saw this delay under 3.0.0 BetaX
