### ISSUE TITLE
Remove OpenDJ Schema Update for Add Attribute

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#339]
We should remove the connector to OpenDJ that updates the schema automatically. The Gluu Server admin should make sure the attribute is available in the LDAP schema. We should rename this process from "Add Attribute" to "Register Attribute"

**Comment by uboznikov** [comment]
@nynymike Will this mean that new attributes can no longer be created on the fly to be used as SCIM 2.0 User Extensions? Would there be alternatives?

**Comment by nynymike** [comment]
Yes, better to throw an objectclass violation. The Gluu Admin should add the schema properly and register it through oxTrust or LDIF.

**Comment by yurem** [comment]
oxAuth/oxTrust not uses any special connector to do schema changes. It uses generic ldap/ldaps to send ldif to do that:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxtrust-config.json#L40

As  result oxTrust updates only custom files: X-SCHEMA-FILE '100-user.ldif' and X-SCHEMA-FILE '99-user.ldif'

Should we remove this convenient functionality from oxTrust and SCIM?
Also after removal this from oxTrust any other application still can send schema updates ldif.

**Comment by nynymike** [comment]
Yes, I think we should remove it. Proper LDAP schema configuration should be a pre-requisite. This will encourage better schema management hygiene.

**Comment by yurem** [comment]
I understand.
I offer additionally apply some changes to attributes lists to notify admin about changes and avoid many questions.
We need to highlight in attributes list attributes which not have definition in LDAP schema.
oxTrust already loads all LDAP schema. So, I think it will be not problem to do that.

**Comment by nynymike** [comment]
Perhaps we should just remove ldif for attributes that are not available in our default ldif files? Which are you thinking about? I wasn't aware any of these existed.

**Comment by yurem** [comment]
There is no custom attributes in CE according to: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/100-user.ldif

But next workflow can be possible after removing custom attributes auto creation:
1) Admin add new attribute metadata.
2) We notify him that he should update schema.
3) He forget to update schema.
4) Developers are going to use new attribute in SCIM and get errors..

**Comment by yurem** [comment]
[21:04:34] Yuriy Movchan: It's regarding attributes metadata
[21:04:48] Yuriy Movchan: We need to remove part which update schema
[21:05:32] Yuriy Movchan: Instead pf schema update we need to show message to admin that he need to do this manually...

**Comment by shekhar16** [comment]
@nynymike @yurem I removed that schema update code but after that the add person functionality is not working due to Caused by: Connection exception (LDAP config error: schema violation contact LDAP admin.: Entry inum=@!C1DE.5DC8.64E1.6104!0001!E1F2.A9D2!0000!A995.69F9.258F.E4A5,ou=people,o=@!C1DE.5DC8.64E1.6104!0001!E1F2.A9D2,o=gluu violates the Directory Server schema configuration because it contains an unknown objectclass ox-C1DE5DC864E161040001E1F2A9D2)

**Comment by yurem** [comment]
I think we need to remove all references to custom object class too

**Comment by nynymike** [comment]
I totally agree! I hate that ox-[org-inum] objectclass!

**Comment by shekhar16** [comment]
@yurem you mean to say we need to find out ldap files where its references are present and we need to comment them.

**Comment by nynymike** [comment]
To support dynamic schema, we created an objectclass that was  ox-(org-inum) for example, `ox-C1DE5DC864E161040001E1F2A9D2`  This objectclass will no longer be created. So we need to find any references to this objectclass and remove them.

**Comment by shekhar16** [comment]
@nynymike @yurem 
I tried this and added the attribute successfully.please refer below for configuration.

![image](https://cloud.githubusercontent.com/assets/15937500/20864572/5eb63c40-ba1c-11e6-9748-366b0c56b8fb.png)

**Comment by shekhar16** [comment]
But there is problem in add person.
I removed the file 100-user.ldif file as it has reference ox-xxxxx
if we are adding attributeOrigin='gluuPerson' in attribute than schema violation.

Any Suggestions.

**Comment by yurem** [comment]
Fixed. All references to commits in issue https://github.com/GluuFederation/oxTrust/issues/414
