### ISSUE TITLE
Add TrustRelationship - Logout URL Error

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#340]
Error in UI field validator - with valid URL checking:
![addtrustrelationshiplogouturlerror](https://cloud.githubusercontent.com/assets/14166017/18203820/af45d4f2-70ef-11e6-9227-b99af6ee32be.png)

**Comment by dmogn** [comment]
gluu-server 2.4.4; Ubuntu 14.04_64

**Comment by shekhar16** [comment]
Fixed.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 @yurem 

Still can be reproduced in 2.4.4 + SP2. Shouldn't we included this in final SP2 release? Seems like serious issue to me.
