### ISSUE TITLE
SCIM: Unable to delete a user after creating it with v1.1 API

### ISSUE THREAD

**Issue by frgtn** [GluuFederation/oxTrust#342]
After creating a user via SCIM v1.1 API I'm no longer able to delete it. The logs show the following LDAP error:
```
Failed to delete entry: The entry 'inum=@!2027.861B.4505.5885!0001!200B.B5FE!0000!F680.C3CA,ou=people,o=@!2027.861B.4505.5885!0001!200B.B5FE,o=gluu' cannot be removed because it has subordinate entries
```
Both v1 and v2 endpoints have this problem. Admin GUI is also unable to remove the user but no error message is displayed.

As a sidenote - both v1 and v2 endpoints return HTTP 404 instead as error which is probably not a good thing.

GLUU version: 2.4.0 Community Edition.

Full traceback:
https://gist.github.com/frgtn/8489e096cc521960261345cbe4b0e11d

**Comment by willow9886** [comment]
Hello, 

Please report issues on our [support portal](http://support.gluu.org). The first and best place to start is to upgrade your Gluu Server to the latest version.. 2.4.4. 

Thanks.
