### ISSUE TITLE
InCommon R&S should not be visible for everyone

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#343]
It makes no sense that every customer sees this checkbox for InCommon R&S when only a small percentage of our customers are members of InCommon (or even US higher education institutions). 

![Add TR screenshot](https://cloud.githubusercontent.com/assets/3717101/18284073/0f5f447c-742e-11e6-8eae-20375e1f9578.png)

This feature should be enabled|disabled in the properties, and the checkbox should normally be hidden.

**Comment by shekhar16** [comment]
do we need to add any flag in ldap or properties file?

**Comment by shekhar16** [comment]
Fixed.

**Comment by uboznikov** [comment]
@shekhar16 I pulled and now it seems the TR form is clipped; I particularly could not see the Released Attributes section. Could you please check, thanks. You may also compare the TR forms of ce-dev and ce-prev-version.

Before:
![tr-form-full](https://cloud.githubusercontent.com/assets/16329085/19030722/3ed0efda-8982-11e6-8419-5a0e58d8ebd4.png)

After:
![tr-form-no-released-attributes](https://cloud.githubusercontent.com/assets/16329085/19030727/4c7cb2ea-8982-11e6-98e3-d63a10236be3.png)

**Comment by shekhar16** [comment]
@uboznikov this is new federation metadata page is redesigned please see https://github.com/GluuFederation/oxTrust/issues/310

**Comment by uboznikov** [comment]
I see, so if my Entity Type = Single SP, I should already see the rest of the form? I have an existing TR and entity type does not seem to be detected, is this intended? Thanks.

**Comment by shekhar16** [comment]
YES :)

**Comment by yurem** [comment]
Honestly speaking I would like to offer rename developer style property name "oxIncommonFlag" to "enableResearchAndScholarship" or "enableSamlInCommon"

**Comment by nynymike** [comment]
Let's re-evaluate this after 3.1 release.

**Comment by otataryn** [comment]
Is there anything left to do within this issue?

**Comment by willow9886** [comment]
Sounds like we should move it to Milestone 3.1. Doing so now...

**Comment by willow9886** [comment]
fixed.
