### ISSUE TITLE
TR download metadata file in background

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#349]
On TR save server is trying to download this metadata file fully. A result user is waiting at leas one minute. Download and validate metadata in background (i.e in new thread.).and We should also check if remote resource exists and cancel download it.

**Comment by yurem** [comment]
We need to close connection after checking if resource exists.

Also how are you going to sync metadata loading and metadata validation timers? If metadata is very big system can start validation earlier than it will be downloaded.

**Comment by shekhar16** [comment]
When it is completely downloaded , than only  we are adding it in validation queue.So it is in sync for both metadata downloading and validation timer.

**Comment by yurem** [comment]
I added comments to commit: https://github.com/GluuFederation/oxTrust/commit/68398a44c5080bb69f98f00be8fa669c8ab6ecf1

Also I don't like method:
```
	@Asynchronous
	public void newThreadSaveSpMetaDataFileSourceTypeURI(UpdateTrustRelationshipAction updateTrustRelationshipAction){
	...
        updateTrustRelationshipAction.
```
We should not pass instance of action to service. If we need instance we need to call Seam methods to do that.

Why we can't just set status of TR to "Download metadata" and update validation timer to use this as flag to trigger it download?

**Comment by nynymike** [comment]
Should this issue be closed?

**Comment by shekhar16** [comment]
@nynymike yes we cann close this issue.
