### ISSUE TITLE
Configure if Scope is visible in OpenID Connect discovery

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#35]
It would be nice if there was a checkbox that controlled whether a scope was published to OpenID Connect discovery. We may need a new LDAP attribute (oxAuthDiscoverable?) to the oxAuthCustomScope objectclass

**Comment by yurem** [comment]
Is this issue still take place? Can you add more comment about it?

**Comment by yurem** [comment]
It's old enhancement. Should we implement it?

**Comment by nynymike** [comment]
It would be nice, but its not a huge priority. I'm assigning it to Javier if he has some downtime.

**Comment by yurem** [comment]
Closing it. No one ask about it during at least one year
