### ISSUE TITLE
Optimize TR update page

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#351]
The TR page with this metadata is very big: http://md.incommon.org/InCommon/InCommon-metadata.xml I get server error after some time. We should not load all federation URL on TR load. We should use filters. Once user enter keyword we should load only URL which conforms this filter. This will make U more user friendly

**Comment by shekhar16** [comment]
Fixed.

**Comment by willow9886** [comment]
@shekhar16 can you comment on the status of this?

**Comment by shekhar16** [comment]
@willow9886 it is fixed.
