### ISSUE TITLE
Re-Order fields in Add person

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#352]
![image](https://cloud.githubusercontent.com/assets/5271048/18561311/f5bb7590-7b44-11e6-85ca-fa0fefb97caf.png)

Let's re-order these fields to:

User Name
Display Name
First Name
Last Name
Email Address
Password
User Status

We should probably also add a field for "Confirm Password" underneath the first password field. 

Note: we should not display the password in clear text in this form. 

Note: should not be getting the "Please enter email" warning notice in top right corner during completion of the add person function. This type of error message should be reserved to if you try to save without entering required fields

**Comment by shekhar16** [comment]
I added confirm password field with its validation aswel.
Reordering for fields is not possible as these are displaying from attributes list.

**Comment by yurem** [comment]
Now we display attributes in the order which LDAP provides for us. Why we can't add new attribute to attribute metadata to allow specify order? In this case we can sort attributes by this property.
