### ISSUE TITLE
Support TR without Metadata

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#353]
Some SP's don't provide metadata--they just provide the ACS url and a binding. Right now, we require customers to make their own metadata for these SP's, and upload it. It would be nice if we had a way to enter this information in a form, and just generate the metadata for the customer.

**Comment by SteveByerly** [comment]
Can you confirm exactly what i'd need to do to get around this? Do I simply need to take the metadata file linked by @yurem and swap out the vars with my own values?

**Comment by nynymike** [comment]
Y

**Comment by uboznikov** [comment]
Also:
https://github.com/GluuFederation/oxTrust/blob/master/configuration/template/shibboleth2/idp/sp-metadata.xml.vm

v3:
https://github.com/GluuFederation/oxTrust/blob/master/configuration/template/shibboleth3/idp/idp-metadata.xml.vm
https://github.com/GluuFederation/oxTrust/blob/master/configuration/template/shibboleth3/idp/sp-metadata.xml.vm

**Comment by shekhar16** [comment]
@nynymike should we design new page for this, containing GluuSAMLTrustRelationship's fields and create files ?

**Comment by nynymike** [comment]
A modal window could be ok too. Perhaps if we add a value to Metadata as "None" it pops up a modal window?

**Comment by nynymike** [comment]
Let's re-evaluate after move to Shib IDPv3.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21133612/afdd0070-c13f-11e6-85b4-eaad47bb8c92.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/9e935fd45e24d906707de7a44b600078114f9e59

**Comment by shekhar16** [comment]
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="C1DE5DC864E161040002D4F5933600064B406DF2">
  <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol">
    <md:Extensions>
      <DiscoveryResponse xmlns="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Binding="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Location="http://localhost:8080/Shibboleth.sso/DS" index="1"/>
    </md:Extensions>
    <md:KeyDescriptor>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>

MIIDYjCCAkoCCQCApPedCQkKtjANBgkqhkiG9w0BAQUFADBzMQswCQYDVQQGEwJJ
TjELMAkGA1UECAwCTVAxDzANBgNVBAcMBmluZG9yZTENMAsGA1UECgwEZ2x1dTEW
MBQGA1UEAwwNZ2x1dWNlbnQuaW5mbzEfMB0GCSqGSIb3DQEJARYQc2hla2hhckBn
bHV1Lm9yZzAeFw0xNjExMjAwNjU3MzFaFw0xNzExMjAwNjU3MzFaMHMxCzAJBgNV
BAYTAklOMQswCQYDVQQIDAJNUDEPMA0GA1UEBwwGaW5kb3JlMQ0wCwYDVQQKDARn
bHV1MRYwFAYDVQQDDA1nbHV1Y2VudC5pbmZvMR8wHQYJKoZIhvcNAQkBFhBzaGVr
aGFyQGdsdXUub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnNkq
vFhilkQh3fQdELm3rzqWzqa+0LVyfB/wYS36fXLH8iXtplVOroTkGv8j8QzLmUFG
YnIN8ZkDx3BTxvsSpfwd1t0RRSmeiV/CVkP/1kO+926QeZpSBvFMqnEf9d91y8WS
IqsBMUb3T5FEy8MPRt0+x8/FAmJ2CGecNhl93W66zCg6rPb+/QUrbzks7sllN3Og
eKHJrBDlWO+0PZIZKqYp9w24IoeZZD1wfOSPjulxk5x8NhebXw4JDNWbxbR7d6NV
6P/aB0/yKfVRVNMYM+Fpcvs95i4uj+G1UHZ846coWNjS4O7eBoGMLiNAY9seab4/
qRziDk3CaeNfLmgT8QIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQBxP9rBw8OPQkys
pIOo321jb13t7AsCoIXjztkEmpLMLXAmoinDEw0dfOA0QAAzrH8r/L9wRpGXk2i4
JnEYanwkSQoFvyV8jURBZc58atkBizWP9VCjZR5OCltLb+4Tvz4FuF2RbzinULAI
xqXaIFEyXe5Yl6SYRaw/sZPIcuDcxARn77z3hj+5Q7rKnyjnWlwBP4fPASKbDdW0
K5MLR/uePVG4VlFtdWaE3J5l6CHzOAEN6zRmizE36jlRMn0lQqoDA1dk16E/4H/5
pRK3e7Osr6FurJ/MlWgtkfJAxzFAYvYbvGYjXetaBPNPAtTjTH7y8Qh8paWSnbuq
FjxujzQX


          </ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/Shibboleth.sso/SAML2/POST" index="1"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="http://localhost:8080/Shibboleth.sso/SAML2/POST-SimpleSign" index="2"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:8080/Shibboleth.sso/SAML2/Artifact" index="3"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:PAOS" Location="http://localhost:8080/Shibboleth.sso/SAML2/ECP" index="4"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:browser-post" Location="http://localhost:8080/Shibboleth.sso/SAML/POST" index="5"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:artifact-01" Location="http://localhost:8080/Shibboleth.sso/SAML/Artifact" index="6"/>
  </md:SPSSODescriptor>
</md:EntityDescriptor>

**Comment by shekhar16** [comment]
Fixed.
