### ISSUE TITLE
Default password reset email contents

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#356]
See ticket here: https://support.gluu.org/customization/customisation-of-reset-password-email-template-3264/

We should change the default email content anyways. Let's use the below as a sample:

![image](https://cloud.githubusercontent.com/assets/5271048/18716266/cc4d84f4-7fe1-11e6-9cab-a34ff0611c42.png)

**Comment by shekhar16** [comment]
Fixed.
The contents are updated.

**Comment by yurem** [comment]
We need to allow customer to write own message. We can move this hard coded message to new xhmtl page. Application can render xhtml->html in order to send it. This allow to override xhtml page via customization functionality.

**Comment by willow9886** [comment]
@yurem should we keep this open?

**Comment by nynymike** [comment]
Moving it to 3.1... because I hate the password reset mechanism in oxTrust anyway.

**Comment by nynymike** [comment]
Gene, assigning this to you because it should support localization. See Yura's comment about supporting a custom message template.

**Comment by yurem** [comment]
Custom xhtml works fine, but I commented out code due to conflict with Richfaces. we need o resolve https://github.com/GluuFederation/oxTrust/issues/768 first and try to enable them back.

**Comment by chrissnyder2337** [comment]
Is there a patch I can leverage apply to bring this functionality to my server before 3.1.5 is released?

**Comment by willow9886** [comment]
We opened a new issue for changing the language of password reset and post registration emails here: https://github.com/GluuFederation/oxTrust/issues/1362

**Comment by natt-tester** [comment]
@willow9886, @syntrydy, the Reset Email template looks like this in 3.1.5_3:

<img width="449" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50056299-684be700-015a-11e9-9bea-0ab98263d461.png">
