### ISSUE TITLE
Too many arrows in OIDC Clients list page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#357]
![image](https://cloud.githubusercontent.com/assets/5271048/18725425/dd557e04-8005-11e6-9f96-4b9b785ab076.png)

I'm not sure why we have three sets of arrows... We only need two sets of arrows at most... 

`<<` / `>>` takes you to the first or last page
`<` / `>` takes you to the previous or next page. 

Let's make sure all other lists inside oxTrust also don't have unnecessary scrolling arrows.

**Comment by shekhar16** [comment]
Fixed. :)

**Comment by sahiliamsso** [comment]
Can we have double arrow >> to move last page instead of »»»» , and > instead of »
