### ISSUE TITLE
oxTrust logs throwing errors everytime check_ssl is ran

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/oxTrust#36]
Whenever /usr/local/bin/check_ssl is ran, which in turn runs the below command:
check_ssl_cert.sh -H `hostname`

we get error like:
SSL_CERT CRITICAL ganesh.gluu.org: Cannot verify certificate\nself signed certificate|days=365;;;;

Now, to tackle this, I've used: "-s" option in the command:

check_ssl_cert.sh -s -H `hostname`

The sample run looks like:
GLUU.root@ce:~# check_ssl_cert.sh -s -H hostname
SSL_CERT OK - X.509 self signed certificate for 'ganesh.gluu.org' from 'ganesh.gluu.org' valid until Feb 20 07:40:19 2016 GMT (expires in 365 days)|days=365;;;;
GLUU.root@ce:~# echo $?
0
GLUU.root@ce:~#

$? = 0 shows that the command ran successfully.

But despite this, the oxTrust logs show:
2015-02-20 10:22:16,276 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] check_ssl retuned an unexpected value

Which is not expected and should be rectified.

You can refer to this from: https://github.com/GluuFederation/ce-ubuntu/issues/3

**Comment by ganesh-at-wiw** [comment]
Please guide if you think something needs to be corrected.

**Comment by otataryn** [comment]
Native check_ssl and check_ssl_cert_alternative.pl -H on Centos just returns a number of days, so that is what is expected in code. 
GLUU.[root@ce community-edition-setup-master]# check_ssl
364

retuned an unexpected value
means that check_ssl returned something that cannot be considered a number. 

Is there any way to make check_ssl_cert.sh -s -H hostname return a number?

**Comment by yurem** [comment]
There is python version of this command: https://github.com/GluuFederation/gluu-util/tree/master/check_ssl
We are planning to migrate to this command in next CE in order to remove python from dist,

**Comment by mzico** [comment]
Just to give you a note: 
I just installed our wildcard cert in https://ubuntu.gluu.org

Also configured intermediate/root cert. But still I am getting: 

GLUU.root@ubuntu:/etc/apache2/sites-enabled# check_ssl
SSL_CERT CRITICAL *.gluu.org: Cannot verify certificate\nself signed certificate|days=363;;;;
GLUU.root@ubuntu:/etc/apache2/sites-enabled#

BTW, I am using 2.1 deb

**Comment by nynymike** [comment]
Can you paste in the Apache SSL configuration?

**Comment by ganesh-at-wiw** [comment]
Yura, the python version of check_ssl command works fine at Ubuntu as I just checked it out.
But I do not see the python version included there in CE.
When are we planning to include it?

**Comment by ganesh-at-wiw** [comment]
If it's okay to leave it for now, then we can close the issue.

**Comment by ganesh-at-wiw** [comment]
Since now the check_ssl works in both rpm and deb alike, though in latest versions.
I've assigned it back to Oleksiy, so that he can add another layer to the error in oxTrust logs.

**Comment by yurem** [comment]
I think it's part of CE. You tested it in 2.2 beta vesion

**Comment by otataryn** [comment]
I'm adding SSL_CERT CRITICAL errors as an expected output in case something is wrong

**Comment by yurem** [comment]
Current version of cehck_ssl always return number:
https://github.com/GluuFederation/gluu-util/blob/master/check_ssl/check_ssl.py

There is no SSL_CERT CRITICAL return code or message now.
