### ISSUE TITLE
SCIM v2.x Users resource endpoint returns empty list if count is omitted

### ISSUE THREAD

**Issue by stakoz** [GluuFederation/oxTrust#360]
According to the [specs](https://tools.ietf.org/html/rfc7644#section-3.4.2) a resource type endpoint should return a list of resources if a `totalResults` is a non-negative. Unfortunately, it looks like a pagination mode is always enabled and that yields no `Resources` if an HTTP query parameter `count` [is missing](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/UserWebService.java#L117). I guess it happens because a corresponding method declaration initializes a `count` argument to 0 if it [is missing]( https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/UserWebService.java#L72). I think optional arguments should be declared as classes, i.e. `Integer` instead of `int`, and only applied if there was an actual value passed as a query parameter.

**Comment by willow9886** [comment]
@uboznikov can you give this issue a milestone?

**Comment by shekhar16** [comment]
@stakoz are you using SCIM client Api to call web services?
