### ISSUE TITLE
WhiteList / BlackList validation for redirect_uri's

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#361]
Implement WhiteList/BlackList validation of redirect URIs in oxTrust UI.

See https://github.com/GluuFederation/oxAuth/issues/301

**Comment by shekhar16** [comment]
Fixed.

https://github.com/GluuFederation/oxTrust/commit/5ff398e2f25d76d6291d23d382247ce5b31d7be2
https://github.com/GluuFederation/oxCore/commit/be4309010d7943e387a8d6b9dc7d4f9051561b43



Added UI to add the white-list uri and blacklist uri.
Added white-list/blacklist uri validation for client's logout redirect uri and login redirect uri.

**Comment by shekhar16** [comment]
To test this, please add whitelist uri and blacklist uri from below page:
Json Configuration-> oxtrust configuration.
