### ISSUE TITLE
Enable GET /user SCIM request to specify Persistent Person ID as search filter

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#364]
Pairwise id's return a different `sub` identifier for each client (or set of clients as specified in the sector_identifier_uri). There are two strategies supported by the Gluu Server for pairwise id's: (1) algorithmic and persistent.  Algorithmic uses a hash of the client_id or sector_identifier_uri to create a unique `sub`, but does not store this anywhere on the Gluu Server LDAP. Persistent pairwise id's (PPID) stores the id as a sub-entry under the person entry in LDAP. 

![image](https://cloud.githubusercontent.com/assets/3717101/19045197/1e7f025a-895d-11e6-8256-28a4c8b5e52d.png)

Because the PPID is a sub-entry, it's not possible to use the PPID as an attribute to search `/users`

One solution may be to add a new endpoint to search for PPID's. For example, see a very similar requirement for FIDO devices, which also exist as a sub-entry under the person.
- [Added FidoDevice to /Schemas endpoint](https://github.com/GluuFederation/oxTrust/commit/b6bb3a11a900847d68a8aaa29e1e2e356554d40d)
- [Added SCIM 2.0 FidoDevices](https://github.com/GluuFederation/oxTrust/commit/229411475d5d5e10819d7aa359cfdfe7de3c124b)

However, this may be overkill. Perhaps we should add some business logic to the `/users` endpoint to handle this special attribute query.

Please post a design for approval, and then prioritize this issue.

Note, to test this you're going to have to enable a test OpenID Connect website where the client is configured for pairwise id's. 

![image](https://cloud.githubusercontent.com/assets/3717101/19045453/83f6089e-895e-11e6-96dc-733e86391cd3.png)

In the JSON config for oxAuth, you will also need to set pairwiseID type to persistent:
![image](https://cloud.githubusercontent.com/assets/3717101/19045538/fa3f03c0-895e-11e6-9246-2aef84fe0c8e.png)

**Comment by uboznikov** [comment]
@nynymike I think we could not include this to the core User schema, as the spec does not mention this possibility, but the spec does say that we could add new resources. So I think the design for this, at least for the SCIM side, should follow that of FIDO devices' as a new resource. And also, as I understand these are not to be created and modified inside of SCIM?

@shekhar16 You can refer to the FIDO devices Web service as the starting point of everything.

[FidoDeviceWebService.java](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/fido/FidoDeviceWebService.java)

And as per the spec, `/Schemas` and `/ResourceTypes` endpoints should also reflect this. Please see [SchemaWebService.java](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/SchemaWebService.java) and [ResourceTypeWS.java](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/ResourceTypeWS.java)

SCIM 2.0 specs for reference: [RFC 7643](https://tools.ietf.org/html/rfc7643), [RFC 7644](https://tools.ietf.org/html/rfc7644)

**Comment by nynymike** [comment]
I think it's right. If we needed SCIM to delete a PPID, we'd need this is as a resource.

**Comment by nynymike** [comment]
I have another idea how to solve this. What if we write the PPID as a multi-value attribute in the user entry. We can leave the sub-entry with the extra metadata as is...

**Comment by uboznikov** [comment]
This is also feasible and PPID can be added as a User extension. We can ship Gluu with this extension turned off and this can be manually enabled by customers who only need it (just like `oxEnrollmentCode`).

**Comment by uboznikov** [comment]
If this is added as a User extension there is no need to update code in both `oxTrust` and `SCIM-Client`, and the only thing to do is write unit tests in `SCIM-Client`.

**Comment by nynymike** [comment]
Well, PPID management is not really that critical. I think its just search that we need. I think we should go with the quick solution, and if we see a future requirement for full management (delete, modify), then we should add the user extension.

**Comment by uboznikov** [comment]
If search should only be available function for the meantime, then I think adding this as a new resource would be the cleaner implementation. The create / update / delete can just be turned off for now, and can be turned on in the future as the need arises, just like in FIDO devices where [create.](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/fido/FidoDeviceWebService.java#L218-L220) is disabled.

**Comment by nynymike** [comment]
I disagree... let's proceed with the attribute in the user entry: **gluuPPID** add to **gluuPerson** objectclass. The attribute should be added at the same time the sub-entry is created.
