### ISSUE TITLE
Failed to add new person if the status not "active"/"inactive"

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#365]
In order to reproduce it we need to try to add new person with any value in status field.

Why we can't limit user here? We can display dropdown list or checkbox...

**Comment by shekhar16** [comment]
@yurem I added status dropdown few months ago and code was also there in repo .It is working in my local.
Let me check what is difference in my local and env.

**Comment by shekhar16** [comment]
@yurem i checked the attribute.ldif in ce-dev env ,it is not updated.
I tried to update it  but couldn't able to replace inumOrg variable for inums
So please advise how we can update the attribute.ldif and its inum variables.

**Comment by shekhar16** [comment]
it is working now for 3.0

**Comment by mzico** [comment]
@shekhar16 : There is no drop down menu in 2.4.4.2 for 'User Status'. Screenshot attached. 


![screenshot_7](https://cloud.githubusercontent.com/assets/7156097/20716056/c44f141e-b616-11e6-84b3-f27ba9b09905.png)

**Comment by willow9886** [comment]
What should items should the drop down menu include? Just `Active` / `Inactive` ?

**Comment by mzico** [comment]
@willow9886 : yes.

**Comment by shekhar16** [comment]
@willow9886 @mzico  as per my above comments , I already added dropdown for status.
![image](https://cloud.githubusercontent.com/assets/15937500/20768061/8609825a-b762-11e6-91d9-96163cd2fbd2.png)

May be 2.4.4.2 doesn't contain latest code .

**Comment by mzico** [comment]
@shekhar16 : I am going to try 'https://repo.gluu.org/centos/6/gluu-server-2.4.4.2-1-5.centos6.x86_64.rpm' locally; however on [bug](https://github.com/GluuFederation/community-edition-setup/issues/221) blocked my update from previous version to this one. I'll inform you as soon as I can test.

**Comment by yurem** [comment]
Fixed
