### ISSUE TITLE
Default "internal" auth should use Name specified in Authn Config Panel

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#369]
We have 2 default methods of authentication for oxTrust and oxAuth on the "Manage authentication" page which exist right out of the box: "default" and "internal". By Mike's opinion, "internal" is not a good name for simple password (bind) authentication against LDAP directory (which it represents). Perhaps something like "simple_password_auth" or "simple_ldap_bind_auth" would be more appropriate?

**Comment by aliaksander-samuseu** [comment]
As I'm not totally sure what Mike had in mind, I'll better provide his quote as it is:
```
The default authn method actually has a Name value now
We should use that..
If you have a chance, we should make a github issue about this: Change "internal" to correct Name for default password authn.
```

So it's possible that correct name of it is already chosen, you may need to ask around about what it is in this case.

**Comment by nynymike** [comment]
Note: see this identical issue from last month: https://github.com/GluuFederation/oxAuth/issues/329

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/27eb434e81b6964a8529c9ff0babf0d68a9e0c9f

**Comment by shekhar16** [comment]
Fixed 
internal  -> simple_password_auth

**Comment by willow9886** [comment]
@yurem what is this status of this? Do we need to update our documentation? As you can see [here](https://gluu.org/docs/ce/3.0.1/admin-guide/oxtrust-ui/#default-authentication-method) we're still calling it "default authentication method" in our docs.
