### ISSUE TITLE
Uma Scope mapping missing

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#37]
In the old interface, you could associate UMA Scopes with policies.
![uma_old](https://cloud.githubusercontent.com/assets/3717101/6471332/8e019844-c1af-11e4-8db1-28258c7536ef.png)

In the new interface, this feature seems to have dropped off.
![uma_new](https://cloud.githubusercontent.com/assets/3717101/6471331/8c1584dc-c1af-11e4-8d3b-1a4f90683a61.png)

Without being able to associate scopes with policies, UMA won't work.

**Comment by yurem** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6104200/6508205/19706520-c360-11e4-90e3-6fec50908441.png)

**Comment by yurem** [comment]
In new interface all scripts in the same place.
But after adding new script it's possible to select it in UMA scope form.

**Comment by nynymike** [comment]
Ok, I guess its the same thing...
