### ISSUE TITLE
Wrong authentication graph in oxTrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#370]
As you can see in below screenshot, there are 29k/week authentication requests there which is not correct at all; this is not a live server and such amount of authentication is not correct. 

Is it possible to find out which code is generating this graph? If yes, then how this graph is generating? 
I think if we know how it's working; we will be able to move forward for further investigation. 

![graph](https://cloud.githubusercontent.com/assets/7156097/19351508/b8e68e50-9121-11e6-908b-fe6c48ac29b3.png)

**Comment by shekhar16** [comment]
@yurem I check the code this functionality only working on Linux system.But our development envirnments are on windows.
Any suggestions to fix it out.

**Comment by yurem** [comment]
@mzico is this graph from our development server?
