### ISSUE TITLE
CR should support different mapping for each backend

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#373]
Additionally we need to support mapping per backed to cover cases when customers have: Active Directory and other LDAP server.

**Comment by aliaksander-samuseu** [comment]
Just an idea (not sure whether it's possible, or easy to implement): can we also have different primary key attributes for each backend? As in mentioned case of AD and some other LDAP directory, attributes usually chosen as key for each will be different (like, samaccountname and uid). Currently to handle this we must look for some compromise, like to create a new attribute that will be present at each directory (and also will be unique across both sets of users).

**Comment by nynymike** [comment]
The whole point of the primary key is to correlate users across two different backends.

**Comment by nynymike** [comment]
Ok, we can leave this as an issue. Perhaps we can just add a way to specify if the operator should be AND or OR when you specify multiple primary keys.

**Comment by nynymike** [comment]
If a customer asks for this, we can open a new issue.
