### ISSUE TITLE
Cache Refresh Resulting Objectclass bug

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#374]
![image](https://cloud.githubusercontent.com/assets/3717101/19496086/93ee8ea8-954b-11e6-8bf8-92d1b2bb982f.png)

This was mis-implemented. It was supposed to be used to specify the resulting objectclass of the person. Instead it was implemented to be a filter.  

For example, in the source directory the objectclass might be:
```
Top
User
inetOrgPerson
```

But in the Gluu Server, post-synchronization, I might want the resulting objectclass to be:
```
top
gluuPerson
acmePerson
```

For reverse compatibility, maybe we should introduce a checkbox where the admin can specify if the list should be interpreted as a filter.

**Comment by willow9886** [comment]
cc @yurem

**Comment by yurem** [comment]
@nynymike in oxTrust we already have properties which allows to specify list of OC in result entry:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxtrust-config.json#L18

Cache Refresh process also uses this list during adding/updating users.

The main idea was to use same list in all oxTrust parts to avoid issues. For example how to edit person entry if in CR admin specified anther OC...

**Comment by nynymike** [comment]
ok, agreed.
