### ISSUE TITLE
Add IDP v3 CAS protocol configuration GUI

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#377]
Mike Schwartz: There should be a config option in oxtrust JSON properties to enable CAS (because we don't want to see it in the oxTrust GUI unless its enabled...)
Mike Schwartz: and it needs to be tested...
Mike Schwartz: CAS is a pretty easy password protocol though.
Mike Schwartz: https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol.html
Mike Schwartz: https://wiki.shibboleth.net/confluence/display/IDP30/CasProtocolConfiguration

**Comment by dmogn** [comment]
Results of meeting with Zico:
- Yes, use memcached  for CAS session sharing (localhost:11211). We also need memcached replication.
- Details of used protocol extensions will be replied later.
- We can use this 'phpCAS' to test our CAS configuration for v3 https://wiki.jasig.org/display/casc/phpcas

**Comment by yurem** [comment]
We can try to comment out configuration block in our CAS config to avoid using memcached. A result we don't need to start/install memcached in CE. If someone need memcached he can install memcached package and uncomment these lines.

**Comment by yurem** [comment]
Where in this GUI it's possible to enable/disable CAS?

**Comment by dmogn** [comment]
@yurem 
![cas_gui](https://cloud.githubusercontent.com/assets/14166017/22160369/dfd4629e-df23-11e6-9344-528eaaaa98e6.png)

**Comment by dmogn** [comment]
Added in 3.0,0 Beta4

**Comment by dmogn** [comment]
TODO: lock/hide the form if IDP is not installed.

**Comment by nynymike** [comment]
Dmitry, please lock this form is the IDP is not enabled.

**Comment by dmogn** [comment]
>> Dmitry, please lock/hide this form is the IDP is not enabled.
Done.

**Comment by yurem** [comment]
@zamilskhan can you review it. @dmogn committed changes regarding this into 3.0.1

**Comment by nynymike** [comment]
Should this issue be closed?

**Comment by dmogn** [comment]
@nynymike - Yes. If no issues from QA.
