### ISSUE TITLE
No left/right scroll bar with sized down window

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#379]
![image](https://cloud.githubusercontent.com/assets/5271048/19735326/b506e02e-9b70-11e6-9962-41f7b73988ee.png)

As you can see in the above screenshot, when the interface window is sized down (or zoomed in) there is no way to scroll left or right to see the rest of the interface.

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20311202/e3b949ca-ab74-11e6-88e0-2c0dce5a3fd2.png)

**Comment by shekhar16** [comment]
Added horizontal scroll bar.

**Comment by willow9886** [comment]
@aliaksander-samuseu can you confirm this fix?
