### ISSUE TITLE
Registration for new user is not completing in CE

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#38]
oxTrust: 2.1.0.Final
oxAuth: 2.0.0.Final
Base CE: 2.1.0-Beta1
Platform: CentOS. 

How to reproduce:
1. "Enable" User Registration script ( Default. Setup coming with default CE installation. Same default "Custom Script" 
2. Go to "Configuration" --> "Manage Registration" 
2.1 Enable "Activate Invitation Links Management" 
3. Go to : https://<hostname>/identity/register

After completing the registration form, IDP is landing to below page: 

![screen shot 2015-03-04 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/7156097/6493458/634e23c0-c280-11e4-8a5c-3c6dccf8a373.png)

**Comment by otataryn** [comment]
Could not reproduce on latest oxTrust snapshot.
2.1 Enable "Activate Invitation Links Management" 
only allows for invited registration, so identity/register is inaccessible.
Enabling "Enable registration without invitation" allows user to be registered without any issues.

**Comment by mzico** [comment]
I will test again. Thanks Oleksiy.

**Comment by mzico** [comment]
@otataryn : I was able to reproduce the problem. Please ping me in chat if you want to discuss more.
