### ISSUE TITLE
Update error message for incorrect attribute

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#382]
Referencing [support ticket](https://support.gluu.org/customization/3435/add-custom-attribute-failed-to-create-entry/).

The error message when an incorrect attribute name is entered should be updated, as it suggests underscores can be used. Let's update the error message to: 

> Attribute name should contain only letters and underscores.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/4ddef1e67ebd7855ba865d04f4edeba6a4b6df1f

**Comment by shekhar16** [comment]
Fixed.
