### ISSUE TITLE
Page's background becomes truncated when certain menu items are selected

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#383]
Environment: CentOS 6.7, Gluu CE 2.4.4 SP2, Firefox 49.02 full stretched, screen resolution at 1360x768

No biggie/urgent too. Please check picture below. When "OpenID Connect" item group is selected it still looks nice, but if sub-item of this group is selected right after that, it becomes truncated.

![page_bottom_background](https://cloud.githubusercontent.com/assets/11802046/20033313/a67e85e8-a3ae-11e6-82cc-799294a2b1ab.jpg)

**Comment by shekhar16** [comment]
@aliaksander-samuseu this issue in not reproduced in latest code.Please check it again with latest build.
