### ISSUE TITLE
Deactivated SAML TR is activated as side-effect of clicking "Update" button

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#384]
Environment:
CentOS 6.7, Gluu CE 2.4.4 SP2

Preconditions:
1. Gluu was installed with Shibboleth module
2. Some valid SAML TR was created (i.e. it's already passed validation and is in "Active" state), then de-activated via web UI

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "Trust Relationships" page and open TR in question for editing
3. Make sure it's still in non-active state (button "Activate" must be present; also attribute can be checked in LDAP), then click "Update" button there.

Result:
TR becomes active, even if no changes were done to it before updating. Please see attached picture.

Expected result:
Clicking this button doesn't change this state of TR at all. Only clicking "Activate" button must activate it (this part is working fine atm)

![tr_active_update_btn](https://cloud.githubusercontent.com/assets/11802046/20033630/2614e6ec-a3b6-11e6-8ff8-c47df0c30ba6.jpg)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

When trying to reproduce, please take into account this other issue: #385 That may affect results you'll get, as under some circumstances, list of TRs may not show their actual states. To make sure you see the current states you need to move to some other page, then return to "Trust Relationships" page again and click "Search"

**Comment by shekhar16** [comment]
Fixed.
