### ISSUE TITLE
Update Add Attribute--> Transform to Attribute Registration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#387]
In old versions of oxTrust, when an attribute was added, we'd update the LDAP schema. This feature lead to bad practices, and also required a wierd objectclass, the ox-(org-inum) objectclass, which was used to catch custom attributes.

Going forward, customers should create their schema in the underlying DS, and "register" the attribute with Gluu--i.e. create the attribute entry under ou=attributes,o=(org-inum),o=gluu

**Comment by nynymike** [comment]
@shekhar16   I think this is a duplicate issue. If so, can you close this?

**Comment by shekhar16** [comment]
yeah sure.
