### ISSUE TITLE
Create UI to configure IDP Initiated SAML Authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#389]
Many customers are using IDP initiated authentication extensively.  It would be way better if we had some way to simplify this configuration through oxTrust. 

Also, see this page about shibboleth support:
https://wiki.shibboleth.net/confluence/display/SHIB2/IdPUnsolicitedSSO

**Comment by rajnikantsh** [comment]
The link https://github.com/GluuFederation/docs/blob/b44a986f6ed52c1a8da6e50830215a75f0f330ae/sources/how-to/idp_initiated_sso.md is broken.

**Comment by dnorthup-ums** [comment]
@willow9886 IdP-Initiated (Unsolicited) SSO has nothing to do with in-bound authentication flows. The nasty thing about it, in fact, is that there is no initial conversation with the SP before the user gets to the IdP. Frequently the vendors that insist upon using it also fail to supply metadata and expect the IdP maintainer to just guess and make metadata out of thin air. So, in more ways than one, nothing much inbound at all.
