### ISSUE TITLE
SAML submenu is hidden

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#391]
![hidden_saml_submenu](https://cloud.githubusercontent.com/assets/14166017/20318053/733d43a4-ab47-11e6-8d86-29fe2c135fed.png)

gluu-server-3.0.0_18-ALPHA1~trusty+Ub14.04_amd64.deb

Setup options:

Install oxAuth     True                                                                                               
Install oxTrust True                                    
Install LDAP  True  
Apache 2 web server   True 
Install Shibboleth SAML IDP    True 
Install Asimba SAML Proxy       True
Install CAS                   True
Install oxAuth RP       False

**Comment by willow9886** [comment]
Lets make sure we test that all menu's are properly exposed / hidden based on the installed components...  Thanks for opening this issue, @dmogn .

**Comment by yurem** [comment]
It's integration build. We need to check method to detect installed components. For instance you can check if exists:
/opt/web/asimba|cas|saml
or
/etc/default/asimba|cas|saml

**Comment by uboznikov** [comment]
@yurem I am checking it from oxTrust JSON property `shibboleth_version` which is set during install time and does not rely on some hard-coded path. Is this approach ok?


![saml-accordion](https://cloud.githubusercontent.com/assets/16329085/20338154/3b6ff196-ac10-11e6-8c02-c4af48b862fe.png)

**Comment by dmogn** [comment]
Asimba's submenu is hidden.

**Comment by dmogn** [comment]
Fixed for Asimba submenu.

**Comment by dmogn** [comment]
Has been detected again...

**Comment by dmogn** [comment]
/opt/web/jetty path changed to new /opt/gluu/jetty path

**Comment by dmogn** [comment]
Fixed.

**Comment by zamilskhan** [comment]
Problem confirmed in luu-server-3.0.0.x86_64 2-BETA1.centos6 package tested with Google Chrome and Chromium web browser. Asimba sub-menu is hidden although Asimba was installed.

```
GLUU.[root@centos community-edition-setup]# cat setup.properties.last | grep -i asimba
installAsimba=True
ldif_asimba=./output/asimba.ldif
```

**Comment by dmogn** [comment]
@zamilskhan
>> 2-BETA1
- Yeah. True. Has been fixed in master branch.

**Comment by yurem** [comment]
ProductInstallationChecker code looks fine. Please reopen it if needed.
