### ISSUE TITLE
Import / Export Schema

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#392]
People are having to recreate their attributes when moving environments (e.g. dev to prod). Would be nice if we provided a feature to export / importing all attributes as a file via an ldif.

Backup schema, and import schema in order to make it easier to move from dev to qa to prod, etc.

**Comment by shekhar16** [comment]
@willow9886 there few changes we made on attribute registration i.e https://github.com/GluuFederation/oxTrust/issues/339  and they are in Yuriy's plate to verify it.
Lets wait to finish attribute registration,so that the things will be clear to import/export bunch of attributes  from/to ldap.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23405166/05c7adb0-fddf-11e6-9ff4-3c067df87e49.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/b104fbd6f9f4effb8499056f3fb8e1608381e2ec

**Comment by yurem** [comment]
it's very powerful functionality. Is it check if it imports only attributes?

**Comment by mzico** [comment]
@willow9886: very nice. We can QA if required. 

Couple of questions: 

- I think we might need it when we upgrade from 2.4.x to 3.0.x, right? 
- If yes, do we have procedure available for such upgrade? 
- If no, then is it necessary when we will re-install a new server with same build ( say: old server is 3.0.0 and installed new server with 3.0.1 from setup.properties.last and other backup directory from old server )?

**Comment by shekhar16** [comment]
Presently it is supporting for all branches. And I m working for export LDIF functionality.

**Comment by shekhar16** [comment]
Now it will allow to import only attributes.

**Comment by yurem** [comment]
I've review code and updated it. It's ready for QA now. It's allows to load attributes meta-data only.
I offer to open another issue because this part requires more changes to make it useful:
- There is not export attributes functionality. User should be able to select attributes definitions needed to export.
- There is no validation during import that attribute with specified name already exists.
- Import not updates attribute DN. It should update atttributes DN to conform new org_inum

**Comment by shekhar16** [comment]
Export attributes ldif is completed.

**Comment by yurem** [comment]
It looks almost ready to use. The one question which bother me is:
- Import not updates attribute DN. It should update atttributes DN to conform new org_inum

It's useful for case when we do export on one machine but import tham on another one with.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/1b22ebb35c3cc5edf701b39b288eee71376d2903
