### ISSUE TITLE
add Asimba IDP sorting feature to 2.4.4.Final

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#397]
By Zico request

**Comment by mzico** [comment]
@dmogn : Do you think it's possible to add in SP2? But please talk to @yurem first to get green signal. 
If we can add that in SP2; it will be all synced... oxTrust / oxAuth .

**Comment by dmogn** [comment]
@yurem Could you rebuild SP3 in maven's repo?
http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.4.sp3/
Latest war date 15 Nov. Zico needs this patch ASAP.

**Comment by dmogn** [comment]
All fixes has been added to Asimba SP3.
