### ISSUE TITLE
Use Display Name instead of username to identify user in oxTrust

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#398]
![image](https://cloud.githubusercontent.com/assets/5271048/20677589/1baf2ea6-b559-11e6-9731-66ea734baf94.png)

When using SCIM, usernames are being generated in a pretty unreadable format. If we use Display Name it will be an easier to understand format for users.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20809615/9fa755fa-b82c-11e6-99a8-170778b64217.png)

**Comment by shekhar16** [comment]
Fixed.
