### ISSUE TITLE
gluu-server 3.0 oxTrust ui SAML2SSO configuration missing

### ISSUE THREAD

**Issue by shouro** [GluuFederation/oxTrust#405]
in gluu-server 3.0,
in add trust relationship page when I tick box of [configure relying party] I dont see clickable SAML2SSO profile. Basically from here I cant progress.

![screenshot from 2016-11-26 02 38 01](https://cloud.githubusercontent.com/assets/91414/20773609/d3c2805e-b77c-11e6-8d7d-b90ac97f1184.png)

**Comment by uboznikov** [comment]
@shouro You need to add additional attributes then save the form first. After this, edit the newly-created TR to add the relying party.

**Comment by zamilskhan** [comment]
Failed to create trust relationship

**Comment by uboznikov** [comment]
@zamilskhan What is the error? You need to search for it after creation. The page does not automatically search and display the list of TRs anymore as before.

**Comment by zamilskhan** [comment]
Hello, sorry for the delay. I get the following error when I try to add attributes in the Trust Relationship.
```
ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to save SP meta-data file FileUploadWrapper [contentType=null, fileName=411DCFEB5D667C860002C54A3FF4000654B2E284-sp-metadata.xml, fileSize=null, stream=null]
```
PS: When creating the Trust Relationship, I chose the attributes once, when I clicked `Add`, I saw a system error message in oxTrust and found the following snippet in the oxtrust log.
```
ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to save SP meta-data file FileUploadWrapper [contentType=null, fileName=411D
CFEB5D667C860002C54A3FF4000654B2E284-sp-metadata.xml, fileSize=null, stream=null]
```

**Comment by uboznikov** [comment]
Build 32-ALPHA1 on Ubuntu 14.04:

![shib-v3-sp-added-successfully](https://cloud.githubusercontent.com/assets/16329085/21132377/956f123c-c14e-11e6-85c6-dc7c474a3dc6.png)

Closing down this ticket. If opening a new one please include testing info (OS, build, etc.) and screenshots for easier troubleshooting.
