### ISSUE TITLE
Add creation and update stamp for users

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#406]
Can we add a non-editable field for create time and update time in the user record?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20867032/3b474656-ba61-11e6-8c1d-6c9b9bb098aa.png)

**Comment by shekhar16** [comment]
Added code to save created and updated timeStamp.

**Comment by shekhar16** [comment]
Fixed.
