### ISSUE TITLE
Purpose of 'Enabled' button in 'SP Requestors' and 'IDPs' page? 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#408]
Do we have any purpose of this 'Enabled' page? From UI side, I can't do anything. 
Do we need these? 
![sprequestorsenabled](https://cloud.githubusercontent.com/assets/7156097/20986285/8c4cca7a-bc8d-11e6-957b-7a5ff0dd95da.png)

**Comment by dmogn** [comment]
The property can be changed in IDP/SP edit page. It IDPs/SPs list they are ReadOnly.

**Comment by dmogn** [comment]
@mzico  - can I close the issue?
