### ISSUE TITLE
OpenID Scopes: Remove LDAP, Add OAuth

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#409]
I'm not sure where these default values are stored. It would probably make sense to move them to a JSON property. 

"LDAP" makes no sense--remove it.  Check the code... see if selecting this value has any meaning.

And I'd like to add "OAuth".  When this scope is selected, it should not be possible to select user claims. You can update the description. 

![image](https://cloud.githubusercontent.com/assets/3717101/21077157/1924ea06-bf07-11e6-8bfa-173d4ee116e4.png)

**Comment by yurem** [comment]
![default](https://cloud.githubusercontent.com/assets/6104200/21522704/9962a53e-cd10-11e6-8fe9-da5673388bde.png)

@nynymike UMA scope description page has different fields. How we can merge OpenId and UMA scopes descriptions dialogs?

**Comment by yurem** [comment]
It part of https://github.com/GluuFederation/oxTrust/issues/435

**Comment by zamilskhan** [comment]
Status check: fixed.
![ldap](https://cloud.githubusercontent.com/assets/7703245/22665391/d4765cfe-ecde-11e6-94bc-54252e53ad0c.png)
