### ISSUE TITLE
OpenID Manual Client Registration : Update Validation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#410]
The OpenID Connect Client Registration form should not throw errors because True|False select boxes have no values selected. Privacy protecting defaults should be used as the default. 

![image](https://cloud.githubusercontent.com/assets/3717101/21402666/324cb29a-c77f-11e6-817b-9fac7d25fce7.png)

![image](https://cloud.githubusercontent.com/assets/3717101/21402662/24cdef94-c77f-11e6-935b-bdcab3e04eca.png)

Also, client secret should not be required if `response type` == `token` | `token id_token` or `grant_type` == `implicit`.

**Comment by shekhar16** [comment]
HI Mike,
We had validations on the fields which are required, If user doesn't choose true|false than the validations get failed.

**Comment by shekhar16** [comment]
Not required condition applied on client secret field i.e.
response type == token or  response type==id_token or grant_type == implicit

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21505660/66bc742e-cc8f-11e6-87b9-c5c0506c74a9.png)
![image](https://cloud.githubusercontent.com/assets/15937500/21505670/782d3f22-cc8f-11e6-9221-0693ef0fa141.png)

**Comment by shekhar16** [comment]
Fixed.
