### ISSUE TITLE
Could not add custom attribute in GUI

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#414]
I am encountering errors when registering custom attributes in oxTrust GUI that were successfully added to the schema.

[Custom attribute(s) not added to OpenLDAP](https://github.com/GluuFederation/community-edition-setup/issues/224)

Build 32 ALPHA1 in Ubuntu 14.04.

![cant-add-custom-attr-oxtrust-gui](https://cloud.githubusercontent.com/assets/16329085/21255516/598e7450-c3a7-11e6-8533-564142de0fc9.png)

**Comment by willow9886** [comment]
@shekhar16 can you take a look at this.

**Comment by yurem** [comment]
Fixed
