### ISSUE TITLE
Fields for Passport should not be hard-coded

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#415]
![image](https://cloud.githubusercontent.com/assets/3717101/21269696/5a130676-c379-11e6-9c71-0b771f049234.png)

Provider should be called "Strategy"

Also, the params should not be hard coded in oxTrust. There could be any number of parameters. For example, see https://github.com/bergie/passport-saml, which has params: callbackUrl, path, protocol, host, entryPoint, issuer, cert, privateCert, decryptionPvk, signatureAlgorithm

The form should let you add a parameter, defining the name and the value. Both of which should be strings.

**Comment by shekhar16** [comment]
IN this case everything will be unpredictable, as user may make spelling mistakes (like instead of clientId user may clentid)  or other properties ,than it will be difficult to return required fields like clientid or client secret to send in web service response or may be response will also be unpredeictable ot handle on client side.
So please , make clarify the things so that in later the things will not be get disturb or the functionality may affected.

**Comment by willow9886** [comment]
@arvindsinghtomar can you help @shekhar16 with this?

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21475863/89d32f04-cb57-11e6-9dfb-1a7a656672bf.png)

**Comment by shekhar16** [comment]
{
  "passportStrategies" : [ {
    "id" : "twitterid",
    "secret" : "twittersecret",
    "clientname" : "twitter"
  }, {
    "clientid" : "fbid",
    "secret" : "fbsecret",
    "clientname" : "facebook"
  } ]
}

**Comment by nynymike** [comment]
I'm concerned that secrets may be displayed in plaintext.
When calling the API, it's ok.
But displaying in the GUI, it's a potential problem
maybe when you add a new field, there can be a checkbox for "password" ?
And if this box is checked, then the password is not shown (or just shows "************")

**Comment by arvindsinghtomar** [comment]
The key fields here will be used by passport server. The fields are to be matched in the passport server to set the strategies.

**Comment by shekhar16** [comment]
Previously I was sending this response , as the fields was predefined.
But for this generic implementation this would not possible because from now we have totally generic fields so we didn't know what fields user is going to add.
So we made response generic,irrespective of fields name and value.

**Comment by arvindsinghtomar** [comment]
We can have a fixed field called strategy and that can become the key to the passportStrategy. The field names in that strategy can be dynamic and can be added by the user.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21568092/8463591c-ced7-11e6-9260-4d9be804f2bd.png)

**Comment by shekhar16** [comment]
{
  "passportStrategies" : {
    "twitter" : {
      "id" : "twitterid",
      "secret" : "twittersecret",
      "clientname" : "twitter"
    },
    "facebook" : {
      "clientid" : "fbid",
      "secret" : "fbsecret",
      "clientname" : "facebook"
    }
  }
}

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
@arvindsinghtomar please test it and let me know if you found any issue in that.
