### ISSUE TITLE
oxtrust ui logouturi: spelled as "loouturi"

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#417]
Please fix spelling on "Generate SP Metadata" screen:
1. Login oxtrust UI
2. Click on "Add Trust Relationship"
3. Select Metadata Location* as None, This screen would show up:

Metatdata URL => should be Metadata URL
Loouturi => logouturi

![image](https://cloud.githubusercontent.com/assets/21104811/21374352/1ff64440-c74c-11e6-97fa-f0d98cac8d57.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21513520/94b5828a-ccdf-11e6-9563-d7fe20ff88dc.png)
