### ISSUE TITLE
Unable to delete Trust relationship from oxtrust ui

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#418]
Not able to delete Trust Relationship from Oxtrust UI

![image](https://cloud.githubusercontent.com/assets/21104811/21376155/bd918cda-c758-11e6-9b1f-65e70d121f9f.png)

Error in logs

```
2016-12-21 03:04:25,033 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name gluuPermission
```

**Comment by shekhar16** [comment]
@sahiliamsso  i tried it but it is working for me.can u please share the log.

**Comment by sahiliamsso** [comment]
working fine now. Thanks
