### ISSUE TITLE
Unable to add Login redirect URI in openID client via oxtrust UI

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#422]
OpenID Connect > Add Client > Add Login Redirect URI
URI trying to add: https://ubuntu.qa.info/identity/

![image](https://cloud.githubusercontent.com/assets/21104811/21445642/9977e698-c8e1-11e6-9689-29e930449762.png)

No error in oxtrust logs.

**Comment by nynymike** [comment]
What URL did you enter? Was it https?

**Comment by shekhar16** [comment]
@nynymike  there are few Blacklisted that are invalid to registered in ldap .so if we try to register these urls it will be going to validation failed.

**Comment by nynymike** [comment]
Yes, it makes no sense to use oxtrust as the redirect uri

**Comment by sahiliamsso** [comment]
none of the uri (https) seems to be working though.

**Comment by mzico** [comment]
@sahiliamsso @nynymike : I was trying to add a remote login url; it's failing with below error ( same as Sahild got ). Was trying to add 'http://192.168.0.105/blog/wp-login.php'. 

![screenshot_1](https://cloud.githubusercontent.com/assets/7156097/21471859/5acdbff2-ca86-11e6-8fbe-77d7c4360719.png)

**Comment by shekhar16** [comment]
Uri are cheked with black listed uri and white listed uri 
Uri will be register only when.
1) Uri should not be included in blacklisted uri list.
2) Uri should include in whitelisted Uri list

**Comment by mzico** [comment]
@shekhar16 : Is this new feature in 3.0.0? Because that uri successfully registered as login uri in 2.4.4.

**Comment by shekhar16** [comment]
yes 
https://github.com/GluuFederation/oxTrust/issues/361

**Comment by shekhar16** [comment]
you can add these whitelist and blacklist URi on Configuration page.

**Comment by shekhar16** [comment]
@mzico @sahiliamsso @nynymike please closed it if verified.
