### ISSUE TITLE
Remove White Pages and Option to be included in White Pages

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#423]
1) Remove the White Pages page:

![image](https://cloud.githubusercontent.com/assets/5271048/21463733/660c049c-c922-11e6-8259-c63768999ea4.png)

2) Remove the check box in personal profile to be included in white pages

![image](https://cloud.githubusercontent.com/assets/5271048/21463735/753453ca-c922-11e6-9d12-519db1372209.png)

3) Remove option to enable white pages

![image](https://cloud.githubusercontent.com/assets/5271048/21463754/e9deb29c-c922-11e6-8131-1253f22e742e.png)

**Comment by shekhar16** [comment]
Fixed.
