### ISSUE TITLE
Hide Secrets in custom scripts / passport config

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#424]
I'm concerned that secrets may be displayed in plaintext as interception script properties.  When calling the API, it's ok. But displaying in the GUI, it's a potential problem. Maybe when you add a new field, there can be a checkbox for "password"? And if this box is checked, then the password is not shown, or just shows "************"

Another option is to allow pre-encoded values. For example: {encode}Aksue2ksCsl== could signal that it is two-way encrypted.

**Comment by yurem** [comment]
We added all required parts to GUI. But it code we not added flag to specify if property contains password or not. We need to do:
1) Add class SimpleExtendedCustomProperty which extends SimpleCustomProperty.
2) Add hideValue boolean flag to SimpleExtendedCustomProperty.
3) Use SimpleExtendedCustomProperty in configurationProperties
4) During rendering list use hideValue  to show or not value by default

**Comment by rajnikantsh** [comment]
code comitted
