### ISSUE TITLE
Cross button ('x') placement in oxtrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#425]
Is it possible to put remove button ( 'x' ) beside every input box instead of where it is now ( it's below of every input box now )? 

i.e.

![screenshot_6](https://cloud.githubusercontent.com/assets/7156097/21508041/333f2a7a-cc43-11e6-991b-e90348c5f432.png)

or, 

![screenshot_7](https://cloud.githubusercontent.com/assets/7156097/21508042/36b350dc-cc43-11e6-95bb-6f7bf3443732.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21582087/7250348a-d070-11e6-9706-5c9c7e7ba915.png)


![image](https://cloud.githubusercontent.com/assets/15937500/21582070/fee0c424-d06f-11e6-9fc8-666f31bd0a63.png)

**Comment by nynymike** [comment]
See also duplicate issue that was closed https://github.com/GluuFederation/oxTrust/issues/442
