### ISSUE TITLE
Unable to 'register' / create custom attribute

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#426]
Tried to add a custom attribute named 'customEmail' from oxTrust of 3.0.0. It failed. 
oxTrust stack trace: http://pastebin.com/kYYtuMcH

**Comment by mzico** [comment]
@yurem @tecoholic

**Comment by yurem** [comment]
Can you  try again with this: http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war 
Also oxTrust allows to register attributes only from specific objectClasses. In oxTRust JSON configuration you should do something similar to this: https://github.com/GluuFederation/community-edition-setup/commit/6318dfc8606634088f42ee271332d96090edd729

I added gluuCustomPerson OC to avoid gluuPerson modifications

**Comment by mzico** [comment]
@yurem : I tried oxtrust war you linked. Not getting that 'Failed to update entry: cn=Subschema' error now; However adding custom attribute is still failing with error: 
![error](https://cloud.githubusercontent.com/assets/7156097/21523302/819c691e-ccd2-11e6-837b-8db500cf211c.png)

I have changed Json configuration there in oxTrust: 

![screenshot_1](https://cloud.githubusercontent.com/assets/7156097/21523308/8c414bb4-ccd2-11e6-8346-4dae4f1307aa.png)

And here is how I am trying to create custom attribute: 

![screenshot_2](https://cloud.githubusercontent.com/assets/7156097/21523313/980f28a8-ccd2-11e6-885e-0df7bfb4a0ef.png)

No indication of error in oxtrust log, just this: 

```
2016-12-28 13:49:59,835 DEBUG [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] Metadata validation finished with result: 'false'
2016-12-28 13:50:14,573 DEBUG [org.gluu.oxtrust.ldap.service.AttributeService] objectClassTypes=[gluuPerson, eduPerson, gluuCustomPerson]
2016-12-28 13:50:30,548 DEBUG [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] Starting update of appliance status
```

**Comment by yurem** [comment]
@mzico can you try on latest deb build?

**Comment by mzico** [comment]
@yurem : Will do.

**Comment by mzico** [comment]
@yurem : A quick status....  Installed 'gluu-server-3.0.0_9-BETA1~trusty+Ub14.04_amd64.deb	2016-12-28 18:35 574M'; however identity is failing to start.  Trying to find out why it's failing... 

```
GLUU.root@proxy:/var/log/apache2# service oxauth status
Jetty NOT running

START_INI      =  /opt/gluu/jetty/oxauth/start.ini
START_D        =  /opt/gluu/jetty/oxauth/start.d
JETTY_HOME     =  /opt/jetty
JETTY_BASE     =  /opt/gluu/jetty/oxauth
JETTY_CONF     =  /opt/jetty/etc/jetty.conf
JETTY_PID      =  /var/run/oxauth.pid
JETTY_START    =  /opt/jetty/start.jar
JETTY_LOGS     =  /opt/gluu/jetty/oxauth/logs
JETTY_STATE    =  /opt/gluu/jetty/oxauth/oxauth.state
CLASSPATH      =
JAVA           =  /opt/jre/bin/java
JAVA_OPTIONS   =  -server -Xms256m -Xmx1152m -XX:+DisableExplicitGC -Dgluu.base=/etc/gluu -Dcatalina.base=/opt/gluu/jetty/oxauth -Djetty.logging.dir=/opt/gluu/jetty/oxauth/logs -Djetty.home=/opt/jetty -Djetty.base=/opt/gluu/jetty/oxauth -Djava.io.tmpdir=/opt/jetty-9.3/temp
JETTY_ARGS     =  jetty.http.host=localhost jetty.http.port=8081 jetty.state=/opt/gluu/jetty/oxauth/oxauth.state jetty-logging.xml jetty-started.xml
RUN_CMD        =  /opt/jre/bin/java -server -Xms256m -Xmx1152m -XX:+DisableExplicitGC -Dgluu.base=/etc/gluu -Dcatalina.base=/opt/gluu/jetty/oxauth -Djetty.logging.dir=/opt/gluu/jetty/oxauth/logs -Djetty.home=/opt/jetty -Djetty.base=/opt/gluu/jetty/oxauth -Djava.io.tmpdir=/opt/jetty-9.3/temp -jar /opt/jetty/start.jar jetty.http.host=localhost jetty.http.port=8081 jetty.state=/opt/gluu/jetty/oxauth/oxauth.state jetty-logging.xml jetty-started.xml

GLUU.root@proxy:/var/log/apache2# service identity status
Jetty NOT running

START_INI      =  /opt/gluu/jetty/identity/start.ini
START_D        =  /opt/gluu/jetty/identity/start.d
JETTY_HOME     =  /opt/jetty
JETTY_BASE     =  /opt/gluu/jetty/identity
JETTY_CONF     =  /opt/jetty/etc/jetty.conf
JETTY_PID      =  /var/run/identity.pid
JETTY_START    =  /opt/jetty/start.jar
JETTY_LOGS     =  /opt/gluu/jetty/identity/logs
JETTY_STATE    =  /opt/gluu/jetty/identity/identity.state
CLASSPATH      =
JAVA           =  /opt/jre/bin/java
JAVA_OPTIONS   =  -server -Xms256m -Xmx768m -XX:+DisableExplicitGC -Dgluu.base=/etc/gluu -Dcatalina.base=/opt/gluu/jetty/identity -Dorg.eclipse.jetty.server.Request.maxFormContentSize=50000000 -Djetty.logging.dir=/opt/gluu/jetty/identity/logs -Djetty.home=/opt/jetty -Djetty.base=/opt/gluu/jetty/identity -Djava.io.tmpdir=/opt/jetty-9.3/temp
JETTY_ARGS     =  jetty.http.host=localhost jetty.http.port=8082 jetty.state=/opt/gluu/jetty/identity/identity.state jetty-logging.xml jetty-started.xml
RUN_CMD        =  /opt/jre/bin/java -server -Xms256m -Xmx768m -XX:+DisableExplicitGC -Dgluu.base=/etc/gluu -Dcatalina.base=/opt/gluu/jetty/identity -Dorg.eclipse.jetty.server.Request.maxFormContentSize=50000000 -Djetty.logging.dir=/opt/gluu/jetty/identity/logs -Djetty.home=/opt/jetty -Djetty.base=/opt/gluu/jetty/identity -Djava.io.tmpdir=/opt/jetty-9.3/temp -jar /opt/jetty/start.jar jetty.http.host=localhost jetty.http.port=8082 jetty.state=/opt/gluu/jetty/identity/identity.state jetty-logging.xml jetty-started.xml

GLUU.root@proxy:/var/log/apache2# service identity start
Starting Jetty: FAILED Fri Dec 30 08:26:29 UTC 2016

GLUU.root@proxy:/var/log/apache2# service oxauth start
Starting Jetty: OK Fri Dec 30 08:26:42 UTC 2016
GLUU.root@proxy:/var/log/apache2# service identity start
Starting Jetty: FAILED Fri Dec 30 08:26:51 UTC 2016
GLUU.root@proxy:/var/log/apache2#
```

**Comment by mzico** [comment]
@yurem : Tried latest deb package; same issue with attribute. Can't create custom one. 

Just for sample; here is the snippet from 2.4.4 custom attribute ( `.....gluuAttributeOrigin: ox-54A920F218F5295D0001C038F3AD....` ): 

```
dn: inum=@!54A9.20F2.18F5.295D!0001!C038.F3AD!0005!E5B5,ou=attributes,o=@!54A9.20F2.18F5.295D!0001!C038.F3AD,o=gluu
objectClass: gluuAttribute
objectClass: top
gluuAttributeViewType: admin
gluuAttributeViewType: user
description: Test attribute
gluuSAML1URI: urn:gluu:dir:attribute-def:testone
gluuStatus: active
oxSCIMCustomAttribute: false
gluuAttributeType: string
gluuSAML2URI: urn:oid:testone
gluuAttributeName: testone
gluuAttributeEditType: admin
oxMultivaluedAttribute: false
displayName: testone
gluuAttributeOrigin: ox-54A920F218F5295D0001C038F3AD
inum: @!54A9.20F2.18F5.295D!0001!C038.F3AD!0005!E5B5
```

**Comment by yurem** [comment]
@mzico we deprecated schema modification from oxTrust in 3.0.0. Now this dialogs allows to register new attribute which admin added to schema manually.
Can you do next:

1. Add new attribute to schema.
2. Update OpenLDAP configuration to apply schema update.
3. Try to use this dialog to register new attribute

**Comment by mzico** [comment]
@yurem : Do we have any doc or procedure how to do that? I can create one doc if procedures are supplied.

**Comment by zamilskhan** [comment]
This issue is still there in 6-BETA2 package. The video shows the behavior. 

[Video Link](https://youtu.be/PYpHdg2icLY)

**Comment by yurem** [comment]
It's expected behavior. We don't modify LDAP schema from oxTrust now. You need to add attribute to LDAP schema first before registering it.

Can you try these steps:
1. Add custom attribute 'gluuCustomPersonAttribute' to /opt/gluu/schema/openldap/custom.schema
2. Add ths new attribute to gluuCustomPerson objectClass

Here is sample file:
```
attributetype ( oxAttribute:1001 NAME 'myCustomAttr1'
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - dynamic registration custom attribute' )

attributetype ( oxAttribute:1002 NAME 'myCustomAttr2'
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - dynamic registration custom attribute' )

attributetype ( oxAttribute:1003 NAME 'gluuCustomPersonAttribute'
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - custom person attribute' )

objectclass ( oxObjectClass:101 NAME 'gluuCustomPerson' SUP top AUXILIARY MAY ( gluuCustomPersonAttribute ) X-ORIGIN 'Gluu - Custom persom objectclass' )

objectclass ( oxObjectClass:102 NAME 'oxAuthClientCustomAttributes' SUP top AUXILIARY MAY ( myCustomAttr1 $ myCustomAttr2) X-ORIGIN 'Gluu - Custom client objectclass' )

```

3. service solserver stop
4.  mv /opt/symas/etc/openldap/slapd.d /opt/symas/etc/openldap/slapd.d.bk01
5. mkdir -p /opt/symas/etc/openldap/slapd.d
6. /opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf -F /opt/symas/etc/openldap/slapd.d
7. service solserver start

**Comment by yurem** [comment]
After that you can try to register gluuCustomPerson attribute in oxTrust

**Comment by yurem** [comment]
@zamilskhan @mzico can you add this to 3.0.0 documentation about schema update?

**Comment by mzico** [comment]
@yurem : will do. Thanks.

**Comment by yurem** [comment]
It looks like we are not using /opt/symas/etc/openldap/slapd.d folder now.

Hence after updating schema files we only need to do:
service solserver restart

@tecoholic

**Comment by tecoholic** [comment]
After the discussion here https://github.com/GluuFederation/community-edition-setup/issues/235 it was decided to leave the slapd.d folder generation to the user. There is no slapd.d conf folder by default. So update the custom.schema file and do a `service solserver restart`. The user cannot created custom attributes from the oxTrust UI directly (I guess) @yurem Correct me if I am wrong.

**Comment by nynymike** [comment]
Correct, no more dynamic creation of schema.

And we should remove the cn=config database... so `slapd.conf` is the only way to manage config by default.
