### ISSUE TITLE
Unable to "Add users" via oxtrust ui

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#427]
Two issues in adding users via Oxtrust UI
1. Getting Error that password and confirm password doesn't match even though both are same.

![image](https://cloud.githubusercontent.com/assets/21104811/21536838/159678c2-cdae-11e6-8a80-9287406abae0.png)

2. When click on add users, we get error

![image](https://cloud.githubusercontent.com/assets/21104811/21536844/300e8140-cdae-11e6-9f39-57252e4768a1.png)

Dec 29, 2016 4:19:54 AM com.sun.faces.lifecycle.ProcessValidationsPhase execute
WARNING: javax.faces.FacesException: javax.el.ELException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3085007220656514429.dir/webapp/WEB-INF/incl/person/personForm.xhtml @127,176 validator="#{_custAttr.metadata.validateAttribute}": java.lang.NullPointerException
javax.faces.FacesException: javax.faces.FacesException: javax.el.ELException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3085007220656514429.dir/webapp/WEB-INF/incl/person/personForm.xhtml @127,176 validator="#{_custAttr.metadata.validateAttribute}": java.lang.NullPointerException

Full stack trace: 
http://pastebin.com/iMTdif4n

**Comment by 127** [comment]
Every mention of @127 makes me very very very sad.

**Comment by willow9886** [comment]
Sorry about that @127. An unfortunate side effect of the global @ convention here on GH...

**Comment by yurem** [comment]
@sahiliamsso Can you retest it on latest oxTrust war build http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war or latest deb build.

**Comment by sahiliamsso** [comment]
retested on latest oxtrust war build and still the same error
```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: bf355
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
```

**Comment by zamilskhan** [comment]
Confirmed on CentOS 6 with 8BETA build.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/a923f51d01e825580398711e08df9eb9bc85072d

**Comment by shekhar16** [comment]
Fixed.

**Comment by zamilskhan** [comment]
User is created, but the `oxtrust.log` shows the following
```
2017-01-11 09:31:40,049 ERROR [qtp425918570-18] [org.gluu.oxtrust.ldap.service.PersonService] (PersonService.java:374) - Error generating inum: 
java.lang.NumberFormatException: For input string: "A448D7078D9DF203"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_112]
        at java.lang.Long.parseLong(Long.java:592) ~[?:1.8.0_112]
        at org.gluu.oxtrust.ldap.service.PersonService.generateInum(PersonService.java:369) [classes/:?]

2017-01-11 09:31:58,670 ERROR [qtp425918570-18] [org.gluu.oxtrust.ldap.service.AttributeService] (AttributeService.java:647) - Failed to find attribute 'cn' metadata
2017-01-11 09:31:58,671 ERROR [qtp425918570-18] [org.gluu.oxtrust.ldap.service.AttributeService] (AttributeService.java:647) - Failed to find attribute 'oxTrustEmail' me
tadata
```
Will this become a problem?
