### ISSUE TITLE
Unable to create Trusted Relationship with uploading metadata file

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxTrust#428]
[ Unable to create Trusted Relationship with uploading metadata file](https://github.com/GluuFederation/oxTrust/issues/416#issuecomment-268408764)

**Comment by sahiliamsso** [comment]
Do we have any updates?

**Comment by uboznikov** [comment]
@shekhar16 What is the purpose of the `if(!update){` statement in the `case FILE:`?

[oxTrust issue #384](https://github.com/GluuFederation/oxTrust/commit/6c16f2072c1641fb41d5533224105ed371acc14d)

https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/UpdateTrustRelationshipAction.java#L285-L287

Above is the cause of this issue. Please review. I am disabling the `if` for now.

**Comment by uboznikov** [comment]
![tr-upload-file-metadata-ok](https://cloud.githubusercontent.com/assets/16329085/21747975/39f7acf6-d5b3-11e6-8277-98748d9c10c2.png)

**Comment by shekhar16** [comment]
@uboznikov  the purpose of   `if(!update)`  is to make status active for only new registering user  not for every updating details,if you comment this line it will re-enable the status=Active so. please revert this  commit.

**Comment by shekhar16** [comment]
@uboznikov  And how this line will make impact on uploading metadata file ,it is just setting a property status = active or inactive. .

**Comment by uboznikov** [comment]
@shekhar16 This issue was hard to trace, I compared it with the version before your commit. Please do so, or check my test screenshot above.

**Comment by shekhar16** [comment]
@uboznikov  if you are registering a new trust relationship than why this update value is true.For new TR update should be false.

**Comment by shekhar16** [comment]
Fixed.

**Comment by uboznikov** [comment]
@shekhar16 That fix breaks the current code. Please compare to Shib v2 version. I have none or very minimal commits to the UI.

**Comment by uboznikov** [comment]
@shekhar16 Have you tested it and compared before and after?

**Comment by shekhar16** [comment]
@uboznikov please check the code which i corrected, the update flag should only been set when it is going to update existing TR ,to check whether it already exist or not ,we are checking initially inum is set or not .
if  inum is not set it means new TR has to be register.

**Comment by sahiliamsso** [comment]
Able to create TR with attaching metadata file. Thanks
