### ISSUE TITLE
Sp Metadata File link is not working in oxtrust UI

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#429]
Search for "gluu SP on appliance" Trust relationship, and click on Sp Metadata File link. 

![image](https://cloud.githubusercontent.com/assets/21104811/21576347/347b1d7a-cf51-11e6-8e93-b3dbe3aab57c.png)

Nothing happens on clicking this link. It's true for all SAML TR's.

**Comment by uboznikov** [comment]
@shekhar16 I am reverting your fix to #351 as it is causing this issue. Please review.

[oxTrust issue #351](https://github.com/GluuFederation/oxTrust/commit/571c05fdf433688d2fe667ee501c25eda3a77a05)

![loadmetadata-returns-null](https://cloud.githubusercontent.com/assets/16329085/21771300/c4a3733a-d6c1-11e6-9397-6208a2b8c1d3.png)

**Comment by uboznikov** [comment]
![429-fixed](https://cloud.githubusercontent.com/assets/16329085/21771549/bf0fe54c-d6c2-11e6-95c3-87ae15c5167e.png)

**Comment by shekhar16** [comment]
@sahiliamsso  please test this issue.

**Comment by sahiliamsso** [comment]
working fine. Thanks for the fix.
