### ISSUE TITLE
Long value of Username cause interface to 'break'

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#430]
Similar to issue https://github.com/GluuFederation/oxTrust/issues/282, when adding long value to "Username" field in Users >> Update User causing interface to break. I verified in both FF and Google Chrome.

![image](https://cloud.githubusercontent.com/assets/21104811/21597362/cf09919e-d16f-11e6-8ff1-aab25175e580.png)

We must limit the input character to this field. I tested with more than 800 characters.

**Comment by nynymike** [comment]
Limit username to 128 characters by default.

**Comment by shekhar16** [comment]
Fixed.
We didn't add maxlength hardcoded ,user can add maxlength attribute  from attribute UI page
