### ISSUE TITLE
SAML Trust Relationship: Entity Type - Federation shows different options in dropdown

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#431]
Select Entity Type as “Federation/Aggregate” , You’ll see Metadata Location as 5 options to choose from-
1.	None
2.	File
3.	URI
4.	Generate
5.	Federation
![image](https://cloud.githubusercontent.com/assets/21104811/21598387/31fecd5c-d182-11e6-8453-f49599008817.png)

 
Now click on Add button, without entering any values. You’ll see now dropdown has 3 values
1.	None
2.	File
3.	URI

![image](https://cloud.githubusercontent.com/assets/21104811/21598390/3eaa466c-d182-11e6-9f71-5af2c3bc3456.png)

**Comment by shekhar16** [comment]
@sahiliamsso  it was implemented as per issue https://github.com/GluuFederation/oxTrust/issues/310

**Comment by sahiliamsso** [comment]
Issue is that initially it displays 5 options under federarion and after clicking update button it shows 3 options in dropdown

**Comment by nynymike** [comment]
This is correct... If entity type is federation, it must be either URL or File...

**Comment by shekhar16** [comment]
@sahiliamsso please test it with latest build.

**Comment by sahiliamsso** [comment]
fixed in the latest build. Thanks Shekhar
