### ISSUE TITLE
Add email validation on Users > Update User screen

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#432]
Please add email format validation check on Add user screen. It allows to submit user with invalid email format but gets exception on the screen.

![image](https://cloud.githubusercontent.com/assets/21104811/21705635/24be2fe0-d3e7-11e6-9806-3c5704d4590d.png)

**Comment by sahiliamsso** [comment]
Also, It allows me to set 1 (say a) character as password  Please confirm if password/confirm password value has to be between 3 and 60 character? If yes then we will need to add this validation on create user screen

**Comment by shekhar16** [comment]
@sahiliamsso we had implemented custom validation for attributes,so if you need minimum ,maximum, and regex for password ,you can add these validation values on attribute page.

**Comment by shekhar16** [comment]
For email address , system error is fixed.
