### ISSUE TITLE
Passport Form Issue

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#433]
add new fields and data is also saved without having the value of Strategy\
The value of strategy can not be empty
It should be a mendatory field
click Add Strategy New form is generated and asks for Strategy and put somr value in it, and then click to add new field, the value of the field gets empty

**Comment by shekhar16** [comment]
Fixed.

**Comment by arvindsinghtomar** [comment]
Thanks Shekhar
