### ISSUE TITLE
Add reference to script from dynamic scope

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#435]
If in authorization request there is dynamic scope we call all enabled dynamic scripts.
To understand if we really need to add dynamic claims we uses next patter in each script:
```
        for dynamicScope in dynamicScopes:
         # Add role  if there is scope = permission
         if (StringHelper.equalsIgnoreCase(dynamicScope, "permission")):
```

It's not very convenient. I offer to add reference from scope to dynamic scope script(s).

In this case we know which script(s) to call for each dynamic scope.
And the dialog will be similar to UMA scope description 
![default](https://cloud.githubusercontent.com/assets/6104200/21824036/49162f44-d786-11e6-8eb7-45ed90ae1d4e.png)

**Comment by yuriyz** [comment]
@otataryn as per commits above on oxTrust we should be able specify scripts for given scope. Means oxScript for oxAuthCustomScope. I like @yurem idea to use similar UI we have for UMA Scope where we do the same, we are adding scripts to scope. Lets use same approach. oxScript attribute should contains DN of the custom script.
