### ISSUE TITLE
Move Passport off "Default Authentication Tab"

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#438]
It doesn't really make sense for the "Enable Passport" to be on the default authentication tab.

I think you should always display the passport tab, and move the "enable|disable" to there...

Also, the selected values should be either **Enabled** or **Disabled**, please remove **Default**. Default is disabled.

![image](https://cloud.githubusercontent.com/assets/3717101/21828531/82ff6b92-d756-11e6-9b7c-545fbeef9741.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21903142/c417bc04-d924-11e6-9b9f-4c5adb856988.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/21918182/aeb8d960-d974-11e6-9bea-b43b5e2cb52e.png)

**Comment by shekhar16** [comment]
Fixed.
