### ISSUE TITLE
Create new sample folder for interception scripts

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#44]
I think it would be better to create a folder substructure for sample scripts. For example: 
```
oxtrust/sample/interception/
oxtrust/sample/interception/pre-registration
oxtrust/sample/interception/post-registration
etc.
```

**Comment by mzico** [comment]
@nynymike / @yurem : Whom should we assign this ticket?

**Comment by yurem** [comment]
All sample script re in: https://github.com/GluuFederation/oxExternal

I think we should move them to oxTrust/oxAuth to maintain them and simplify way of finding them.

**Comment by yurem** [comment]
@nynymike and @willow9886 What do you think?
For example all auth scripts are in: https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations

**Comment by willow9886** [comment]
Yes, simplified navigation structure seems like a good idea.

**Comment by nynymike** [comment]
agreed

**Comment by willow9886** [comment]
closing issue..
