### ISSUE TITLE
Passport Form broken

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#441]
If I enter the strategy value in upper case and then try to modify to lower case, the values doesn't get updated after I restart passport. And after that the values changes to upper case automatically, even if I change it to lowercase, ie, if I enter ClientID instead of clientID and modify it to lowercase, the change doesn't happen. until I create a different strategy and rename the old strategy.

It would be an great option to have remove button to remove a strategy once its created.

**Comment by shekhar16** [comment]
I tested this issue in latest release gluu-server-3.0.0_3-BETA4-trusty+Ub14.04_amd64.deb and it is updating the fieldset in that .
it is not there please test it with latest release 3.0 and let me know.
