### ISSUE TITLE
Improve display of redirect_uri's

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#442]
If you're in oxtrust, managing a client who has multiple (6,7,8+) redirectloginURIs, logoutURIs the lists are not very user friendly. As the list grows it becomes increasingly difficult to see what URI corresponds to the X that you are clicking on. This could be resolved by throwing some CSS on these list types that give every other row an alternating grey-ish(or whatever color) background so that the rows are easier to identity. Here is an example so you can see the type of layout I'm referring to:https://www.w3.org/Style/Examples/007/evenodd.en.html

**Comment by nynymike** [comment]
Duplicate of https://github.com/GluuFederation/oxTrust/issues/425

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23102736/d4b30c6c-f6d4-11e6-8ffe-14b75c46ca59.png)

**Comment by shekhar16** [comment]
Fixed.
Please test it with latest Build.
