### ISSUE TITLE
Changes in "Configure RelyingParty" are not saved

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#446]
Steps to reproduce
1. Click on Add Trust relationship
2. Attach sample metedata file
3. Click on "Configure RelyingParty" and add SAML2SSO and leave other options as default
4. Release attributes
5. Click on Save
6. Search for the TR created in above steps
7. Click on "Configure RelyingParty"

Expected : You should see "SAML2SSO" selected with default values
Actual: Nothing is selected. 

Version gluu-server-3.0.0 (2-BETA3~trusty+Ub14.04)

**Comment by shekhar16** [comment]
Are you getting any exception.

**Comment by nynymike** [comment]
Can you test if the TR entry in LDAP is updated? This is a critical bug report.

**Comment by sahiliamsso** [comment]
gluuProfileConfiguration are getting saved in LDAP

<rp:ProfileConfiguration xsi:type="saml:SAML2SSOProfile" 
 includeAttributeStatement="true"
 assertionLifetime="150"
 assertionProxyCount="0"
 signResponses="conditional"
 signAssertions="never"
 signRequests="conditional"
 encryptAssertions="conditional"
 encryptNameIds="never"
/>

**Error in logs**
2017-01-18 04:55:36,851 ERROR [pool-2-thread-3] [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:322) - Failed to parse stored metadataFilter configuration for trustRelationship inum=@!495F.F2BE.310E.8C33!0002!C48C.C103!0006!D29C.653A,ou=trustRelationships,inum=@!495F.F2BE.310E.8C33!0002!C48C.C103,ou=appliances,o=gluu
org.xml.sax.SAXParseException: The prefix "rp" for element "rp:ProfileConfiguration" is not bound.

**Comment by shekhar16** [comment]
@uboznikov please check this exception  it is related to the xml file you added for shiboleth3.

**Comment by uboznikov** [comment]
[Fix to #363 causes org.xml.sax.SAXParseException](https://github.com/GluuFederation/oxTrust/issues/412)

@yurem We may need to review the fix...

**Comment by uboznikov** [comment]
@shekhar16 Can you please check in UI, RP data is saved ok but cannot be displayed, even after restart. On retrieval there were no exceptions.

**Comment by uboznikov** [comment]
Thanks @yurem after latest [fix](https://github.com/GluuFederation/oxTrust/commit/84a60ce2e242a8dcacb9179a2bece39549ecaa9f) configure RP is now ok.

![configure-rp-ok](https://cloud.githubusercontent.com/assets/16329085/22152943/15929464-df60-11e6-8c45-f317aded6a44.png)

@sahiliamsso Please re-test in new build. Thanks.

**Comment by yurem** [comment]
Can you retest it on new beta build?

**Comment by sahiliamsso** [comment]
Fixed, verified on gluu-server-3.0.0 (2-BETA4~trusty+Ub14.04)
