### ISSUE TITLE
Password should not be visible in the form

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#450]
Obviously the password should not be visible in the add password form. 

![image](https://cloud.githubusercontent.com/assets/3717101/22189227/f315ab56-e0e0-11e6-9099-65d6b5401483.png)

**Comment by mzico** [comment]
Password is not readable now in: 

```
GLUU.root@check:~# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1283518304725568223.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 9b912
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9

GLUU.root@check:~#
```


![password_invisible](https://cloud.githubusercontent.com/assets/7156097/22399383/d4e70ef2-e560-11e6-83c6-276b4f8201bb.png)
