### ISSUE TITLE
Atribute form missing SAML URI values

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#452]
Why can't the user enter SAML URI's for these attributes? 

![image](https://cloud.githubusercontent.com/assets/3717101/22189515/9267fc80-e0e2-11e6-9769-7037370f9d14.png)

**Comment by dmogn** [comment]
There is some logic for show/hide URI fields:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/UpdateAttributeAction.java#L373
Attribute Origin should be equal to application configuration personCustomObjectClass.

I can simply remove this rule or change "hide" state to "disabled" state for URI fields (more user friendly, I think).

**Comment by dmogn** [comment]
Mike Schwartz: remove it...
Mike Schwartz: It's up to the admin to configure attributes correctly.

**Comment by dmogn** [comment]
Fixed.
