### ISSUE TITLE
SP Metadata File link is broken

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#455]
Clickin on the metadata used to show a modal window with the metadata... no clicking on it does nothing.

![image](https://cloud.githubusercontent.com/assets/3717101/22189996/d3f82f78-e0e5-11e6-9ff1-80f836acbec9.png)

No errors in the log.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/429

**Comment by uboznikov** [comment]
It is fine in build 2-BETA4:

![metadata-display-ok](https://cloud.githubusercontent.com/assets/16329085/22252038/d612d224-e287-11e6-9b3f-9d92d6452606.png)
