### ISSUE TITLE
Trust Relationship Creation throws NPE

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#458]
OS: Ubuntu Server 14.04
Pakcage: 2-BETA4~trusty+Ub14.04

The following NPE is thrown in a fresh installation of Gluu Server while creating a Trust Relationship. The TR is created without any issue. The email configuration is not functional in the test environment. 

```
1-24 19:47:06,462 ERROR [qtp425918570-11] [org.gluu.oxtrust.ldap.service.TrustService] (TrustService.java:385) - Failed to send the notification email: java.lang.NullPointerException: null
```

**Comment by uboznikov** [comment]
This can be safely ignored, the intention in the `try-catch` block is explicit:

[TrustService.java](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java#L371-L386)
