### ISSUE TITLE
"Activate Invitation Links Management"  in oxTrust

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#46]
Currently, the only reference to invitation links in oxTrust is in Configuration > Manage Registration, where we have a checkbox for Activate Invitation Links Management. 

All other functionality within oxTrust relating to invitation links management has been removed, including "Configure Linktrack API"  and "Registration Requests" (which was formerly a part of the Profile section of oxTrust).

It seems that we should either add these options back to oxTrust, or we should remove Activate Invitation Links Management from Manage Registration to remove all reference to Invitation Links.

**Comment by willow9886** [comment]
It seems like we're leaning towards removing "Activate Invitation Links Management" from the oxTrust interface. We need to figure out a plan for any existing customers who are using this feature, and the features listed above that have already been removed from oxTrust.

**Comment by willow9886** [comment]
Mike's suggestion is to maintain the feature in the main branch, but hide it unless you manually update a properties file or ldap entry. Oleksiy agreed this is a good quick fix. I think we should proceed with this.

**Comment by yurem** [comment]
Should we add property in oxTrust.properties to enable disable it?

**Comment by willow9886** [comment]
Yes, let's proceed. "Activate Invitation Link " should be hidden by default.

**Comment by willow9886** [comment]
covered in new UI.
