### ISSUE TITLE
passport json  format exception

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#461]
getting json format exception for passport initail loaded data in latest release i.e 
gluu-server-3.0.0_3-BETA4-trusty+Ub14.04_amd64.deb

`2017-01-26 13:45:48,590 ERROR [qtp502572999-58] [org.gluu.oxtrust.ldap.service.PassportService] (PassportService.java:62) - Failed to load passport configuration from LDAP
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '{  "provider":"facebook",  "clientID":"facebook_client_id",  "clientSecret":"facebook_client_secret" }' to object
	at org.gluu.site.ldap.persistence.AbstractEntryManager.convertStringToJson(AbstractEntryManager.java:1100) ~[classes/:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.setPropertyValue(AbstractEntryManager.java:1048) ~[classes/:?]`

**Comment by shekhar16** [comment]
@yurem i checked the passport functionality with initial settings i found the code is getting exception due to initial loaded passport configurations.
As we are getting inputs for both field name and field value .

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/415

**Comment by nynymike** [comment]
Is this resolved? I can't tell... please close issue if they are fixed.

**Comment by shekhar16** [comment]
Fixed.
