### ISSUE TITLE
oxTrust300. password field inconsistent UI 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#463]
* Tried in: Firefox. 
* oxTrust version: 

```
tomcat@check2442:/opt/tomcat/webapps$ cat /opt/tomcat/webapps/identity/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 3b892
Archiver-Version: Plexus Archiver

tomcat@check2442:/opt/tomcat/webapps$

```

* Attaching a video file: 
[Video_file.zip](https://github.com/GluuFederation/oxTrust/files/736394/Video_file.zip)

* How to reproduce: 
   - Try to add a new user. 
   - During providing password; double click or a single long click in password inbox will generate lot of unnecessary dots. Feel free to check the video.

**Comment by yurem** [comment]
@shekhar, I think the problem in this line:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml#L57

In Zico's scenario this method get value:
"Click to enter Confirm Pasword"
and replace all characters with *.

We need to use "#{rich:element('custpasswordHiddenId')}.value}" method to get real value.
There is same problem with repeat password filed.

**Comment by yurem** [comment]
@mzico It looks like I fixed it. Can yiu verify it on this build? https://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war

**Comment by mzico** [comment]
@yurem : Checking...

**Comment by mzico** [comment]
@yurem : Yes, it's much better now. 
Just two suggestions: ( If you think we should create a separate issue for below enhancements, I can create new github issue ): 

- Error message should be more specific. ( i.e. if I use existing email_address for new person's registration, error message shows `Failed to add person` in browser. But in log.. the reason is: `some attributes not unique`. 
May be we can show this  `some attribute not unique` in oxTrust Error message? 

- `Password should be same`; I believe just one error message is sufficient enough than six ( 6 ) error messages. Screenshot attached. 

![password](https://cloud.githubusercontent.com/assets/7156097/22398252/3dafc49a-e54a-11e6-9048-2fed12c3e8ef.png)
