### ISSUE TITLE
Remove SAML 1 and ShibbolethSSO

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#465]
Please disable SAML 1 Artifact Resolution, SAML 1 Attribute Query, ShibbolethSSO.

We need to update the form:
![image](https://cloud.githubusercontent.com/assets/3717101/22441488/30e4be1e-e6fd-11e6-94db-33e9581a8e1b.png)

**Comment by uboznikov** [comment]
![saml1-removed](https://cloud.githubusercontent.com/assets/16329085/22509001/3d5b3e86-e8c7-11e6-89a3-5aed55d4504c.png)

**Comment by zamilskhan** [comment]
removed. closing issue
