### ISSUE TITLE
Remove "Manage Email Addresses" section from Configuration > Org. Configuration

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#47]
This section for admin to enter email address for Jira, Centreon, Billing, etc. are no longer needed. 

![screenshot 2015-04-07 at 10 26 01 am](https://cloud.githubusercontent.com/assets/5271048/7026629/883bc2a0-dd10-11e4-8e03-88862df3ff4a.png)

**Comment by nynymike** [comment]
Make sure we remove these fields from the [LDAP schema](https://github.com/GluuFederation/community-edition-setup/blob/master/static/opendj/101-ox.ldif#L165) and also from the model (i.e. don't just remove the panel from the UI).

**Comment by dmogn** [comment]
There is one usage of privacyEmail field:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/service/TrustService.java#L376 
mail.sendMail(appliance.getSmtpFromName() + " <" + appliance.getSmtpFromEmailAddress() + ">", appliance.getPrivacyEmail(), subj, preMsg + mailMsg);

What to do with it?

**Comment by dmogn** [comment]
Done.

**Comment by yurem** [comment]
Maybe we should keep at least one e-mail filed : "Admin E-mail". Application should able to send notification to someone...

**Comment by nynymike** [comment]
yes, we have the SMTP code, which is useful in interception scripts. Perhaps having a default admin email address could be useful if you want to send a notification.

**Comment by dmogn** [comment]
We can use email from installation or revert one email field.

**Comment by yurem** [comment]
Correct, we can populate email filed using our ldif templates: https://github.com/GluuFederation/community-edition-setup/tree/master/templates

**Comment by yurem** [comment]
Fixed
