### ISSUE TITLE
2.4.4.2: It's impossible to remove entries from "Logout URI" property of OIDC client.

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#470]
This is not fixed in 2.4.4.2. 

https://trello.com/c/uD7HWXsl/697-qa-https-github-com-gluufederation-oxtrust-issues-366

**Comment by shekhar16** [comment]
@yurem commited the fix in sp 3 branch .Can create its war far tester's to test.

**Comment by aliaksander-samuseu** [comment]
Fixed both in 3.0 and 2.4.3sp3
