### ISSUE TITLE
OpenID dynamic scope. Don't display list of claims

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#472]
We should not allow to specify list of claims for dynamic scopes.

**Comment by yurem** [comment]
Fixed in https://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war

**Comment by zamilskhan** [comment]
The behaviour is given in [this video](https://youtu.be/puFaVOez638)
