### ISSUE TITLE
UMA -> Resources : "Modify" dialog does not open

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#479]
1. Go to UMA -> Resources
2. Click on any existing resource (as shown on screenshot)

Result (bug): "Add" dialog is opened
Expected result: "Modify" dialog is opened

![umaresourcemodify](https://cloud.githubusercontent.com/assets/2013070/22629793/9d715bd0-ebf5-11e6-98fd-280dd0aa7bde.png)

**Comment by yurem** [comment]
@yuriyz I think it's data issue. In clean 3.0.0 I can't reproduce it. But I find 2 bugs during the testing:

- fix resources search
- fix scope selection in respurce form
