### ISSUE TITLE
UMA->Resources : Remove "Resources" as well as "Add Resources" button (see screenshot) from Update/Add resources page

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#480]
![removeresources](https://cloud.githubusercontent.com/assets/2013070/22661359/c327dd14-ecad-11e6-8824-763d5d4bf4dc.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/22702157/c4f69b52-ed85-11e6-9804-71e26b9c85e1.png)

**Comment by shekhar16** [comment]
Fixed.
