### ISSUE TITLE
Failed to load velocity template 'sp- metadata.xml'

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#482]
prod 3.0.0 in ubuntu 14.04

 Zamil Khan: it throws 2017-02-06 22:55:13,099 ERROR [main] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:57) - Failed to load velocity template 'sp-
metadata.xml'
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'sp-metadata.xml.vm'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474) ~[velocity-1.7.jar:1.7]
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352) ~[velocity-1.7.jar:1.7]
[20:01:14] Zamil Khan: please confirm if you see this
[20:01:24] Zamil Khan: HPPT ERROR 503 service unavailable

**Comment by dmogn** [comment]
I cannot reproduce this error. The file /opt/gluu-server-3.0.0/opt/gluu/jetty/identity/conf/shibboleth3/idp/sp-metadata.xml.vm exists on my installation. No errors with it.

**Comment by yurem** [comment]
```
ls -l1 /opt/gluu/jetty/identity/conf/shibboleth3/idp/
total 56
drwxr-xr-x 2 root root  4096 Feb 10 15:30 MetadataFilter
drwxr-xr-x 2 root root  4096 Feb 10 15:30 ProfileConfiguration
-rw-r--r-- 1 root root  2985 Feb  6 14:18 attribute-filter.xml.vm
-rw-r--r-- 1 root root  3406 Feb  6 14:18 attribute-resolver.xml.vm
-rw-r--r-- 1 root root  2618 Feb  6 14:18 cas-protocol.xml.vm
-rw-r--r-- 1 root root  3196 Feb  6 14:18 idp-metadata.xml.vm
-rw-r--r-- 1 root root  4322 Feb  6 14:18 metadata-providers.xml.vm
-rw-r--r-- 1 root root 16106 Feb  6 14:18 relying-party.xml.vm
drwxr-xr-x 2 root root  4096 Feb 10 15:30 schema
-rw-r--r-- 1 root root  1720 Feb  6 14:18 sp-metadata.xml.vm
```
