### ISSUE TITLE
UMA resource set GUI corrupts the "scopes" field

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#484]
Issue is described in issue [3744](https://support.gluu.org/3744) on the support site.

**Comment by shekhar16** [comment]
newly registered resourceset's Scope entry  with 

![image](https://cloud.githubusercontent.com/assets/15937500/25315019/d2963cd8-286b-11e7-8651-ed6112770154.png)

**Comment by shekhar16** [comment]
After updating record of the Scope from oxtrust UI.

![image](https://cloud.githubusercontent.com/assets/15937500/25315046/3fcee354-286c-11e7-848d-ec33b86a20f3.png)

**Comment by shekhar16** [comment]
I checked the get resourceset WS aswell, in this WS the reposne returning the scopeURL not Scope display name.There is nothing wrong in oxtrust side

So now there are 2 issues in oxauth side 
1) In resourceset registration, save the oxUri correctly , if scope is new.
2) In resourceset fetch with WS ,we should return the the whole scope's details or scope inum or scope display name or scope's uri.

**Comment by shekhar16** [comment]
@nynymike please advice what we should do in this case.

**Comment by yurem** [comment]
@yuriyz Can you help @shekhar16 with this issue. I suspect server API and form in oxTrust probably not in sync

**Comment by yuriyz** [comment]
@shekhar16 it's not about `oxAuthUmaScopeDescription` but about `oxAuthUmaResourceSet` update. 
Please check ticket again `https://support.gluu.org/3744/`. 

Would you please give code point in oxTrust where you set scope DNs `oxAuthUmaScope` property for `oxAuthUmaResourceSet` OC ? I believe bug is there.

Here is how that property set on oxauth side:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/uma/ws/rs/ResourceSetRegistrationWS.java#L349-349

**Comment by shekhar16** [comment]
@yuriyz 
for 1st issue I raised here is its code referecnce 
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/uma/ScopeService.java#L170
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/uma/ScopeService.java#L171

2 issue i raised 
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/uma/ScopeService.java#L259

in oxauth , on saving the the NEW Scope in resource set we are saving display name and uri same.
And in get method we are returning the URl ,not display name.

Please Let me know if I m wrong.

**Comment by yuriyz** [comment]
Would you please give code point in oxTrust where you set scope DNs `oxAuthUmaScope` property for `oxAuthUmaResourceSet` OC ? Means code point where you update Resource Set.

**Comment by shekhar16** [comment]
Here is the line code line where we are upting the scope in oxtrust.
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/uma/UpdateScopeDescriptionAction.java#L165

**Comment by shekhar16** [comment]
Please let me know should I correct anything in code.

**Comment by yuriyz** [comment]
@shekhar16 I don't understand, I'm asking about ResourceSet update. That code does not update Resource Set but scope entity. It is two different entities.

**Comment by yuriyz** [comment]
This one seems to be the action for Resource Set update 
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/uma/UpdateResourceSetAction.java

**Comment by shekhar16** [comment]
@yuriyz Please check ticket again https://support.gluu.org/3744/.
He is updating new scope which we added in resource set.
here is the ready reference of shared pics in support issue reported

![image](https://cloud.githubusercontent.com/assets/15937500/25403814/41eb377c-2a1b-11e7-8b88-f73ff3688cff.png)

![image](https://cloud.githubusercontent.com/assets/15937500/25403832/520fa46c-2a1b-11e7-9f94-a17132645026.png)

**Comment by yuriyz** [comment]
oxauth supports only URI based scopes. By scope uri it should be possible to fetch scope description.
oxauth does NOT support plain based scopes. Mainly because oxauth tracks scope and therefore if two resource servers use same "view" plain based scope it would be impossible to track it back. Also it may produce many duplications and avoid to confusion (e.g. which "view" scope is registered by which RS and to which one apply UMA Policy). oxauth has to validate whether scope is URI based and if not throw exception which is not the case right now.

Issue for oxauth is opened https://github.com/GluuFederation/oxAuth/issues/512
