### ISSUE TITLE
Make cache provider configurable via UI (oxCacheConfiguration attribute of gluuAppliance OS)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#485]
See these two commits:
https://github.com/GluuFederation/oxTrust/commit/8d32151a31e9fe81fede07d49a51f4f4be46d074
https://github.com/GluuFederation/community-edition-setup/commit/7ef3027810f1e6bcf07367a3313243ecf8c0b1f1

there is new attribute oxCacheConfiguration in gluuAppliance OC is to provide generic way to switch cache provider.

Example: 
oxCacheConfiguration: {"cacheProviderType": IN_MEMORY, "memcachedConfiguration": {"servers":"localhost:11211", "maxOperationQueueLength":100000, "bufferSize":32768, "defaultPutExpiration":60, "connectionFactoryType": DEFAULT}, "inMemoryConfiguration": {"defaultPutExpiration":60}}

We need to make it configurable via oxTrust

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23224761/9b5c9946-f955-11e6-8dfe-726eb22b370c.png)

**Comment by yuriyz** [comment]
@shekhar16 
- please put "cacheProviderType" as very first parameter
- Tab title must be "Cache Configuration" (not "Memcached configuration")
- connection provider type is missed for memcachedConfiguration.

Otherwise looks as good start.

**Comment by shekhar16** [comment]
@yuriyz  I will make the changes as per your suggestion.Thanx :+1:

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23317357/0f64d4bc-faf4-11e6-99a5-8b923a84aba8.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by yuriyz** [comment]
please add redis configuration support

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/9289d84b83e36282ab11a14b9f8daf7b0bbc5f2b

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23563678/b494fc5e-006d-11e7-86aa-84f551bb0b3c.png)

**Comment by shekhar16** [comment]
added redis configuration.
