### ISSUE TITLE
UMA scope name error is ambiguous : need clear error message

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#486]
https://support.gluu.org/customization/3763/uma-scope-form-id-field-ambiguous/

(This is probably related to my other two UMA scope issues.)

Going to the GUI to create a new scope (scope_form.png), the "Id" field says "Click to enter Scope Name". Some names are flagged as "invalid" with no explanation as to what constitutes a valid scope name. See scope_name.png.

test-name works as a display name, but not as a scope name. Trial and error shows it is the hyphen "-" that it doesn't like. Neither does it like "!" or "@" which seem to be standard characters in other Gluu IDs. It doesn't seem to mind "_" characters, though.

This should probably be documented somewhere, and also in the error message.

**Comment by shekhar16** [comment]
@yuriyz  there is a validation it only allows alpha numeric in id fields.
Do you want me to remove that validation?

**Comment by yuriyz** [comment]
well, it depends. If it works correctly with special characters then yes, please remove it. If not then just correct error message. Something like "Scope name is invalid. Only letters and numbers with underscore are allowed".

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/c0cce0193521e4821555c05a72308a3f269f7066

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23102607/1a6d5422-f6d2-11e6-890e-2bed86f5310a.png)

**Comment by shekhar16** [comment]
Fixed.
