### ISSUE TITLE
UMA Scope : internal scope does not have reference url

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#487]
1. Create UMA Scope via GUI with name "edit"

Result : reference column is empty
Expected result : reference column must not be empty.

As described here reference url for internal scope must be "scope_endpoint" + "scope id":
https://support.gluu.org/customization/3761/uma-scopes-names-in-general-seem-to-be-broken/#at19404

Example: https://ce-dev.gluu.org/oxauth/seam/resource/restv1/uma/scopes/edit

**Comment by yuriyz** [comment]
For clarity maybe also change column name to "Reference url (used for resource set registration)" to keep clear for clients that reference url must be used instead of id or name.

**Comment by yurem** [comment]
Fixed:
![default](https://cloud.githubusercontent.com/assets/6104200/23031586/353a3f2c-f47a-11e6-9d16-89b69a753c83.png)

**Comment by ianalexr** [comment]
@yurem The fix uses the name of the scope instead of the id. So invalid reference urls are displayed if the scope id and name aren't the same. The default SCIM Access scope for example shows a reference URL that gives an invalid scope response (as it should be `../uma/scopes/scim_access`).
