### ISSUE TITLE
Federation SP list is not loading in GUI

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#488]
Expected behavior: 

- Create a Trust Relationship with InCommon Federated metadata ( http://md.incommon.org/InCommon/InCommon-metadata.xml ). 
- Done. 
- Move to create a new Trust Relationship: 
    - DisplayName: anything
    - Description: anything
    - Entity Type: `Single Sp`
    - Metadata Type: `Federation`
    - Select Federation: `InCommon` Should be here
    - A link like [this](https://gluu.org/docs/admin-guide/saml/#federation-configuration) should pop up from where we can select desired SP. 

Current situation: 

- 'Metadata Type' is not showing `InCommon`
- No link to select federated SP list. 

There is an existing github [issue](https://github.com/GluuFederation/oxShibboleth/issues/22) there on this.

**Comment by yurem** [comment]
Fixed

**Comment by mzico** [comment]
@yurem : Confirmed. working in 3.0.0
