### ISSUE TITLE
'Configure Relying Party' not appearing in existing Trust Relationship

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#489]
Whenever we go to create a 'new' Trust Relationship; 'Configure Relying Party' is working. 
But if we try to use this feature for an existing Trust Relationship; it's not working. 

I am sharing a video with you
[For_Shekhar.zip](https://github.com/GluuFederation/oxTrust/files/778097/For_Shekhar.zip)

**Comment by zamilskhan** [comment]
Reloading brought the configure link in oxTrust in Ubuntu 14.04.2

**Comment by mzico** [comment]
@zamilskhan : 

>> Reloading brought the configure link in oxTrust in Ubuntu 14.04.2

Which reloading? Shib conf reloading?

**Comment by zamilskhan** [comment]
I reloaded the browser

**Comment by zamilskhan** [comment]
It worked once, but it is not working again. However, when update button is clicked after selecting the configure RP button the following error is thrown in the `oxturst.log` file
```
017-02-15 20:36:33,265 ERROR [qtp425918570-18] [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] (UpdateTrustRelationshipAction.java:291) - Fai
led to save SP meta-data file FileUploadWrapper [contentType=null, fileName=6B0EC88B040A001E0002306704F200063B09E724-sp-metadata.xml, fileSize=null, s
tream=null]
```

**Comment by shekhar16** [comment]
Fixed.
@zamilskhan please test it with latest build.
thanks :)
