### ISSUE TITLE
Application Session tab hidden on Custom Scripts page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#49]
Currently the tab for Application Session is half hidden on the custom scripts page. Let's make an adjustment to the interface so that it can be clearly viewed in full. 

![screenshot 2015-04-07 at 11 34 26 am](https://cloud.githubusercontent.com/assets/5271048/7028210/12a0007e-dd1a-11e4-9570-38bbf2738148.png)

**Comment by yurem** [comment]
In new GUI there is no this bug
