### ISSUE TITLE
Update JSON property comment for sessionAsJWT

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#498]
![image](https://cloud.githubusercontent.com/assets/3717101/23525440/2a949a6a-ff54-11e6-98ae-f6859de33b56.png)

Let's change this comment to:

- Experimental feature. Do not use in production!

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/23564138/7ed87d3c-006f-11e7-9bbd-61e841af0212.png)

**Comment by shekhar16** [comment]
Fixed.
