### ISSUE TITLE
Support post user add custom script

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#5]
Scenario: 
I do not have any backend AD / LDAP. I am using Gluu Server's internal LDAP to store user information. My new user will enter into Gluu Server's LDAP with only oxTrust registration feature. Primarily, I am allowing "Username" and "Email_Address" for registration. Is it possible to automatically map and populate ePPN ( eduPersonPrincipalName )? 

ePPN will take "Email_address" attribute's value. 

That means, if any user register with "Email_Address: john@company.com", then Gluu server will automatically populate ePPN value as "john@company.com".

**Comment by yurem** [comment]
Added support in current code

**Comment by mzico** [comment]
@yurem : How to implement this feature in any live IDP? Customer who require this has 1.7.0 oxtrust and oxauth inside their IDP.

**Comment by yurem** [comment]
You should update it to CE 2.1 and use this script as sample: https://github.com/GluuFederation/oxExternal/blob/master/user_registration/sample/SampleScript.py
