### ISSUE TITLE
Transparent Logo upload problem

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#50]
There's an issue with uploading logos with transparent backgrounds in the oxTrust user interface. See Will's comment below.

**Comment by willow9886** [comment]
I was able to successfully upload a logo. However, when I tried to remove the test logo and upload a different logo, it did not take effect. See screenshot below. 

![Uploading Screenshot 2015-04-08 at 1.23.57 PM - Display 1.png . . .]()

**Comment by willow9886** [comment]
I was able to upload multiple logos without issue..

**Comment by willow9886** [comment]
There's an issue with uploading logos with transparent backgrounds in the oxtrust user interface. When you upload an image with a transparent background, it shows up like the screenshots below.

![screenshot 2015-04-08 at 2 29 31 pm](https://cloud.githubusercontent.com/assets/5271048/7053559/c3c55692-ddfb-11e4-98ad-af643346e0d6.png)

![screenshot 2015-04-08 at 2 29 25 pm](https://cloud.githubusercontent.com/assets/5271048/7053561/c6677ccc-ddfb-11e4-85ed-849f13ae4ea6.png)

**Comment by zamilskhan** [comment]
Yes, the same thing happened in the CE Ubuntu 2.1 Installation. The problem seems to be with transparent background.

**Comment by otataryn** [comment]
Fixed by changing thumbnail image type from JPEG to PNG.
JPEG does not allow for alpha channel, and apparently sun image library works differently on Windows and CentOS: on Windows it just drops alpha altogether and on CentOS it throws an exception. 

With PNG as image format for thumbnails there should not be any issues.
