### ISSUE TITLE
failed to make connection to backend: localhost

### ISSUE THREAD

**Issue by abel408** [GluuFederation/oxTrust#501]
Hello all,

I have a brand new install on Ubuntu 16.10. Everything was working well during set up. I gave the server a restart and now I am prompted with this a 503 Service Unavailable message each time I try to get to the gluu gui admin.

My apache error logs show this:

`[Tue Mar 07 15:19:36.808362 2017] [proxy:error] [pid 2657:tid 140669666436864] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8082 (localhost) failed
[Tue Mar 07 15:19:36.808471 2017] [proxy:error] [pid 2657:tid 140669666436864] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 5s
[Tue Mar 07 15:19:36.808519 2017] [proxy_http:error] [pid 2657:tid 140669666436864] [client 10.131.0.227:64585] AH01114: HTTP: failed to make connection to backend: localhost`

I've already attempted reinstalling gluu with the same outcome. I've read the installation guide at least 5 times. Not sure what I'm doing wrong.

**Comment by willow9886** [comment]
Hi @abel408 support issues need to be routed through http://support.gluu.org . If we find a bug from your ticket, we will open and assign a github issue as needed. 

Thanks,
Will
