### ISSUE TITLE
Remove "Default" From Select List

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#506]
![image](https://cloud.githubusercontent.com/assets/3717101/24180632/f68cb830-0e83-11e7-90ed-75468463205f.png)

If a person selects `Default`, what happens is that the last authentication method is used.  This is confusing behavior.

The initial default value should be `auth_ldap_server`. We should remove the `Default` value which can only cause trouble.

**Comment by shekhar16** [comment]
Fixed.
