### ISSUE TITLE
Oxtrust | Fix input validation message for dynamicRegistrationExpirationTime 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#509]
GUI under JSON Configuration->OxAuth Configuration
Set expiration time "dynamicRegistrationExpirationTime" 0

Error Message in the field validation:  Value must be at least 1.

![image](https://cloud.githubusercontent.com/assets/21104811/24224465/4df194e4-0f81-11e7-9ab9-e60f95ae4d47.png)

**Comment by willow9886** [comment]
duplicate: https://github.com/GluuFederation/oxTrust/issues/508
