### ISSUE TITLE
in JSON Config, adjust "Ox" formatting

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#510]
![image](https://cloud.githubusercontent.com/assets/5271048/24473502/239b5cc6-148f-11e7-9b4a-d894dfef8538.png)

`oxTrust`, `oxAuth` should always be formatted in this way, where ox is lower case. 

Currently in JSON config page, it is formatted as OxTrust OxAuth, which is different from all our other formatting.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24521874/511c9e86-15ab-11e7-9f1f-84d2c299552d.png)

**Comment by willow9886** [comment]
nice. Thanks @shekhar16
