### ISSUE TITLE
Explanation of fields in JSON Configuration > oxTrust Configuration & oxTrust Import Person Configuration 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#511]
In oxAuth JSON Config section we have explanations for each field, as shown in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5271048/24474063/0b8a780e-1491-11e7-84a5-181ab8e52b85.png)

We should provide the same human readable explanations for oxTrust Configuration and oxTrust Import Person Configuration. 

![image](https://cloud.githubusercontent.com/assets/5271048/24474147/47492502-1491-11e7-960b-9d3b3d347888.png)

@shekhar16 maybe you can work with Zico to come up with explanations or descriptions for each field and then run it by me so I can make sure the English is clear and makes sense?

**Comment by mzico** [comment]
@shekhar16 : I will go over all fields and share a list which will have one line explanations with you. Added in my internal ToDo list.

**Comment by yurem** [comment]
@mzico and @shekhar16 can we fix it in 3.1.0?

**Comment by shekhar16** [comment]
@mzico  can u please share the url or path where you added this dscription.

**Comment by willow9886** [comment]
Lets track this as an issue in docs repo: https://github.com/GluuFederation/docs-ce-prod/issues/38
