### ISSUE TITLE
Invalid reference urls displayed on UMA scopes

### ISSUE THREAD

**Issue by ianalexr** [GluuFederation/oxTrust#512]
The fix for #487 uses the name of the scope instead of the id, so invalid reference urls are displayed if the scope id and name aren't the same. For example, the default SCIM Access scope shows a reference URL that gives an invalid scope response `../uma/scopes/SCIM Access` instead of the acutal scope `.../uma/scopes/scim_access`.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24577014/96482604-16e3-11e7-8b99-eaa353232bc7.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
Fixed in 3.0.2 version
