### ISSUE TITLE
Federation TR's creation/editing page lacks critical controls and can't be edited

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#515]
Environment:
CentOS 7.3, gluu-server-3.0.1-2-1.centos6 (but also was tried in the latest oxTrust snapshot war), Google Chrome

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "SAML -> Trust Relationship" page and click "Add relationship" button there
3. Create federation using entity type of "Federation/Aggregate", method "URI" and this source of metadata: [https://www.testshib.org/metadata/testshib-providers.xml](https://www.testshib.org/metadata/testshib-providers.xml) (it has 2 entities, but still can pass as fed metadata, and it's easier to handle than InCommon's huge blob) and wait till it'll pass validation
4. Try to update description of the federation you created

Result:
On step 3) you can already see that creation page doesn't contain "Configure RelyingParty" and "Released attributes" controls. Even if it's open for editing after created, they won't appear. Please see picture below:
![fed-page-lacks-controls](https://cloud.githubusercontent.com/assets/11802046/24624324/2c9b49ac-18b4-11e7-9012-265e2ed0fed2.jpg)

On step 4) you are presented with "System error" message, update doesn't happen and next Java exception is logged in `/opt/gluu/jetty/identity/logs/oxtrust.log` (full text is [here](https://github.com/GluuFederation/oxTrust/files/890970/federation-md-update-log.txt)):

```
2017-04-03 18:15:42,771 ERROR [qtp274064559-14] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: java.lang.NullPointerException
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) ~[?:?]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
```

Expected result:
Both creating and editing pages for federation TRs must contain mentioned controls (some users, including customers, rely on them from previous versions).

**Comment by nynymike** [comment]
Alex, configure relying party and released attributes doesn't apply to federation metadata. Also, I'm not able to reproduce your issue in my Ubuntu 14 test instance. Are you saying that this is a problem only in Red Hat 7? Can you re-test to make sure this is the case.

**Comment by aliaksander-samuseu** [comment]
@nynymike @shekhar16 

I did some additional testing in 2.4.4SP3 and 3.1 packages to compare previous and current behaviour of this feature.

2.4.4: On federation's properties page there are both controls for R&S and custom RP config features;  the later in case of fed TR does nothing  (nothing is changed in `relying-party.xml`), the former actually adds certain constructs to `attribute-filter.xml` needed to support R&S categories; in case of fed TR full list of fed's entityids are put in `attribute-filter.xml` inside of  `AttributeFilterPolicy` element; the page allows to add released attributes and correctly modifies  `attribute-filter.xml` to release those attributes to all entityids of the federation. The whole setup in fact works, it basically sends specified attributes to any fed's entityid using default relying party config, what probably could be a useful feature.

3.1: On federation's properties page there are no controls for R&S and custom RP config features any more. List of released attributes is also missing (though during fed TR's creation you can add attributes to it by clicking them, and after TR is created those attributes are also persisted in LDAP; a correct `AttributeFilterPolicy` element's structure is put into `attribute-filter.xml`; but the final setup doesn't work, it can't release attributes to any entityid of the federation as it could in 2.4.4 due to the fact no metadata element is added for this fed TR to `metadata-providers.xml`

I'm not sure whether this change was intended or is it a bug.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

Please also note that in the latest 3.1 beta package I still can't update description of fed TR after it was created, it throws some Java excepation.

**Comment by aliaksander-samuseu** [comment]
@nynymike @shekhar16 

As we are use IdP v3.2 in CE3.1, we now could probably utilize its enhanced relying party definitions, like `RelyingPartyByGroup` which is keyed not by entityid, but by metadata's attributes (described [here](https://wiki.shibboleth.net/confluence/display/IDP30/RelyingPartyConfiguration)). That would not only allow Gluu's users to create a general federation rules releasing some limited set of attributes to all members of the federation, but also to set custom profile settings for it (didn't work in 2.4.4). If those beans are ordered correctly, with federation `RelyingPartyByGroup` beans following more exact `RelyingPartyByName` beans, we could achieve "general rules + exceptions" design, which probably could be useful in some cases (no need to create a separate TR for each and every SP, if most of them work fine using the general federation TR)

**Comment by shekhar16** [comment]
The relying party will be visible when we select entity type=single sp.
The page was redesign as per https://github.com/GluuFederation/oxTrust/issues/310

**Comment by aliaksander-samuseu** [comment]
@shekhar16 
Just wanted to make sure there is no confusion here. As mentioned above, in IdPv3 we got those new conditions - `RelyingPartyByGroup`/`RelyingPartyByTag` - which actually may make those controls useful for federations too, if employed. So we could allow users to create general TR for some federation, instead of creating separate TRs for each SP he needs from this federation (they still could create individual TRs for this federation as well, if they need some specific, different settings for this one SP).

Actually, some of our users were configuring their Gluu instances this way even in previous versions already (though it wasn't fully supported). So I thought it may be a useful feature.

**Comment by aliaksander-samuseu** [comment]
Closing it for now.
