### ISSUE TITLE
Support inetOrgPerson

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#516]
In metadata for `inetOrgPerson` attributes which are not included in `gluuPerson`, change `gluuAttributeOrigin` to `gluuCustomPerson`

Customers who want to add these attributes should just add them to the gluuPerson LDAP schema.

```
gluuAttributeName: carLicense
gluuAttributeName: facsimileTelephoneNumber
gluuAttributeName: departmentNumber
gluuAttributeName: employeeType
gluuAttributeName: cn
gluuAttributeName: mobile
gluuAttributeName: telephoneNumber
gluuAttributeName: st
gluuAttributeName: manager
gluuAttributeName: street
gluuAttributeName: postOfficeBox
gluuAttributeName: employeeNumber
gluuAttributeName: preferredDeliveryMethod
gluuAttributeName: telephoneNumber
gluuAttributeName: roomNumber
gluuAttributeName: secretary
gluuAttributeName: homePostalAddress
gluuAttributeName: l
gluuAttributeName: postalCode
gluuAttributeName: description
gluuAttributeName: title
```

**Comment by nynymike** [comment]
moving this to community-edition-setup

**Comment by aliaksander-samuseu** [comment]
@nynymike 

Was it fixed? I still see that such inetorgperson attributes like "mobile", "cn" etc are not shown on "Attributes" pages in current beta CE 3.1.0 packages, but metadata for them is present in LDAP, preventing registering attributes with such names in LDAP. I haven't tested 3.0.2 yet.

**Comment by willow9886** [comment]
Moved to: https://github.com/GluuFederation/community-edition-setup/issues/282

**Comment by aliaksander-samuseu** [comment]
Removed my comment, sorry for confusion.
