### ISSUE TITLE
Change "Default" terminology

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#517]
![image](https://cloud.githubusercontent.com/assets/5271048/24776067/fbdba9f0-1ae4-11e7-92d7-f237420b05ac.png)

What is default authentication? Is it LDAP authentication? 

If so, then that's what it should be called. How is anybody supposed to know what default means?

**Comment by nynymike** [comment]
This should probably be changed to include just the available acr's. "Default" is not necessary... the default is "auth_ldap_server"

**Comment by willow9886** [comment]
But `auth_ldap_server` is also an available choice... see screenshot below.

So shouldn't `auth_ldap_server` just be the default? 

![image](https://cloud.githubusercontent.com/assets/5271048/24830325/8537d916-1c49-11e7-879d-3ae631a6153a.png)
