### ISSUE TITLE
Change title of the two default authentication methods fields

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#518]
![image](https://cloud.githubusercontent.com/assets/5271048/24777088/6cb0594c-1ae9-11e7-8b7e-91f6e000183b.png)

It's not 100% clear what the difference is between the two default authentication options... 

Let's update the the title's of the two fields to:

Default authentication method for apps:

Authentication method to access Gluu UI ("oxTrust"):

**Comment by nynymike** [comment]
How about:
1. "Default acr"
2. "oxTrust acr" 

The docs should further explain their purpose.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24825558/45ae6536-1c3e-11e7-85ad-b82486b5d32d.png)

**Comment by shekhar16** [comment]
Fix  in 3.0.2 version
