### ISSUE TITLE
Developer environment

### ISSUE THREAD

**Issue by rystraum** [GluuFederation/oxTrust#52]
Hi,

I'm familiar with Java but has not worked on jBoss before, but I'm comfortable enough with OOP and frameworks to feel my way around. I would like to contribute to this project, but I've been trying to set up a workflow where I can test my changes to no avail.

Do you have any documentation on how we can set a development environment up?

**Comment by otataryn** [comment]
Hello. 
The easiest way to fire up an enenvironment would be to create your own CE deployment, as described here: http://www.gluu.org/docs/articles/gluu-server-ce/ (see Installation). Once that is done you will be able to hack around and to move parts of the project to your workstation.

**Comment by nynymike** [comment]
Rys,

Rahat just setup a development oxTrust environment, and may have some tips on setting up your development environment.

- Mike

**Comment by willow9886** [comment]
Also, this guide might help you get the test environment setup:

https://github.com/GluuFederation/oxTrust/wiki/Setting-up-Development-Environment-on-Windows

Closing this issue for now.
