### ISSUE TITLE
Change or remove "basic" authentication

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#521]
![image](https://cloud.githubusercontent.com/assets/5271048/24777303/5f6d022a-1aea-11e7-911a-b4c1d72ed996.png)

This is similar to issue #517 ..

Basic is not a very descriptive name for an authentication method. Is this LDAP authentication? If so, then we should just call it LDAP authentication.

**Comment by nynymike** [comment]
These values come from the name of the script.
