### ISSUE TITLE
Centralize log4j2.xml

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#522]
`log4j2.xml` needs to be moved outside of the war file. Not only is the current location bad...
but also, it is overwritten from the original war file on restart of jetty. Finally, the export script also needs to make sure that the log4j2.xml is backed up and restored. 

I'm putting this as a 3.1 issue, but a workaround also needs to be documented for version 3, or we will not be able to handle cluster logs.

**Comment by yurem** [comment]
In oxAuth/oxTrust log files all log folders are relative to 'catalina.base' variable. We set it in [/etс/defaults/oxauth](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/jetty/oxauth#L3)

As result in 3.0.1 it's easy to change location of application logs files via /etс/defaults/oxauth|oxtrust.

Also we can add programmatic approach too. In method AppInitializer.updateLoggingSeverity we need to add:
 if (need_to_change_logs_location) {
  System.setProperty("catalina.base", "/path/to/log/folder");
  LoggerContext loggerContext = LoggerContext.getContext(false);
  loggerContext.reconfigure();
}

I offer to add new system variable 'gluu.base.log' (or any better name) then continue to use tomcat specific variable 'catalina.base'

**Comment by nynymike** [comment]
yes, please proceed.

**Comment by willow9886** [comment]
It would be nice if we had a work around in 3.0.2 and a final solution in 3.1.0.

**Comment by worm333** [comment]
@nynymike  I'm not quite understand why the current location of [log4j.xml](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/log4j2.xml) is bad and what `original`.war file is overwriting it. Could you please elaborate more on this issue?

And I'm afraid I didn't get what kind of `export script` are you talking about.

**Comment by yurem** [comment]
In our log4j2.xml all folders are relative to ${sys:catalina.base} We can use this. In method which apply log level we can try to set this system variable value to change log files location.
Additionally I offer to rename "catalina.base" to "log.base".

**Comment by shekhar16** [comment]
to move log4j.xml file outside war file, we need to add in deployment descriptor.

<context-param>
        <param-name>log4jConfigLocation</param-name>
        <param-value>file://${MY_ENV_VAR}log4j.xml</param-value>
    </context-param>

    <listener>
        <listener-class>org.springframework.web.util.Log4jConfigListener</listener-class>
    </listener>

**Comment by yurem** [comment]
@mike, are we really need to move log4j2.xml outside of war or we just need to allow to move log files to other folder? log4j2.xml is part of oxAuth.war which is mandatory to proper server start.

**Comment by worm333** [comment]
@yurem, @nynymike please correct me if I'm wrong. As I understand the goal of this issue is to provide the possibility to admins to change the location of log files.

 So basically we need to add into `/identity/logviewer/configure` page new field e.g.: `Log base` where admins could change the location of log files.
 Also we need to update [identity](https://github.com/GluuFederation/community-edition-setup/blob/4f60438c32f35a4594ce2da92701a57970ef69ba/templates/jetty/identity) template in [community-edition-setup](https://github.com/GluuFederation/community-edition-setup) in order to  rename system variable `catalina.base` to `log.base` ( and also rename all usages of `catalina.base` in oxTrust).

**Comment by worm333** [comment]
I've added new field `External log4j location`  in `/identity/logviewer/configure` form. If field is empty or path to external log4j is incorrect (file does not exist), then log4j2 will read the default logger config from .war (otherwise logger will be configured from external config)
