### ISSUE TITLE
Client Form: Enable admin to enable / disable refresh token issuance

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#523]
https://github.com/GluuFederation/oxAuth/issues/18

I was reading this article: http://gluu.co/connect-deep-dive and this part jumped out at me:

NOTE: The AS may or may not issue a refresh token to a particular client. Issuing such a token is ultimately a trust decision. If you have doubts about a client’s ability to keep these privileged tokens safe, don’t issue it one!

The configuration for refresh tokens should be stored in the client ldap entry and exposed as client configuration in oxtrust.  Let's add an attribute called `oxClientRefreshTokenEnabled` and add it to the `oxClient` objectclass.

**Comment by nynymike** [comment]
Actually this is controlled if the grant_type "refresh_token" is allowed. This change should be backed out.

**Comment by rajnikantsh** [comment]
Branch is not merge in master hence their is no change because of this issue
