### ISSUE TITLE
Use servers which are in 'Manage Authentication' list

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#525]
![iteration_manage_authentication](https://cloud.githubusercontent.com/assets/7156097/24913523/13a9af68-1e97-11e7-99e3-c0e4ac96b792.png)

According to above setup, authentication won't face any issue if any server of three ( server1,server2,server3 ) are online and active. 

Right now, oxTrust is only using 'server1.gluu.org:1636' but if 'server1' goes down; oxTrust is not iterating the list and not getting to server2 or server3. 

Here is how it should work: 

- Use 'server1:1636' by default
- If 'server1:1636' is not reachable, go to server2:1636
- If server2:1636 is not available as well, go to server3.:1636

According to oxAuth developer, this feature is already implemented in oxAuth. So we need to cover the half now.

**Comment by yurem** [comment]
Let add some corrections to description..
oxAuth uses all server1...server3 specified in description. But it treat them as one server which has few fail-over servers. As result it creates fail-over set with server1...server3.

oxAuth also supports different LDAP server settings. For this there is oxIDPAuthentication attribute. It's multi-valued attribute. But oxTrust not allows to add moe than one configuration. It's the issue.

**Comment by shekhar16** [comment]
For this issue , should we use same attribute i.e oxIDPAuthentication and its connections?

**Comment by yurem** [comment]
yes, we can store server settings in multi-valued oxIDPAuthentication attribute. oxAuth supports this already.

Also we can clean up this part. We can remove methods which converts configuration from < v1.0 to current format. In the code there are comments about this.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29365806-d4af394e-82b5-11e7-9afa-00513fb6eb0e.png)

**Comment by yurem** [comment]
I've updated pull request and merged it.

But there are bugs in new code. For example set password dialog set password to wrong config.

New code should not use this variable: https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/ManagePersonAuthenticationAction.java#L102

**Comment by willow9886** [comment]
@shekhar16 we need a fix on this ASAP. It's blocking our ability to build a new test package.. thanks in advance!

**Comment by shekhar16** [comment]
@willow9886   i committed the  code please test it and let me know if I need to correct or add anything in this functionality.
Thanx :)

**Comment by yurem** [comment]
I've review and add small changes https://github.com/GluuFederation/oxTrust/commit/7cd69127b66c5244faa6e6647b0b3506490bdda1

It works fine now
