### ISSUE TITLE
Translate resource bundles

### ISSUE THREAD

**Issue by worm333** [GluuFederation/oxTrust#531]
### Translation guide.
oxTrust contains the following resource bundles: [oxtrust_en.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_en.properties), [oxtrust_fr.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_fr.properties) and [oxtrust_ru.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_ru.properties)

These properties files store the translatable text of the messages to be displayed.
The default properties file, which is called [oxtrust_en.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_en.properties), contains the following lines:
```
home.welcome = Welcome to your Gluu Identity Appliance {0} !
home.freeMemory = Free Memory
home.freeDiskSpace = Free Disk Space
.......
```
Now that the messages are in a properties file, they can be translated into various languages. No changes to the source code are required. For example to use the French version of the oxTrust the [oxtrust_fr.properties](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/resources/oxtrust_fr.properties) should contains these lines:
```
home.welcome = Bienvenue dans votre Gluu Identity Appliance {0} !
home.freeMemory = Mémoire libre
home.freeDiskSpace = Espace disque libre
.......
```
Notice that the values to the right side of the equal sign have been translated but that the keys on the left side have not been changed. These keys must not change, because they will be referenced when oxTrust fetches the translated text.

To add translation for not yet supported languages, just create new properties file in [resource](https://github.com/GluuFederation/oxTrust/tree/master/server/src/main/resources) folder and name it oxtrust_[language_code].properties, then make sure that values to the right side of the equal sign have been translated.

**Comment by nynymike** [comment]
The community can provide translations...
