### ISSUE TITLE
Duplicate oxTrust graph legends

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#532]
Do we need both of them? 

![indication_bar](https://cloud.githubusercontent.com/assets/7156097/25292999/5baa1848-269e-11e7-856b-0b7f99654a4f.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/25312262/d58878e0-2832-11e7-9c8f-878de12c5b9b.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/25312350/ab34bb92-2834-11e7-9a1f-33368f5a7e88.png)
