### ISSUE TITLE
No way to remove federated sp metadata

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#533]
Two screenshots attached. 

First one, a file type trust relationship; as you can see there is a cross button which help administrator to remove current metadata if required. 

Second one, an InCommon affiliated trust relationship; there is no way to remove SP metadata/metadata link. 

To replace any InCommon affiliated SP metadata, administrator need to delete this trust relationship first and then can add new one with new metadata link. 

![cross_button](https://cloud.githubusercontent.com/assets/7156097/25293380/41d21612-26a0-11e7-8b1d-c7db3d550aff.png)

![fed_affiliated_sp](https://cloud.githubusercontent.com/assets/7156097/25293383/454c3cdc-26a0-11e7-87b1-a57ba52e1bd0.png)

**Comment by shekhar16** [comment]
[8:44:15 PM | Edited 8:44:21 PM] Shekhar L: Hi Dmitry
[8:44:45 PM] Dmitry Ogn: Hi Shekhar
[8:45:28 PM] Shekhar L: Can u please help me on issue for which Yuriy M created the conversation
[8:45:47 PM] Dmitry Ogn: Yeah
[8:45:55 PM] Shekhar L: I m facing CAS issue on SAml validation
[8:46:17 PM] Shekhar L: and I think both are independent
[8:46:49 PM] Dmitry Ogn: I'll fix it.
[8:47:05 PM] Shekhar L: ok

**Comment by shekhar16** [comment]
Waiting for this fix.

**Comment by dmogn** [comment]
@mzico  check, please.
User can select other entityID. No sense in empty/null entityID with type SP - 'federation', right?
Or user can select other TR type - then entityID will be hidden.

![533_1](https://user-images.githubusercontent.com/14166017/31233339-d35b4f72-a9c2-11e7-85c6-ae78c5db0261.jpg)

![533_2](https://user-images.githubusercontent.com/14166017/31233347-db68cdfc-a9c2-11e7-92b9-0e0b735e2d1e.jpg)
