### ISSUE TITLE
MAX_COUNT in SCIM Client negative test cases

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#536]
Get 'MAX_COUNT'  property from oxtrust config in Scim client negative testcases after migration.

**Comment by jgomer2001** [comment]
SCIM-client cannot or **should not** read the oxtrust config, but SCIM-server code should, so this is a fix applicable for oxTrust project only

**Comment by jgomer2001** [comment]
Now admin UI should look like this (after doing maven install of oxtrust-static):
![536](https://user-images.githubusercontent.com/5444180/32744138-9a709838-c87c-11e7-9ca8-dc428dad2895.png)
