### ISSUE TITLE
Unable to remove Custom Script from oxTrust UI

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#537]
OS: CentOS 6.8 (possibly affecting all other)
Package: 2.4.4 sp2 upgraded to 3.0.1
Ticket: https://support.gluu.org/upgrade/3982/migrated-244sp2-301-unable-to-delete-unwanted-person-authentication-scripts/
Steps to reproduce: Install 2.4.4 and update to `2.4.4-sp2` be replacing the `identity.war, `oxauth.war` from maven and upgrade to 3.0.1. Log in and try to remove custom scripts it will throw error. 
Report: https://github.com/GluuFederation/gluu-qa/wiki/Itemized-Reports#upgrade-script
Observation: Issue confirmed with similar stack trace given in the ticket.

**Comment by rajnikantsh** [comment]
Issue was related to date format of oxAuthAuthenticationTime attribute. so change in migration script for  date format while importing data in CE-3.0.2
