### ISSUE TITLE
oxTrust user registration - confirmation email possible? 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#540]
In 3.x, current scenario is: 

- Enable registration script from oxTrust. 
- Hit https://[hostname]/identity/register
- Fill up the form and hit 'register'

After third step, workflow is jumping to oxAuth login page. 

Is it possible to send a confirmation email to newly registered person? 
And, would be great if we can show ... after registration... 'User successfully registered, please log into to Gluu Server'

Advanced level enhancement: 

- If possible, send activation link to newly registered email_address
- After 'activation' from forwarded link to email; user will be become 'active' in Gluu Server. 

Thoughts? Suggestion? 

@nynymike @willow9886 @shekhar16

**Comment by willow9886** [comment]
Yea, sounds like we need a better default user registration user experience.

**Comment by yurem** [comment]
yes, we need to implement it. Partially we can do this now. I offer to implement custom logic via registration script.
Here is what I suggest to add:
1. Add to [registration ](https://github.com/GluuFederation/oxExternal/blob/master/user_registration/sample/SampleScript.py) script.
```
    def getConfirmationPage(self, user, requestParameters, configurationAttributes):
        print "User registration. Get confirmation page"

   def confirmRegistration(self, user, requestParameters, configurationAttributes):
        print "User registration. Confirm method"
```
If getConfirmationPage return non empty string we need to redirect user to specified page after registration

2. Add page /oxtrust-server/src/main/webapp/confirmRegister.xhtml (/register/confirm) which should call 'confirmRegistration'

**Comment by yurem** [comment]
After that we can implement what @mzico suggested:
1. In preRegister add to user entry attribute with random GUID
2. In post Register we need to send e-mail with link and with GUID at the end
3. In confirmRegistration we need to try to find user by GUI and remove GUID and active user.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxExternal/commit/c744eceed84357e83d7f66f5eb875927385219ee#diff-c26b65d1d358368054b5000f284c7582

**Comment by yurem** [comment]
@shekhar16 can you write new sample scripts which implements this work flow?

Can you add these new methods to sample script: https://github.com/GluuFederation/oxExternal/blob/master/user_registration/sample/SampleScript.py

**Comment by yurem** [comment]
We opened simular issue some tiem ago:
`Extend registration script. Add method to allow call special endpoint externally` #324

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxExternal/commit/ed61aba9259f10bf865886cda910328b89350f73#diff-c26b65d1d358368054b5000f284c7582

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/17c792027487c970720070904dd7ebc941e42c9e

**Comment by yurem** [comment]
I've comments about: https://github.com/GluuFederation/oxExternal/blob/master/user_registration/confirm_registration/SampleScript.py

It's almost ready. We only can't store self.guid in script context because it's global context.
Instead of this we need to try to find user by this attribute.

Also please add more print statemements and use this method to get request value:
            confirmation_code = ServerUtil.getFirstValue(requestParameters, "code")
            if ArrayHelper.isEmpty(confirmation_code):
                print "User registration. Confirm method. Confirmation code not existin tin request"

                return True

And
appConfiguration= CdiUtil.bean(AppConfiguration)
it's
org.xdi.config.oxtrust.AppConfiguration
You can get any property of this configuration bean to generate e-mail

**Comment by rajnikantsh** [comment]
Changes are made. created pull request  https://github.com/GluuFederation/oxExternal/pull/3

**Comment by jschristie** [comment]
@yurem @rajnikantsh 
not able to get registration page.

I have enabled user registration script, I am using RC3 build.

**Comment by jschristie** [comment]
https://trello.com/c/fbjWYuFq/53-%CA%BAoxtrust-user-registration-confirmation-email-possible

**Comment by rajnikantsh** [comment]
code comitted with pull request https://github.com/GluuFederation/oxTrust/pull/667

**Comment by yurem** [comment]
Why we can't move code from confirmation method to custom script? We don't need to hard code this logic in code.

**Comment by rajnikantsh** [comment]
code comitted https://github.com/GluuFederation/oxTrust/pull/686
