### ISSUE TITLE
Cancel button not displayed correct on UMA Scope screen

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#542]
UMA > Scopes > Update Scope

![image](https://cloud.githubusercontent.com/assets/21104811/25744401/60b297b0-31b7-11e7-9fc6-d3b035b8f507.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/25780964/c89f96e0-334f-11e7-8bda-7518e5769d19.png)
