### ISSUE TITLE
SCIM2 test mode compilation failed after Validate Token endpoints removal

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#546]
We need to rewrite these methods in weld branch to provides same functionality which we have with validate token endpoints:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/BaseScimWebService.java#L97

https://github.com/GluuFederation/oxTrust/blob/weld/server/src/main/java/org/gluu/oxtrust/ldap/service/JsonConfigurationService.java#L179

**Comment by jgomer2001** [comment]
@yurem Please take a look at the couple of pull requests that point to solving this issue
