### ISSUE TITLE
Unable to login in local dev env

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#547]
I had oxtrust master,oxauth master and oxcore weld branch.But getting 404 errors on oxauth pages
![image](https://cloud.githubusercontent.com/assets/15937500/25884873/cce7386e-3572-11e7-8e1f-ae4b180e6875.png)

![image](https://cloud.githubusercontent.com/assets/15937500/25884883/e128a7cc-3572-11e7-8557-ce1d2d4ce150.png)

**Comment by shekhar16** [comment]
@yurem  i checked the oxauth master branch which has been migrated to weld framework and found that we removed the authorize.page.xml ,login.page.xml and other *.page.xml whichwas responsible to map the url for that page.

Now after migration i think we need to change the path of oxauth pages by adding suffix  *.htm as per web.xml maping of faceservlet .
And I tested above solution and getting pages.
Please suggest.

**Comment by yurem** [comment]
I think current oxAuth code not enable pretty urls. @worm333 Can you fix this.

**Comment by yurem** [comment]
@shekhar16 I think we can close this issue.
