### ISSUE TITLE
Password reset is broken

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#552]
Steps to reproduce -
Enable Self-service password reset from UI
Provide SMTP configuration
Access https://<host>/identity/person/passwordReminder.htm
Provide Email ID and click Submit
Now  Click on the password reset link received in email

Expected - Allows to change password 
Actual - Redirects to Login screen

Ubuntu 14.04
Implementation-Version: 3.0.2
Implementation-Build: ea927^M

Logs
WARNING: #{passwordReminderAction.requestReminder}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: oxGuid=htcb7hy9p0zspbgn, ou=resetPasswordRequests,inum=@!2FFE.143E.3D99.853C!0002!276F.8FF8,ou=appliances,o=gluu
javax.faces.FacesException: #{passwordReminderAction.requestReminder}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: oxGuid=htcb7hy9p0zspbgn, ou=resetPasswordRequests,inum=@!2FFE.143E.3D99.853C!0002!276F.8FF8,ou=appliances,o=gluu

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/554

**Comment by shekhar16** [comment]
fixed in both master and  3.0.2 branch.
@sahiliamsso  can u please verify the fix with latest code.
