### ISSUE TITLE
Captcha not showing up on registration 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#558]
Disable Captcha for Registration form is unchecked. But Captcha NOT showing up on registration page

![image](https://cloud.githubusercontent.com/assets/21104811/26181424/8dd10ce2-3b8d-11e7-9729-40beb546c2cf.png)

![image](https://cloud.githubusercontent.com/assets/21104811/26181435/a969cfe8-3b8d-11e7-9ff6-291628df343b.png)

**Comment by willow9886** [comment]
@sahiliamsso your screenshot doesn't show a captcha being presented?

**Comment by sahiliamsso** [comment]
I tried both ways by enabling/disabling but its NOT showing up on registration screen.

**Comment by shekhar16** [comment]
@sahiliamsso ,please check the recaptcha site and secret key in your oxtrust configuration.I think it is missing in your configuration.

**Comment by willow9886** [comment]
@shekhar16 can we make Captcha disabled by default? 

The field should really say: 

> Enable captcha for registration form 

And then if you need to make additional changes in configuration for captcha to take effect, those instructions should be presented to a user.

**Comment by shekhar16** [comment]
@willow9886 yes we can make Captcha disabled default.
To work this functionality proprly ,we need to register with captcha site and then we get keys.So we should check with Yuriy M about these keys.

**Comment by sahiliamsso** [comment]
ok i see if i am entering valid captcha site key and client secret then it shows up on registration form.

**Comment by shekhar16** [comment]
@sahiliamsso can we close this issue.

**Comment by sahiliamsso** [comment]
Sekhar, Original issue can be marked resolved. However this one still not fixed as mentioned by @willow9886 
```
can we make Captcha disabled by default?

The field should really say:

Enable captcha for registration form
And then if you need to make additional changes in configuration for captcha to take effect, those instructions should be presented to a user.
```

**Comment by shekhar16** [comment]
I think @yurem can tell us,about the recaptcha keys whether we are setting it up in setup or this would be for specific clients.

**Comment by zamilskhan** [comment]
Tested, working properly in 3.0.2. Closing ticket.
