### ISSUE TITLE
oxTrust should check environment variables for ox-ldap.properties

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#562]
It would be good if oxTrust could check the environment variables first for oxLDAP.properties and then look to the file system.

**Comment by nynymike** [comment]
For docker deployment, we'd prefer not to have any file.

**Comment by dmogn** [comment]
We need a flag to detect "Docker" version in oxTrust. At now oxTrust can detect CE only:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/util/ProductInstallationChecker.java
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/ProductInstallationCheckerAction.java

**Comment by iromli** [comment]
This is related to hide SAML menu in docker version of oxTrust though. A workaround to hide the menu is to create `/install/community-edition-setup` directory in oxTrust docker image.

**Comment by yurem** [comment]
@rahatjaan we need to add same method to oxAuth to allow override use env variables instead of ox-ldap.properties

Is this works fine if we don't have ox-ldap.properties at all?
