### ISSUE TITLE
Spelling Mistake at Gluu Server > Person

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#564]
Gluu Server 3.1.0
1- Navigate to User > Manage People
2- Search one person / Add Update User
3- At Left side Nav menu Wrong spelling for User Permission
It should be "User Permission" instead of "User permisison"

**Comment by shekhar16** [comment]
@centroxy User permisison is an attribute, you can modify it from configuration -> attributes

**Comment by centroxy** [comment]
Hi @shekhar16 . This user permission attribute comes with Gluu server as default attribute. Is it possible to correct the spelling, so when we install Gluu server, we see the correct one.

**Comment by willow9886** [comment]
Yes, >permisison  is not the correct spelling. It should be spelled as @centroxy noted above: > Permission

**Comment by shekhar16** [comment]
To modify the attribute display name is a immediate solution as we provide this functionality from oxtrust UI.
We will update the preloaded data in LDAP.
Thanks.

**Comment by shekhar16** [comment]
Fixed.
