### ISSUE TITLE
"Enable proxy patterns" feature of CAS page doesn't seem to work

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#566]
Environment:
Ubuntu 14.04, Gluu CE 3.0.2

Preconditions:
1. A freshly installed Gluu CE instance with IdP component, where CAS hasn't been configured yet

Steps to reproduce:
1. Log in to web UI as admin user
2. Proceed to "Configuration -> Manage authentication" page, "CAS Protocol" tab
3. Set "Enable" checkbox, click "Update" button then "Update configuration files" button
4. Move into the container, copy contents of IdP's conf dir before proxy settings is touched to use as a reference in the future: `#  cp -R /opt/shibboleth-idp/conf/ idp-conf-for-comparison/`
5. Set "Enable Proxy Patterns" checkbox, click "Update" button then "Update configuration files" button
6. In the container, compare current files in IdP conf directory to the ones preserved before: `# diff -q -r idp-conf-for-comparison/conf/ /opt/shibboleth-idp/conf/`

Result:
The comparison shows no changes to the files was done on step 5) As it's hard to say what actually this feature should do, no estimations for expected result are available atm. Dmitry evaluated it as an issue and asked to create a report for him

**Comment by nynymike** [comment]
If this feature is not doing anything, let's just remove it from the GUI.
