### ISSUE TITLE
Migration to Weld 3.0.0

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#567]
Many parts already were updated to Weld 3.0, JSF 2.2 and RestEasy 3.x.

There are next issues which we need to resolve in order to resolve this issue:
1) oxTrust reads all navigation.xml files and update faces-config.xml at runtime. But all added navigation-cases not work. We need to fix this.
2) Update last 55 places where there are: s:validateAll, s:validate, s:validateEquality, s:graphicsImage, s:message, s:button, s:link, s:fileUpload, s:defaultAction.\

**Comment by yurem** [comment]
I comment out navigation.xml files validation. We don't need to validate them as generica faces-config.xml files. They are custom gluu navigation.xml files. We need to add xsd if needed to fix this. Also I fixed login method. @shekhar16 , @willow9886 Now current version looks like:
![default](https://cloud.githubusercontent.com/assets/6104200/26468897/c22c678e-41a0-11e7-8273-86cb688aff29.png)

**Comment by worm333** [comment]
I've replaced: `s:validateAll`, `s:validate`, `s:validateEquality`, `s:graphicsImage`, `s:message` and `s:button` tags with similar tags from jsf as it recommended [here](https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Web_Framework_Kit/2.7/html/Seam_Guide/_seam_2_ui_controls_migration_to_jsf.html)

For `s:validityEquality` I created  custom validator [EqualsValidator](https://github.com/GluuFederation/oxTrust/pull/570/commits/302da345385bc2e33af49de5b97036d249f20644#diff-c3c7bd9914704be5be8e35aba6e35192)


`s:defaultAction` just removed without replacement.

`s:fileUpload` - still should be replaced ( probably with [rich:fileUpload](https://docs.jboss.org/richfaces/latest_3_3_X/en/devguide/html/rich_fileUpload.html))

**Comment by worm333** [comment]
Here is some bugs I've noticed:

- `configuration/update` page could not be updated
- `attribute/inventory` attributes doesn't shows. Clicking to `Shows All Attributes` leads to the following exception: `javax.faces.FacesException: #{attributeInventoryAction.toggleShowInactive}: java.lang.NullPointerException`
- accessing `/organization/cacherefresh` page leads to the following error:`SEVERE: JSF1006: Cannot instantiate converter of type newLineToBRConverter`
- `/logviewer/configure` can not add new template
- accessing `/logviewer/view` page leads to the following error: `javax.el.ELException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-5745345510060453610.dir/webapp/logviewer/viewLogFile.xhtml @110,92 value="#{viewLogFileAction.getTailOfLogFile()}": java.lang.NullPointerException`

**Comment by yurem** [comment]
@worm333 thanks you for update
I've opened separate issue regarding fileUpload control: https://github.com/GluuFederation/oxTrust/issues/571

**Comment by yurem** [comment]
@worm333 
Please update bugs list. I've fixed few of them. The second part I can't reproduce. Maybe someone fixed them already

**Comment by yurem** [comment]
Done, for all other migration issues we need to open separate issue
