### ISSUE TITLE
Multivalued attribute administration missing workflow

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#572]
Multivalued attributes should present itself 'twice' at least in oxTrust. However here is what happening: 

 - A multivalued attribute is declared
 - Selected an user
 - Grabbed this multi valued attributes, populated this for this user
 - Then there is no second attribute available in oxTrust for inserting second values

Here is this video, showing how a multi valued attributes is behaving when Gluu Server administrator is trying to use oxTrust for some specific user: https://youtu.be/YJgfe8_qi_Y

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/27720269-45e35088-5d76-11e7-9e2a-a9fac4e3bdb3.png)

**Comment by willow9886** [comment]
@shekhar16 the blue x , + , - icons don't look right... is that intended design?
