### ISSUE TITLE
UMA 2 Scopes : Adapt oxTrust code according to scopes changes in oxAuth

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#573]
Now oxAuth support plain UMA scopes, following changes are made that must be reflected on UI:
1) removed oxUrl and oxType attributes (no type anymore for scope)
2) oxId keeps plain scope name (e.g view, edit, delete) or full scope url (e.g. http://rs.com/scopes/edit).

Please check commits attached to issue for more details here:
https://github.com/GluuFederation/oxAuth/issues/536

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/27019534-e5899eb8-4f56-11e7-953e-62dfda0ac6fd.png)

**Comment by yuriyz** [comment]
@shekhar16 can you paste screenshot of how "Add UMA scope" dialog looks ?

**Comment by yuriyz** [comment]
@shekhar16 I don't see any commits where you changed UI.

**Comment by yuriyz** [comment]
ah, it's done as part of other issues, closing for now.
