### ISSUE TITLE
Pass relyingPartyId from IDP to oxAuth in authorization request

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#575]
In 2.4.4 sp4 we implemented this already. These are only 2 lines:
https://github.com/GluuFederation/oxTrust/commit/00d18d62fcf8963f7f91938e5b493da8c4ddf469#diff-d009f1d80def1ca9109c86a33fb7c86dR136

How to implement this in 3.1.x?
@qbert2k how we can pass custom authorization paramer/header in 3.1.x which we can get from custom script?
@dmogn what we can use instead of line above with IDP3?
```
String relyingPartyId = edu.internet2.middleware.shibboleth.idp.util.HttpServletHelper.getLoginContext(request).getRelyingPartyId();
```

**Comment by nynymike** [comment]
What is the impact of this bug?

**Comment by yurem** [comment]
I updated saml authentication filter. Now it uses JWT state to send additional data in authorization request.
https://github.com/GluuFederation/oxTrust/commit/36578b97f4bb9786e3ff314057221bc540054adf

Now, we only need to find replacement of this IDP2 line:
https://github.com/GluuFederation/oxTrust/commit/00d18d62fcf8963f7f91938e5b493da8c4ddf469#diff-d009f1d80def1ca9109c86a33fb7c86dR136

**Comment by yurem** [comment]
@nynymike During building oxTrust we build 3 libraries: openid-auth-client, saml-openid-auth-client,  	cas-openid-auth-client These are libs which we include in our custom IDP build, etc..

Initially we added these libs to oxAuth but later moved to oxTrust. I think instead of moving them to oxAuth again we can move them to separate project

**Comment by dmogn** [comment]
Done.

**Comment by yurem** [comment]
Right now according to the @dmogn it requires that oxAuth should rreturn conversation_id in redirect.
oxAuth don't forward inbound custom parameters back.
Can we instead of:
```
final String key = ExternalAuthentication.startExternalAuthentication(request);
```
write:
```
final String key = request.getParameter(ExternalAuthentication.ONVERSATION_KEY);
```

In this case we don't start new flow. Also oxAuth can return input parameter in header if this will help.

**Comment by nynymike** [comment]
why is this an oxTrust issue?

**Comment by willow9886** [comment]
From Yura earlier in the thread:

> @nynymike During building oxTrust we build 3 libraries: openid-auth-client, saml-openid-auth-client, cas-openid-auth-client These are libs which we include in our custom IDP build, etc..

> Initially we added these libs to oxAuth but later moved to oxTrust. I think instead of moving them to oxAuth again we can move them to separate project

**Comment by dmogn** [comment]
@yurem - fixed https://github.com/GluuFederation/oxTrust/blob/master/saml-openid-auth-client/src/main/java/org/gluu/oxauth/client/authentication/AuthenticationFilter.java#L164

**Comment by dmogn** [comment]
@yurem - fixed https://github.com/GluuFederation/oxTrust/blob/master/saml-openid-auth-client/src/main/java/org/gluu/oxauth/client/authentication/AuthenticationFilter.java#L164
