### ISSUE TITLE
Deprecate or review native2ascii script usage

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#578]
In our oxtrust/oxauth server pom.xml there is dependency on
```
<executable>${basedir}/src/main/resources/scripts/native2ascii.sh</executable>
```

This script for Linux only. As result on Windows we have to comment out this line.
Are we really need to convert our resource files? Can we do this on runtime?

If it's not possible we need to add Windows version of script too.

**Comment by worm333** [comment]
In fact `native2ascii` we only need in production builds. Basically `resources/scripts/native2ascii.sh` is looping through all `messages*.properties` files and converts specific characters in ASCII, using Unicode escapes (\uxxxx) notation. 

So I've created new profile `native2ascii` which will be activated only in unix-like systems, take a look at these pull requests: #579 and [#560](https://github.com/GluuFederation/oxAuth/pull/560).
