### ISSUE TITLE
Fix UMA scope validation logic for id

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#582]
![image](https://user-images.githubusercontent.com/3717101/27004900-d39d6bec-4dd7-11e7-9dab-cc9f081739c9.png)

1. The id does not need to be alphanumeric (in fact URLs are the standard), and the limit for URL length is 2083 characters
2. Scopes can have a description according to UMA [3.1.1](https://docs.kantarainitiative.org/uma/ed/oauth-uma-federated-authz-2.0-04.html#scope-desc)

**Comment by yuriyz** [comment]
related to https://github.com/GluuFederation/oxTrust/issues/573
