### ISSUE TITLE
Remove scope type from table view

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#583]
![image](https://user-images.githubusercontent.com/3717101/27004935-9fb1ba8a-4dd8-11e7-9dd1-4aa3f6bd5684.png)

We have removed scope type from the form, it should also be removed from the table view.

**Comment by yuriyz** [comment]
related to https://github.com/GluuFederation/oxTrust/issues/573

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/27019529-e02944d2-4f56-11e7-9ca4-9dc882c4a1ad.png)
