### ISSUE TITLE
Post-logout redirect uri list is named incorrectly

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#587]
Environment: Gluu CE 3.x

Please see picture below:
![logout-redir-url](https://user-images.githubusercontent.com/11802046/27050968-12bb369c-4fbd-11e7-876d-55b327c44a94.png)

The correct name of this list is "Post Logout Redirect URIs". Note that name of the corresponding button on the page is correct, seems like this list was just missed last time naming issues were attended there.

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/27090535-1247c220-507b-11e7-8187-6ba887e9d8f9.png)
