### ISSUE TITLE
UMA 2 : Introduce new "UMA Claims Gathering Script"

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#590]
1. Introduce new "UMA Claims Gathering Script". In Configuration -> Manage Custom Scripts there should be new tab called "UMA Claims Gathering Script". Key for new script type should be `uma_claims_gathering`.
See: https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/custom/script/CustomScriptType.java#L49-49

Make sure "Priority" is present for "UMA Claims Gathering Script" 
(we will use "level" for it org.xdi.model.custom.script.model.CustomScript#level)

2. Rename name "UMA Authorization Policies" to "UMA RPT Policy".
Note: key is renamed too, `uma_authorization_policy` -> `uma_rpt_policy`.

Changed in oxCore made here
https://github.com/GluuFederation/oxCore/commit/d70859a1ba9ab62814e91236664b80e42ab404b8

**Comment by yuriyz** [comment]
cc : @nynymike

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/27255394-64f1a2aa-53bb-11e7-8417-e47a01c80947.png)

**Comment by shekhar16** [comment]
@yuriyz please add the script configuration for UMA Claims Gathering Script in scrpt.ldif file

**Comment by yuriyz** [comment]
@shekhar16 added https://github.com/GluuFederation/community-edition-setup/commit/bde124668280930f16884df86c695118e07bbd0d

**Comment by shekhar16** [comment]
Thanks :+1:

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/27258180-83b599ac-5411-11e7-899b-6cb0148d7aa9.png)

**Comment by yuriyz** [comment]
@shekhar16 minor thing, please rename label "Level" -> "Priority". Otherwise look good.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/27298409-1b978700-5546-11e7-91c9-62fadbcb76dc.png)
