### ISSUE TITLE
Several JSF-related exceptions in 3.1.0 blocks usage

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#591]
When building master branch from source and then running, some runtime errors arise and hinder the usage of oxtrust itself. The following describes the situation:

*Last cloned of repositories*: Jun 16th at 00:00 UTC
*IDE used*: IntelliJ 2017.1.2
*oxauth version used*: 3.1.0-SNAPSHOT (built from source also)
*app server*: Jetty using different ports under HTTPS. Versions tried: 9.4.2.v20170220, 9.4.4.v20170414
*deployment strategy*: generating war with IDE and then manual deploy, and also via maven with jetty:run inside IDE
*log levels*: TRACE (both apps)

When starting oxAuth and oxTrust, no errors in logs. Configuration from files and LDAP is picked properly.

When hitting  `https://localhost:8453/identity/` it redirects to `https://localhost:8443/oxauth/login` as expected, but underneath, the following exception appears in oxtrust log (see attachment):

[in_login.txt](https://github.com/GluuFederation/oxTrust/files/1081450/in_login.txt)

The first one is a security warning (by inspecting the code I consider it as normal - no user is logged in). The second warning is about an already commited response. The third is an error related to a redirection that could not be made. 

After authenticating using **admin**, the dashboard is shown normally...

When clicking on any **main** menu item (e.g. custom scripts, manage people, etc.) I can see the HTML forms, but any further click redirects me to the Oops page `https://localhost:8453/identity/error`

Behind the scenes, the following is shown in oxtrust log. This relates to a JSF problem (see attachment):

[after_second_click.txt](https://github.com/GluuFederation/oxTrust/files/1081451/after_second_click.txt)

If one tries to visit again `https://localhost:8453/identity/` you still have your session but cannot go further than two clicks. For instance, one cannot see a tab in the custom scripts section other than the first one.

**Comment by nynymike** [comment]
Shekhar and Yura... any ideas what could be going on here? Is this something specific to IntelliJ? Does this behavior exist with Eclipse?

**Comment by jgomer2001** [comment]
@yurem @shekhar16 
**Also important** 
Apparently SCIM service is not being "activated": by modifying entries directly in LDAP to enable SCIM and UMA custom script, if one enters to a URL similar to `https://localhost:8453/identity/seam/resource/restv1/scim/v2/Schemas/` a 404 HTTP error (not found) is returned by Jetty

**Comment by nynymike** [comment]
Not sure what you mean by activated, but there is a config setting to enable SCIM. 

![image](https://user-images.githubusercontent.com/3717101/27248501-fdf27b66-52c9-11e7-858f-3fcc6c6d0f24.png)

![image](https://user-images.githubusercontent.com/3717101/27248516-3edff414-52ca-11e7-9b75-5fc42faa5dea.png)

**Comment by nynymike** [comment]
![image](https://user-images.githubusercontent.com/3717101/27248526-59081614-52ca-11e7-9fca-bb31265bb292.png)

**Comment by nynymike** [comment]
![image](https://user-images.githubusercontent.com/3717101/27248532-681a9532-52ca-11e7-9712-de6c14702383.png)

**Comment by nynymike** [comment]
![image](https://user-images.githubusercontent.com/3717101/27248538-7f67dd94-52ca-11e7-8c69-cf7257b78d93.png)

**Comment by jgomer2001** [comment]
You are right, that wasn't clear. I edited...

**Comment by yurem** [comment]
@jgomer2001 I think you get redirects in loop and exceptions because your oxAuth instance not up or oxTrust is unable to get access token.
I've added negative navigation rules:
https://github.com/GluuFederation/oxTrust/commit/8f29124924c70ee27fc72a36d0827fdf35d93bba

I this issue there are other questions too. Can you tell if other issues still have place?

**Comment by yurem** [comment]
Remove second redirect in pre-authentication phase: https://github.com/GluuFederation/oxTrust/commit/f90eca1bfe799515c4266b91a228194ed69ce0ab

**Comment by jgomer2001** [comment]
@yura
I think you overlooked some details in my issue. If oxAuth weren't up and running I wouldn't be able to login... and of course it's getting the access token: I can login! ; local oxAuth is well behaved - not even an error in that log.

I cloned master branch once more but am getting the same exact behaviour.

Also, I mentioned the SCIM problem here because I tought it could give some additional clues to solve the issue.

The idea of @nynymike is not bad. I will find the time to try with eclipse. Maybe cleaning the maven-repo is of use also

**Comment by jgomer2001** [comment]
Last week commits on this project have improved considerably my local oxTrust behavior
Curiously I ended up achieving better results in a CLI only environment...
