### ISSUE TITLE
UMA 2 : added "claims_redirect_uris" to client.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#593]
https://github.com/GluuFederation/oxAuth/issues/569

Look at oxauth issue above, there is new 'claims_redirect_uris' parameter added to client object (Dynamic Registration is updated). Please add parameter on UI.

`oxClaimRedirectURI` added to `oxAuthClient` OC.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/27259715-0fb84f1a-5437-11e7-8dea-b4571f70d6f6.png)

**Comment by yuriyz** [comment]
looks good

**Comment by shekhar16** [comment]
Fixed.
