### ISSUE TITLE
Password Reminder page is not working.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#595]
Enter valid email address and then click on "Send Email" button.
getting Error page.
Getting below exception.:
javax.faces.FacesException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.String'. Check configuration for 'email'

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/27490047-7895ea66-585a-11e7-8d77-d5e76350829a.png)

**Comment by willow9886** [comment]
@shekhar16 can you put a space in between `using` and `GLUU`. ?
