### ISSUE TITLE
Newly created users has admin rights.

### ISSUE THREAD

**Issue by worm333** [GluuFederation/oxTrust#598]
Steps to reproduce:

1. Go to `/identity/person/add` and create new user.
2. Logout from oxTrust and log in with credentials of newly created user.

As a result new user will have admin rights.

**Comment by willow9886** [comment]
I am unable to replicate this on CE 3.0.2.

I registered a new user.

Logged in as the user and am only able to see my personal > profile. 

![image](https://user-images.githubusercontent.com/5271048/27548132-a329a470-5a5d-11e7-97fe-85b5b112c340.png)

**Comment by worm333** [comment]
This behavior happens in the latest versions of oxTrust. Here is the information about my environment where I was able to reproduce it:

- oxAuth revision number: `a670dc8065600e8dd4174ddcb1bb5fb7927aa87f`
- oxTrust revision number: `5f8302d423dc17d740f46ec371e536a643846202`
- Gluu server: [gluu-server-3.0.1_1-5~trusty+Ub14.04_amd64.deb](https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.0.1_1-5~trusty+Ub14.04_amd64.deb)

**Comment by yurem** [comment]
I can't reproduce it in [3.0.2](https://repo.gluu.org/ubuntu/pool/main/trusty/gluu-server-3.0.2_9-1~trusty+Ub14.04_amd64.deb)

Do you have any scripts enabled which can add memberOf attribute to add user to admin group.

Can you try again and export this user and admin group entries?

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxCore/commit/0e5b3b335eae2d4455f1c3c4ab2b714745afc4dc
