### ISSUE TITLE
Configuration JSON editor should not use hardcoded oxauth config DN

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#60]
Currently JSON configuration editor uses next method to determine oxauth config DN:
it gets oxtrust config DN from oxTrustLdap.properties and replace oxtrust with oxauth.

I think JSON editor should allow to specify DN of configuration entries in LDAP in similar to Log viewer way.

oxJsonConfig: {"json_ldap_dn":[{"value1":"oxAuth dynamic configuration","value2":"ou=oxauth,ou=configuration,inum=@!1111!0002!4907,ou=appliances,o=gluu","description":""},{"value1":"oxTrust configuration","value2":"ou=oxtrust,ou=configuration,inum=@!1111!0002!4907,ou=appliances,o=gluu","description":""}]}

**Comment by willow9886** [comment]
@yurem is this issue still outstanding?

**Comment by yurem** [comment]
I opened it after code review. I found line: https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/ldap/service/JsonConfigurationService.java#L127

But DN of LDAP configuration is the static now. Hence we are not going to move oxauth configuration to other place...

I offer to move this issue to 2.6.0 version or close at all.
