### ISSUE TITLE
personal info on users page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#603]
We display an `x` next to each item in the user profile page, but the x is overlapping the persons data. Let's implement a better design for this so that the `x` doesn't overlap the info.

![image](https://user-images.githubusercontent.com/5271048/27748834-91b4042e-5d96-11e7-9d65-f26c79af1e72.png)

**Comment by shekhar16** [comment]
Here is the option i tried.

![image](https://user-images.githubusercontent.com/15937500/27771452-1ef622e6-5f6c-11e7-9696-03de06465bdd.png)

**Comment by shekhar16** [comment]
Is it ok ?

**Comment by willow9886** [comment]
@shekhar16 yes, looks better.

**Comment by shekhar16** [comment]
Can we close this issue?
