### ISSUE TITLE
show u2f creds in user page

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#604]
We should show a users u2f creds in the manage people page. 

![image](https://user-images.githubusercontent.com/5271048/27748998-3d8bdb82-5d97-11e7-9405-4d14745cade8.png)

Other creds, like mobile number and OTP are stored as user claims. Since they are seperate LDAP entries under the person entry, they would have to be listed in a subsection.

**Comment by shekhar16** [comment]
I couldn't see these attribute (like mobile number and OTP) in ldap. Can u please help to locate these attributes.so that i can fix this issue.

**Comment by shekhar16** [comment]
@nynymike @yurem Can u please help me to add these fields in user attribute tab as these are not in attribute list.

**Comment by shekhar16** [comment]
The fields like oxexternalid (otp etc) ,fido variables I think these are runtime variables,not registration variable. the values for these entries save by system at the time of processes.We cant save them at the time of add user or user registration.
Please advice.

**Comment by yurem** [comment]
We need to display list of 2F authenticated methods which user enable.

In order to prepare this list we need to do:
1. Load user entry with 'oxExternalUid' attributes
2. Convert
oxExternalUid: saml:%s
oxExternalUid: duo:%s
...
to
Saml
Duo
...

3. Load user sub-entries from ou=fido,inum=@!E06D.5F6A.990D.DE94!0001!B78E.5EFA!0000!3FD0.6966.AC43.EEA0,ou=people,o=@!E06D.5F6A.990D.DE94!0001!B78E.5EFA,o=gluu
4. Add Super Gluu method loaded in step 3 to list of 2F methods.


Also this list should has button to remove selected authentication method.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/32958759-77b99602-cbe5-11e7-9161-cf859b670bb5.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/pull/764/commits/dc04fc9aa28e3e3caf63130f03bb5518ce134883

**Comment by mzico** [comment]
@shekhar16 : I see something like below, U2f is in authentication method and this user ( mohib@gluu.org ) has u2f devices. 
![screenshot_2](https://user-images.githubusercontent.com/7156097/34598578-42082a48-f1b3-11e7-8826-2f7102e10ffc.png)

**Comment by shekhar16** [comment]
@mzico  please share the user ldap record.

**Comment by mzico** [comment]
@shekhar16 : 

```
dn: inum=@!4B9A.45BE.1105.F0BE!0001!8C52.84C8!0000!4AE1.614D.D91F.B2FB,ou=people,o=@!4B9A.45BE.1105.F0BE!0001!8C52.84C8,o=gluu
oxCreationTimestamp: 20180105064818.099Z
uid: mohib
givenName: Mohib
displayName: Zico
sn: Zico
mail: mohib@gluu.org
gluuStatus: active
oxTrustEmail: {"operation":null,"value":"mohib@gluu.org","display":"mohib@gluu.org","primary":true,"reference":null,"type":"other"}
inum: @!4B9A.45BE.1105.F0BE!0001!8C52.84C8!0000!4AE1.614D.D91F.B2FB
iname: *person*mohib
userPassword:: xxxx.....
cn: Mohib Zico
objectClass: top
objectClass: gluuPerson
objectClass: gluuCustomPerson
oxLastLogonTime: 20180105065119.859Z
```

oxTrust version: 

```

GLUU.root@test:/opt/opendj/logs# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-558512455259960531.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.2.Final
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 191918d3a969d0ffb8ee99178e5ed7cd545b1323
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121

```

**Comment by nynymike** [comment]
No values should prevent display of the labels for "Authentication Methods" (do you mean the main preference of this user? Wouldn't this be an ordered array of methods?) and "Super Gluu Devices" (do you mean U2F devices?) . Overall, I'm really confused by the interface here... it's cryptic.

**Comment by shekhar16** [comment]
@mzico  as per your above record there is no oxexternalUid it means there is no Authenitcation methods present for this user.
Please share records of the fido  values for same user.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/34623542-cbc4a300-f277-11e7-8780-1e874575fe34.png)

**Comment by willow9886** [comment]
@shekhar16 this doesnt make sense... what we are trying to show in the user profile is which devices the user has registered.

What you are calling the "authentication method" is only relevant when considering the registered devices. That means, just saying which methods a user can use is not important. 

The way this should be handled is best illustrated in a hypothetical example:

Let's say a user, Will, has registered and nicknamed the following 2FA devices: 

two U2F keys, one SMS phone number, two OTP mobile apps, and one Super Gluu device. 

In the user profile, it should list the following:

U2F: `blue yubikey` , `black yubikey` 
Super Gluu device(s): `Will's Samsung Galaxy S7`
OTP mobile apps: `Will's Google authenticator` , `Will's authenticator`
SMS phone: `+ 1 925.389.8427` 

Please confirm that you understand this.

**Comment by yurem** [comment]
I understand the issue. Both data for U2F and Super-Gluu (because it's based on U2F) we store in same place.

Here is sample data in LDAP:
```
dn: inum=@!38D4.410C.1D43.8932!0001!37F2.B744!0000!593C.048C.3D78.9E91,ou=pe
 ople,o=@!38D4.410C.1D43.8932!0001!37F2.B744,o=gluu
objectClass: gluuPerson
objectClass: top
uid: xyz

dn: ou=fido,inum=@!38D4.410C.1D43.8932!0001!37F2.B744!0000!593C.048C.3D78.9E
 91,ou=people,o=@!38D4.410C.1D43.8932!0001!37F2.B744,o=gluu
objectClass: organizationalUnit
objectClass: top
ou: fido

dn: oxId=1508521337148,ou=fido,inum=@!38D4.410C.1D43.8932!0001!37F2.B744!000
 0!593C.048C.3D78.9E91,ou=people,o=@!38D4.410C.1D43.8932!0001!37F2.B744,o=gl
 uu
objectClass: oxDeviceRegistration
objectClass: top
creationDate: 20171020174217.146Z
oxApplication: https://ce-dev4.gluu.org/identity/authentication/authcode
oxCounter: -1
oxDeviceData: {"uuid":"1234...","type":"normal"
 ,"platform":"android","name":"SM-G930F","os_name":"n","os_version":"7.0","p
 ush_token":"1234..."}
oxDeviceHashCode: -7735
oxDeviceKeyHandle: 1234...
oxDeviceRegistrationConf: {"publicKey":"1234..."}
oxId: 1508521337148
oxStatus: active

dn: oxId=1515179523154,ou=fido,inum=@!38D4.410C.1D43.8932!0001!37F2.B744!000
 0!593C.048C.3D78.9E91,ou=people,o=@!38D4.410C.1D43.8932!0001!37F2.B744,o=gl
 uu
objectClass: oxDeviceRegistration
objectClass: top
creationDate: 20180105191203.153Z
oxApplication: https://ce-dev4.gluu.org
oxCounter: -1
oxDeviceHashCode: 356
oxDeviceKeyHandle: 12345...
oxDeviceRegistrationConf: {"publicKey":"12345..."}
oxId: 1515179523154
oxStatus: active
```

As result we have 3 groups:
1. Super Gluu
2. U2F
3. Other methdos

We can try to combine all these methods in one list

**Comment by yurem** [comment]
In ldif first record is Super-Gluu device, second record is U2F device

**Comment by willow9886** [comment]
@yurem see my comment above.. 

Ideally, in the user page, it looks like this:

U2F: blue yubikey , black yubikey
Super Gluu device(s): Will's Samsung Galaxy S7
OTP mobile apps: Will's Google authenticator , Will's authenticator
SMS phone: + 1 925-333-8333

**Comment by yurem** [comment]
@willow9886 yes, I'm ok with this. I provided sample data for @shekhar16

**Comment by willow9886** [comment]
Perfect!

**Comment by nynymike** [comment]
Aren't we using mobile phone number for SMS? I think we already have that in the form, or it can be added there...

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/34685035-0ba11a2e-f4cd-11e7-958d-c36fc9a63dc0.png)

**Comment by shekhar16** [comment]
The data is dummy,So please don't get confused on that.

**Comment by willow9886** [comment]
@shekhar16 This section of the interface needs to be titled:

U2F Credentials:

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/34685946-fd0c3cc0-f4cf-11e7-875d-a54ceacc3e4b.png)

**Comment by willow9886** [comment]
yes, looks better.
