### ISSUE TITLE
Issues with password reset feature

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#607]
Environment:
Ubuntu 14.04, gluu-server-3.0.2-9-1

Preconditions:
1. Mail server is configured at "Configuration -> Org. Configuration -> SMTP server configuration" and confirmed to be functioning (due to [other issue](https://github.com/GluuFederation/oxTrust/issues/608) this feature may be quite picky about SMTP server it wants to work with)
2. "Self-Service Password Reset" feature is enabled
3. A test active non-admin user with a meaningful (non-bogus) email address in "Email" attribute  exists in the system. SMTP server configured for this instance must be able to send emails to this user's mailbox.

Steps to reproduce:
1. Log out from web UI if you are logged in
2. Proceed to url like `https://your.gluu.host/identity/person/passwordReminder.htm` and submit email of the test user there
3. Check email box and follow url with confirmation code it contains.

Result:

A letter containing url similar to `'https://your.gluu.host/identity/resetPassword/XXXXXXXXXX` (where "XXXXXXXXXX" is confirmation code of sort) is delivered to specified email. But following this url produces nothing and user arrives to the regular oxAuth's login page. A Java exception is registered in `oxtrust.log` (here is [full text](https://github.com/GluuFederation/oxTrust/files/1129023/reset_pass_excpt.txt) of it):
```
2017-07-06 19:07:44,724 ERROR [qtp274064559-10] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: null
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]```
```
Searching internal LDAP with line like this `/opt/opendj/bin/ldapsearch -h 127.0.0.1 -p 1636 -s sub -T -Z -X -D 'cn=directory manager,o=gluu' -j /tmp/.pw -b 'ou=resetPasswordRequests,inum=@!80E9.CD48.2755.A503!0002!8B7D.8FA4,ou=appliances,o=gluu' -z 5 '&(oxguid=5v1o1c5cct!zunf8)'` where "5v1o1c5cct!zunf8"  is confirmation code from the letter yields next:
```                      
dn: oxGuid=5v1o1c5cct!zunf8,ou=resetPasswordRequests,inum=@!80E9.CD48.2755.A503!0002!8B7D.8FA4,ou=appliances,o=gluu
creationDate: 20170706190710.986Z
oxGuid: 5v1o1c5cct!zunf8
personInum: @!80E9.CD48.2755.A503!0001!A098.8C39!0000!DB9D.37B5.A72D.03BE
objectClass: top
objectClass: gluuPasswordResetRequest
```

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

We also probably have some issue with mark up in the letter's template, as it's presented in the mail client as a source code of html file (it's not rendered), thought it looks like it should:

![selection_072](https://user-images.githubusercontent.com/11802046/27929827-2d0806ae-629d-11e7-98dc-7a04957b207d.jpg)

Source is below:

```
From - Thu Jul  6 22:45:49 2017
X-Account-Key: account5
X-UIDL: 00000001595e936d
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Return-Path: <gluu-user@sphost.site>
X-Original-To: gluu-user@sphost.site
Delivered-To: gluu-user@sphost.site
Received: from ce3ubnt14.host.loc (mygluu3.host.loc [192.168.238.154])
	by smtp.sphost.site (Postfix) with ESMTPA id 92AB41CD3487
	for <gluu-user@sphost.site>; Thu,  6 Jul 2017 15:24:51 -0400 (EDT)
Date: Thu, 6 Jul 2017 19:24:51 +0000 (UTC)
From: Alex <gluu-user@sphost.site>
To: gluu-user@sphost.site
Message-ID: <866114913.4.1499369091489.JavaMail.gluu-user@sphost.site>
Subject: Password reset was requested at Home identity server
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Hello test

We received a request to reset your password. You may click the button below to choose your new password.
If you did not make this request, you can safely ignore this message. 

<a href='https://ce3ubnt14.host.loc/identity/resetPassword/h7hi2za7mn139ui8'> <button>Reset Password</button></a>

```

**Comment by shekhar16** [comment]
@aliaksander-samuseu  Have u tried it with latest build? As u mentioned version 3.0.2.
Please try with latest build.

**Comment by yurem** [comment]
@aliaksander-samuseu can your check it in 3.1.0: http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.0-SNAPSHOT/oxtrust-server-3.1.0-SNAPSHOT.war ? Please reopen it if bug still exists.

**Comment by mpaone** [comment]
@aliaksander-samuseu I've been experiencing the same issue with 3.0.2.  Do you know if this was fixed in a newer version?  If you cannot confirm, I will be trying a later version as soon as I get time.
