### ISSUE TITLE
Issues with SMTP server configuration

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#608]
Environment:
Ubuntu 14.04, gluu-server-3.0.2-9-1

Preconditions:
1. You have account at webmail.gluu.org

Steps to reproduce:
1. Log in to web UI as admin
2. Proceed to "Configuration -> Org. Configuration -> SMTP server configuration"
3. Configure it using settings like this:
  - SMTP host: webmail.gluu.org
  - From Name: any
  - From Email Address: your email address
  - Requires Authentication: set
  - SMTP User Name: your email address
  - SMTP Password: your pass
  - Requires SSL: set
  - SMTP Port: 465
4. Click "Update"
5. Click "Test configuration"

Result:
No response from Gluu server in reasonable time. In `oxtrust.log` next trace appears ([full text](https://github.com/GluuFederation/oxTrust/files/1129123/smtp-server-feature-erro.txt)):
```
2017-07-06 20:05:31,467 ERROR [qtp274064559-19] [org.gluu.oxtrust.action.UpdateOrganizationAction] (UpdateOrganizationAction.java:233) - SMTP Host Connection Error
javax.mail.MessagingException: Could not connect to SMTP host: webmail.gluu.org, port: 465, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1949) ~[javax.mail.glassfish-1.4.1.v201005082020.jar:?]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654) ~[javax.mail.glassfish-1.4.1.v201005082020.jar:?]
	at javax.mail.Service.connect(Service.java:310) ~[javax.mail.glassfish-1.4.1.v201005082020.jar:?]
```

This configuration is just an example, but the fact it fails to use it most likely signify some bugs in the feature. I can use the same config in my Thunderbird email client without issues. I can reach webmail.gluu.org:465 from inside my container. I was also able to setup a very simple "Postfix+Dovecot" bundle locally and managed to configure Gluu to work with it, so it's not completely broken.

Expected result:
A letter notifying that test was successful is delivered to email box used in configurations.

**Comment by shekhar16** [comment]
@aliaksander-samuseu  it seam like there isconnection isuue with smtp server.

**Comment by bluebaroncanada** [comment]
This may be related to an issue I'm also experiencing where there is no certificate trust.
I resolved this issue locally by adding `props.put("mail.smtp.ssl.trust", this.hostName);`  to line 75 of `MainUtils.java`
This is an urgent issue that is fatal to execution.   I will file another issue in case they aren't actually related.

**Comment by bluebaroncanada** [comment]
May be related to https://github.com/GluuFederation/oxTrust/issues/627
Urgent

**Comment by worm333** [comment]
Fixed in [this commit](https://github.com/GluuFederation/oxTrust/commit/07ce59a40bfe63f37e0d36ff7aa01b736e6e72e3).
