### ISSUE TITLE
Load configuration from LDAP before editing in JSON editor

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#61]
Current implementation of JSON configuration editor load configuration from LDAP at startup only.
In future we are planning to do oxAuth/oxTrust configuration reload on the fly without server restart.
Hence JSON editor should load actual configuration from LDAP before allows admin to edit it.

**Comment by rahatjaan** [comment]
fixing it now

**Comment by rahatjaan** [comment]
fixed and committed to master branch because it is very small fix so no need to create a separate branch.
