### ISSUE TITLE
Move captcha site key and site secret to manage registration page

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#612]
![captcha](https://user-images.githubusercontent.com/7703245/28099593-46aa3870-66df-11e7-956b-32a7d6d75dc9.png)
These fields are from oxTrust JSON Configuration. Moving them to the manage register page will make enabling captcha easier.

**Comment by shekhar16** [comment]
@zamilskhan  This is a part of oxtrust configuration json which is displayed by json editor js library .

**Comment by zamilskhan** [comment]
@shekhar16 is there any way we can put the input in the manage registration page so that when these 2 fields are put there, they will be filled up in the oxtrust config json?

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/28498855-7b51cfe0-6fc5-11e7-88a3-db3d0e9b6002.png)
