### ISSUE TITLE
JSF 2.2 and navigation.xml review after page.xml convertion

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#613]
- Remove from xhtml if there is sumalar annotation in action class.
Example
<f:metadata>
remove if="#{permissionService.hasPermission('trust', 'access')
remove identity.checkLoggedIn()
because @Secure("#{permissionService.hasPermission('trust', 'access')}")

- Use JSF 2.2.way to set request parameters
Repalce
<f:metadata>
<f:viewAction action="#{updateAsimbaIDPAction.setEditEntryInum(param['inum'])}"/>
</f:metadata>
with
<f:metadata>
<f:viewParam name="inum" value="#{updateAsimbaIDPAction.editEntryInum}" />
</f:metadata>

- There is no end conversation tag in JSF 2.2 navigation rules
We need to call next method from code:
@Inject private ConversationService conversationService;
conversationService.endConversation();
Places to call it we need to tkae from page.xml

- There is no tag to add message in JSF 2.2. We also need to check page.xml and call from code methods to add messages:
@Inject
FacesMessages facesMessages;
facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to load custom scripts");

**Comment by dmogn** [comment]
related with https://github.com/GluuFederation/oxTrust/issues/611

**Comment by yurem** [comment]
Updated all pages
