### ISSUE TITLE
SAML TR unable to add attributes

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#619]
Package: gluu-server-3.1.0.x86_64 1-1.BETA3.centos6
oxTrust Implementation-Build	: `a92af0ad7378a8bf8ef3ef5c807a5d76414a15bc`

Unable to add attributes while creating a new TR, and new TR is not created
![create-tr-error](https://user-images.githubusercontent.com/7703245/28253261-9055f350-6ac3-11e7-882b-d6743e56ef93.png)

**Comment by shekhar16** [comment]
@zamilskhan  please test it with latest build. its working for me with latest code.

**Comment by rajnikantsh** [comment]
@zamilskhan can you please test it with latest code because as per @shekhar16 its working with latest code

**Comment by nynymike** [comment]
Closing issue. If it's still a bug, please re-open.
