### ISSUE TITLE
Custom nameid functionality requires update

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#620]
Current AttributeResolverAction do work in hack way. It reads the template, process it and overwrite IDP file.
Another IDP configuration generator do the same. As result we don't know which file in IDP now.

We need to update AttributeResolverAction to store configuration in LDAP. And IDP configuration generator should use this information when needed.

In result we should get one service which generate IDP files from templates.

**Comment by rajnikantsh** [comment]
Here is the PR for this issue

https://github.com/GluuFederation/oxTrust/pull/630
https://github.com/GluuFederation/oxCore/pull/42
https://github.com/GluuFederation/community-edition-setup/pull/318
