### ISSUE TITLE
Handle coversation timeout

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#626]
In 3.1 we uses conversation context for all forms. This is better than session scope because it allows to open few tabs to do few independent updates simultaneously. Example:
Tab 1: https://u144.gluu.info/identity/person/update/@!FE7B.148F.D760.2436!0001!A0D4.6821!0000!51BE.EDED.A372.2CA8?cid=3
Tab 2: https://u144.gluu.info/identity/person/update/@!FE7B.148F.D760.2436!0001!A0D4.6821!0000!FE57.BF9D.DF9D.0760?cid=4

The default conversation timeout is 10 minutes. After this time application cleans expired conversations. When user access to open such expired session Weld throws: 
```
javax.faces.FacesException: WELD-000321: No conversation found to restore for id XYZ
```

**Comment by yurem** [comment]
@nynymike @willow9886 How to handle this situation correctly?

We can add background JS process to web page to show user message after 9 minutes. In this dialog we can add button to update conversation. This one minute is enough to confirm that user still there.

Another simpler solution is to catch this exception and show error page with problem description.

Also we can increase conversation timeout to 30 minutes.

Do you have any ideas? Which approach is better?

**Comment by nynymike** [comment]
1. Background JS process won't run if the tab is closed. 
2. Yes, update conversation to 30 min. 
3. We should catch the error and logout the user if possible.

**Comment by yurem** [comment]
In RC3 we implemented point 2.
`
Yes, update conversation to 30 min.
`

In next build we will implement:
`
We should catch the error and logout the user if possible.
`

**Comment by yurem** [comment]
![default](https://user-images.githubusercontent.com/6104200/29365721-ab0ecbbe-82a0-11e7-9991-a846ef057e77.png)

**Comment by yurem** [comment]
Added catch of this exception and specify added message for this case
