### ISSUE TITLE
UI Revamp for OxTrust

### ISSUE THREAD

**Issue by rahatjaan** [GluuFederation/oxTrust#63]
I am instructed to create this ticket from William that we are planning for a brand new UI design using responsive HTML5 and Css3.

We will use bootstrap, responsiveness for UI design. The idea for the UI is to come up with such a UI which is responsive and can be seen on any resolution that will help.

I am writing my proposal here for the new UI

1) Don't use JSF at all for UI. I can write two pages on why not to use any server side frameworks which stores the whole component tree in the memory on server which is to be rendered in the browser. It eats tons of memory on server side and when you go to cloud then you can not imagine the number of issues you face with shared session on a session store for serialization. I just delivered a cloud product where we used JSF 2.0 and let me tell you that in the end we have pull the JSF out of our stack completely in order to manage our application flow.

2) Use pure JS front like angular JS. It is being a standard in designing the modern rich internet application. I can write lot more details on powers that angular brings in 
3) Use completely stateless services on back-end (REST services, whether user Spring MVC, Seam or Jersey). The value that service oriented architecture brings in any product is obvious and I don't need to explain them here.
4) Security is a question here, usually being a REST developer I prefer to use token based security for our stateless services the advantage is that these services can be used to develop any mobile application UI in native technologies as well as we can publish our API suit for external system to get integrated to us.

With these some of the proposals and comments I would like to hear feedback from the team on it.

**Comment by nynymike** [comment]
I like the idea, but I'm concerned about how long it would take to re-write the entire UI of the application...

**Comment by rahatjaan** [comment]
I think it will be premature for me to say anything about estimating the entire UI to a brand new technology because I don't have full sight of the product itself.

But here is another way of doing a revamp. As a first step we can just build the UI with JSF and the same technology framework and just do the HTML bootstrap way and make it responsive.

As a next step down the road as a long term plan we can start migrating from JSF to angular page by page and action classes (JSF beans to REST services service by service) 

That way we don't need to migrate everything in a single go.

For just revamping the UI and UX it should take a month I guess if I am not too optimistic but I used to be optimistic most of the time

**Comment by yurem** [comment]
We are trying to add bootstrap 3 to oxTrust using Steve Oh's instructions from this issue: http://stackoverflow.com/questions/16751933/richfaces-with-bootstrap-css

If you have any question you can speak with Oleksiy about this.

**Comment by willow9886** [comment]
Yes, Oleksiy and Andriy are working on getting boostrap added now. I think after that has been completed and merged with our main project, we can start to plan for the additional upgrades described by Rahat.

**Comment by yurem** [comment]
We should open another issue to apply other changes to GUI
