### ISSUE TITLE
Images in developer setup are too small

### ISSUE THREAD

**Issue by bluebaroncanada** [GluuFederation/oxTrust#633]
On this page https://gluu.org/docs/ce/3.0.2/developer-guide/oxtrust-eclipse/
Some images are too small to be legible.

https://gluu.org/docs/ce/3.0.2/img/developer/oxtrust/deployinjetty.png
https://gluu.org/docs/ce/3.0.2/img/developer/oxtrust/vmarguments.png
https://gluu.org/docs/ce/3.0.2/img/developer/oxtrust/jettyverchng.png
https://gluu.org/docs/ce/3.0.2/img/developer/oxtrust/configurationlistener.png

**Comment by willow9886** [comment]
Closing this issue and adding it to the docs repo:

https://github.com/GluuFederation/docs-ce-prod/issues/42
