### ISSUE TITLE
Some instructions in developer setup impossible to complete

### ISSUE THREAD

**Issue by bluebaroncanada** [GluuFederation/oxTrust#634]
1. Download Silver Edition from Symas Download

2. Create folder for custom Gluu schema: C:\Program Files (x86)\symas-openldap\etc\openldap\schema

3. Copy into custom Gluu schema folder 2 files from CE /opt/gluu-server-3.0.2/opt/gluu/schema/openldap

4. Copy C:\Program Files (x86)\symas-openldap\etc\openldap\slapd.conf.default into C:\Program Files (x86)\symas-openldap\etc\openldap\slapd.conf

5. Edit file C:\Program Files (x86)\symas-openldap\etc\openldap\slapd.conf - Uncommnet next lines:

   include      `etc/openldap/schema/ppolicy.schema`
   include      `etc/openldap/schema/cosine.schema`
   include      `etc/openldap/schema/inetorgperson.schema`
   include      `etc/openldap/schema/eduperson.schema`

slapd.conf does not exist and there are no other schema files

**Comment by bluebaroncanada** [comment]
Reinstalling openldap solved it, updating the directory names is still needed.

**Comment by bluebaroncanada** [comment]
This instruction doesn't jive with the includes beloe
2. Create folder for custom Gluu schema: C:\Program Files (x86)\symas-openldap\etc\openldap\schema

   include      `etc/openldap/gluu/gluu.schema`
   include      `etc/openldap/gluu/custom.schema`

**Comment by bluebaroncanada** [comment]
Module not listed
moduleload   unique.la

**Comment by bluebaroncanada** [comment]
Had to add the module manually.  Suggest that be added to the instructions.

**Comment by bluebaroncanada** [comment]
Had to create the directory `var/run` for the `slapd.pid` on the `slaptest.bat` step.

**Comment by bluebaroncanada** [comment]
export OPENDJ_JAVA_HOME=/opt/jre; /opt/opendj/bin/ldapsearch -h localhost -p 1636  -Z -X -w secret -D `cn=directory manager,o=gluu` -b `o=gluu` objectClass=* > gluu.ldif
backticks should be double quotes.  also, throughout, this problem exists and special characters, when copied, are not handled by the browser/os which makes it very difficult to paste

**Comment by bluebaroncanada** [comment]
What does this mean?  How do you do that?  There is a typo and the grammar is difficult to comprehend.

2. Load gluu.ldif into dev LDAP and update to conform new environemt

**Comment by bluebaroncanada** [comment]
```
3.2. Fix invalid cache setting JSON format in: inum=<appliance_inum>,ou=appliances,o=gluu. We need to remove do: - Replace IN_MEMORY with IN_MEMORY - Replace DEFAULT with DEFAULT
```
What?

**Comment by bluebaroncanada** [comment]
```
3.2. Fix invalid cache setting JSON format in: inum=<appliance_inum>,ou=appliances,o=gluu. We need to remove do: - Replace IN_MEMORY with IN_MEMORY - Replace DEFAULT with DEFAULT
```
What?

**Comment by nynymike** [comment]
We are not going to support you building a development version of oxTrust...

And by the way, we use a Gluu Server for LDAP... we never use Symas Silver.
