### ISSUE TITLE
Configure Log Viewer Error Message

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#635]
Package: gluu-server-3.1.0.x86_64 1-1.BETA4.centos6
Steps to reproduce:

1. Add new log location from configure log viewer
2. Click on update to see error message
![config-log-viewer](https://user-images.githubusercontent.com/7703245/28824529-3379794a-76e4-11e7-862a-b85dd48e03a5.png)

3. Check to see that logs have been added and accessed from oxTrust.

**Comment by rajnikantsh** [comment]
Log configurations was saved successfully but displayed message was wrong.

**Comment by jschristie** [comment]
issue still persist, meesage displayed is incorrect, i am using the latest build.

![image](https://user-images.githubusercontent.com/23150138/29279601-f6b8b58c-8135-11e7-839d-4f54821a8e65.png)

**Comment by yurem** [comment]
Please retest it in RC3. I'm getting this message when I click Update button
![default](https://user-images.githubusercontent.com/6104200/29315070-d8f73606-81c9-11e7-9be1-1bdfddf21267.png)
