### ISSUE TITLE
Can't add SAML TRs in web UI

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#639]
In latest snapshot Gluu CE 3.1 oxtrust.war provided by Yuriy for QA [here](http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.0-SNAPSHOT/oxtrust-server-3.1.0-SNAPSHOT.war) new TR cannot be added in web UI as upon selection of any "Metadata Location" option subsequent controls (like url input field or file upload control) don't appear. I'm also unable to add attributes to the "Released" list. Can't see any errors in logs. I was testing with latest Chrome.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/310

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/28938935-421a7222-78ad-11e7-9071-33929589eae7.png)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

I did select "Single SP", but further controls still didn't appear. Which oxTrust package do you use? Is it the snapshot .war I referenced?

**Comment by shekhar16** [comment]
I m using latest code 3.1.0.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

How can I test it? Is it available as a package to install, or as a .war archive?

**Comment by shekhar16** [comment]
I think you can test it with latest .war file from repo.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 
Just have tested it, it still the same

**Comment by aliaksander-samuseu** [comment]
I've installed the latest RC1 package, and the issue is not there anymore. Closing it.
