### ISSUE TITLE
Remove trust all trust manager from oxLdap

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#641]
oxLdap supports new properties:
```
ssl.trustStoreFile:
ssl.trustStorePin:
ssl.trustStoreFormat:
```

We added them in 3.1.0. I offer to not support trust all trust manager in 3.2.0

**Comment by nynymike** [comment]
I think that is overkill... I like trust all... In some cases importing server certs is overkill

**Comment by yurem** [comment]
ok, closing it. Current code supports both: cert and trust all cert modes It's up to admin to select right one.
