### ISSUE TITLE
Display Client Refresh token time to live

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#645]
A new feature in oxAuth allows specification of different refresh token expiration intervals. This needs to be displayed, and settable in the oxTrust admin UI.

See: https://github.com/GluuFederation/oxAuth/issues/603

**Comment by worm333** [comment]
Added the necessary changes in the following pull requests: [oxTrust](https://github.com/GluuFederation/oxTrust/pull/646), [oxAuth](https://github.com/GluuFederation/oxAuth/pull/605) and [community_edition_setup](https://github.com/GluuFederation/community-edition-setup/pull/320).
