### ISSUE TITLE
Display status of client in OpenID Connect Client Form

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#649]
Corresponding UI change for oxAuth https://github.com/GluuFederation/oxAuth/issues/612

**Comment by nynymike** [comment]
Reopen if necesssary per comment in https://github.com/GluuFederation/oxAuth/issues/612

**Comment by worm333** [comment]
The following pull requests are related with this issue: [719](https://github.com/GluuFederation/oxTrust/pull/719), [337](https://github.com/GluuFederation/community-edition-setup/pull/337), [643](https://github.com/GluuFederation/oxAuth/pull/643).
