### ISSUE TITLE
Error when session is idle for ~10min

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#650]
Getting this error on any action taken after session is idle for ~10mins
![image](https://user-images.githubusercontent.com/21104811/29234128-8a8e8de8-7f12-11e7-9f4d-2ab2c08a4f38.png)

![image](https://user-images.githubusercontent.com/21104811/29234311-bcc70460-7f13-11e7-87d3-534a1245df6f.png)

**Comment by dmogn** [comment]
Same with this issue: https://github.com/GluuFederation/oxTrust/issues/609

**Comment by yurem** [comment]
Duplicate. Original issue: https://github.com/GluuFederation/oxTrust/issues/626
