### ISSUE TITLE
Tab not working in add users

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#654]
while adding users in oxTrust, i use Tab to move to next field, however tab doesn't take me to next field or doesn't highlight or allow me to type the values.

users>add person

click on Username, enter value and then press tab to move to next field.

I am taken to next field or let me to type.

**Comment by yurem** [comment]
I'm moving it to 3.2.0 and mark it as enhancement. The reasons is that it's not bug and even not all standalone applications supports right tab order.
