### ISSUE TITLE
Enabling custom scripts gives error

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#655]
While trying to enable User Registration/Client Registration under Manage Custom Script gives error, however the script is enabled.

![image](https://user-images.githubusercontent.com/23150138/29278592-d981844c-8132-11e7-8fa0-23e097163a6a.png)

**Comment by yurem** [comment]
I can't reproduce it in RC3. Also please attach log messages which will give information about problematic place.
