### ISSUE TITLE
Leaving the oxTrust Admin UI idle, gives an error

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#656]
Ideally if i leave the oxTrust admin UI idle for some time, it should log me out and return me to login page, rather here i get following error and clicking on back button, i am logged in, which is not ideal.

![image](https://user-images.githubusercontent.com/23150138/29279029-3bd4164a-8134-11e7-93f8-ed9bc4aaa00f.png)

**Comment by yurem** [comment]
Same issue is here: Handle coversation timeout #626
