### ISSUE TITLE
Normal user profile issue

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#658]
profile button is not leading to profile page and also don't show navigation.
see the picture https://prnt.sc/g8rsy2

**Comment by ldeveloperl1985** [comment]
Facing same problem on ce-de3 and also on RC3 build

**Comment by rajnikantsh** [comment]
I am using latest copy of repository and everything is working on my system with latest pull. Uploading snapshot
![profile view](https://user-images.githubusercontent.com/5759657/29456173-2b369276-8432-11e7-948b-ff04153b1ba1.png)

**Comment by rajnikantsh** [comment]
Hi @ldeveloperl1985 can you please attach logs for this issue. I can't reproduce it on my local?

**Comment by ldeveloperl1985** [comment]
Hello @rajnikantsh 
Issue solved. I installed RC4 build and it works fine
