### ISSUE TITLE
After adding custom NameID with emailaddress as default, not able to add TR or view existing TR

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#674]
https://trello.com/c/QTCixOIQ/54-after-adding-custom-nameid-with-emailaddress-as-default-not-able-to-add-tr-or-view-existing-tr

**Comment by jschristie** [comment]
Steps to replicate:

1. Login to UI
2. SAML>ADD TR> select `single SP` and  "Metadata type" to `None`
3. Add
4. Click on `Add Custom ID` select `emailaddress`
5. Resolve Attribute
6. Click on TrustRelationship tab, you will be redirected to Home page with error.

**Comment by rajnikantsh** [comment]
code comitted created pull request https://github.com/GluuFederation/oxTrust/pull/687
