### ISSUE TITLE
Passport authentication displayed (but not default acr or oxTrust acr)

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#677]
I enabled the passport authentication script, and but I did not select passport as either the default acr or the oxTrust acr:

![image](https://user-images.githubusercontent.com/3717101/29547217-5b156786-86be-11e7-92aa-ea1eeb54003e.png)

However, when I login to oxTrust, I see the passport authentication page:

![image](https://user-images.githubusercontent.com/3717101/29547170-27417f8a-86be-11e7-950a-1aa07fef33b6.png)

Shouldn't I still see the regular password page?

**Comment by yurem** [comment]
Login page updated according this: https://github.com/GluuFederation/oxTrust/issues/596

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/29e0daea455f1a8e93e02755cc3d631c75e7272f

**Comment by shekhar16** [comment]
Fixed. hide the passport block from login page.
![image](https://user-images.githubusercontent.com/15937500/29676860-e6356bd6-8916-11e7-8d8a-e75437077bee.png)
