### ISSUE TITLE
Scope Type is missing

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#678]
WE removed the `Scope type` select box, but I think we need to add it back. 

![image](https://user-images.githubusercontent.com/3717101/29547257-95317b80-86be-11e7-993d-1a12e66a84c3.png)

And it should read simply "OpenID | OAuth". If it's OAuth, there should be no associated claims.

We also need to allow the selection of a dynamic scope script (similar to how authorization scripts are associated to UMA scopes).  We need to add a "Name" field to the dynamic scope script so we can select each one.

**Comment by nynymike** [comment]
Note by Yura:

I think we should do the same what we have In UMA scope description now.

In UMA Scope description form we can specify which scripts to execute.
But in dynamic scope we uses another workflow
We iterate through all dynamic scopes scripts
And script has if statement to verfy if we need to apply this script to scope
It's not optimal

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29584477-764b2656-87a1-11e7-9618-b0f0657aa5ea.png)

**Comment by nynymike** [comment]
Remove "dynamic" -- it should just be OAuth | OpenID.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29673172-09beb0d6-890c-11e7-8bed-6e5d97d5918c.png)

**Comment by willow9886** [comment]
@shekhar16 can you make it say `OpenID` instead of `Openid` ?

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29747828-3dc4d79c-8b24-11e7-93fc-ca1726f3af3e.png)

**Comment by shekhar16** [comment]
removed scopetype="dynamic" condition.the above dialogue display only  script type= "dynamic_scope"  and it should be enabled.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29747994-9d00b528-8b29-11e7-8aa4-83ca78fb3722.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/29748103-321d0164-8b2c-11e7-9b54-0b85031e7c2b.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/b3e702f13eb65870d6d790a65c3ecf1ca3a30061
