### ISSUE TITLE
Updated fav icon and logo not display on page

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#688]
Navigate to Configuration > Organization configuration > oxTrust settings
It updated logo and icon successfully but not reflects on page
problem picture: https://prnt.sc/gc03pm

**Comment by rajnikantsh** [comment]
I have committed changes to display updated logo in organization configuration. Changes won't be available immediately as you click update button. It takes about five minutes or more to reflect.

**Comment by willow9886** [comment]
>  Changes won't be available immediately as you click update button. It takes about five minutes or more to reflect.

@jschristie can you add this note to the docs, re: changing the logo in oxTrust ?
