### ISSUE TITLE
"Download Shibboleth3 configuration files" not work

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#689]
Navigate to SAML > Trust Relationships > select "gluu SP on appliance" > click on "Download Shibboleth3 configuration files"

"Download Shibboleth3 configuration files" link not work and redirect to error page

problem picture: https://prnt.sc/gc1b5w

**Comment by shekhar16** [comment]
Fixed.
Please test it and let me know if any issue found.
