### ISSUE TITLE
Add feature to force oxAuth to generate new Keys

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxTrust#69]
oxAuth already has a feature to rotate keys automatically in a configured time:

```
<!-- Key regeneration interval in hours -->
<key-regeneration-enabled>true</key-regeneration-enabled>
<key-regeneration-interval>48</key-regeneration-interval>
```

It is required to have a way in the UI to rotate keys any time when desired.

**Comment by yurem** [comment]
We need to introduce trigger which oxTrust can use to notify oxAuth to regenerate keys. For example oxTrust can add some attribute to oxAuth configuration entry. This will be flag for oxAuth to rotate key. Before rotating keys oxAuth should remove this attribute from configuration entry.

Also we need to take into consideration that oxAuth can work in cluster. In this case first oxAuth instance which removed attribute should do keys regeneration.

What do you thin about this approach?

**Comment by willow9886** [comment]
@qbert2k can you comment on the status of this issue?

**Comment by shekhar16** [comment]
Can we start to work on set/reset key on oxtrust side ?

**Comment by shekhar16** [comment]
@nynymike  @yurem  Can u please describe the issue?

**Comment by yurem** [comment]
@shekhar16 do you need any input to fix it?

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/99ea3d3a6a3385372ceed8098e19d4106d54073c

**Comment by shekhar16** [comment]
Json sample : {"server_ip":"test1124","update_at":1505844134478}

![image](https://user-images.githubusercontent.com/15937500/30624822-2a6c646e-9ddd-11e7-833e-c5347d2ebfbc.png)

**Comment by shekhar16** [comment]
Fixed.
