### ISSUE TITLE
AttributeResolverAction should not directly update attribute-resolver.xml

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#690]
Here is how all Action classes in oxTrust can trigger IDP config update:
```
			boolean updateShib3Configuration = appConfiguration.isConfigGeneration();
			if (updateShib3Configuration) {
				List<GluuSAMLTrustRelationship> trustRelationships = trustService.getAllActiveTrustRelationships();
				if (!shibboleth3ConfService.generateConfigurationFiles(trustRelationships)) {

					log.error("Failed to update Shibboleth v3 configuration");
					facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to update Shibboleth v3 configuration");
				}
			}
```

Now we have wrong flow. AttributeResolverAction directly update file hard-coded in variable:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java#L38

And other oxTrust service can update same file using shibboleth3ConfService. Asresult each process overwrite previous process changes. We need to fix this.

We need to do:
1) Store AttributeResolverAction configuration in LDAP in one new LDAP attribute.
2) Call code above to trigger shibboleth3ConfService update.
3) Don't [hardcode ](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/action/AttributeResolverAction.java#L127) logic which update attribute-resolver.xml. We uses Velocity to generate files. We need to update attribute-resolver.xml.vm to include your cahnges.

**Comment by rajnikantsh** [comment]
I have some questions regarding three steps you mentioned:
1. For Step 1. I already committed code with following pull requests:
   - https://github.com/GluuFederation/community-edition-setup/pull/318
   - https://github.com/GluuFederation/oxCore/pull/42
   - https://github.com/GluuFederation/oxTrust/pull/630

2. As for Step three I am not updating  attribute-resolver.xml i am updating attribute-resolver.xml.vm. As described in issue https://github.com/GluuFederation/oxTrust/issues/274

**Comment by yurem** [comment]
We can't update update attribute-resolver.xml.vm from oxTrust. We don't customize from oxTrust Velocity templates. It makes upgrade difficult. Also it's difficult to do support if we offer to patch manually our templates.

Instead of this we can prepare Velocity template which will render target file. We generate our all IDP, CAS templates in this way.

Also please fix conflict in this request [630](https://github.com/GluuFederation/oxTrust/pull/630/conflicts).

**Comment by yurem** [comment]
I fixed conflicts/updated and merged pull request GluuFederation/community-edition-setup#318 and GluuFederation/oxCore#42
I changed:
- Attribute oxTrustAttributeResolver to oxTrustConfAttributeResolver to conform other attribute name style
- Property oxTrustAttributeResolver in LdapOxTrustConfiguration to attributeResolverConfig.

Is this GluuFederation/oxCore/pull/38 pull request can we cancel?

Please regenerate LDAP schema files from gluu_schema.json. We need to to this together with this file update. In order to do this you can use our tool: GluuFederation/community-edition-setup/blob/master/schema/generator.py

**Comment by rajnikantsh** [comment]
@yurem I resolved conflict https://github.com/GluuFederation/oxTrust/pull/630/conflicts . Also Yes we can cancel https://github.com/GluuFederation/oxCore/pull/38 pull request as this code is not used anymore.
