### ISSUE TITLE
File upload - SAML TR is broken

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#694]
Create Single SP SAML TR with file upload option. TR is not validated and following error appears.

![image](https://user-images.githubusercontent.com/21104811/29744131-4c26560c-8abc-11e7-8511-426df970c7c6.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/pull/695

**Comment by shekhar16** [comment]
I checked the code and found there is not sync file path name and isfederate method is calling twice in case     of uri and file upload metadata type.
