### ISSUE TITLE
Gluu Server memory usage (3.1.0)

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#697]
I am having an unusual behavior on Gluu server RC5
When I had installed Gluu server RC5. Free memory was 35%. After 3 days it was just 5% and Today, I had to restart the server as oxTrust did not work for me.

**Comment by yurem** [comment]
In CE default caching mode is "in_memory". If there is bug in this mode it can led to this issue.

**Comment by yuriyz** [comment]
@centroxy would you please provide information how much memory is consumed by oxauth and how much by oxtrust(identity) ?

**Comment by yuriyz** [comment]
@centroxy in addition, would you please set cache configuration to REDIS and check how it works. If we get memory issue with REDIS then it means that we have memory leaks and it is not related to cache.

**Comment by centroxy** [comment]
Hi @yuriyz I am not sure how to reproduce this issue. On day 1 of the installation free Memory was 35% and after 5/6 days it slowly went down to 5 %.  I will set the cache configuration and let you know. It may take a week to get back to you .

**Comment by nynymike** [comment]
Perhaps we can run a profiler for an extended period of time. It could be an uncleaned up collection or some other problem object.

**Comment by yurem** [comment]
Final 3.1.1 version works stable on dev servers. We can move this issue to CE 3.1.3 when we will have more feedback about memory usage
