### ISSUE TITLE
Incorrect error message on Register page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#698]
https://host/identity/register
Provide valid values in all fields except the "Email" Field.

This results in displaying wrong validation error message on all other fields having correct values provided. 

![image](https://user-images.githubusercontent.com/21104811/29795373-86bb0a80-8c3b-11e7-8093-1de41c4b34a4.png)

**Comment by willow9886** [comment]
Also, validation errors should only show up if invalid data has been entered into a field.

**Comment by zamilskhan** [comment]
Addition: once the email is provided, user is not registered and there is nothing in oxauth or oxtrust logs.
![create-user-error](https://user-images.githubusercontent.com/7703245/29796518-6bf87362-8c73-11e7-878a-d08f79de33db.png)
