### ISSUE TITLE
Enhancement for "shibboleth2-configuration.zip" elements

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#7]
* attribute-map.xml
   * Released attributes are not showing it's urn value, instead it is loading
the value from template.
i.e. the snippet of existing "attribute-map.xml" from one trust relationship
where I released UID and givenName:

              <Attribute name="urn:oid:$attrParams.attributeOids.get($attribute.name)" id="uid"/>
              <Attribute name="urn:oid:$attrParams.attributeOids.get($attribute.name)" id="givenName"/>

* shibboleth2.xml
   * handlerURL for SP has syntax error. In the below the url has double "//" before "Shibboleth.sso"
i.e: Existing configuration generated by IDP:

             <Sessions lifetime="28800" timeout="3600" checkAddress="false"
                handlerURL="https://mytestsp.gluu.org//Shibboleth.sso" handlerSSL="false"

    * Suggestion:
       * exportLocation: Possible to add hostname of SP instead of "localhost"?
       * MetadataProvider: Generally SP do not have this(**) location. Possible to
keep it just like this:  "MetadataProvider type="XML" file="idp-metadata.xml"
        * CredentialResolver: Same. Possible to add comment for end user as they
modify the location of Key and Cert according to their own file system? 
Or, can we add comment which will instruct user to provide the static location
for their file system?

(**) opt/idp/metadata/

**Comment by otataryn** [comment]
How can this be reproduced?

**Comment by mzico** [comment]
We can create a trust relationship with "generate" method for any testSP.

**Comment by mzico** [comment]
@willow9886 , @yurem: Just tried in Gluu 2.4. It's working well. Closing the issue.
