### ISSUE TITLE
Make it easier to manage approved redirect_uris for sector_identifier_uri validation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#70]
oxAuth validates that when a client registers a sector_identifier, the redirect_uri's registered must be present in a JSON at the specified https location [OpenID Connect Client Registration](http://openid.net/specs/openid-connect-registration-1_0.html#SectorIdentifierValidation) 

That JSON file could be anywhere, but it would be convenient if oxTrust provided a way to publish these. For example, a simple interface would enable you to creat, browse, update and delete all the sector_identifier_uri's respective allowed redirect_uris.

**Comment by willow9886** [comment]
@qbert closing this issue..
