### ISSUE TITLE
Localization on French, doesn't render the page porpoerly

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#700]
When selecting language from dropdown to french, the page doesn't render properly, where as for Russian, the page is rendering properly.

![image](https://user-images.githubusercontent.com/23150138/29825274-8c0b5c40-8cf1-11e7-8ba1-b70f7970c89d.png)

![image](https://user-images.githubusercontent.com/23150138/29825290-97fa85ee-8cf1-11e7-88c9-0b38ac3490ff.png)

and also while changing language, the graph isn't coming up properly, until it is refreshed twice.

**Comment by worm333** [comment]
While we do not have a translation into French, we can disable `french` option in dropdown. What do you think ?

**Comment by willow9886** [comment]
@worm333 yes, lets disable for now.

**Comment by yurem** [comment]
@worm333 can we close it?

**Comment by worm333** [comment]
Removed French language in [this commit](https://github.com/GluuFederation/oxTrust/commit/792c7402634e9ddc21508baf359742047370434b).
