### ISSUE TITLE
Weld notification at the bottom of the screen is blocking few features

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#701]
Weld notification is blocking some of the processes until the weld notification is closed. Can this notification be removed or blocked from appearing on the screen.

![image](https://user-images.githubusercontent.com/23150138/29825481-2d400dae-8cf2-11e7-899c-b1db45013386.png)

**Comment by yurem** [comment]
I'm closing it. During build run we can select production/development build:
![default](https://user-images.githubusercontent.com/6104200/29930809-1e7f1ad0-8e78-11e7-9d0d-cb781f1c9d43.png)

In final packages I will turn it off
