### ISSUE TITLE
Update OpenID Client page to support JWT access tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#703]
Complementary to issue: 
 https://github.com/GluuFederation/oxAuth/issues/638

**Comment by lrkirven** [comment]
Do you guys have some specific documentation for configuring the JWT access tokens?

**Comment by nynymike** [comment]
@lrkirven You'll need to leave a more specific support issue. You may be able to accomplish your goal with either the `id_token` JWT or `userinfo` JWT.  Please open an issue on https://support.gluu.org

**Comment by yuriyz** [comment]
done in 3.1.4 and master
