### ISSUE TITLE
After changing oxAuth/oxTrust JSON conf application should reload settings

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#71]
For example we can add json attribute version and increase it at every config update.
On oxAuth/oxTrust periodic job should reload config on version change

**Comment by yurem** [comment]
We implemented reload from file system on configuration file changes. I think we need to update configuration file or give access to see properties in readonly mode.

**Comment by rahatjaan** [comment]
What action needs to taken here???? I don't understand as reload mechanism is already in place so do we really need to do something here??

**Comment by yurem** [comment]
We need to discuss this with Mike
While working on cluster we added ability to reload config files without tomcat restart. The configuration update in LDAP now works in this way FS->Application->LDAP
If we add additional workflow Application->LDAP we will get mix.

I think this part should update config files in FS. After changing them system will reload them automatically.

**Comment by yurem** [comment]
I think we should support reload config from FS only. This GUI should allow view setting only or render updated oxAuth/oxTrust configuration files. What do you think?

**Comment by nynymike** [comment]
Management of config on the filesystem presents a problem for scalability. It means that in a cluster, we will have to push files... in LDAP, the active (cn=config) is stored in memory, and when the LDAP server is shutdown, it updates /opt/opendj/conf/config.ldif   It is not recommended to modify the filesystem, but if you do so, the LDAP server must be stopped at the time (and then changes will be picked up at startup, or as you mentioned by putting a flag file in the folder). But one of the criticisms of the Gluu Server is reliance on filesystem config, which I happen to agree with. Its really makes it harder for clustered deployments.

**Comment by yurem** [comment]
@iromli I think this issue will be interesting for you too

**Comment by yurem** [comment]
Requirement about reload conf files we got from gluu cluster. As far as I remember in their architecture they put updated files to each node on starting/stopping nodes.

We uses LDAP replication. It's not clear how workflow will look if we change configs on few nodes. Also configs in file systems allows to do upgrade from one to another server. It's easy to compare config files.

Current JSON editor is not ready. It allows to remove/add dummy nodes, etc.. For me we can use it in read only mode only now.

Which approach is the better for us?

**Comment by nynymike** [comment]
Ok, this is very disappointing news... I thought the whole point of the JSON editor was that its very hard to modify the JSON in LDIF.

**Comment by yurem** [comment]
We need to improve it. It should have basic information about config structure. This editor should know if the value is multi-value, mandatory, etc.. For example we can add annotations to config beans to give it this information.

Also we need take into consideration gluu-server too. What we really need to update on all nodes after starting/stopping new cluster node.

**Comment by yurem** [comment]
Done
