### ISSUE TITLE
Redis is not available on "cacheProviderType" combobox 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#715]
There are 2 bugs:
1. Minor : Title says : oxMemCache-Config. But it's not only memcached configuration. It is generic configuration for oxauth. I would expect to see "Cache Provider Configuration".
2. CRITICAL : it is not possible to select "Redis" as configuration provider in combobox. See screenshot attached.

![redisconfiguration_notavailable](https://user-images.githubusercontent.com/2013070/30221982-1715fb5e-94ce-11e7-85bf-3dfcf5f1e790.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/485

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/30246557-5696cc4c-961b-11e7-8e4c-a920644933f8.png)

**Comment by yuriyz** [comment]
@shekhar16 good job. Between, did u check whether redis configuration is really persisted in ldap ?

**Comment by willow9886** [comment]
re-opening until @shekhar16 can confirm @yuriyz's above question. Thanks.

**Comment by shekhar16** [comment]
Yes cacheProviderType dropdown value and redis configuration both will get update we make any change in that.

**Comment by yuriyz** [comment]
please merge into`version_3.1.1`

**Comment by shekhar16** [comment]
Its working on 3.1.1 as well. So closing it.

![image](https://user-images.githubusercontent.com/15937500/30512095-a6b0e7a6-9b04-11e7-8d84-21c2b9f97b93.png)
