### ISSUE TITLE
UMA 2 : resource added via api exists in ldap but is not visible on GUI

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#716]
https://support.gluu.org/access-management/4480/cannot-add-resource-or-resource_set-in-uma2/#at25249

**Comment by shekhar16** [comment]
@yuriyz  I checked the ldap and found we have 2 similar ou i.e resource_set and resource.
Presenlty the Uma>resources is implemented for ou=resources not for resource_set.

![image](https://user-images.githubusercontent.com/15937500/30249426-10cc09a4-965a-11e7-8042-6a1243468671.png)

object class for resources is oxUmaResource and for resource_set is oxAuthUmaResourceSet.
So are we replacing resources with resource_set and there respective classes.
And oxAuthUmaResourceSet object class is not declared in gluu.schema.
Please let me know.

**Comment by yuriyz** [comment]
In UMA 2 we have 'resource' name instead of 'resource set' as it was in UMA 1.0.1. So now we are using ou=resources and oxUmaResource. ou=resource_sets and oxAuthUmaResourceSet is removed.

**Comment by yuriyz** [comment]
Also I hope u are reusing oxauth ldap classes instead of duplicating. For uma resource it is https://github.com/GluuFederation/oxAuth/blob/version_3.1.0/Model/src/main/java/org/xdi/oxauth/model/uma/persistence/UmaResource.java#L24-24

**Comment by shekhar16** [comment]
Fixed.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/30387059-126e8658-98c9-11e7-8ced-25c7b1f51c2f.png)

**Comment by yuriyz** [comment]
@shekhar16 fix is not in `version_3.1.1` branch. Please merge or cherry-pick.

**Comment by shekhar16** [comment]
its working on 3.1.1 version.
