### ISSUE TITLE
Super gluu Enrol page.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#717]
![image](https://user-images.githubusercontent.com/15937500/30249552-4cd43532-965c-11e7-812d-a36740c88ead.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/37f41f7de889e2a86e4d4ae90f65e191bc36b5e3

https://github.com/GluuFederation/oxAuth/commit/30c5da6e4105f852c95b4241d5af293cff70850b

**Comment by shekhar16** [comment]
@willow9886  the super gluu enrol page is added .
![image](https://user-images.githubusercontent.com/15937500/30249679-859425ce-965e-11e7-8868-772553146730.png)

**Comment by willow9886** [comment]
@shekhar16 it looks like the logo is being cut off by the web address bar.. 

also, the "Enroll your device" text at the top of the page should be formatted as a header.

**Comment by shekhar16** [comment]
![Uploading image.png…]()

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/41e83de77862625de24f66082f8be8a86bd698f0

**Comment by willow9886** [comment]
@shekhar16 looks good!

**Comment by shekhar16** [comment]
Can we close this issue?

**Comment by willow9886** [comment]
@shekhar16 this will be included in the 3.1.1 packages?

**Comment by willow9886** [comment]
We also need to make sure the subsequent authn page gets added: 

![image](https://user-images.githubusercontent.com/5271048/30981398-db416eac-a449-11e7-8396-2349d6205418.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/b6fe4b7f61a54351683fc8b061ce2bf4ef6bc7ec
