### ISSUE TITLE
Add interfaces for Asimba

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#72]
If Asimba is deployed during installation, oxTrust should include interfaces to make managing Asimba easier. This is something that can be incorporated into the [interface redesign project](https://github.com/GluuFederation/oxTrust/issues/63). We'll need to put together some wireframes so that we know which functionality should be manageable from the interface.

**Comment by willow9886** [comment]
Let's add an additional dropdown in the existing SAML menu to include Asimba.. see screenshot below. 

![image](https://cloud.githubusercontent.com/assets/5271048/12124145/153341ea-b3aa-11e5-8c71-899a8a1d2dd7.png)

**Comment by dmogn** [comment]
![oxtrust_addidp_form](https://cloud.githubusercontent.com/assets/14166017/12658405/a2a366fa-c5e7-11e5-9894-41bcc7998150.jpg)

New SAML submenu. "Add IDP" form.

**Comment by dmogn** [comment]
![oxtrust_addsprequestor_form](https://cloud.githubusercontent.com/assets/14166017/12684677/f5ac4490-c69e-11e5-8dba-8bbc6d3fe9b6.jpg)


"Add SP Requestor" (add client application) form.

**Comment by dmogn** [comment]
![oxtrust_addselector_form](https://cloud.githubusercontent.com/assets/14166017/12732021/6196d510-c912-11e5-95c2-a2a68a5ed814.jpg)

"Add Selector' form.

**Comment by dmogn** [comment]
![oxtrust_idps_form_preview](https://cloud.githubusercontent.com/assets/14166017/12830131/71244b96-cb6c-11e5-9012-18ff7356a732.jpg)

Two table stales from other oxTrust pages. Which is better?

**Comment by nynymike** [comment]
bottom one

**Comment by dmogn** [comment]
Done.

**Comment by dmogn** [comment]
TODO for 2.4.2: More hints, rename some fields, set selection to "Selector" form

Mike Schwartz: its confusing...
Mike Schwartz: What is a Selector?
Mike Schwartz: Where would one find the organziation id?

Mike Schwartz: Its asking me for a bunch of ID's... and I'm not sure where to find them
Mike Schwartz: PreAuthorizationProfileID, PostAuthorizationProfileID, AttributeReleasePolicyID, 
Mike Schwartz: what is this stuff????
I see a link for add IDP
Mike Schwartz: Is that "Add SP Requestor" ?
Dmitry Ogn: It is Asimba config term... Asimba uses terms "Requestor", "Requestor Pool". But industry term is "SP"

Mike Schwartz: But we can maybe put some in context hints about what's going on.
Mike Schwartz: If I can't understand it... who can?
Mike Schwartz: The term "ID" is not really accurate.
Mike Schwartz: an ID is normally a part of an elemnt of the XML
Mike Schwartz: think entityID....
Mike Schwartz: I think you are asking for the inbound URL there....
Mike Schwartz: and maybe an exact match.
Mike Schwartz: not sure...

**Comment by yurem** [comment]
Can we close it?

**Comment by dmogn** [comment]
Maybe yes.
