### ISSUE TITLE
Cache Provider Configuration settings fix

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#723]
![bug](https://user-images.githubusercontent.com/30447907/30668937-102eb9e0-9e22-11e7-8a8f-a2d6bf03273e.png)
MEMCACHED configuration instruction for `servers` should read `server details separated by spaces` and not `server details separated by commas`

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/32987321-1d7d9ca4-cd0e-11e7-8116-b9184e0e1ee6.png)

**Comment by shekhar16** [comment]
fixed.

**Comment by afroDC** [comment]
Did you change it in the picture you linked? It still says "server details separated by commas"

It should read "server details separated by spaces" as instructed above.

**Comment by shekhar16** [comment]
Oh Sorry that was older snap
Here is fixed snapshot.
![image](https://user-images.githubusercontent.com/15937500/32994009-0af94b18-cd87-11e7-9d3c-53117df547dd.png)
