### ISSUE TITLE
Error on clicking INACTIVE attributes in Oxtrust UI

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#724]
Configuration >  Attributes > Show All Attributes
Click on any INACTIVE attribute, say city
Error message is displayed on screen. This behavior is intermittent and no error in identity or openldap logs

![image](https://user-images.githubusercontent.com/21104811/30677334-d2606d20-9ea8-11e7-8a99-12c4d6f69cd4.png)

**Comment by shekhar16** [comment]
@yurem I debugged the code and found 2 issues one is fixed regarding nullponter for getSaml2Uri.
second issue is the list of attributes are coming from cacheprovider which return null and some time list of attribute.

**Comment by mzico** [comment]
@yurem @shekhar16 : Problem persist in 3.1.1 beta2. 
If you want to reproduce the issue, you can try to 'Enable'  _Description_ attribute.

**Comment by shekhar16** [comment]
Fixed.
