### ISSUE TITLE
Add User - Input fields editable after click 3 times.

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#728]
Go to Users > Add Person
Try to input "Username" or any other field.
Expected Result - User should be able to input
Actual Result -  unless click 3 times, it won't let enter anything in the field.

Nothing recorded in identity logs.

**Comment by yurem** [comment]
Can you take a look on this? I suspect your JS which fix tab order led to this issue

**Comment by rajnikantsh** [comment]
code comitted https://github.com/GluuFederation/oxTrust/pull/730/commits/f8ea1f0caa761a389373dfca46779fcecd6c1a83
