### ISSUE TITLE
Add new redisProviderType configuration property

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#729]
UI needs to have combo box to be able select `redisProviderType` 
https://github.com/GluuFederation/oxAuth/issues/652

Configuration of redis now contains:

- redisProviderType - type of connection, valid values are : STANDALONE, CLUSTER, SHARDED
- servers - property with server connection string, example: localhost:6379 (for tutorial cluster it will be localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005)
- defaultPutExpiration - default put expiration in seconds

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/30761383-adb0965e-9ffb-11e7-8215-7ad40b63e0b3.png)
