### ISSUE TITLE
Default Value for Cache Refresh --> LDAP

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#73]
The default value is for Cache Refresh is "VDS" which no one uses. We should change this to LDAP

**Comment by nynymike** [comment]
![image](https://cloud.githubusercontent.com/assets/3717101/7776809/813986c2-0083-11e5-8e1e-7eba9d1d23d7.png)

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxTrust/commit/b5104de539be0d71d15196172de3ee0ee2091df8
