### ISSUE TITLE
The Gluu logo still doubles up in the top left corner

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#731]
![image](https://user-images.githubusercontent.com/30447907/30870650-09b5a90c-a2aa-11e7-929d-22f8b956a5f9.png)

**Comment by afroDC** [comment]
Is this a new installation? Are you using the latest 3.1.1 beta? Did you change the code in any way? 

Sometimes the bug comes out and sometimes it doesn't happen at all.

**Comment by shekhar16** [comment]
I m using latest oxtrust build.

**Comment by afroDC** [comment]
Testing again with a fresh install of 3.1.1

**Comment by shekhar16** [comment]
@afroDC  please verify it and let me know ,otherwise please close this issue.

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/30987280-091c7062-a45c-11e7-85c9-7b704578624f.png)

The problem still exists.

**Comment by afroDC** [comment]
There are 2 logo references in the HTML it seems:

![image](https://user-images.githubusercontent.com/30447907/30987522-ee1c2784-a45c-11e7-8131-220c85441725.png)

Note when I delete:

```
<img style="width: 230px; height: 70px;" src="/identity/servlet/logo">
```

The larger logo disappears.

![image](https://user-images.githubusercontent.com/30447907/30987595-2cb71d32-a45d-11e7-9402-036d3e43af5b.png)

**Comment by shekhar16** [comment]
I tried with ce-dev3.gluu.org environment but it is not reproduced,I tried on firefox and chrome aswel.
here is snapshot.
![image](https://user-images.githubusercontent.com/15937500/31020798-9f958204-a551-11e7-9949-33ff1ae2b0b8.png)

**Comment by willow9886** [comment]
@shekhar16 this logo looks too large.. the logo as shown in @afroDC's screenshot is the correct logo size.

![image](https://user-images.githubusercontent.com/5271048/31021340-2761a48a-a4fb-11e7-9fb4-dc443d9aa23f.png)

**Comment by yurem** [comment]
Fixed
