### ISSUE TITLE
SAML menu shows up even if not installed

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#732]
Seems to be related to an already closed issue:

https://github.com/GluuFederation/oxTrust/issues/216

SAML options on the left menu should be hidden if SAML is not installed.

**Comment by willow9886** [comment]
oxTrust interfaces should not be displayed for any optional components that **have not been installed**, for example: Shibboleth, Asimba, Passport, etc.

**Comment by yurem** [comment]
Fixed
