### ISSUE TITLE
Configure Log Viewer New Log Template button not working

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#734]
Package: gluu-server-3.1.1.x86_64 1-1.beta2.centos6
The "Add Log Template" button does not work as tested in Mozilla Firefox and Chromium.
![configu-log-viewer-error](https://user-images.githubusercontent.com/7703245/30924094-95a01a30-a3cf-11e7-9021-273a682d1ea6.png)

**Comment by yurem** [comment]
Fixed
