### ISSUE TITLE
OpenID Dynamic Scope Type value is missing

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#738]
![image](https://user-images.githubusercontent.com/3717101/31030141-e6720306-a519-11e7-80db-9b72a95bbf24.png)

Which is causing [this issue](https://support.gluu.org/customization/4566/dynamic-scope-script-does-not-seem-to-be-called-anymore-in-310/)

**Comment by yurem** [comment]
Fixed
