### ISSUE TITLE
Commit with Comment

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#739]
If you watch [this video](
https://www.youtube.com/watch?v=SLPSrzk_VnM&feature=youtu.be&a=), you can see that it has an interesting workflow for submitting changes. Instead of having a submit button, it implements a "Commit" feature. This encourages the admin to put a comment about what config changed, and you could write a log message with the change that was made.

**Comment by shmorri** [comment]
Moved to the new UI project: https://github.com/GluuFederation/gluu-admin-ui/issues/123
