### ISSUE TITLE
Extend Authentication Script to support GUI representation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#741]
It would be nice to have a GUI representation of Authentication Scripts.

**Comment by shekhar16** [comment]
@nynymike We already had GUI representation for authentication script.Please let me know if I need to add anything.

![image](https://user-images.githubusercontent.com/15937500/31192102-de0cbb1e-a95d-11e7-941f-87fdce0635dc.png)

**Comment by shekhar16** [comment]
Is it ok or you need to change design.onclick the script options will get open.

![image](https://user-images.githubusercontent.com/15937500/31350238-0b93f0ea-ad44-11e7-9960-d67f98cd1cec.png)

**Comment by shekhar16** [comment]
Fixed in master and 3.1.2 version

**Comment by willow9886** [comment]
![image](https://user-images.githubusercontent.com/5271048/31396800-057d35fc-adaa-11e7-9eb4-ed65dcf97d67.png)

**Comment by willow9886** [comment]
![image](https://user-images.githubusercontent.com/5271048/31397541-e856b3a2-adab-11e7-9216-78ba026e106c.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/31578245-ba8ced00-b13a-11e7-8cdb-c404efaab793.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/32787018-84227d44-c97b-11e7-95ce-9d6a9e71d5da.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/32787071-a55653c8-c97b-11e7-9903-b566f2e561d6.png)
