### ISSUE TITLE
No option to clear an OIDC client's setting if it was already set to some value explicitly using a drop-down list

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#745]
Environment: Ubuntu 14.04, gluu-server-3.1.1-1.beta3~trusty+Ub14.04

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "OpenID Connect -> Clients" page
3. Create a client's registration with minimal set of properties there
4. Summon drop-down list corresponding to  "JWS alg Algorithm for signing the Userinfo Response" property and note its composition
5. Set this property to "RS256" and click "Update" button
6. Summon drop-down list corresponding to  "JWS alg Algorithm for signing the Userinfo Response" property again and note its composition

Result:

Initially this (and many other similar) setting is devoid of actual value, thus oxAuth resorts to using some defaults. On step 4) it can be seen that in the drop-down list, aside from "none" value, there is an empty space value present (see picture below). When the same drop-down list is viewed on step 6), the empty space value is not present any more, thus it's impossible to restore the original, empty state of the setting.

Though it may appear that "none" settings should play the same role as the empty space/absence of value, at least in the case of "JWS alg Algorithm for signing the Userinfo Response" it's not the same. By default (out-of-the-box, when it's empty), it results in a clear-text JSON object being returned from userinfo, while when set to "none" what is returned is JWT token (base64-encoded, dot-separated), though without a signature part (what still conforms to the spec).

Thus inability to restore the original empty state of some property if it was previously changed leads to inability to set a perfectly valid mode of endpoint's operation via web UI (and perhaps results in similar issues in case of other properties there which are set via drop-down lists)

![selection_080](https://user-images.githubusercontent.com/11802046/31301631-1cb3e110-ab04-11e7-8cf5-cdb195faed55.jpg)

Expected result:

Drop-down lists on this page should always contain a clear-space value in them which, if used, clears corresponding property of its current value.

**Comment by shekhar16** [comment]
Fixed. 
Added empty option in all dropdowns on update client page
![image](https://user-images.githubusercontent.com/15937500/31383488-da252926-add8-11e7-8285-46f5d08cebb5.png)
