### ISSUE TITLE
Change data type "Photo" to "binary"

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#748]
When creating a custom attribute, data type "photo" should read as "binary" to cover all binary types.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/522e9c07b71a423cfb4fbf5c41bd530a4eb3e1b8

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/36559610-854b2ac4-1834-11e8-9e40-28f393598f3c.png)

**Comment by yurem** [comment]
We also need to change:
```
PHOTO("photo", "Binary")
to
BINARY("binary", "Binary")
```

Also in setup attributes.ldif we need to change `photo` to `binary`.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/pull/70
