### ISSUE TITLE
Unable to delete created attributes

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#750]
I'm unable to delete newly registered attributes in oxTrust. 

![image](https://user-images.githubusercontent.com/30447907/31565174-706b288c-b02b-11e7-813a-488ed2b4056f.png)

**Comment by shekhar16** [comment]
@afroDC  can u please share the details how you created the new attribute.

**Comment by shekhar16** [comment]
@afroDC can u please share the above required details.So that we can resolve this high priority issue asap.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33000612-3db046b8-cdcf-11e7-91a7-fbae131bbce8.png)

after register new attribute ,listed in attribute list.
![image](https://user-images.githubusercontent.com/15937500/33000676-8623d81a-cdcf-11e7-9773-f64791ea8c25.png)

Now deteted the attribute ,working fine.here is successful message after delete..
![image](https://user-images.githubusercontent.com/15937500/33000721-ccb517ee-cdcf-11e7-9575-70db3ab36755.png)

**Comment by shekhar16** [comment]
It is working fine for me.
Closing this issue.please let me know if you can reproduce it and reopen the issue.
