### ISSUE TITLE
oxTrust cannot create "userCertificate"

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#751]
Adding an entry for the attribute userCertificate results in a "failed to create user error"

![image](https://user-images.githubusercontent.com/30447907/31565354-13feb8a6-b02c-11e7-9f06-28dcbc4f2cbd.png)

Inside the identity log:

2017-10-13 16:34:34,673 ERROR [qtp1689843956-19] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:259) - Failed to add new person @!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!F130.FAAC.3A94.7404
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!F130.FAAC.3A94.7404,ou=people,o=@!4F28.9AB9.686C.B2E5!0001!373A.FC53,o=gluu

...[snip]...

Caused by: com.unboundid.ldap.sdk.LDAPException: userCertificate: requires ;binary transfer

...[snip]...

**Comment by afroDC** [comment]
It is necessary to assign the `userCertificate` attribute to `gluuPerson` before this. Then create a `userCertificate` attribute entry.

I can modify and add entries with ldapmodify like so:

```
vi chris.ldif

dn: inum=@!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!dc,ou=people,o=@!4F28.9AB9.686C.B2E5!0001!373A.FC53,o=gluu
changetype: add
oxCreationTimestamp: 20171013181917.088Z
uid: afroDC
givenName: Chris
displayName: DC
sn: Blanton
mail: dc@gluu.org
gluuStatus: active
oxTrustEmail: {"operation":null,"value":"dc@gluu.org","display":"dc@gluu.org","p
 rimary":true,"reference":null,"type":"other"}
inum: @!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!dc
iname: *person*afroDC
userPassword:: e0JDUllQVH0kMmIkMDgkbEt3QjRoeFdaaldYZklUdEZIRXhIdTZrTFVWNy5HZ1pWY
 khpcURyTE90R0d3RVJMSWxtd2UA
usercertificate:: MIICOzCCAaSgAwIBAgIIG4PzK/izWnowDQYJKoZIhvcNAQEFBQA
 wYDFeMAkGA1UEBhMCVVMwCQYDVQQIEwJLTDAOBgNVBAoTB0N5cnVzeHAwDgYDVQQLEwdDeXJ1c3
 hwMBIGA1UEAxMLQW5hbmRiYWJ1IFYwEgYJKoZIhvcNAQkBFgVhbmFuZDAeFw0xNTA5MjExMTUxN
 TBaFw00NzA1MzAxMzM4MzBaMGAxXjAJBgNVBAYTAlVTMAkGA1UECBMCS0wwDgYDVQQKEwdDeXJ1
 c3hwMA4GA1UECxMHQ3lydXN4cDASBgNVBAMTC0FuYW5kYmFidSBWMBIGCSqGSIb3DQEJARYFYW5
 hbmQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAIS+XfAHIQPhuBb6RnpFyDElS1O0dj7Sxb
 fYqspQzevqQYQs2QsAqodD79sNc6yErB4+Uj7yxZE7SFhJ3/c3e6vGvNL8gfJVL31tnBN1iI8rG
 tpjl3Et1imS+AlmZHRkUWE0d7xrxd2D53dgOcJXPUFsUaLUfzaPGs9FPdbUVrgHAgMBAAEwDQYJ
 KoZIhvcNAQEFBQADgYEALWx0ok3k2fS439QgFWWYqFWfaS83Qq8mGOt8VBIDYLY06CDHUQrqKaW
 Aij2hJeTYrYLecoCa6WxrDXAy4m+y99qBRaP0pJyYTkeR6hsQbQomIsST9fTPaI42j50hy3WeLm
 dN86Vmv+SFjAniyOhmrPjPkV000k95mo6PYKWEkqw=
cn: Chris DC
objectClass: top
objectClass: gluuPerson
objectClass: gluuCustomPerson
objectClass: eduPerson

/opt/opendj/bin/ldapmodify -p 1636 -Z -X -D "cn=directory manager,o=gluu" -w secret -f chris.ldif

[root@localhost ~]# /opt/opendj/bin/ldapsearch -p 1636 -Z -X -D 'cn=directory manager,o=gluu' -w secret -b o=gluu "cn=*"

dn: inum=@!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!dc,ou=people,o=@!4F28.9AB9.68
 6C.B2E5!0001!373A.FC53,o=gluu
mail: dc@gluu.org
iname: *person*afroDC
displayName: DC
givenName: Chris
sn: Blanton
cn: Chris DC
oxCreationTimestamp: 20171013181917.088Z
objectClass: top
objectClass: eduPerson
objectClass: gluuPerson
objectClass: gluuCustomPerson
userCertificate;binary:: MIICOzCCAaSgAwIBAgIIG4PzK/izWnowDQYJKoZIhvcNAQEFBQAwYDF
 eMAkGA1UEBhMCVVMwCQYDVQQIEwJLTDAOBgNVBAoTB0N5cnVzeHAwDgYDVQQLEwdDeXJ1c3hwMBIGA1
 UEAxMLQW5hbmRiYWJ1IFYwEgYJKoZIhvcNAQkBFgVhbmFuZDAeFw0xNTA5MjExMTUxNTBaFw00NzA1M
 zAxMzM4MzBaMGAxXjAJBgNVBAYTAlVTMAkGA1UECBMCS0wwDgYDVQQKEwdDeXJ1c3hwMA4GA1UECxMH
 Q3lydXN4cDASBgNVBAMTC0FuYW5kYmFidSBWMBIGCSqGSIb3DQEJARYFYW5hbmQwgZ8wDQYJKoZIhvc
 NAQEBBQADgY0AMIGJAoGBAIS+XfAHIQPhuBb6RnpFyDElS1O0dj7SxbfYqspQzevqQYQs2QsAqodD79
 sNc6yErB4+Uj7yxZE7SFhJ3/c3e6vGvNL8gfJVL31tnBN1iI8rGtpjl3Et1imS+AlmZHRkUWE0d7xrx
 d2D53dgOcJXPUFsUaLUfzaPGs9FPdbUVrgHAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEALWx0ok3k2fS4
 39QgFWWYqFWfaS83Qq8mGOt8VBIDYLY06CDHUQrqKaWAij2hJeTYrYLecoCa6WxrDXAy4m+y99qBRaP
 0pJyYTkeR6hsQbQomIsST9fTPaI42j50hy3WeLmdN86Vmv+SFjAniyOhmrPjPkV000k95mo6PYKWEkq
 w=
gluuStatus: active
userPassword:: e0JDUllQVH0kMmIkMDgkbEt3QjRoeFdaaldYZklUdEZIRXhIdTZrTFVWNy5HZ1pWY
 khpcURyTE90R0d3RVJMSWxtd2UA
oxTrustEmail: {"operation":null,"value":"dc@gluu.org","display":"dc@gluu.org","p
 rimary":true,"reference":null,"type":"other"}
inum: @!4F28.9AB9.686C.B2E5!0001!373A.FC53!0000!dc
uid: afroDC
```

Note that the `userCertificate::` entry is automatically changed to `userCertificate;binary::`

**Comment by afroDC** [comment]
See this ticket for further information:

https://support.gluu.org/authentication/4636/hosting-openldap-server-in-separate-server/

**Comment by afroDC** [comment]
See this ticket for further information:

https://support.gluu.org/identity-management/4623/how-to-load-binary-data-from-openldap-to-gluu-openldap/

**Comment by jgomer2001** [comment]
I added the attribute to `gluuPerson` and also included `userCertificate` in the attributes branch (see commit above) as suggested by dc.

I am unsure of what needs to be done for this to work. Still getting what dc pointed out:
```
ERROR gluu.oxtrust.action.UpdatePersonAction UpdatePersonAction.java:220- Failed to update person @!3245.DF39.6A34.9E97!0001!513A.9888!0000!0E09.B2B4.52F0.88EA
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!3245.DF39.6A34.9E97!0001!513A.9888!0000!0E09.B2B4.52F0.88EA,ou=people,o=@!3245.DF39.6A34.9E97!0001!513A.9888,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:185) ~[oxcore-ldap-3.2.0-SNAPSHOT.jar:?]
...
Caused by: com.unboundid.ldap.sdk.LDAPException: userCertificate: requires ;binary transfer
	at com.unboundid.ldap.sdk.LDAPConnection.modify(LDAPConnection.java:2754) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.modify(AbstractConnectionPool.java:1304) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at org.gluu.site.ldap.OperationsFacade.modifyEntry(OperationsFacade.java:563) ~[oxcore-ldap-3.2.0-SNAPSHOT.jar:?]
	at org.gluu.site.ldap.OperationsFacade.updateEntry(OperationsFacade.java:549) ~[oxcore-ldap-3.2.0-SNAPSHOT.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:179) ~[oxcore-ldap-3.2.0-SNAPSHOT.jar:?]
	... 136 more
```

It's @shekhar16  turn to see what's wrong.

**Comment by yurem** [comment]
We added binrary attributes support long time ago. But admin must define these attributes in ox-[ldap.properties](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/ox-ldap.properties#L23)

Can you add userCertificate to this list, restart application and try to persist user entry again?

**Comment by yurem** [comment]
If this helps we need to add this attribute to ox-ldap.properties setup template

**Comment by jgomer2001** [comment]
Same error after `ox-dap.properties` update...
`oxtrust_persistence.log` is showing:

```
...
07:58:32,987 DEBUG [main] [org.gluu.site.ldap.LDAPConnectionProvider] (LDAPConnectionProvider.java:162) - Using next binary attributes: [objectguid, usercertificate]
...
08:00:25,669 DEBUG [qtp622889-14] [org.gluu.site.ldap.persistence.AbstractEntryManager] (AbstractEntryManager.java:275) - LDAP attributes for merge: [AttributeModification [modificationType=REPLACE, attribute=Attribute [name=updatedAt, values=[20171123130025.652Z]], oldAttribute=Attribute [name=updatedAt, values=[20171112132809.390Z]]], AttributeModification [modificationType=REPLACE, attribute=Attribute [name=oxTrustEmail, values=[{"operation":null,"value":"jg@gl.com","display":"jg@gl.com","primary":true,"reference":null,"type":"other"}]], oldAttribute=Attribute [name=oxTrustEmail, values=[{"value":"jg@gl.com","display":"jg@gl.com","type":"other","primary":true}]]], 
   AttributeModification [modificationType=ADD, attribute=Attribute [name=userCertificate, values=[MIICO...qw=]], oldAttribute=null]]
...
```
Also tried removing lowercasing [here](https://github.com/GluuFederation/oxCore/blob/master/oxLdap/src/main/java/org/gluu/site/ldap/LDAPConnectionProvider.java#L159) and rebuilding. No success

**Comment by yurem** [comment]
According to your last message this attribute requires special value format and it's not similar to binary attributes. 
I think we need to do next:
1. Add new option to ox-ldap.properties "certificateAttribute"
2. In this method go through list of attributes which we are going to persist and add ";binary" to attribute name. More info is here: http://www.tldp.org/HOWTO/archived/LDAP-Implementation-HOWTO/certificates.html
3.  Check if persist/read/update works fine.

**Comment by yurem** [comment]
We added support for userCertificate attribute in oxLdap. There is remaining part in oxTrust. We need to fix GUI to support them too.

**Comment by yurem** [comment]
I added:

1. new "[certificate](https://github.com/GluuFederation/oxCore/commit/41996cce30c23726d6acbdf6c58230b5ddeba68d)" attribute type
2. It's [definition ](https://github.com/GluuFederation/community-edition-setup/commit/1ff6a510393d214477672d89488e781bcb9dd17c) in setup

Now we need to update this [page ](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/WEB-INF/incl/person/personForm.xhtml)and probably action code in simular to 'userPassword' way. Here is example:

```
<ox:decorate label="#{msg['person.userCertificate]}" rendered="#{(_custAttr.adminCanEdit or _mustEnter) and (_custAttr.metadata.displayName eq 'Certificate')}">
    <div class="col-xs-10">
// Paste text area here                                                                                           
    </div>
</ox:decorate> 
```

**Comment by yurem** [comment]
We can either provides text area or file upload button for this

**Comment by yurem** [comment]
Implemented
