### ISSUE TITLE
Relaying party profiles are missing. 

### ISSUE THREAD

**Issue by kevin-8387** [GluuFederation/oxTrust#752]
Hello,
I am using GLUU 3.1.0 on centos 6.7 and when I am adding/editing trust relationship and try to configure replaying party popup shows only three option which all are SAML2SSOProfile, SAML2AttributeQueryProfile and SAML2ArtifactResolutionProfile.
How I can enable other missing profiles.

**Comment by mzico** [comment]
Github is only for feature request or bug report. Please use our support portal ( https://support.gluu.org ) for any kind of question or assistance.
