### ISSUE TITLE
GUI issue - 3.1.1 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#753]
Screenshot attached: 

- A comparatively big names [ without space ] are hiding  { Check eduPersonPrincipalName } 
- ":*" signs are not aligned properly for some attributes
- There is a weird "+/-" sign there. 

![screenshot_3](https://user-images.githubusercontent.com/7156097/31726607-1812a564-b3ed-11e7-8d1c-0e33d08d2a3e.png)

**Comment by shekhar16** [comment]
@mzico +/- links are for multi valued attributes. 
Here are some changes I made for above 2 points.
Please take a look and let me know.
![image](https://user-images.githubusercontent.com/15937500/32146491-5d3911a4-bcfe-11e7-93ae-d9a211c0b6b3.png)
