### ISSUE TITLE
Unable to add attributes via Attributes Filter

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#754]
Package: gluu-server-3.1.1.x86_64 1-8.centos6
Steps to reproduce: 
1. Enable User Registration Script
2. Add Attribute Filter from Manage Registration
![registration-attribute](https://user-images.githubusercontent.com/7703245/31739325-68082974-b445-11e7-91bb-6fde14adcac2.png)

2. Check user registration page to find that the attribute does not show up in the registration page
![register-people](https://user-images.githubusercontent.com/7703245/31739351-7dc48032-b445-11e7-8be5-cc481deea66d.png)

**Comment by shekhar16** [comment]
@zamilskhan I think you are trying with inactive attribute to add in registration form.Inactive attribute are will not be added in the form as they are not eligible for this.
You can try it by making the "mobile" attribute active from Configuration > attributes page.

here is the snapshot after making mobile as an active attribute and getting this attribute in registration form.
![image](https://user-images.githubusercontent.com/15937500/32993912-607cecd6-cd85-11e7-936b-8b7e75b8c199.png)

**Comment by shekhar16** [comment]
I m closing this issue for now.
If you found any issue Please let me know and reopen it.
