### ISSUE TITLE
Manage People: Incorrect Label on email address field. 

### ISSUE THREAD

**Issue by mferry4act** [GluuFederation/oxTrust#756]
When I click on Manage People and then search for a user I receive the following screen. 

![gluuwronglabel](https://user-images.githubusercontent.com/26067753/31830014-938facf8-b584-11e7-8572-2756e331ace3.PNG)

The "Status" label over the email address is wrong.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/31862382-a8a5ef76-b75a-11e7-831a-31a0fc3ada1c.png)
