### ISSUE TITLE
Import People: User Status

### ISSUE THREAD

**Issue by mferry4act** [GluuFederation/oxTrust#757]
Using a XLS file that has the following columns to import users: 

Username, First Name, Last Name, Email, Password, User Status 

User statuses are not being imported.    I have checked the attribute for User Status in order to make sure that I have the correct column name, and as far as I can tell the column name is correct.

**Comment by shekhar16** [comment]
@mferry4act There is no column for user status in xls sheet to import user functionality.
Initially the user is inactive.

**Comment by mferry4act** [comment]
@shekhar16 Looking through past tickets.   Wasn't this feature added with the following?

https://github.com/GluuFederation/oxTrust/issues/171


Thanks.

**Comment by rajnikantsh** [comment]
created pull request https://github.com/GluuFederation/community-edition-setup/pull/359.

**Comment by sahiliamsso** [comment]
It's still failing when providing User Status value in spreadsheet. .

**Comment by yurem** [comment]
Fixed
