### ISSUE TITLE
"JSON configuration -> oxTrust" page/tab contains field no longer being used

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#759]
The field's name is `scimTestModeAccessToken`. According to Jose, "we removed the long-lived access token approach for a series of reasons". Better to remove the field as well (and corresponding element of configuration JSON object in LDAP) to prevent confusion.

**Comment by willow9886** [comment]
cc @jschristie

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/013fe1f2733c426f1aa3f063fb450e5b7d8fdbec

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/32065630-e9801ac4-ba9a-11e7-9c40-10cef552a229.png)
