### ISSUE TITLE
Expose API's for everything

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#762]
If we expose API's for oxTrust, it will be easier for customers to build their own configuration UI's.  API's should be protected with different UMA scopes depending on the security implication.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/oxTrust/projects/2

I created a project board so we can discuss potential frameworks and also discuss scope of the project.

**Comment by willow9886** [comment]
Breaking into four separate issues:

https://github.com/GluuFederation/oxTrust/issues/783

https://github.com/GluuFederation/oxTrust/issues/784

https://github.com/GluuFederation/oxTrust/issues/785

https://github.com/GluuFederation/oxTrust/issues/786
