### ISSUE TITLE
Add new default designs for U2F, OTP, and SMS OTP auth pages

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#767]
All html/css code files can be found [here](https://drive.google.com/drive/folders/1v_AidVtMOKiVyN86vYC4XtW0gO2BXal7).

## U2F

- existing page: https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/webapp/auth/u2f      

- new design: http://ec2-13-59-108-255.us-east-2.compute.amazonaws.com/verification/2-step.html      

## OTP App

- existing page: https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/webapp/auth/otp

- new design: http://ec2-13-59-108-255.us-east-2.compute.amazonaws.com/verification/verification-mobile.html

## SMS OTP

- existing page: https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/webapp/auth/twiliosms

- new design: http://ec2-13-59-108-255.us-east-2.compute.amazonaws.com/verification/verification-code.html

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33064086-93bbec3c-ceca-11e7-8207-ac42cbd2b29a.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/pull/698/commits/9e8d68adcb9c6a9f71b50ac96501511cda21b168

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33079026-809ecd92-cefa-11e7-8116-bbd0ac117796.png)

**Comment by willow9886** [comment]
@shekhar16 the design on this second one doesnt look totally accurate.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33111501-77284b7e-cf74-11e7-9ce0-d04e59feb955.png)

**Comment by willow9886** [comment]
@shekhar16 the spacing between the logo and the line is too large. See my screenshot below.

![image](https://user-images.githubusercontent.com/5271048/33132021-fa2bd0fc-cf5d-11e7-84b8-9412174d8a17.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/33466881-d083b40c-d676-11e7-9a7d-ecbabddf1b0d.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxAuth/commit/9af79cd8e1720b23c786a303d09fc8cc1a2848ba

**Comment by shekhar16** [comment]
Fixed.
