### ISSUE TITLE
Replace Richfaces with JSF2 and other JSF frameworks

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#768]
There are few points about this;

1. Richfaces is not under active development.
2. JSF 2.2 allows to replace big part of Richfaces functionality.
3. We are planing to use new framework for GUI and Richfaces can conflict with it.
4. We have to use old jQuery and morris libraries due to Richfaces dependency.

Also we can use in https://github.com/GluuFederation/oxTrust/issues/746 JSF2 as templates due to Richfaces dependency.

**Comment by yurem** [comment]
It's time consuming issue. We can continue work on it in 4.0.0

**Comment by syntrydy** [comment]
@yurem we can move this to 4.0 release

**Comment by yurem** [comment]
It's very urgent issue

**Comment by shmorri** [comment]
This is no longer necessary since oxTrust is being replaced

**Comment by sectestaccount** [comment]
Hi, 
morris 0.5.0dependency is still present:
https://[domain.com]/identity/theme/plugins/morris/morris.min.js
There is a newer version: https://morrisjs.github.io/morris.js/
