### ISSUE TITLE
[Bug][Functional][ManageCustomScripts] "Cross button" won't close new script UI section until any character is put into "Name" field

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#77]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.2

Steps to reproduce:
1) Login into oxTrust web UI
2) Move to the "Manage Custom Scripts" page
3) Click "Add custom script configuration" link on any tab here
4) Click "cross button" at the top-right corner of the UI section for the new script

Result: Section isn't removed, notification is displayed notifying that "Name" field is mandatory; it's can be finally removed only after any character is placed in the field (see attached screenshot)

Expected result: Section is immediately removed; in case user already has submitted some input to any its field he is notified about possible data loss and is asked to confirm the action.

![26 06](https://cloud.githubusercontent.com/assets/11802046/8367810/e3176e30-1baa-11e5-8d59-8a5568c95183.png)

**Comment by mzico** [comment]
@aliaksander-samuseu : Just refresh the page.

**Comment by aliaksander-samuseu** [comment]
This bug appears again in 2.4.3-1-3. Just click add script button and try to immediately close the new script form.

**Comment by shekhar16** [comment]
Fixed.
