### ISSUE TITLE
UMA Scope is not editable after image upload

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#770]
1. Create UMA Scope
2. Upload image to Scope and click "Update" button.
3. Try to change name of the scope 
It's not possible, oxtrust always shows error page.

https://support.gluu.org/access-management/4790/upload-picture-to-uma-scopes/

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/4b9b57f8152239a6d6b73601a327800f1efbe0cf

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/33467188-b6662882-d678-11e7-9c1a-7bc6763289ec.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/b0e2cd69dc056621896a60ce631fc1434ee61149
https://github.com/GluuFederation/oxTrust/commit/0a3869f4dc977cb0c8e4d321d25ca68db4a3611d

**Comment by rocklyve** [comment]
Tested upload via Webinterface and it has worked. 
Thank you very much.
But I didn't get a download link, is there another bug?
![selection_005](https://user-images.githubusercontent.com/11009552/33717509-7c0f7260-db5a-11e7-8317-dacdff7b2702.jpg)
Adding a uma scope via a post request has worked (_http://photoz.example.com/dev/scopes/view scope_).

**Comment by willow9886** [comment]
@shekhar16 can you look into the above report?

**Comment by shekhar16** [comment]
Added id fields on ui 

![image](https://user-images.githubusercontent.com/15937500/35622470-f621ec76-06ad-11e8-88cf-4d2d0e35bc1d.png)

**Comment by yuriyz** [comment]
@shekhar16 : 
1. is it possible to add tooltip with hints for "Id:*" field? Because for end-user it may be not intuitive what to enter there. Tooltip can be: "Scope id, for example: `edit`, `add`, `http://rs.com/scope/view` "
2. Please remove "*" sign from Display name, display name is optional and user can left it blank. If user left it blank Display name should fallback to id field (oxId ldap attribute).

**Comment by shekhar16** [comment]
1) I added tooltip for id
2) @yuriyz  in oxauth code we had required validation for display name  i.e. .https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/uma/persistence/UmaScopeDescription.java#L37

**Comment by yuriyz** [comment]
@shekhar16 ok, lets drop it in next version then.
