### ISSUE TITLE
Import People: Import Failed, there are simular UID's in the Input File

### ISSUE THREAD

**Issue by mferry4act** [GluuFederation/oxTrust#778]
We are attempting to import users into our gluu server (3.1.1) , and have successfully imported 27,000+ users.   We have one final import block that we are trying to import of around 6000 users.  Whenever we try to validate the file we receive: 

Import Failed.  There are persons with simular uid(s) in the input file.  

Using basic sampling (1 user every few hundred) and the Manage People search function I have been unable to locate any of these users from this last import in the database. 

I have even reduced the import file down to just the first 10 users on the file, and have verified that none of these users are in the database.   Yet even this list of 10 users receives this error.  

Would appreciate any additional insights that may be available regarding this "bug", it appears very similar to https://github.com/GluuFederation/oxTrust/issues/102  , but that ticket is 2 years old and has been marked as closed for some time.

**Comment by nynymike** [comment]
You'll have to move this issue to the Gluu Support site, because it's not clear if it's a bug. Please register and post on https://support.gluu.org
