### ISSUE TITLE
Dropdown for Scope Type : "dynamic" or "ldap"

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#78]
We should extend the schema of the schema of the LDAP entry oxAuthCustomScope to include 
"oxScopeType" attribute. The current valid values are "ldap" or "dynamic"

The UI should enable selection of the oxScopteType as "type: " + drop down of available types.

![image](https://cloud.githubusercontent.com/assets/3717101/8411720/0a2394fc-1e4b-11e5-8c81-aea536a0df0a.png)

**Comment by yurem** [comment]
Resolved
