### ISSUE TITLE
Prepare working prototype which demonstrates oxTrust API

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#784]

**Comment by dmogn** [comment]
@yurem  Technically speaking, I think that API should be a set of statefull/stateless session beans, which wrap 
org.gluu.oxtrust.action.*
org.gluu.oxtrust.ldap.service.*
beans.

It is easy to expose session beans to XML or REST WS just with JEE annotation adding.
JS-based UI can use web services.
And JSF-based UI can use these session beans directly in expressions. 

Am I right?

**Comment by dmogn** [comment]
And we going from "light profile" to JEE application server features.

**Comment by yurem** [comment]
We can use JEE in this task. Even "light profile" requires Application Server. This is from Jetty docs:
```
JSR 339 | Java API for RESTful Web Services 2.0 (JAX-RS) | No
```

**Comment by yurem** [comment]
We use RESTEasy and CDI in oxAuth/oxTrust already. And this combination works well. I offer to continue use them for this task too.

**Comment by yurem** [comment]
Also our main target point is to allow developers write custom GUI for oxTrust. Or integrate it in own admin applications.
