### ISSUE TITLE
Cover all oxTrust GUI by oxTrust API 

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#785]
Using sample from issue #784

**Comment by dmogn** [comment]
@willow9886  We could divide the issue to these subtasks (following the existing UI structure):

SAML - TrustRelationship API
SAML - Asimba API
OpenID Connect API
UMA API 
CAS API
Users API - Groups
Users API - People
Personal profile API
Orgagization profile API
Authentication Method API
Attributes API
Certificates API
Custom Scripts API
Registration API
OxTrust configuration API
OxAuth configuration API
Server Status API
Server Log API

Every subtask is relatively short and easy traceable,
