### ISSUE TITLE
Activate/Deactive LDAP server feature of "Manage authentication" page is broken

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#789]
Related ticket: [https://support.gluu.org/authentication/4877/something-went-wrong-while-deactivating-ldap-authentication/#at28263](https://support.gluu.org/authentication/4877/something-went-wrong-while-deactivating-ldap-authentication/#at28263)

Created per Yuriy's request, as he confirmed there was an error is code (should be fixed in next re-assembled 3.1.2 beta package)

**Comment by yurem** [comment]
Fixed in https://github.com/GluuFederation/oxTrust/commit/d3894d757e652a4e96ee10cb20b9b06a7d342b35
