### ISSUE TITLE
Erratic behavior on the add user form

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#792]
A summary of things experimented:

After login, clicking on manage people -> add user. Filled all fields and despire password and confirm password are the same, I got error in red saying that passwords do not match. So I cleaned both fields enter passwords again and after pressing "add" I am taken to the 
"Oops
The form was removed after 30 minutes of inactivity 
Return to the application using below button."

But I am doing the steps quickly one after the other, so there is no inactivity

Try to add the user again, but it says user already exists so (and I confirmed the user was created indeed after pressing "add button")

Try to add a different user, and no problem.

Then try to add a new one, and forgot to supply e-mail so I am warned. After filling in the e-mail and pressing "add" I get an error as shown below.

![sin titulo](https://user-images.githubusercontent.com/5444180/33999973-fa4b99ec-e0b9-11e7-991c-89e2c66e03f8.png)

Then I try to click on clicking on manage people -> add user to start all over again, but the error is stuck there...

**Comment by jgomer2001** [comment]
[2017_12_14.stderrout.log.txt](https://github.com/GluuFederation/oxTrust/files/1560489/2017_12_14.stderrout.log.txt)

Here is a log excerpt

**Comment by shekhar16** [comment]
@jgomer2001  i fixed the email issue.Here is the snapshot.

![image](https://user-images.githubusercontent.com/15937500/34069658-5464607c-e27b-11e7-94d1-5acc67514137.png)

 but couldn't able to replicate the first scenerio.

**Comment by yurem** [comment]
@jgomer2001 please reopen it if neded
