### ISSUE TITLE
Wrong (auto-generated) SAML2 attribute's name is displayed in web UI instead of explicitly supplied one

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#795]
Environment:
CentOS 7.4.1708, gluu-server-3.1.1-1-2.centos7

Preconditions:
1. Custom attribute "customTestNew" is already added to scheme (all what is left is to register it in web UI)

Steps to reproduce:
1. Log in to web UI as admin
2. Proceed to "Configuration -> Attributes", click "Register attribute"
3. Use "customTestNew" for "name"/"display name",  `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname` for "SAML2 URI", leave "SAML1 URI" empty and  provide any  values for the rest of mandatory fields, then click "Register" button

Result:
Attribute is registered overall successfully. "SAML1 URI" - which was left empty - is assigned autogenerated value, but "SAML2 URI" - which was assigned value explicitly - shown in web UI as if it has been assigned autogenerated value as well, though it's clear from its configuration entry in LDAP that in fact it was assigned the explicitly set value:
![wrong_saml2_name](https://user-images.githubusercontent.com/11802046/34232088-c4c14b4c-e5ef-11e7-9ace-1d50ff96b51f.png)
If this attribute is edited and saved after initial creation, the wrong SAML2 name will actually be persisted to LDAP.

**Comment by aliaksander-samuseu** [comment]
The interesting part is that "SAML1 URI" doesn't behave like that, only "SAML2 URI" does

**Comment by shekhar16** [comment]
@aliaksander-samuseu  Please verify it with latest build.
I m closing the issue for now and please let me know if you found anything on that and reopen the issue.
