### ISSUE TITLE
Cache Refresh Update Timezone

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#796]
Package: gluu-server-3.1.2.x86_64 0:3-1RC2.centos6
Steps to reporduce: 
1. Install gluu-server-3.1.2
2. Configure and start cache refresh
3. Change Timezone
4. Restart gluu-server
5. Check the cache refresh last updated time
The time will still show in UTC even after changing the timezone to Chicago.

**Comment by shekhar16** [comment]
@mzico @zamilskhan  this is because we storing this value in ldap whenever the update occurs the time will be stored in ldap.

**Comment by yurem** [comment]
@zamilskhan Can you explain where we need to check this
>>Check the cache refresh last updated time
>>The time will still show in UTC even after changing the timezone to Chicago.

**Comment by willow9886** [comment]
Closing this. If it becomes an issue we can reopen.

**Comment by mzico** [comment]
I can see this problem in 3.1.2. Timing should represent the local VM timing; not GMT.

**Comment by shekhar16** [comment]
Fixed.
in my environment cache refresh last run value is Mar. 13 2018 03:12 PM (UTC) is converted to Tue Mar 13 2018 20:42:00 (local timezone).
Here is screenshot.
![image](https://user-images.githubusercontent.com/15937500/37553646-27f2e8d8-29f2-11e8-8ee9-231d89deb088.png)
