### ISSUE TITLE
[Bug][Functional][Attributes]"System error" result on attempt to view "Work Telephone Number" attribute's properties

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#80]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Login into oxTrust web UI
2) Move to the "Attributes" page
3) Click "Work Telephone Number" link to view corresponding attribute's properties (you may need to switch to "Show All Attributes" mode in case it was made inactive)

Result: user is being redirected to IdP's home page and error message stating "System Error. Please try again or contact a Gluu administrator for help" is displayed (see screenshot below)

Expected result: user is being redirected to page listing attribute's properties.

![08 07](https://cloud.githubusercontent.com/assets/11802046/8579319/8d93336a-25bc-11e5-9bf5-a7ced055bb52.png)

**Comment by yurem** [comment]
According to attribute definition it should belong to inetOrgPerson. But according OpenDJ definition there is no this attribute in
objectClasses: ( 2.16.840.1.113730.3.2.2 NAME 'inetOrgPerson'
  SUP organizationalPerson STRUCTURAL MAY ( audio $ businessCategory $
  carLicense $ departmentNumber $ displayName $ employeeNumber $ employeeType $
  givenName $ homePhone $ homePostalAddress $ initials $ jpegPhoto $
  labeledURI $ mail $ manager $ mobile $ o $ pager $ photo $ roomNumber $
  secretary $ uid $ userCertificate $ x500UniqueIdentifier $
  preferredLanguage $ userSMIMECertificate $ userPKCS12 ) X-ORIGIN 'RFC 2798' )

Can we use for example telephoneNumber from person OC in attribute defintion?

**Comment by nynymike** [comment]
I never heard of the attribute workTelephoneNumber either... telephoneNumbe is fine.

**Comment by willow9886** [comment]
@rahatjaan also offered a work around for this issue on trello:

"Workaround for this issue is to add a 'custom attribute' named 'workTelephoneNumber' in the schema through OpenDJ control panel."

**Comment by yurem** [comment]
I changed attribute definition. But I think we should make one improvement.
Current person entry contains only 3 OC: gluuPerson, top, ox-XYZ (for dynamic attributes)

As result our attributes list not conform OC specified in person entry. For example: roomNumber, secretary, etc.

What do you think if we will add 'person' or 'organizationalPerson' or 'inetOrgPerson' to default list of person OC ?
Or we can do that without updating code. gluuPerson can extend one of the mentioned OC above.

What do you think?

**Comment by nynymike** [comment]
The reason I don't want person is because it throws a lot of errors because 'cn' and 'sn' are required. I'm ok with adding organizationalPerson and inetOrgPerson.

**Comment by yurem** [comment]
I agree about 'person' object class. It will add bugs in random places.

We can't add even organizationalPerson and inetOrgPerson because:
inetOrgPerson SUP organizationalPerson SUP person!

What do you think about adding all attributes defined in attributes.ldif to gluuPerson?

Without this we will get similar issues from time to time.

**Comment by nynymike** [comment]
That's an idea... or we can add in our code to always make sure that cn and sn is populated...

**Comment by yurem** [comment]
Mandatory cn and sn can led to issues in SCIM. Also I know that in CR in pre CE version this was an problem because in AD server not all user entries have sn.

**Comment by nynymike** [comment]
ok, then let's go with your idea to add more attributes to gluuPerson

**Comment by yurem** [comment]
We have to add next attributes (from inetOrgPerson and eduPerson) to gluuPerson:

title carLicense facsimileTelephoneNumber departmentNumber employeeType mobile telephoneNumber manager postOfficeBox employeeNumber preferredDeliveryMethod telephoneNumber roomNumber secretary homePostalAddress
 postalCode description eduPersonAffiliation eduPersonNickName eduPersonOrgDN eduPersonOrgUnitDN eduPersonPrimaryAffiliation eduPersonPrincipalName eduPersonEntitlement eduPersonPrimaryOrgUnitDN eduPersonScopedAffiliation eduPersonTargetedID eduPersonAssurance

**Comment by yurem** [comment]
It will make gluuPerson very complex :(

I think there is more sophisticates and more accurate approach.
We can change gluuStatus of this attributes to false by default.
And during enabling attribute we can do next:
1) Check if attribute exist in server schema
2) Prompt user to use existing attribute
3) If user agree to use existing attribute we should add it to custom object class and change gluStatus to true
4) If user disagree we should tell him that this attribute already exists and don't allow to enable gluuStatus unless he will specify other attributeName which application can add.

**Comment by nynymike** [comment]
ok by me.

**Comment by yurem** [comment]
Latest oxTrust add to custom object class attribute if it defined already. It do that during add and update.
@aliaksander-samuseu if you are going to retest it now you should manually remove gluuLdapAttributeName from attribute entry to avoid errors.

In 2.4.0 there is no gluuLdapAttributeName that's why we should remove it manually.
