### ISSUE TITLE
Protect oxTrust apis by UMA

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#803]
1. oxTrust already uses UMA to protect SCIM and Passport endpoints. We ref-factored UMA services some time ago and now both endpoints uses same services. For /apis we only need to implement new class like this [ScimUmaProtectionService](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/uma/ScimUmaProtectionService.java).

2. We need to add filter like [this](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/auth/AuthenticationFilter.java). It should intercept all calls to /restv1/apis and call UMA RPT validation api. This should protect all /apis endpoints. Later we need to move SCIM and Passport UMA validation from endpoints to this filter too.

3. For each /apis/group_id like /apis/saml we need to register UMA resource with few scopes like:
https://(domain name)/auth/oxtrust.allow-saml-config-all

4. In AuthenticationFilter we need to check if RPT is associated with right resourceId and set list of allowed RPT scopes in request scoped bean. oxTrust API endpoint should check if there is scope in this bean before process request.

Instead of 2 and 4 we can use more modern OOP/CDI based solution like:
```
     @GET
     @Path("/read/{inum}")
     @Produces(MediaType.APPLICATION_JSON)
@UmaSecure("#{umaPermissionService.hasScope("apis_saml", '/auth/oxtrust.allow-saml-config-all', '/auth/oxtrust.allow-saml-modify-all'...)}")
public String read(@PathParam("inum") String inum, @Context HttpServletResponse response) ...

```

In this annotation interceptor method can get from request Authorization header and call RPT endpoint to get list of allowed permissions, validate them and allow or not execute intercepted method.

In oxService there is annotation @Secure which you can use as reference. I can write prototype if needed.

**Comment by dmogn** [comment]
The related issue: https://github.com/GluuFederation/oxTrust/issues/783

**Comment by yurem** [comment]
After step #4 I added one solution which will make permission checking code less and very clear.
