### ISSUE TITLE
Manage Registration doesn't pull up attributes list

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/oxTrust#806]
When i click on configure registration form attributes, Attributes appears at the bottom, but the list is empty. I have to type in the Attributes filter box to bring the list, however. When i enter search or add, it gives me with one attibutes "cn" first, then if i re-type again. I get the whole list of attributes.

**Comment by jschristie** [comment]
for your reference, i am attaching few screenshots

before entering
![image](https://user-images.githubusercontent.com/23150138/34653713-ddf55408-f415-11e7-8cb3-1d14c9f2162a.png)

After entering first time

![image](https://user-images.githubusercontent.com/23150138/34653735-22eaf9f0-f416-11e7-8146-1d6cb4db36bc.png)

after re-entering and deleting 

![image](https://user-images.githubusercontent.com/23150138/34653754-9abdf9aa-f416-11e7-805f-2bfb93c7129d.png)

**Comment by yurem** [comment]
Now it should display full list if there is no search filter
