### ISSUE TITLE
Remove UMA > "Add Resource" Button 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#808]
Remove the "Add Resource" button here:

![image](https://user-images.githubusercontent.com/3717101/34691646-e43f41bc-f482-11e7-9bf1-f69f72c1ebe2.png)

**Comment by yuriyz** [comment]
@nynymike does it make sense to leave the details page for scope_expression case? Expression can look not very nice in the table row because it can be huge, so I assume we would need to show starting part of the expression and then on details page show complete details.

**Comment by willow9886** [comment]
Updated Mikes comment to reflect @yuriyz comment.

**Comment by shekhar16** [comment]
fixed.
![image](https://user-images.githubusercontent.com/15937500/34733816-b22068ce-f58f-11e7-8195-fac81144bec7.png)

**Comment by yurem** [comment]
There is replacement for this:  oxd and UMA API. But why we don't allow to add resource set manually? It's convenient for case when user is starting to use UMA.

**Comment by R-Gerard** [comment]
The documentation for `3.1.2` still refers to the "Add Resource" button:
https://gluu.org/docs/ce/3.1.2/admin-guide/uma/#add-resource

**Comment by yurem** [comment]
@nynymike can we restore this button back?

**Comment by Adrian-A** [comment]
@nynymike - adding the UMA Add Resource Button back would be useful for evaluation purposes.

**Comment by nynymike** [comment]
I guess if you really want to create the resource centrally, it's ok.

**Comment by nynymike** [comment]
Create resource requires a PAT, so there is an associated client:
https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-federated-authz-2.0.html#create-rreg 

And you can see this associatedClient attribute:
 https://gluu.org/docs/ce/3.1.3/reference/schema/#oxauthumaresourceset

So if we enable this feature, we also need a way to allow the person to associate this scope with a client, otherwise would another client even be allowed to see the resource set?

**Comment by yuriyz** [comment]
I agree, we can add it back but then resource should be associated with the client because otherwise it will be filtered out if client will try to fetch it.

**Comment by shekhar16** [comment]
Add Resource set button is added again here is screenshot.
![image](https://user-images.githubusercontent.com/15937500/40873863-a7812c70-6685-11e8-9ff7-c327387fdf04.png)

**Comment by nynymike** [comment]
Shekhar, did you add the requirement that resources sets have to be associated with a client? (per my comment on 5/31)

**Comment by yuriyz** [comment]
oxAssociatedClient should point to client entity DN. See https://github.com/GluuFederation/oxAuth/blob/1f2f944e154c0c3145051a000edab83c9f1ef758/Model/src/main/java/org/xdi/oxauth/model/uma/persistence/UmaResource.java#L51

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/41058460-8090a482-69e7-11e8-9e3c-6c76807658d6.png)


![image](https://user-images.githubusercontent.com/15937500/41058485-927c475a-69e7-11e8-9cef-ef33700bc6ad.png)

**Comment by nynymike** [comment]
When you enter search text, oxTrust does a substring search on displayname or clientid? If so, it looks good.

**Comment by shekhar16** [comment]
its searching on both display name and inum both.here is snapshot for inum searching.
![image](https://user-images.githubusercontent.com/15937500/41113690-efe42670-6a9f-11e8-9f92-510d75acb15a.png)
