### ISSUE TITLE
Make Sector Identifier GUID instead of INUM

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#809]
![image](https://user-images.githubusercontent.com/3717101/34692239-16cce614-f485-11e7-870e-47697833d822.png)

It would be better if the sector identifier was a GUID not an inum. No advantage to an inum here.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/34833913-90616e8a-f716-11e7-9474-247ab41051ab.png)

**Comment by shekhar16** [comment]
There is no GUID present in record set for sector identifier.

**Comment by yurem** [comment]
@nynymike We can replace inum=XYZ!XYZ... with oxId=GUID Is this what you expect?

**Comment by nynymike** [comment]
That would be fine.

**Comment by yurem** [comment]
Implemented
