### ISSUE TITLE
[Bug][Functional][Federations]"Delete" button isn't deactivated in the editor during new federation's creation

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#81]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Log in to oxTrust web UI
2) Move to the "Federations" page
3) Click "Add federation" link to open federation editor
4) Note that "Delete" button is present and active; press the button and confirm the deletion in pop-up dialog that will appear

Result:
Deletion is actually tried, resulting in error message "System Error. Please try again or contact a Gluu administrator for help." (see attached screenshot)

Expected result:
The button shouldn't even be there, it can't have any purposes in this context; at least it should be grayed out.

![fed_delete_button](https://cloud.githubusercontent.com/assets/11802046/8682361/4bdfab0c-2a75-11e5-91d5-ef146abff2c1.png)

**Comment by mzico** [comment]
Federation is not our concern now.
