### ISSUE TITLE
Add Scope Description --> Add Scope

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#810]
![image](https://user-images.githubusercontent.com/3717101/34693442-28e09b4e-f489-11e7-9e22-d6cb722cbe78.png)

The button text should be simply "Add Scope"

**Comment by shekhar16** [comment]
fixed.
![image](https://user-images.githubusercontent.com/15937500/34736438-f17b6ef2-f598-11e7-928f-4c985111c3ea.png)
