### ISSUE TITLE
Show Modality accordign to requirement

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#815]
We need to find way to get data to display Modality according to this requirement:
https://github.com/GluuFederation/oxTrust/issues/814

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/40131475-b7e8ce32-5957-11e8-8d19-4360874ed3c1.png)

**Comment by willow9886** [comment]
In your screenshot, what is the string in the modality field for totp and
u2f devices? Modality indicates the type of device or mechanism in use, it
should be human understandable.

**Comment by shekhar16** [comment]
@willow9886  the 2 fields which were displayed in above screen shot is for other authentication methods which are stored in oxexternaluid, I think this related to passport #814.
For these method we only had auth_method_id and auth_method_details in format i.e. oxExternalUid: auth_method_id:auth_method_details

**Comment by willow9886** [comment]
@shekhar16 i see, I still think we need human readable descriptions for modality. If it's authentication at an external IDP via Passport, can we list the external provider, e.g. Facebook, Google, etc. ? If not, then we should discuss our options. Please ping me on Rocket ASAP to discuss.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/40596773-b65dce1c-625a-11e8-8ee4-33f273461154.png)

**Comment by shekhar16** [comment]
@willow9886 we added all devices there available values.
super gluu ,u2f devices ,otp devices and mobile devices.

**Comment by willow9886** [comment]
@shekhar16 where did the `nickname` values come from for the two `Passport` entries?

**Comment by shekhar16** [comment]
@willow9886 its the initial part of oxexternalUID attribute like 
for Oxexternaluid = passport-saml:alex.samuseu@yandex.ru,  the nickname value is passport-saml

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/40666397-39a25c02-637d-11e8-808c-35f16a4d982d.png)
