### ISSUE TITLE
Multi value Gluu Person attribute  delete  clears all value  

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxTrust#818]
This issue is in Gluu Server 3.1.1 and 3.1.2 

In oxTrust edit user page, you can add multiple user permission fields and values. However, if you click the `x` for one field, all fields are removed. 

See before and after screenshots below:

![image](https://user-images.githubusercontent.com/5271048/35116520-5d5f3798-fc51-11e7-86a8-847ebf2a72ee.png)

![image](https://user-images.githubusercontent.com/5271048/35116531-67edaae6-fc51-11e7-9045-3d22c4f34114.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/35346572-9b846c44-0158-11e8-9c3d-17a9c5dbd51c.png)

**Comment by shekhar16** [comment]
Fixed.
