### ISSUE TITLE
[Bug][Functional][SAML]Ability to modify module's settings is lost on attempt to add attribute to the "Released" list

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#82]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Log in to oxTrust web UI
2) Move to the "SAML" -> "Trust relationships" page
3) Click "Add Relationship" link to open relationship editor
4) Put some valid values into "Display Name" and "Description" fields
5) Select "URI" method from the "Metadata Type*" dropdown.
6) Put any of the 2 links below into "Sp Metadata URL" field:
https://shib.alexanderstreet.com/Shibboleth.sso/Metadata
https://ib213.tmit.bme.hu/Shibboleth.sso/Metadata
(You can also use File method and provide their downloaded metadata manually)
7) Add "Inum" or "Email" attribute to the "Released" list (most likely any other will do too)
8) Click "Add" button

Result1:
Browser is "stuck" in endless loading loop, then after several minutes "Internal server error" error page is displayed; after that any deletion, addition or update operation for this module won't succeed until Gluu server is restarted (it just looks like browser is loading page for several minutes, then either nothing happens, or another error page is displayed); the same result will occur on any attempt to add attribute to the list, be it new, or already existing SAML relationship.

Optional steps:
9) If browser's "Back" button is clicked, then, depending on browser, you'll be taken to the previous page where oxTrust's main menu will be accessible
10) Select "SAML' -> "Trust relationships" again from the menu

Result2:
Java exception page should be displayed; reload page once more (by pressing F5 key) and this time you should be able to access the UI (see attached screenshot)

![saml-trusts-release-attrs](https://cloud.githubusercontent.com/assets/11802046/8688422/a9848c9e-2aa4-11e5-8872-0439720acfb7.png)

**Comment by mzico** [comment]
@aliaksander-samuseu : I couldn't reproduce the problem with 2.3.3. Used 'File' method to upload the metadata file, added 'mail' and 'inum' attributes, removed 'mail' attributes and removed trust relationship; all worked for me. 

Generally, this 500 error appears if IDP can't resolve SP's hostname ( i.e. SP is not reachable from Internet or some firewall issue in SP server ). 

Please feel free to open new ticket if you face this issue and include stack trace from wrapper.log.
