### ISSUE TITLE
Validate custom scripts

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#821]
Based on this ticket, https://support.gluu.org/authentication/4999/312-bug-in-saving-custom-scriptssaving-bad-scripts/ , Custom scripts should be checked for syntax/errors in the UI itself rather waiting several seconds for exception to appear in the oxauth_scripts log.

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/36865926-f712ecf6-1da1-11e8-8c3c-49b61d85b94d.png)

**Comment by yurem** [comment]
This update add new button to script panel. It shows this button only if script has error at loading or methods execution. It display first error occurred error. This panel uses ajax to pull data from oxTrust every 10 seconds.

**Comment by sahiliamsso** [comment]
Please fix the button alignment

![image](https://user-images.githubusercontent.com/21104811/37740409-9d85f330-2d83-11e8-9447-904f3b879923.png)

**Comment by yurem** [comment]
Fixed
