### ISSUE TITLE
Add inum and ppid to people search

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#824]
You can't search on inum or ppid. This would be helpful. 

![image](https://user-images.githubusercontent.com/3717101/35455189-9eadc61a-0296-11e8-9c62-00146cfb313c.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/35480210-68e99488-042f-11e8-8b13-1e1865a0315e.png)

**Comment by shekhar16** [comment]
added search for inum and oxppid.
