### ISSUE TITLE
Rename "Client Secret Expires" web UI control

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#826]
It was pointed out by an user that name of this control may be misleading as upon reaching this date client will be removed, what is not something one will expect from a "password expiration" feature. Usual behaviour in such case would be to disable the entry, not remove it. From the other standpoint, I believe it's implemented like this to help with managing of dozens dynamic client registrations, removing stale ones automatically. Won't it be better to rename it to something like "Client's registration expires" instead? Will be less confusing, at least.

**Comment by mzico** [comment]
+1

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/37132801-c2cf4714-22b5-11e8-8840-d217bd2b4fba.png)
