### ISSUE TITLE
'Server Status' report

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#83]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Log in to oxTrust web UI
2) Move to the "Configuration" -> "Server status" page
3) Note the values shown by different counters here.
4) Try to restart the Gluu server, or the host server itself and repeat steps 1-3, observing the differences.

Result:
Values of "Free memory" and "Free disk space" counters either don't seem right, or just aren't shown at all; "System uptime" counter doesn't change at all, neither instantly after refreshing the page, nor over time. (see attached screenshot)

![counters](https://cloud.githubusercontent.com/assets/11802046/8697502/155ee17c-2afe-11e5-9ed5-35e394eba21f.png)

**Comment by mzico** [comment]
Need input from @yurem and @rahatjaan on this issue. I *think* we are going to implement a new 'Server Status' feature in our new oxTrust+oxAuth. 

However, here is current status of 2.3.3 rpm: 

![server_status](https://cloud.githubusercontent.com/assets/7156097/9294555/87e51410-4416-11e5-8347-85b4633f44a8.png)

**Comment by yurem** [comment]
Fixed: d1c043af7877de881f9a5c4b3702c51f19d2890e
