### ISSUE TITLE
Bulk delete clients

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#831]
![image](https://user-images.githubusercontent.com/3717101/35782600-db38f606-09bf-11e8-8897-18baa0f0fa26.png)

Add a checkbox to allow an admin to select several clients for deletion.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36262858-9d0ed2b0-128e-11e8-913f-041cce94ceb6.png)

**Comment by yurem** [comment]
It works fine. I merged update into 3.1.3 too

**Comment by ldeveloperl1985** [comment]
Not working on my case
Environment:
OS: Ubuntu 14.04
Gluu version: 3.1.3
Install package: gluu-server-3.1.3_1.3_trusty+Ub14.04_amd64.deb
