### ISSUE TITLE
Selected menu item indication is missing in Users

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#835]
Perform following steps to reproduce,
1. Login to Gluu
2. Navigate and click on  Users menu link
3. Click on Manage Groups item link
4. Observe that selected item link(Manage group) indication is missing in the menu(Users)
5. Click on Manage People item link 
6. Observe that selected item link(Manage People) indication is missing in the menu(Users)
7. Observe that for other items(Add Person, Import People) in the Users group, selected menu item indication is present

This issue found in Gluu version 3.1.1. It also can be found in 3.1.2. Check below screens for detail information.

**Users->Manage Groups**
![1](https://user-images.githubusercontent.com/36174217/35869558-8ecd386a-0b89-11e8-9cc2-88cfdd68302b.jpg)

**Users->Manage People**
![2](https://user-images.githubusercontent.com/36174217/35869570-98be99b8-0b89-11e8-8982-5241909e2409.jpg)

**Users->Add Person**
![3](https://user-images.githubusercontent.com/36174217/35831740-f9f34b9c-0af4-11e8-9ad8-351fcd96c409.jpg)

**Users->Import People**
![4](https://user-images.githubusercontent.com/36174217/35831752-039b4492-0af5-11e8-95f4-d81575cf4e9f.jpg)

**Comment by yurem** [comment]
There is same issue in few other sections too.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36353522-8d9b1f8a-14ed-11e8-9c38-9b0cdf68943e.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36353616-a1278f10-14ee-11e8-99a9-c8928d44776f.png)
