### ISSUE TITLE
Custom Attribute Resolvers

### ISSUE THREAD

**Issue by libliflin** [GluuFederation/oxTrust#836]
Hi,

One of our service providers is very particular about the format of the attributes in the SAML assertion. To make this work we have modified `/opt/shibboleth-idp/conf/attribute-resolver.xml` while inside the chroot with XML like below. 

```
    <resolver:AttributeDefinition xsi:type="ad:Simple" id="uid" sourceAttributeID="uid">
        <resolver:Dependency ref="siteLDAP" />
        <resolver:AttributeEncoder xsi:type="enc:SAML2String" name="uid" nameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" encodeType="false" />
    </resolver:AttributeDefinition>
```

However, going into the Gluu Admin page and saving some other configuration unrelated to this service provider's attributes (like custom login scripts) causes this file to be reverted, containing attribute resolvers that do not work, causing this service provider to fail.

We are using community gluu version 3.1.2 on a 64 bit redhat.

**Comment by yurem** [comment]
Identity generates `/opt/shibboleth-idp/conf/attribute-resolver.xml` from template `/opt/gluu/jetty/identity/conf/shibboleth3/idp/attribute-resolver.xml.vm`

Hence if you need to apply persistent manual changes to `attribute-resolver.xml` you should edit source template.

Please re-open issue in support.gluu.org if you have more question about this.
