### ISSUE TITLE
Cannot Add Custom Attributes in 3.1.2 OpenDJ

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxTrust#837]
Adding custom attributes in 3.1.2 doesn't work in oxTrust. In 2.4.4, according to [this](https://gluu.org/docs/ce/2.4.4/admin-guide/attributes/) documentation shows that you can do it directly from the UI with OpenDJ. This fails in 3.1.2 w/ OpenDJ.
![image](https://user-images.githubusercontent.com/30447907/35835172-d882e982-0a9e-11e8-8e83-15ba31723e77.png)

To do it manually, from [this documentation](https://gluu.org/docs/ce/2.4.4/admin-guide/attributes/#manual-schema-management-command), create an ldif something like this:

```
dn: inum=@!C9EE.DAEE.CAB8.2B67!0001!6389.5816!0005!C701,ou=attributes,o=@!C9EE.DAEE.CAB8.2B67!0001!6389.5816,o=gluu
changetype: add
objectClass: top
objectClass: gluuAttribute
inum: @!C9EE.DAEE.CAB8.2B67!0001!6389.5816!0005!C701
description: Test
displayName: Test
urn: urn:mace:dir:attribute-def:customTest
gluuAttributeName: customTest
gluuAttributeOrigin: gluuPerson
gluuAttributeType: string
gluuAttributeEditType: user
gluuAttributeEditType: admin
gluuAttributeViewType: user
gluuAttributeViewType: admin
gluuStatus: active

```
 The inums can be found in LDAP tree under `attributes`

Then run this command:

`/opt/opendj/bin/ldapmodify -p 1636 -Z -X -D 'cn=directory manager' -w secret -f test.ldif`

Manually editing the custom schema in `/opt/opendj/config/schema/` is also unsuccessful, even with a restart.

**Comment by yurem** [comment]
Can we close this?

**Comment by nynymike** [comment]
yes, we specifically removed schema management from oxTrust. I don't even like our old solution--it used 99user.ldif which was a bad place for an organization to manage their custom schema.
