### ISSUE TITLE
[Bug][Functional][Installation]"service gluu-server restart" console command fails

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#84]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Preconditions:
Gluu server is running and fully operational

Steps to reproduce:
1) Open console and issue the following command under the root user: "service gluu-server restart"

Result:
Despite the server is stopped successfully, it's subsequent start attempt results in failure due to the fact some ports are already in use; if command "service gluu-server start" is issued after that, the server will start successfully this time; if command "service gluu-server stop" is issued, followed by the command "service gluu-server start", the issue won't occur

![gluu-restart](https://cloud.githubusercontent.com/assets/11802046/8697911/f526536e-2b01-11e5-8b03-c30f796bcb7c.png)

**Comment by mzico** [comment]
This issue should be moved to 'https://github.com/GluuFederation/community-edition-setup/issues' 
Anyone know how to move issue from one repo to another?

**Comment by willow9886** [comment]
moved to CE issues. https://github.com/GluuFederation/community-edition-setup/issues/54
