### ISSUE TITLE
Use decorator for input elements

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#843]
There are XHTML pages where we uses next pattern:

<h:outputLabel  ...
<h:inputText...

Instead of this we need to use decorator:
<ox:decorate 
   <h:inputText...
</ox:decorate 

Here is example of such conversion:
https://github.com/GluuFederation/oxTrust/commit/85e3e0b1d631a836f335af309103de3ac812d975

We need to update rest input elements in this page and check other XHTML pages too

**Comment by nynymike** [comment]
not investing in big changes to old interface
