### ISSUE TITLE
UMA Resource Registration : Scope and Scope expression are mutually exclusive

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#844]
Right now oxTrust shows both "Scopes: " and "Scope Expression". However it is MUTUALLY EXCLUSIVE.
I guess we need some flip button, like show "Scope:" by default. And button "Specify scope expression". If clicked then "Scopes:" are hided and "Scope Expression:" is shown. If clicked again then hide "Scope Expression:" and show "Scopes:". So user can edit only one given scope related field at give moment of time.

Feel free to use another approach then flip button (flip button is first that came to my mind) but idea is clear, user should be able to edit "Scopes:" OR "Scope expression:". Not both together. We must hide (make invisible one of them when the other is editing.)
![z3](https://user-images.githubusercontent.com/2013070/36040358-e05670a2-0dcd-11e8-9da5-e4906ca593dd.png)

**Comment by yurem** [comment]
Switch button looks fine. But we not used this behavior in other oxTrust form. What do you think about adding drop-down list? We use same approach in all othr forms too.

**Comment by yuriyz** [comment]
sure, drop down sounds  good too

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36350816-9362be56-14c4-11e8-8833-81fef35da841.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36350819-a7af0996-14c4-11e8-9dad-3c8e82406245.png)
