### ISSUE TITLE
SCIM interceptor script should implement postAddUser/postUpdateUser/postDeleteUser

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#845]
There are similar methods in update_user [script](https://github.com/GluuFederation/oxExternal/blob/master/update_user/sample/SampleScript.py).
We need these methods in SCIM script too.

Also we can add similar methods for group: postAddGroup/postUpdateGroup/postDeleteGroup

**Comment by yurem** [comment]
You committed code for this issue already. Can we close this issue?

**Comment by jgomer2001** [comment]
yes, closing...
