### ISSUE TITLE
NameId form should update "saml-nameid.xml" too

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#846]
According to the code it change only "attribute-resolver.xml". But it should modify also "saml-nameid.xml"

The is more information about this functionality is here: https://gluu.org/docs/ce/3.1.2/admin-guide/saml/#oxtrust-gui

**Comment by sahiliamsso** [comment]
-rw-r--r-- 1 jetty jetty     0 Mar 30 01:38 attribute-resolver.xml

Error in Logs

2018-03-30 01:38:16,148 ERROR [qtp1744347043-343] [org.apache.velocity.runtime.log.CommonsLogLogChute] (CommonsLogLogChute.java:122) - ResourceManager.getResource() parse exception
org.apache.velocity.exception.ParseErrorException: Encountered "<EOF>" at attribute-resolver.xml.vm[line 71, column 30]
Was expecting one of:
    "(" ...
    <RPAREN> ...
    <ESCAPE_DIRECTIVE> ...
    <SET_DIRECTIVE> ...


and saml-nameid.xml has this value
        <bean parent="shibboleth.SAML2AttributeSourcedGenerator"
        p:format="urn:oasis:names:tc:SAML:2.0:nameid-format:email"
        p:attributeSourceIds="#{ {'$nameIdConfig.attributeName'} }"/>

**Comment by sahiliamsso** [comment]
saml-nameid.xml file not being updated with correct attribute names.  It shows generic variable #{ {'$nameIdConfig.attributeName'} } .



    <bean parent="shibboleth.SAML2AttributeSourcedGenerator"
        p:format="urn:oasis:names:tc:SAML:2.0:nameid-format:email"
        p:attributeSourceIds="#{ {'$nameIdConfig.attributeName'} }"/>
    <bean parent="shibboleth.SAML2AttributeSourcedGenerator"
        p:format="urn:oasis:names:tc:SAML:2.0:nameid-format:email"
        p:attributeSourceIds="#{ {'$nameIdConfig.attributeName'} }"/>


![image](https://user-images.githubusercontent.com/21104811/38340276-2d2fe420-3890-11e8-9fb1-9655eee28219.png)

**Comment by yurem** [comment]
Fixed
