### ISSUE TITLE
"SAML-> Configure Custom NameId" page uses confusing names for its controls

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#847]
Naming has little to do with nameid, at some points:
![selection_089](https://user-images.githubusercontent.com/11802046/36049721-dc5c68c2-0df4-11e8-9221-dc683f2f2fc3.jpg)
Should be something like below:
"Activate NameID" instead of "Create NameID"
"Source attribute" instead of "Attribute Base"
"Nameid type" instead of "Attribute Type"
"Commit changes" or "Update" instead of "Resolve attribute"

**Comment by shekhar16** [comment]
Fixed. 

![image](https://user-images.githubusercontent.com/15937500/36070309-df482498-0f1d-11e8-81a5-73d2b2ff4ce4.png)
