### ISSUE TITLE
"Internal server error" on attempt to test SMTP connection

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#85]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Log in to oxTrust web UI
2) Move to "Configuration" -> "Organization Configuration"
3) Provide some valid settings for SMTP connection and tick the "Requires SSL" and "Requires Authentication" checkboxes
4) Click the "Test configuration" button

Result:
The browser tries to load the page for several minutes, then an "Internal server error" error message is returned from the server; monitoring with Wireshark showed that upon clicking the button standard TCP connection handshake (syn-syn+ack-ack) is initiated to specified SMTPS port, but nothing happens after that.

![test-mail](https://cloud.githubusercontent.com/assets/11802046/8704438/a031819c-2b2b-11e5-8520-795cd00b8c6e.png)

**Comment by mzico** [comment]
@aliaksander-samuseu : What does wrapper.log says about this failure? Generally this 'Internal Server Error' means Server felt into waiting loop and died.

**Comment by aliaksander-samuseu** [comment]
@mzico : that's strange, but I can't see anything unusual in wrapper log for the whole period of time the page is being stuck in loading state. The only relevant entry can be found in apache's error log:idp.gluu.loc:443 192.168.238.102 - - [18/Aug/2015:18:12:33 +0000] "POST /identity/organization/configuration?cid=219 HTTP/1.1" 500 1019 "https://idp.gluu.loc/identity/organization/configuration" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"

**Comment by mzico** [comment]
tail wrapper log while doing this SMTP configuration from oxTrust.

**Comment by aliaksander-samuseu** [comment]
Did that. There is a lot of usual oxTrust's messages (validation of metadata, this old exception related to certeficate timestamp checking etc), but nothing more, for the whole 5 minutes when the page is stuck in this state.

**Comment by aliaksander-samuseu** [comment]
It also seems that page stays in this state for exactly 5 minutes, you can see the difference between log timestamps from access and error apache's log I posted above. I repeated it once more, and the difference between time in timestamps is the same once more:

[Tue Aug 18 18:34:09.692958 2015] [proxy_ajp:error] [pid 49917:tid 140109592577792] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Tue Aug 18 18:34:09.693059 2015] [proxy_ajp:error] [pid 49917:tid 140109592577792] [client 192.168.238.102:58928] AH00992: ajp_read_header: ajp_ilink_receive failed, referer: https://idp.gluu.loc/identity/organization/configuration?cid=223
[Tue Aug 18 18:34:09.693090 2015] [proxy_ajp:error] [pid 49917:tid 140109592577792] (70007)The timeout specified has expired: [client 192.168.238.102:58928] AH00878: read response failed from 127.0.0.1:8009 (localhost), referer: https://idp.gluu.loc/identity/organization/configuration?cid=223

idp.gluu.loc:443 192.168.238.102 - - [18/Aug/2015:18:29:09 +0000] "POST /identity/organization/configuration?cid=223 HTTP/1.1" 500 1019 "https://idp.gluu.loc/identity/organization/configuration?cid=223" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"

**Comment by aliaksander-samuseu** [comment]
No, there is something, but it's not an error, so it was hidden amongst usual chit-chatting:

INFO   | jvm 1    | 2015/08/18 18:12:33 | 2015-08-18 18:12:33,912 INFO  [org.gluu.oxtrust.action.UpdateOrganizationAction] HostName: smtp.yandex.ru Port: 465 RequireSSL: true RequireSSL: true
INFO   | jvm 1    | 2015/08/18 18:12:33 | 2015-08-18 18:12:33,912 INFO  [org.gluu.oxtrust.action.UpdateOrganizationAction] UserName: alex.samuseu Password: vfcdxsza
INFO   | jvm 1    | 2015/08/18 18:12:33 | 2015-08-18 18:12:33,912 DEBUG [org.gluu.oxtrust.util.MailUtils] HostName: smtp.yandex.ru Port: 465 ConnectionTimeOut: 5000
INFO   | jvm 1    | 2015/08/18 18:12:33 | 2015-08-18 18:12:33,912 DEBUG [org.gluu.oxtrust.util.MailUtils] UserName: alex.samuseu Password: vfcdxsza

The timestamp on it matches the time on request from apache's access log

**Comment by aliaksander-samuseu** [comment]
**Rahat wrote:**
Error occurs when we don't check "Requires Authentication" check box.
I am attaching snapshots of both cases ("Requires Authentication" unchecked and checked).
If error occurs where "Requires Authentication" Check box is checked at your side then we can further look into it.

**Comment by aliaksander-samuseu** [comment]
It was last tested on ce-release.gluu.org at 15.10.2015, and was reproducible. I filled in all input fields of the "SMTP server configuration" tab, and set "Requires Authentication" and "Requires SSL" checkboxes. Still the same Internal server error

**Comment by mzico** [comment]
Can't reproduce the issue with 2.4.1. Tried with our mail server.
