### ISSUE TITLE
AuthorizationProcessingFilter should check to which API client make an call

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#850]
org.gluu.oxtrust.service.scim2.interceptor.AuthorizationProcessingFilter is much better than our old approaches. We are planning to reuse it to protect new rest API too. As result we need to add code into filter to allow call specific UMA protection code based on context path.

**Comment by yurem** [comment]
BTW, If `@ScimAuthorization` limit scope to API with this annotation only we can close this issue.

**Comment by jgomer2001** [comment]
I can move AuthorizationProcessingFilter to a proper package
and change name of @ScimAuthorization annotation to a different one
in `filter` method I might code the multiplexing so separate classes (or logic) can be called based on url path pattern

however, not sure if I understand:
> BTW, If @ScimAuthorization limit scope to API with this annotation only we can close this issue.

let me know if I can proceed with the above sketch

**Comment by yurem** [comment]
Regarding this:
> BTW, If @ScimAuthorization limit scope to API with this annotation only we can close this issue.
Rest call AuthorizationProcessingFilter filter only if method annotated with @ScimAuthorization

This means that AuthorizationProcessingFilter  not filter URL like this `https://localhost:8453/identity/restv1/group/read/@!5304.5F36.0E64.E1AC!0001!179C.62D7!0003!60B7`.

Hence you can close this issue without changes.

**Comment by jgomer2001** [comment]
Here is how to protect an API with the enhancements pushed to branch `issue850`:

- Add org.gluu.oxtrust.service.filter.ProtectedApi annotation to restEasy methods of interest

- Add a subclass of org.gluu.oxtrust.service.uma.BaseUmaProtectionService that implements specific details of UMA protection in method `processAuthorization`

   This method will likely call `processUmaAuthorization` of base class (currently it basically does a generic RPT validation)

   We already have two descendants of abstract base class: PassportUmaProtectionService and ScimUmaProtectionService


When  method `filter` in org.gluu.oxtrust.service.filter.AuthorizationProcessingFilter is called, a proper weld instance that inherits BaseUmaProtectionService is chosen based on path of actual HTTP request. 

The selection is made by checking the contents of the org.gluu.oxtrust.service.uma.BindingUrls annotation present in the concrete subclasses

If the path of the request starts with any of the relative urls specified in the class annotation, that's the class employed to achieve the protection

btw AuthorizationProcessingFilter is an application-scoped bean according to weld-probe...

**Note:**

Passport stuff was adjusted to follow this too, but I only tested SCIM services which are fine.

**Comment by yurem** [comment]
New update to `@ProtectedApi`. Now it's possible to specify list of required UMA scopes which required to access this API. Exmple:
```
@ProtectedApi(scopes = { "/api/group/access" })
public class GroupWebService {
...    
    @ProtectedApi(scopes = { "/api/group/read" })
    public GluuGroup read(@PathParam("inum") String inum, @Context HttpServletResponse response) {

```

I added these changes to master (3.2.0) only.
