### ISSUE TITLE
'Inbound' button available though 'Asimba' is false

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#853]
It's in 3.1.2. 
'Inbound' button is not doing anything ( no drop down ) but it's still there though I chose 'false' for Asimba during setup. 

oxTrust version: 

```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.2.Final
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 9de781cd23764ec11b234af65cd055d159a83877
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121

```

![inbound_button](https://user-images.githubusercontent.com/7156097/36281537-9a292058-1263-11e8-859c-6488d38ac1fe.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/889

**Comment by shekhar16** [comment]
Fixed.
