### ISSUE TITLE
Add 'server:port' instead of 'server' in Cache Refresh

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#857]
We need to provide the 'hostname/ip_address:port_number' in 'Server' value. 
I think it will be more understandable if we can put "Server and Port" or "Server:Port" instead of only "Server". 
![server_port](https://user-images.githubusercontent.com/7156097/36499961-6ef830e6-1708-11e8-8eed-6ac4b739728c.png)

**Comment by shekhar16** [comment]
Fixed .

![image](https://user-images.githubusercontent.com/15937500/36558517-4d388f1c-1831-11e8-8f9c-db2835b9c614.png)
