### ISSUE TITLE
Different lists on OIDC-related pages has remove controls' column skewed

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#858]
Environment:
CentOS 7.3, gluu-server-3.1.2-1-4.centos7, Google Chrome

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "OIDC -> Scopes" page and open any scope with long list of claims there

Result:
Names of the scopes and other elements are slightly shifted comparing to position of there corresponding remove controls. Please see picture below:
![lists_displaced](https://user-images.githubusercontent.com/11802046/36508177-01a396ec-176d-11e8-9033-2f8f503b6341.png)
Different lists on OIDC clients' properties shows the same behaviour as well.

**Comment by shekhar16** [comment]
Fixed.

X button is aligned now and added rows with different color to identify its x button.

![image](https://user-images.githubusercontent.com/15937500/36632058-4ec97cc0-19a7-11e8-819a-b639774e6f61.png)
