### ISSUE TITLE
GUI problems in Manage Authentication

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#860]
Go to Configuration -> Manage Authentication-> Manage LDAP Authentication page and scroll down. Observe that cross buttons are misplaced, they should moved to the right side of representing input field. Only a colon found as label followed by Change Bind Password link. No space found between "Deactivate' and "Test LDAP Connection" buttons.

Check below screens for detail information.

![11](https://user-images.githubusercontent.com/36174217/36568339-c7fcb8e6-1853-11e8-90ce-6f6a9494fe54.jpg)

![22](https://user-images.githubusercontent.com/36174217/36568386-014ba2c4-1854-11e8-9fa6-9fb9b31964f9.jpg)

![33](https://user-images.githubusercontent.com/36174217/36568403-111088aa-1854-11e8-8616-8ed31e8cf10e.jpg)

![44](https://user-images.githubusercontent.com/36174217/36568416-220156d0-1854-11e8-8269-3e985f1405ec.jpg)

**Comment by willow9886** [comment]
@shekhar16 can you do a full sweep of the entire GUI and fix all such interface oddities?

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36644169-5c8077bc-1a7c-11e8-9c3f-778a4f4a1d1b.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36644177-83212bdc-1a7c-11e8-9392-bfd88a2efd68.png)

**Comment by shekhar16** [comment]
I think above fix is looking good.
i m closing this issue if u need anything more please reopen it and let me know.

**Comment by sahiliamsso** [comment]
@shekhar16  Lets add space b/w "Deactivate" and "Test LDAP Connection"
![image](https://user-images.githubusercontent.com/21104811/37320291-084ef974-2699-11e8-88a4-d435f1eee656.png)

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/37355952-ed92eb6e-270a-11e8-8b88-98a5a03701af.png)
