### ISSUE TITLE
Overall user experience for adding a person by using the Add person form

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#861]
Go to Users-> Add person
![0](https://user-images.githubusercontent.com/36174217/36631213-5190d2cc-199e-11e8-984f-33a0e0a3d26d.jpg)
_Observe that Click to enter message is missing in Password field._

Enter 123456789 in Password field
![1](https://user-images.githubusercontent.com/36174217/36631220-74a68c48-199e-11e8-9989-3310dc5b5efc.jpg)

Move to Confirm password field by clicking on the input field
![2](https://user-images.githubusercontent.com/36174217/36631232-9c61a1d2-199e-11e8-8df5-f7b082f21918.jpg)
_Observe that entered password text is showing in the Password field(Similar behavior can be found in Confirm password field also, check the last screen)._

Than warning message appear about password and confirm password not matching and password text got hidden again.
![3](https://user-images.githubusercontent.com/36174217/36631246-d7355218-199e-11e8-8960-28d35dfe42c2.jpg)
_Note at this point user did not enter any value in confirm password field and did not move to another field in the form. The warning message about mismatch should be shown after user enter value in the confirm password field and move to another field from it._

![4](https://user-images.githubusercontent.com/36174217/36631258-fe030fc0-199e-11e8-8f7c-7011b0dc799a.jpg)

**Suggestions:** 

1. In order to show hidden password in Password and Confirm Password field a checkbox can be introduced with label Show password.

2. Warning message about each field in the form appear as soon as user move to another field. For example when user click on Username field and move to First name field without entering any value, waring message shows about Username field. Warning message can be shown after user finish filling the form and click on Add button for respective input fields.

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/75a17aba39f9747ae152d892b9f220a1c059ce80

**Comment by shekhar16** [comment]
Tabs indexing and show/hide password confirm password is added.
