### ISSUE TITLE
Display Resource creation date and associated RS

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#864]
It would be helpful if one could see the creation timestamp and associated client. 

![image](https://user-images.githubusercontent.com/3717101/36645050-adf4de52-1a28-11e8-9858-80c1f27f4f7c.png)

This data is available from LDAP client attributes: `oxAssociatedClient` and operational `createTimestamp`

![image](https://user-images.githubusercontent.com/3717101/36645044-8c589676-1a28-11e8-8439-101761d0b11f.png)

#### Update this resource form

* Lookup the associated client `displayName`. Use `client_id` only if displayName is not found.  

* The client name should [hyperlink](.) to the respective client detail page.

**Comment by sahiliamsso** [comment]
Creation Time is blank
![image](https://user-images.githubusercontent.com/21104811/38120065-b42a026e-33e3-11e8-936b-7c7bf6f2d2aa.png)

**Comment by shekhar16** [comment]
@sahiliamsso  please check in ldap is there any value present in oxAuthCreation attribute.

![image](https://user-images.githubusercontent.com/15937500/38122453-b5045fa4-33f2-11e8-887b-4daa4e1a7228.png)

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/38157568-ccc90f00-34a5-11e8-8958-9735c67d8681.png)

This is a fresh install, and i don't see  oxAuthCreation  attribute

**Comment by yurem** [comment]
oxTrust not allows to add UMA resources now. This value should come from oxAuth. We not create these 2 resources which you show in screenshot through API. We added them during setup from [this](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/scim.ldif#L44) ldif.
You can add this attribute to ldif with dummy date.

**Comment by yurem** [comment]
I added this attribute to template entries in setup: https://github.com/GluuFederation/community-edition-setup/commit/4f9a371098670e893a9aba43faca4009c9a64d26

We need to check this in new Beta

**Comment by yurem** [comment]
I've removed expiration attributes from Passport and SCIM resources which we added in previous build to skip their clean up. These are internal resources. Hence oxAuth should not remove them in expiration checker timer
