### ISSUE TITLE
Use JSON Logic GUI to display scope expression

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#865]
Currently scope expression display in row format. 
![umaissuerowimage](https://user-images.githubusercontent.com/2329776/36662575-cca66078-1b04-11e8-8dd0-52566b1ef2c7.png)

Display this row format to GUI.

Example:

```
row JSON
{  
   "rule":{  
      "or":[  
         {  
            "var":0
         },
         {  
            "var":1
         },
         {  
            "and":[  
               {  
                  "var":2
               },
               {  
                  "var":3
               }
            ]
         }
      ]
   },
   "data":[  
      "https://test1.com",
      "https://test2.com",
      "https://test1.com",
      "https://test3.com"
   ]
}
```

```
Note:
1.     "var":0 --> "https://test1.com"
        "var":1 --> "https://test2.com"
         ...

2. JSON rules can be nested at any level.
```

Convert below JSON to GUI.

![umanewissue](https://user-images.githubusercontent.com/2329776/36662743-6a4dea6c-1b05-11e8-8c45-b1ff6a325bee.png)

I've made this design in [Gluu-Gateway](https://github.com/GluuFederation/gluu-gateway) which is in angular JS framework. But you can use [JQuery-Builder](https://github.com/jeremywall/jQuery-QueryBuilder) library.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/38750803-b67d21cc-3f73-11e8-9616-08aff7076a2f.png)

**Comment by shekhar16** [comment]
@yurem  @willow9886 Can we close this issue ?

**Comment by sahiliamsso** [comment]
AND/OR is not selectable.
![image](https://user-images.githubusercontent.com/21104811/44128734-20d0d952-a062-11e8-9f2a-050b58207c11.png)

**Comment by natt-tester** [comment]
@shekhar16, please refer to Sahil's comment above.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45948121-ba172200-bfee-11e8-9ffe-bbf65a1272b1.png)
