### ISSUE TITLE
'Add custom script configuration' drop down box 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#866]
Screenshot attached; when you go and hit 'Add custom script configuration'; here is what coming: 

[1]
![custom_script_1](https://user-images.githubusercontent.com/7156097/36676892-71178606-1ad2-11e8-8fa0-4cd3f09e79be.png)

[2]
![custom_script_2](https://user-images.githubusercontent.com/7156097/36676898-73c38b34-1ad2-11e8-8169-abf9cc82d7cc.png)

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/36744775-a38f9226-1c13-11e8-98f7-80f9505896f3.png)
