### ISSUE TITLE
User Registration not working 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#87]
Gluu Server: CentOS 6.x - 2.3.1 - oxTrust: 3.0.1-SNAPSHOT - oxAuth: 3.0.1-SNAPSHOT

`https://hostname/identity/register` is not appearing. Instead it is moving for oxAuth login page. 

Investigation: 
1. No visible error in oxtrust/oxauth/wrapper log. 
2. `https_gluu.conf` has good condition:  `<LocationMatch  "/identity/(error|feedback|register|ssologin|federation/hosted/inventory|/federation/proposal/add)">`

**Comment by mzico** [comment]
Bug persist in 2.3.2. Log throwing NPE: 

stack trace from wrapper.log: 

    INFO   | jvm 1    | 2015/08/12 12:28:45 | 2015-08-12 12:28:45,926 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
    INFO   | jvm 1    | 2015/08/12 12:28:45 | javax.el.ELException: java.lang.NullPointerException
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:339)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:348)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.parser.AstPropertySuffix.invoke(AstPropertySuffix.java:58)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.parser.AstValue.invoke(AstValue.java:96)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.core.Expressions$2.invoke(Expressions.java:222)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.navigation.Page.preRender(Page.java:311)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.navigation.Pages.preRender(Pages.java:351)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.jsf.SeamPhaseListener.preRenderPage(SeamPhaseListener.java:565)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.jsf.SeamPhaseListener.beforeRenderResponse(SeamPhaseListener.java:476)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.jsf.SeamPhaseListener.beforeServletPhase(SeamPhaseListener.java:147)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.jsf.SeamPhaseListener.beforePhase(SeamPhaseListener.java:117)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:228)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:99)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at java.lang.Thread.run(Thread.java:745)
    INFO   | jvm 1    | 2015/08/12 12:28:45 | Caused by: java.lang.NullPointerException
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.gluu.oxtrust.action.RegisterPersonAction.initPerson(RegisterPersonAction.java:130)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at java.lang.reflect.Method.invoke(Method.java:606)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.gluu.oxtrust.action.RegisterPersonAction_$$_javassist_seam_70.initPerson(RegisterPersonAction_$$_javassist_seam_70.java)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at java.lang.reflect.Method.invoke(Method.java:606)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335)
    INFO   | jvm 1    | 2015/08/12 12:28:45 |       ... 55 more

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxTrust/commit/bdc5b67e0b4bf3322383755410e37c14491de86b
