### ISSUE TITLE
Make oxTrust Favicon standard Gluu transparent icosahedron

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#870]
![image](https://user-images.githubusercontent.com/3717101/36695956-633a0910-1b08-11e8-9ee5-0d94c145659a.png)

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/36857379-6b8b3592-1d9e-11e8-9ad7-29b457d80b8e.png)

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36890111-b1e145ca-1e22-11e8-993a-2d70b2e4c409.png)
