### ISSUE TITLE
UMA scope Download/Link is 404

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#871]
We can just remove this Download Link.  It would be better to show the oxID in this table. 

![image](https://user-images.githubusercontent.com/3717101/36696144-fe2ff592-1b08-11e8-9926-7f16751eb90e.png)

![image](https://user-images.githubusercontent.com/3717101/36696102-e52551f0-1b08-11e8-8548-43ccbfc7f822.png)

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/36797566-48f4686c-1cce-11e8-81bb-9dc9ae5069f0.png)
