### ISSUE TITLE
Show Clients using UMA Scope

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#872]
It would be nice to know which UMA resource servers are using a certain scope. For example, in a table like this:

![image](https://user-images.githubusercontent.com/3717101/36697258-255b076c-1b0c-11e8-8ac3-3b000a17adda.png)

This information is available in LDAP:

![image](https://user-images.githubusercontent.com/3717101/36696958-4ff10d74-1b0b-11e8-97eb-cdfd13f637f2.png)

If you could search under `ou=resources,ou=uma,o=(org-inum),o=gluu` for the scope by DN. Then keep a map of the client_dn and fetch each client object. In the table, it's best to show the displayName of the client with a link to the client entry in oxAuth (client detail view)

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/36945177-3686c3dc-1fd0-11e8-8d25-2c86fbb15432.png)
