### ISSUE TITLE
No certificate upload button available 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#874]
This feature is required when Gluu Server Administrator need to renew certificate for any SP ( Service Provider ). 

![nouploadoption](https://user-images.githubusercontent.com/7156097/36733310-da8ca882-1b95-11e8-876f-21201d87c194.png)

**Comment by shekhar16** [comment]
for button we had condition for gluuSAMLspMetaDataFN is empty then only the button will be visible.
Let me know should I hide the label "Update public certificate" aswel or remove the condition from button so that button will be visible..

**Comment by yurem** [comment]
I think both label and button should use same render condition.

**Comment by mzico** [comment]
@shekhar16 : I am not exactly sure what 'gluuSAMLspMetaDataFN' is.. .can you provide some little explanation or example?

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/37358477-325199a2-2711-11e8-888b-30dd66691aed.png)
