### ISSUE TITLE
Some meta information not retrieved via SCIM if user was not created or updated with the API itself

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#877]
Context info here: https://support.gluu.org/identity-management/5160/scim-resourcesmeta-properties/

**Comment by sahiliamsso** [comment]
Still able to see this error message on screen
![image](https://user-images.githubusercontent.com/21104811/38284065-0d5e2aa8-37d7-11e8-8935-ac001736d7f1.png)


Also, when you double click "Add Trust Relationship", you will see this screen appearing.

**Comment by sahiliamsso** [comment]
Sorry, re-opened by mistake.
