### ISSUE TITLE
[Bug][Functional][Join Federation]"Failed to save metadata file" error on attempt to apply for hosted federation's membership

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#89]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Steps to reproduce:
1) Log in to oxTrust web UI as a regular user (not a member of Gluu Manager Group)
2) Move to "Federations" -> "Join Federation" page
3) Fill all required fields there and click "Add" button; you can use next urls as sources of test metadata:
https://shib.alexanderstreet.com/Shibboleth.sso/Metadata
https://ib213.tmit.bme.hu/Shibboleth.sso/Metadata

Result:
"Failed to save metadata file" error is displayed. Further investigation showed that oxTrust encounters some problem while trying to save the metadata; it seems some directory either doesn't exist, or service has insufficient rights to create it. First several lines of java error trace read:

2015-07-20 17:34:22,925 ERROR [org.gluu.oxtrust.ldap.service.Shibboleth2ConfService] Failed to write meta-data file '/opt/shibboleth-federation/metadata/F6BEE46F845CD7D60002C6D4559200066CB80690-metadata.xml'
java.io.IOException: Directory '/opt/shibboleth-federation/metadata' could not be created

Indeed, there is no such directory under that path, and it seems that access permissions set for /opt directory won't allow the service to create any directories here. After /opt/shibboleth-federation/ directory was created manually and its ownership was transferred to tomcat user/group, sub-directory "metadata" had been created by the oxTrust itself and application process was successful.

See attached screenshot for details.

Expected result:
The '/opt/shibboleth-federation/' directory must be created during installation, at least in case if federation hosting functionality was selected by user from the options list, and must have sufficient access permissions (for oxTrust to create sub-directories and files there). Also, as Zico said: "we should rename it to 'Gluu Federation' instead of 'Shibboleth Federation'"

![no-fed-dir](https://cloud.githubusercontent.com/assets/11802046/8786723/79eefad0-2f38-11e5-9a02-385e87d87c5f.png)

**Comment by mzico** [comment]
We are not supporting hosting federation right now. May be we will re-engage again when this feature is active. Closing issue for now.
