### ISSUE TITLE
Getting error when try to open UMA scope

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxTrust#897]
I am getting an error when trying to open any scope in UMA.

Reproduce problem
Navigation to UMA -> scopes and click on any scope.

![oops](https://user-images.githubusercontent.com/2329776/37281409-e25834a6-2616-11e8-949b-43c706b2f1ce.png)

You can see an error in below log file.
[oxtrust.log](https://github.com/GluuFederation/oxTrust/files/1802540/oxtrust.log)

Environment
OS: Ubuntu 14.04
Gluu version: 3.1.3
Install package: gluu-server-3.1.3_1.3_trusty+Ub14.04_amd64.deb

**Comment by shekhar16** [comment]
I think code is partially merged in 3.1.3 branch. the code of UpdateScopeDescriptionAction.java is missing https://github.com/GluuFederation/oxTrust/commit/1ad3fc7f2170e7b8e5b63e30368b03335252660b

**Comment by yurem** [comment]
I've merged and resolved conflict in this commit: 526e70eefe9545ff96c7801612b1a18b4973416b
