### ISSUE TITLE
[Bug][Security][Federations]Regular users are capable to add/modify hosted federations

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#90]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.0-1

Preconditions:
1) At least one regular user's account exists in the oxTrust
2) Several test federations are created at "Federations"-> "Federations" page while logged in as admin user
3) "Federation hosting" has been enabled at the "Organization configuration" page

Steps to reproduce:
1) Log in to oxTrust web UI as a regular user (not a member of Gluu Manager Group)
2) Copy and paste this url to your browser's address bar: https://your.gluu.host.dns.name/identity/federation/proposal/inventory?cid=33
3) Try to modify existing federation there, and to add your own

Result:
After completing step 2) user ends up on the "Federations"-> "Federations" page, though - judging by composition of the UI - it seems that regular users can only apply for membership in existing federations (and only after service's admin's approval) and can't create federations of their own (there is no path to "Federations"->"Federations" page through menus of the UI); after getting to this page, on step 3) they are not only capable to do that, but even can modify existing federations.
There is also another example of strange behavior: if "Cancel" button is clicked during application process, user also ends up on the "Federations"-> "Federations" page.

See attached screenshot for details.

Expected result:
Users should be only capable of applying for membership in existing federations; proper authorization scheme should be implemented for this module, what
1) Prevents them from browsing directly to this page using well-known url
2) Disallows creation or modification of hosted federations' objects for regular users (aside from, probably, their own SP, i.e. the one that was created as result of them applying for membership in some hosted federation before; but any subsequent modifications also should require approval from service admin)

![sec-fed](https://cloud.githubusercontent.com/assets/11802046/8788432/0e72e144-2f43-11e5-8b0b-c9c088fa15ea.png)

**Comment by mzico** [comment]
We are not supporting hosting federation right now. May be we will re-open the bug if required in future. Closing ticket for now.
