### ISSUE TITLE
3.1.3 QA - Authentication graph not reflecting actual Successful authentication count.

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#901]
According to graph, 2 successful authentication events but if you check logs then count is different,

![image](https://user-images.githubusercontent.com/21104811/37379609-4c2ceb6c-275a-11e8-96ef-ebbf3b8c66c6.png)

2018_03_13.stderrout.log:2018-03-14 00:32:56,584 INFO  [qtp985655350-11] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log:2018-03-14 00:34:00,429 INFO  [qtp985655350-11] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log:2018-03-14 01:15:57,902 INFO  [qtp985655350-18] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log:2018-03-14 02:02:00,300 INFO  [qtp985655350-19] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log.024054043:2018-03-13 01:23:21,895 INFO  [qtp985655350-13] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log.235445733:2018-03-13 02:43:56,547 INFO  [qtp985655350-19] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
2018_03_13.stderrout.log.235445733:2018-03-13 13:39:04,784 INFO  [qtp985655350-15] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust-2018-03-13-1.log:2018-03-13 01:23:21,895 INFO  [qtp985655350-13] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust-2018-03-13-1.log:2018-03-13 02:43:56,547 INFO  [qtp985655350-19] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust-2018-03-13-1.log:2018-03-13 13:39:04,784 INFO  [qtp985655350-15] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust.log:2018-03-14 00:32:56,584 INFO  [qtp985655350-11] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust.log:2018-03-14 00:34:00,429 INFO  [qtp985655350-11] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust.log:2018-03-14 01:15:57,902 INFO  [qtp985655350-18] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully
oxtrust.log:2018-03-14 02:02:00,300 INFO  [qtp985655350-19] [org.gluu.oxtrust.action.Authenticator] (Authenticator.java:132) - User 'admin' authenticated successfully

**Comment by yurem** [comment]
You should wait 300 seconds according to default oxAuth metric [reporter ](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxauth-config.json#L231) interval. Every 5 minutes oxAuth persists to LDAP new statistic. You can change this property to persist statistic often.
