### ISSUE TITLE
Improve password reset functionality

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#903]
There are 2 small issue:
1. Mail service should send e-mail in UTF-8. Now when user name has non ASCII characters it send it as ???.
2. Don't show profile button in password reset form. These are notes from support ticket:

Sample scenario: USER A with a display name of UserA recently logged in to Gluu and logged out properly. USER B with a display name of UserB used forgot password and gets redirected to the screen where he/she can change his/her password. USER B checked the user icon at the upper right part of the screen the displayed name was UserA but supposedly it was UserB since USER B initiated the request of new password.

Link to original issue: https://support.gluu.org/single-sign-on/5230/forgot-password/

**Comment by yurem** [comment]
It's small issue. It will be nice to include it into 3.1.3

**Comment by shekhar16** [comment]
We already had UTF-8 encoding.Here is the link https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/service/MailService.java#L118

**Comment by yurem** [comment]
@shekhar16 can you try to reproduce it?

**Comment by yurem** [comment]
I added this update: https://github.com/GluuFederation/oxCore/commit/1cb71b8b35b3a2ba03085224d80425afe82d94b2 Can you check if this helps to resolve issue?

**Comment by yurem** [comment]
![screenshot 6](https://user-images.githubusercontent.com/6104200/37591980-56b4db08-2b7e-11e8-9ada-db70f2e1d474.png)

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/37593351-bc4ced80-2b82-11e8-88df-f1dcb6053071.png)
