### ISSUE TITLE
Selected Entity ID name and Change Entity ID link showing as a single link

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#906]
Perform following steps to reproduce,
1. Create a Federation type Trust relationship in SAML
2. Create a Single SP from that created Federation Trust relationship
3. Observe that in the created single SP trust relationship selected Entity ID name and Change Entity ID link showing as single link

Suggestion: Selected Entity ID name can be shown as text and Change Entity ID should be shown as link as user will be able to change it by clicking on it.

Check below screen for detail information.

![single_sp_from_federation_sp](https://user-images.githubusercontent.com/36174217/37569926-769ae374-2b13-11e8-88b8-a63c063d20d3.JPG)

**Comment by yurem** [comment]
The changes in v 3.1.3 and in master. We need to retest it.
