### ISSUE TITLE
In Add Person form user is not able to navigate to next input field by pressing the [Tab] button in keyboard

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#907]
Perform following steps to reproduce,
1. Go to Add Person form
2. Click on Username input field and enter username
3. Press on [Tab] button in keyboard and observe that user is not navigated to the next input field in the form which is First Name field. 

When user click on tab button in they expect to navigate to the next field in the form. In user self registration form in Gluu user is able to move between input fields by hitting the tab button which is expected.

Check below screen for detail information,

![tab](https://user-images.githubusercontent.com/36174217/37570142-1627784c-2b16-11e8-95b0-68353f3611f4.jpg)

**Comment by shekhar16** [comment]
we fixed in latest code commit on https://github.com/GluuFederation/oxTrust/issues/861

**Comment by willow9886** [comment]
@shekhar16 tabs now work... but the new field you tab into is not selected...so the user still has to click into the form!

**Comment by shekhar16** [comment]
The fields has been implemented with <rich:inplaceInput , so for every field we had span and input fields in combine form that's why, on focus its only focusing the field but not allowing to enter text.

**Comment by yurem** [comment]
In next version we are planning to remove richfaces at all. I think we can replace rich:inplaceInput with h:inputText to make text input generic across all our GUI.

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/39635094-14696522-4fda-11e8-8b56-30f78e88dd21.png)

**Comment by shekhar16** [comment]
Tabs are working by above changes.

**Comment by natt-tester** [comment]
@shekhar16, I've just tested it and there seems to be quite a lot of buggy behavior present. Did you check the functionality after finishing the task? 

Whenever I click on a field or use a tab, an **error message pops out**. Even as a reminder, it looks pretty aggressive, so without any real update/addition we shouldn't display them.

Also, the show/hide password **icon doesn't seem to work**. 

And it's **impossible to add a new user**:

<img width="389" alt="no_user" src="https://user-images.githubusercontent.com/38302725/44087921-a73641de-a004-11e8-8f6f-5b29d3ac26db.png">

The whole activity throws the following error:

![error2](https://user-images.githubusercontent.com/38302725/44086634-89dd33b2-a000-11e8-9d4a-f0904cad3a10.jpg)

Refer to the GIF:
![buggybug](https://user-images.githubusercontent.com/38302725/44087803-52a19fa6-a004-11e8-88da-fe057cdfbb63.gif)

**Comment by shekhar16** [comment]
@natt-tester  
1) The primary validations are working on losing the focus on fields i.e if you leave the field blank and change focus from that fields it will validate immediately that's why u are seeing validation message popup.I think u should know about onfocus validations.

2) Show/hide buttons are not working because we are working on richfaces => primfaces migration i.e. #768. And show/hide button already fixed in that branch, as this issue still in progress for other pages so we can't merged it right now.

3) We fixed the duplicate uid validation in https://github.com/GluuFederation/oxTrust/commit/7fc02f4f015ca4db14c1336ca69e8430ba69d978

@yurem i consolidated above changes in new PR (i.e. https://github.com/GluuFederation/oxTrust/pull/1100 ) for above pending changes.So that u can merge it.

**Comment by natt-tester** [comment]
@shekhar16, great that there are some fixes provided. I always report what I see as a user, and at the moment of testing, the UX was terrible. "You know it works like that" doesn't really apply if we want to make the UX better. 

I would suggest getting rid of the popup messages as soon as possible on focus out, especially when the user clicks through them. The behavior in this view is inconsistent with other menu items' behavior, e.g. in Register Attribute. The way I see it, if there's any button that could validate the whole form -- just like Register does in this view -- it should do it, highlighting the field and/or providing a meaningful hint in/under the field + a pop-up:

![validation](https://user-images.githubusercontent.com/38302725/44148530-1c4bf3ba-a0dc-11e8-8930-e2102a24157d.gif)
