### ISSUE TITLE
3.1.3 QA - No option to remove field or strategy under passport authentication method.

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#911]
Currently there is no option for the user to delete the field or strategy under passport authentication method.

![image](https://user-images.githubusercontent.com/21104811/37740572-38e28e88-2d84-11e8-8f36-d4a7401f7967.png)

And, it doesn't allow to save the configuration until those fields are filled. 

![image](https://user-images.githubusercontent.com/21104811/37740628-639b144c-2d84-11e8-8e0f-50ecf8ad20d8.png)

**Comment by yurem** [comment]
Done. Can you retest it on new oxTrust 3.1.3 build?

**Comment by sahiliamsso** [comment]
Underlying issue is fixed, But error validation message is still not in correct format.
![image](https://user-images.githubusercontent.com/21104811/38341484-71f0413a-3896-11e8-9bbd-e9e58e91142c.png)
