### ISSUE TITLE
Move texts from xhtml/java into oxtrust_en.properties

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#913]
oxTrust has full i18n support.  It also allow to customize  oxtrust_{xy}.properties via external resources. But in xhtml/java there are texts. We need to move all texts to oxtrust_en.properties.

Example for java:
```
    @Inject
    private FacesMessages facesMessages;

    facesMessages.add("#{msg['string.key]}");
    facesMessages.add(Severity severity, "#{msg['string.key]}") {
    facesMessages.add(String clientId, Severity severity, "#{msg['string.key]}") {
    facesMessages.add(Severity severity, "#{msg['string.key]}", Object ... params) {
```

Example for xhtml:
```
#{msg['string.key']}
```

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/b1496d54fbc7d48d045eedef5194c91a900ed378

**Comment by syntrydy** [comment]
More text has been move to properties files in other issues, plus the one moved in this issue.

Also moving text to properties file is a progressive task, we fix them ask we see them in code.
