### ISSUE TITLE
Google Image icon missing in passport-social script login page

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#915]
Configuration > Manage Authentication
Enter Strategy => google, and provide clientID, and clientSecret
Restart passport

Try to login

Image icon is broken for google.
![image](https://user-images.githubusercontent.com/21104811/37806218-d9aad8e4-2e64-11e8-9c76-f8663a067bb0.png)

**Comment by yurem** [comment]
Fixed
