### ISSUE TITLE
User status is enabled after clicking registration confirmation link via email

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#916]
Steps to reproduce
1. Register user 
2. Click on the confirmation link received in email
3. Notification is displayed: "You successfully registered. But your account is disabled"

But in actual. User account gets enabled immediately after clicking the confirmation link.

![image](https://user-images.githubusercontent.com/21104811/37806940-c29f9456-2e68-11e8-92d1-142ffe50e7e9.png)

Actual User Status 
![image](https://user-images.githubusercontent.com/21104811/37807090-9e3ff5b4-2e69-11e8-9352-e39b57f0828a.png)

**Comment by yurem** [comment]
Before opening /identity/register did you do logout? If no it shows right message about new user which you added. Did you registered sahil user?
