### ISSUE TITLE
Non-enabled scripts should not show as default authentication options

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#92]
I see CAS on the dropdown for default authentication, although the CAS script is not even enabled. I don't even think we should ship with the CAS script present. I'd rather see Duo there! 

![image](https://cloud.githubusercontent.com/assets/3717101/8883188/88ff52a4-3212-11e5-92b2-4a8192a7026c.png)

**Comment by yurem** [comment]
There is no bug in this form. It display only enabled script.
But I found bug which can led to this issue. In custom script form after changing usage type few times form can't be saved. Hence I suspect scripts were not saved. As result this form shows invalid list.
