### ISSUE TITLE
Reload oxTrust configuration without tomcat restart

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#93]
In cluster setup, LDAPs may deployed after oxTrust. Although oxTrust able to do the LDAP connection failover, it doesn't load the entry from LDAP correctly. For example, when trying to login, oxTrust throws error about non-existant account (although the account is actually exists in LDAP). Restarting Tomcat manually fixes this issue. It would be nice if oxTrust has a feature to reload the configuration without having to restart Tomcat. This is similar to oxAuth feature (https://github.com/GluuFederation/oxAuth/issues/22).

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxTrust/commit/44362d998580de80d73791688c8b3491bf97d09c
