### ISSUE TITLE
JSON Configuration is not working

### ISSUE THREAD

**Issue by origicom** [GluuFederation/oxTrust#938]
for some reason the JSON Configuration is not working. All 4 tabs are showing empty.

![image](https://user-images.githubusercontent.com/5741549/36937071-1beb4e84-1f0e-11e8-8a2e-23f7fe78af70.png)

Any idea what approach to use to find the root cause of this?

**Comment by mzico** [comment]
@origicom : Which Gluu server version?

**Comment by yurem** [comment]
Closing, because there is no info about this.
