### ISSUE TITLE
Uploading picture through "Picture URL" attribute prevents user from logging in to web UI

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#94]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.1-2

Preconditions:
1) Fresh installation of Gluu CE
2) New regular user account created just for this test
3) Feature "User Can Edit Own Profile" on the "Configuration->Organization Configuration" page is enabled
4) Authentication against internal LDAP database is used (though it was confirmed that issue can be reproduced for CR-created accounts authenticating against back-end LDAP)

Steps to reproduce:
1) Log in to oxTrust web UI as a regular user (not a member of Gluu Manager Group) that was created for this test
2) Move to "Personal" -> "Profile" page
3) Attach "Picture URL" attribute to your user
4) Using controls provided by attached attribute add any picture to the user account and click "Update" button
5) Log out and try to log in again with this user

Result:
Logging in process can't be completed. Empty page is returned and next error messages appear in the wrapper.log (you can find complete logs related to failed login attempt here: http://pastebin.com/4fNNtFzU):
org.apache.coyote.ajp.AjpProcessor process
SEVERE: Error processing request
java.lang.ArrayIndexOutOfBoundsException

The last url from the browser's address bar:
https://idp.gluu.org/oxauth/seam/resource/restv1/oxauth/authorize?response_type=code+id_token&scope=openid+profile+email+user_name&redirect_uri=https%3A%2F%2Fidp.gluu.org%2Fidentity%2Fauthentication%2Fauthcode&nonce=nonce&client_id=%40!73A0.15C2.270C.31F5!0008!3105.58B0&cid=149

From now on user isn't able to log into oxTrust with this account until the attribute is cleared of value assigned to it by picture uploading feature from before. Issue affects admin accounts too, and also accounts created by CR. To get access to the login page again flush all session related cookies from your browser cache - now you should be able to login as admin user and remove affected test user account, or assign its "Picture URL" attribute some bogus value  (string of random character will do) - as you can't currently remove the attribute itself, due to the issue #96
Also note how unsightly the content of this attribute looks when viewed in the user's editor of the "Users->Manage people" page. See attached screenshot for details.

![picture-prevents-login](https://cloud.githubusercontent.com/assets/11802046/9049935/5d8eac82-3a50-11e5-9105-c98ffef7ab7e.png)

**Comment by mzico** [comment]
Bug persist there in 2.3.2. No specific indication of error in log. 
Here are couple of last lines from oxauth.log: 

    2015-08-12 11:58:41,612 TRACE [org.xdi.oxauth.service.AttributeService] Get attribute from cache by Dn 'inum=@!468E.50EC.FF5C.BCDC!0001!1705.F84C!0005!BE64,ou=attributes,o=@!468E.50EC.FF5C.BCDC!0001!1705.F84C,o=gluu'
    2015-08-12 11:58:41,613 TRACE [org.xdi.oxauth.service.AttributeService] Get attribute from cache by Dn 'inum=@!468E.50EC.FF5C.BCDC!0001!1705.F84C!0005!6493,ou=attributes,o=@!468E.50EC.FF5C.BCDC!0001!1705.F84C,o=gluu'
    2015-08-12 11:58:41,669 DEBUG [org.xdi.oxauth.model.authorize.ScopeChecker] Checking scopes policy for: openid profile email user_name
    2015-08-12 11:58:41,714 DEBUG [org.xdi.oxauth.model.authorize.ScopeChecker] Granted scopes: [user_name, email, openid, profile]

**Comment by yurem** [comment]
It's oxAuth issue. I send e-mail to discuss this.

**Comment by yurem** [comment]
Instead of this issue I open 2 new issues:
https://github.com/GluuFederation/oxTrust/issues/135
https://github.com/GluuFederation/oxAuth/issues/87
