### ISSUE TITLE
2FA authentication fails when Primary Key is selected as mail

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#943]
Go to Configuration > Manage Authentication, and set primary key to "mail"
Enable any custom script from Configuration > Manage Custom scripts . I checked U2F
Now, try to login with mail attribute

Error in oxauth logs
2018-04-05 01:25:45,373 INFO  [qtp1744347043-14] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - U2F. Authenticate for step 1
2018-04-05 01:25:55,159 INFO  [qtp1744347043-11] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - U2F. Authenticate for step 1
2018-04-05 01:25:55,313 INFO  [qtp1744347043-11] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - U2F. Prepare for step 2
2018-04-05 01:25:55,325 INFO  [qtp1744347043-11] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - U2F. Prepare for step 2. Failed to determine user name

It seems this line, user = authenticationService.getAuthenticatedUser() is returning NULL value

**Comment by jgomer2001** [comment]
I tried OTP, this was my finding:

```
01:02:15,499 INFO  [service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - OTP. Prepare for step 1
01:02:15,499 DEBUG [oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:226) - Executing python 'getExtraParametersForStep' authenticator method
01:02:48,355 DEBUG [oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:163) - Executing python 'authenticate' authenticator method
01:02:48,356 INFO  [service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - OTP. Authenticate for step 1
01:02:48,397 INFO  [service.PythonService$PythonLoggerOutputStream] (PythonService.java:209) - OTP. Process basic authentication. Failed to find user 'jose@gluu.org'
```

**Comment by jgomer2001** [comment]
@yurem  I suspect the problem living here:

https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Server/src/main/java/org/xdi/oxauth/service/AuthenticationService.java#L454
https://github.com/GluuFederation/oxAuth/blob/version_3.1.2/Server/src/main/java/org/xdi/oxauth/service/UserService.java#L93

**Comment by willow9886** [comment]
@yurem It would be nice to make this really easy out-of-the-box, so orgs can simply choose whether they want to use email, username, or both to identify users.

**Comment by yurem** [comment]
Updated oxAuth and OTP script: https://github.com/GluuFederation/oxAuth/commit/5d9885cf10a727e45d0349be077bbff5c82d9f8d

**Comment by willow9886** [comment]
@yurem does this change need to be explained and documented?
