### ISSUE TITLE
[Bug][Functional][Profile]Admin user can't edit its own attributes when corresponding feature is disabled

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#95]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.1-2

Preconditions:
1) Fresh installation of Gluu CE
2) Authentication against internal LDAP database is used

Steps to reproduce:
1) Log in to oxTrust web UI as an admin user
2) Enable "User Can Edit Own Profile" feature on the "Configuration->Organization Configuration" page and move to the "Personal->Profile" page to have a look at features it can offer.
3) Move to the "Users"->"Manage People" page to have a look at features it can offer.
4) Disable "User Can Edit Own Profile" feature on the "Configuration->Organization Configuration" page and move to the "Personal->Profile" page to compare its state to what could be seen on step 2.
5) Move to the "Users"->"Manage People" page to compare its state to what could be seen on step 3.

Result:
Admin user can't edit its own attributes via profile page when this feature is disabled, though he still can do this by finding itself in the list on the "Users"->"Manage People" page.

Expected result:
1) Super admin should always have unrestricted access to all settings the system allows him to modify, and shouldn't be restricted by features designed to control regular users.
2) Regardless of security policies, having 2 modules - both accessible by admin - which react to this setting differently (one is affected by it, the other is not) makes no sense, but it can inconvenience and confuse the end user. Choosing some consistent behavior is recommended.
See attached screenshot
![admin-can t-edit](https://cloud.githubusercontent.com/assets/11802046/9050183/877d511c-3a53-11e5-9134-d371c365823d.png)

**Comment by mzico** [comment]
Couldn't reproduce the issue in 2.3.2.
