### ISSUE TITLE
SAML SP configuration is not Working with Gluu 3.1.3

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#950]
Steps to reproduce:

 Just follow the documentation [here](https://gluu.org/docs/ce/3.1.2/integration/sswebapps/saml-sp/#super-quick-ubuntu-shib-apache-install).

The error message is:

> ERROR [org.opensaml.saml.common.binding.security.impl.ReceivedEndpointSecurityHandler:200] - Message Handler: SAML message intended destination endpoint ‘https://gluu.gasmyr.com/idp/profile/SAML2/Redirect/SSO' did not match the recipient endpoint ‘http://gluu.gasmyr.com/idp/profile/SAML2/Redirect/SSO'
2018-04-09 20:17:54,828 - WARN [net.shibboleth.idp.profile.impl.WebFlowMessageHandlerAdaptor:202] - Profile Action WebFlowMessageHandlerAdaptor: Exception handling message
org.opensaml.messaging.handler.MessageHandlerException: SAML message failed received endpoint check
at org.opensaml.saml.common.binding.security.impl.ReceivedEndpointSecurityHandler.checkEndpointURI(ReceivedEndpointSecurityHandler.java:202)

**Comment by yurem** [comment]
yes, I can reproduce the same. I suspect it's configuration issue because the is difference in endpoint protocol only:
https://gluu.gasmyr.com/idp/profile/SAML2/Redirect/SSO
vs.
http://gluu.gasmyr.com/idp/profile/SAML2/Redirect/SSO

**Comment by yurem** [comment]
It looks like it's proxy issue

**Comment by syntrydy** [comment]
Yes, it works now. 
@yurem Thanks

**Comment by yurem** [comment]
Also I find and fixed this: https://github.com/GluuFederation/oxTrust/commit/39ae095653a0dd7cf465bfdafbe47bf80a4d7342
