### ISSUE TITLE
Inbound SAML not working on Gluu 3.1.3 RC2.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#951]
# Description
The passport service after restart is suppose to generate the metadata for all IDPs registered in this file `/etc/gluu/conf/passport-saml-config.json`.
That is not the case.
The generated metadata is suppose to be under this folder `/opt/gluu/node/passport/server/idp-metadata`. One some instance this folder is not present even after passport service restart.

# Steps to reproduce:
Simply follow the documentation [here](https://gluu.org/docs/ce/authn-guide/inbound-saml-passport/).

# Logs file
  Related logs files can be found under `/opt/gluu/node/passport/server/logs/` directory.

# Sample error message
 `
2018-04-11T09:35:59+0100 [INFO] UMAConfigurations were received
2018-04-11T09:36:00+0100 [ERROR] Error in starting the server. error:-  https://gluu.gasmyr.com/oxauth/restv1/token
`

**Comment by yurem** [comment]
Did you do these point:
> Navigate to Configuration>Manage Authentication > Passport Authentication Method
> Select “Enabled” from Passport Support drop-down list and click “Update”

**Comment by syntrydy** [comment]
yes

**Comment by yurem** [comment]
Can we close this?

**Comment by yurem** [comment]
@syntrydy Can we close it?

**Comment by syntrydy** [comment]
yes
