### ISSUE TITLE
log statements of level lower than INFO not shown after start

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#952]
Environment: RC2/RC3 for 3.1.3 (ubuntu 14)

Suppose these steps:
- Set level to DEBUG
- Restart identity
- Login to oxtrust and do some activity

All statements in log are INFO or ERROR (no DEBUG).

- Set level to TRACE
- Do some activity 

Statements now appear (DEBUG and TRACE)

- Restart identity
- Login to oxtrust and do some activity

Neither DEBUG nor TRACE messages appear (only INFO or ERROR)

In **summary**, when starting it behaves as in INFO level. If changes are made afterwards, it logs correctly.

*Handy tip:*
An easy way to trigger a debug statement (requires scim+uma enabled):
Visit in a browser https://.../identity/restv1/scim/v2/Schemas/urn:ietf:params:scim:schemas:core:2.0:Group

Entry point in code for this action is: https://github.com/GluuFederation/oxTrust/blob/version_3.1.3/server/src/main/java/org/gluu/oxtrust/ws/rs/scim2/SchemaWebService.java#L92
you should be able to see the couple of log statements for this method https://github.com/GluuFederation/oxTrust/blob/version_3.1.3/server/src/main/java/org/gluu/oxtrust/service/scim2/serialization/ScimResourceSerializer.java#L194

**Comment by yurem** [comment]
I've checked this in debugger and in 3.1.3 RC4 after that. It works as expected. here is sample after enabling `DEBUG`:

![default](https://user-images.githubusercontent.com/6104200/38892961-7c64ffac-4291-11e8-8748-856be41a1e37.png)

**Comment by yurem** [comment]
Can you retest it? After changing log level wait 30 seconds to allow oxTrust reload configuration from LDAP.

**Comment by yurem** [comment]
@musta

**Comment by yurem** [comment]
To reproduce it we need to reboot oxTrust/oxAuth.

Also we need to add timer job to check if new loggers have right log level. The system might call some services after startup loggers configuration.

**Comment by yurem** [comment]
Root case of the issue is in dynamic nature of CDI. It creates components when they needed. As result Log  Manager creates loggers with delay (first usage of class). Also it creates them with default setting specified in log4j2.xml. To resolve this issue I added timer job with invocation interval 15 seconds. It find loggers and apply required log level to newly created loggers.

**Comment by yurem** [comment]
I added new log message to indite logger service work. Example:
```
[org.xdi.service.logger.LoggerService] (LoggerService.java:145) - Uppdated log level of '12' loggers to DEBUG
```
