### ISSUE TITLE
Auto-generate client secret

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxTrust#953]
If an OpenID Connect client is being created via the UI, let's offer the ability to randomly generate the client secret. It should be 24 characters long including upper case, lower case letters, numbers, but **no special characters**.  This will ensure strong security. 

![image](https://user-images.githubusercontent.com/5271048/38640524-2223b8a4-3d9a-11e8-98d9-c48bcb8e07fd.png)

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/39096097-f0ec3324-4668-11e8-930f-f9350f758a97.png)

**Comment by yurem** [comment]
It should be simple java script method to generate it.
Also we need:
 - button near to this field to allow regenerate password.
 - button to show/hide password value

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/39265478-fb092b68-48e4-11e8-9bc3-72a6f4ca3c6d.png)

**Comment by shekhar16** [comment]
@yurem Can we close this issue?
