### ISSUE TITLE
SMS OTP with twilio fail somewhere in the script

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#965]
# Description
Authentication using Twilio OTP fail due to some mishandling of the phone number  inside the corresponding interception script.
## Steps to reproduce

Just follow the documentation [here](https://gluu.org/docs/ce/authn-guide/sms-otp/).

**Comment by syntrydy** [comment]
The below PR is intended to fix that issue. 
[This pull request](https://github.com/GluuFederation/oxAuth/pull/786).

**Comment by yurem** [comment]
Merged
