### ISSUE TITLE
Attribute not editable

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#97]
You can't edit the attribute metadata if the attribute is not editable. See 

https://support.gluu.org/view/integrations/memberof-not-listed-in-scopeclaim/2015

**Comment by willow9886** [comment]
Alex also had some notes about editing of attributes in this [support ticket](https://support.gluu.org/view/maintenance/inability-to-change-pre-packaged-attriubutes-properties-via-oxtrust-web-ui/1972).

**Comment by yurem** [comment]
I've added missing `gluuAttributeEditType: admin` to attribute entries.
https://github.com/GluuFederation/community-edition-setup/commit/17bb277e5ae090a1c8f53da6893154857b7426bc

Now all attributes have:
gluuAttributeEditType: admin
gluuAttributeViewType: admin

**Comment by yurem** [comment]
I've opened issue to review user level permissions too: https://github.com/GluuFederation/oxTrust/issues/98
