### ISSUE TITLE
OTP 2FA / enrollment page + login page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#970]
Check out these screenshots: 

- 
![otp_phase_1](https://user-images.githubusercontent.com/7156097/39120793-2267052c-46b5-11e8-8adf-0270f1933762.png)

- 
![otp_page_2](https://user-images.githubusercontent.com/7156097/39120797-250989bc-46b5-11e8-8a2d-54e4c27a92ea.png)

**Comment by syntrydy** [comment]
@mzico I think this issue is not in the right place, should be in the oxAuth project

**Comment by mzico** [comment]
@syntrydy : correct, thanks. 
They are in: /opt/jetty-9.4/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-2910649789493835348.dir/webapp/auth/otp/ ...

**Comment by syntrydy** [comment]
I move this issue in oxAuth project https://github.com/GluuFederation/oxAuth/issues/807
