### ISSUE TITLE
ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] check_ssl retuned an unexpected value

### ISSUE THREAD

**Issue by burcinbozkurt** [GluuFederation/oxTrust#972]
I'm getting check_ssl error issue in v2.4.4.sp2 in CentOS 7. Initially after installation this did not occur, no problem was working properly and now Apache is not starting anymore.

I tried below commands to no avail:

localedef -c -f UTF-8 -i en_US en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

Test follows:
root@keyserver ~]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

[root@keyserver ~]# check_ssl
unable to load certificate
139898384406432:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: TRUSTED CERTIFICATE
Traceback (most recent call last):
  File "/usr/local/bin/check_ssl.py", line 13, in <module>
    time_tup = time.strptime(t, '%b %d %H:%M:%S %Y %Z')
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%b %d %H:%M:%S %Y %Z'
[root@keyserver ~]# locale-gen en_US.utf8
-bash: locale-gen: command not found

The wrapper.log file is in the attachment
[wrapper.log](https://github.com/GluuFederation/oxTrust/files/1954303/wrapper.log)

**Comment by mzico** [comment]
Use support portal for any kind of support related issues.
