### ISSUE TITLE
AuthenticationService.authenticate always returns false for a custom attribute defined in Gluu 

### ISSUE THREAD

**Issue by burcinbozkurt** [GluuFederation/oxTrust#973]
We have a custom authentication script developed in Gluu 2.4.4.sp2 on Centos 7.

We have a custom attribute "ID" that is defined for a person.

def authenticate(self, configurationAttributes, requestParameters, step):
        context = Contexts.getEventContext()
        sessionStateService = SessionStateService.instance()
        sessionState = sessionStateService.getSessionState()
        sessionAttributes = sessionState.getSessionAttributes()
        print "AkisIDExternalAuthenticator. Authenticate. Session State ID: %s" % sessionState.getId()

        context.set("keyOpErrorMsg", "")

        if (step == 1):
            print "AkisIDExternalAuthenticator. Authenticate for step 1"

            ''' Getting captcha from request '''

            logged_in = False
            tckn = eCertificate.getSubject().getSerialNumberAttribute()

            print "TCKN = %s" % tckn
            if (StringHelper.isNotEmptyString(tckn)):
                userService = UserService.instance()
        authenticationService = AuthenticationService.instance()

                #logged_in = userService.authenticate(tckn)
                logged_in = authenticationService.authenticate(tckn)

        print "AuthenticationService is initialized %s" % logged_in
            print "Logged in %s" % logged_in

            if (not logged_in):
                nameSurname = eCertificate.getSubject().getCommonNameAttribute()
                print "NameSurnameFromServer: %s" % nameSurname
                context.set("registerMsg", "Kimlik dogrulama basarisiz !!!")
                context.set("tckk_count_login_steps", 2)
                context.set("tcknFromServer", tckn)
                context.set("nameSurnameFromServer", nameSurname)

            return True

I debug the code and authenticationService.authenticate(tckn) always returns false. The user with the parameter tckn already exists in Gluu and there exists no other exception in the code.

Same holds for userService.authenticate(tckn).

**Comment by mzico** [comment]
@burcinbozkurt : Please use our support portal ( https://support.gluu.org ). Github is only for bug tracking.
