### ISSUE TITLE
Password Reset: Reset link should be send only if the provide email exists in LDAP

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#975]
# Description

During PASSWORD reset, the reset link is send to the provided email address. Actually there is not validation to check if the email exist in Gluu's LDAP.

Password reset link should be send only when there is a user entry with the provided email in ldap.

**Comment by mzico** [comment]
@syntrydy : don't you think it might leak certain 'true' information to crackers? As for example, if Gluu Server 'checks' for valid email_address.. it give a 'green signal' to cracker that... "Yes... this email_address is already here in Gluu Server". 

@yurem : what do you think?

**Comment by sahiliamsso** [comment]
Email validations are done at the backend. User receives link to reset password only when email is registered with GLUU. Otherwise this message is sent in email  “This email address is not on our database of registered users and therefore the attempted password change has failed.”

**Comment by syntrydy** [comment]
That is not the case @sahiliamsso , feel free to test with an unregistered email.
