### ISSUE TITLE
Review default attribute permissions

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#98]
Now all attributes in https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif have:
gluuAttributeEditType: admin
gluuAttributeViewType: admin

We need to review this template file. We should add/remove next attributes:
gluuAttributeEditType: user
gluuAttributeViewType: user

**Comment by nynymike** [comment]
I don't like the idea of user-facing oxTrust anymore...
