### ISSUE TITLE
Enhancement: change the Password Reminder string

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#984]
Please change the string to:

Sorry, the Password Reminder functionality is not enabled. The password recovery e-mail has not been sent.
Please contact the administrator.

![2018-05-12_19h45_27](https://user-images.githubusercontent.com/38302725/39956111-aaaf9b3e-561d-11e8-8b92-8ef7f4ce98de.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/40055693-b44f0e0c-5840-11e8-8936-aa8412580bf5.png)

**Comment by syntrydy** [comment]
@natt-tester loks good?

**Comment by willow9886** [comment]
What does `Instructions letter not sent.` mean?

Would be better if that was more descriptive. In addition, there should be
a line break in between paragraphs for better readability.

Thanks!

**Comment by natt-tester** [comment]
I checked the string yesterday and told @syntrydy to remove the last bit about the instructions letter. I'd assumed it was about a password recovery e-mail, which I then rephrased. Is it ok if it says:

Sorry, the Password Reminder functionality is not enabled. 
The password recovery e-mail has not been sent.
Please contact the administrator. 

@willow9886 ?

**Comment by willow9886** [comment]
yep, much better.

**Comment by syntrydy** [comment]
@natt-tester you can test it. Pull the master branch of  this project , generate new identity.war and use it for testing

**Comment by natt-tester** [comment]
Looks good, @syntrydy. I think we can close it :)
