### ISSUE TITLE
Bug: dead link in Gluu logo

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#985]
Please refer to the GIF from the login page and fix the logo behavior. I believe it should lead back to the login screen :)

![2018-05-11_14h23_15](https://user-images.githubusercontent.com/38302725/39956128-035d36ce-561e-11e8-9017-a06c59b1990a.gif)

**Comment by syntrydy** [comment]
Fix here https://github.com/GluuFederation/oxTrust/pull/988

**Comment by natt-tester** [comment]
It's done :)
