### ISSUE TITLE
Use automate tests to test API insted of manual testing

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#992]
Currently we  have only manual tests in: https://github.com/GluuFederation/oxTrust/tree/master/client/src/main/java/org/gluu/oxtrust/api/test We need to update them to run at build time. There is good example how to do this in [SCIM-Client](https://github.com/GluuFederation/SCIM-Client).

Also proper place for tests in `client/src/test`.

**Comment by syntrydy** [comment]
@yurem There are some pull request waiting that i need before i start working on this issue.

Can you merge them?
