### ISSUE TITLE
Log login initator exception with TRACE level only

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#996]
Here is example of stack trace:
[oxtrust.log](https://github.com/GluuFederation/oxTrust/files/2036866/oxtrust.log)

**Comment by syntrydy** [comment]
This seems to be the same issue as this one https://github.com/GluuFederation/oxTrust/issues/1032

**Comment by syntrydy** [comment]
Fixed here https://github.com/GluuFederation/oxTrust/issues/1032
