### ISSUE TITLE
SCIM2 filter code should build filter graph to allow convert it in any filter type

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#998]
Current SCIM2 filter code tightly depends on LDAP filter syntax. Instead of building filter from string (`org.gluu.search.filter.Filter.create`) it should call org.gluu.search.filter.Filter methods like `createPresenceFilter`, `createEqualityFilter`, etc..

After that this Filter object tree we can convert to either LDAP or SQL filter.

**Comment by jgomer2001** [comment]
Suppose a user with:
```
oxTrustAddresses: {"type":"home","streetAddress":"621 East 6th Street Suite 200",
"locality":"Austin","region":"TX","postalCode":"78701","country":"US","primary":true}
```

In SCIM API one can supply a search filter like 

```
filter=addresses[streetAddress co "East"]
```

Which searches for matches of sub attribute `streetAddress` containing the word `East`. 

This is translated currently to ldap filter `(oxTrustAddresses=*"streetAddress":"*East*"*)`. 

@yurem How to specify this kind of filter using `org.gluu.search.filter.Filter`?  Namely, *some chars* followed by `"streetAddress":"`, followed by *some chars*, followed by `East`, etc. etc.

**Comment by yurem** [comment]
```
		String[] targetArray = new String[] { "\"streetAddress\":\"*East*\"" };
		Filter filter = Filter.createSubstringFilter("oxTrustAddresses", null, targetArray, null);
		System.out.println(filter);
```
Output:
```
(oxTrustAddresses=*"streetAddress":"*East*"*)
```

**Comment by yurem** [comment]
Can we close it?
